In [1]:
import pandas as pd
import numpy as np
import re,yaml,os
import itertools as it
import networkx as nx
def ding():
    os.system('afplay /System/Library/Sounds/Submarine.aiff')

In [2]:
pd.__version__
%store -r num
# num=0
print(num)

2

In [3]:
rep="/Volumes/BroadExt/sDrive/Recherche/Boye/HDR/Data/vlexique2.0.3/WordStructure/"
fParadigmes="vlexique2-S%d.csv"%num
paradigmes=pd.read_csv(rep+fParadigmes,sep=";",encoding="utf8")

In [4]:
cols=paradigmes.columns.tolist()
cases=cols[2:]
print ", ".join(cases)

ai1S, ai2P, ai2S, ai3P, ai3S, fi1P, fi1S, fi2P, fi2S, fi3P, fi3S, ii1P, ii1S, ii2P, ii2S, ii3P, ii3S, inf, is1P, is1S, is2P, is2S, is3P, is3S, pI1P, pI2P, pI2S, pP, pc1P, pc1S, pc2P, pc2S, pc3P, pc3S, pi1P, pi1S, pi2P, pi2S, pi3P, pi3S, ppFP, ppFS, ppMP, ppMS, ps1P, ps1S, ps2P, ps2S, ps3P, ps3S

In [5]:
for c in cases:
    display(paradigmes[[c]].dropna().head(1))

      ai1S
1  abâdOnE

    ai2P
351   yt

      ai2S
92  afEbli

       ai3P
1  abâdOnEr

    ai3S
0  abEsa

      fi1P
0  abEs6rô

      fi1S
0  abEs6rE

        fi2P
1  abâdOn6re

      fi2S
0  abEs6ra

      fi3P
0  abEs6rô

      fi3S
0  abEs6ra

       ii1P
1  abâdOnjô

    ii1S
0  abEsE

       ii2P
1  abâdOnje

      ii2S
1  abâdOnE

    ii3P
0  abEsE

    ii3S
0  abEsE

     inf
0  abEse

       is1P
120  aZisjô

       is1S
39  akôplis

       is2P
120  aZisje

     is2S
120  aZis

    is3P
351   ys

    is3S
142  Ema

    pI1P
0  abEsô

    pI2P
0  abEse

   pI2S
0  abEs

      pP
0  abEsâ

         pc1P
1  abâdOn6rjô

      pc1S
0  abEs6rE

       pc2P
0  abEs6rje

      pc2S
0  abEs6rE

      pc3P
0  abEs6rE

      pc3S
0  abEs6rE

    pi1P
0  abEsô

   pi1S
0  abEs

    pi2P
0  abEse

   pi2S
0  abEs

   pi3P
0  abEs

   pi3S
0  abEs

    ppFP
0  abEse

    ppFS
0  abEse

    ppMP
0  abEse

    ppMS
0  abEse

       ps1P
1  abâdOnjô

   ps1S
0  abEs

       ps2P
1  abâdOnje

   ps2S
0  abEs

   ps3P
0  abEs

   ps3S
0  abEs

In [6]:
g=nx.Graph()
for (c1,c2) in it.combinations(cases, 2):
    c1Val=paradigmes[c1].notnull()
    c2Val=paradigmes[c2].notnull()
    incompatibles=paradigmes[c1Val & c2Val & (paradigmes[c1]!=paradigmes[c2])][[c1,c2]]
    compatibles=paradigmes[c1Val & c2Val & (paradigmes[c1]==paradigmes[c2])][[c1,c2]]
    if len(incompatibles)==0 and len(compatibles)>0:
        g.add_edge(c1,c2,weight=len(compatibles))
cliques=list(nx.find_cliques(g))

In [7]:
cliques=sorted(cliques, key=len, reverse=True)
print(cliques[0])
maxLenClique=len(cliques[0])
wCliques=(cliques[:])

[u'ii1S', u'ii3P', u'ii2S']

In [8]:
syncretismes=[]
syncretiques=set()

def cleanCliques(lCliques):
    sCases=set(sum(lCliques,[]))
    syncretiques.update(sCases)
    for c in lCliques:
        wCliques.remove(c)
    for c in sCases:
        for w in wCliques:
            if c in w:
                w.remove(c)
    return
                

def addCliques(length):
    conflits=[]
    lCliques=[x for x in cliques if len(x)==length]
    if len(lCliques)>1:
        for (c1,c2) in it.combinations(lCliques, 2):
            inter=set(c1).intersection(set(c2))
            if inter:
                conflits.append([c1,c2])
    if conflits:
        ajouts=[]
        for c in lCliques:
            noConflit=True
            for conflit in conflits:
                if c in conflit:
                    noConflit=False
            if noConflit:
                ajouts.append(c)
        syncretismes.extend(ajouts)
        cleanCliques(ajouts)
        for c1,c2 in conflits:
            sC1=set(c1)
            sC2=set(c2)
            pivot=list(sC1.intersection(sC2))[0]
            dC1=sC1.difference(sC2)
            wC1=sum(g[pivot][c]["weight"] for c in dC1)
            dC2=sC2.difference(sC1)
            wC2=sum(g[pivot][c]["weight"] for c in dC2)
            print c1,wC1,c2,wC2
    else:
        syncretismes.extend(lCliques)
        cleanCliques(lCliques)
    return

In [9]:
for i in range(maxLenClique):
    print(maxLenClique-i)
    addCliques(maxLenClique-i)
syncretismes,syncretiques,wCliques

3
2
1

([[u'ii1S', u'ii3P', u'ii2S'],
  [u'ps2S', u'ps3S', u'ps1S'],
  [u'is2S', u'is1S', u'is3P'],
  [u'ai3S', u'ai2S', u'is3S'],
  [u'ppMS', u'ppMP'],
  [u'ps3P']],
 {u'ai2S',
  u'ai3S',
  u'ii1S',
  u'ii2S',
  u'ii3P',
  u'is1S',
  u'is2S',
  u'is3P',
  u'is3S',
  u'ppMP',
  u'ppMS',
  u'ps1S',
  u'ps2S',
  u'ps3P',
  u'ps3S'},
 [])

In [10]:
dExpansion={s[0]:s for s in syncretismes if len(s)>1}
dExpansion

{u'ai3S': [u'ai3S', u'ai2S', u'is3S'],
 u'ii1S': [u'ii1S', u'ii3P', u'ii2S'],
 u'is2S': [u'is2S', u'is1S', u'is3P'],
 u'ppMS': [u'ppMS', u'ppMP'],
 u'ps2S': [u'ps2S', u'ps3S', u'ps1S']}

In [11]:
if "fi2S" in dExpansion:
    if "fi3S" in dExpansion["fi2S"]:
        dExpansion[u"fi3S"]=dExpansion.pop("fi2S")
if "ii1S" in dExpansion:
    if "ii3S" in dExpansion["ii1S"]:
        dExpansion[u"ii3S"]=dExpansion.pop("ii1S")
if "pc2S" in dExpansion:
    if "pc3S" in dExpansion["pc2S"]:
        dExpansion[u"pc3S"]=dExpansion.pop("pc2S")
if "ps2S" in dExpansion:
    if "ps3S" in dExpansion["ps2S"]:
        dExpansion[u"ps3S"]=dExpansion.pop("ps2S")        
if "pi2S" in dExpansion:
    if "pi3S" in dExpansion["pi2S"]:
        dExpansion[u"pi3S"]=dExpansion.pop("pi2S")
if "ppMP" in dExpansion:
    if "ppMS" in dExpansion["ppMP"]:
        dExpansion[u"ppMS"]=dExpansion.pop("ppMP")

In [12]:
dExpansion

{u'ai3S': [u'ai3S', u'ai2S', u'is3S'],
 u'ii1S': [u'ii1S', u'ii3P', u'ii2S'],
 u'is2S': [u'is2S', u'is1S', u'is3P'],
 u'ppMS': [u'ppMS', u'ppMP'],
 u'ps3S': [u'ps2S', u'ps3S', u'ps1S']}

In [13]:
omps=paradigmes[[c for c in cols if c not in syncretiques]].copy()

In [14]:
def fusionFormes(row):
    result=np.nan
    for c in row:
        if c==c:
            result=c
            break
    return result

In [15]:
# paradigmes[["ppMS","ppMP"]].apply(fusionFormes,axis=1)

In [16]:
for s in dExpansion:
    print s,dExpansion[s]
    omps[s]=paradigmes[dExpansion[s]].apply(fusionFormes,axis=1)

ppMS [u'ppMS', u'ppMP']
ii1S [u'ii1S', u'ii3P', u'ii2S']
is2S [u'is2S', u'is1S', u'is3P']
ai3S [u'ai3S', u'ai2S', u'is3S']
ps3S [u'ps2S', u'ps3S', u'ps1S']

In [17]:
with open(rep+fParadigmes.replace(".csv","-omp.yaml"),"w") as outFile:
    yaml.safe_dump(dExpansion,outFile)

In [18]:
omps.dropna(thresh=3).to_csv(rep+fParadigmes.replace(".csv","-omp.csv"),encoding="utf8",sep=";",index=None)

In [19]:
if num<8:
    num+=1
else:
    num=0
    ding()
    ding()
    ding()
%store num

Stored 'num' (int)