In [96]:
import pandas as pd
import numpy as np
import re,yaml,os
import itertools as it
import networkx as nx
def ding():
    os.system('afplay /System/Library/Sounds/Submarine.aiff')

In [97]:
pd.__version__
%store -r numOMP
num=numOMP
num=6
print(num)

6

In [98]:
rep="/Volumes/BroadExt/sDrive/Recherche/Boye/HDR/Data/vlexique2.0.3/WordStructure/"
rep="/Users/gilles/sDrive/Recherche/Boye/HDR/Data/vlexique2.0.3/WordStructure/"
fParadigmes="vlexique2-CV3-Test%d.csv"%num
fParadigmes="vlexique2-S%d.csv"%num
seuilCompatibilite=10
paradigmes=pd.read_csv(rep+fParadigmes,sep=";",encoding="utf8")

In [99]:
cols=paradigmes.columns.tolist()
cases=cols[:]
cases.remove("lexeme")
print(len(cases),", ".join(cases))

50 ai1P, ai1S, ai2P, ai2S, ai3P, ai3S, fi1P, fi1S, fi2P, fi2S, fi3P, fi3S, ii1P, ii1S, ii2P, ii2S, ii3P, ii3S, inf, is1S, is2P, is2S, is3P, is3S, pI1P, pI2P, pI2S, pP, pc1P, pc1S, pc2P, pc2S, pc3P, pc3S, pi1P, pi1S, pi2P, pi2S, pi3P, pi3S, ppFP, ppFS, ppMP, ppMS, ps1P, ps1S, ps2P, ps2S, ps3P, ps3S

for c in cases:
    display(paradigmes[[c]].dropna().head(1))

In [100]:
g=nx.Graph()
for (c1,c2) in it.combinations(cases, 2):
    c1SimpleVal=(paradigmes[c1].notnull())&(~paradigmes[c1].str.contains(",",na=False))
    c2SimpleVal=(paradigmes[c2].notnull())&(~paradigmes[c2].str.contains(",",na=False))
    
    incompatiblesSimples=paradigmes[c1SimpleVal & c2SimpleVal & (paradigmes[c1]!=paradigmes[c2])][[c1,c2]]
    compatiblesSimples=paradigmes[c1SimpleVal & c2SimpleVal & (paradigmes[c1]==paradigmes[c2])][[c1,c2]]
    
    nbIncompatibles=len(incompatiblesSimples)
    nbCompatibles=len(compatiblesSimples)
    # print(c1,c2,nbIncompatibles,nbCompatibles)
    
    c1MultipleVal=((paradigmes[c1].notnull())&(paradigmes[c2].notnull())&(paradigmes[c1].str.contains(",",na=False)))
    c2MultipleVal=((paradigmes[c1].notnull())&(paradigmes[c2].notnull())&(paradigmes[c2].str.contains(",",na=False)))
    multiples=paradigmes[c1MultipleVal|c2MultipleVal][[c1,c2]].apply(lambda x: x.str.split(',')).explode(c1).explode(c2)
    
    if len(multiples)>0:
        compatiblesMultiples=multiples[multiples[c1]==multiples[c2]][[c1,c2]]
        display(multiples,compatiblesMultiples)
        nbCompatiblesMultiples=len(compatiblesMultiples.index.unique())
        if nbCompatiblesMultiples==len(multiples.index.unique()):
            # display(compatiblesMultiples)
            nbCompatibles+=len(compatiblesMultiples)
        else:
            nbIncompatibles+=len(multiples.index.unique())-len(compatiblesMultiples.index.unique())
    
    # print(c1,c2,nbIncompatibles,nbCompatibles)
    
    if nbIncompatibles==0 and nbCompatibles>=seuilCompatibilite:
        g.add_edge(c1,c2,weight=len(compatibles))
cliques=list(nx.find_cliques(g))

ai1P ai1S 8 0
ai1P ai2P 1 0
ai1P ai2S 3 0
ai1P ai3P 8 0
ai1P ai3S 7 0
ai1P fi1P 8 0
ai1P fi1S 8 0
ai1P fi2P 8 0
ai1P fi2S 8 0
ai1P fi3P 8 0
ai1P fi3S 8 0
ai1P ii1P 8 0
ai1P ii1S 8 0
ai1P ii2P 7 0
ai1P ii2S 8 0
ai1P ii3P 8 0
ai1P ii3S 8 0
ai1P inf 8 0
ai1P is1S 2 0
ai1P is2P 0 0
ai1P is2S 0 0
ai1P is3P 1 0
ai1P is3S 3 0
ai1P pI1P 8 0
ai1P pI2P 7 0
ai1P pI2S 8 0
ai1P pP 8 0
ai1P pc1P 8 0
ai1P pc1S 8 0
ai1P pc2P 8 0
ai1P pc2S 8 0
ai1P pc3P 8 0
ai1P pc3S 8 0
ai1P pi1P 8 0
ai1P pi1S 8 0
ai1P pi2P 8 0
ai1P pi2S 8 0
ai1P pi3P 8 0
ai1P pi3S 8 0
ai1P ppFP 7 0
ai1P ppFS 7 0
ai1P ppMP 7 0
ai1P ppMS 8 0
ai1P ps1P 8 0
ai1P ps1S 7 0
ai1P ps2P 7 0
ai1P ps2S 8 0
ai1P ps3P 7 0
ai1P ps3S 7 0
ai1S ai2P 2 0
ai1S ai2S 0 6
ai1S ai3P 54 0
ai1S ai3S 31 36

       ai1S     fi1P
1412  EsEjE  EsEj6rô
1412  EsEjE    EsErô

Empty DataFrame
Columns: [ai1S, fi1P]
Index: []

ai1S fi1P 61 0

       ai1S     fi1S
234     asi   asjErE
234     asi   aswarE
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE

Empty DataFrame
Columns: [ai1S, fi1S]
Index: []

ai1S fi1S 70 0

       ai1S     fi2P
1412  EsEjE  EsEj6re
1412  EsEjE    EsEre

Empty DataFrame
Columns: [ai1S, fi2P]
Index: []

ai1S fi2P 67 0

       ai1S     fi2S
1412  EsEjE  EsEj6ra
1412  EsEjE    EsEra

Empty DataFrame
Columns: [ai1S, fi2S]
Index: []

ai1S fi2S 67 0

       ai1S     fi3P
1412  EsEjE  EsEj6rô
1412  EsEjE    EsErô

Empty DataFrame
Columns: [ai1S, fi3P]
Index: []

ai1S fi3P 69 0

       ai1S     fi3S
234     asi   asjEra
234     asi   aswara
1412  EsEjE  EsEj6ra
1412  EsEjE    EsEra

Empty DataFrame
Columns: [ai1S, fi3S]
Index: []

ai1S fi3S 72 0
ai1S ii1P 51 0
ai1S ii1S 39 33
ai1S ii2P 56 0
ai1S ii2S 35 31
ai1S ii3P 38 32
ai1S ii3S 41 33
ai1S inf 74 0
ai1S is1S 2 0
ai1S is2P 0 0
ai1S is2S 0 0
ai1S is3P 1 0
ai1S is3S 0 3
ai1S pI1P 62 0

    ai1S    pI2P
234  asi   asEje
234  asi  aswaje

Empty DataFrame
Columns: [ai1S, pI2P]
Index: []

ai1S pI2P 71 0

      ai1S  pI2S
234    asi  asje
234    asi  aswa
3391  vuly    v2
3391  vuly   v9j

Empty DataFrame
Columns: [ai1S, pI2S]
Index: []

ai1S pI2S 65 7
ai1S pP 73 0
ai1S pc1P 24 0

       ai1S     pc1S
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE

Empty DataFrame
Columns: [ai1S, pc1S]
Index: []

ai1S pc1S 68 0

       ai1S      pc2P
1412  EsEjE  EsEj6rje
1412  EsEjE    EsErje

Empty DataFrame
Columns: [ai1S, pc2P]
Index: []

ai1S pc2P 55 0

       ai1S     pc2S
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE

Empty DataFrame
Columns: [ai1S, pc2S]
Index: []

ai1S pc2S 63 0

       ai1S     pc3P
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE

Empty DataFrame
Columns: [ai1S, pc3P]
Index: []

ai1S pc3P 57 0

       ai1S     pc3S
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE

Empty DataFrame
Columns: [ai1S, pc3S]
Index: []

ai1S pc3S 70 0
ai1S pi1P 70 0

     ai1S  pi1S
234   asi  asje
234   asi  aswa
1721   ai     E
1721   ai    ai

     ai1S pi1S
1721   ai   ai

ai1S pi1S 67 6
ai1S pi2P 73 0

     ai1S  pi2S
234   asi  asje
234   asi  aswa
1721   ai     E
1721   ai    ai

     ai1S pi2S
1721   ai   ai

ai1S pi2S 66 5

    ai1S  pi3P
234  asi  asEj
234  asi  aswa

Empty DataFrame
Columns: [ai1S, pi3P]
Index: []

ai1S pi3P 74 0

     ai1S  pi3S
234   asi  asje
234   asi  aswa
1721   ai     E
1721   ai    ai

     ai1S pi3S
1721   ai   ai

ai1S pi3S 67 6
ai1S ppFP 52 14
ai1S ppFS 54 17
ai1S ppMP 44 23
ai1S ppMS 47 27
ai1S ps1P 43 0

    ai1S  ps1S
234  asi  asEj
234  asi  aswa

Empty DataFrame
Columns: [ai1S, ps1S]
Index: []

ai1S ps1S 67 0
ai1S ps2P 64 0

    ai1S  ps2S
234  asi  asEj
234  asi  aswa

Empty DataFrame
Columns: [ai1S, ps2S]
Index: []

ai1S ps2S 70 0
ai1S ps3P 66 0

    ai1S  ps3S
234  asi  asEj
234  asi  aswa

Empty DataFrame
Columns: [ai1S, ps3S]
Index: []

ai1S ps3S 72 0
ai2P ai2S 1 0
ai2P ai3P 2 0
ai2P ai3S 2 0
ai2P fi1P 2 0
ai2P fi1S 2 0
ai2P fi2P 2 0
ai2P fi2S 2 0
ai2P fi3P 2 0
ai2P fi3S 2 0
ai2P ii1P 2 0
ai2P ii1S 2 0
ai2P ii2P 2 0
ai2P ii2S 2 0
ai2P ii3P 2 0
ai2P ii3S 2 0
ai2P inf 2 0
ai2P is1S 1 0
ai2P is2P 0 0
ai2P is2S 0 0
ai2P is3P 1 0
ai2P is3S 1 0
ai2P pI1P 2 0
ai2P pI2P 1 1
ai2P pI2S 2 0
ai2P pP 2 0
ai2P pc1P 2 0
ai2P pc1S 2 0
ai2P pc2P 2 0
ai2P pc2S 2 0
ai2P pc3P 2 0
ai2P pc3S 2 0
ai2P pi1P 2 0
ai2P pi1S 2 0
ai2P pi2P 1 1
ai2P pi2S 2 0
ai2P pi3P 2 0
ai2P pi3S 2 0
ai2P ppFP 0 1
ai2P ppFS 0 1
ai2P ppMP 1 0
ai2P ppMS 2 0
ai2P ps1P 2 0
ai2P ps1S 2 0
ai2P ps2P 2 0
ai2P ps2S 2 0
ai2P ps3P 2 0
ai2P ps3S 2 0
ai2S ai3P 3 0
ai2S ai3S 0 7
ai2S fi1P 5 0
ai2S fi1S 7 0
ai2S fi2P 7 0
ai2S fi2S 7 0
ai2S fi3P 7 0
ai2S fi3S 7 0
ai2S ii1P 3 0
ai2S ii1S 7 0
ai2S ii2P 3 0
ai2S ii2S 7 0
ai2S ii3P 6 0
ai2S ii3S 8 0
ai2S inf 9 0
ai2S is1S 1 0
ai2S is2P 0 0
ai2S is2S 0 0
ai2S is3P 1 0
ai2S is3S 0 2
ai2S pI1P 4 0
ai2S pI2P 7 0
ai2S pI2S 3 5
ai2S pP 9 0
ai2S pc1P 3 0
ai2S pc1S 6 0
ai2S pc2P 4 0
ai2S pc2S 5 0
ai2S pc3P 5 0
ai2S pc3S 7 0
ai2S pi1P 5 0
ai2S pi1S 3 5
ai2S pi2P 8 0
ai2S pi2S 3 5
ai2S pi3P 8 1
ai2S pi3S 3 6
ai2S ppFP 2 1
ai2S ppFS 2 2
ai2S ppMP 2 2
ai2S ppMS 3 6
ai2S ps1P 3 0
ai2S ps1S 5 0
ai2S ps2P 4 0
ai2S ps2S 6 0
ai2S ps3P 5 1
ai2S ps3S 6 1
ai3P ai3S 112 0

        ai3P     fi1P
1412  EsEjEr  EsEj6rô
1412  EsEjEr    EsErô

Empty DataFrame
Columns: [ai3P, fi1P]
Index: []

ai3P fi1P 111 0

        ai3P     fi1S
1412  EsEjEr  EsEj6rE
1412  EsEjEr    EsErE

Empty DataFrame
Columns: [ai3P, fi1S]
Index: []

ai3P fi1S 117 0

        ai3P     fi2P
1412  EsEjEr  EsEj6re
1412  EsEjEr    EsEre

Empty DataFrame
Columns: [ai3P, fi2P]
Index: []

ai3P fi2P 109 0

        ai3P     fi2S
1412  EsEjEr  EsEj6ra
1412  EsEjEr    EsEra

Empty DataFrame
Columns: [ai3P, fi2S]
Index: []

ai3P fi2S 106 0

        ai3P     fi3P
1412  EsEjEr  EsEj6rô
1412  EsEjEr    EsErô

Empty DataFrame
Columns: [ai3P, fi3P]
Index: []

ai3P fi3P 119 0

        ai3P     fi3S
1412  EsEjEr  EsEj6ra
1412  EsEjEr    EsEra

Empty DataFrame
Columns: [ai3P, fi3S]
Index: []

ai3P fi3S 121 0
ai3P ii1P 64 0
ai3P ii1S 108 0
ai3P ii2P 79 0
ai3P ii2S 98 0
ai3P ii3P 117 0
ai3P ii3S 120 0
ai3P inf 106 15
ai3P is1S 3 0
ai3P is2P 3 0
ai3P is2S 2 0
ai3P is3P 1 0
ai3P is3S 4 0
ai3P pI1P 108 0
ai3P pI2P 114 0

       ai3P pI2S
3391  vulyr   v2
3391  vulyr  v9j

Empty DataFrame
Columns: [ai3P, pI2S]
Index: []

ai3P pI2S 113 0
ai3P pP 119 0
ai3P pc1P 28 0

        ai3P     pc1S
1412  EsEjEr  EsEj6rE
1412  EsEjEr    EsErE

Empty DataFrame
Columns: [ai3P, pc1S]
Index: []

ai3P pc1S 106 0

        ai3P      pc2P
1412  EsEjEr  EsEj6rje
1412  EsEjEr    EsErje

Empty DataFrame
Columns: [ai3P, pc2P]
Index: []

ai3P pc2P 76 0

        ai3P     pc2S
1412  EsEjEr  EsEj6rE
1412  EsEjEr    EsErE

Empty DataFrame
Columns: [ai3P, pc2S]
Index: []

ai3P pc2S 90 0

        ai3P     pc3P
1412  EsEjEr  EsEj6rE
1412  EsEjEr    EsErE

Empty DataFrame
Columns: [ai3P, pc3P]
Index: []

ai3P pc3P 87 0

        ai3P     pc3S
1412  EsEjEr  EsEj6rE
1412  EsEjEr    EsErE

Empty DataFrame
Columns: [ai3P, pc3S]
Index: []

ai3P pc3S 115 0
ai3P pi1P 114 0

     ai3P pi1S
2358  pyr   p2
2358  pyr  pHi

Empty DataFrame
Columns: [ai3P, pi1S]
Index: []

ai3P pi1S 118 0
ai3P pi2P 117 0
ai3P pi2S 116 0
ai3P pi3P 121 0
ai3P pi3S 121 0
ai3P ppFP 107 0
ai3P ppFS 112 0
ai3P ppMP 108 0
ai3P ppMS 121 0
ai3P ps1P 53 0
ai3P ps1S 107 0
ai3P ps2P 96 0
ai3P ps2S 107 0
ai3P ps3P 115 0
ai3P ps3S 120 0

       ai3S     fi1P
1412  EsEja  EsEj6rô
1412  EsEja    EsErô
2232   pEja   pEj6rô
2232   pEja     pErô

Empty DataFrame
Columns: [ai3S, fi1P]
Index: []

ai3S fi1P 220 0

       ai3S     fi1S
234     asi   asjErE
234     asi   aswarE
1412  EsEja  EsEj6rE
1412  EsEja    EsErE
2232   pEja   pEj6rE
2232   pEja     pErE

Empty DataFrame
Columns: [ai3S, fi1S]
Index: []

ai3S fi1S 321 0

       ai3S     fi2P
1412  EsEja  EsEj6re
1412  EsEja    EsEre
2232   pEja   pEj6re
2232   pEja     pEre

Empty DataFrame
Columns: [ai3S, fi2P]
Index: []

ai3S fi2P 240 0

       ai3S     fi2S
1412  EsEja  EsEj6ra
1412  EsEja    EsEra
2232   pEja   pEj6ra
2232   pEja     pEra

Empty DataFrame
Columns: [ai3S, fi2S]
Index: []

ai3S fi2S 234 0

       ai3S     fi3P
1412  EsEja  EsEj6rô
1412  EsEja    EsErô
2232   pEja   pEj6rô
2232   pEja     pErô

Empty DataFrame
Columns: [ai3S, fi3P]
Index: []

ai3S fi3P 286 0

       ai3S     fi3S
234     asi   asjEra
234     asi   aswara
1412  EsEja  EsEj6ra
1412  EsEja    EsEra
2232   pEja   pEj6ra
2232   pEja     pEra

Empty DataFrame
Columns: [ai3S, fi3S]
Index: []

ai3S fi3S 367 0
ai3S ii1P 92 0
ai3S ii1S 281 0
ai3S ii2P 134 0
ai3S ii2S 190 0
ai3S ii3P 285 0
ai3S ii3S 363 0
ai3S inf 384 0
ai3S is1S 2 0
ai3S is2P 0 0
ai3S is2S 0 0
ai3S is3P 1 0
ai3S is3S 0 4
ai3S pI1P 249 0

    ai3S    pI2P
234  asi   asEje
234  asi  aswaje

Empty DataFrame
Columns: [ai3S, pI2P]
Index: []

ai3S pI2P 339 0

      ai3S  pI2S
234    asi  asje
234    asi  aswa
3391  vuly    v2
3391  vuly   v9j

Empty DataFrame
Columns: [ai3S, pI2S]
Index: []

ai3S pI2S 327 12
ai3S pP 354 0
ai3S pc1P 31 0

       ai3S     pc1S
1412  EsEja  EsEj6rE
1412  EsEja    EsErE
2232   pEja   pEj6rE
2232   pEja     pErE

Empty DataFrame
Columns: [ai3S, pc1S]
Index: []

ai3S pc1S 247 0

       ai3S      pc2P
1412  EsEja  EsEj6rje
1412  EsEja    EsErje
2232   pEja   pEj6rje
2232   pEja     pErje

Empty DataFrame
Columns: [ai3S, pc2P]
Index: []

ai3S pc2P 124 0

       ai3S     pc2S
1412  EsEja  EsEj6rE
1412  EsEja    EsErE
2232   pEja   pEj6rE
2232   pEja     pErE

Empty DataFrame
Columns: [ai3S, pc2S]
Index: []

ai3S pc2S 157 0

       ai3S     pc3P
1412  EsEja  EsEj6rE
1412  EsEja    EsErE
2232   pEja   pEj6rE
2232   pEja     pErE

Empty DataFrame
Columns: [ai3S, pc3P]
Index: []

ai3S pc3P 138 0

       ai3S     pc3S
1412  EsEja  EsEj6rE
1412  EsEja    EsErE
2232   pEja   pEj6rE
2232   pEja     pErE

Empty DataFrame
Columns: [ai3S, pc3S]
Index: []

ai3S pc3S 311 0
ai3S pi1P 285 0

     ai3S  pi1S
234   asi  asje
234   asi  aswa
2358   py    p2
2358   py   pHi

Empty DataFrame
Columns: [ai3S, pi1S]
Index: []

ai3S pi1S 348 13
ai3S pi2P 341 0

    ai3S  pi2S
234  asi  asje
234  asi  aswa

Empty DataFrame
Columns: [ai3S, pi2S]
Index: []

ai3S pi2S 338 11

    ai3S  pi3P
234  asi  asEj
234  asi  aswa

Empty DataFrame
Columns: [ai3S, pi3P]
Index: []

ai3S pi3P 371 3

    ai3S  pi3S
234  asi  asje
234  asi  aswa

Empty DataFrame
Columns: [ai3S, pi3S]
Index: []

ai3S pi3S 367 17
ai3S ppFP 264 29
ai3S ppFS 301 35
ai3S ppMP 274 45
ai3S ppMS 318 66
ai3S ps1P 58 0

    ai3S  ps1S
234  asi  asEj
234  asi  aswa

Empty DataFrame
Columns: [ai3S, ps1S]
Index: []

ai3S ps1S 269 1
ai3S ps2P 178 0

    ai3S  ps2S
234  asi  asEj
234  asi  aswa

Empty DataFrame
Columns: [ai3S, ps2S]
Index: []

ai3S ps2S 244 1
ai3S ps3P 244 2

    ai3S  ps3S
234  asi  asEj
234  asi  aswa

Empty DataFrame
Columns: [ai3S, ps3S]
Index: []

ai3S ps3S 356 3

         fi1P     fi1S
1412  EsEj6rô  EsEj6rE
1412  EsEj6rô    EsErE
1412    EsErô  EsEj6rE
1412    EsErô    EsErE
2232   pEj6rô   pEj6rE
2232   pEj6rô     pErE
2232     pErô   pEj6rE
2232     pErô     pErE

Empty DataFrame
Columns: [fi1P, fi1S]
Index: []

fi1P fi1S 308 0

         fi1P     fi2P
1412  EsEj6rô  EsEj6re
1412  EsEj6rô    EsEre
1412    EsErô  EsEj6re
1412    EsErô    EsEre
2232   pEj6rô   pEj6re
2232   pEj6rô     pEre
2232     pErô   pEj6re
2232     pErô     pEre

Empty DataFrame
Columns: [fi1P, fi2P]
Index: []

fi1P fi2P 267 0

         fi1P     fi2S
1412  EsEj6rô  EsEj6ra
1412  EsEj6rô    EsEra
1412    EsErô  EsEj6ra
1412    EsErô    EsEra
2232   pEj6rô   pEj6ra
2232   pEj6rô     pEra
2232     pErô   pEj6ra
2232     pErô     pEra

Empty DataFrame
Columns: [fi1P, fi2S]
Index: []

fi1P fi2S 247 0

         fi1P     fi3P
1412  EsEj6rô  EsEj6rô
1412  EsEj6rô    EsErô
1412    EsErô  EsEj6rô
1412    EsErô    EsErô
2232   pEj6rô   pEj6rô
2232   pEj6rô     pErô
2232     pErô   pEj6rô
2232     pErô     pErô

         fi1P     fi3P
1412  EsEj6rô  EsEj6rô
1412    EsErô    EsErô
2232   pEj6rô   pEj6rô
2232     pErô     pErô

fi1P fi3P 0 284

         fi1P     fi3S
1412  EsEj6rô  EsEj6ra
1412  EsEj6rô    EsEra
1412    EsErô  EsEj6ra
1412    EsErô    EsEra
2232   pEj6rô   pEj6ra
2232   pEj6rô     pEra
2232     pErô   pEj6ra
2232     pErô     pEra

Empty DataFrame
Columns: [fi1P, fi3S]
Index: []

fi1P fi3S 322 0

         fi1P   ii1P
1412  EsEj6rô  EsEjô
1412    EsErô  EsEjô

Empty DataFrame
Columns: [fi1P, ii1P]
Index: []

fi1P ii1P 97 0

         fi1P   ii1S
1412  EsEj6rô  EsEjE
1412    EsErô  EsEjE
2232   pEj6rô   pEjE
2232     pErô   pEjE

Empty DataFrame
Columns: [fi1P, ii1S]
Index: []

fi1P ii1S 260 0

         fi1P   ii2P
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi1P, ii2P]
Index: []

fi1P ii2P 135 0

         fi1P   ii2S
1412  EsEj6rô  EsEjE
1412    EsErô  EsEjE
2232   pEj6rô   pEjE
2232     pErô   pEjE

Empty DataFrame
Columns: [fi1P, ii2S]
Index: []

fi1P ii2S 185 0

         fi1P   ii3P
1412  EsEj6rô  EsEjE
1412    EsErô  EsEjE
2232   pEj6rô   pEjE
2232     pErô   pEjE

Empty DataFrame
Columns: [fi1P, ii3P]
Index: []

fi1P ii3P 257 0

         fi1P   ii3S
1412  EsEj6rô  EsEjE
1412    EsErô  EsEjE
2232   pEj6rô   pEjE
2232     pErô   pEjE

Empty DataFrame
Columns: [fi1P, ii3S]
Index: []

fi1P ii3S 309 0

         fi1P    inf
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi1P, inf]
Index: []

fi1P inf 322 0
fi1P is1S 3 0
fi1P is2P 4 0
fi1P is2S 2 0
fi1P is3P 1 0
fi1P is3S 4 0

         fi1P   pI1P
1412  EsEj6rô  EsEjô
1412    EsErô  EsEjô
2232   pEj6rô   pEjô
2232     pErô   pEjô

Empty DataFrame
Columns: [fi1P, pI1P]
Index: []

fi1P pI1P 258 0

         fi1P   pI2P
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi1P, pI2P]
Index: []

fi1P pI2P 305 0

         fi1P  pI2S
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
2232   pEj6rô   pEj
2232     pErô   pEj
3391    vudrô    v2
3391    vudrô   v9j

Empty DataFrame
Columns: [fi1P, pI2S]
Index: []

fi1P pI2S 297 0

         fi1P     pP
1412  EsEj6rô  EsEjâ
1412    EsErô  EsEjâ
2232   pEj6rô   pEjâ
2232     pErô   pEjâ

Empty DataFrame
Columns: [fi1P, pP]
Index: []

fi1P pP 302 0
fi1P pc1P 34 0

         fi1P     pc1S
1412  EsEj6rô  EsEj6rE
1412  EsEj6rô    EsErE
1412    EsErô  EsEj6rE
1412    EsErô    EsErE
2232   pEj6rô   pEj6rE
2232   pEj6rô     pErE
2232     pErô   pEj6rE
2232     pErô     pErE

Empty DataFrame
Columns: [fi1P, pc1S]
Index: []

fi1P pc1S 243 0

         fi1P      pc2P
1412  EsEj6rô  EsEj6rje
1412  EsEj6rô    EsErje
1412    EsErô  EsEj6rje
1412    EsErô    EsErje
2232   pEj6rô   pEj6rje
2232   pEj6rô     pErje
2232     pErô   pEj6rje
2232     pErô     pErje

Empty DataFrame
Columns: [fi1P, pc2P]
Index: []

fi1P pc2P 124 0

         fi1P     pc2S
1412  EsEj6rô  EsEj6rE
1412  EsEj6rô    EsErE
1412    EsErô  EsEj6rE
1412    EsErô    EsErE
2232   pEj6rô   pEj6rE
2232   pEj6rô     pErE
2232     pErô   pEj6rE
2232     pErô     pErE

Empty DataFrame
Columns: [fi1P, pc2S]
Index: []

fi1P pc2S 161 0

         fi1P     pc3P
1412  EsEj6rô  EsEj6rE
1412  EsEj6rô    EsErE
1412    EsErô  EsEj6rE
1412    EsErô    EsErE
2232   pEj6rô   pEj6rE
2232   pEj6rô     pErE
2232     pErô   pEj6rE
2232     pErô     pErE

Empty DataFrame
Columns: [fi1P, pc3P]
Index: []

fi1P pc3P 136 0

         fi1P     pc3S
1412  EsEj6rô  EsEj6rE
1412  EsEj6rô    EsErE
1412    EsErô  EsEj6rE
1412    EsErô    EsErE
2232   pEj6rô   pEj6rE
2232   pEj6rô     pErE
2232     pErô   pEj6rE
2232     pErô     pErE

Empty DataFrame
Columns: [fi1P, pc3S]
Index: []

fi1P pc3S 275 0

         fi1P   pi1P
1412  EsEj6rô  EsEjô
1412    EsErô  EsEjô
2232   pEj6rô   pEjô
2232     pErô   pEjô

Empty DataFrame
Columns: [fi1P, pi1P]
Index: []

fi1P pi1P 293 0

         fi1P  pi1S
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
2232   pEj6rô   pEj
2232     pErô   pEj
2358     purô    p2
2358     purô   pHi

Empty DataFrame
Columns: [fi1P, pi1S]
Index: []

fi1P pi1S 318 0

         fi1P   pi2P
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi1P, pi2P]
Index: []

fi1P pi2P 308 0

         fi1P  pi2S
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
2232   pEj6rô   pEj
2232     pErô   pEj

Empty DataFrame
Columns: [fi1P, pi2S]
Index: []

fi1P pi2S 305 0

         fi1P  pi3P
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
2232   pEj6rô   pEj
2232     pErô   pEj

Empty DataFrame
Columns: [fi1P, pi3P]
Index: []

fi1P pi3P 317 0

         fi1P  pi3S
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
2232   pEj6rô   pEj
2232     pErô   pEj

Empty DataFrame
Columns: [fi1P, pi3S]
Index: []

fi1P pi3S 322 0

         fi1P   ppFP
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi1P, ppFP]
Index: []

fi1P ppFP 256 0

         fi1P   ppFS
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi1P, ppFS]
Index: []

fi1P ppFS 290 0

         fi1P   ppMP
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi1P, ppMP]
Index: []

fi1P ppMP 276 0

         fi1P   ppMS
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi1P, ppMS]
Index: []

fi1P ppMS 322 0

         fi1P   ps1P
1412  EsEj6rô  EsEjô
1412    EsErô  EsEjô

Empty DataFrame
Columns: [fi1P, ps1P]
Index: []

fi1P ps1P 62 0

         fi1P  ps1S
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
2232   pEj6rô   pEj
2232     pErô   pEj

Empty DataFrame
Columns: [fi1P, ps1S]
Index: []

fi1P ps1S 254 0

         fi1P   ps2P
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi1P, ps2P]
Index: []

fi1P ps2P 197 0

         fi1P  ps2S
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
2232   pEj6rô   pEj
2232     pErô   pEj

Empty DataFrame
Columns: [fi1P, ps2S]
Index: []

fi1P ps2S 234 0

         fi1P  ps3P
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
2232   pEj6rô   pEj
2232     pErô   pEj

Empty DataFrame
Columns: [fi1P, ps3P]
Index: []

fi1P ps3P 237 0

         fi1P  ps3S
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
2232   pEj6rô   pEj
2232     pErô   pEj

Empty DataFrame
Columns: [fi1P, ps3S]
Index: []

fi1P ps3S 306 0

         fi1S     fi2P
1412  EsEj6rE  EsEj6re
1412  EsEj6rE    EsEre
1412    EsErE  EsEj6re
1412    EsErE    EsEre
2232   pEj6rE   pEj6re
2232   pEj6rE     pEre
2232     pErE   pEj6re
2232     pErE     pEre

Empty DataFrame
Columns: [fi1S, fi2P]
Index: []

fi1S fi2P 349 0

         fi1S     fi2S
1412  EsEj6rE  EsEj6ra
1412  EsEj6rE    EsEra
1412    EsErE  EsEj6ra
1412    EsErE    EsEra
2232   pEj6rE   pEj6ra
2232   pEj6rE     pEra
2232     pErE   pEj6ra
2232     pErE     pEra

Empty DataFrame
Columns: [fi1S, fi2S]
Index: []

fi1S fi2S 343 0

         fi1S     fi3P
1412  EsEj6rE  EsEj6rô
1412  EsEj6rE    EsErô
1412    EsErE  EsEj6rô
1412    EsErE    EsErô
2232   pEj6rE   pEj6rô
2232   pEj6rE     pErô
2232     pErE   pEj6rô
2232     pErE     pErô

Empty DataFrame
Columns: [fi1S, fi3P]
Index: []

fi1S fi3P 412 0

         fi1S       fi3S
234    asjErE     asjEra
234    asjErE     aswara
234    aswarE     asjEra
234    aswarE     aswara
1412  EsEj6rE    EsEj6ra
1412  EsEj6rE      EsEra
1412    EsErE    EsEj6ra
1412    EsErE      EsEra
2232   pEj6rE     pEj6ra
2232   pEj6rE       pEra
2232     pErE     pEj6ra
2232     pErE       pEra
2870  rEEsErE  rEEsEj6ra
2870  rEEsErE    rEEsEra

Empty DataFrame
Columns: [fi1S, fi3S]
Index: []

fi1S fi3S 647 0

         fi1S   ii1P
1412  EsEj6rE  EsEjô
1412    EsErE  EsEjô

Empty DataFrame
Columns: [fi1S, ii1P]
Index: []

fi1S ii1P 112 0

         fi1S   ii1S
234    asjErE  asEjE
234    aswarE  asEjE
1412  EsEj6rE  EsEjE
1412    EsErE  EsEjE
2232   pEj6rE   pEjE
2232     pErE   pEjE

Empty DataFrame
Columns: [fi1S, ii1S]
Index: []

fi1S ii1S 476 0

         fi1S   ii2P
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [fi1S, ii2P]
Index: []

fi1S ii2P 188 0

         fi1S   ii2S
234    asjErE  asEjE
234    aswarE  asEjE
1412  EsEj6rE  EsEjE
1412    EsErE  EsEjE
2232   pEj6rE   pEjE
2232     pErE   pEjE

Empty DataFrame
Columns: [fi1S, ii2S]
Index: []

fi1S ii2S 289 0

         fi1S   ii3P
234    asjErE  asEjE
234    aswarE  asEjE
1412  EsEj6rE  EsEjE
1412    EsErE  EsEjE
2232   pEj6rE   pEjE
2232     pErE   pEjE

Empty DataFrame
Columns: [fi1S, ii3P]
Index: []

fi1S ii3P 414 0

         fi1S   ii3S
234    asjErE  asEjE
234    aswarE  asEjE
1412  EsEj6rE  EsEjE
1412    EsErE  EsEjE
2232   pEj6rE   pEjE
2232     pErE   pEjE

Empty DataFrame
Columns: [fi1S, ii3S]
Index: []

fi1S ii3S 635 0

         fi1S    inf
234    asjErE  aswar
234    aswarE  aswar
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [fi1S, inf]
Index: []

fi1S inf 684 0
fi1S is1S 3 0
fi1S is2P 5 0
fi1S is2S 2 0
fi1S is3P 1 0
fi1S is3S 4 0

         fi1S   pI1P
234    asjErE  asEjô
234    aswarE  asEjô
1412  EsEj6rE  EsEjô
1412    EsErE  EsEjô
2232   pEj6rE   pEjô
2232     pErE   pEjô

Empty DataFrame
Columns: [fi1S, pI1P]
Index: []

fi1S pI1P 385 0

         fi1S    pI2P
234    asjErE   asEje
234    asjErE  aswaje
234    aswarE   asEje
234    aswarE  aswaje
1412  EsEj6rE   EsEje
1412    EsErE   EsEje
2232   pEj6rE    pEje
2232     pErE    pEje

Empty DataFrame
Columns: [fi1S, pI2P]
Index: []

fi1S pI2P 642 0

         fi1S  pI2S
234    asjErE  asje
234    asjErE  aswa
234    aswarE  asje
234    aswarE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj
3391    vudrE    v2
3391    vudrE   v9j

Empty DataFrame
Columns: [fi1S, pI2S]
Index: []

fi1S pI2S 632 0

         fi1S     pP
234    asjErE  asEjâ
234    aswarE  asEjâ
1412  EsEj6rE  EsEjâ
1412    EsErE  EsEjâ
2232   pEj6rE   pEjâ
2232     pErE   pEjâ

Empty DataFrame
Columns: [fi1S, pP]
Index: []

fi1S pP 610 0
fi1S pc1P 38 0

         fi1S     pc1S
234    asjErE   asjErE
234    aswarE   asjErE
1412  EsEj6rE  EsEj6rE
1412  EsEj6rE    EsErE
1412    EsErE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232   pEj6rE     pErE
2232     pErE   pEj6rE
2232     pErE     pErE

         fi1S     pc1S
234    asjErE   asjErE
1412  EsEj6rE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232     pErE     pErE

fi1S pc1S 0 389

         fi1S      pc2P
1412  EsEj6rE  EsEj6rje
1412  EsEj6rE    EsErje
1412    EsErE  EsEj6rje
1412    EsErE    EsErje
2232   pEj6rE   pEj6rje
2232   pEj6rE     pErje
2232     pErE   pEj6rje
2232     pErE     pErje

Empty DataFrame
Columns: [fi1S, pc2P]
Index: []

fi1S pc2P 150 0

         fi1S     pc2S
1412  EsEj6rE  EsEj6rE
1412  EsEj6rE    EsErE
1412    EsErE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232   pEj6rE     pErE
2232     pErE   pEj6rE
2232     pErE     pErE

         fi1S     pc2S
1412  EsEj6rE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232     pErE     pErE

fi1S pc2S 0 204

         fi1S     pc3P
1412  EsEj6rE  EsEj6rE
1412  EsEj6rE    EsErE
1412    EsErE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232   pEj6rE     pErE
2232     pErE   pEj6rE
2232     pErE     pErE

         fi1S     pc3P
1412  EsEj6rE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232     pErE     pErE

fi1S pc3P 0 162

         fi1S     pc3S
234    asjErE   asjErE
234    aswarE   asjErE
1412  EsEj6rE  EsEj6rE
1412  EsEj6rE    EsErE
1412    EsErE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232   pEj6rE     pErE
2232     pErE   pEj6rE
2232     pErE     pErE

         fi1S     pc3S
234    asjErE   asjErE
1412  EsEj6rE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232     pErE     pErE

fi1S pc3S 0 480

         fi1S   pi1P
234    asjErE  asEjô
234    aswarE  asEjô
1412  EsEj6rE  EsEjô
1412    EsErE  EsEjô
2232   pEj6rE   pEjô
2232     pErE   pEjô

Empty DataFrame
Columns: [fi1S, pi1P]
Index: []

fi1S pi1P 436 0

         fi1S  pi1S
234    asjErE  asje
234    asjErE  aswa
234    aswarE  asje
234    aswarE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
1721     airE     E
1721     airE    ai
2232   pEj6rE   pEj
2232     pErE   pEj
2358     purE    p2
2358     purE   pHi

Empty DataFrame
Columns: [fi1S, pi1S]
Index: []

fi1S pi1S 675 0

         fi1S   pi2P
234    asjErE  asEje
234    aswarE  asEje
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [fi1S, pi2P]
Index: []

fi1S pi2P 625 0

         fi1S  pi2S
234    asjErE  asje
234    asjErE  aswa
234    aswarE  asje
234    aswarE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
1721     airE     E
1721     airE    ai
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [fi1S, pi2S]
Index: []

fi1S pi2S 647 0

         fi1S  pi3P
234    asjErE  asEj
234    asjErE  aswa
234    aswarE  asEj
234    aswarE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [fi1S, pi3P]
Index: []

fi1S pi3P 656 0

         fi1S  pi3S
234    asjErE  asje
234    asjErE  aswa
234    aswarE  asje
234    aswarE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
1721     airE     E
1721     airE    ai
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [fi1S, pi3S]
Index: []

fi1S pi3S 678 0

         fi1S   ppFP
234    asjErE   asiz
234    aswarE   asiz
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [fi1S, ppFP]
Index: []

fi1S ppFP 464 0

         fi1S   ppFS
234    asjErE   asiz
234    aswarE   asiz
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [fi1S, ppFS]
Index: []

fi1S ppFS 598 0

         fi1S   ppMP
234    asjErE    asi
234    aswarE    asi
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [fi1S, ppMP]
Index: []

fi1S ppMP 566 0

         fi1S   ppMS
234    asjErE    asi
234    aswarE    asi
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [fi1S, ppMS]
Index: []

fi1S ppMS 681 0

         fi1S   ps1P
1412  EsEj6rE  EsEjô
1412    EsErE  EsEjô

Empty DataFrame
Columns: [fi1S, ps1P]
Index: []

fi1S ps1P 63 0

         fi1S  ps1S
234    asjErE  asEj
234    asjErE  aswa
234    aswarE  asEj
234    aswarE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [fi1S, ps1S]
Index: []

fi1S ps1S 462 0

         fi1S   ps2P
234    asjErE  asEje
234    aswarE  asEje
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [fi1S, ps2P]
Index: []

fi1S ps2P 248 0

         fi1S  ps2S
234    asjErE  asEj
234    asjErE  aswa
234    aswarE  asEj
234    aswarE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [fi1S, ps2S]
Index: []

fi1S ps2S 380 0

         fi1S  ps3P
234    asjErE  aswa
234    aswarE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [fi1S, ps3P]
Index: []

fi1S ps3P 335 0

         fi1S  ps3S
234    asjErE  asEj
234    asjErE  aswa
234    aswarE  asEj
234    aswarE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [fi1S, ps3S]
Index: []

fi1S ps3S 613 0

         fi2P     fi2S
1412  EsEj6re  EsEj6ra
1412  EsEj6re    EsEra
1412    EsEre  EsEj6ra
1412    EsEre    EsEra
2232   pEj6re   pEj6ra
2232   pEj6re     pEra
2232     pEre   pEj6ra
2232     pEre     pEra

Empty DataFrame
Columns: [fi2P, fi2S]
Index: []

fi2P fi2S 313 0

         fi2P     fi3P
1412  EsEj6re  EsEj6rô
1412  EsEj6re    EsErô
1412    EsEre  EsEj6rô
1412    EsEre    EsErô
2232   pEj6re   pEj6rô
2232   pEj6re     pErô
2232     pEre   pEj6rô
2232     pEre     pErô

Empty DataFrame
Columns: [fi2P, fi3P]
Index: []

fi2P fi3P 313 0

         fi2P     fi3S
1412  EsEj6re  EsEj6ra
1412  EsEj6re    EsEra
1412    EsEre  EsEj6ra
1412    EsEre    EsEra
2232   pEj6re   pEj6ra
2232   pEj6re     pEra
2232     pEre   pEj6ra
2232     pEre     pEra

Empty DataFrame
Columns: [fi2P, fi3S]
Index: []

fi2P fi3S 360 0

         fi2P   ii1P
1412  EsEj6re  EsEjô
1412    EsEre  EsEjô

Empty DataFrame
Columns: [fi2P, ii1P]
Index: []

fi2P ii1P 105 0

         fi2P   ii1S
1412  EsEj6re  EsEjE
1412    EsEre  EsEjE
2232   pEj6re   pEjE
2232     pEre   pEjE

Empty DataFrame
Columns: [fi2P, ii1S]
Index: []

fi2P ii1S 310 0

         fi2P   ii2P
1412  EsEj6re  EsEje
1412    EsEre  EsEje
2232   pEj6re   pEje
2232     pEre   pEje

Empty DataFrame
Columns: [fi2P, ii2P]
Index: []

fi2P ii2P 158 0

         fi2P   ii2S
1412  EsEj6re  EsEjE
1412    EsEre  EsEjE
2232   pEj6re   pEjE
2232     pEre   pEjE

Empty DataFrame
Columns: [fi2P, ii2S]
Index: []

fi2P ii2S 223 0

         fi2P   ii3P
1412  EsEj6re  EsEjE
1412    EsEre  EsEjE
2232   pEj6re   pEjE
2232     pEre   pEjE

Empty DataFrame
Columns: [fi2P, ii3P]
Index: []

fi2P ii3P 281 0

         fi2P   ii3S
1412  EsEj6re  EsEjE
1412    EsEre  EsEjE
2232   pEj6re   pEjE
2232     pEre   pEjE

Empty DataFrame
Columns: [fi2P, ii3S]
Index: []

fi2P ii3S 352 0

         fi2P    inf
1412  EsEj6re  EsEje
1412    EsEre  EsEje
2232   pEj6re   pEje
2232     pEre   pEje

Empty DataFrame
Columns: [fi2P, inf]
Index: []

fi2P inf 361 0
fi2P is1S 3 0
fi2P is2P 5 0
fi2P is2S 2 0
fi2P is3P 1 0
fi2P is3S 4 0

         fi2P   pI1P
1412  EsEj6re  EsEjô
1412    EsEre  EsEjô
2232   pEj6re   pEjô
2232     pEre   pEjô

Empty DataFrame
Columns: [fi2P, pI1P]
Index: []

fi2P pI1P 265 0

         fi2P   pI2P
1412  EsEj6re  EsEje
1412    EsEre  EsEje
2232   pEj6re   pEje
2232     pEre   pEje

Empty DataFrame
Columns: [fi2P, pI2P]
Index: []

fi2P pI2P 340 0

         fi2P  pI2S
1412  EsEj6re  EsEj
1412    EsEre  EsEj
2232   pEj6re   pEj
2232     pEre   pEj
3391    vudre    v2
3391    vudre   v9j

Empty DataFrame
Columns: [fi2P, pI2S]
Index: []

fi2P pI2S 338 0

         fi2P     pP
1412  EsEj6re  EsEjâ
1412    EsEre  EsEjâ
2232   pEj6re   pEjâ
2232     pEre   pEjâ

Empty DataFrame
Columns: [fi2P, pP]
Index: []

fi2P pP 344 0
fi2P pc1P 38 0

         fi2P     pc1S
1412  EsEj6re  EsEj6rE
1412  EsEj6re    EsErE
1412    EsEre  EsEj6rE
1412    EsEre    EsErE
2232   pEj6re   pEj6rE
2232   pEj6re     pErE
2232     pEre   pEj6rE
2232     pEre     pErE

Empty DataFrame
Columns: [fi2P, pc1S]
Index: []

fi2P pc1S 291 0

         fi2P      pc2P
1412  EsEj6re  EsEj6rje
1412  EsEj6re    EsErje
1412    EsEre  EsEj6rje
1412    EsEre    EsErje
2232   pEj6re   pEj6rje
2232   pEj6re     pErje
2232     pEre   pEj6rje
2232     pEre     pErje

Empty DataFrame
Columns: [fi2P, pc2P]
Index: []

fi2P pc2P 140 0

         fi2P     pc2S
1412  EsEj6re  EsEj6rE
1412  EsEj6re    EsErE
1412    EsEre  EsEj6rE
1412    EsEre    EsErE
2232   pEj6re   pEj6rE
2232   pEj6re     pErE
2232     pEre   pEj6rE
2232     pEre     pErE

Empty DataFrame
Columns: [fi2P, pc2S]
Index: []

fi2P pc2S 190 0

         fi2P     pc3P
1412  EsEj6re  EsEj6rE
1412  EsEj6re    EsErE
1412    EsEre  EsEj6rE
1412    EsEre    EsErE
2232   pEj6re   pEj6rE
2232   pEj6re     pErE
2232     pEre   pEj6rE
2232     pEre     pErE

Empty DataFrame
Columns: [fi2P, pc3P]
Index: []

fi2P pc3P 152 0

         fi2P     pc3S
1412  EsEj6re  EsEj6rE
1412  EsEj6re    EsErE
1412    EsEre  EsEj6rE
1412    EsEre    EsErE
2232   pEj6re   pEj6rE
2232   pEj6re     pErE
2232     pEre   pEj6rE
2232     pEre     pErE

Empty DataFrame
Columns: [fi2P, pc3S]
Index: []

fi2P pc3S 323 0

         fi2P   pi1P
1412  EsEj6re  EsEjô
1412    EsEre  EsEjô
2232   pEj6re   pEjô
2232     pEre   pEjô

Empty DataFrame
Columns: [fi2P, pi1P]
Index: []

fi2P pi1P 308 0

         fi2P  pi1S
1412  EsEj6re  EsEj
1412    EsEre  EsEj
2232   pEj6re   pEj
2232     pEre   pEj
2358     pure    p2
2358     pure   pHi

Empty DataFrame
Columns: [fi2P, pi1S]
Index: []

fi2P pi1S 358 0

         fi2P   pi2P
1412  EsEj6re  EsEje
1412    EsEre  EsEje
2232   pEj6re   pEje
2232     pEre   pEje

Empty DataFrame
Columns: [fi2P, pi2P]
Index: []

fi2P pi2P 356 0

         fi2P  pi2S
1412  EsEj6re  EsEj
1412    EsEre  EsEj
2232   pEj6re   pEj
2232     pEre   pEj

Empty DataFrame
Columns: [fi2P, pi2S]
Index: []

fi2P pi2S 352 0

         fi2P  pi3P
1412  EsEj6re  EsEj
1412    EsEre  EsEj
2232   pEj6re   pEj
2232     pEre   pEj

Empty DataFrame
Columns: [fi2P, pi3P]
Index: []

fi2P pi3P 358 0

         fi2P  pi3S
1412  EsEj6re  EsEj
1412    EsEre  EsEj
2232   pEj6re   pEj
2232     pEre   pEj

Empty DataFrame
Columns: [fi2P, pi3S]
Index: []

fi2P pi3S 360 0

         fi2P   ppFP
1412  EsEj6re  EsEje
1412    EsEre  EsEje
2232   pEj6re   pEje
2232     pEre   pEje

Empty DataFrame
Columns: [fi2P, ppFP]
Index: []

fi2P ppFP 279 0

         fi2P   ppFS
1412  EsEj6re  EsEje
1412    EsEre  EsEje
2232   pEj6re   pEje
2232     pEre   pEje

Empty DataFrame
Columns: [fi2P, ppFS]
Index: []

fi2P ppFS 322 0

         fi2P   ppMP
1412  EsEj6re  EsEje
1412    EsEre  EsEje
2232   pEj6re   pEje
2232     pEre   pEje

Empty DataFrame
Columns: [fi2P, ppMP]
Index: []

fi2P ppMP 310 0

         fi2P   ppMS
1412  EsEj6re  EsEje
1412    EsEre  EsEje
2232   pEj6re   pEje
2232     pEre   pEje

Empty DataFrame
Columns: [fi2P, ppMS]
Index: []

fi2P ppMS 360 0

         fi2P   ps1P
1412  EsEj6re  EsEjô
1412    EsEre  EsEjô

Empty DataFrame
Columns: [fi2P, ps1P]
Index: []

fi2P ps1P 63 0

         fi2P  ps1S
1412  EsEj6re  EsEj
1412    EsEre  EsEj
2232   pEj6re   pEj
2232     pEre   pEj

Empty DataFrame
Columns: [fi2P, ps1S]
Index: []

fi2P ps1S 313 0

         fi2P   ps2P
1412  EsEj6re  EsEje
1412    EsEre  EsEje
2232   pEj6re   pEje
2232     pEre   pEje

Empty DataFrame
Columns: [fi2P, ps2P]
Index: []

fi2P ps2P 222 0

         fi2P  ps2S
1412  EsEj6re  EsEj
1412    EsEre  EsEj
2232   pEj6re   pEj
2232     pEre   pEj

Empty DataFrame
Columns: [fi2P, ps2S]
Index: []

fi2P ps2S 288 0

         fi2P  ps3P
1412  EsEj6re  EsEj
1412    EsEre  EsEj
2232   pEj6re   pEj
2232     pEre   pEj

Empty DataFrame
Columns: [fi2P, ps3P]
Index: []

fi2P ps3P 263 0

         fi2P  ps3S
1412  EsEj6re  EsEj
1412    EsEre  EsEj
2232   pEj6re   pEj
2232     pEre   pEj

Empty DataFrame
Columns: [fi2P, ps3S]
Index: []

fi2P ps3S 350 0

         fi2S     fi3P
1412  EsEj6ra  EsEj6rô
1412  EsEj6ra    EsErô
1412    EsEra  EsEj6rô
1412    EsEra    EsErô
2232   pEj6ra   pEj6rô
2232   pEj6ra     pErô
2232     pEra   pEj6rô
2232     pEra     pErô

Empty DataFrame
Columns: [fi2S, fi3P]
Index: []

fi2S fi3P 303 0

         fi2S     fi3S
1412  EsEj6ra  EsEj6ra
1412  EsEj6ra    EsEra
1412    EsEra  EsEj6ra
1412    EsEra    EsEra
2232   pEj6ra   pEj6ra
2232   pEj6ra     pEra
2232     pEra   pEj6ra
2232     pEra     pEra

         fi2S     fi3S
1412  EsEj6ra  EsEj6ra
1412    EsEra    EsEra
2232   pEj6ra   pEj6ra
2232     pEra     pEra

fi2S fi3S 0 357

         fi2S   ii1P
1412  EsEj6ra  EsEjô
1412    EsEra  EsEjô

Empty DataFrame
Columns: [fi2S, ii1P]
Index: []

fi2S ii1P 97 0

         fi2S   ii1S
1412  EsEj6ra  EsEjE
1412    EsEra  EsEjE
2232   pEj6ra   pEjE
2232     pEra   pEjE

Empty DataFrame
Columns: [fi2S, ii1S]
Index: []

fi2S ii1S 316 0

         fi2S   ii2P
1412  EsEj6ra  EsEje
1412    EsEra  EsEje
2232   pEj6ra   pEje
2232     pEra   pEje

Empty DataFrame
Columns: [fi2S, ii2P]
Index: []

fi2S ii2P 158 0

         fi2S   ii2S
1412  EsEj6ra  EsEjE
1412    EsEra  EsEjE
2232   pEj6ra   pEjE
2232     pEra   pEjE

Empty DataFrame
Columns: [fi2S, ii2S]
Index: []

fi2S ii2S 238 0

         fi2S   ii3P
1412  EsEj6ra  EsEjE
1412    EsEra  EsEjE
2232   pEj6ra   pEjE
2232     pEra   pEjE

Empty DataFrame
Columns: [fi2S, ii3P]
Index: []

fi2S ii3P 281 0

         fi2S   ii3S
1412  EsEj6ra  EsEjE
1412    EsEra  EsEjE
2232   pEj6ra   pEjE
2232     pEra   pEjE

Empty DataFrame
Columns: [fi2S, ii3S]
Index: []

fi2S ii3S 346 0

         fi2S    inf
1412  EsEj6ra  EsEje
1412    EsEra  EsEje
2232   pEj6ra   pEje
2232     pEra   pEje

Empty DataFrame
Columns: [fi2S, inf]
Index: []

fi2S inf 357 0
fi2S is1S 3 0
fi2S is2P 5 0
fi2S is2S 2 0
fi2S is3P 1 0
fi2S is3S 4 0

         fi2S   pI1P
1412  EsEj6ra  EsEjô
1412    EsEra  EsEjô
2232   pEj6ra   pEjô
2232     pEra   pEjô

Empty DataFrame
Columns: [fi2S, pI1P]
Index: []

fi2S pI1P 253 0

         fi2S   pI2P
1412  EsEj6ra  EsEje
1412    EsEra  EsEje
2232   pEj6ra   pEje
2232     pEra   pEje

Empty DataFrame
Columns: [fi2S, pI2P]
Index: []

fi2S pI2P 334 0

         fi2S  pI2S
1412  EsEj6ra  EsEj
1412    EsEra  EsEj
2232   pEj6ra   pEj
2232     pEra   pEj
3391    vudra    v2
3391    vudra   v9j

Empty DataFrame
Columns: [fi2S, pI2S]
Index: []

fi2S pI2S 334 0

         fi2S     pP
1412  EsEj6ra  EsEjâ
1412    EsEra  EsEjâ
2232   pEj6ra   pEjâ
2232     pEra   pEjâ

Empty DataFrame
Columns: [fi2S, pP]
Index: []

fi2S pP 340 0
fi2S pc1P 38 0

         fi2S     pc1S
1412  EsEj6ra  EsEj6rE
1412  EsEj6ra    EsErE
1412    EsEra  EsEj6rE
1412    EsEra    EsErE
2232   pEj6ra   pEj6rE
2232   pEj6ra     pErE
2232     pEra   pEj6rE
2232     pEra     pErE

Empty DataFrame
Columns: [fi2S, pc1S]
Index: []

fi2S pc1S 296 0

         fi2S      pc2P
1412  EsEj6ra  EsEj6rje
1412  EsEj6ra    EsErje
1412    EsEra  EsEj6rje
1412    EsEra    EsErje
2232   pEj6ra   pEj6rje
2232   pEj6ra     pErje
2232     pEra   pEj6rje
2232     pEra     pErje

Empty DataFrame
Columns: [fi2S, pc2P]
Index: []

fi2S pc2P 137 0

         fi2S     pc2S
1412  EsEj6ra  EsEj6rE
1412  EsEj6ra    EsErE
1412    EsEra  EsEj6rE
1412    EsEra    EsErE
2232   pEj6ra   pEj6rE
2232   pEj6ra     pErE
2232     pEra   pEj6rE
2232     pEra     pErE

Empty DataFrame
Columns: [fi2S, pc2S]
Index: []

fi2S pc2S 193 0

         fi2S     pc3P
1412  EsEj6ra  EsEj6rE
1412  EsEj6ra    EsErE
1412    EsEra  EsEj6rE
1412    EsEra    EsErE
2232   pEj6ra   pEj6rE
2232   pEj6ra     pErE
2232     pEra   pEj6rE
2232     pEra     pErE

Empty DataFrame
Columns: [fi2S, pc3P]
Index: []

fi2S pc3P 155 0

         fi2S     pc3S
1412  EsEj6ra  EsEj6rE
1412  EsEj6ra    EsErE
1412    EsEra  EsEj6rE
1412    EsEra    EsErE
2232   pEj6ra   pEj6rE
2232   pEj6ra     pErE
2232     pEra   pEj6rE
2232     pEra     pErE

Empty DataFrame
Columns: [fi2S, pc3S]
Index: []

fi2S pc3S 324 0

         fi2S   pi1P
1412  EsEj6ra  EsEjô
1412    EsEra  EsEjô
2232   pEj6ra   pEjô
2232     pEra   pEjô

Empty DataFrame
Columns: [fi2S, pi1P]
Index: []

fi2S pi1P 285 0

         fi2S  pi1S
1412  EsEj6ra  EsEj
1412    EsEra  EsEj
1721     aira     E
1721     aira    ai
2232   pEj6ra   pEj
2232     pEra   pEj
2358     pura    p2
2358     pura   pHi

Empty DataFrame
Columns: [fi2S, pi1S]
Index: []

fi2S pi1S 353 0

         fi2S   pi2P
1412  EsEj6ra  EsEje
1412    EsEra  EsEje
2232   pEj6ra   pEje
2232     pEra   pEje

Empty DataFrame
Columns: [fi2S, pi2P]
Index: []

fi2S pi2P 348 0

         fi2S  pi2S
1412  EsEj6ra  EsEj
1412    EsEra  EsEj
1721     aira     E
1721     aira    ai
2232   pEj6ra   pEj
2232     pEra   pEj

Empty DataFrame
Columns: [fi2S, pi2S]
Index: []

fi2S pi2S 349 0

         fi2S  pi3P
1412  EsEj6ra  EsEj
1412    EsEra  EsEj
2232   pEj6ra   pEj
2232     pEra   pEj

Empty DataFrame
Columns: [fi2S, pi3P]
Index: []

fi2S pi3P 354 0

         fi2S  pi3S
1412  EsEj6ra  EsEj
1412    EsEra  EsEj
1721     aira     E
1721     aira    ai
2232   pEj6ra   pEj
2232     pEra   pEj

Empty DataFrame
Columns: [fi2S, pi3S]
Index: []

fi2S pi3S 355 0

         fi2S   ppFP
1412  EsEj6ra  EsEje
1412    EsEra  EsEje
2232   pEj6ra   pEje
2232     pEra   pEje

Empty DataFrame
Columns: [fi2S, ppFP]
Index: []

fi2S ppFP 263 0

         fi2S   ppFS
1412  EsEj6ra  EsEje
1412    EsEra  EsEje
2232   pEj6ra   pEje
2232     pEra   pEje

Empty DataFrame
Columns: [fi2S, ppFS]
Index: []

fi2S ppFS 316 0

         fi2S   ppMP
1412  EsEj6ra  EsEje
1412    EsEra  EsEje
2232   pEj6ra   pEje
2232     pEra   pEje

Empty DataFrame
Columns: [fi2S, ppMP]
Index: []

fi2S ppMP 301 0

         fi2S   ppMS
1412  EsEj6ra  EsEje
1412    EsEra  EsEje
2232   pEj6ra   pEje
2232     pEra   pEje

Empty DataFrame
Columns: [fi2S, ppMS]
Index: []

fi2S ppMS 354 0

         fi2S   ps1P
1412  EsEj6ra  EsEjô
1412    EsEra  EsEjô

Empty DataFrame
Columns: [fi2S, ps1P]
Index: []

fi2S ps1P 60 0

         fi2S  ps1S
1412  EsEj6ra  EsEj
1412    EsEra  EsEj
2232   pEj6ra   pEj
2232     pEra   pEj

Empty DataFrame
Columns: [fi2S, ps1S]
Index: []

fi2S ps1S 316 0

         fi2S   ps2P
1412  EsEj6ra  EsEje
1412    EsEra  EsEje
2232   pEj6ra   pEje
2232     pEra   pEje

Empty DataFrame
Columns: [fi2S, ps2P]
Index: []

fi2S ps2P 212 0

         fi2S  ps2S
1412  EsEj6ra  EsEj
1412    EsEra  EsEj
2232   pEj6ra   pEj
2232     pEra   pEj

Empty DataFrame
Columns: [fi2S, ps2S]
Index: []

fi2S ps2S 291 0

         fi2S  ps3P
1412  EsEj6ra  EsEj
1412    EsEra  EsEj
2232   pEj6ra   pEj
2232     pEra   pEj

Empty DataFrame
Columns: [fi2S, ps3P]
Index: []

fi2S ps3P 264 0

         fi2S  ps3S
1412  EsEj6ra  EsEj
1412    EsEra  EsEj
2232   pEj6ra   pEj
2232     pEra   pEj

Empty DataFrame
Columns: [fi2S, ps3S]
Index: []

fi2S ps3S 347 0

         fi3P     fi3S
1412  EsEj6rô  EsEj6ra
1412  EsEj6rô    EsEra
1412    EsErô  EsEj6ra
1412    EsErô    EsEra
2232   pEj6rô   pEj6ra
2232   pEj6rô     pEra
2232     pErô   pEj6ra
2232     pErô     pEra

Empty DataFrame
Columns: [fi3P, fi3S]
Index: []

fi3P fi3S 467 0

         fi3P   ii1P
1412  EsEj6rô  EsEjô
1412    EsErô  EsEjô

Empty DataFrame
Columns: [fi3P, ii1P]
Index: []

fi3P ii1P 104 0

         fi3P   ii1S
1412  EsEj6rô  EsEjE
1412    EsErô  EsEjE
2232   pEj6rô   pEjE
2232     pErô   pEjE

Empty DataFrame
Columns: [fi3P, ii1S]
Index: []

fi3P ii1S 348 0

         fi3P   ii2P
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi3P, ii2P]
Index: []

fi3P ii2P 169 0

         fi3P   ii2S
1412  EsEj6rô  EsEjE
1412    EsErô  EsEjE
2232   pEj6rô   pEjE
2232     pErô   pEjE

Empty DataFrame
Columns: [fi3P, ii2S]
Index: []

fi3P ii2S 240 0

         fi3P   ii3P
1412  EsEj6rô  EsEjE
1412    EsErô  EsEjE
2232   pEj6rô   pEjE
2232     pErô   pEjE

Empty DataFrame
Columns: [fi3P, ii3P]
Index: []

fi3P ii3P 363 0

         fi3P   ii3S
1412  EsEj6rô  EsEjE
1412    EsErô  EsEjE
2232   pEj6rô   pEjE
2232     pErô   pEjE

Empty DataFrame
Columns: [fi3P, ii3S]
Index: []

fi3P ii3S 450 0

         fi3P    inf
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi3P, inf]
Index: []

fi3P inf 469 0
fi3P is1S 3 0
fi3P is2P 5 0
fi3P is2S 2 0
fi3P is3P 1 0
fi3P is3S 4 0

         fi3P   pI1P
1412  EsEj6rô  EsEjô
1412    EsErô  EsEjô
2232   pEj6rô   pEjô
2232     pErô   pEjô

Empty DataFrame
Columns: [fi3P, pI1P]
Index: []

fi3P pI1P 304 0

         fi3P   pI2P
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi3P, pI2P]
Index: []

fi3P pI2P 422 0

         fi3P  pI2S
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
2232   pEj6rô   pEj
2232     pErô   pEj
3391    vudrô    v2
3391    vudrô   v9j

Empty DataFrame
Columns: [fi3P, pI2S]
Index: []

fi3P pI2S 417 0

         fi3P     pP
1412  EsEj6rô  EsEjâ
1412    EsErô  EsEjâ
2232   pEj6rô   pEjâ
2232     pErô   pEjâ

Empty DataFrame
Columns: [fi3P, pP]
Index: []

fi3P pP 428 0
fi3P pc1P 37 0

         fi3P     pc1S
1412  EsEj6rô  EsEj6rE
1412  EsEj6rô    EsErE
1412    EsErô  EsEj6rE
1412    EsErô    EsErE
2232   pEj6rô   pEj6rE
2232   pEj6rô     pErE
2232     pErô   pEj6rE
2232     pErô     pErE

Empty DataFrame
Columns: [fi3P, pc1S]
Index: []

fi3P pc1S 322 0

         fi3P      pc2P
1412  EsEj6rô  EsEj6rje
1412  EsEj6rô    EsErje
1412    EsErô  EsEj6rje
1412    EsErô    EsErje
2232   pEj6rô   pEj6rje
2232   pEj6rô     pErje
2232     pErô   pEj6rje
2232     pErô     pErje

Empty DataFrame
Columns: [fi3P, pc2P]
Index: []

fi3P pc2P 141 0

         fi3P     pc2S
1412  EsEj6rô  EsEj6rE
1412  EsEj6rô    EsErE
1412    EsErô  EsEj6rE
1412    EsErô    EsErE
2232   pEj6rô   pEj6rE
2232   pEj6rô     pErE
2232     pErô   pEj6rE
2232     pErô     pErE

Empty DataFrame
Columns: [fi3P, pc2S]
Index: []

fi3P pc2S 194 0

         fi3P     pc3P
1412  EsEj6rô  EsEj6rE
1412  EsEj6rô    EsErE
1412    EsErô  EsEj6rE
1412    EsErô    EsErE
2232   pEj6rô   pEj6rE
2232   pEj6rô     pErE
2232     pErô   pEj6rE
2232     pErô     pErE

Empty DataFrame
Columns: [fi3P, pc3P]
Index: []

fi3P pc3P 164 0

         fi3P     pc3S
1412  EsEj6rô  EsEj6rE
1412  EsEj6rô    EsErE
1412    EsErô  EsEj6rE
1412    EsErô    EsErE
2232   pEj6rô   pEj6rE
2232   pEj6rô     pErE
2232     pErô   pEj6rE
2232     pErô     pErE

Empty DataFrame
Columns: [fi3P, pc3S]
Index: []

fi3P pc3S 408 0

         fi3P   pi1P
1412  EsEj6rô  EsEjô
1412    EsErô  EsEjô
2232   pEj6rô   pEjô
2232     pErô   pEjô

Empty DataFrame
Columns: [fi3P, pi1P]
Index: []

fi3P pi1P 353 0

         fi3P  pi1S
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
1721     airô     E
1721     airô    ai
2232   pEj6rô   pEj
2232     pErô   pEj
2358     purô    p2
2358     purô   pHi

Empty DataFrame
Columns: [fi3P, pi1S]
Index: []

fi3P pi1S 452 0

         fi3P   pi2P
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi3P, pi2P]
Index: []

fi3P pi2P 434 0

         fi3P  pi2S
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
1721     airô     E
1721     airô    ai
2232   pEj6rô   pEj
2232     pErô   pEj

Empty DataFrame
Columns: [fi3P, pi2S]
Index: []

fi3P pi2S 439 0

         fi3P  pi3P
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
2232   pEj6rô   pEj
2232     pErô   pEj

Empty DataFrame
Columns: [fi3P, pi3P]
Index: []

fi3P pi3P 465 0

         fi3P  pi3S
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
1721     airô     E
1721     airô    ai
2232   pEj6rô   pEj
2232     pErô   pEj

Empty DataFrame
Columns: [fi3P, pi3S]
Index: []

fi3P pi3S 468 0

         fi3P   ppFP
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi3P, ppFP]
Index: []

fi3P ppFP 345 0

         fi3P   ppFS
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi3P, ppFS]
Index: []

fi3P ppFS 416 0

         fi3P   ppMP
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi3P, ppMP]
Index: []

fi3P ppMP 398 0

         fi3P   ppMS
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi3P, ppMS]
Index: []

fi3P ppMS 468 0

         fi3P   ps1P
1412  EsEj6rô  EsEjô
1412    EsErô  EsEjô

Empty DataFrame
Columns: [fi3P, ps1P]
Index: []

fi3P ps1P 62 0

         fi3P  ps1S
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
2232   pEj6rô   pEj
2232     pErô   pEj

Empty DataFrame
Columns: [fi3P, ps1S]
Index: []

fi3P ps1S 345 0

         fi3P   ps2P
1412  EsEj6rô  EsEje
1412    EsErô  EsEje
2232   pEj6rô   pEje
2232     pErô   pEje

Empty DataFrame
Columns: [fi3P, ps2P]
Index: []

fi3P ps2P 228 0

         fi3P  ps2S
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
2232   pEj6rô   pEj
2232     pErô   pEj

Empty DataFrame
Columns: [fi3P, ps2S]
Index: []

fi3P ps2S 316 0

         fi3P  ps3P
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
2232   pEj6rô   pEj
2232     pErô   pEj

Empty DataFrame
Columns: [fi3P, ps3P]
Index: []

fi3P ps3P 328 0

         fi3P  ps3S
1412  EsEj6rô  EsEj
1412    EsErô  EsEj
2232   pEj6rô   pEj
2232     pErô   pEj

Empty DataFrame
Columns: [fi3P, ps3S]
Index: []

fi3P ps3S 453 0

         fi3S   ii1P
1412  EsEj6ra  EsEjô
1412    EsEra  EsEjô

Empty DataFrame
Columns: [fi3S, ii1P]
Index: []

fi3S ii1P 116 0

         fi3S   ii1S
234    asjEra  asEjE
234    aswara  asEjE
1412  EsEj6ra  EsEjE
1412    EsEra  EsEjE
2232   pEj6ra   pEjE
2232     pEra   pEjE

Empty DataFrame
Columns: [fi3S, ii1S]
Index: []

fi3S ii1S 511 0

         fi3S   ii2P
1412  EsEj6ra  EsEje
1412    EsEra  EsEje
2232   pEj6ra   pEje
2232     pEra   pEje

Empty DataFrame
Columns: [fi3S, ii2P]
Index: []

fi3S ii2P 199 0

         fi3S   ii2S
234    asjEra  asEjE
234    aswara  asEjE
1412  EsEj6ra  EsEjE
1412    EsEra  EsEjE
2232   pEj6ra   pEjE
2232     pEra   pEjE

Empty DataFrame
Columns: [fi3S, ii2S]
Index: []

fi3S ii2S 304 0

         fi3S   ii3P
234    asjEra  asEjE
234    aswara  asEjE
1412  EsEj6ra  EsEjE
1412    EsEra  EsEjE
2232   pEj6ra   pEjE
2232     pEra   pEjE

Empty DataFrame
Columns: [fi3S, ii3P]
Index: []

fi3S ii3P 483 0

         fi3S   ii3S
234    asjEra  asEjE
234    aswara  asEjE
1412  EsEj6ra  EsEjE
1412    EsEra  EsEjE
2232   pEj6ra   pEjE
2232     pEra   pEjE

Empty DataFrame
Columns: [fi3S, ii3S]
Index: []

fi3S ii3S 831 0

           fi3S      inf
234      asjEra    aswar
234      aswara    aswar
1412    EsEj6ra    EsEje
1412      EsEra    EsEje
2232     pEj6ra     pEje
2232       pEra     pEje
2870  rEEsEj6ra  rEEsEje
2870    rEEsEra  rEEsEje

Empty DataFrame
Columns: [fi3S, inf]
Index: []

fi3S inf 978 0
fi3S is1S 3 0
fi3S is2P 5 0
fi3S is2S 2 0
fi3S is3P 1 0
fi3S is3S 4 0

           fi3S     pI1P
234      asjEra    asEjô
234      aswara    asEjô
1412    EsEj6ra    EsEjô
1412      EsEra    EsEjô
2232     pEj6ra     pEjô
2232       pEra     pEjô
2870  rEEsEj6ra  rEEsEjô
2870    rEEsEra  rEEsEjô

Empty DataFrame
Columns: [fi3S, pI1P]
Index: []

fi3S pI1P 411 0

           fi3S     pI2P
234      asjEra    asEje
234      asjEra   aswaje
234      aswara    asEje
234      aswara   aswaje
1412    EsEj6ra    EsEje
1412      EsEra    EsEje
2232     pEj6ra     pEje
2232       pEra     pEje
2870  rEEsEj6ra  rEEsEje
2870    rEEsEra  rEEsEje

Empty DataFrame
Columns: [fi3S, pI2P]
Index: []

fi3S pI2P 797 0

           fi3S    pI2S
234      asjEra    asje
234      asjEra    aswa
234      aswara    asje
234      aswara    aswa
311      balEra    balE
311      balEra   balEj
1412    EsEj6ra    EsEj
1412      EsEra    EsEj
2232     pEj6ra     pEj
2232       pEra     pEj
2870  rEEsEj6ra  rEEsEj
2870    rEEsEra  rEEsEj
3391      vudra      v2
3391      vudra     v9j

Empty DataFrame
Columns: [fi3S, pI2S]
Index: []

fi3S pI2S 774 0

         fi3S     pP
234    asjEra  asEjâ
234    aswara  asEjâ
1412  EsEj6ra  EsEjâ
1412    EsEra  EsEjâ
2232   pEj6ra   pEjâ
2232     pEra   pEjâ

Empty DataFrame
Columns: [fi3S, pP]
Index: []

fi3S pP 778 0
fi3S pc1P 38 0

         fi3S     pc1S
234    asjEra   asjErE
234    aswara   asjErE
1412  EsEj6ra  EsEj6rE
1412  EsEj6ra    EsErE
1412    EsEra  EsEj6rE
1412    EsEra    EsErE
2232   pEj6ra   pEj6rE
2232   pEj6ra     pErE
2232     pEra   pEj6rE
2232     pEra     pErE

Empty DataFrame
Columns: [fi3S, pc1S]
Index: []

fi3S pc1S 394 0

         fi3S      pc2P
1412  EsEj6ra  EsEj6rje
1412  EsEj6ra    EsErje
1412    EsEra  EsEj6rje
1412    EsEra    EsErje
2232   pEj6ra   pEj6rje
2232   pEj6ra     pErje
2232     pEra   pEj6rje
2232     pEra     pErje

Empty DataFrame
Columns: [fi3S, pc2P]
Index: []

fi3S pc2P 152 0

         fi3S     pc2S
1412  EsEj6ra  EsEj6rE
1412  EsEj6ra    EsErE
1412    EsEra  EsEj6rE
1412    EsEra    EsErE
2232   pEj6ra   pEj6rE
2232   pEj6ra     pErE
2232     pEra   pEj6rE
2232     pEra     pErE

Empty DataFrame
Columns: [fi3S, pc2S]
Index: []

fi3S pc2S 205 0

         fi3S     pc3P
1412  EsEj6ra  EsEj6rE
1412  EsEj6ra    EsErE
1412    EsEra  EsEj6rE
1412    EsEra    EsErE
2232   pEj6ra   pEj6rE
2232   pEj6ra     pErE
2232     pEra   pEj6rE
2232     pEra     pErE

Empty DataFrame
Columns: [fi3S, pc3P]
Index: []

fi3S pc3P 169 0

         fi3S     pc3S
234    asjEra   asjErE
234    aswara   asjErE
1412  EsEj6ra  EsEj6rE
1412  EsEj6ra    EsErE
1412    EsEra  EsEj6rE
1412    EsEra    EsErE
2232   pEj6ra   pEj6rE
2232   pEj6ra     pErE
2232     pEra   pEj6rE
2232     pEra     pErE

Empty DataFrame
Columns: [fi3S, pc3S]
Index: []

fi3S pc3S 578 0

         fi3S   pi1P
234    asjEra  asEjô
234    aswara  asEjô
1412  EsEj6ra  EsEjô
1412    EsEra  EsEjô
2232   pEj6ra   pEjô
2232     pEra   pEjô

Empty DataFrame
Columns: [fi3S, pi1P]
Index: []

fi3S pi1P 488 0

         fi3S  pi1S
234    asjEra  asje
234    asjEra  aswa
234    aswara  asje
234    aswara  aswa
1412  EsEj6ra  EsEj
1412    EsEra  EsEj
1721     aira     E
1721     aira    ai
2232   pEj6ra   pEj
2232     pEra   pEj
2358     pura    p2
2358     pura   pHi

Empty DataFrame
Columns: [fi3S, pi1S]
Index: []

fi3S pi1S 876 0

         fi3S   pi2P
234    asjEra  asEje
234    aswara  asEje
1412  EsEj6ra  EsEje
1412    EsEra  EsEje
2232   pEj6ra   pEje
2232     pEra   pEje

Empty DataFrame
Columns: [fi3S, pi2P]
Index: []

fi3S pi2P 756 0

         fi3S  pi2S
234    asjEra  asje
234    asjEra  aswa
234    aswara  asje
234    aswara  aswa
1412  EsEj6ra  EsEj
1412    EsEra  EsEj
1721     aira     E
1721     aira    ai
2232   pEj6ra   pEj
2232     pEra   pEj

Empty DataFrame
Columns: [fi3S, pi2S]
Index: []

fi3S pi2S 788 0

         fi3S   pi3P
234    asjEra   asEj
234    asjEra   aswa
234    aswara   asEj
234    aswara   aswa
311    balEra   balE
311    balEra  balEj
1412  EsEj6ra   EsEj
1412    EsEra   EsEj
2232   pEj6ra    pEj
2232     pEra    pEj

Empty DataFrame
Columns: [fi3S, pi3P]
Index: []

fi3S pi3P 921 0

           fi3S    pi3S
234      asjEra    asje
234      asjEra    aswa
234      aswara    asje
234      aswara    aswa
311      balEra    balE
311      balEra   balEj
1412    EsEj6ra    EsEj
1412      EsEra    EsEj
1721       aira       E
1721       aira      ai
2232     pEj6ra     pEj
2232       pEra     pEj
2870  rEEsEj6ra  rEEsEj
2870    rEEsEra  rEEsEj

Empty DataFrame
Columns: [fi3S, pi3S]
Index: []

fi3S pi3S 969 0

         fi3S   ppFP
234    asjEra   asiz
234    aswara   asiz
1412  EsEj6ra  EsEje
1412    EsEra  EsEje
2232   pEj6ra   pEje
2232     pEra   pEje

Empty DataFrame
Columns: [fi3S, ppFP]
Index: []

fi3S ppFP 598 0

         fi3S   ppFS
234    asjEra   asiz
234    aswara   asiz
1412  EsEj6ra  EsEje
1412    EsEra  EsEje
2232   pEj6ra   pEje
2232     pEra   pEje

Empty DataFrame
Columns: [fi3S, ppFS]
Index: []

fi3S ppFS 827 0

         fi3S   ppMP
234    asjEra    asi
234    aswara    asi
1412  EsEj6ra  EsEje
1412    EsEra  EsEje
2232   pEj6ra   pEje
2232     pEra   pEje

Empty DataFrame
Columns: [fi3S, ppMP]
Index: []

fi3S ppMP 758 0

           fi3S     ppMS
234      asjEra      asi
234      aswara      asi
1412    EsEj6ra    EsEje
1412      EsEra    EsEje
2232     pEj6ra     pEje
2232       pEra     pEje
2870  rEEsEj6ra  rEEsEje
2870    rEEsEra  rEEsEje

Empty DataFrame
Columns: [fi3S, ppMS]
Index: []

fi3S ppMS 970 0

         fi3S   ps1P
1412  EsEj6ra  EsEjô
1412    EsEra  EsEjô

Empty DataFrame
Columns: [fi3S, ps1P]
Index: []

fi3S ps1P 63 0

         fi3S  ps1S
234    asjEra  asEj
234    asjEra  aswa
234    aswara  asEj
234    aswara  aswa
1412  EsEj6ra  EsEj
1412    EsEra  EsEj
2232   pEj6ra   pEj
2232     pEra   pEj

Empty DataFrame
Columns: [fi3S, ps1S]
Index: []

fi3S ps1S 471 0

         fi3S   ps2P
234    asjEra  asEje
234    aswara  asEje
1412  EsEj6ra  EsEje
1412    EsEra  EsEje
2232   pEj6ra   pEje
2232     pEra   pEje

Empty DataFrame
Columns: [fi3S, ps2P]
Index: []

fi3S ps2P 248 0

         fi3S  ps2S
234    asjEra  asEj
234    asjEra  aswa
234    aswara  asEj
234    aswara  aswa
1412  EsEj6ra  EsEj
1412    EsEra  EsEj
2232   pEj6ra   pEj
2232     pEra   pEj

Empty DataFrame
Columns: [fi3S, ps2S]
Index: []

fi3S ps2S 391 0

         fi3S  ps3P
234    asjEra  aswa
234    aswara  aswa
1412  EsEj6ra  EsEj
1412    EsEra  EsEj
2232   pEj6ra   pEj
2232     pEra   pEj

Empty DataFrame
Columns: [fi3S, ps3P]
Index: []

fi3S ps3P 367 0

         fi3S  ps3S
234    asjEra  asEj
234    asjEra  aswa
234    aswara  asEj
234    aswara  aswa
1412  EsEj6ra  EsEj
1412    EsEra  EsEj
2232   pEj6ra   pEj
2232     pEra   pEj

Empty DataFrame
Columns: [fi3S, ps3S]
Index: []

fi3S ps3S 819 0
ii1P ii1S 116 0
ii1P ii2P 109 0
ii1P ii2S 113 0
ii1P ii3P 116 0
ii1P ii3S 117 0
ii1P inf 117 0
ii1P is1S 2 0
ii1P is2P 0 0
ii1P is2S 0 0
ii1P is3P 1 0
ii1P is3S 4 0
ii1P pI1P 100 4
ii1P pI2P 113 0

       ii1P pI2S
3391  vuljô   v2
3391  vuljô  v9j

Empty DataFrame
Columns: [ii1P, pI2S]
Index: []

ii1P pI2S 112 0
ii1P pP 116 0
ii1P pc1P 31 0

       ii1P     pc1S
1412  EsEjô  EsEj6rE
1412  EsEjô    EsErE

Empty DataFrame
Columns: [ii1P, pc1S]
Index: []

ii1P pc1S 106 0

       ii1P      pc2P
1412  EsEjô  EsEj6rje
1412  EsEjô    EsErje

Empty DataFrame
Columns: [ii1P, pc2P]
Index: []

ii1P pc2P 75 0

       ii1P     pc2S
1412  EsEjô  EsEj6rE
1412  EsEjô    EsErE

Empty DataFrame
Columns: [ii1P, pc2S]
Index: []

ii1P pc2S 87 0

       ii1P     pc3P
1412  EsEjô  EsEj6rE
1412  EsEjô    EsErE

Empty DataFrame
Columns: [ii1P, pc3P]
Index: []

ii1P pc3P 79 0

       ii1P     pc3S
1412  EsEjô  EsEj6rE
1412  EsEjô    EsErE

Empty DataFrame
Columns: [ii1P, pc3S]
Index: []

ii1P pc3S 112 0
ii1P pi1P 111 5

       ii1P pi1S
2358  puvjô   p2
2358  puvjô  pHi

Empty DataFrame
Columns: [ii1P, pi1S]
Index: []

ii1P pi1S 116 0
ii1P pi2P 117 0
ii1P pi2S 115 0
ii1P pi3P 116 0
ii1P pi3S 117 0
ii1P ppFP 96 0
ii1P ppFS 107 0
ii1P ppMP 100 0
ii1P ppMS 117 0
ii1P ps1P 5 46
ii1P ps1S 109 0
ii1P ps2P 98 0
ii1P ps2S 101 0
ii1P ps3P 98 0
ii1P ps3S 115 0
ii1S ii2P 205 0
ii1S ii2S 0 322
ii1S ii3P 0 417
ii1S ii3S 0 586
ii1S inf 595 0
ii1S is1S 3 0
ii1S is2P 5 0
ii1S is2S 2 0
ii1S is3P 1 0
ii1S is3S 4 0
ii1S pI1P 345 0

      ii1S    pI2P
234  asEjE   asEje
234  asEjE  aswaje

Empty DataFrame
Columns: [ii1S, pI2P]
Index: []

ii1S pI2P 535 0

        ii1S   pI2S
234    asEjE   asje
234    asEjE   aswa
311   balEjE   balE
311   balEjE  balEj
3391    vulE     v2
3391    vulE    v9j

Empty DataFrame
Columns: [ii1S, pI2S]
Index: []

ii1S pI2S 533 0
ii1S pP 542 0
ii1S pc1P 38 0

       ii1S     pc1S
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE
2232   pEjE   pEj6rE
2232   pEjE     pErE

Empty DataFrame
Columns: [ii1S, pc1S]
Index: []

ii1S pc1S 355 0

       ii1S      pc2P
1412  EsEjE  EsEj6rje
1412  EsEjE    EsErje
2232   pEjE   pEj6rje
2232   pEjE     pErje

Empty DataFrame
Columns: [ii1S, pc2P]
Index: []

ii1S pc2P 144 0

       ii1S     pc2S
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE
2232   pEjE   pEj6rE
2232   pEjE     pErE

Empty DataFrame
Columns: [ii1S, pc2S]
Index: []

ii1S pc2S 200 0

       ii1S     pc3P
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE
2232   pEjE   pEj6rE
2232   pEjE     pErE

Empty DataFrame
Columns: [ii1S, pc3P]
Index: []

ii1S pc3P 159 0

       ii1S     pc3S
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE
2232   pEjE   pEj6rE
2232   pEjE     pErE

Empty DataFrame
Columns: [ii1S, pc3S]
Index: []

ii1S pc3S 401 0
ii1S pi1P 404 0

       ii1S  pi1S
234   asEjE  asje
234   asEjE  aswa
1721   aisE     E
1721   aisE    ai
2358   puvE    p2
2358   puvE   pHi

Empty DataFrame
Columns: [ii1S, pi1S]
Index: []

ii1S pi1S 587 0
ii1S pi2P 567 0

       ii1S  pi2S
234   asEjE  asje
234   asEjE  aswa
1721   aisE     E
1721   aisE    ai

Empty DataFrame
Columns: [ii1S, pi2S]
Index: []

ii1S pi2S 574 0

       ii1S   pi3P
234   asEjE   asEj
234   asEjE   aswa
311  balEjE   balE
311  balEjE  balEj

Empty DataFrame
Columns: [ii1S, pi3P]
Index: []

ii1S pi3P 580 0

        ii1S   pi3S
234    asEjE   asje
234    asEjE   aswa
311   balEjE   balE
311   balEjE  balEj
1721    aisE      E
1721    aisE     ai

Empty DataFrame
Columns: [ii1S, pi3S]
Index: []

ii1S pi3S 591 0
ii1S ppFP 375 0
ii1S ppFS 500 0
ii1S ppMP 459 0
ii1S ppMS 591 0
ii1S ps1P 62 0

      ii1S  ps1S
234  asEjE  asEj
234  asEjE  aswa

Empty DataFrame
Columns: [ii1S, ps1S]
Index: []

ii1S ps1S 414 0
ii1S ps2P 237 0

      ii1S  ps2S
234  asEjE  asEj
234  asEjE  aswa

Empty DataFrame
Columns: [ii1S, ps2S]
Index: []

ii1S ps2S 362 0
ii1S ps3P 305 0

      ii1S  ps3S
234  asEjE  asEj
234  asEjE  aswa

Empty DataFrame
Columns: [ii1S, ps3S]
Index: []

ii1S ps3S 516 0
ii2P ii2S 198 0
ii2P ii3P 201 0
ii2P ii3S 209 0
ii2P inf 202 7
ii2P is1S 2 0
ii2P is2P 0 1
ii2P is2S 0 0
ii2P is3P 1 0
ii2P is3S 4 0
ii2P pI1P 154 0
ii2P pI2P 180 13

       ii2P pI2S
3391  vulje   v2
3391  vulje  v9j

Empty DataFrame
Columns: [ii2P, pI2S]
Index: []

ii2P pI2S 195 0
ii2P pP 203 0
ii2P pc1P 34 0

       ii2P     pc1S
1412  EsEje  EsEj6rE
1412  EsEje    EsErE
2232   pEje   pEj6rE
2232   pEje     pErE

Empty DataFrame
Columns: [ii2P, pc1S]
Index: []

ii2P pc1S 176 0

       ii2P      pc2P
1412  EsEje  EsEj6rje
1412  EsEje    EsErje
2232   pEje   pEj6rje
2232   pEje     pErje

Empty DataFrame
Columns: [ii2P, pc2P]
Index: []

ii2P pc2P 112 0

       ii2P     pc2S
1412  EsEje  EsEj6rE
1412  EsEje    EsErE
2232   pEje   pEj6rE
2232   pEje     pErE

Empty DataFrame
Columns: [ii2P, pc2S]
Index: []

ii2P pc2S 141 0

       ii2P     pc3P
1412  EsEje  EsEj6rE
1412  EsEje    EsErE
2232   pEje   pEj6rE
2232   pEje     pErE

Empty DataFrame
Columns: [ii2P, pc3P]
Index: []

ii2P pc3P 115 0

       ii2P     pc3S
1412  EsEje  EsEj6rE
1412  EsEje    EsErE
2232   pEje   pEj6rE
2232   pEje     pErE

Empty DataFrame
Columns: [ii2P, pc3S]
Index: []

ii2P pc3S 189 0
ii2P pi1P 189 0

       ii2P pi1S
1721  aisje    E
1721  aisje   ai
2358  puvje   p2
2358  puvje  pHi

Empty DataFrame
Columns: [ii2P, pi1S]
Index: []

ii2P pi1S 208 0
ii2P pi2P 195 13

       ii2P pi2S
1721  aisje    E
1721  aisje   ai

Empty DataFrame
Columns: [ii2P, pi2S]
Index: []

ii2P pi2S 206 0
ii2P pi3P 208 0

       ii2P pi3S
1721  aisje    E
1721  aisje   ai

Empty DataFrame
Columns: [ii2P, pi3S]
Index: []

ii2P pi3S 209 0
ii2P ppFP 149 6
ii2P ppFS 177 6
ii2P ppMP 166 6
ii2P ppMS 200 7
ii2P ps1P 53 0
ii2P ps1S 181 0
ii2P ps2P 5 145
ii2P ps2S 170 0
ii2P ps3P 161 0
ii2P ps3S 200 0
ii2S ii3P 0 286
ii2S ii3S 0 327
ii2S inf 328 0
ii2S is1S 3 0
ii2S is2P 5 0
ii2S is2S 2 0
ii2S is3P 1 0
ii2S is3S 4 0
ii2S pI1P 221 0

      ii2S    pI2P
234  asEjE   asEje
234  asEjE  aswaje

Empty DataFrame
Columns: [ii2S, pI2P]
Index: []

ii2S pI2P 300 0

       ii2S  pI2S
234   asEjE  asje
234   asEjE  aswa
3391   vulE    v2
3391   vulE   v9j

Empty DataFrame
Columns: [ii2S, pI2S]
Index: []

ii2S pI2S 305 0
ii2S pP 318 0
ii2S pc1P 38 0

       ii2S     pc1S
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE
2232   pEjE   pEj6rE
2232   pEjE     pErE

Empty DataFrame
Columns: [ii2S, pc1S]
Index: []

ii2S pc1S 255 0

       ii2S      pc2P
1412  EsEjE  EsEj6rje
1412  EsEjE    EsErje
2232   pEjE   pEj6rje
2232   pEjE     pErje

Empty DataFrame
Columns: [ii2S, pc2P]
Index: []

ii2S pc2P 128 0

       ii2S     pc2S
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE
2232   pEjE   pEj6rE
2232   pEjE     pErE

Empty DataFrame
Columns: [ii2S, pc2S]
Index: []

ii2S pc2S 180 0

       ii2S     pc3P
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE
2232   pEjE   pEj6rE
2232   pEjE     pErE

Empty DataFrame
Columns: [ii2S, pc3P]
Index: []

ii2S pc3P 145 0

       ii2S     pc3S
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE
2232   pEjE   pEj6rE
2232   pEjE     pErE

Empty DataFrame
Columns: [ii2S, pc3S]
Index: []

ii2S pc3S 267 0
ii2S pi1P 267 0

       ii2S  pi1S
234   asEjE  asje
234   asEjE  aswa
1721   aisE     E
1721   aisE    ai
2358   puvE    p2
2358   puvE   pHi

Empty DataFrame
Columns: [ii2S, pi1S]
Index: []

ii2S pi1S 323 0
ii2S pi2P 326 0

       ii2S  pi2S
234   asEjE  asje
234   asEjE  aswa
1721   aisE     E
1721   aisE    ai

Empty DataFrame
Columns: [ii2S, pi2S]
Index: []

ii2S pi2S 320 0

      ii2S  pi3P
234  asEjE  asEj
234  asEjE  aswa

Empty DataFrame
Columns: [ii2S, pi3P]
Index: []

ii2S pi3P 324 0

       ii2S  pi3S
234   asEjE  asje
234   asEjE  aswa
1721   aisE     E
1721   aisE    ai

Empty DataFrame
Columns: [ii2S, pi3S]
Index: []

ii2S pi3S 326 0
ii2S ppFP 221 0
ii2S ppFS 279 0
ii2S ppMP 257 0
ii2S ppMS 326 0
ii2S ps1P 60 0

      ii2S  ps1S
234  asEjE  asEj
234  asEjE  aswa

Empty DataFrame
Columns: [ii2S, ps1S]
Index: []

ii2S ps1S 277 0
ii2S ps2P 192 0

      ii2S  ps2S
234  asEjE  asEj
234  asEjE  aswa

Empty DataFrame
Columns: [ii2S, ps2S]
Index: []

ii2S ps2S 261 0
ii2S ps3P 227 0

      ii2S  ps3S
234  asEjE  asEj
234  asEjE  aswa

Empty DataFrame
Columns: [ii2S, ps3S]
Index: []

ii2S ps3S 311 0
ii3P ii3S 0 527
ii3P inf 532 0
ii3P is1S 3 0
ii3P is2P 4 0
ii3P is2S 2 0
ii3P is3P 1 0
ii3P is3S 4 0
ii3P pI1P 304 0

      ii3P    pI2P
234  asEjE   asEje
234  asEjE  aswaje

Empty DataFrame
Columns: [ii3P, pI2P]
Index: []

ii3P pI2P 468 0

       ii3P  pI2S
234   asEjE  asje
234   asEjE  aswa
3391   vulE    v2
3391   vulE   v9j

Empty DataFrame
Columns: [ii3P, pI2S]
Index: []

ii3P pI2S 459 0
ii3P pP 501 0
ii3P pc1P 37 0

       ii3P     pc1S
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE
2232   pEjE   pEj6rE
2232   pEjE     pErE

Empty DataFrame
Columns: [ii3P, pc1S]
Index: []

ii3P pc1S 317 0

       ii3P      pc2P
1412  EsEjE  EsEj6rje
1412  EsEjE    EsErje
2232   pEjE   pEj6rje
2232   pEjE     pErje

Empty DataFrame
Columns: [ii3P, pc2P]
Index: []

ii3P pc2P 137 0

       ii3P     pc2S
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE
2232   pEjE   pEj6rE
2232   pEjE     pErE

Empty DataFrame
Columns: [ii3P, pc2S]
Index: []

ii3P pc2S 188 0

       ii3P     pc3P
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE
2232   pEjE   pEj6rE
2232   pEjE     pErE

Empty DataFrame
Columns: [ii3P, pc3P]
Index: []

ii3P pc3P 164 0

       ii3P     pc3S
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE
2232   pEjE   pEj6rE
2232   pEjE     pErE

Empty DataFrame
Columns: [ii3P, pc3S]
Index: []

ii3P pc3S 404 0
ii3P pi1P 377 0

       ii3P  pi1S
234   asEjE  asje
234   asEjE  aswa
1721   aisE     E
1721   aisE    ai
2358   puvE    p2
2358   puvE   pHi

Empty DataFrame
Columns: [ii3P, pi1S]
Index: []

ii3P pi1S 503 0
ii3P pi2P 491 0

       ii3P  pi2S
234   asEjE  asje
234   asEjE  aswa
1721   aisE     E
1721   aisE    ai

Empty DataFrame
Columns: [ii3P, pi2S]
Index: []

ii3P pi2S 495 0

      ii3P  pi3P
234  asEjE  asEj
234  asEjE  aswa

Empty DataFrame
Columns: [ii3P, pi3P]
Index: []

ii3P pi3P 531 0

       ii3P  pi3S
234   asEjE  asje
234   asEjE  aswa
1721   aisE     E
1721   aisE    ai

Empty DataFrame
Columns: [ii3P, pi3S]
Index: []

ii3P pi3S 530 0
ii3P ppFP 366 0
ii3P ppFS 462 0
ii3P ppMP 434 0
ii3P ppMS 526 0
ii3P ps1P 62 0

      ii3P  ps1S
234  asEjE  asEj
234  asEjE  aswa

Empty DataFrame
Columns: [ii3P, ps1S]
Index: []

ii3P ps1S 345 0
ii3P ps2P 216 0

      ii3P  ps2S
234  asEjE  asEj
234  asEjE  aswa

Empty DataFrame
Columns: [ii3P, ps2S]
Index: []

ii3P ps2S 312 0
ii3P ps3P 318 0

      ii3P  ps3S
234  asEjE  asEj
234  asEjE  aswa

Empty DataFrame
Columns: [ii3P, ps3S]
Index: []

ii3P ps3S 487 0
ii3S inf 1147 0
ii3S is1S 3 0
ii3S is2P 5 0
ii3S is2S 2 0
ii3S is3P 1 0
ii3S is3S 4 0
ii3S pI1P 415 0

      ii3S    pI2P
234  asEjE   asEje
234  asEjE  aswaje

Empty DataFrame
Columns: [ii3S, pI2P]
Index: []

ii3S pI2P 838 0

        ii3S   pI2S
234    asEjE   asje
234    asEjE   aswa
311   balEjE   balE
311   balEjE  balEj
3391    vulE     v2
3391    vulE    v9j

Empty DataFrame
Columns: [ii3S, pI2S]
Index: []

ii3S pI2S 848 0
ii3S pP 932 0
ii3S pc1P 38 0

       ii3S     pc1S
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE
2232   pEjE   pEj6rE
2232   pEjE     pErE

Empty DataFrame
Columns: [ii3S, pc1S]
Index: []

ii3S pc1S 402 0

       ii3S      pc2P
1412  EsEjE  EsEj6rje
1412  EsEjE    EsErje
2232   pEjE   pEj6rje
2232   pEjE     pErje

Empty DataFrame
Columns: [ii3S, pc2P]
Index: []

ii3S pc2P 154 0

       ii3S     pc2S
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE
2232   pEjE   pEj6rE
2232   pEjE     pErE

Empty DataFrame
Columns: [ii3S, pc2S]
Index: []

ii3S pc2S 206 0

       ii3S     pc3P
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE
2232   pEjE   pEj6rE
2232   pEjE     pErE

Empty DataFrame
Columns: [ii3S, pc3P]
Index: []

ii3S pc3P 169 0

       ii3S     pc3S
1412  EsEjE  EsEj6rE
1412  EsEjE    EsErE
2232   pEjE   pEj6rE
2232   pEjE     pErE

Empty DataFrame
Columns: [ii3S, pc3S]
Index: []

ii3S pc3S 568 0
ii3S pi1P 508 0

       ii3S  pi1S
234   asEjE  asje
234   asEjE  aswa
1721   aisE     E
1721   aisE    ai
2358   puvE    p2
2358   puvE   pHi

Empty DataFrame
Columns: [ii3S, pi1S]
Index: []

ii3S pi1S 1022 0
ii3S pi2P 885 0

       ii3S  pi2S
234   asEjE  asje
234   asEjE  aswa
1721   aisE     E
1721   aisE    ai

Empty DataFrame
Columns: [ii3S, pi2S]
Index: []

ii3S pi2S 961 0

       ii3S   pi3P
234   asEjE   asEj
234   asEjE   aswa
311  balEjE   balE
311  balEjE  balEj

Empty DataFrame
Columns: [ii3S, pi3P]
Index: []

ii3S pi3P 1107 0

        ii3S   pi3S
234    asEjE   asje
234    asEjE   aswa
311   balEjE   balE
311   balEjE  balEj
1721    aisE      E
1721    aisE     ai

Empty DataFrame
Columns: [ii3S, pi3S]
Index: []

ii3S pi3S 1148 0
ii3S ppFP 632 0
ii3S ppFS 903 0
ii3S ppMP 815 0
ii3S ppMS 1116 0
ii3S ps1P 63 0

      ii3S  ps1S
234  asEjE  asEj
234  asEjE  aswa

Empty DataFrame
Columns: [ii3S, ps1S]
Index: []

ii3S ps1S 485 0
ii3S ps2P 251 0

      ii3S  ps2S
234  asEjE  asEj
234  asEjE  aswa

Empty DataFrame
Columns: [ii3S, ps2S]
Index: []

ii3S ps2S 398 0
ii3S ps3P 364 0

      ii3S  ps3S
234  asEjE  asEj
234  asEjE  aswa

Empty DataFrame
Columns: [ii3S, ps3S]
Index: []

ii3S ps3S 822 0
inf is1S 3 0
inf is2P 5 0
inf is2S 2 0
inf is3P 1 0
inf is3S 4 0
inf pI1P 441 0

       inf    pI2P
234  aswar   asEje
234  aswar  aswaje

Empty DataFrame
Columns: [inf, pI2P]
Index: []

inf pI2P 197 940

         inf   pI2S
234    aswar   asje
234    aswar   aswa
311   balEje   balE
311   balEje  balEj
3391  vulwar     v2
3391  vulwar    v9j

Empty DataFrame
Columns: [inf, pI2S]
Index: []

inf pI2S 1102 0
inf pP 1070 0
inf pc1P 38 0

        inf     pc1S
1412  EsEje  EsEj6rE
1412  EsEje    EsErE
2232   pEje   pEj6rE
2232   pEje     pErE

Empty DataFrame
Columns: [inf, pc1S]
Index: []

inf pc1S 408 0

        inf      pc2P
1412  EsEje  EsEj6rje
1412  EsEje    EsErje
2232   pEje   pEj6rje
2232   pEje     pErje

Empty DataFrame
Columns: [inf, pc2P]
Index: []

inf pc2P 154 0

        inf     pc2S
1412  EsEje  EsEj6rE
1412  EsEje    EsErE
2232   pEje   pEj6rE
2232   pEje     pErE

Empty DataFrame
Columns: [inf, pc2S]
Index: []

inf pc2S 206 0

        inf     pc3P
1412  EsEje  EsEj6rE
1412  EsEje    EsErE
2232   pEje   pEj6rE
2232   pEje     pErE

Empty DataFrame
Columns: [inf, pc3P]
Index: []

inf pc3P 169 0

        inf     pc3S
1412  EsEje  EsEj6rE
1412  EsEje    EsErE
2232   pEje   pEj6rE
2232   pEje     pErE

Empty DataFrame
Columns: [inf, pc3S]
Index: []

inf pc3S 589 0
inf pi1P 531 0

         inf  pi1S
234    aswar  asje
234    aswar  aswa
1721     air     E
1721     air    ai
2358  puvwar    p2
2358  puvwar   pHi

Empty DataFrame
Columns: [inf, pi1S]
Index: []

inf pi1S 1414 0
inf pi2P 187 798

        inf  pi2S
234   aswar  asje
234   aswar  aswa
1721    air     E
1721    air    ai

Empty DataFrame
Columns: [inf, pi2S]
Index: []

inf pi2S 1130 0

        inf   pi3P
234   aswar   asEj
234   aswar   aswa
311  balEje   balE
311  balEje  balEj

Empty DataFrame
Columns: [inf, pi3P]
Index: []

inf pi3P 1506 0

         inf   pi3S
234    aswar   asje
234    aswar   aswa
311   balEje   balE
311   balEje  balEj
1721     air      E
1721     air     ai

Empty DataFrame
Columns: [inf, pi3S]
Index: []

inf pi3S 2272 0
inf ppFP 168 678
inf ppFS 280 1393
inf ppMP 226 1150
inf ppMS 392 2257
inf ps1P 63 0

       inf  ps1S
234  aswar  asEj
234  aswar  aswa

Empty DataFrame
Columns: [inf, ps1S]
Index: []

inf ps1S 493 0
inf ps2P 239 12

       inf  ps2S
234  aswar  asEj
234  aswar  aswa

Empty DataFrame
Columns: [inf, ps2S]
Index: []

inf ps2S 404 0
inf ps3P 371 0

       inf  ps3S
234  aswar  asEj
234  aswar  aswa

Empty DataFrame
Columns: [inf, ps3S]
Index: []

inf ps3S 928 0
is1S is2P 1 0
is1S is2S 0 1
is1S is3P 0 1
is1S is3S 2 0
is1S pI1P 3 0
is1S pI2P 2 0
is1S pI2S 3 0
is1S pP 3 0
is1S pc1P 2 0
is1S pc1S 3 0
is1S pc2P 3 0
is1S pc2S 3 0
is1S pc3P 3 0
is1S pc3S 3 0
is1S pi1P 3 0
is1S pi1S 3 0
is1S pi2P 3 0
is1S pi2S 3 0
is1S pi3P 2 1
is1S pi3S 3 0
is1S ppFP 2 0
is1S ppFS 2 0
is1S ppMP 2 0
is1S ppMS 3 0
is1S ps1P 2 0
is1S ps1S 2 1
is1S ps2P 3 0
is1S ps2S 2 1
is1S ps3P 2 1
is1S ps3S 2 1
is2P is2S 2 0
is2P is3P 0 0
is2P is3S 0 0
is2P pI1P 4 0
is2P pI2P 5 0
is2P pI2S 5 0
is2P pP 5 0
is2P pc1P 1 0
is2P pc1S 5 0
is2P pc2P 4 0
is2P pc2S 5 0
is2P pc3P 3 0
is2P pc3S 5 0
is2P pi1P 5 0
is2P pi1S 5 0
is2P pi2P 5 0
is2P pi2S 5 0
is2P pi3P 5 0
is2P pi3S 5 0
is2P ppFP 3 0
is2P ppFS 4 0
is2P ppMP 4 0
is2P ppMS 5 0
is2P ps1P 2 0
is2P ps1S 5 0
is2P ps2P 0 5
is2P ps2S 5 0
is2P ps3P 5 0
is2P ps3S 5 0
is2S is3P 0 0
is2S is3S 0 0
is2S pI1P 2 0
is2S pI2P 2 0
is2S pI2S 2 0
is2S pP 2 0
is2S pc1P 1 0
is2S pc1S 2 0
is2S pc2P 2 0
is2S pc2S 2 0
is2S pc3P 2 0
is2S pc3S 2 0
is2S pi1P 2 0
is2S pi1S 2 0
is2S pi2P 2 0
is2S pi2S 2 0
is2S pi3P 0 2
is2S pi3S 2 0
is2S ppFP 2 0
is2S ppFS 2 0
is2S ppMP 2 0
is2S ppMS 2 0
is2S ps1P 1 0
is2S ps1S 0 2
is2S ps2P 2 0
is2S ps2S 0 2
is2S ps3P 0 2
is2S ps3S 0 2
is3P is3S 1 0
is3P pI1P 1 0
is3P pI2P 1 0
is3P pI2S 1 0
is3P pP 1 0
is3P pc1P 1 0
is3P pc1S 1 0
is3P pc2P 1 0
is3P pc2S 1 0
is3P pc3P 1 0
is3P pc3S 1 0
is3P pi1P 1 0
is3P pi1S 1 0
is3P pi2P 1 0
is3P pi2S 1 0
is3P pi3P 1 0
is3P pi3S 1 0
is3P ppFP 0 0
is3P ppFS 0 0
is3P ppMP 0 0
is3P ppMS 1 0
is3P ps1P 1 0
is3P ps1S 1 0
is3P ps2P 1 0
is3P ps2S 1 0
is3P ps3P 1 0
is3P ps3S 1 0
is3S pI1P 3 0
is3S pI2P 2 0
is3S pI2S 3 0
is3S pP 4 0
is3S pc1P 4 0
is3S pc1S 4 0
is3S pc2P 4 0
is3S pc2S 4 0
is3S pc3P 4 0
is3S pc3S 4 0
is3S pi1P 4 0

     is3S pi1S
2358   py   p2
2358   py  pHi

Empty DataFrame
Columns: [is3S, pi1S]
Index: []

is3S pi1S 4 0
is3S pi2P 4 0
is3S pi2S 4 0
is3S pi3P 4 0
is3S pi3S 4 0
is3S ppFP 1 1
is3S ppFS 1 1
is3S ppMP 1 1
is3S ppMS 2 2
is3S ps1P 4 0
is3S ps1S 4 0
is3S ps2P 4 0
is3S ps2S 4 0
is3S ps3P 4 0
is3S ps3S 4 0

      pI1P    pI2P
234  asEjô   asEje
234  asEjô  aswaje

Empty DataFrame
Columns: [pI1P, pI2P]
Index: []

pI1P pI2P 435 0

       pI1P  pI2S
234   asEjô  asje
234   asEjô  aswa
3391   vulô    v2
3391   vulô   v9j

Empty DataFrame
Columns: [pI1P, pI2S]
Index: []

pI1P pI2S 423 0
pI1P pP 403 0
pI1P pc1P 35 0

       pI1P     pc1S
1412  EsEjô  EsEj6rE
1412  EsEjô    EsErE
2232   pEjô   pEj6rE
2232   pEjô     pErE

Empty DataFrame
Columns: [pI1P, pc1S]
Index: []

pI1P pc1S 300 0

       pI1P      pc2P
1412  EsEjô  EsEj6rje
1412  EsEjô    EsErje
2232   pEjô   pEj6rje
2232   pEjô     pErje

Empty DataFrame
Columns: [pI1P, pc2P]
Index: []

pI1P pc2P 120 0

       pI1P     pc2S
1412  EsEjô  EsEj6rE
1412  EsEjô    EsErE
2232   pEjô   pEj6rE
2232   pEjô     pErE

Empty DataFrame
Columns: [pI1P, pc2S]
Index: []

pI1P pc2S 169 0

       pI1P     pc3P
1412  EsEjô  EsEj6rE
1412  EsEjô    EsErE
2232   pEjô   pEj6rE
2232   pEjô     pErE

Empty DataFrame
Columns: [pI1P, pc3P]
Index: []

pI1P pc3P 137 0

       pI1P     pc3S
1412  EsEjô  EsEj6rE
1412  EsEjô    EsErE
2232   pEjô   pEj6rE
2232   pEjô     pErE

Empty DataFrame
Columns: [pI1P, pc3S]
Index: []

pI1P pc3S 328 0
pI1P pi1P 3 337

      pI1P  pi1S
234  asEjô  asje
234  asEjô  aswa

Empty DataFrame
Columns: [pI1P, pi1S]
Index: []

pI1P pi1S 431 0
pI1P pi2P 410 0

      pI1P  pi2S
234  asEjô  asje
234  asEjô  aswa

Empty DataFrame
Columns: [pI1P, pi2S]
Index: []

pI1P pi2S 415 0

      pI1P  pi3P
234  asEjô  asEj
234  asEjô  aswa

Empty DataFrame
Columns: [pI1P, pi3P]
Index: []

pI1P pi3P 429 0

      pI1P  pi3S
234  asEjô  asje
234  asEjô  aswa

Empty DataFrame
Columns: [pI1P, pi3S]
Index: []

pI1P pi3S 441 0
pI1P ppFP 338 0
pI1P ppFS 399 0
pI1P ppMP 373 0
pI1P ppMS 440 0
pI1P ps1P 57 5

      pI1P  ps1S
234  asEjô  asEj
234  asEjô  aswa

Empty DataFrame
Columns: [pI1P, ps1S]
Index: []

pI1P ps1S 329 0
pI1P ps2P 215 0

      pI1P  ps2S
234  asEjô  asEj
234  asEjô  aswa

Empty DataFrame
Columns: [pI1P, ps2S]
Index: []

pI1P ps2S 291 0
pI1P ps3P 263 0

      pI1P  ps3S
234  asEjô  asEj
234  asEjô  aswa

Empty DataFrame
Columns: [pI1P, ps3S]
Index: []

pI1P ps3S 412 0

        pI2P   pI2S
234    asEje   asje
234    asEje   aswa
234   aswaje   asje
234   aswaje   aswa
311   balEje   balE
311   balEje  balEj
3391    v2je     v2
3391    v2je    v9j

Empty DataFrame
Columns: [pI2P, pI2S]
Index: []

pI2P pI2S 971 0

       pI2P     pP
234   asEje  asEjâ
234  aswaje  asEjâ

Empty DataFrame
Columns: [pI2P, pP]
Index: []

pI2P pP 812 0
pI2P pc1P 35 0

        pI2P     pc1S
234    asEje   asjErE
234   aswaje   asjErE
1412   EsEje  EsEj6rE
1412   EsEje    EsErE
2232    pEje   pEj6rE
2232    pEje     pErE

Empty DataFrame
Columns: [pI2P, pc1S]
Index: []

pI2P pc1S 394 0

       pI2P      pc2P
1412  EsEje  EsEj6rje
1412  EsEje    EsErje
2232   pEje   pEj6rje
2232   pEje     pErje

Empty DataFrame
Columns: [pI2P, pc2P]
Index: []

pI2P pc2P 148 0

       pI2P     pc2S
1412  EsEje  EsEj6rE
1412  EsEje    EsErE
2232   pEje   pEj6rE
2232   pEje     pErE

Empty DataFrame
Columns: [pI2P, pc2S]
Index: []

pI2P pc2S 199 0

       pI2P     pc3P
1412  EsEje  EsEj6rE
1412  EsEje    EsErE
2232   pEje   pEj6rE
2232   pEje     pErE

Empty DataFrame
Columns: [pI2P, pc3P]
Index: []

pI2P pc3P 158 0

        pI2P     pc3S
234    asEje   asjErE
234   aswaje   asjErE
1412   EsEje  EsEj6rE
1412   EsEje    EsErE
2232    pEje   pEj6rE
2232    pEje     pErE

Empty DataFrame
Columns: [pI2P, pc3S]
Index: []

pI2P pc3S 520 0

       pI2P   pi1P
234   asEje  asEjô
234  aswaje  asEjô

Empty DataFrame
Columns: [pI2P, pi1P]
Index: []

pI2P pi1P 487 0

        pI2P  pi1S
234    asEje  asje
234    asEje  aswa
234   aswaje  asje
234   aswaje  aswa
1721    aise     E
1721    aise    ai

Empty DataFrame
Columns: [pI2P, pi1S]
Index: []

pI2P pi1S 1005 0

       pI2P   pi2P
234   asEje  asEje
234  aswaje  asEje

      pI2P   pi2P
234  asEje  asEje

pI2P pi2P 3 800

        pI2P  pi2S
234    asEje  asje
234    asEje  aswa
234   aswaje  asje
234   aswaje  aswa
1721    aise     E
1721    aise    ai

Empty DataFrame
Columns: [pI2P, pi2S]
Index: []

pI2P pi2S 864 0

       pI2P   pi3P
234   asEje   asEj
234   asEje   aswa
234  aswaje   asEj
234  aswaje   aswa
311  balEje   balE
311  balEje  balEj

Empty DataFrame
Columns: [pI2P, pi3P]
Index: []

pI2P pi3P 959 0

        pI2P   pi3S
234    asEje   asje
234    asEje   aswa
234   aswaje   asje
234   aswaje   aswa
311   balEje   balE
311   balEje  balEj
1721    aise      E
1721    aise     ai

Empty DataFrame
Columns: [pI2P, pi3S]
Index: []

pI2P pi3S 1100 0

       pI2P  ppFP
234   asEje  asiz
234  aswaje  asiz

Empty DataFrame
Columns: [pI2P, ppFP]
Index: []

pI2P ppFP 121 517

       pI2P  ppFS
234   asEje  asiz
234  aswaje  asiz

Empty DataFrame
Columns: [pI2P, ppFS]
Index: []

pI2P ppFS 166 758

       pI2P ppMP
234   asEje  asi
234  aswaje  asi

Empty DataFrame
Columns: [pI2P, ppMP]
Index: []

pI2P ppMP 151 691

       pI2P ppMS
234   asEje  asi
234  aswaje  asi

Empty DataFrame
Columns: [pI2P, ppMS]
Index: []

pI2P ppMS 195 927
pI2P ps1P 61 0

       pI2P  ps1S
234   asEje  asEj
234   asEje  aswa
234  aswaje  asEj
234  aswaje  aswa

Empty DataFrame
Columns: [pI2P, ps1S]
Index: []

pI2P ps1S 479 0

       pI2P   ps2P
234   asEje  asEje
234  aswaje  asEje

      pI2P   ps2P
234  asEje  asEje

pI2P ps2P 228 19

       pI2P  ps2S
234   asEje  asEj
234   asEje  aswa
234  aswaje  asEj
234  aswaje  aswa

Empty DataFrame
Columns: [pI2P, ps2S]
Index: []

pI2P ps2S 386 0

       pI2P  ps3P
234   asEje  aswa
234  aswaje  aswa

Empty DataFrame
Columns: [pI2P, ps3P]
Index: []

pI2P ps3P 345 0

       pI2P  ps3S
234   asEje  asEj
234   asEje  aswa
234  aswaje  asEj
234  aswaje  aswa

Empty DataFrame
Columns: [pI2P, ps3S]
Index: []

pI2P ps3S 773 0

       pI2S      pP
234    asje   asEjâ
234    aswa   asEjâ
311    balE  balEjâ
311   balEj  balEjâ
3391     v2    vulâ
3391    v9j    vulâ

Empty DataFrame
Columns: [pI2S, pP]
Index: []

pI2S pP 804 0

     pI2S     pc1P
3391   v2  vudrijô
3391  v9j  vudrijô

Empty DataFrame
Columns: [pI2S, pc1P]
Index: []

pI2S pc1P 35 0

      pI2S     pc1S
234   asje   asjErE
234   aswa   asjErE
1412  EsEj  EsEj6rE
1412  EsEj    EsErE
2232   pEj   pEj6rE
2232   pEj     pErE
3391    v2    vudrE
3391   v9j    vudrE

Empty DataFrame
Columns: [pI2S, pc1S]
Index: []

pI2S pc1S 394 0

      pI2S      pc2P
1412  EsEj  EsEj6rje
1412  EsEj    EsErje
2232   pEj   pEj6rje
2232   pEj     pErje
3391    v2   vudrije
3391   v9j   vudrije

Empty DataFrame
Columns: [pI2S, pc2P]
Index: []

pI2S pc2P 147 0

      pI2S     pc2S
1412  EsEj  EsEj6rE
1412  EsEj    EsErE
2232   pEj   pEj6rE
2232   pEj     pErE
3391    v2    vudrE
3391   v9j    vudrE

Empty DataFrame
Columns: [pI2S, pc2S]
Index: []

pI2S pc2S 199 0

      pI2S     pc3P
1412  EsEj  EsEj6rE
1412  EsEj    EsErE
2232   pEj   pEj6rE
2232   pEj     pErE
3391    v2    vudrE
3391   v9j    vudrE

Empty DataFrame
Columns: [pI2S, pc3P]
Index: []

pI2S pc3P 159 0

      pI2S     pc3S
234   asje   asjErE
234   aswa   asjErE
1412  EsEj  EsEj6rE
1412  EsEj    EsErE
2232   pEj   pEj6rE
2232   pEj     pErE
3391    v2    vudrE
3391   v9j    vudrE

Empty DataFrame
Columns: [pI2S, pc3S]
Index: []

pI2S pc3S 518 0

      pI2S   pi1P
234   asje  asEjô
234   aswa  asEjô
3391    v2   vulô
3391   v9j   vulô

Empty DataFrame
Columns: [pI2S, pi1P]
Index: []

pI2S pi1P 458 0

       pI2S  pi1S
234    asje  asje
234    asje  aswa
234    aswa  asje
234    aswa  aswa
311    balE  balE
311   balEj  balE
1721     ai     E
1721     ai    ai
3391     v2    v2
3391    v9j    v2

      pI2S  pi1S
234   asje  asje
234   aswa  aswa
311   balE  balE
1721    ai    ai
3391    v2    v2

pI2S pi1S 3 997

      pI2S   pi2P
234   asje  asEje
234   aswa  asEje
3391    v2   vule
3391   v9j   vule

Empty DataFrame
Columns: [pI2S, pi2P]
Index: []

pI2S pi2P 798 0

       pI2S  pi2S
234    asje  asje
234    asje  aswa
234    aswa  asje
234    aswa  aswa
311    balE  balE
311   balEj  balE
1721     ai     E
1721     ai    ai
3391     v2    v2
3391    v9j    v2

      pI2S  pi2S
234   asje  asje
234   aswa  aswa
311   balE  balE
1721    ai    ai
3391    v2    v2

pI2S pi2S 3 901

       pI2S   pi3P
234    asje   asEj
234    asje   aswa
234    aswa   asEj
234    aswa   aswa
311    balE   balE
311    balE  balEj
311   balEj   balE
311   balEj  balEj
3391     v2    v9l
3391    v9j    v9l

      pI2S   pi3P
234   aswa   aswa
311   balE   balE
311  balEj  balEj

pI2S pi3P 150 796

       pI2S   pi3S
234    asje   asje
234    asje   aswa
234    aswa   asje
234    aswa   aswa
311    balE   balE
311    balE  balEj
311   balEj   balE
311   balEj  balEj
1721     ai      E
1721     ai     ai
3391     v2     v2
3391    v9j     v2

       pI2S   pi3S
234    asje   asje
234    aswa   aswa
311    balE   balE
311   balEj  balEj
1721     ai     ai
3391     v2     v2

pI2S pi3S 3 1075

       pI2S    ppFP
234    asje    asiz
234    aswa    asiz
311    balE  balEje
311   balEj  balEje
3391     v2    vuly
3391    v9j    vuly

Empty DataFrame
Columns: [pI2S, ppFP]
Index: []

pI2S ppFP 588 24

       pI2S    ppFS
234    asje    asiz
234    aswa    asiz
311    balE  balEje
311   balEj  balEje
3391     v2    vuly
3391    v9j    vuly

Empty DataFrame
Columns: [pI2S, ppFS]
Index: []

pI2S ppFS 854 41

       pI2S    ppMP
234    asje     asi
234    aswa     asi
311    balE  balEje
311   balEj  balEje
3391     v2    vuly
3391    v9j    vuly

Empty DataFrame
Columns: [pI2S, ppMP]
Index: []

pI2S ppMP 740 61

       pI2S    ppMS
234    asje     asi
234    aswa     asi
311    balE  balEje
311   balEj  balEje
3391     v2    vuly
3391    v9j    vuly

Empty DataFrame
Columns: [pI2S, ppMS]
Index: []

pI2S ppMS 1000 84
pI2S ps1P 60 0

      pI2S  ps1S
234   asje  asEj
234   asje  aswa
234   aswa  asEj
234   aswa  aswa
3391    v2   v9j
3391   v9j   v9j

      pI2S  ps1S
234   aswa  aswa
3391   v9j   v9j

pI2S ps1S 86 393

      pI2S   ps2P
234   asje  asEje
234   aswa  asEje
3391    v2  vulje
3391   v9j  vulje

Empty DataFrame
Columns: [pI2S, ps2P]
Index: []

pI2S ps2P 244 0

      pI2S  ps2S
234   asje  asEj
234   asje  aswa
234   aswa  asEj
234   aswa  aswa
3391    v2   v9j
3391   v9j   v9j

      pI2S  ps2S
234   aswa  aswa
3391   v9j   v9j

pI2S ps2S 80 309

      pI2S  ps3P
234   asje  aswa
234   aswa  aswa
3391    v2   v9j
3391   v9j   v9j

      pI2S  ps3P
234   aswa  aswa
3391   v9j   v9j

pI2S ps3P 78 264

      pI2S  ps3S
234   asje  asEj
234   asje  aswa
234   aswa  asEj
234   aswa  aswa
3391    v2   v9j
3391   v9j   v9j

      pI2S  ps3S
234   aswa  aswa
3391   v9j   v9j

pI2S ps3S 127 641
pP pc1P 38 0

         pP     pc1S
1412  EsEjâ  EsEj6rE
1412  EsEjâ    EsErE
2232   pEjâ   pEj6rE
2232   pEjâ     pErE

Empty DataFrame
Columns: [pP, pc1S]
Index: []

pP pc1S 382 0

         pP      pc2P
1412  EsEjâ  EsEj6rje
1412  EsEjâ    EsErje
2232   pEjâ   pEj6rje
2232   pEjâ     pErje

Empty DataFrame
Columns: [pP, pc2P]
Index: []

pP pc2P 149 0

         pP     pc2S
1412  EsEjâ  EsEj6rE
1412  EsEjâ    EsErE
2232   pEjâ   pEj6rE
2232   pEjâ     pErE

Empty DataFrame
Columns: [pP, pc2S]
Index: []

pP pc2S 200 0

         pP     pc3P
1412  EsEjâ  EsEj6rE
1412  EsEjâ    EsErE
2232   pEjâ   pEj6rE
2232   pEjâ     pErE

Empty DataFrame
Columns: [pP, pc3P]
Index: []

pP pc3P 165 0

         pP     pc3S
1412  EsEjâ  EsEj6rE
1412  EsEjâ    EsErE
2232   pEjâ   pEj6rE
2232   pEjâ     pErE

Empty DataFrame
Columns: [pP, pc3S]
Index: []

pP pc3S 520 0
pP pi1P 501 0

         pP  pi1S
234   asEjâ  asje
234   asEjâ  aswa
1721   aisâ     E
1721   aisâ    ai
2358   puvâ    p2
2358   puvâ   pHi

Empty DataFrame
Columns: [pP, pi1S]
Index: []

pP pi1S 934 0
pP pi2P 812 0

         pP  pi2S
234   asEjâ  asje
234   asEjâ  aswa
1721   aisâ     E
1721   aisâ    ai

Empty DataFrame
Columns: [pP, pi2S]
Index: []

pP pi2S 860 0

         pP   pi3P
234   asEjâ   asEj
234   asEjâ   aswa
311  balEjâ   balE
311  balEjâ  balEj

Empty DataFrame
Columns: [pP, pi3P]
Index: []

pP pi3P 1007 0

          pP   pi3S
234    asEjâ   asje
234    asEjâ   aswa
311   balEjâ   balE
311   balEjâ  balEj
1721    aisâ      E
1721    aisâ     ai

Empty DataFrame
Columns: [pP, pi3S]
Index: []

pP pi3S 1065 0
pP ppFP 613 0
pP ppFS 839 0
pP ppMP 769 0
pP ppMS 1033 0
pP ps1P 63 0

        pP  ps1S
234  asEjâ  asEj
234  asEjâ  aswa

Empty DataFrame
Columns: [pP, ps1S]
Index: []

pP ps1S 466 0
pP ps2P 247 0

        pP  ps2S
234  asEjâ  asEj
234  asEjâ  aswa

Empty DataFrame
Columns: [pP, ps2S]
Index: []

pP ps2S 383 0
pP ps3P 349 0

        pP  ps3S
234  asEjâ  asEj
234  asEjâ  aswa

Empty DataFrame
Columns: [pP, ps3S]
Index: []

pP ps3S 760 0
pc1P pc1S 38 0
pc1P pc2P 37 0
pc1P pc2S 38 0
pc1P pc3P 37 0
pc1P pc3S 38 0
pc1P pi1P 38 0

       pc1P pi1S
2358  purjô   p2
2358  purjô  pHi

Empty DataFrame
Columns: [pc1P, pi1S]
Index: []

pc1P pi1S 37 0
pc1P pi2P 38 0
pc1P pi2S 37 0
pc1P pi3P 38 0
pc1P pi3S 38 0
pc1P ppFP 33 0
pc1P ppFS 35 0
pc1P ppMP 33 0
pc1P ppMS 38 0
pc1P ps1P 30 0
pc1P ps1S 37 0
pc1P ps2P 36 0
pc1P ps2S 38 0
pc1P ps3P 33 0
pc1P ps3S 37 0

         pc1S      pc2P
1412  EsEj6rE  EsEj6rje
1412  EsEj6rE    EsErje
1412    EsErE  EsEj6rje
1412    EsErE    EsErje
2232   pEj6rE   pEj6rje
2232   pEj6rE     pErje
2232     pErE   pEj6rje
2232     pErE     pErje

Empty DataFrame
Columns: [pc1S, pc2P]
Index: []

pc1S pc2P 151 0

         pc1S     pc2S
1412  EsEj6rE  EsEj6rE
1412  EsEj6rE    EsErE
1412    EsErE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232   pEj6rE     pErE
2232     pErE   pEj6rE
2232     pErE     pErE

         pc1S     pc2S
1412  EsEj6rE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232     pErE     pErE

pc1S pc2S 0 206

         pc1S     pc3P
1412  EsEj6rE  EsEj6rE
1412  EsEj6rE    EsErE
1412    EsErE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232   pEj6rE     pErE
2232     pErE   pEj6rE
2232     pErE     pErE

         pc1S     pc3P
1412  EsEj6rE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232     pErE     pErE

pc1S pc3P 0 163

         pc1S     pc3S
1412  EsEj6rE  EsEj6rE
1412  EsEj6rE    EsErE
1412    EsErE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232   pEj6rE     pErE
2232     pErE   pEj6rE
2232     pErE     pErE

         pc1S     pc3S
1412  EsEj6rE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232     pErE     pErE

pc1S pc3S 0 371

         pc1S   pi1P
1412  EsEj6rE  EsEjô
1412    EsErE  EsEjô
2232   pEj6rE   pEjô
2232     pErE   pEjô

Empty DataFrame
Columns: [pc1S, pi1P]
Index: []

pc1S pi1P 320 0

         pc1S  pi1S
234    asjErE  asje
234    asjErE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
1721     airE     E
1721     airE    ai
2232   pEj6rE   pEj
2232     pErE   pEj
2358     purE    p2
2358     purE   pHi

Empty DataFrame
Columns: [pc1S, pi1S]
Index: []

pc1S pi1S 404 0

         pc1S   pi2P
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc1S, pi2P]
Index: []

pc1S pi2P 398 0

         pc1S  pi2S
234    asjErE  asje
234    asjErE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
1721     airE     E
1721     airE    ai
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc1S, pi2S]
Index: []

pc1S pi2S 400 0

         pc1S  pi3P
234    asjErE  asEj
234    asjErE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc1S, pi3P]
Index: []

pc1S pi3P 404 0

         pc1S  pi3S
234    asjErE  asje
234    asjErE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
1721     airE     E
1721     airE    ai
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc1S, pi3S]
Index: []

pc1S pi3S 406 0

         pc1S   ppFP
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc1S, ppFP]
Index: []

pc1S ppFP 295 0

         pc1S   ppFS
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc1S, ppFS]
Index: []

pc1S ppFS 367 0

         pc1S   ppMP
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc1S, ppMP]
Index: []

pc1S ppMP 339 0

         pc1S   ppMS
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc1S, ppMS]
Index: []

pc1S ppMS 406 0

         pc1S   ps1P
1412  EsEj6rE  EsEjô
1412    EsErE  EsEjô

Empty DataFrame
Columns: [pc1S, ps1P]
Index: []

pc1S ps1P 63 0

         pc1S  ps1S
234    asjErE  asEj
234    asjErE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc1S, ps1S]
Index: []

pc1S ps1S 354 0

         pc1S   ps2P
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc1S, ps2P]
Index: []

pc1S ps2P 232 0

         pc1S  ps2S
234    asjErE  asEj
234    asjErE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc1S, ps2S]
Index: []

pc1S ps2S 318 0

         pc1S  ps3P
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc1S, ps3P]
Index: []

pc1S ps3P 278 0

         pc1S  ps3S
234    asjErE  asEj
234    asjErE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc1S, ps3S]
Index: []

pc1S ps3S 387 0

          pc2P     pc2S
1412  EsEj6rje  EsEj6rE
1412  EsEj6rje    EsErE
1412    EsErje  EsEj6rE
1412    EsErje    EsErE
2232   pEj6rje   pEj6rE
2232   pEj6rje     pErE
2232     pErje   pEj6rE
2232     pErje     pErE

Empty DataFrame
Columns: [pc2P, pc2S]
Index: []

pc2P pc2S 143 0

          pc2P     pc3P
1412  EsEj6rje  EsEj6rE
1412  EsEj6rje    EsErE
1412    EsErje  EsEj6rE
1412    EsErje    EsErE
2232   pEj6rje   pEj6rE
2232   pEj6rje     pErE
2232     pErje   pEj6rE
2232     pErje     pErE

Empty DataFrame
Columns: [pc2P, pc3P]
Index: []

pc2P pc3P 118 0

          pc2P     pc3S
1412  EsEj6rje  EsEj6rE
1412  EsEj6rje    EsErE
1412    EsErje  EsEj6rE
1412    EsErje    EsErE
2232   pEj6rje   pEj6rE
2232   pEj6rje     pErE
2232     pErje   pEj6rE
2232     pErje     pErE

Empty DataFrame
Columns: [pc2P, pc3S]
Index: []

pc2P pc3S 149 0

          pc2P   pi1P
1412  EsEj6rje  EsEjô
1412    EsErje  EsEjô
2232   pEj6rje   pEjô
2232     pErje   pEjô

Empty DataFrame
Columns: [pc2P, pi1P]
Index: []

pc2P pi1P 145 0

          pc2P  pi1S
1412  EsEj6rje  EsEj
1412    EsErje  EsEj
2232   pEj6rje   pEj
2232     pErje   pEj
2358     purje    p2
2358     purje   pHi

Empty DataFrame
Columns: [pc2P, pi1S]
Index: []

pc2P pi1S 152 0

          pc2P   pi2P
1412  EsEj6rje  EsEje
1412    EsErje  EsEje
2232   pEj6rje   pEje
2232     pErje   pEje

Empty DataFrame
Columns: [pc2P, pi2P]
Index: []

pc2P pi2P 154 0

          pc2P  pi2S
1412  EsEj6rje  EsEj
1412    EsErje  EsEj
2232   pEj6rje   pEj
2232     pErje   pEj

Empty DataFrame
Columns: [pc2P, pi2S]
Index: []

pc2P pi2S 151 0

          pc2P  pi3P
1412  EsEj6rje  EsEj
1412    EsErje  EsEj
2232   pEj6rje   pEj
2232     pErje   pEj

Empty DataFrame
Columns: [pc2P, pi3P]
Index: []

pc2P pi3P 154 0

          pc2P  pi3S
1412  EsEj6rje  EsEj
1412    EsErje  EsEj
2232   pEj6rje   pEj
2232     pErje   pEj

Empty DataFrame
Columns: [pc2P, pi3S]
Index: []

pc2P pi3S 154 0

          pc2P   ppFP
1412  EsEj6rje  EsEje
1412    EsErje  EsEje
2232   pEj6rje   pEje
2232     pErje   pEje

Empty DataFrame
Columns: [pc2P, ppFP]
Index: []

pc2P ppFP 129 0

          pc2P   ppFS
1412  EsEj6rje  EsEje
1412    EsErje  EsEje
2232   pEj6rje   pEje
2232     pErje   pEje

Empty DataFrame
Columns: [pc2P, ppFS]
Index: []

pc2P ppFS 142 0

          pc2P   ppMP
1412  EsEj6rje  EsEje
1412    EsErje  EsEje
2232   pEj6rje   pEje
2232     pErje   pEje

Empty DataFrame
Columns: [pc2P, ppMP]
Index: []

pc2P ppMP 135 0

          pc2P   ppMS
1412  EsEj6rje  EsEje
1412    EsErje  EsEje
2232   pEj6rje   pEje
2232     pErje   pEje

Empty DataFrame
Columns: [pc2P, ppMS]
Index: []

pc2P ppMS 153 0

          pc2P   ps1P
1412  EsEj6rje  EsEjô
1412    EsErje  EsEjô

Empty DataFrame
Columns: [pc2P, ps1P]
Index: []

pc2P ps1P 53 0

          pc2P  ps1S
1412  EsEj6rje  EsEj
1412    EsErje  EsEj
2232   pEj6rje   pEj
2232     pErje   pEj

Empty DataFrame
Columns: [pc2P, ps1S]
Index: []

pc2P ps1S 144 0

          pc2P   ps2P
1412  EsEj6rje  EsEje
1412    EsErje  EsEje
2232   pEj6rje   pEje
2232     pErje   pEje

Empty DataFrame
Columns: [pc2P, ps2P]
Index: []

pc2P ps2P 132 0

          pc2P  ps2S
1412  EsEj6rje  EsEj
1412    EsErje  EsEj
2232   pEj6rje   pEj
2232     pErje   pEj

Empty DataFrame
Columns: [pc2P, ps2S]
Index: []

pc2P ps2S 142 0

          pc2P  ps3P
1412  EsEj6rje  EsEj
1412    EsErje  EsEj
2232   pEj6rje   pEj
2232     pErje   pEj

Empty DataFrame
Columns: [pc2P, ps3P]
Index: []

pc2P ps3P 130 0

          pc2P  ps3S
1412  EsEj6rje  EsEj
1412    EsErje  EsEj
2232   pEj6rje   pEj
2232     pErje   pEj

Empty DataFrame
Columns: [pc2P, ps3S]
Index: []

pc2P ps3S 148 0

         pc2S     pc3P
1412  EsEj6rE  EsEj6rE
1412  EsEj6rE    EsErE
1412    EsErE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232   pEj6rE     pErE
2232     pErE   pEj6rE
2232     pErE     pErE

         pc2S     pc3P
1412  EsEj6rE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232     pErE     pErE

pc2S pc3P 0 145

         pc2S     pc3S
1412  EsEj6rE  EsEj6rE
1412  EsEj6rE    EsErE
1412    EsErE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232   pEj6rE     pErE
2232     pErE   pEj6rE
2232     pErE     pErE

         pc2S     pc3S
1412  EsEj6rE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232     pErE     pErE

pc2S pc3S 0 206

         pc2S   pi1P
1412  EsEj6rE  EsEjô
1412    EsErE  EsEjô
2232   pEj6rE   pEjô
2232     pErE   pEjô

Empty DataFrame
Columns: [pc2S, pi1P]
Index: []

pc2S pi1P 187 0

         pc2S  pi1S
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj
2358     purE    p2
2358     purE   pHi

Empty DataFrame
Columns: [pc2S, pi1S]
Index: []

pc2S pi1S 205 0

         pc2S   pi2P
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc2S, pi2P]
Index: []

pc2S pi2P 206 0

         pc2S  pi2S
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc2S, pi2S]
Index: []

pc2S pi2S 204 0

         pc2S  pi3P
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc2S, pi3P]
Index: []

pc2S pi3P 206 0

         pc2S  pi3S
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc2S, pi3S]
Index: []

pc2S pi3S 206 0

         pc2S   ppFP
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc2S, ppFP]
Index: []

pc2S ppFP 163 0

         pc2S   ppFS
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc2S, ppFS]
Index: []

pc2S ppFS 184 0

         pc2S   ppMP
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc2S, ppMP]
Index: []

pc2S ppMP 174 0

         pc2S   ppMS
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc2S, ppMS]
Index: []

pc2S ppMS 205 0

         pc2S   ps1P
1412  EsEj6rE  EsEjô
1412    EsErE  EsEjô

Empty DataFrame
Columns: [pc2S, ps1P]
Index: []

pc2S ps1P 60 0

         pc2S  ps1S
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc2S, ps1S]
Index: []

pc2S ps1S 196 0

         pc2S   ps2P
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc2S, ps2P]
Index: []

pc2S ps2P 177 0

         pc2S  ps2S
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc2S, ps2S]
Index: []

pc2S ps2S 197 0

         pc2S  ps3P
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc2S, ps3P]
Index: []

pc2S ps3P 183 0

         pc2S  ps3S
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc2S, ps3S]
Index: []

pc2S ps3S 202 0

         pc3P     pc3S
1412  EsEj6rE  EsEj6rE
1412  EsEj6rE    EsErE
1412    EsErE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232   pEj6rE     pErE
2232     pErE   pEj6rE
2232     pErE     pErE

         pc3P     pc3S
1412  EsEj6rE  EsEj6rE
1412    EsErE    EsErE
2232   pEj6rE   pEj6rE
2232     pErE     pErE

pc3P pc3S 0 171

         pc3P   pi1P
1412  EsEj6rE  EsEjô
1412    EsErE  EsEjô
2232   pEj6rE   pEjô
2232     pErE   pEjô

Empty DataFrame
Columns: [pc3P, pi1P]
Index: []

pc3P pi1P 156 0

         pc3P  pi1S
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj
2358     purE    p2
2358     purE   pHi

Empty DataFrame
Columns: [pc3P, pi1S]
Index: []

pc3P pi1S 168 0

         pc3P   pi2P
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc3P, pi2P]
Index: []

pc3P pi2P 168 0

         pc3P  pi2S
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc3P, pi2S]
Index: []

pc3P pi2S 166 0

         pc3P  pi3P
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc3P, pi3P]
Index: []

pc3P pi3P 169 0

         pc3P  pi3S
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc3P, pi3S]
Index: []

pc3P pi3S 169 0

         pc3P   ppFP
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc3P, ppFP]
Index: []

pc3P ppFP 135 0

         pc3P   ppFS
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc3P, ppFS]
Index: []

pc3P ppFS 149 0

         pc3P   ppMP
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc3P, ppMP]
Index: []

pc3P ppMP 142 0

         pc3P   ppMS
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc3P, ppMS]
Index: []

pc3P ppMS 168 0

         pc3P   ps1P
1412  EsEj6rE  EsEjô
1412    EsErE  EsEjô

Empty DataFrame
Columns: [pc3P, ps1P]
Index: []

pc3P ps1P 56 0

         pc3P  ps1S
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc3P, ps1S]
Index: []

pc3P ps1S 153 0

         pc3P   ps2P
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc3P, ps2P]
Index: []

pc3P ps2P 138 0

         pc3P  ps2S
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc3P, ps2S]
Index: []

pc3P ps2S 154 0

         pc3P  ps3P
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc3P, ps3P]
Index: []

pc3P ps3P 152 0

         pc3P  ps3S
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc3P, ps3S]
Index: []

pc3P ps3S 166 0

         pc3S   pi1P
1412  EsEj6rE  EsEjô
1412    EsErE  EsEjô
2232   pEj6rE   pEjô
2232     pErE   pEjô

Empty DataFrame
Columns: [pc3S, pi1P]
Index: []

pc3S pi1P 380 0

         pc3S  pi1S
234    asjErE  asje
234    asjErE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
1721     airE     E
1721     airE    ai
2232   pEj6rE   pEj
2232     pErE   pEj
2358     purE    p2
2358     purE   pHi

Empty DataFrame
Columns: [pc3S, pi1S]
Index: []

pc3S pi1S 558 0

         pc3S   pi2P
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc3S, pi2P]
Index: []

pc3S pi2P 526 0

         pc3S  pi2S
234    asjErE  asje
234    asjErE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
1721     airE     E
1721     airE    ai
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc3S, pi2S]
Index: []

pc3S pi2S 543 0

         pc3S  pi3P
234    asjErE  asEj
234    asjErE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc3S, pi3P]
Index: []

pc3S pi3P 579 0

         pc3S  pi3S
234    asjErE  asje
234    asjErE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
1721     airE     E
1721     airE    ai
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc3S, pi3S]
Index: []

pc3S pi3S 590 0

         pc3S   ppFP
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc3S, ppFP]
Index: []

pc3S ppFP 412 0

         pc3S   ppFS
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc3S, ppFS]
Index: []

pc3S ppFS 519 0

         pc3S   ppMP
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc3S, ppMP]
Index: []

pc3S ppMP 488 0

         pc3S   ppMS
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc3S, ppMS]
Index: []

pc3S ppMS 588 0

         pc3S   ps1P
1412  EsEj6rE  EsEjô
1412    EsErE  EsEjô

Empty DataFrame
Columns: [pc3S, ps1P]
Index: []

pc3S ps1P 63 0

         pc3S  ps1S
234    asjErE  asEj
234    asjErE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc3S, ps1S]
Index: []

pc3S ps1S 391 0

         pc3S   ps2P
1412  EsEj6rE  EsEje
1412    EsErE  EsEje
2232   pEj6rE   pEje
2232     pErE   pEje

Empty DataFrame
Columns: [pc3S, ps2P]
Index: []

pc3S ps2P 236 0

         pc3S  ps2S
234    asjErE  asEj
234    asjErE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc3S, ps2S]
Index: []

pc3S ps2S 349 0

         pc3S  ps3P
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc3S, ps3P]
Index: []

pc3S ps3P 337 0

         pc3S  ps3S
234    asjErE  asEj
234    asjErE  aswa
1412  EsEj6rE  EsEj
1412    EsErE  EsEj
2232   pEj6rE   pEj
2232     pErE   pEj

Empty DataFrame
Columns: [pc3S, ps3S]
Index: []

pc3S ps3S 551 0

       pi1P  pi1S
234   asEjô  asje
234   asEjô  aswa
1721   aisô     E
1721   aisô    ai
2358   puvô    p2
2358   puvô   pHi

Empty DataFrame
Columns: [pi1P, pi1S]
Index: []

pi1P pi1S 526 0
pi1P pi2P 508 0

       pi1P  pi2S
234   asEjô  asje
234   asEjô  aswa
1721   aisô     E
1721   aisô    ai

Empty DataFrame
Columns: [pi1P, pi2S]
Index: []

pi1P pi2S 495 0

      pi1P  pi3P
234  asEjô  asEj
234  asEjô  aswa

Empty DataFrame
Columns: [pi1P, pi3P]
Index: []

pi1P pi3P 524 0

       pi1P  pi3S
234   asEjô  asje
234   asEjô  aswa
1721   aisô     E
1721   aisô    ai

Empty DataFrame
Columns: [pi1P, pi3S]
Index: []

pi1P pi3S 529 0
pi1P ppFP 380 0
pi1P ppFS 471 0
pi1P ppMP 438 0
pi1P ppMS 527 0
pi1P ps1P 60 3

      pi1P  ps1S
234  asEjô  asEj
234  asEjô  aswa

Empty DataFrame
Columns: [pi1P, ps1S]
Index: []

pi1P ps1S 356 0
pi1P ps2P 237 0

      pi1P  ps2S
234  asEjô  asEj
234  asEjô  aswa

Empty DataFrame
Columns: [pi1P, ps2S]
Index: []

pi1P ps2S 319 0
pi1P ps3P 300 0

      pi1P  ps3S
234  asEjô  asEj
234  asEjô  aswa

Empty DataFrame
Columns: [pi1P, ps3S]
Index: []

pi1P ps3S 476 0

      pi1S   pi2P
234   asje  asEje
234   aswa  asEje
1721     E   aise
1721    ai   aise
2358    p2   puve
2358   pHi   puve

Empty DataFrame
Columns: [pi1S, pi2P]
Index: []

pi1S pi2P 940 0

      pi1S  pi2S
234   asje  asje
234   asje  aswa
234   aswa  asje
234   aswa  aswa
1721     E     E
1721     E    ai
1721    ai     E
1721    ai    ai
2358    p2    p2
2358   pHi    p2

      pi1S  pi2S
234   asje  asje
234   aswa  aswa
1721     E     E
1721    ai    ai
2358    p2    p2

pi1S pi2S 3 1068

      pi1S   pi3P
234   asje   asEj
234   asje   aswa
234   aswa   asEj
234   aswa   aswa
311   balE   balE
311   balE  balEj
1721     E    ais
1721    ai    ais
2358    p2    p9v
2358   pHi    p9v

     pi1S  pi3P
234  aswa  aswa
311  balE  balE

pi1S pi3P 195 968

      pi1S   pi3S
234   asje   asje
234   asje   aswa
234   aswa   asje
234   aswa   aswa
311   balE   balE
311   balE  balEj
1721     E      E
1721     E     ai
1721    ai      E
1721    ai     ai
2358    p2     p2
2358   pHi     p2

      pi1S  pi3S
234   asje  asje
234   aswa  aswa
311   balE  balE
1721     E     E
1721    ai    ai
2358    p2    p2

pi1S pi3S 3 1397

     pi1S  ppFP
234  asje  asiz
234  aswa  asiz

Empty DataFrame
Columns: [pi1S, ppFP]
Index: []

pi1S ppFP 654 32

      pi1S  ppFS
234   asje  asiz
234   aswa  asiz
1721     E    ai
1721    ai    ai

     pi1S ppFS
1721   ai   ai

pi1S ppFS 1015 53

      pi1S ppMP
234   asje  asi
234   aswa  asi
1721     E   ai
1721    ai   ai

     pi1S ppMP
1721   ai   ai

pi1S ppMP 862 78

      pi1S ppMS
234   asje  asi
234   aswa  asi
1721     E   ai
1721    ai   ai
2358    p2   py
2358   pHi   py

     pi1S ppMS
1721   ai   ai

pi1S ppMS 1265 113

     pi1S    ps1P
2358   p2  pHisjô
2358  pHi  pHisjô

Empty DataFrame
Columns: [pi1S, ps1P]
Index: []

pi1S ps1P 62 0

      pi1S  ps1S
234   asje  asEj
234   asje  aswa
234   aswa  asEj
234   aswa  aswa
2358    p2  pHis
2358   pHi  pHis

     pi1S  ps1S
234  aswa  aswa

pi1S ps1S 93 396

      pi1S    ps2P
234   asje   asEje
234   aswa   asEje
2358    p2  pHisje
2358   pHi  pHisje

Empty DataFrame
Columns: [pi1S, ps2P]
Index: []

pi1S ps2P 250 0

      pi1S  ps2S
234   asje  asEj
234   asje  aswa
234   aswa  asEj
234   aswa  aswa
1721     E   ais
1721    ai   ais
2358    p2  pHis
2358   pHi  pHis

     pi1S  ps2S
234  aswa  aswa

pi1S ps2S 87 313

      pi1S  ps3P
234   asje  aswa
234   aswa  aswa
1721     E   ais
1721    ai   ais
2358    p2  pHis
2358   pHi  pHis

     pi1S  ps3P
234  aswa  aswa

pi1S ps3P 95 265

      pi1S  ps3S
234   asje  asEj
234   asje  aswa
234   aswa  asEj
234   aswa  aswa
1721     E   ais
1721    ai   ais
2358    p2  pHis
2358   pHi  pHis

     pi1S  ps3S
234  aswa  aswa

pi1S ps3S 154 686

       pi2P  pi2S
234   asEje  asje
234   asEje  aswa
1721   aise     E
1721   aise    ai

Empty DataFrame
Columns: [pi2P, pi2S]
Index: []

pi2P pi2S 914 0

      pi2P  pi3P
234  asEje  asEj
234  asEje  aswa

Empty DataFrame
Columns: [pi2P, pi3P]
Index: []

pi2P pi3P 943 0

       pi2P  pi3S
234   asEje  asje
234   asEje  aswa
1721   aise     E
1721   aise    ai

Empty DataFrame
Columns: [pi2P, pi3S]
Index: []

pi2P pi3S 977 0
pi2P ppFP 121 460
pi2P ppFS 157 650
pi2P ppMP 147 594
pi2P ppMS 186 791
pi2P ps1P 63 0

      pi2P  ps1S
234  asEje  asEj
234  asEje  aswa

Empty DataFrame
Columns: [pi2P, ps1S]
Index: []

pi2P ps1S 475 0
pi2P ps2P 233 18

      pi2P  ps2S
234  asEje  asEj
234  asEje  aswa

Empty DataFrame
Columns: [pi2P, ps2S]
Index: []

pi2P ps2S 400 0
pi2P ps3P 355 0

      pi2P  ps3S
234  asEje  asEj
234  asEje  aswa

Empty DataFrame
Columns: [pi2P, ps3S]
Index: []

pi2P ps3S 765 0

      pi2S   pi3P
234   asje   asEj
234   asje   aswa
234   aswa   asEj
234   aswa   aswa
311   balE   balE
311   balE  balEj
1721     E    ais
1721    ai    ais

     pi2S  pi3P
234  aswa  aswa
311  balE  balE

pi2S pi3P 171 857

      pi2S   pi3S
234   asje   asje
234   asje   aswa
234   aswa   asje
234   aswa   aswa
311   balE   balE
311   balE  balEj
1721     E      E
1721     E     ai
1721    ai      E
1721    ai     ai

      pi2S  pi3S
234   asje  asje
234   aswa  aswa
311   balE  balE
1721     E     E
1721    ai    ai

pi2S pi3S 0 1131

     pi2S  ppFP
234  asje  asiz
234  aswa  asiz

Empty DataFrame
Columns: [pi2S, ppFP]
Index: []

pi2S ppFP 583 25

      pi2S  ppFS
234   asje  asiz
234   aswa  asiz
1721     E    ai
1721    ai    ai

     pi2S ppFS
1721   ai   ai

pi2S ppFS 846 38

      pi2S ppMP
234   asje  asi
234   aswa  asi
1721     E   ai
1721    ai   ai

     pi2S ppMP
1721   ai   ai

pi2S ppMP 730 62

      pi2S ppMS
234   asje  asi
234   aswa  asi
1721     E   ai
1721    ai   ai

     pi2S ppMS
1721   ai   ai

pi2S ppMS 1021 83
pi2S ps1P 61 0

     pi2S  ps1S
234  asje  asEj
234  asje  aswa
234  aswa  asEj
234  aswa  aswa

     pi2S  ps1S
234  aswa  aswa

pi2S ps1S 92 394

     pi2S   ps2P
234  asje  asEje
234  aswa  asEje

Empty DataFrame
Columns: [pi2S, ps2P]
Index: []

pi2S ps2P 249 0

      pi2S  ps2S
234   asje  asEj
234   asje  aswa
234   aswa  asEj
234   aswa  aswa
1721     E   ais
1721    ai   ais

     pi2S  ps2S
234  aswa  aswa

pi2S ps2S 86 311

      pi2S  ps3P
234   asje  aswa
234   aswa  aswa
1721     E   ais
1721    ai   ais

     pi2S  ps3P
234  aswa  aswa

pi2S ps3P 92 263

      pi2S  ps3S
234   asje  asEj
234   asje  aswa
234   aswa  asEj
234   aswa  aswa
1721     E   ais
1721    ai   ais

     pi2S  ps3S
234  aswa  aswa

pi2S ps3S 147 648

       pi3P   pi3S
234    asEj   asje
234    asEj   aswa
234    aswa   asje
234    aswa   aswa
311    balE   balE
311    balE  balEj
311   balEj   balE
311   balEj  balEj
1721    ais      E
1721    ais     ai

      pi3P   pi3S
234   aswa   aswa
311   balE   balE
311  balEj  balEj

pi3P pi3S 243 1261

      pi3P    ppFP
234   asEj    asiz
234   aswa    asiz
311   balE  balEje
311  balEj  balEje

Empty DataFrame
Columns: [pi3P, ppFP]
Index: []

pi3P ppFP 736 2

      pi3P    ppFS
234   asEj    asiz
234   aswa    asiz
311   balE  balEje
311  balEj  balEje

Empty DataFrame
Columns: [pi3P, ppFS]
Index: []

pi3P ppFS 1123 4

      pi3P    ppMP
234   asEj     asi
234   aswa     asi
311   balE  balEje
311  balEj  balEje

Empty DataFrame
Columns: [pi3P, ppMP]
Index: []

pi3P ppMP 1003 6

      pi3P    ppMS
234   asEj     asi
234   aswa     asi
311   balE  balEje
311  balEj  balEje

Empty DataFrame
Columns: [pi3P, ppMS]
Index: []

pi3P ppMS 1431 9
pi3P ps1P 63 0

     pi3P  ps1S
234  asEj  asEj
234  asEj  aswa
234  aswa  asEj
234  aswa  aswa

     pi3P  ps1S
234  asEj  asEj
234  aswa  aswa

pi3P ps1S 7 481

     pi3P   ps2P
234  asEj  asEje
234  aswa  asEje

Empty DataFrame
Columns: [pi3P, ps2P]
Index: []

pi3P ps2P 251 0

     pi3P  ps2S
234  asEj  asEj
234  asEj  aswa
234  aswa  asEj
234  aswa  aswa

     pi3P  ps2S
234  asEj  asEj
234  aswa  aswa

pi3P ps2S 8 394

     pi3P  ps3P
234  asEj  aswa
234  aswa  aswa

     pi3P  ps3P
234  aswa  aswa

pi3P ps3P 6 364

     pi3P  ps3S
234  asEj  asEj
234  asEj  aswa
234  aswa  asEj
234  aswa  aswa

     pi3P  ps3S
234  asEj  asEj
234  aswa  aswa

pi3P ps3S 9 886

      pi3S    ppFP
234   asje    asiz
234   aswa    asiz
311   balE  balEje
311  balEj  balEje

Empty DataFrame
Columns: [pi3S, ppFP]
Index: []

pi3S ppFP 781 38

       pi3S    ppFS
234    asje    asiz
234    aswa    asiz
311    balE  balEje
311   balEj  balEje
1721      E      ai
1721     ai      ai

     pi3S ppFS
1721   ai   ai

pi3S ppFS 1397 88

       pi3S    ppMP
234    asje     asi
234    aswa     asi
311    balE  balEje
311   balEj  balEje
1721      E      ai
1721     ai      ai

     pi3S ppMP
1721   ai   ai

pi3S ppMP 1148 94

       pi3S    ppMS
234    asje     asi
234    aswa     asi
311    balE  balEje
311   balEj  balEje
1721      E      ai
1721     ai      ai

     pi3S ppMS
1721   ai   ai

pi3S ppMS 1932 182
pi3S ps1P 63 0

     pi3S  ps1S
234  asje  asEj
234  asje  aswa
234  aswa  asEj
234  aswa  aswa

     pi3S  ps1S
234  aswa  aswa

pi3S ps1S 95 397

     pi3S   ps2P
234  asje  asEje
234  aswa  asEje

Empty DataFrame
Columns: [pi3S, ps2P]
Index: []

pi3S ps2P 251 0

      pi3S  ps2S
234   asje  asEj
234   asje  aswa
234   aswa  asEj
234   aswa  aswa
1721     E   ais
1721    ai   ais

     pi3S  ps2S
234  aswa  aswa

pi3S ps2S 90 312

      pi3S  ps3P
234   asje  aswa
234   aswa  aswa
1721     E   ais
1721    ai   ais

     pi3S  ps3P
234  aswa  aswa

pi3S ps3P 99 271

      pi3S  ps3S
234   asje  asEj
234   asje  aswa
234   aswa  asEj
234   aswa  aswa
1721     E   ais
1721    ai   ais

     pi3S  ps3S
234  aswa  aswa

pi3S ps3S 179 747
ppFP ppFS 0 840
ppFP ppMP 51 774
ppFP ppMS 56 803
ppFP ps1P 57 0

     ppFP  ps1S
234  asiz  asEj
234  asiz  aswa

Empty DataFrame
Columns: [ppFP, ps1S]
Index: []

ppFP ps1S 365 1
ppFP ps2P 195 11

     ppFP  ps2S
234  asiz  asEj
234  asiz  aswa

Empty DataFrame
Columns: [ppFP, ps2S]
Index: []

ppFP ps2S 311 1
ppFP ps3P 286 1

     ppFP  ps3S
234  asiz  asEj
234  asiz  aswa

Empty DataFrame
Columns: [ppFP, ps3S]
Index: []

ppFP ps3S 583 1
ppFS ppMP 59 1268
ppFS ppMS 73 1683
ppFS ps1P 58 0

     ppFS  ps1S
234  asiz  asEj
234  asiz  aswa

Empty DataFrame
Columns: [ppFS, ps1S]
Index: []

ppFS ps1S 447 1
ppFS ps2P 218 11

     ppFS  ps2S
234  asiz  asEj
234  asiz  aswa

Empty DataFrame
Columns: [ppFS, ps2S]
Index: []

ppFS ps2S 363 1
ppFS ps3P 334 2

     ppFS  ps3S
234  asiz  asEj
234  asiz  aswa

Empty DataFrame
Columns: [ppFS, ps3S]
Index: []

ppFS ps3S 787 3
ppMP ppMS 0 1418
ppMP ps1P 56 0

    ppMP  ps1S
234  asi  asEj
234  asi  aswa

Empty DataFrame
Columns: [ppMP, ps1S]
Index: []

ppMP ps1S 422 1
ppMP ps2P 209 11

    ppMP  ps2S
234  asi  asEj
234  asi  aswa

Empty DataFrame
Columns: [ppMP, ps2S]
Index: []

ppMP ps2S 344 1
ppMP ps3P 324 1

    ppMP  ps3S
234  asi  asEj
234  asi  aswa

Empty DataFrame
Columns: [ppMP, ps3S]
Index: []

ppMP ps3S 730 2
ppMS ps1P 63 0

    ppMS  ps1S
234  asi  asEj
234  asi  aswa

Empty DataFrame
Columns: [ppMS, ps1S]
Index: []

ppMS ps1S 491 1
ppMS ps2P 239 12

    ppMS  ps2S
234  asi  asEj
234  asi  aswa

Empty DataFrame
Columns: [ppMS, ps2S]
Index: []

ppMS ps2S 402 1
ppMS ps3P 365 3

    ppMS  ps3S
234  asi  asEj
234  asi  aswa

Empty DataFrame
Columns: [ppMS, ps3S]
Index: []

ppMS ps3S 914 5
ps1P ps1S 61 0
ps1P ps2P 61 0
ps1P ps2S 61 0
ps1P ps3P 61 0
ps1P ps3S 62 0

     ps1S   ps2P
234  asEj  asEje
234  aswa  asEje

Empty DataFrame
Columns: [ps1S, ps2P]
Index: []

ps1S ps2P 242 0

     ps1S  ps2S
234  asEj  asEj
234  asEj  aswa
234  aswa  asEj
234  aswa  aswa

     ps1S  ps2S
234  asEj  asEj
234  aswa  aswa

ps1S ps2S 0 378

     ps1S  ps3P
234  asEj  aswa
234  aswa  aswa

     ps1S  ps3P
234  aswa  aswa

ps1S ps3P 0 313

     ps1S  ps3S
234  asEj  asEj
234  asEj  aswa
234  aswa  asEj
234  aswa  aswa

     ps1S  ps3S
234  asEj  asEj
234  aswa  aswa

ps1S ps3S 0 486

      ps2P  ps2S
234  asEje  asEj
234  asEje  aswa

Empty DataFrame
Columns: [ps2P, ps2S]
Index: []

ps2P ps2S 237 0
ps2P ps3P 219 0

      ps2P  ps3S
234  asEje  asEj
234  asEje  aswa

Empty DataFrame
Columns: [ps2P, ps3S]
Index: []

ps2P ps3S 248 0

     ps2S  ps3P
234  asEj  aswa
234  aswa  aswa

     ps2S  ps3P
234  aswa  aswa

ps2S ps3P 0 295

     ps2S  ps3S
234  asEj  asEj
234  asEj  aswa
234  aswa  asEj
234  aswa  aswa

     ps2S  ps3S
234  asEj  asEj
234  aswa  aswa

ps2S ps3S 0 400

     ps3P  ps3S
234  aswa  asEj
234  aswa  aswa

     ps3P  ps3S
234  aswa  aswa

ps3P ps3S 0 371

c1="ai1S"
c2="pi1S"

c1SimpleVal=(paradigmes[c1].notnull())&(~paradigmes[c1].str.contains(",",na=False))
c2SimpleVal=(paradigmes[c2].notnull())&(~paradigmes[c2].str.contains(",",na=False))

incompatiblesSimples=paradigmes[c1SimpleVal & c2SimpleVal & (paradigmes[c1]!=paradigmes[c2])][[c1,c2]]
compatiblesSimples=paradigmes[c1SimpleVal & c2SimpleVal & (paradigmes[c1]==paradigmes[c2])][[c1,c2]]

nbIncompatibles=len(incompatiblesSimples)
nbCompatibles=len(compatiblesSimples)
print(nbIncompatibles,nbCompatibles)

c1MultipleVal=((paradigmes[c1].notnull())&(paradigmes[c2].notnull())&(paradigmes[c1].str.contains(",",na=False)))
c2MultipleVal=((paradigmes[c1].notnull())&(paradigmes[c2].notnull())&(paradigmes[c2].str.contains(",",na=False)))
multiples=paradigmes[c1MultipleVal|c2MultipleVal][[c1,c2]].apply(lambda x: x.str.split(',')).explode(c1).explode(c2)

if len(multiples)>0:
    compatiblesMultiples=multiples[multiples[c1]==multiples[c2]][[c1,c2]]
    display(multiples,compatiblesMultiples)
    nbCompatiblesMultiples=len(compatiblesMultiples.index.unique())
    if nbCompatiblesMultiples==len(multiples.index.unique()):
        display(compatiblesMultiples)
        nbCompatibles+=len(compatiblesMultiples)
    else:
        nbIncompatibles+=len(multiples.index.unique())-len(compatiblesMultiples.index.unique())

nbIncompatibles,nbCompatibles

In [132]:
paradigmes[c1MultipleVal|c2MultipleVal][[c1,c2]]

     ps3P       ps3S
234  aswa  asEj,aswa

In [102]:
cliques=sorted(cliques, key=len, reverse=True)
print(cliques)
maxLenClique=len(cliques[0])
wCliques=(cliques[:])

[['pc1S', 'pc3P', 'fi1S', 'pc2S', 'pc3S'], ['ii3P', 'ii1S', 'ii3S', 'ii2S'], ['ps1S', 'ps2S', 'ps3S', 'ps3P'], ['fi3P', 'fi1P'], ['ppMP', 'ppMS'], ['pi3S', 'pi2S'], ['fi3S', 'fi2S'], ['ppFS', 'ppFP']]

In [103]:
syncretismes=[]

def cleanCliques(lCliques):
    sCases=set(sum(lCliques,[]))
    for c in lCliques:
        wCliques.remove(c)
    for c in sCases:
        for w in wCliques:
            if c in w:
                w.remove(c)
    return
                

def addCliques(length):
    conflits=[]
    lCliques=[x for x in cliques if len(x)==length]
    if len(lCliques)>1:
        for (c1,c2) in it.combinations(lCliques, 2):
            inter=set(c1).intersection(set(c2))
            if inter:
                conflits.append([c1,c2])
    if conflits:
        ajouts=[]
        for c in lCliques:
            noConflit=True
            for conflit in conflits:
                if c in conflit:
                    noConflit=False
            if noConflit:
                ajouts.append(c)
        syncretismes.extend(ajouts)
        cleanCliques(ajouts)
        for c1,c2 in conflits:
            sC1=set(c1)
            sC2=set(c2)
            pivot=list(sC1.intersection(sC2))[0]
            dC1=sC1.difference(sC2)
            wC1=sum(g[pivot][c]["weight"] for c in dC1)
            dC2=sC2.difference(sC1)
            wC2=sum(g[pivot][c]["weight"] for c in dC2)
            print (c1,wC1,c2,wC2)
    else:
        syncretismes.extend(lCliques)
        cleanCliques(lCliques)
    return

In [104]:
for i in range(maxLenClique):
    if maxLenClique-i>1:
        print(maxLenClique-i)
        addCliques(maxLenClique-i)

print(syncretismes)
syncretiques=set()
for l in syncretismes:
    print(l)
    for c in l:
        print(c)
        syncretiques.add(c)

syncretismes,syncretiques,wCliques

5
4
3
2
[['pc1S', 'pc3P', 'fi1S', 'pc2S', 'pc3S'], ['ii3P', 'ii1S', 'ii3S', 'ii2S'], ['ps1S', 'ps2S', 'ps3S', 'ps3P'], ['fi3P', 'fi1P'], ['ppMP', 'ppMS'], ['pi3S', 'pi2S'], ['fi3S', 'fi2S'], ['ppFS', 'ppFP']]
['pc1S', 'pc3P', 'fi1S', 'pc2S', 'pc3S']
pc1S
pc3P
fi1S
pc2S
pc3S
['ii3P', 'ii1S', 'ii3S', 'ii2S']
ii3P
ii1S
ii3S
ii2S
['ps1S', 'ps2S', 'ps3S', 'ps3P']
ps1S
ps2S
ps3S
ps3P
['fi3P', 'fi1P']
fi3P
fi1P
['ppMP', 'ppMS']
ppMP
ppMS
['pi3S', 'pi2S']
pi3S
pi2S
['fi3S', 'fi2S']
fi3S
fi2S
['ppFS', 'ppFP']
ppFS
ppFP

([['pc1S', 'pc3P', 'fi1S', 'pc2S', 'pc3S'],
  ['ii3P', 'ii1S', 'ii3S', 'ii2S'],
  ['ps1S', 'ps2S', 'ps3S', 'ps3P'],
  ['fi3P', 'fi1P'],
  ['ppMP', 'ppMS'],
  ['pi3S', 'pi2S'],
  ['fi3S', 'fi2S'],
  ['ppFS', 'ppFP']],
 {'fi1P',
  'fi1S',
  'fi2S',
  'fi3P',
  'fi3S',
  'ii1S',
  'ii2S',
  'ii3P',
  'ii3S',
  'pc1S',
  'pc2S',
  'pc3P',
  'pc3S',
  'pi2S',
  'pi3S',
  'ppFP',
  'ppFS',
  'ppMP',
  'ppMS',
  'ps1S',
  'ps2S',
  'ps3P',
  'ps3S'},
 [])

In [105]:
dExpansion={s[0]:s for s in syncretismes if len(s)>1}
dExpansion

{'pc1S': ['pc1S', 'pc3P', 'fi1S', 'pc2S', 'pc3S'],
 'ii3P': ['ii3P', 'ii1S', 'ii3S', 'ii2S'],
 'ps1S': ['ps1S', 'ps2S', 'ps3S', 'ps3P'],
 'fi3P': ['fi3P', 'fi1P'],
 'ppMP': ['ppMP', 'ppMS'],
 'pi3S': ['pi3S', 'pi2S'],
 'fi3S': ['fi3S', 'fi2S'],
 'ppFS': ['ppFS', 'ppFP']}

In [106]:
if "fi2S" in dExpansion:
    if "fi3S" in dExpansion["fi2S"]:
        dExpansion[u"fi3S"]=dExpansion.pop("fi2S")
if "ii1S" in dExpansion:
    if "ii3S" in dExpansion["ii1S"]:
        dExpansion[u"ii3S"]=dExpansion.pop("ii1S")
if "pc2S" in dExpansion:
    if "pc3S" in dExpansion["pc2S"]:
        dExpansion[u"pc3S"]=dExpansion.pop("pc2S")
if "ps2S" in dExpansion:
    if "ps3S" in dExpansion["ps2S"]:
        dExpansion[u"ps3S"]=dExpansion.pop("ps2S")        
if "pi2S" in dExpansion:
    if "pi3S" in dExpansion["pi2S"]:
        dExpansion[u"pi3S"]=dExpansion.pop("pi2S")
if "ppMP" in dExpansion:
    if "ppMS" in dExpansion["ppMP"]:
        dExpansion[u"ppMS"]=dExpansion.pop("ppMP")

In [107]:
dExpansion

{'pc1S': ['pc1S', 'pc3P', 'fi1S', 'pc2S', 'pc3S'],
 'ii3P': ['ii3P', 'ii1S', 'ii3S', 'ii2S'],
 'ps1S': ['ps1S', 'ps2S', 'ps3S', 'ps3P'],
 'fi3P': ['fi3P', 'fi1P'],
 'pi3S': ['pi3S', 'pi2S'],
 'fi3S': ['fi3S', 'fi2S'],
 'ppFS': ['ppFS', 'ppFP'],
 'ppMS': ['ppMP', 'ppMS']}

In [108]:
print([c for c in cols if c not in syncretiques])
omps=paradigmes[[c for c in cols if c not in syncretiques]].copy()

['lexeme', 'ai1P', 'ai1S', 'ai2P', 'ai2S', 'ai3P', 'ai3S', 'fi2P', 'ii1P', 'ii2P', 'inf', 'is1S', 'is2P', 'is2S', 'is3P', 'is3S', 'pI1P', 'pI2P', 'pI2S', 'pP', 'pc1P', 'pc2P', 'pi1P', 'pi1S', 'pi2P', 'pi3P', 'ps1P', 'ps2P']

In [118]:
def fusionFormes(row):
    result=[]
    for c in row:
        if c==c:
            result.extend(c.split(","))
    result=list(set(result))
    if result:
        result=",".join(result)
    else:
        result=np.NaN
    return result

In [111]:
for s in dExpansion:
    print (s,dExpansion[s])
    omps[s]=paradigmes[dExpansion[s]].apply(fusionFormes,axis=1)

pc1S ['pc1S', 'pc3P', 'fi1S', 'pc2S', 'pc3S']
ii3P ['ii3P', 'ii1S', 'ii3S', 'ii2S']
ps1S ['ps1S', 'ps2S', 'ps3S', 'ps3P']
fi3P ['fi3P', 'fi1P']
pi3S ['pi3S', 'pi2S']
fi3S ['fi3S', 'fi2S']
ppFS ['ppFS', 'ppFP']
ppMS ['ppMP', 'ppMS']

In [112]:
with open(rep+fParadigmes.replace(".csv","-omp.yaml"),"w") as outFile:
    yaml.safe_dump(dExpansion,outFile)

In [113]:
omps.dropna(thresh=2).to_csv(rep+fParadigmes.replace(".csv","-omp.csv"),encoding="utf8",sep=";",index=None)

In [114]:
if num<9:
    print(num)
    num+=1
    ding()
else:
    num=0
    ding()
    ding()
    ding()
numOMP=num
%store numOMP

6
Stored 'numOMP' (int)