In [2]:
import pandas as pd
import random,glob

# Tirage des échantillons de semaine
- 600 formes verbales par jour, 7 jours par semaines
    - 4200 formes
- 52 semaines par an pendant 8 ans
    - 416 échantillons de 4200 formes

In [9]:
chunk=4200
nbChunks=52*8

In [4]:
fVerbes3='/Users/gilles/ownCloud/Recherche/Boye/HDR/Data/Samples/MGC-171229-Verbes3.pkl'
repDesintegrationSamples="/Users/gilles/ownCloud/Recherche/Boye/HDR/Data/Desintegration/Desintegration-Samples/"

### Lecture de la base de verbes

In [3]:
dfLex=pd.read_pickle(fVerbes3)

In [4]:
del dfLex["ext"]
del dfLex["cs"]
del dfLex["ms"]
del dfLex["vs"]
del dfLex["prob"]

#### Standardisation de la phonologie en notation API

In [5]:
# traduire SAMPA-BDLex en API

def sampa2api(sampa):
    if isinstance(sampa,str):
        api=sampa.decode("utf8")
    else:
        api=sampa
    api=api.replace(u'n"',u'n') 
    api=api.replace(u't"',u't') 
    api=api.replace(u'z"',u'z') 
    api=api.replace(u'R"',u'ʁ') 
    api=api.replace(u'p"',u'p') 
    api=api.replace(u'S',u'ʃ') 
    api=api.replace(u'Z',u'ʒ')
    api=api.replace(u'N',u'ŋ')
    api=api.replace(u'J',u'ɲ')
    api=api.replace(u'r',u'ʁ') 
    api=api.replace(u'H',u'ɥ')
    api=api.replace(u'E',u'ɛ')
    api=api.replace(u'2',u'ø')
    api=api.replace(u'9',u'œ')
    api=api.replace(u'6',u'ə')
    api=api.replace(u'O',u'ɔ')
    api=api.replace(u'è',u'e')   
    api=api.replace(u'ò',u'o')    
    api=api.replace(u'â',u'ɑ̃')   
    api=api.replace(u'ê',u'ɛ̃')   
    api=api.replace(u'û',u'œ̃')  
    api=api.replace(u'ô',u'ɔ̃')       
    api=api.replace(u'@',u'ə')
    api=api.replace(u'R',u'ʁ') 
    return api

In [6]:
dfLex["phono"]=dfLex["phono"].apply(sampa2api)

#### Définition de la fréquence cumulée

In [7]:
dfLex["freqcum"]= (dfLex["freq"].cumsum()*1000).astype(int)
freqMax=dfLex["freqcum"].max()

In [8]:
dfLex

,ortho,phono,lexeme,freq,case,freqcum
40,a,a,avoir,7.167735e+11,pi3S,716773482510576
45,abaissa,abɛsa,abaisser,2.640001e+08,ai3S,717037482636240
46,abaissai,abɛsɛ,abaisser,1.700001e+07,ai1S,717054482650551
47,abaissaient,abɛsɛ,abaisser,4.100005e+07,ii3P,717095482704558
48,abaissais,abɛsɛ,abaisser,4.933548e+01,ii1S,717095482753893
49,abaissais,abɛsɛ,abaisser,4.954692e-01,ii2S,717095482754389
50,abaissait,abɛsɛ,abaisser,2.520003e+08,ii3S,717347483019956
52,abaissant,abɛsɑ̃,abaisser,2.510001e+08,pP,717598483083327
56,abaissas,abɛsa,abaisser,2.565900e-01,ai2S,717598483083584
57,abaissasse,abɛsas,abaisser,3.093462e-01,is1S,717598483083893
58,abaissassent,abɛsas,abaisser,5.334386e-01,is3P,717598483084426
59,abaissasses,abɛsas,abaisser,1.339310e-02,is2S,717598483084440
60,abaissassiez,abɛsasje,abaisser,8.213818e-03,is2P,717598483084448
61,abaissassions,abɛsasjɔ̃,abaisser,2.274855e-02,is1P,717598483084471
64,abaisse,abɛs,abaisser,1.115741e+08,pi1S,717710057218392
65,abaisse,abɛs,abaisser,9.406933e-02,ps1S,717710057218486
66,abaisse,abɛs,abaisser,5.148962e+06,pI2S,717715206180451
67,abaisse,abɛs,abaisser,3.562775e+08,pi3S,718071483668223
68,abaisse,abɛs,abaisser,1.530317e+01,ps3S,718071483683527
71,abaissent,abɛs,abaisser,1.000001e+08,pi3P,718171483753299
72,abaissent,abɛs,abaisser,1.351810e+00,ps3P,718171483754650
73,abaisser,abɛse,abaisser,4.000004e+08,inf,718571484168227
74,abaissera,abɛsəʁa,abaisser,2.600002e+07,fi3S,718597484188055
75,abaisserai,abɛsəʁɛ,abaisser,1.700001e+07,fi1S,718614484198679
76,abaisseraient,abɛsəʁɛ,abaisser,8.000004e+06,pc3P,718622484202738
77,abaisserais,abɛsəʁɛ,abaisser,1.189638e+07,pc1S,718634380583118
78,abaisserais,abɛsəʁɛ,abaisser,1.103631e+06,pc2S,718635484213763
79,abaisserait,abɛsəʁɛ,abaisser,2.200003e+07,pc3S,718657484240438
80,abaisseras,abɛsəʁa,abaisser,4.860260e+00,fi2S,718657484245298
81,abaisserez,abɛsəʁe,abaisser,3.808938e+00,fi2P,718657484249107
...,...,...,...,...,...,...
437513,ôtera,ɔtəʁa,ôter,6.000005e+07,fi3S,34521596872246912
437514,ôterai,ɔtəʁɛ,ôter,1.600003e+07,fi1S,34521612872276172
437515,ôteraient,ɔtəʁɛ,ôter,9.894309e+00,pc3P,34521612872286068
437516,ôterais,ɔtəʁɛ,ôter,1.281150e+07,pc1S,34521625683789644
437517,ôterais,ɔtəʁɛ,ôter,1.188527e+06,pc2S,34521626872316168
437518,ôterait,ɔtəʁɛ,ôter,5.700007e+07,pc3S,34521683872383168
437519,ôteras,ɔtəʁa,ôter,3.100001e+07,fi2S,34521714872396616
437520,ôterez,ɔtəʁe,ôter,3.700001e+07,fi2P,34521751872406960
437521,ôteriez,ɔtəʁje,ôter,4.676073e+00,pc2P,34521751872411636
437522,ôterions,ɔtəʁjɔ̃,ôter,7.000002e+06,pc1P,34521758872414096
437523,ôterons,ɔtəʁɔ̃,ôter,6.861365e+00,fi1P,34521758872420960
437524,ôteront,ɔtəʁɔ̃,ôter,1.111143e+01,fi3P,34521758872432076
437525,ôtes,ot,ôter,6.500016e+07,pi2S,34521823872592988
437526,ôtes,ot,ôter,4.788842e+00,ps2S,34521823872597776
437527,ôtez,ɔte,ôter,2.393235e+07,pI2P,34521847804944396
437528,ôtez,ɔte,ôter,1.870678e+08,pi2P,34522034872777488
437529,ôtiez,ɔtje,ôter,1.700001e+07,ii2P,34522051872786616
437530,ôtiez,ɔtje,ôter,7.132319e-01,ps2P,34522051872787332
437531,ôtions,ɔtjɔ̃,ôter,1.841085e+01,ii1P,34522051872805744
437532,ôtions,ɔtjɔ̃,ôter,3.281248e-01,ps1P,34522051872806072
437533,ôtons,ɔtɔ̃,ôter,4.900007e+00,pI1P,34522051872810968
437534,ôtons,ɔtɔ̃,ôter,9.000045e+06,pi1P,34522060872855752
437535,ôtâmes,ɔtam,ôter,3.721756e+00,ai1P,34522060872859476
437536,ôtât,ɔta,ôter,1.400001e+07,is3S,34522074872872916
437537,ôtâtes,ɔtat,ôter,1.224225e-01,ai2P,34522074872873036
437538,ôtèrent,ɔtɛʁ,ôter,2.700003e+07,ai3P,34522101872904084
437539,ôté,ɔte,ôter,8.650007e+08,ppMS,34522966873587212
437540,ôtée,ɔte,ôter,9.600014e+07,ppFS,34523062873729892
437541,ôtées,ɔte,ôter,2.300004e+07,ppFP,34523085873770952
437542,ôtés,ɔte,ôter,1.800009e+07,ppMP,34523103873861964

### Définition des tirages

In [10]:
%%time
tirage=[]
for n in range(nbChunks*chunk):
    tirage.append(random.randrange(freqMax))

CPU times: user 3.77 s, sys: 240 ms, total: 4.01 s
Wall time: 3.38 s

In [11]:
dfLex["tir1"]=0

In [12]:
def tirage2triage(tirage,cumul=True):    
    triage=sorted(tirage)
    freqTop=0
    indexMin=0
    tirs={}

    for num,tir in enumerate(triage[:]):
        if tir > freqTop:
            indexMin=dfLex[dfLex["freqcum"]>=tir][0:1].index.astype(int)[0]
            freqTop=dfLex.ix[indexMin,'freqcum']
            tirs[indexMin]=0
        tirs[indexMin] += 1
        if num%500000==0:
            print num,
    print
    if cumul:
        for indexNum in tirs:
            dfLex.ix[indexNum,'tir1']+=tirs[indexNum]
    else:
        dfLex['tir1']=0
        for indexNum in tirs:
            dfLex.ix[indexNum,'tir1']=tirs[indexNum]

In [13]:
for nbChunk in range(nbChunks):
    %time tirage2triage(tirage[nbChunk*chunk:(nbChunk+1)*chunk],cumul=False)
    print
    print "nbChunk",nbChunk
    print dfLex[dfLex["tir1"]!=0]["tir1"].sum()
    print dfLex[dfLex["tir1"]!=0]["tir1"].count()
    dfSample=dfLex[dfLex["tir1"]!=0]["lexeme case phono tir1".split(" ")]
    dfSample.to_csv(path_or_buf=repDesintegrationSamples+"DS-%03d-%d.csv"%(nbChunk,chunk),sep="\t",encoding="utf8")
    display(dfSample)
    # with open("/Users/gilles/Box Sync/2015-Data/"+tiragePrefix+"%02d"%(nTile)+echantillon+'-Tirage.pkl', 'wb') as output:
    #     pickle.dump(lexique, output, pickle.HIGHEST_PROTOCOL)

/Users/gilles/opt/anaconda3/envs/python2/lib/python2.7/site-packages/ipykernel_launcher.py:10: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  # Remove the CWD from sys.path while we load stuff.

0

/Users/gilles/opt/anaconda3/envs/python2/lib/python2.7/site-packages/ipykernel_launcher.py:22: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

CPU times: user 1min 10s, sys: 17.5 s, total: 1min 28s
Wall time: 31.5 s

nbChunk 0
4200
1896

             lexeme  case     phono  tir1
40            avoir  pi3S         a    95
132      abandonner   inf  abɑ̃dɔne     2
164      abandonner  ppMS  abɑ̃dɔne     1
243         abattre  pi3S       aba     1
1441        abouter  pI1P    abutɔ̃     1
1943       absenter  pi1S    absɑ̃t     1
2766       accabler  ppMP    akable     1
2887      accentuer  ii3S  aksɑ̃tyɛ     1
2950       accepter  ii3S   aksɛptɛ     1
2971       accepter   inf   aksɛpte     1
2984       accepter  pi2S    aksɛpt     1
3003       accepter  ppMS   aksɛpte     1
3397    accompagner  pi1S   akɔ̃paɲ     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3738        accoter  ppFS     akɔte     1
3913       accouder  ppMS     akude     1
4087       accourir  pi1S      akuʁ     1
4291      accrocher  ppMS    akʁɔʃe     1
4321      accroupir  ppFS    akʁupi     2
4736        accuser  pi2P     akyze     1
5008       acharner  pi3S     aʃaʁn     1
5119        acheter   inf     aʃəte     1
5136        acheter  ppMS     aʃəte     3
5311        acheter  pi3S      aʃɛt     2
5807       acquérir  ppMS       aki     2
6407        adapter  pi1S     adapt     1
6443        adapter  ppMS    adapte     2
6891       admettre   inf    admɛtʁ     1
7031       admettre  ppFS     admiz     1
7294         adorer  ii3P     adɔʁɛ     1
...             ...   ...       ...   ...
427667     éloigner  ai3P   ɛlwaɲɛʁ     1
429337     émouvoir  ii3S     ɛmuvɛ     1
430797      épauler  pi1S      ɛpol     1
431968      éponger  pi1S     ɛpɔ̃ʒ     1
432160      épouser   inf     ɛpuze     2
432695      épuiser  ppMP    ɛpɥize     1
433195   équivaloir  ii3S   ɛkivalɛ     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    11
434070         être  ii3S       ɛtɛ    69
434488         être    pP      ɛtɑ̃     1
434740     éteindre  ai1S     ɛtɛɲi     1
434782      étendre  pi3S      ɛtɑ̃     2
434811      étendre  ai3S    ɛtɑ̃di     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     6
435294       étirer  ppFS     ɛtiʁe     1
435417      étonner  ai3S     ɛtɔna     1
435450      étonner  pc3S   ɛtɔnəʁɛ     1
435484     étouffer  ii3S     ɛtufɛ     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    29
436632     évanouir   inf   ɛvanuiʁ     1
436867     éveiller  ppMS     ɛvɛje     1
437301       éviter   inf     ɛvite     2
437417      évoquer    pP    ɛvɔkɑ̃     1
437474         être  pi2P        ɛt    12
437476         être   inf       ɛtʁ    20
437497         ôter  ii3S       ɔtɛ     1
437539         ôter  ppMS       ɔte     1

[1896 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 20.3 s, total: 1min 33s
Wall time: 30.7 s

nbChunk 1
4200
1899

             lexeme  case      phono  tir1
40            avoir  pi3S          a   101
145      abandonner  pi2S    abɑ̃dɔn     1
164      abandonner  ppMS   abɑ̃dɔne     1
1950       absenter   inf    absɑ̃te     1
2070       absorber   inf    absɔʁbe     1
2123       absoudre  ppMS       absu     1
2581         abîmer   inf      abime     1
3406    accompagner   inf   akɔ̃paɲe     2
3433    accompagner  ppMS   akɔ̃paɲe     1
3471      accomplir  ps3S   akɔ̃plis     1
3536       accorder   inf     akɔʁde     1
4426     accréditer   inf   akʁɛdite     1
4519     accueillir  ai3S      akəji     2
4686      accumuler  ppMP    akymyle     1
5041       acharner  ppMS     aʃaʁne     1
5119        acheter   inf      aʃəte     2
5311        acheter  pi3S       aʃɛt     1
5320        acheter  pc3S    aʃɛtəʁɛ     1
5852      acquitter   inf      akite     1
6891       admettre   inf     admɛtʁ     2
6970        admirer    pP    admiʁɑ̃     1
7227        adopter  ai1S     adɔptɛ     1
7297         adorer  ii3S      adɔʁɛ     1
7312         adorer  pi3S       adɔʁ     1
7343         adorer  ppMS      adɔʁe     1
7458        adoucir   inf     adusiʁ     1
7518       adresser  ai3S     adʁɛsa     1
8243        affaler  ppMP      afale     1
8420       affecter  ppFP     afɛkte     1
8550       afficher  pi3S       afiʃ     1
...             ...   ...        ...   ...
427840       éluder  ai3S      ɛlyda     1
427929       élever  pc3P    ɛlɛvəʁɛ     1
428847      émettre  ppFS       ɛmiz     1
429691      énerver  pi1S      ɛnɛʁv     1
430590     épargner  ppMS     ɛpaʁɲe     1
432138      épouser  ai3S      ɛpuza     1
433196   équivaloir    pP   ɛkivalɑ̃     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    15
434070         être  ii3S        ɛtɛ    71
434134       étaler  ii3S      ɛtalɛ     1
434298       étaler  ai3P     ɛtalɛʁ     1
434772     éteindre  ppMS       ɛtɛ̃     1
434794      étendre  pi3P      ɛtɑ̃d     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
434895    éterniser  ppMS   ɛtɛʁnize     1
435054         être  ii2P       ɛtje     1
435111    étinceler  ai3P  ɛtɛ̃səlɛʁ     1
435172         être  ii1P      ɛtjɔ̃     1
435417      étonner  ai3S      ɛtɔna     1
435438      étonner  pi3S       ɛtɔn     1
435506     étouffer   inf      ɛtufe     1
436316         être  ppMS        ɛte    31
436457       évader   inf      ɛvade     1
437280       éviter  ai1S      ɛvitɛ     1
437295       éviter  pi3S       ɛvit     1
437328       éviter  ppMS      ɛvite     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    26

[1899 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 20.2 s, total: 1min 33s
Wall time: 32 s

nbChunk 2
4200
1937

             lexeme  case     phono  tir1
40            avoir  pi3S         a    82
128      abandonner  pi3S   abɑ̃dɔn     2
132      abandonner   inf  abɑ̃dɔne     2
264         abattre  pi3P      abat     1
585        abhorrer  pi3S      abɔʁ     1
1147        aborder   inf    abɔʁde     1
1674        abriter    pP   abʁitɑ̃     1
2063       absorber  pi1S    absɔʁb     1
2102       absorber  ppFS   absɔʁbe     1
2371         abuser  ppMS     abyze     1
2581         abîmer   inf     abime     1
2971       accepter   inf   aksɛpte     1
3005       accepter  ppFS   aksɛpte     1
3385    accompagner  ii3S  akɔ̃paɲɛ     2
3433    accompagner  ppMS  akɔ̃paɲe     1
3443      accomplir   inf  akɔ̃pliʁ     2
3629       accoster  ai3S    akɔsta     1
3825      accoucher  pi3P      akuʃ     1
4210     accoutumer  ppMS   akutyme     1
4519     accueillir  ai3S     akəji     1
4750        accuser  ppFS     akyze     1
4771        accéder  ii3S    aksɛdɛ     1
5111        acheter  ii3S     aʃətɛ     1
5119        acheter   inf     aʃəte     1
5136        acheter  ppMS     aʃəte     2
5140        achever  ai3S     aʃəva     1
6072        activer   inf    aktive     1
6414        adapter   inf    adapte     1
7013        admirer  ii2P   admiʁje     1
7283        adopter  ppMS    adɔpte     1
...             ...   ...       ...   ...
432302      épouser  ppMS     ɛpuze     1
432303      épouser  ppFS     ɛpuze     1
433354      érafler  ppMS    ɛʁafle     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ    13
434069         être  ii2S       ɛtɛ     2
434070         être  ii3S       ɛtɛ    84
434147       étaler  pi3S      ɛtal     1
434770     éteindre  pi2S      ɛtɛ̃     1
434772     éteindre  ppMS      ɛtɛ̃     1
434779     éteindre  ppMP      ɛtɛ̃     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     1
435418      étonner  ai1S     ɛtɔnɛ     1
436203      étudier  pi3P     ɛtydi     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    20
436627     évanouir  ppMS    ɛvanui     1
436836     éveiller  fi3S   ɛvɛjəʁa     1
437284       éviter  ii3S     ɛvitɛ     1
437285       éviter    pP    ɛvitɑ̃     1
437301       éviter   inf     ɛvite     1
437318       éviter  ii2P    ɛvitje     1
437416      évoquer  ii3S     ɛvɔkɛ     1
437431      évoquer   inf     ɛvɔke     2
437474         être  pi2P        ɛt    15
437476         être   inf       ɛtʁ    24
437495         ôter  ii1S       ɔtɛ     1
437497         ôter  ii3S       ɔtɛ     1

[1937 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 20.2 s, total: 1min 38s
Wall time: 31.1 s

nbChunk 3
4200
1971

             lexeme  case     phono  tir1
40            avoir  pi3S         a    74
73         abaisser   inf     abɛse     1
132      abandonner   inf  abɑ̃dɔne     2
166      abandonner  ppFS  abɑ̃dɔne     1
305         abattre  ppMS     abaty     1
1326        abouler  pI2P     abule     1
1460         aboyer  ii3S    abwajɛ     1
1859        abréger  pi3S     abʁɛʒ     1
2066       absorber  pi3S    absɔʁb     1
2143       abstenir   inf  abstəniʁ     1
2355         abuser  pi2P     abyze     1
2594         abîmer  pi2S      abim     1
2612         abîmer  ppFS     abime     1
2712       accabler  ii3P    akablɛ     1
3347     accommoder  pi3P    akɔmɔd     1
3400    accompagner  pi3S   akɔ̃paɲ     2
3406    accompagner   inf  akɔ̃paɲe     1
3419    accompagner  pi2S   akɔ̃paɲ     1
3434    accompagner  ppFS  akɔ̃paɲe     1
3573       accorder  ppFS    akɔʁde     1
4230      accrocher  ai3S    akʁɔʃa     1
4291      accrocher  ppMS    akʁɔʃe     1
4519     accueillir  ai3S     akəji     1
4736        accuser  pi2P     akyze     1
4758        accéder  pi3S     aksɛd     1
4783        accéder   inf    aksɛde     1
4823      accélérer  ii3S  aksɛlɛʁɛ     1
5070      acheminer   inf   aʃəmine     1
5119        acheter   inf     aʃəte     3
5136        acheter  ppMS     aʃəte     3
...             ...   ...       ...   ...
428620      émettre  pi3P      ɛmɛt     1
429694      énerver  pi3S     ɛnɛʁv     1
430558     épargner  pi3S     ɛpaʁɲ     1
431992      éponger   inf    ɛpɔ̃ʒe     1
432156      épouser  pi3S      ɛpuz     2
432160      épouser   inf     ɛpuze     1
432537     éprouver  ii3S    ɛpʁuvɛ     1
432653      épuiser  pi3S     ɛpɥiz     1
434048         être  ii3P       ɛtɛ     1
434068         être  ii1S       ɛtɛ     9
434070         être  ii3S       ɛtɛ    59
434072       étaler  ai3S     ɛtala     1
434488         être    pP      ɛtɑ̃     1
434726     éteindre  ii3S     ɛtɛɲɛ     2
434730     éteindre  pi3P      ɛtɛɲ     1
435471      étonner  ppMS     ɛtɔne     1
435500     étouffer  pi3S      ɛtuf     1
435506     étouffer   inf     ɛtufe     1
435748    étrangler   inf  ɛtʁɑ̃gle     1
436213      étudier  fi2P   ɛtydiʁe     1
436316         être  ppMS       ɛte    21
436457       évader   inf     ɛvade     1
436652     évanouir  pi2S    ɛvanui     1
436815     éveiller  ai3S     ɛvɛja     1
436820     éveiller  ii3S     ɛvɛjɛ     1
437285       éviter    pP    ɛvitɑ̃     1
437301       éviter   inf     ɛvite     2
437329       éviter  ppFS     ɛvite     1
437474         être  pi2P        ɛt    11
437476         être   inf       ɛtʁ    22

[1971 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 20.2 s, total: 1min 32s
Wall time: 31.4 s

nbChunk 4
4200
1916

             lexeme  case       phono  tir1
40            avoir  pi3S           a    84
128      abandonner  pi3S     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     3
133      abandonner  fi3S  abɑ̃dɔnəʁa     1
164      abandonner  ppMS    abɑ̃dɔne     1
297         abattre  pc3S      abatʁɛ     1
1147        aborder   inf      abɔʁde     1
1670        abriter  ii3P      abʁitɛ     1
1885        abréger  fi3S    abʁɛʒəʁa     1
2128       absoudre  ppFS       absut     1
2820      accaparer  ppFP     akapaʁe     1
2971       accepter   inf     aksɛpte     1
3386    accompagner    pP   akɔ̃paɲɑ̃     1
3406    accompagner   inf    akɔ̃paɲe     1
3408    accompagner  fi1S  akɔ̃paɲəʁɛ     2
3433    accompagner  ppMS    akɔ̃paɲe     1
3488      accomplir  pi1P  akɔ̃plisɔ̃     1
3530       accorder  pi3S       akɔʁd     1
4090       accourir  pi3S        akuʁ     1
4163     accoutumer  ii1S     akutymɛ     1
4479     accueillir  pi1S        akœj     1
4635      accumuler  ii1S     akymylɛ     1
4716        accuser  pi3S        akyz     1
4720        accuser   inf       akyze     1
4823      accélérer  ii3S    aksɛlɛʁɛ     1
4835      accélérer   inf    aksɛlɛʁe     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     1
5139        acheter  ppMP       aʃəte     1
5311        acheter  pi3S        aʃɛt     1
...             ...   ...         ...   ...
432160      épouser   inf       ɛpuze     2
432167      épouser  fi2S     ɛpuzəʁa     1
432302      épouser  ppMS       ɛpuze     1
432552     éprouver  pi3S       ɛpʁuv     1
432581     éprouver  ai1P     ɛpʁuvam     1
432586     éprouver  ppMS      ɛpʁuve     1
433912      établir  ppMS      ɛtabli     1
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ     9
434070         être  ii3S         ɛtɛ    77
434300       étaler  ppFS       ɛtale     1
434723     éteindre  ii3P       ɛtɛɲɛ     1
434726     éteindre  ii3S       ɛtɛɲɛ     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     5
435471      étonner  ppMS       ɛtɔne     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
435951     étriller  ppMP      ɛtʁije     1
436198      étudier  pi1S       ɛtydi     1
436316         être  ppMS         ɛte    25
436457       évader   inf       ɛvade     1
436632     évanouir   inf     ɛvanuiʁ     2
436821     éveiller    pP      ɛvɛjɑ̃     1
436869     éveiller  ppFS       ɛvɛje     1
437285       éviter    pP      ɛvitɑ̃     1
437461      évoquer  ppMP       ɛvɔke     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    15
437539         ôter  ppMS         ɔte     1

[1916 rows x 4 columns]

0
CPU times: user 1min 6s, sys: 20.4 s, total: 1min 27s
Wall time: 33.7 s

nbChunk 5
4200
1951

             lexeme  case      phono  tir1
40            avoir  pi3S          a    95
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     1
914          abolir    pP   abɔlisɑ̃     1
1468         aboyer   inf     abwaje     1
2106       absorber  ppMP    absɔʁbe     1
2355         abuser  pi2P      abyze     1
2593         abîmer  fi3P   abiməʁɔ̃     1
2975       accepter  pc1S  aksɛptəʁɛ     1
2988       accepter  pI2P    aksɛpte     1
3005       accepter  ppFS    aksɛpte     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3404    accompagner  pi3P    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3571       accorder  ppMS     akɔʁde     1
4063       accourir  pi3P       akuʁ     1
4091       accourir  ppMS      akuʁy     1
4234      accrocher  ii3P     akʁɔʃɛ     1
4321      accroupir  ppFS     akʁupi     1
4368      accroupir  ai3S     akʁupi     1
4482     accueillir  pi3S       akœj     1
4484     accueillir  pi3P       akœj     1
4686      accumuler  ppMP    akymyle     1
4694        accuser    pP     akyzɑ̃     1
4720        accuser   inf      akyze     1
5027       acharner  pi2S      aʃaʁn     1
5136        acheter  ppMS      aʃəte     2
5140        achever  ai3S      aʃəva     1
5157        achever   inf      aʃəve     1
5311        acheter  pi3S       aʃɛt     1
...             ...   ...        ...   ...
429694      énerver  pi3S      ɛnɛʁv     1
430562     épargner   inf     ɛpaʁɲe     1
432160      épouser   inf      ɛpuze     1
432586     éprouver  ppMS     ɛpʁuve     1
432689      épuiser  ppMS     ɛpɥize     1
433174      équiper  ppMP      ɛkipe     1
433969      établir  pi3S     ɛtabli     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ    11
434070         être  ii3S        ɛtɛ    76
434301       étaler  ppFP      ɛtale     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     2
435408      étoiler  ppMS     ɛtwale     1
435417      étonner  ai3S      ɛtɔna     1
435425      étonner    pP     ɛtɔnɑ̃     1
435444      étonner   inf      ɛtɔne     1
436218      étudier  pi2S      ɛtydi     1
436316         être  ppMS        ɛte    20
436402      évacuer   inf     ɛvakye     1
436632     évanouir   inf    ɛvanuiʁ     1
436820     éveiller  ii3S      ɛvɛjɛ     1
437282       éviter  ii1S      ɛvitɛ     1
437284       éviter  ii3S      ɛvitɛ     1
437329       éviter  ppFS      ɛvite     1
437444      évoquer  pi2S       ɛvɔk     1
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    19
437493         ôter  ai1S        ɔtɛ     1
437497         ôter  ii3S        ɔtɛ     1

[1951 rows x 4 columns]

0
CPU times: user 1min 9s, sys: 20.4 s, total: 1min 29s
Wall time: 32.2 s

nbChunk 6
4200
1932

             lexeme  case       phono  tir1
40            avoir  pi3S           a    94
132      abandonner   inf    abɑ̃dɔne     1
148      abandonner  pi2P    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     1
299         abattre   inf       abatʁ     2
1132        aborder  ii3S      abɔʁdɛ     1
2730       accabler  pi3S       akabl     1
2967       accepter  pi3S      aksɛpt     1
2975       accepter  pc1S   aksɛptəʁɛ     1
2983       accepter  fi3P  aksɛptəʁɔ̃     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     1
3421    accompagner  pI2P    akɔ̃paɲe     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3738        accoter  ppFS       akɔte     1
4235      accrocher  ii1S      akʁɔʃɛ     1
4496     accueillir  fi1P    akəjəʁɔ̃     1
4509     accueillir   inf      akəjiʁ     1
4713        accuser  pi1S        akyz     1
4997       acharner  ii3S      aʃaʁnɛ     1
5125        acheter  pi2P       aʃəte     1
5137        acheter  ppFS       aʃəte     1
5313        acheter  pi3P        aʃɛt     1
6414        adapter   inf      adapte     1
6991        admirer  pi3S       admiʁ     1
7221        adonner  ppMP       adɔne     1
7295         adorer  ii1S       adɔʁɛ     1
7314         adorer  pi3P        adɔʁ     1
7349        adosser  ai3S       adɔsa     1
7518       adresser  ai3S      adʁɛsa     2
...             ...   ...         ...   ...
429677      énerver  ii3S      ɛnɛʁvɛ     1
430156     épaissir  ppFS       ɛpɛsi     1
431065        épier    pP       ɛpjɑ̃     1
432142      épouser  ii1S       ɛpuzɛ     1
432155      épouser  pI2S        ɛpuz     1
432166      épouser  pc3S     ɛpuzəʁɛ     1
432171      épouser  fi1P    ɛpuzəʁɔ̃     1
432302      épouser  ppMS       ɛpuze     2
432586     éprouver  ppMS      ɛpʁuve     1
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ    12
434070         être  ii3S         ɛtɛ    73
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434831      étendre  ppMS      ɛtɑ̃dy     1
434923     éternuer   inf     ɛtɛʁnye     1
434936     éternuer  pi2S      ɛtɛʁny     1
435054         être  ii2P        ɛtje     2
435133      étioler  pi3P       ɛtjɔl     1
435232       étirer  ai3S       ɛtiʁa     1
435444      étonner   inf       ɛtɔne     1
435506     étouffer   inf       ɛtufe     1
436316         être  ppMS         ɛte    20
436815     éveiller  ai3S       ɛvɛja     1
437295       éviter  pi3S        ɛvit     1
437301       éviter   inf       ɛvite     2
437308       éviter  fi2S     ɛvitəʁa     1
437427      évoquer  pi3S        ɛvɔk     1
437474         être  pi2P          ɛt     9
437476         être   inf         ɛtʁ    22
437528         ôter  pi2P         ɔte     1

[1932 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 18.5 s, total: 1min 31s
Wall time: 30.3 s

nbChunk 7
4200
1873

             lexeme  case      phono  tir1
40            avoir  pi3S          a    96
125      abandonner  pi1S    abɑ̃dɔn     1
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
148      abandonner  pi2P   abɑ̃dɔne     1
1460         aboyer  ii3S     abwajɛ     1
2736       accabler   inf     akable     1
2971       accepter   inf    aksɛpte     1
2972       accepter  fi3S  aksɛptəʁa     1
3436    accompagner  ppMP   akɔ̃paɲe     1
3475      accomplir  pi3P   akɔ̃plis     1
3536       accorder   inf     akɔʁde     1
3555       accorder  pI2P     akɔʁde     1
3821      accoucher  pi3S       akuʃ     1
4234      accrocher  ii3P     akʁɔʃɛ     1
4291      accrocher  ppMS     akʁɔʃe     1
4293      accrocher  ppFP     akʁɔʃe     1
4502     accueillir  ppMS      akəji     1
4713        accuser  pi1S       akyz     1
5108        acheter  ii3P      aʃətɛ     1
5119        acheter   inf      aʃəte     1
5136        acheter  ppMS      aʃəte     2
5146        achever  ii3P      aʃəvɛ     1
5308        acheter  pi1S       aʃɛt     1
5313        acheter  pi3P       aʃɛt     1
5316        acheter  fi1S    aʃɛtəʁɛ     1
5879      acquitter  ppMS      akite     1
6043      actionner  ppMS    aksjɔne     1
6443        adapter  ppMS     adapte     1
6891       admettre   inf     admɛtʁ     2
...             ...   ...        ...   ...
432423   épouvanter  ppMP   ɛpuvɑ̃te     1
432577     éprouver  ii1P   ɛpʁuvjɔ̃     1
432586     éprouver  ppMS     ɛpʁuve     1
433113      équiper   inf      ɛkipe     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    20
434070         être  ii3S        ɛtɛ    61
434733     éteindre  pI2P      ɛtɛɲe     1
434777     éteindre  ppFP      ɛtɛ̃t     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     1
435135      étioler   inf     ɛtjɔle     1
435244       étirer    pP     ɛtiʁɑ̃     1
435438      étonner  pi3S       ɛtɔn     1
435444      étonner   inf      ɛtɔne     1
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435519     étouffer  pi2S       ɛtuf     1
435536     étouffer  ai3P     ɛtufɛʁ     1
435731    étrangler  ii3S   ɛtʁɑ̃glɛ     1
435732    étrangler    pP  ɛtʁɑ̃glɑ̃     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
436316         être  ppMS        ɛte    33
436484       évader  ppMS      ɛvade     1
436627     évanouir  ppMS     ɛvanui     1
437281       éviter  ii3P      ɛvitɛ     1
437301       éviter   inf      ɛvite     2
437427      évoquer  pi3S       ɛvɔk     1
437474         être  pi2P         ɛt    10
437476         être   inf        ɛtʁ    19

[1873 rows x 4 columns]

0
CPU times: user 1min 6s, sys: 21.3 s, total: 1min 28s
Wall time: 33.8 s

nbChunk 8
4200
1954

             lexeme  case      phono  tir1
40            avoir  pi3S          a    71
125      abandonner  pi1S    abɑ̃dɔn     1
128      abandonner  pi3S    abɑ̃dɔn     1
1688        abriter   inf     abʁite     1
2577         abîmer  pi3S       abim     1
2581         abîmer   inf      abime     1
2712       accabler  ii3P     akablɛ     1
2939       accepter  ai3S    aksɛpta     1
2964       accepter  pi1S     aksɛpt     1
2971       accepter   inf    aksɛpte     2
2972       accepter  fi3S  aksɛptəʁa     1
2989       accepter  pi2P    aksɛpte     1
3003       accepter  ppMS    aksɛpte     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3438      accomplir  ppMS    akɔ̃pli     1
3536       accorder   inf     akɔʁde     1
4626        acculer  ppMS      akyle     1
4685      accumuler  ppFP    akymyle     1
4688        accuser  ai3S      akyza     1
4693        accuser  ii3S      akyzɛ     1
4716        accuser  pi3S       akyz     1
5014       acharner   inf     aʃaʁne     1
5111        acheter  ii3S      aʃətɛ     1
5119        acheter   inf      aʃəte     2
5137        acheter  ppFS      aʃəte     1
5157        achever   inf      aʃəve     1
5835      acquitter  ii3S      akitɛ     1
6807        adjurer  ii3P     adʒyʁɛ     1
7250        adopter   inf     adɔpte     1
...             ...   ...        ...   ...
432156      épouser  pi3S       ɛpuz     1
432160      épouser   inf      ɛpuze     1
432302      épouser  ppMS      ɛpuze     1
432369   épouvanter  ii3P   ɛpuvɑ̃tɛ     1
433969      établir  pi3S     ɛtabli     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ     9
434070         être  ii3S        ɛtɛ    69
434723     éteindre  ii3P      ɛtɛɲɛ     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434773     éteindre  pi3S       ɛtɛ̃     1
434782      étendre  pi3S       ɛtɑ̃     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     3
435258       étirer  pi3P       ɛtiʁ     1
435506     étouffer   inf      ɛtufe     1
435538     étouffer  ppMS      ɛtufe     1
435711     étourdir  pi3S     ɛtuʁdi     1
435838    étreindre  pi3S      ɛtʁɛ̃     1
436205      étudier   inf     ɛtydje     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    20
436629     évanouir  ppFS     ɛvanui     1
436815     éveiller  ai3S      ɛvɛja     1
436897      éventer  pi1S      ɛvɑ̃t     1
437114       évider  pi1S       ɛvid     1
437353      évoluer    pP    ɛvɔlyɑ̃     1
437413      évoquer  ii3P      ɛvɔkɛ     1
437474         être  pi2P         ɛt    10
437476         être   inf        ɛtʁ    22

[1954 rows x 4 columns]

0
CPU times: user 1min 6s, sys: 22.3 s, total: 1min 29s
Wall time: 34.8 s

nbChunk 9
4200
1947

             lexeme  case       phono  tir1
40            avoir  pi3S           a    94
132      abandonner   inf    abɑ̃dɔne     1
145      abandonner  pi2S     abɑ̃dɔn     1
164      abandonner  ppMS    abɑ̃dɔne     1
2766       accabler  ppMP      akable     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     1
2980       accepter  pc2P  aksɛptəʁje     1
3003       accepter  ppMS     aksɛpte     1
3007       accepter  ppFP     aksɛpte     1
3313        accoler  ppMS       akɔle     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3433    accompagner  ppMS    akɔ̃paɲe     1
4210     accoutumer  ppMS     akutyme     1
4292      accrocher  ppFS      akʁɔʃe     1
4682      accumuler  ai3P    akymylɛʁ     1
4748        accuser  ppMS       akyze     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     1
5149        achever  ii3S       aʃəvɛ     1
5150        achever    pP      aʃəvɑ̃     1
5328        acheter  ps2S        aʃɛt     1
6043      actionner  ppMS     aksjɔne     1
6446        adapter  ppMP      adapte     1
6457    additionner    pP   adisjɔnɑ̃     1
6464    additionner  pi1S     adisjɔn     1
6891       admettre   inf      admɛtʁ     1
7046       admettre  ai3S        admi     1
7312         adorer  pi3S        adɔʁ     3
7539       adresser   inf      adʁɛse     1
...             ...   ...         ...   ...
432157      épouser  ps3S        ɛpuz     1
432532     éprouver  ai3S      ɛpʁuva     1
432552     éprouver  pi3S       ɛpʁuv     1
433169      équiper  ppMS       ɛkipe     1
433325      érafler   inf      ɛʁafle     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ    11
434070         être  ii3S         ɛtɛ    69
434734     éteindre  pi2P       ɛtɛɲe     1
434747     éteindre  ai3S       ɛtɛɲi     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434833      étendre  ppFS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     1
435417      étonner  ai3S       ɛtɔna     1
435438      étonner  pi3S        ɛtɔn     1
435506     étouffer   inf       ɛtufe     1
435512     étouffer  pc3S     ɛtufəʁɛ     1
435532     étouffer  pi1P      ɛtufɔ̃     1
435780    étrangler  ppMS    ɛtʁɑ̃gle     1
435837    étreindre  ppMS       ɛtʁɛ̃     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    29
436484       évader  ppMS       ɛvade     1
436627     évanouir  ppMS      ɛvanui     1
436820     éveiller  ii3S       ɛvɛjɛ     1
437124       évider  pi3P        ɛvid     1
437285       éviter    pP      ɛvitɑ̃     1
437474         être  pi2P          ɛt     9
437476         être   inf         ɛtʁ    16

[1947 rows x 4 columns]

0
CPU times: user 1min 4s, sys: 22.7 s, total: 1min 26s
Wall time: 35.8 s

nbChunk 10
4200
1981

             lexeme  case       phono  tir1
40            avoir  pi3S           a    73
113      abandonner  ii3S    abɑ̃dɔnɛ     1
132      abandonner   inf    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     1
910          abolir  ii3P     abɔlisɛ     1
2066       absorber  pi3S      absɔʁb     1
2324         abuser  ii3S       abyzɛ     1
2394      abâtardir  fi1S  abataʁdiʁɛ     1
2577         abîmer  pi3S        abim     1
2715       accabler  ii3S      akablɛ     1
2966       accepter  pI2S      aksɛpt     1
2967       accepter  pi3S      aksɛpt     1
3343     accommoder  pi3S      akɔmɔd     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
3914       accouder  ppFS       akude     1
4237      accrocher  ii3S      akʁɔʃɛ     1
4294      accrocher  ppMP      akʁɔʃe     1
4323      accroupir   inf     akʁupiʁ     1
4373      accroître  pi3S       akʁwa     1
4716        accuser  pi3S        akyz     1
4720        accuser   inf       akyze     1
4771        accéder  ii3S      aksɛdɛ     1
4835      accélérer   inf    aksɛlɛʁe     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     1
5137        acheter  ppFS       aʃəte     1
5139        acheter  ppMP       aʃəte     2
...             ...   ...         ...   ...
427668     éloigner  ppMS      ɛlwaɲe     1
428104      émacier  ppMS      ɛmasje     1
428176       émaner  ii3S       ɛmanɛ     1
428572  émerveiller  pi3S     ɛmɛʁvɛj     1
430485     épanouir   inf     ɛpanuiʁ     1
431131       épicer  ppMS       ɛpise     1
432156      épouser  pi3S        ɛpuz     1
432302      épouser  ppMS       ɛpuze     1
432659      épuiser   inf      ɛpɥize     1
433912      établir  ppMS      ɛtabli     3
434048         être  ii3P         ɛtɛ     7
434068         être  ii1S         ɛtɛ    12
434070         être  ii3S         ɛtɛ    73
434072       étaler  ai3S       ɛtala     1
434868    éterniser   inf    ɛtɛʁnize     1
434917     éternuer  pi3S      ɛtɛʁny     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     1
436198      étudier  pi1S       ɛtydi     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    22
436547      évaluer  ppMS      ɛvalye     1
436656     évanouir  ii3S    ɛvanuisɛ     1
436835     éveiller   inf       ɛvɛje     1
437284       éviter  ii3S       ɛvitɛ     1
437285       éviter    pP      ɛvitɑ̃     1
437323       éviter  pi1P      ɛvitɔ̃     1
437474         être  pi2P          ɛt     9
437476         être   inf         ɛtʁ    18
437494         ôter  ii3P         ɔtɛ     1

[1981 rows x 4 columns]

0
CPU times: user 1min 7s, sys: 21.9 s, total: 1min 29s
Wall time: 34.7 s

nbChunk 11
4200
1972

             lexeme  case      phono  tir1
40            avoir  pi3S          a    81
128      abandonner  pi3S    abɑ̃dɔn     1
299         abattre   inf      abatʁ     1
1128        aborder  ai1S     abɔʁdɛ     1
1951       absenter  fi3S  absɑ̃təʁa     1
2070       absorber   inf    absɔʁbe     1
2102       absorber  ppFS    absɔʁbe     1
2133       abstenir  ii1S    abstənɛ     1
2136       abstenir    pP   abstənɑ̃     1
2157       abstenir  ppMP    abstəny     1
2947       accepter  ii3P    aksɛptɛ     1
2967       accepter  pi3S     aksɛpt     3
2971       accepter   inf    aksɛpte     1
2977       accepter  pc3S  aksɛptəʁɛ     1
2989       accepter  pi2P    aksɛpte     1
2999       accepter  is3S    aksɛpta     1
3003       accepter  ppMS    aksɛpte     1
3007       accepter  ppFP    aksɛpte     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3443      accomplir   inf   akɔ̃pliʁ     1
3467      accomplir  ii3S  akɔ̃plisɛ     1
3527       accorder  pi1S      akɔʁd     1
3970      accoupler   inf     akuple     1
4182     accoutumer   inf    akutyme     1
4259      accrocher   inf     akʁɔʃe     2
4368      accroupir  ai3S     akʁupi     1
4511     accueillir  ppMP      akəji     1
4519     accueillir  ai3S      akəji     1
4686      accumuler  ppMP    akymyle     1
5119        acheter   inf      aʃəte     3
...             ...   ...        ...   ...
432569     éprouver  pi2S      ɛpʁuv     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    17
434070         être  ii3S        ɛtɛ    66
434762     éteindre   inf     ɛtɛ̃dʁ     2
434833      étendre  ppFS     ɛtɑ̃dy     2
435054         être  ii2P       ɛtje     6
435254       étirer  pi3S       ɛtiʁ     1
435417      étonner  ai3S      ɛtɔna     1
435438      étonner  pi3S       ɛtɔn     1
435471      étonner  ppMS      ɛtɔne     1
435481     étouffer  ii3P      ɛtufɛ     1
435484     étouffer  ii3S      ɛtufɛ     1
435519     étouffer  pi2S       ɛtuf     1
435726    étrangler  ai3S   ɛtʁɑ̃gla     1
435731    étrangler  ii3S   ɛtʁɑ̃glɛ     1
435838    étreindre  pi3S      ɛtʁɛ̃     1
436184      étudier  ii1S     ɛtydjɛ     1
436201      étudier  pi3S      ɛtydi     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    25
436815     éveiller  ai3S      ɛvɛja     1
436821     éveiller    pP     ɛvɛjɑ̃     1
437295       éviter  pi3S       ɛvit     1
437301       éviter   inf      ɛvite     2
437329       éviter  ppFS      ɛvite     1
437427      évoquer  pi3S       ɛvɔk     1
437474         être  pi2P         ɛt     8
437476         être   inf        ɛtʁ    15
437512         ôter   inf        ɔte     2

[1972 rows x 4 columns]

0
CPU times: user 1min 10s, sys: 20.8 s, total: 1min 31s
Wall time: 32.4 s

nbChunk 12
4200
1939

            lexeme  case       phono  tir1
40           avoir  pi3S           a    70
111     abandonner  ii1S    abɑ̃dɔnɛ     1
164     abandonner  ppMS    abɑ̃dɔne     1
243        abattre  pi3S         aba     1
1388       aboutir  ppMS       abuti     2
1393       aboutir   inf      abutiʁ     2
1468        aboyer   inf      abwaje     1
1684       abriter  pi3S       abʁit     1
2594        abîmer  pi2S        abim     1
2964      accepter  pi1S      aksɛpt     1
2967      accepter  pi3S      aksɛpt     2
2971      accepter   inf     aksɛpte     2
2975      accepter  pc1S   aksɛptəʁɛ     1
3003      accepter  ppMS     aksɛpte     1
3322    accommoder  ii3S     akɔmɔdɛ     1
3438     accomplir  ppMS     akɔ̃pli     1
3443     accomplir   inf    akɔ̃pliʁ     1
3465     accomplir  ii1S   akɔ̃plisɛ     1
3468     accomplir    pP  akɔ̃plisɑ̃     1
3536      accorder   inf      akɔʁde     1
4292     accrocher  ppFS      akʁɔʃe     1
4381     accroître   inf     akʁwatʁ     1
4519    accueillir  ai3S       akəji     1
4737       accuser  ii2P      akyzje     1
4809     accélérer  pi1S     aksɛlɛʁ     1
4812     accélérer  pi3S     aksɛlɛʁ     1
4823     accélérer  ii3S    aksɛlɛʁɛ     1
5008      acharner  pi3S       aʃaʁn     1
5041      acharner  ppMS      aʃaʁne     1
5042      acharner  ppFS      aʃaʁne     1
...            ...   ...         ...   ...
431789       épier  ppFS        ɛpje     1
431871    éplucher   inf      ɛplyʃe     1
432153     épouser  pi1S        ɛpuz     1
432302     épouser  ppMS       ɛpuze     1
432537    éprouver  ii3S      ɛpʁuvɛ     2
432552    éprouver  pi3S       ɛpʁuv     2
432556    éprouver   inf      ɛpʁuve     3
433199  équivaloir  pi3P      ɛkival     1
434048        être  ii3P         ɛtɛ     3
434068        être  ii1S         ɛtɛ    13
434069        être  ii2S         ɛtɛ     1
434070        être  ii3S         ɛtɛ    76
434762    éteindre   inf      ɛtɛ̃dʁ     1
434773    éteindre  pi3S        ɛtɛ̃     1
434775    éteindre  ppFS       ɛtɛ̃t     1
434831     étendre  ppMS      ɛtɑ̃dy     1
435054        être  ii2P        ɛtje     1
435172        être  ii1P       ɛtjɔ̃     2
435295      étirer  ppFP       ɛtiʁe     1
435471     étonner  ppMS       ɛtɔne     2
435506    étouffer   inf       ɛtufe     1
435970     étriper  pi3P       ɛtʁip     1
436205     étudier   inf      ɛtydje     1
436316        être  ppMS         ɛte    21
437301      éviter   inf       ɛvite     1
437412     évoquer  ai1S       ɛvɔkɛ     1
437427     évoquer  pi3S        ɛvɔk     2
437474        être  pi2P          ɛt    10
437476        être   inf         ɛtʁ    23
437497        ôter  ii3S         ɔtɛ     1

[1939 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 20.3 s, total: 1min 37s
Wall time: 32.5 s

nbChunk 13
4200
1950

             lexeme  case      phono  tir1
40            avoir  pi3S          a    84
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
168      abandonner  ppFP   abɑ̃dɔne     1
299         abattre   inf      abatʁ     4
1388        aboutir  ppMS      abuti     1
1684        abriter  pi3S      abʁit     1
1796        abrutir  ppMS     abʁyti     1
2063       absorber  pi1S     absɔʁb     1
2070       absorber   inf    absɔʁbe     1
2135       abstenir  ii3S    abstənɛ     1
2946       accepter  ai1S    aksɛptɛ     1
2967       accepter  pi3S     aksɛpt     1
3003       accepter  ppMS    aksɛpte     1
3380    accompagner  ai3S   akɔ̃paɲa     1
3406    accompagner   inf   akɔ̃paɲe     2
3440      accomplir  ppFS    akɔ̃pli     1
3443      accomplir   inf   akɔ̃pliʁ     1
4255      accrocher  pi3S      akʁɔʃ     1
4259      accrocher   inf     akʁɔʃe     1
4502     accueillir  ppMS      akəji     1
4718        accuser  pi3P       akyz     1
4748        accuser  ppMS      akyze     1
4823      accélérer  ii3S   aksɛlɛʁɛ     1
4824      accélérer    pP  aksɛlɛʁɑ̃     1
4835      accélérer   inf   aksɛlɛʁe     1
5108        acheter  ii3P      aʃətɛ     1
5119        acheter   inf      aʃəte     3
5136        acheter  ppMS      aʃəte     1
5149        achever  ii3S      aʃəvɛ     1
...             ...   ...        ...   ...
433238   équivaloir  pi3S      ɛkivo     1
433429     érailler  ppMS      ɛʁaje     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    16
434070         être  ii3S        ɛtɛ    83
434153       étaler   inf      ɛtale     1
434302       étaler  ppMP      ɛtale     1
434488         être    pP       ɛtɑ̃     1
434727     éteindre    pP     ɛtɛɲɑ̃     1
434768     éteindre  pi1S       ɛtɛ̃     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     1
435448      étonner  pc1S    ɛtɔnəʁɛ     1
435472      étonner  ppFS      ɛtɔne     1
435484     étouffer  ii3S      ɛtufɛ     1
435497     étouffer  pi1S       ɛtuf     1
435499     étouffer  pI2S       ɛtuf     1
435538     étouffer  ppMS      ɛtufe     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
435780    étrangler  ppMS   ɛtʁɑ̃gle     1
436200      étudier  pI2S      ɛtydi     1
436221      étudier  pi2P     ɛtydje     1
436316         être  ppMS        ɛte    31
436457       évader   inf      ɛvade     1
436484       évader  ppMS      ɛvade     1
437285       éviter    pP     ɛvitɑ̃     1
437301       éviter   inf      ɛvite     3
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    14
437476         être   inf        ɛtʁ    13

[1950 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 19.6 s, total: 1min 33s
Wall time: 31.6 s

nbChunk 14
4200
1917

             lexeme  case     phono  tir1
40            avoir  pi3S         a    89
170      abandonner  ppMP  abɑ̃dɔne     1
299         abattre   inf     abatʁ     1
305         abattre  ppMS     abaty     1
307         abattre  ppFS     abaty     1
1147        aborder   inf    abɔʁde     1
1408        aboutir  pi1S     abuti     1
1684        abriter  pi3S     abʁit     1
1796        abrutir  ppMS    abʁyti     1
1867        abréger  ai3S    abʁɛʒa     1
2946       accepter  ai1S   aksɛptɛ     1
2967       accepter  pi3S    aksɛpt     2
2971       accepter   inf   aksɛpte     2
3406    accompagner   inf  akɔ̃paɲe     1
3571       accorder  ppMS    akɔʁde     1
3968      accoupler  pi3P     akupl     1
4509     accueillir   inf    akəjiʁ     2
4716        accuser  pi3S      akyz     1
4718        accuser  pi3P      akyz     1
4720        accuser   inf     akyze     1
5108        acheter  ii3P     aʃətɛ     1
5119        acheter   inf     aʃəte     1
5136        acheter  ppMS     aʃəte     3
5157        achever   inf     aʃəve     1
5171        achever  ppMS     aʃəve     1
5807       acquérir  ppMS       aki     1
5905       acquérir   inf    akɛʁiʁ     1
6967        admirer  ii1S    admiʁɛ     1
7028       admettre  ppMS      admi     1
7250        adopter   inf    adɔpte     1
...             ...   ...       ...   ...
433004   équilibrer  ii3S  ɛkilibʁɛ     1
433571       ériger  pi3S      ɛʁiʒ     2
433590       ériger   inf     ɛʁiʒe     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ     6
434069         être  ii2S       ɛtɛ     2
434070         être  ii3S       ɛtɛ   100
434147       étaler  pi3S      ɛtal     1
434300       étaler  ppFS     ɛtale     1
434827      étendre  pi1S      ɛtɑ̃     1
435054         être  ii2P      ɛtje     3
435172         être  ii1P     ɛtjɔ̃     4
435232       étirer  ai3S     ɛtiʁa     1
435363      étoiler  ii3S    ɛtwalɛ     1
435438      étonner  pi3S      ɛtɔn     1
435444      étonner   inf     ɛtɔne     1
435450      étonner  pc3S   ɛtɔnəʁɛ     2
435506     étouffer   inf     ɛtufe     2
435726    étrangler  ai3S  ɛtʁɑ̃gla     1
436221      étudier  pi2P    ɛtydje     1
436239      étudier  ppMP    ɛtydje     1
436316         être  ppMS       ɛte    25
436869     éveiller  ppFS     ɛvɛje     1
437284       éviter  ii3S     ɛvitɛ     1
437299       éviter  pi3P      ɛvit     1
437301       éviter   inf     ɛvite     2
437474         être  pi2P        ɛt    14
437476         être   inf       ɛtʁ    11
437492         ôter  ai3S       ɔta     1

[1917 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 19.4 s, total: 1min 33s
Wall time: 33.1 s

nbChunk 15
4200
1947

             lexeme  case      phono  tir1
40            avoir  pi3S          a    98
130      abandonner  pi3P    abɑ̃dɔn     1
158      abandonner  pi1P  abɑ̃dɔnɔ̃     1
164      abandonner  ppMS   abɑ̃dɔne     1
287         abattre  ai3S      abati     1
300         abattre  fi2P     abatʁe     1
1169        aborder  pi1P    abɔʁdɔ̃     1
1668        abriter  ai3S     abʁita     1
1722        abriter  ppMP     abʁite     1
2355         abuser  pi2P      abyze     1
2964       accepter  pi1S     aksɛpt     1
2967       accepter  pi3S     aksɛpt     1
2984       accepter  pi2S     aksɛpt     1
3003       accepter  ppMS    aksɛpte     1
3406    accompagner   inf   akɔ̃paɲe     1
3434    accompagner  ppFS   akɔ̃paɲe     2
4234      accrocher  ii3P     akʁɔʃɛ     1
4255      accrocher  pi3S      akʁɔʃ     1
4473     accueillir  ii3S      akəjɛ     1
4509     accueillir   inf     akəjiʁ     2
4683      accumuler  ppMS    akymyle     1
4693        accuser  ii3S      akyzɛ     1
4716        accuser  pi3S       akyz     2
4748        accuser  ppMS      akyze     1
4783        accéder   inf     aksɛde     1
5119        acheter   inf      aʃəte     3
5136        acheter  ppMS      aʃəte     1
5308        acheter  pi1S       aʃɛt     1
5807       acquérir  ppMS        aki     1
5852      acquitter   inf      akite     1
...             ...   ...        ...   ...
431882     éplucher  fi1P  ɛplyʃəʁɔ̃     1
432519     éprendre  ppMS       ɛpʁi     1
432532     éprouver  ai3S     ɛpʁuva     1
432552     éprouver  pi3S      ɛpʁuv     1
432653      épuiser  pi3S      ɛpɥiz     1
433195   équivaloir  ii3S    ɛkivalɛ     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ     7
434070         être  ii3S        ɛtɛ    70
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434917     éternuer  pi3S     ɛtɛʁny     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     3
435232       étirer  ai3S      ɛtiʁa     1
435422      étonner  ii3S      ɛtɔnɛ     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    13
436629     évanouir  ppFS     ɛvanui     1
436831     éveiller  pi3S       ɛvɛj     1
436835     éveiller   inf      ɛvɛje     1
437284       éviter  ii3S      ɛvitɛ     1
437328       éviter  ppMS      ɛvite     1
437416      évoquer  ii3S      ɛvɔkɛ     1
437417      évoquer    pP     ɛvɔkɑ̃     1
437427      évoquer  pi3S       ɛvɔk     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    29
437492         ôter  ai3S        ɔta     1
437539         ôter  ppMS        ɔte     2

[1947 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 20.2 s, total: 1min 35s
Wall time: 31.9 s

nbChunk 16
4200
1943

             lexeme  case       phono  tir1
40            avoir  pi3S           a    88
132      abandonner   inf    abɑ̃dɔne     3
305         abattre  ppMS       abaty     1
1121        aborder  ai3S      abɔʁda     1
1393        aboutir   inf      abutiʁ     1
1688        abriter   inf      abʁite     1
2581         abîmer   inf       abime     1
2736       accabler   inf      akable     1
2952       accepter    pP    aksɛptɑ̃     1
2980       accepter  pc2P  aksɛptəʁje     1
3005       accepter  ppFS     aksɛpte     1
3382    accompagner  ii3P    akɔ̃paɲɛ     1
3397    accompagner  pi1S     akɔ̃paɲ     2
3400    accompagner  pi3S     akɔ̃paɲ     2
3406    accompagner   inf    akɔ̃paɲe     2
3433    accompagner  ppMS    akɔ̃paɲe     1
3443      accomplir   inf    akɔ̃pliʁ     1
3573       accorder  ppFS      akɔʁde     1
4103       accourir  ai3S       akuʁy     1
4291      accrocher  ppMS      akʁɔʃe     1
4656      accumuler   inf     akymyle     1
4748        accuser  ppMS       akyze     1
5119        acheter   inf       aʃəte     3
5136        acheter  ppMS       aʃəte     2
5149        achever  ii3S       aʃəvɛ     1
6414        adapter   inf      adapte     1
6967        admirer  ii1S      admiʁɛ     1
6996        admirer   inf      admiʁe     1
7250        adopter   inf      adɔpte     1
7283        adopter  ppMS      adɔpte     2
...             ...   ...         ...   ...
430482     épanouir  ppFS      ɛpanui     1
430646   éparpiller  ppMP    ɛpaʁpije     1
430688       épater   inf       ɛpate     1
430871       épeler  pi2P       ɛpəle     1
432160      épouser   inf       ɛpuze     1
432302      épouser  ppMS       ɛpuze     1
432535     éprouver  ii1S      ɛpʁuvɛ     1
432537     éprouver  ii3S      ɛpʁuvɛ     2
433026   équilibrer   inf    ɛkilibʁe     1
433325      érafler   inf      ɛʁafle     1
433912      établir  ppMS      ɛtabli     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    70
434299       étaler  ppMS       ɛtale     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434768     éteindre  pi1S        ɛtɛ̃     1
434821      étendre   inf      ɛtɑ̃dʁ     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     1
435296       étirer  ppMP       ɛtiʁe     1
435486     étouffer    pP      ɛtufɑ̃     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436316         être  ppMS         ɛte    30
436500      évaluer    pP     ɛvalyɑ̃     1
436867     éveiller  ppMS       ɛvɛje     2
437314       éviter  pi2S        ɛvit     1
437458      évoquer  ppMS       ɛvɔke     1
437474         être  pi2P          ɛt    14
437476         être   inf         ɛtʁ    30

[1943 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 18.4 s, total: 1min 34s
Wall time: 38.9 s

nbChunk 17
4200
1942

             lexeme  case        phono  tir1
40            avoir  pi3S            a    79
128      abandonner  pi3S      abɑ̃dɔn     1
132      abandonner   inf     abɑ̃dɔne     1
299         abattre   inf        abatʁ     1
305         abattre  ppMS        abaty     1
1110        abonner  ppMS        abɔne     1
1688        abriter   inf       abʁite     1
2051       absorber  ii3S      absɔʁbɛ     1
2066       absorber  pi3S       absɔʁb     1
2070       absorber   inf      absɔʁbe     1
2100       absorber  ppMS      absɔʁbe     1
2967       accepter  pi3S       aksɛpt     1
2971       accepter   inf      aksɛpte     1
2977       accepter  pc3S    aksɛptəʁɛ     1
3003       accepter  ppMS      aksɛpte     2
3349     accommoder   inf      akɔmɔde     1
3397    accompagner  pi1S      akɔ̃paɲ     1
3400    accompagner  pi3S      akɔ̃paɲ     1
3436    accompagner  ppMP     akɔ̃paɲe     1
3484      accomplir  ii1P  akɔ̃plisjɔ̃     1
3536       accorder   inf       akɔʁde     2
3583       accorder  ppMP       akɔʁde     1
4237      accrocher  ii3S       akʁɔʃɛ     1
4482     accueillir  pi3S         akœj     1
4686      accumuler  ppMP      akymyle     1
4693        accuser  ii3S        akyzɛ     1
4748        accuser  ppMS        akyze     1
5119        acheter   inf        aʃəte     1
5136        acheter  ppMS        aʃəte     1
5311        acheter  pi3S         aʃɛt     1
...             ...   ...          ...   ...
430558     épargner  pi3S        ɛpaʁɲ     1
431971      éponger  pi3S        ɛpɔ̃ʒ     1
432303      épouser  ppFS        ɛpuze     1
432537     éprouver  ii3S       ɛpʁuvɛ     1
432586     éprouver  ppMS       ɛpʁuve     1
433300    éradiquer  ppFS      ɛʁadike     1
433922      établir   inf      ɛtabliʁ     1
434048         être  ii3P          ɛtɛ     2
434068         être  ii1S          ɛtɛ    14
434069         être  ii2S          ɛtɛ     1
434070         être  ii3S          ɛtɛ    72
434151       étaler  pi3P         ɛtal     1
434300       étaler  ppFS        ɛtale     1
434722       étayer  ppMP        ɛtɛje     1
434772     éteindre  ppMS         ɛtɛ̃     1
434811      étendre  ai3S       ɛtɑ̃di     1
434821      étendre   inf       ɛtɑ̃dʁ     1
435054         être  ii2P         ɛtje     1
435172         être  ii1P        ɛtjɔ̃     2
435240       étirer  ii3P        ɛtiʁɛ     1
435497     étouffer  pi1S         ɛtuf     2
436201      étudier  pi3S        ɛtydi     1
436205      étudier   inf       ɛtydje     1
436316         être  ppMS          ɛte    28
436544      évaluer  is3S       ɛvalya     1
437285       éviter    pP       ɛvitɑ̃     1
437363      évoluer  pi3S        ɛvɔly     1
437367      évoluer   inf       ɛvɔlye     1
437474         être  pi2P           ɛt    12
437476         être   inf          ɛtʁ    21

[1942 rows x 4 columns]

0
CPU times: user 1min 7s, sys: 15.7 s, total: 1min 23s
Wall time: 33.9 s

nbChunk 18
4200
1959

             lexeme  case      phono  tir1
40            avoir  pi3S          a    91
101        abaisser  ppMS      abɛse     1
132      abandonner   inf   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
170      abandonner  ppMP   abɑ̃dɔne     1
1946       absenter  pi3S     absɑ̃t     1
2070       absorber   inf    absɔʁbe     1
2322         abuser  ii1S      abyzɛ     1
2975       accepter  pc1S  aksɛptəʁɛ     1
2979       accepter  fi2P  aksɛptəʁe     1
3003       accepter  ppMS    aksɛpte     1
3096       acclamer  ii3S     aklamɛ     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     2
3534       accorder  pi3P      akɔʁd     1
3637       accoster  ii3P     akɔstɛ     1
3827      accoucher   inf      akuʃe     1
4252      accrocher  pi1S      akʁɔʃ     1
4280      accrocher  pi2P     akʁɔʃe     1
4519     accueillir  ai3S      akəji     1
4750        accuser  ppFS      akyze     1
5119        acheter   inf      aʃəte     4
5136        acheter  ppMS      aʃəte     3
5308        acheter  pi1S       aʃɛt     1
5329        achever  pi1S       aʃɛv     1
5332        achever  pi3S       aʃɛv     1
6891       admettre   inf     admɛtʁ     2
7012        admirer  pi2P     admiʁe     1
7312         adorer  pi3S       adɔʁ     2
...             ...   ...        ...   ...
429694      énerver  pi3S      ɛnɛʁv     1
431348    épiloguer  ai3P   ɛpilɔgɛʁ     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
432552     éprouver  pi3S      ɛpʁuv     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ    14
434070         être  ii3S        ɛtɛ    74
434811      étendre  ai3S     ɛtɑ̃di     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     1
435422      étonner  ii3S      ɛtɔnɛ     1
435435      étonner  pi1S       ɛtɔn     1
435438      étonner  pi3S       ɛtɔn     1
435471      étonner  ppMS      ɛtɔne     1
435497     étouffer  pi1S       ɛtuf     1
435540     étouffer  ppFS      ɛtufe     1
436227      étudier  pi1P    ɛtydjɔ̃     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    23
436457       évader   inf      ɛvade     1
436679     évanouir  pi3S     ɛvanui     1
436835     éveiller   inf      ɛvɛje     1
437284       éviter  ii3S      ɛvitɛ     1
437301       éviter   inf      ɛvite     1
437413      évoquer  ii3P      ɛvɔkɛ     1
437416      évoquer  ii3S      ɛvɔkɛ     1
437474         être  pi2P         ɛt    18
437476         être   inf        ɛtʁ    19

[1959 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 19.8 s, total: 1min 35s
Wall time: 31.8 s

nbChunk 19
4200
1915

             lexeme  case        phono  tir1
40            avoir  pi3S            a    92
130      abandonner  pi3P      abɑ̃dɔn     1
132      abandonner   inf     abɑ̃dɔne     1
166      abandonner  ppFS     abɑ̃dɔne     1
250         abattre  pi1S          aba     1
305         abattre  ppMS        abaty     1
1174        aborder  ai3P      abɔʁdɛʁ     1
1801        abrutir   inf      abʁytiʁ     1
1859        abréger  pi3S        abʁɛʒ     1
2051       absorber  ii3S      absɔʁbɛ     1
2219       abstenir  fi1P  abstjɛ̃dʁɔ̃     1
2371         abuser  ppMS        abyze     1
3003       accepter  ppMS      aksɛpte     2
3316        accoler  ppMP        akɔle     1
3400    accompagner  pi3S      akɔ̃paɲ     1
3433    accompagner  ppMS     akɔ̃paɲe     1
3818      accoucher  pi1S         akuʃ     1
3913       accouder  ppMS        akude     1
3914       accouder  ppFS        akude     1
4238      accrocher    pP      akʁɔʃɑ̃     1
4291      accrocher  ppMS       akʁɔʃe     2
4502     accueillir  ppMS        akəji     1
4656      accumuler   inf      akymyle     1
4812      accélérer  pi3S      aksɛlɛʁ     1
4998       acharner    pP      aʃaʁnɑ̃     1
5119        acheter   inf        aʃəte     4
5136        acheter  ppMS        aʃəte     4
5171        achever  ppMS        aʃəve     1
6539        adhérer  ii3S        adɛʁɛ     1
6811        adjurer    pP      adʒyʁɑ̃     1
...             ...   ...          ...   ...
433922      établir   inf      ɛtabliʁ     1
433939      établir  pi1S       ɛtabli     1
434048         être  ii3P          ɛtɛ     4
434068         être  ii1S          ɛtɛ    11
434070         être  ii3S          ɛtɛ    81
434723     éteindre  ii3P        ɛtɛɲɛ     1
434747     éteindre  ai3S        ɛtɛɲi     1
434768     éteindre  pi1S         ɛtɛ̃     1
434831      étendre  ppMS       ɛtɑ̃dy     1
435054         être  ii2P         ɛtje     1
435172         être  ii1P        ɛtjɔ̃     2
435260       étirer   inf        ɛtiʁe     1
435460      étonner  pi2P        ɛtɔne     1
435746    étrangler  pi3P      ɛtʁɑ̃gl     1
435780    étrangler  ppMS     ɛtʁɑ̃gle     1
436051     étriquer  ppMS       ɛtʁike     1
436201      étudier  pi3S        ɛtydi     1
436316         être  ppMS          ɛte    19
436484       évader  ppMS        ɛvade     1
437285       éviter    pP       ɛvitɑ̃     1
437292       éviter  pi1S         ɛvit     1
437295       éviter  pi3S         ɛvit     1
437301       éviter   inf        ɛvite     2
437302       éviter  fi3S      ɛvitəʁa     1
437365      évoluer  pi3P        ɛvɔly     1
437413      évoquer  ii3P        ɛvɔkɛ     1
437417      évoquer    pP       ɛvɔkɑ̃     1
437450      évoquer  ii1P      ɛvɔkjɔ̃     1
437474         être  pi2P           ɛt    11
437476         être   inf          ɛtʁ    12

[1915 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 20.1 s, total: 1min 34s
Wall time: 31.9 s

nbChunk 20
4200
1909

             lexeme  case      phono  tir1
40            avoir  pi3S          a    74
132      abandonner   inf   abɑ̃dɔne     1
307         abattre  ppFS      abaty     1
1116        abonner  ppMP      abɔne     1
1388        aboutir  ppMS      abuti     1
1415        aboutir  ii3S    abutisɛ     1
1710        abriter  pi1P    abʁitɔ̃     1
2614         abîmer  ppFP      abime     1
2971       accepter   inf    aksɛpte     1
2989       accepter  pi2P    aksɛpte     1
2994       accepter  ii1P  aksɛptjɔ̃     1
2997       accepter  pi1P   aksɛptɔ̃     1
3003       accepter  ppMS    aksɛpte     2
3380    accompagner  ai3S   akɔ̃paɲa     2
3429    accompagner  ai1P  akɔ̃paɲam     1
3443      accomplir   inf   akɔ̃pliʁ     1
3458      accomplir  ppMP    akɔ̃pli     1
3571       accorder  ppMS     akɔʁde     1
4212     accoutumer  ppFS    akutyme     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4292      accrocher  ppFS     akʁɔʃe     1
4491     accueillir  pc3S    akəjəʁɛ     1
4631        acculer  ppMP      akyle     1
4684      accumuler  ppFS    akymyle     1
4720        accuser   inf      akyze     1
4771        accéder  ii3S     aksɛdɛ     1
4824      accélérer    pP  aksɛlɛʁɑ̃     1
5041       acharner  ppMS     aʃaʁne     1
5042       acharner  ppFS     aʃaʁne     1
5119        acheter   inf      aʃəte     2
...             ...   ...        ...   ...
432369   épouvanter  ii3P   ɛpuvɑ̃tɛ     1
432535     éprouver  ii1S     ɛpʁuvɛ     1
432556     éprouver   inf     ɛpʁuve     1
432562     éprouver  pc3S   ɛpʁuvəʁɛ     1
432586     éprouver  ppMS     ɛpʁuve     1
433102      équiper  pi1S       ɛkip     1
433238   équivaloir  pi3S      ɛkivo     1
433923      établir  fi3S   ɛtabliʁa     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    16
434070         être  ii3S        ɛtɛ    67
434072       étaler  ai3S      ɛtala     1
434488         être    pP       ɛtɑ̃     1
434770     éteindre  pi2S       ɛtɛ̃     1
434772     éteindre  ppMS       ɛtɛ̃     1
435054         être  ii2P       ɛtje     3
435251       étirer  pi1S       ɛtiʁ     1
435417      étonner  ai3S      ɛtɔna     1
435544     étouffer  ppMP      ɛtufe     1
435794    étreindre  ii3S     ɛtʁɛɲɛ     1
436201      étudier  pi3S      ɛtydi     1
436205      étudier   inf     ɛtydje     1
436239      étudier  ppMP     ɛtydje     1
436316         être  ppMS        ɛte    27
436835     éveiller   inf      ɛvɛje     1
437295       éviter  pi3S       ɛvit     1
437301       éviter   inf      ɛvite     2
437317       éviter  pi2P      ɛvite     2
437474         être  pi2P         ɛt     9
437476         être   inf        ɛtʁ    24

[1909 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 20.9 s, total: 1min 37s
Wall time: 32.2 s

nbChunk 21
4200
1951

             lexeme  case      phono  tir1
40            avoir  pi3S          a    87
73         abaisser   inf      abɛse     1
164      abandonner  ppMS   abɑ̃dɔne     1
170      abandonner  ppMP   abɑ̃dɔne     1
1153        aborder  pc3S   abɔʁdəʁɛ     1
1688        abriter   inf     abʁite     1
1716        abriter  ppMS     abʁite     1
1861        abréger  pi3P      abʁɛʒ     1
2610         abîmer  ppMS      abime     1
2888      accentuer    pP  aksɑ̃tyɑ̃     1
2939       accepter  ai3S    aksɛpta     1
2971       accepter   inf    aksɛpte     1
2979       accepter  fi2P  aksɛptəʁe     1
3003       accepter  ppMS    aksɛpte     1
3005       accepter  ppFS    aksɛpte     1
3324     accommoder    pP   akɔmɔdɑ̃     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3419    accompagner  pi2S    akɔ̃paɲ     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
3536       accorder   inf     akɔʁde     1
3573       accorder  ppFS     akɔʁde     1
4235      accrocher  ii1S     akʁɔʃɛ     1
4255      accrocher  pi3S      akʁɔʃ     1
4259      accrocher   inf     akʁɔʃe     1
4502     accueillir  ppMS      akəji     1
4683      accumuler  ppMS    akymyle     1
4783        accéder   inf     aksɛde     1
5041       acharner  ppMS     aʃaʁne     1
...             ...   ...        ...   ...
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    11
434070         être  ii3S        ɛtɛ    94
434131       étaler  ii3P      ɛtalɛ     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434811      étendre  ai3S     ɛtɑ̃di     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     1
435232       étirer  ai3S      ɛtiʁa     1
435243       étirer  ii3S      ɛtiʁɛ     1
435244       étirer    pP     ɛtiʁɑ̃     1
435435      étonner  pi1S       ɛtɔn     1
435438      étonner  pi3S       ɛtɔn     1
435444      étonner   inf      ɛtɔne     1
435471      étonner  ppMS      ɛtɔne     1
435538     étouffer  ppMS      ɛtufe     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    25
436457       évader   inf      ɛvade     1
436835     éveiller   inf      ɛvɛje     1
437046     évertuer  ii3P    ɛvɛʁtyɛ     1
437285       éviter    pP     ɛvitɑ̃     1
437301       éviter   inf      ɛvite     3
437328       éviter  ppMS      ɛvite     1
437367      évoluer   inf     ɛvɔlye     1
437416      évoquer  ii3S      ɛvɔkɛ     1
437424      évoquer  pi1S       ɛvɔk     1
437474         être  pi2P         ɛt    13
437476         être   inf        ɛtʁ    21
437497         ôter  ii3S        ɔtɛ     1

[1951 rows x 4 columns]

0
CPU times: user 1min 10s, sys: 20.6 s, total: 1min 31s
Wall time: 31.9 s

nbChunk 22
4200
1937

             lexeme  case      phono  tir1
40            avoir  pi3S          a    72
574        abhorrer  ii3S      abɔʁɛ     1
887          abolir  ppMS      abɔli     1
977         abonder  pi1S      abɔ̃d     1
1132        aborder  ii3S     abɔʁdɛ     1
1393        aboutir   inf     abutiʁ     1
2042       absorber  ai3S    absɔʁba     1
2339         abuser   inf      abyze     1
2610         abîmer  ppMS      abime     1
2971       accepter   inf    aksɛpte     2
3406    accompagner   inf   akɔ̃paɲe     2
3440      accomplir  ppFS    akɔ̃pli     1
3443      accomplir   inf   akɔ̃pliʁ     1
3530       accorder  pi3S      akɔʁd     1
3545       accorder  pc2P  akɔʁdəʁje     1
3884       accouder   inf      akude     1
4255      accrocher  pi3S      akʁɔʃ     1
4259      accrocher   inf     akʁɔʃe     1
4281      accrocher  ii2P    akʁɔʃje     1
4503     accueillir  ppFS      akəji     1
4509     accueillir   inf     akəjiʁ     1
5119        acheter   inf      aʃəte     3
5136        acheter  ppMS      aʃəte     1
5137        acheter  ppFS      aʃəte     1
5149        achever  ii3S      aʃəvɛ     1
6446        adapter  ppMP     adapte     1
7250        adopter   inf     adɔpte     1
7294         adorer  ii3P      adɔʁɛ     1
7309         adorer  pi1S       adɔʁ     1
7966      affaiblir   inf    afɛbliʁ     1
...             ...   ...        ...   ...
432693      épuiser  ppFP     ɛpɥize     1
433590       ériger   inf      ɛʁiʒe     1
433922      établir   inf    ɛtabliʁ     1
433969      établir  pi3S     ɛtabli     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    11
434070         être  ii3S        ɛtɛ    69
434134       étaler  ii3S      ɛtalɛ     2
434300       étaler  ppFS      ɛtale     1
434301       étaler  ppFP      ɛtale     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434768     éteindre  pi1S       ɛtɛ̃     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     3
435172         être  ii1P      ɛtjɔ̃     1
435294       étirer  ppFS      ɛtiʁe     1
435422      étonner  ii3S      ɛtɔnɛ     1
435457      étonner  pi2S       ɛtɔn     1
435471      étonner  ppMS      ɛtɔne     1
435475     étouffer  ai3S      ɛtufa     1
435484     étouffer  ii3S      ɛtufɛ     1
435504     étouffer  pi3P       ɛtuf     1
435865     étrenner   inf     ɛtʁɛne     1
436233      étudier  ppMS     ɛtydje     2
436316         être  ppMS        ɛte    25
437301       éviter   inf      ɛvite     1
437416      évoquer  ii3S      ɛvɔkɛ     1
437474         être  pi2P         ɛt    19
437476         être   inf        ɛtʁ    23
437512         ôter   inf        ɔte     1

[1937 rows x 4 columns]

0
CPU times: user 1min 11s, sys: 20.9 s, total: 1min 32s
Wall time: 33.3 s

nbChunk 23
4200
1982

             lexeme  case      phono  tir1
40            avoir  pi3S          a    85
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
574        abhorrer  ii3S      abɔʁɛ     1
1421        aboutir  ps3S     abutis     1
2070       absorber   inf    absɔʁbe     1
2581         abîmer   inf      abime     1
2964       accepter  pi1S     aksɛpt     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     2
2975       accepter  pc1S  aksɛptəʁɛ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3527       accorder  pi1S      akɔʁd     1
3530       accorder  pi3S      akɔʁd     1
4320      accroupir  ppMS     akʁupi     1
4321      accroupir  ppFS     akʁupi     1
4502     accueillir  ppMS      akəji     1
4720        accuser   inf      akyze     1
4783        accéder   inf     aksɛde     1
4809      accélérer  pi1S    aksɛlɛʁ     1
4835      accélérer   inf   aksɛlɛʁe     1
4862      accélérer  ppMS   aksɛlɛʁe     1
5041       acharner  ppMS     aʃaʁne     1
5119        acheter   inf      aʃəte     2
5125        acheter  pi2P      aʃəte     1
5136        acheter  ppMS      aʃəte     1
5313        acheter  pi3P       aʃɛt     1
5320        acheter  pc3S    aʃɛtəʁɛ     1
...             ...   ...        ...   ...
432145      épouser    pP     ɛpuzɑ̃     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
432640      épuiser    pP    ɛpɥizɑ̃     1
432689      épuiser  ppMS     ɛpɥize     1
433922      établir   inf    ɛtabliʁ     1
433928      établir  pc3S   ɛtabliʁɛ     1
434048         être  ii3P        ɛtɛ     1
434068         être  ii1S        ɛtɛ     9
434070         être  ii3S        ɛtɛ    73
434153       étaler   inf      ɛtale     1
434488         être    pP       ɛtɑ̃     2
434729     éteindre  ps3S       ɛtɛɲ     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
435054         être  ii2P       ɛtje     6
435172         être  ii1P      ɛtjɔ̃     4
435244       étirer    pP     ɛtiʁɑ̃     1
435506     étouffer   inf      ɛtufe     1
435731    étrangler  ii3S   ɛtʁɑ̃glɛ     1
436316         être  ppMS        ɛte    23
436547      évaluer  ppMS     ɛvalye     1
436640     évanouir  ai3P    ɛvanuiʁ     1
437064     évertuer   inf    ɛvɛʁtye     1
437244    éviscérer   inf    ɛvisɛʁe     1
437301       éviter   inf      ɛvite     1
437329       éviter  ppFS      ɛvite     1
437416      évoquer  ii3S      ɛvɔkɛ     1
437417      évoquer    pP     ɛvɔkɑ̃     2
437474         être  pi2P         ɛt     8
437476         être   inf        ɛtʁ    30
437539         ôter  ppMS        ɔte     1

[1982 rows x 4 columns]

0
CPU times: user 1min 8s, sys: 21.5 s, total: 1min 29s
Wall time: 33.3 s

nbChunk 24
4200
1964

             lexeme  case      phono  tir1
40            avoir  pi3S          a   100
132      abandonner   inf   abɑ̃dɔne     3
164      abandonner  ppMS   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
1175        aborder  ppMS     abɔʁde     1
1565       abreuver  pi3S      abʁœv     1
1681        abriter  pi1S      abʁit     1
2972       accepter  fi3S  aksɛptəʁa     1
3123       acclamer  pc3S   aklaməʁɛ     1
3319     accommoder  ii3P    akɔmɔdɛ     1
3406    accompagner   inf   akɔ̃paɲe     1
3436    accompagner  ppMP   akɔ̃paɲe     1
3438      accomplir  ppMS    akɔ̃pli     1
3443      accomplir   inf   akɔ̃pliʁ     1
3821      accoucher  pi3S       akuʃ     1
3862       accouder  ai3S      akuda     1
4080       accourir  pc3S     akuʁʁɛ     1
4180     accoutumer  pi3P     akutym     1
4259      accrocher   inf     akʁɔʃe     1
4292      accrocher  ppFS     akʁɔʃe     1
4294      accrocher  ppMP     akʁɔʃe     1
4387      accroître  ppMS       akʁy     1
4473     accueillir  ii3S      akəjɛ     1
4547        acculer   inf      akyle     1
4713        accuser  pi1S       akyz     1
4864      accélérer  ppFS   aksɛlɛʁe     1
5111        acheter  ii3S      aʃətɛ     1
5119        acheter   inf      aʃəte     3
5137        acheter  ppFS      aʃəte     1
5157        achever   inf      aʃəve     1
...             ...   ...        ...   ...
433912      établir  ppMS     ɛtabli     1
433922      établir   inf    ɛtabliʁ     1
433954      établir  pi3P    ɛtablis     1
434048         être  ii3P        ɛtɛ     6
434068         être  ii1S        ɛtɛ    20
434070         être  ii3S        ɛtɛ    67
434134       étaler  ii3S      ɛtalɛ     1
434726     éteindre  ii3S      ɛtɛɲɛ     1
434734     éteindre  pi2P      ɛtɛɲe     2
434773     éteindre  pi3S       ɛtɛ̃     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     2
435293       étirer  ppMS      ɛtiʁe     1
435417      étonner  ai3S      ɛtɔna     2
435538     étouffer  ppMS      ɛtufe     1
435666     étourdir  pc3S   ɛtuʁdiʁɛ     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    25
436408      évacuer  pc3S    ɛvakyʁɛ     1
436520      évaluer   inf     ɛvalye     1
436867     éveiller  ppMS      ɛvɛje     1
437301       éviter   inf      ɛvite     2
437307       éviter  pc3S    ɛvitəʁɛ     1
437317       éviter  pi2P      ɛvite     1
437328       éviter  ppMS      ɛvite     1
437414      évoquer  ii1S      ɛvɔkɛ     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    14

[1964 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 20.1 s, total: 1min 33s
Wall time: 32.3 s

nbChunk 25
4200
1922

             lexeme  case      phono  tir1
40            avoir  pi3S          a    76
164      abandonner  ppMS   abɑ̃dɔne     1
955         abonder  ii3P     abɔ̃dɛ     1
1140        aborder  pi1S      abɔʁd     2
1393        aboutir   inf     abutiʁ     2
2939       accepter  ai3S    aksɛpta     1
2952       accepter    pP   aksɛptɑ̃     1
2977       accepter  pc3S  aksɛptəʁɛ     1
2984       accepter  pi2S     aksɛpt     1
3003       accepter  ppMS    aksɛpte     1
3009       accepter  ppMP    aksɛpte     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3536       accorder   inf     akɔʁde     1
4009       accourir  ii3S      akuʁɛ     1
4252      accrocher  pi1S      akʁɔʃ     1
4255      accrocher  pi3S      akʁɔʃ     1
4386      accroître  fi3P  akʁwatʁɔ̃     1
4635      accumuler  ii1S    akymylɛ     1
4849      accélérer  pi2P   aksɛlɛʁe     1
5136        acheter  ppMS      aʃəte     1
5169        achever  ai3P     aʃəvɛʁ     1
5171        achever  ppMS      aʃəve     1
5311        acheter  pi3S       aʃɛt     1
5807       acquérir  ppMS        aki     1
6865       admettre  pi2S       admɛ     1
6866       admettre  ii3P     admɛtɛ     1
6891       admettre   inf     admɛtʁ     2
6991        admirer  pi3S      admiʁ     1
...             ...   ...        ...   ...
432156      épouser  pi3S       ɛpuz     1
432303      épouser  ppFS      ɛpuze     1
432535     éprouver  ii1S     ɛpʁuvɛ     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
432586     éprouver  ppMS     ɛpʁuve     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    10
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    67
434147       étaler  pi3S       ɛtal     1
434722       étayer  ppMP      ɛtɛje     1
434772     éteindre  ppMS       ɛtɛ̃     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434848    éterniser  ai3S   ɛtɛʁniza     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     1
435422      étonner  ii3S      ɛtɔnɛ     1
435438      étonner  pi3S       ɛtɔn     2
435748    étrangler   inf   ɛtʁɑ̃gle     2
436205      étudier   inf     ɛtydje     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    23
436457       évader   inf      ɛvade     1
436632     évanouir   inf    ɛvanuiʁ     1
436828     éveiller  pi1S       ɛvɛj     1
437301       éviter   inf      ɛvite     1
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    20
437497         ôter  ii3S        ɔtɛ     1

[1922 rows x 4 columns]

0
CPU times: user 1min 11s, sys: 21.5 s, total: 1min 33s
Wall time: 33.3 s

nbChunk 26
4200
1956

             lexeme  case        phono  tir1
40            avoir  pi3S            a    88
108      abandonner  ai3S     abɑ̃dɔna     1
128      abandonner  pi3S      abɑ̃dɔn     1
143      abandonner  fi1P  abɑ̃dɔnəʁɔ̃     1
170      abandonner  ppMP     abɑ̃dɔne     2
243         abattre  pi3S          aba     1
1178        aborder  ppMP       abɔʁde     1
1260       aboucher   inf        abuʃe     1
1688        abriter   inf       abʁite     1
2104       absorber  ppFP      absɔʁbe     1
2967       accepter  pi3S       aksɛpt     3
2984       accepter  pi2S       aksɛpt     1
3003       accepter  ppMS      aksɛpte     1
3406    accompagner   inf     akɔ̃paɲe     2
3412    accompagner  pc3S   akɔ̃paɲəʁɛ     1
3419    accompagner  pi2S      akɔ̃paɲ     1
3434    accompagner  ppFS     akɔ̃paɲe     1
3438      accomplir  ppMS      akɔ̃pli     1
3443      accomplir   inf     akɔ̃pliʁ     1
3540       accorder  pc1S     akɔʁdəʁɛ     1
4255      accrocher  pi3S        akʁɔʃ     2
4259      accrocher   inf       akʁɔʃe     1
4321      accroupir  ppFS       akʁupi     2
4381      accroître   inf      akʁwatʁ     1
4473     accueillir  ii3S        akəjɛ     1
4482     accueillir  pi3S         akœj     1
4502     accueillir  ppMS        akəji     1
4509     accueillir   inf       akəjiʁ     1
4688        accuser  ai3S        akyza     1
4783        accéder   inf       aksɛde     1
...             ...   ...          ...   ...
429335     émouvoir  ii1S        ɛmuvɛ     1
429698      énerver  pi3P        ɛnɛʁv     1
430028     énumérer  ii3S      ɛnymɛʁɛ     1
430592     épargner  ppFP       ɛpaʁɲe     1
431167        épier   inf         ɛpje     1
432160      épouser   inf        ɛpuze     1
432539     éprouver    pP      ɛpʁuvɑ̃     1
432556     éprouver   inf       ɛpʁuve     1
433922      établir   inf      ɛtabliʁ     1
433944      établir  ii1S     ɛtablisɛ     1
434048         être  ii3P          ɛtɛ     2
434068         être  ii1S          ɛtɛ    13
434069         être  ii2S          ɛtɛ     1
434070         être  ii3S          ɛtɛ    74
434729     éteindre  ps3S         ɛtɛɲ     1
434789      étendre    pP      ɛtɑ̃dɑ̃     1
435054         être  ii2P         ɛtje     1
435172         être  ii1P        ɛtjɔ̃     2
435295       étirer  ppFP        ɛtiʁe     1
435450      étonner  pc3S      ɛtɔnəʁɛ     1
435506     étouffer   inf        ɛtufe     1
435660     étourdir   inf      ɛtuʁdiʁ     1
435828    étreindre   inf      ɛtʁɛ̃dʁ     1
436316         être  ppMS          ɛte    27
436402      évacuer   inf       ɛvakye     2
436711     évaporer   inf      ɛvapɔʁe     1
436820     éveiller  ii3S        ɛvɛjɛ     1
437301       éviter   inf        ɛvite     3
437474         être  pi2P           ɛt    12
437476         être   inf          ɛtʁ    24

[1956 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.2 s, total: 1min 35s
Wall time: 33.4 s

nbChunk 27
4200
1937

             lexeme  case     phono  tir1
40            avoir  pi3S         a   112
113      abandonner  ii3S  abɑ̃dɔnɛ     1
130      abandonner  pi3P   abɑ̃dɔn     2
145      abandonner  pi2S   abɑ̃dɔn     1
164      abandonner  ppMS  abɑ̃dɔne     1
955         abonder  ii3P    abɔ̃dɛ     1
1388        aboutir  ppMS     abuti     1
1688        abriter   inf    abʁite     1
2952       accepter    pP  aksɛptɑ̃     1
2964       accepter  pi1S    aksɛpt     1
2967       accepter  pi3S    aksɛpt     2
2971       accepter   inf   aksɛpte     1
2989       accepter  pi2P   aksɛpte     1
3005       accepter  ppFS   aksɛpte     1
3422    accompagner  pi2P  akɔ̃paɲe     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3519       accorder  ii3S    akɔʁdɛ     1
3527       accorder  pi1S     akɔʁd     1
3571       accorder  ppMS    akɔʁde     1
4255      accrocher  pi3S     akʁɔʃ     2
4291      accrocher  ppMS    akʁɔʃe     1
4294      accrocher  ppMP    akʁɔʃe     1
4462     accréditer  ppFS  akʁɛdite     1
4509     accueillir   inf    akəjiʁ     2
4997       acharner  ii3S    aʃaʁnɛ     1
5136        acheter  ppMS     aʃəte     3
5137        acheter  ppFS     aʃəte     2
5758     acquiescer  pi3S     akjɛs     1
6414        adapter   inf    adapte     1
6891       admettre   inf    admɛtʁ     2
...             ...   ...       ...   ...
432160      épouser   inf     ɛpuze     2
432491     éprendre   inf   ɛpʁɑ̃dʁ     1
432537     éprouver  ii3S    ɛpʁuvɛ     2
432552     éprouver  pi3S     ɛpʁuv     2
432689      épuiser  ppMS    ɛpɥize     1
433174      équiper  ppMP     ɛkipe     1
433912      établir  ppMS    ɛtabli     1
433922      établir   inf   ɛtabliʁ     1
433995       étager    pP    ɛtaʒɑ̃     1
434048         être  ii3P       ɛtɛ     1
434068         être  ii1S       ɛtɛ     7
434069         être  ii2S       ɛtɛ     2
434070         être  ii3S       ɛtɛ    78
434132       étaler  ii1S     ɛtalɛ     1
434770     éteindre  pi2S      ɛtɛ̃     1
434772     éteindre  ppMS      ɛtɛ̃     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     3
435243       étirer  ii3S     ɛtiʁɛ     1
435438      étonner  pi3S      ɛtɔn     1
435450      étonner  pc3S   ɛtɔnəʁɛ     1
435456      étonner  fi3P  ɛtɔnəʁɔ̃     1
435471      étonner  ppMS     ɛtɔne     1
436316         être  ppMS       ɛte    20
436402      évacuer   inf    ɛvakye     1
436835     éveiller   inf     ɛvɛje     1
437367      évoluer   inf    ɛvɔlye     1
437474         être  pi2P        ɛt    14
437476         être   inf       ɛtʁ    18
437512         ôter   inf       ɔte     1

[1937 rows x 4 columns]

0
CPU times: user 1min 5s, sys: 22 s, total: 1min 27s
Wall time: 33.9 s

nbChunk 28
4200
1954

             lexeme  case       phono  tir1
40            avoir  pi3S           a    88
114      abandonner    pP   abɑ̃dɔnɑ̃     1
132      abandonner   inf    abɑ̃dɔne     1
887          abolir  ppMS       abɔli     1
1716        abriter  ppMS      abʁite     1
1950       absenter   inf     absɑ̃te     1
2736       accabler   inf      akable     1
2971       accepter   inf     aksɛpte     3
3003       accepter  ppMS     aksɛpte     2
3005       accepter  ppFS     aksɛpte     1
3571       accorder  ppMS      akɔʁde     1
4063       accourir  pi3P        akuʁ     1
4210     accoutumer  ppMS     akutyme     1
4294      accrocher  ppMP      akʁɔʃe     1
4672      accumuler  pi2P     akymyle     1
4748        accuser  ppMS       akyze     1
5119        acheter   inf       aʃəte     3
5136        acheter  ppMS       aʃəte     1
5316        acheter  fi1S     aʃɛtəʁɛ     1
6072        activer   inf      aktive     1
6825        adjurer   inf      adʒyʁe     1
6928    administrer   inf  administʁe     1
6996        admirer   inf      admiʁe     1
7246        adopter  pi3S       adɔpt     1
7250        adopter   inf      adɔpte     1
7309         adorer  pi1S        adɔʁ     1
7312         adorer  pi3S        adɔʁ     2
7320         adorer  pc1S     adɔʁəʁɛ     1
7518       adresser  ai3S      adʁɛsa     1
7541       adresser  fi1S    adʁɛsəʁɛ     1
...             ...   ...         ...   ...
432586     éprouver  ppMS      ɛpʁuve     1
432588     éprouver  ppFS      ɛpʁuve     1
432691      épuiser  ppFS      ɛpɥize     1
433912      établir  ppMS      ɛtabli     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ     6
434070         être  ii3S         ɛtɛ    79
434072       étaler  ai3S       ɛtala     1
434722       étayer  ppMP       ɛtɛje     1
434789      étendre    pP     ɛtɑ̃dɑ̃     1
434821      étendre   inf      ɛtɑ̃dʁ     1
435054         être  ii2P        ɛtje     2
435059    étinceler  ii3P    ɛtɛ̃səlɛ     1
435074    étinceler   inf    ɛtɛ̃səle     1
435172         être  ii1P       ɛtjɔ̃     3
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435534     étouffer  is3S       ɛtufa     1
435746    étrangler  pi3P     ɛtʁɑ̃gl     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436209      étudier  pc1S     ɛtydiʁɛ     1
436218      étudier  pi2S       ɛtydi     1
436316         être  ppMS         ɛte    22
436629     évanouir  ppFS      ɛvanui     2
437301       éviter   inf       ɛvite     1
437367      évoluer   inf      ɛvɔlye     1
437407      évoluer  ppMS      ɛvɔlye     1
437416      évoquer  ii3S       ɛvɔkɛ     2
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    20

[1954 rows x 4 columns]

0
CPU times: user 1min 2s, sys: 22.4 s, total: 1min 24s
Wall time: 34.3 s

nbChunk 29
4200
1920

             lexeme  case        phono  tir1
40            avoir  pi3S            a   105
125      abandonner  pi1S      abɑ̃dɔn     1
132      abandonner   inf     abɑ̃dɔne     1
170      abandonner  ppMP     abɑ̃dɔne     1
688         abjurer  ppMS       abʒyʁe     1
1130        aborder  ii1S       abɔʁdɛ     1
1859        abréger  pi3S        abʁɛʒ     1
2102       absorber  ppFS      absɔʁbe     1
2220       abstenir  fi3P  abstjɛ̃dʁɔ̃     1
2791      accaparer   inf      akapaʁe     1
2952       accepter    pP     aksɛptɑ̃     1
2971       accepter   inf      aksɛpte     1
2989       accepter  pi2P      aksɛpte     1
3406    accompagner   inf     akɔ̃paɲe     2
3530       accorder  pi3S        akɔʁd     1
3536       accorder   inf       akɔʁde     1
3573       accorder  ppFS       akɔʁde     1
3862       accouder  ai3S        akuda     1
4072       accourir   inf       akuʁiʁ     1
4255      accrocher  pi3S        akʁɔʃ     1
4257      accrocher  pi3P        akʁɔʃ     1
4693        accuser  ii3S        akyzɛ     1
4694        accuser    pP       akyzɑ̃     1
5054      acheminer    pP     aʃəminɑ̃     1
5119        acheter   inf        aʃəte     4
5157        achever   inf        aʃəve     1
5171        achever  ppMS        aʃəve     1
5332        achever  pi3S         aʃɛv     1
5885       acquérir  pi3P        akjɛʁ     1
6049        activer  ai1S       aktivɛ     1
...             ...   ...          ...   ...
432537     éprouver  ii3S       ɛpʁuvɛ     1
432556     éprouver   inf       ɛpʁuve     1
432580     éprouver  pi1P      ɛpʁuvɔ̃     1
432586     éprouver  ppMS       ɛpʁuve     2
433922      établir   inf      ɛtabliʁ     2
434048         être  ii3P          ɛtɛ     6
434068         être  ii1S          ɛtɛ    13
434070         être  ii3S          ɛtɛ    75
434135       étaler    pP       ɛtalɑ̃     1
434147       étaler  pi3S         ɛtal     1
434488         être    pP         ɛtɑ̃     1
434762     éteindre   inf       ɛtɛ̃dʁ     1
434772     éteindre  ppMS         ɛtɛ̃     1
434831      étendre  ppMS       ɛtɑ̃dy     1
435054         être  ii2P         ɛtje     4
435172         être  ii1P        ɛtjɔ̃     2
435240       étirer  ii3P        ɛtiʁɛ     1
435258       étirer  pi3P         ɛtiʁ     1
435450      étonner  pc3S      ɛtɔnəʁɛ     1
435497     étouffer  pi1S         ɛtuf     1
435506     étouffer   inf        ɛtufe     1
435748    étrangler   inf     ɛtʁɑ̃gle     1
435780    étrangler  ppMS     ɛtʁɑ̃gle     1
435782    étrangler  ppFS     ɛtʁɑ̃gle     1
436316         être  ppMS          ɛte    19
436837     éveiller  fi1S      ɛvɛjəʁɛ     1
437301       éviter   inf        ɛvite     6
437317       éviter  pi2P        ɛvite     1
437474         être  pi2P           ɛt     4
437476         être   inf          ɛtʁ    18

[1920 rows x 4 columns]

0
CPU times: user 1min 7s, sys: 22.4 s, total: 1min 29s
Wall time: 33.5 s

nbChunk 30
4200
1958

             lexeme  case       phono  tir1
40            avoir  pi3S           a    88
132      abandonner   inf    abɑ̃dɔne     1
166      abandonner  ppFS    abɑ̃dɔne     1
299         abattre   inf       abatʁ     1
1143        aborder  pi3S       abɔʁd     1
1388        aboutir  ppMS       abuti     1
1468         aboyer   inf      abwaje     1
2066       absorber  pi3S      absɔʁb     1
2102       absorber  ppFS     absɔʁbe     1
2135       abstenir  ii3S     abstənɛ     1
2587         abîmer  pc3S     abiməʁɛ     1
2612         abîmer  ppFS       abime     1
2920      accentuer  pi2P    aksɑ̃tye     1
2967       accepter  pi3S      aksɛpt     2
2971       accepter   inf     aksɛpte     2
3422    accompagner  pi2P    akɔ̃paɲe     1
3530       accorder  pi3S       akɔʁd     1
3537       accorder  fi3S    akɔʁdəʁa     1
3573       accorder  ppFS      akɔʁde     1
3827      accoucher   inf       akuʃe     1
4280      accrocher  pi2P      akʁɔʃe     1
4291      accrocher  ppMS      akʁɔʃe     1
4368      accroupir  ai3S      akʁupi     1
4381      accroître   inf     akʁwatʁ     1
4720        accuser   inf       akyze     2
5119        acheter   inf       aʃəte     3
5136        acheter  ppMS       aʃəte     1
5807       acquérir  ppMS         aki     1
5812       acquérir  ppFS        akiz     1
6955    administrer  ppMS  administʁe     1
...             ...   ...         ...   ...
432556     éprouver   inf      ɛpʁuve     1
432586     éprouver  ppMS      ɛpʁuve     1
432657      épuiser  pi3P       ɛpɥiz     1
432691      épuiser  ppFS      ɛpɥize     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    80
434134       étaler  ii3S       ɛtalɛ     1
434302       étaler  ppMP       ɛtale     1
434726     éteindre  ii3S       ɛtɛɲɛ     1
434821      étendre   inf      ɛtɑ̃dʁ     1
435054         être  ii2P        ɛtje     1
435438      étonner  pi3S        ɛtɔn     1
435471      étonner  ppMS       ɛtɔne     1
435504     étouffer  pi3P        ɛtuf     1
435726    étrangler  ai3S    ɛtʁɑ̃gla     1
435780    étrangler  ppMS    ɛtʁɑ̃gle     1
435794    étreindre  ii3S      ɛtʁɛɲɛ     1
436212      étudier  fi2S     ɛtydiʁa     1
436221      étudier  pi2P      ɛtydje     1
436227      étudier  pi1P     ɛtydjɔ̃     1
436316         être  ppMS         ɛte    33
436457       évader   inf       ɛvade     1
436520      évaluer   inf      ɛvalye     1
436831     éveiller  pi3S        ɛvɛj     1
436836     éveiller  fi3S     ɛvɛjəʁa     1
437301       éviter   inf       ɛvite     1
437417      évoquer    pP      ɛvɔkɑ̃     1
437474         être  pi2P          ɛt    18
437476         être   inf         ɛtʁ    17

[1958 rows x 4 columns]

0
CPU times: user 1min 3s, sys: 22.5 s, total: 1min 26s
Wall time: 33.9 s

nbChunk 31
4200
1961

             lexeme  case     phono  tir1
40            avoir  pi3S         a   104
132      abandonner   inf  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     1
299         abattre   inf     abatʁ     1
1112        abonner  ppFS     abɔne     1
1393        aboutir   inf    abutiʁ     1
2581         abîmer   inf     abime     1
2610         abîmer  ppMS     abime     1
2900      accentuer  pi3S   aksɑ̃ty     1
2904      accentuer   inf  aksɑ̃tye     1
2950       accepter  ii3S   aksɛptɛ     1
2971       accepter   inf   aksɛpte     1
2989       accepter  pi2P   aksɛpte     1
3009       accepter  ppMP   aksɛpte     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     2
3422    accompagner  pi2P  akɔ̃paɲe     2
3438      accomplir  ppMS   akɔ̃pli     1
3821      accoucher  pi3S      akuʃ     1
3827      accoucher   inf     akuʃe     1
3878       accouder  pi3S      akud     1
4216     accoutumer  ppMP   akutyme     1
4292      accrocher  ppFS    akʁɔʃe     1
4323      accroupir   inf   akʁupiʁ     1
4341      accroupir  pI2S    akʁupi     1
4426     accréditer   inf  akʁɛdite     1
4502     accueillir  ppMS     akəji     1
4748        accuser  ppMS     akyze     1
4812      accélérer  pi3S   aksɛlɛʁ     2
5119        acheter   inf     aʃəte     3
...             ...   ...       ...   ...
431906     éplucher  ppMS    ɛplyʃe     1
432160      épouser   inf     ɛpuze     1
432302      épouser  ppMS     ɛpuze     1
432549     éprouver  pi1S     ɛpʁuv     1
432556     éprouver   inf    ɛpʁuve     1
433950      établir  ps3S   ɛtablis     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ     9
434069         être  ii2S       ɛtɛ     1
434070         être  ii3S       ɛtɛ    71
434762     éteindre   inf    ɛtɛ̃dʁ     1
434770     éteindre  pi2S      ɛtɛ̃     1
434773     éteindre  pi3S      ɛtɛ̃     1
434779     éteindre  ppMP      ɛtɛ̃     1
434789      étendre    pP   ɛtɑ̃dɑ̃     1
435444      étonner   inf     ɛtɔne     1
435450      étonner  pc3S   ɛtɔnəʁɛ     1
435506     étouffer   inf     ɛtufe     1
436205      étudier   inf    ɛtydje     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    24
436520      évaluer   inf    ɛvalye     1
436815     éveiller  ai3S     ɛvɛja     1
436835     éveiller   inf     ɛvɛje     2
437281       éviter  ii3P     ɛvitɛ     1
437301       éviter   inf     ɛvite     2
437328       éviter  ppMS     ɛvite     2
437474         être  pi2P        ɛt    12
437476         être   inf       ɛtʁ    19
437539         ôter  ppMS       ɔte     1

[1961 rows x 4 columns]

0
CPU times: user 1min 2s, sys: 22.3 s, total: 1min 24s
Wall time: 35 s

nbChunk 32
4200
1944

             lexeme  case       phono  tir1
40            avoir  pi3S           a    90
113      abandonner  ii3S    abɑ̃dɔnɛ     1
132      abandonner   inf    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     1
264         abattre  pi3P        abat     1
1684        abriter  pi3S       abʁit     1
1688        abriter   inf      abʁite     1
2371         abuser  ppMS       abyze     1
2614         abîmer  ppFP       abime     1
2715       accabler  ii3S      akablɛ     1
2887      accentuer  ii3S    aksɑ̃tyɛ     1
2971       accepter   inf     aksɛpte     1
2977       accepter  pc3S   aksɛptəʁɛ     1
3406    accompagner   inf    akɔ̃paɲe     1
3468      accomplir    pP  akɔ̃plisɑ̃     1
4216     accoutumer  ppMP     akutyme     1
4255      accrocher  pi3S       akʁɔʃ     1
4280      accrocher  pi2P      akʁɔʃe     1
4293      accrocher  ppFP      akʁɔʃe     1
4381      accroître   inf     akʁwatʁ     1
4473     accueillir  ii3S       akəjɛ     1
4509     accueillir   inf      akəjiʁ     1
4713        accuser  pi1S        akyz     1
5041       acharner  ppMS      aʃaʁne     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     1
5311        acheter  pi3S        aʃɛt     1
5905       acquérir   inf      akɛʁiʁ     1
6054        activer    pP     aktivɑ̃     1
6418        adapter  pc1S    adaptəʁɛ     1
...             ...   ...         ...   ...
432374   épouvanter  ii3S    ɛpuvɑ̃tɛ     1
432537     éprouver  ii3S      ɛpʁuvɛ     3
432689      épuiser  ppMS      ɛpɥize     1
432695      épuiser  ppMP      ɛpɥize     1
433914      établir  ppFS      ɛtabli     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ    19
434070         être  ii3S         ɛtɛ    90
434301       étaler  ppFP       ɛtale     1
434488         être    pP        ɛtɑ̃     1
434773     éteindre  pi3S        ɛtɛ̃     1
434831      étendre  ppMS      ɛtɑ̃dy     1
434833      étendre  ppFS      ɛtɑ̃dy     2
434868    éterniser   inf    ɛtɛʁnize     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     2
435232       étirer  ai3S       ɛtiʁa     1
435425      étonner    pP      ɛtɔnɑ̃     1
435484     étouffer  ii3S       ɛtufɛ     1
435828    étreindre   inf     ɛtʁɛ̃dʁ     1
435834    étreindre  pi1S       ɛtʁɛ̃     1
436316         être  ppMS         ɛte    26
436402      évacuer   inf      ɛvakye     1
436820     éveiller  ii3S       ɛvɛjɛ     1
436904      éventer   inf      ɛvɑ̃te     1
437292       éviter  pi1S        ɛvit     1
437301       éviter   inf       ɛvite     4
437328       éviter  ppMS       ɛvite     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    15

[1944 rows x 4 columns]

0
CPU times: user 1min 3s, sys: 22.5 s, total: 1min 25s
Wall time: 34 s

nbChunk 33
4200
1933

             lexeme  case       phono  tir1
40            avoir  pi3S           a   101
45         abaisser  ai3S       abɛsa     1
128      abandonner  pi3S     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
170      abandonner  ppMP    abɑ̃dɔne     1
1147        aborder   inf      abɔʁde     1
1417        aboutir    pP    abutisɑ̃     1
1688        abriter   inf      abʁite     1
1946       absenter  pi3S      absɑ̃t     1
1979       absenter  ppMS     absɑ̃te     1
2610         abîmer  ppMS       abime     1
2616         abîmer  ppMP       abime     1
2950       accepter  ii3S     aksɛptɛ     1
2964       accepter  pi1S      aksɛpt     1
2969       accepter  pi3P      aksɛpt     1
2971       accepter   inf     aksɛpte     1
3003       accepter  ppMS     aksɛpte     1
3406    accompagner   inf    akɔ̃paɲe     1
3413    accompagner  fi2S  akɔ̃paɲəʁa     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
3536       accorder   inf      akɔʁde     2
3571       accorder  ppMS      akɔʁde     1
4007       accourir  ii1S       akuʁɛ     1
4075       accourir  fi3S      akuʁʁa     1
4720        accuser   inf       akyze     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     3
5905       acquérir   inf      akɛʁiʁ     1
6044      actionner  ppFS     aksjɔne     1
...             ...   ...         ...   ...
432519     éprendre  ppMS        ɛpʁi     1
432532     éprouver  ai3S      ɛpʁuva     1
432556     éprouver   inf      ɛpʁuve     2
433170      équiper  ppFS       ɛkipe     1
434068         être  ii1S         ɛtɛ    15
434070         être  ii3S         ɛtɛ    84
434821      étendre   inf      ɛtɑ̃dʁ     1
435054         être  ii2P        ɛtje     3
435172         être  ii1P       ɛtjɔ̃     1
435420      étonner  ii1S       ɛtɔnɛ     1
435471      étonner  ppMS       ɛtɔne     1
435500     étouffer  pi3S        ɛtuf     1
435538     étouffer  ppMS       ɛtufe     1
436184      étudier  ii1S      ɛtydjɛ     1
436201      étudier  pi3S       ɛtydi     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    29
436402      évacuer   inf      ɛvakye     1
436457       évader   inf       ɛvade     1
436820     éveiller  ii3S       ɛvɛjɛ     1
436835     éveiller   inf       ɛvɛje     1
437285       éviter    pP      ɛvitɑ̃     1
437301       éviter   inf       ɛvite     2
437302       éviter  fi3S     ɛvitəʁa     1
437317       éviter  pi2P       ɛvite     1
437424      évoquer  pi1S        ɛvɔk     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    20
437492         ôter  ai3S         ɔta     1
437539         ôter  ppMS         ɔte     1

[1933 rows x 4 columns]

0
CPU times: user 1min 1s, sys: 21.4 s, total: 1min 22s
Wall time: 33.9 s

nbChunk 34
4200
1937

             lexeme  case       phono  tir1
40            avoir  pi3S           a    87
128      abandonner  pi3S     abɑ̃dɔn     2
299         abattre   inf       abatʁ     1
869          aboyer  pi3P        abwa     1
1801        abrutir   inf     abʁytiʁ     1
2154       abstenir  ppMS     abstəny     1
2214       abstenir  pc3S  abstjɛ̃dʁɛ     1
2579         abîmer  pi3P        abim     1
2948       accepter  ii1S     aksɛptɛ     1
2971       accepter   inf     aksɛpte     2
2972       accepter  fi3S   aksɛptəʁa     1
3003       accepter  ppMS     aksɛpte     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     2
3434    accompagner  ppFS    akɔ̃paɲe     1
3440      accomplir  ppFS     akɔ̃pli     1
3556       accorder  pi2P      akɔʁde     1
4255      accrocher  pi3S       akʁɔʃ     3
4257      accrocher  pi3P       akʁɔʃ     1
4291      accrocher  ppMS      akʁɔʃe     1
4320      accroupir  ppMS      akʁupi     1
4509     accueillir   inf      akəjiʁ     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     1
5146        achever  ii3P       aʃəvɛ     1
5149        achever  ii3S       aʃəvɛ     1
5171        achever  ppMS       aʃəve     1
5807       acquérir  ppMS         aki     1
6446        adapter  ppMP      adapte     1
...             ...   ...         ...   ...
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ    12
434069         être  ii2S         ɛtɛ     3
434070         être  ii3S         ɛtɛ    80
434144       étaler  pi1S        ɛtal     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434775     éteindre  ppFS       ɛtɛ̃t     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434821      étendre   inf      ɛtɑ̃dʁ     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     1
435422      étonner  ii3S       ɛtɔnɛ     1
435435      étonner  pi1S        ɛtɔn     1
435501     étouffer  ps3S        ɛtuf     1
435506     étouffer   inf       ɛtufe     1
435540     étouffer  ppFS       ɛtufe     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    24
436815     éveiller  ai3S       ɛvɛja     1
436828     éveiller  pi1S        ɛvɛj     1
436835     éveiller   inf       ɛvɛje     1
436867     éveiller  ppMS       ɛvɛje     1
437005     éventrer  fi2P   ɛvɑ̃tʁəʁe     1
437040      éventer  ppMS      ɛvɑ̃te     1
437301       éviter   inf       ɛvite     2
437363      évoluer  pi3S       ɛvɔly     1
437474         être  pi2P          ɛt    11
437476         être   inf         ɛtʁ    16
437512         ôter   inf         ɔte     2
437525         ôter  pi2S          ot     1

[1937 rows x 4 columns]

0
CPU times: user 1min 5s, sys: 22.3 s, total: 1min 27s
Wall time: 33.3 s

nbChunk 35
4200
1972

             lexeme  case      phono  tir1
40            avoir  pi3S          a   102
307         abattre  ppFS      abaty     1
313         abattre  ppMP      abaty     1
1468         aboyer   inf     abwaje     1
2244       abstenir  ai3S     abstɛ̃     1
2717       accabler    pP    akablɑ̃     1
2971       accepter   inf    aksɛpte     2
2974       accepter  pc3P  aksɛptəʁɛ     1
2989       accepter  pi2P    aksɛpte     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3536       accorder   inf     akɔʁde     1
4094       accourir  ai3P     akuʁyʁ     1
4259      accrocher   inf     akʁɔʃe     1
4283      accrocher  ii1P   akʁɔʃjɔ̃     1
4473     accueillir  ii3S      akəjɛ     1
4511     accueillir  ppMP      akəji     1
4716        accuser  pi3S       akyz     1
4720        accuser   inf      akyze     1
4812      accélérer  pi3S    aksɛlɛʁ     1
4864      accélérer  ppFS   aksɛlɛʁe     1
5044       acharner  ppMP     aʃaʁne     1
5109        acheter  ii1S      aʃətɛ     1
5136        acheter  ppMS      aʃəte     1
5157        achever   inf      aʃəve     1
5326        acheter  fi3P   aʃɛtəʁɔ̃     1
5327        acheter  pi2S       aʃɛt     1
6969        admirer  ii3S     admiʁɛ     1
6991        admirer  pi3S      admiʁ     1
7231        adopter  ii3S     adɔptɛ     1
...             ...   ...        ...   ...
427733        élire  ppMS        ɛly     1
427923       élever  pi3S       ɛlɛv     1
428561  émerveiller  ii3S   ɛmɛʁvɛjɛ     1
432156      épouser  pi3S       ɛpuz     1
432556     éprouver   inf     ɛpʁuve     1
432586     éprouver  ppMS     ɛpʁuve     1
433922      établir   inf    ɛtabliʁ     3
433954      établir  pi3P    ɛtablis     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    12
434070         être  ii3S        ɛtɛ    74
434762     éteindre   inf     ɛtɛ̃dʁ     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434833      étendre  ppFS     ɛtɑ̃dy     1
434901     éternuer  ai3S    ɛtɛʁnya     1
435172         être  ii1P      ɛtjɔ̃     1
435243       étirer  ii3S      ɛtiʁɛ     1
435438      étonner  pi3S       ɛtɔn     1
435452      étonner  fi2P    ɛtɔnəʁe     1
435484     étouffer  ii3S      ɛtufɛ     2
436201      étudier  pi3S      ɛtydi     1
436316         être  ppMS        ɛte    34
436453       évader  pi3S       ɛvad     1
436457       évader   inf      ɛvade     1
437295       éviter  pi3S       ɛvit     1
437301       éviter   inf      ɛvite     4
437329       éviter  ppFS      ɛvite     1
437474         être  pi2P         ɛt    14
437476         être   inf        ɛtʁ    20
437513         ôter  fi3S      ɔtəʁa     1

[1972 rows x 4 columns]

0
CPU times: user 1min 3s, sys: 22.9 s, total: 1min 26s
Wall time: 33.9 s

nbChunk 36
4200
1937

             lexeme  case        phono  tir1
40            avoir  pi3S            a    82
164      abandonner  ppMS     abɑ̃dɔne     2
243         abattre  pi3S          aba     1
299         abattre   inf        abatʁ     1
982         abonder  pi3P        abɔ̃d     1
1162        aborder  pI2P       abɔʁde     1
1393        aboutir   inf       abutiʁ     1
1440        aboutir  pi3S        abuti     1
1468         aboyer   inf       abwaje     1
2339         abuser   inf        abyze     1
2736       accabler   inf       akable     1
2964       accepter  pi1S       aksɛpt     1
2971       accepter   inf      aksɛpte     1
3385    accompagner  ii3S     akɔ̃paɲɛ     1
3406    accompagner   inf     akɔ̃paɲe     1
3417    accompagner  fi1P  akɔ̃paɲəʁɔ̃     1
3419    accompagner  pi2S      akɔ̃paɲ     1
3443      accomplir   inf     akɔ̃pliʁ     1
3488      accomplir  pi1P   akɔ̃plisɔ̃     1
3530       accorder  pi3S        akɔʁd     1
3573       accorder  ppFS       akɔʁde     1
3827      accoucher   inf        akuʃe     1
3884       accouder   inf        akude     1
4178     accoutumer  pi3S       akutym     1
4292      accrocher  ppFS       akʁɔʃe     1
4373      accroître  pi3S        akʁwa     1
4637      accumuler  ii3S      akymylɛ     1
5119        acheter   inf        aʃəte     2
5136        acheter  ppMS        aʃəte     1
5165        achever  pi1P       aʃəvɔ̃     1
...             ...   ...          ...   ...
428110      émacier  ppMP       ɛmasje     1
428557  émerveiller  ai1S     ɛmɛʁvɛjɛ     1
428605  émerveiller  ppMS     ɛmɛʁvɛje     1
430042     énumérer   inf      ɛnymɛʁe     1
430509     épanouir  ii3S     ɛpanuisɛ     1
430532     épanouir  pi3S       ɛpanui     1
432160      épouser   inf        ɛpuze     2
434048         être  ii3P          ɛtɛ     2
434068         être  ii1S          ɛtɛ    11
434069         être  ii2S          ɛtɛ     1
434070         être  ii3S          ɛtɛ    69
434730     éteindre  pi3P         ɛtɛɲ     1
434782      étendre  pi3S         ɛtɑ̃     1
434833      étendre  ppFS       ɛtɑ̃dy     1
434917     éternuer  pi3S       ɛtɛʁny     1
435054         être  ii2P         ɛtje     3
435172         être  ii1P        ɛtjɔ̃     1
435258       étirer  pi3P         ɛtiʁ     1
435419      étonner  ii3P        ɛtɔnɛ     1
435538     étouffer  ppMS        ɛtufe     1
436316         être  ppMS          ɛte    25
436402      évacuer   inf       ɛvakye     1
437285       éviter    pP       ɛvitɑ̃     1
437301       éviter   inf        ɛvite     3
437307       éviter  pc3S      ɛvitəʁɛ     1
437327       éviter  ai3P       ɛvitɛʁ     1
437414      évoquer  ii1S        ɛvɔkɛ     1
437427      évoquer  pi3S         ɛvɔk     1
437474         être  pi2P           ɛt    15
437476         être   inf          ɛtʁ    25

[1937 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 21.6 s, total: 1min 39s
Wall time: 32.9 s

nbChunk 37
4200
1973

             lexeme  case     phono  tir1
40            avoir  pi3S         a    90
128      abandonner  pi3S   abɑ̃dɔn     1
164      abandonner  ppMS  abɑ̃dɔne     1
299         abattre   inf     abatʁ     2
887          abolir  ppMS     abɔli     1
2339         abuser   inf     abyze     1
2971       accepter   inf   aksɛpte     1
2989       accepter  pi2P   aksɛpte     1
3319     accommoder  ii3P   akɔmɔdɛ     1
3343     accommoder  pi3S    akɔmɔd     1
3397    accompagner  pi1S   akɔ̃paɲ     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3530       accorder  pi3S     akɔʁd     2
3827      accoucher   inf     akuʃe     1
4090       accourir  pi3S      akuʁ     1
4210     accoutumer  ppMS   akutyme     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4369      accroupir  pi3S    akʁupi     1
4373      accroître  pi3S     akʁwa     1
4685      accumuler  ppFP   akymyle     1
4748        accuser  ppMS     akyze     1
4835      accélérer   inf  aksɛlɛʁe     1
5111        acheter  ii3S     aʃətɛ     1
5119        acheter   inf     aʃəte     1
5136        acheter  ppMS     aʃəte     1
5308        acheter  pi1S      aʃɛt     1
5327        acheter  pi2S      aʃɛt     1
6412        adapter  pi3P     adapt     1
6996        admirer   inf    admiʁe     1
...             ...   ...       ...   ...
427733        élire  ppMS       ɛly     1
429349     émouvoir   inf   ɛmuvwaʁ     2
429365     émouvoir  ppMS       ɛmy     1
430340     épancher   inf    ɛpɑ̃ʃe     1
430531     épanouir  ai3S    ɛpanui     1
432523     éprendre  ppFS     ɛpʁiz     1
432533     éprouver  ai1S    ɛpʁuvɛ     1
432552     éprouver  pi3S     ɛpʁuv     1
433926      établir  pc1S  ɛtabliʁɛ     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    14
434070         être  ii3S       ɛtɛ    72
434131       étaler  ii3P     ɛtalɛ     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
434801      étendre  ii1P  ɛtɑ̃djɔ̃     1
435054         être  ii2P      ɛtje     1
435116      étioler  ii1S    ɛtjɔlɛ     1
435172         être  ii1P     ɛtjɔ̃     1
435243       étirer  ii3S     ɛtiʁɛ     1
435450      étonner  pc3S   ɛtɔnəʁɛ     1
435486     étouffer    pP    ɛtufɑ̃     1
435506     étouffer   inf     ɛtufe     1
435815    étreindre  ai3S    ɛtʁɛɲi     1
436316         être  ppMS       ɛte    21
437301       éviter   inf     ɛvite     2
437365      évoluer  pi3P     ɛvɔly     1
437417      évoquer    pP    ɛvɔkɑ̃     1
437474         être  pi2P        ɛt     9
437476         être   inf       ɛtʁ    15
437492         ôter  ai3S       ɔta     1

[1973 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 21.4 s, total: 1min 34s
Wall time: 31.8 s

nbChunk 38
4200
1960

             lexeme  case       phono  tir1
40            avoir  pi3S           a    89
149      abandonner  ii2P   abɑ̃dɔnje     1
164      abandonner  ppMS    abɑ̃dɔne     1
170      abandonner  ppMP    abɑ̃dɔne     1
890          abolir   inf      abɔliʁ     1
1796        abrutir  ppMS      abʁyti     1
1825        abrutir  ii3S    abʁytisɛ     1
2904      accentuer   inf    aksɑ̃tye     1
2932      accentuer  ppMS    aksɑ̃tye     1
2964       accepter  pi1S      aksɛpt     1
2969       accepter  pi3P      aksɛpt     1
2989       accepter  pi2P     aksɛpte     1
2990       accepter  ii2P    aksɛptje     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3421    accompagner  pI2P    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
3530       accorder  pi3S       akɔʁd     1
3827      accoucher   inf       akuʃe     1
3862       accouder  ai3S       akuda     1
4294      accrocher  ppMP      akʁɔʃe     1
4323      accroupir   inf     akʁupiʁ     1
5119        acheter   inf       aʃəte     2
5131        acheter  pi1P      aʃətɔ̃     1
5137        acheter  ppFS       aʃəte     1
5140        achever  ai3S       aʃəva     1
5308        acheter  pi1S        aʃɛt     1
5315        acheter  fi3S     aʃɛtəʁa     1
6072        activer   inf      aktive     1
6928    administrer   inf  administʁe     1
6970        admirer    pP     admiʁɑ̃     1
...             ...   ...         ...   ...
433062   équilibrer  ppMS    ɛkilibʁe     1
433113      équiper   inf       ɛkipe     1
433912      établir  ppMS      ɛtabli     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ    13
434070         être  ii3S         ɛtɛ    73
434153       étaler   inf       ɛtale     1
434755     éteindre  fi3S     ɛtɛ̃dʁa     1
434773     éteindre  pi3S        ɛtɛ̃     1
434821      étendre   inf      ɛtɑ̃dʁ     1
435054         être  ii2P        ɛtje     3
435133      étioler  pi3P       ɛtjɔl     1
435172         être  ii1P       ɛtjɔ̃     3
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435471      étonner  ppMS       ɛtɔne     1
435484     étouffer  ii3S       ɛtufɛ     1
435968      étriper  pi3S       ɛtʁip     1
436201      étudier  pi3S       ɛtydi     1
436316         être  ppMS         ɛte    26
436629     évanouir  ppFS      ɛvanui     1
436820     éveiller  ii3S       ɛvɛjɛ     1
436835     éveiller   inf       ɛvɛje     1
436873     éveiller  ppMP       ɛvɛje     1
437301       éviter   inf       ɛvite     1
437331       éviter  ppMP       ɛvite     1
437417      évoquer    pP      ɛvɔkɑ̃     1
437474         être  pi2P          ɛt    10
437476         être   inf         ɛtʁ    15
437508         ôter  pi3S          ot     1

[1960 rows x 4 columns]

0
CPU times: user 1min 4s, sys: 22.3 s, total: 1min 26s
Wall time: 32.4 s

nbChunk 39
4200
1926

             lexeme  case      phono  tir1
40            avoir  pi3S          a    86
100        abaisser  ai3P     abɛsɛʁ     1
129      abandonner  ps3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
1388        aboutir  ppMS      abuti     1
2389      abâtardir  ppMS   abataʁdi     1
2734       accabler  pi3P      akabl     1
2967       accepter  pi3S     aksɛpt     3
2971       accepter   inf    aksɛpte     3
2975       accepter  pc1S  aksɛptəʁɛ     1
2989       accepter  pi2P    aksɛpte     1
3406    accompagner   inf   akɔ̃paɲe     1
3573       accorder  ppFS     akɔʁde     1
3821      accoucher  pi3S       akuʃ     1
4103       accourir  ai3S      akuʁy     1
4234      accrocher  ii3P     akʁɔʃɛ     1
4257      accrocher  pi3P      akʁɔʃ     1
4339      accroupir  pi1S     akʁupi     1
4368      accroupir  ai3S     akʁupi     1
4479     accueillir  pi1S       akœj     1
4716        accuser  pi3S       akyz     2
4748        accuser  ppMS      akyze     1
4811      accélérer  pI2S    aksɛlɛʁ     1
4835      accélérer   inf   aksɛlɛʁe     1
4864      accélérer  ppFS   aksɛlɛʁe     1
5119        acheter   inf      aʃəte     1
6412        adapter  pi3P      adapt     1
6443        adapter  ppMS     adapte     1
...             ...   ...        ...   ...
427671     éloigner  ppMP     ɛlwaɲe     1
428650     émouvoir  pi3S        ɛmø     1
430540     épargner  ii1S     ɛpaʁɲɛ     1
431871     éplucher   inf     ɛplyʃe     1
432302      épouser  ppMS      ɛpuze     1
432534     éprouver  ii3P     ɛpʁuvɛ     1
432689      épuiser  ppMS     ɛpɥize     1
433354      érafler  ppMS     ɛʁafle     1
433571       ériger  pi3S       ɛʁiʒ     1
433912      établir  ppMS     ɛtabli     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    13
434070         être  ii3S        ɛtɛ    80
434772     éteindre  ppMS       ɛtɛ̃     1
434773     éteindre  pi3S       ɛtɛ̃     1
434782      étendre  pi3S       ɛtɑ̃     1
434950     éternuer  ppMS    ɛtɛʁnye     1
435054         être  ii2P       ɛtje     3
435172         être  ii1P      ɛtjɔ̃     1
435419      étonner  ii3P      ɛtɔnɛ     1
435438      étonner  pi3S       ɛtɔn     1
435666     étourdir  pc3S   ɛtuʁdiʁɛ     1
436198      étudier  pi1S      ɛtydi     1
436205      étudier   inf     ɛtydje     2
436316         être  ppMS        ɛte    22
437124       évider  pi3P       ɛvid     1
437301       éviter   inf      ɛvite     1
437417      évoquer    pP     ɛvɔkɑ̃     1
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    18

[1926 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.2 s, total: 1min 36s
Wall time: 32.3 s

nbChunk 40
4200
1944

             lexeme  case      phono  tir1
40            avoir  pi3S          a    88
148      abandonner  pi2P   abɑ̃dɔne     1
255         abattre  ii3P      abatɛ     1
292         abattre  fi3S     abatʁa     1
305         abattre  ppMS      abaty     1
1688        abriter   inf     abʁite     1
1796        abrutir  ppMS     abʁyti     1
2070       absorber   inf    absɔʁbe     1
2100       absorber  ppMS    absɔʁbe     1
2971       accepter   inf    aksɛpte     1
3382    accompagner  ii3P   akɔ̃paɲɛ     1
3404    accompagner  pi3P    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     2
3419    accompagner  pi2S    akɔ̃paɲ     1
3443      accomplir   inf   akɔ̃pliʁ     1
3467      accomplir  ii3S  akɔ̃plisɛ     1
3490      accomplir  pi3S    akɔ̃pli     1
3556       accorder  pi2P     akɔʁde     1
3571       accorder  ppMS     akɔʁde     1
3583       accorder  ppMP     akɔʁde     1
3858      accoucher  ppMS      akuʃe     1
4233      accrocher  ai1S     akʁɔʃɛ     1
4252      accrocher  pi1S      akʁɔʃ     1
4279      accrocher  pI2P     akʁɔʃe     1
4293      accrocher  ppFP     akʁɔʃe     1
4470     accueillir  ii3P      akəjɛ     1
4482     accueillir  pi3S       akœj     1
4720        accuser   inf      akyze     1
5119        acheter   inf      aʃəte     6
5137        acheter  ppFS      aʃəte     1
...             ...   ...        ...   ...
432160      épouser   inf      ɛpuze     1
432532     éprouver  ai3S     ɛpʁuva     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ    17
434070         être  ii3S        ɛtɛ    74
434153       étaler   inf      ɛtale     1
434773     éteindre  pi3S       ɛtɛ̃     1
434782      étendre  pi3S       ɛtɑ̃     2
434833      étendre  ppFS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     1
435232       étirer  ai3S      ɛtiʁa     1
435438      étonner  pi3S       ɛtɔn     1
435506     étouffer   inf      ɛtufe     1
435517     étouffer  fi1P   ɛtufəʁɔ̃     1
436316         être  ppMS        ɛte    29
436457       évader   inf      ɛvade     1
436520      évaluer   inf     ɛvalye     1
436704     évaporer  pi1S     ɛvapɔʁ     1
436815     éveiller  ai3S      ɛvɛja     1
436820     éveiller  ii3S      ɛvɛjɛ     1
436867     éveiller  ppMS      ɛvɛje     1
437027     éventrer  ppMP    ɛvɑ̃tʁe     1
437117       évider  pi3S       ɛvid     1
437301       éviter   inf      ɛvite     2
437427      évoquer  pi3S       ɛvɔk     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt     9
437476         être   inf        ɛtʁ    21

[1944 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 21.3 s, total: 1min 34s
Wall time: 32.5 s

nbChunk 41
4200
1941

             lexeme  case     phono  tir1
40            avoir  pi3S         a    96
67         abaisser  pi3S      abɛs     1
113      abandonner  ii3S  abɑ̃dɔnɛ     1
128      abandonner  pi3S   abɑ̃dɔn     2
258         abattre  ii3S     abatɛ     2
913          abolir  ii3S   abɔlisɛ     1
1147        aborder   inf    abɔʁde     1
2066       absorber  pi3S    absɔʁb     1
2764       accabler  ppFS    akable     1
2904      accentuer   inf  aksɑ̃tye     1
2948       accepter  ii1S   aksɛptɛ     1
2967       accepter  pi3S    aksɛpt     1
2997       accepter  pi1P  aksɛptɔ̃     1
3003       accepter  ppMS   aksɛpte     1
3146       acclamer  ppFP    aklame     1
3397    accompagner  pi1S   akɔ̃paɲ     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3440      accomplir  ppFS   akɔ̃pli     1
3443      accomplir   inf  akɔ̃pliʁ     1
3536       accorder   inf    akɔʁde     1
3878       accouder  pi3S      akud     1
4234      accrocher  ii3P    akʁɔʃɛ     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4255      accrocher  pi3S     akʁɔʃ     1
4291      accrocher  ppMS    akʁɔʃe     1
4294      accrocher  ppMP    akʁɔʃe     1
4373      accroître  pi3S     akʁwa     1
4509     accueillir   inf    akəjiʁ     1
4748        accuser  ppMS     akyze     1
4754        accuser  ppMP     akyze     1
...             ...   ...       ...   ...
433272    éradiquer   inf   ɛʁadike     1
433916      établir  ppFP    ɛtabli     1
433939      établir  pi1S    ɛtabli     1
434048         être  ii3P       ɛtɛ     7
434068         être  ii1S       ɛtɛ    16
434070         être  ii3S       ɛtɛ    80
434300       étaler  ppFS     ɛtale     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
434768     éteindre  pi1S      ɛtɛ̃     1
434782      étendre  pi3S      ɛtɑ̃     1
435054         être  ii2P      ɛtje     2
435059    étinceler  ii3P  ɛtɛ̃səlɛ     1
435172         être  ii1P     ɛtjɔ̃     2
435417      étonner  ai3S     ɛtɔna     1
435471      étonner  ppMS     ɛtɔne     1
435484     étouffer  ii3S     ɛtufɛ     1
435497     étouffer  pi1S      ɛtuf     1
435794    étreindre  ii3S    ɛtʁɛɲɛ     1
436201      étudier  pi3S     ɛtydi     1
436316         être  ppMS       ɛte    15
436398      évacuer  pi3S     ɛvaky     1
436440       évader  ii1S     ɛvadɛ     1
436831     éveiller  pi3S      ɛvɛj     1
436867     éveiller  ppMS     ɛvɛje     1
437301       éviter   inf     ɛvite     2
437328       éviter  ppMS     ɛvite     1
437474         être  pi2P        ɛt     9
437476         être   inf       ɛtʁ    16
437492         ôter  ai3S       ɔta     1
437512         ôter   inf       ɔte     1

[1941 rows x 4 columns]

0
CPU times: user 1min 9s, sys: 21.9 s, total: 1min 31s
Wall time: 32 s

nbChunk 42
4200
1944

             lexeme  case     phono  tir1
40            avoir  pi3S         a    94
113      abandonner  ii3S  abɑ̃dɔnɛ     1
128      abandonner  pi3S   abɑ̃dɔn     1
148      abandonner  pi2P  abɑ̃dɔne     1
259         abattre    pP    abatɑ̃     1
299         abattre   inf     abatʁ     1
1175        aborder  ppMS    abɔʁde     1
1421        aboutir  ps3S    abutis     1
1439        aboutir  ai3S     abuti     1
2971       accepter   inf   aksɛpte     2
3349     accommoder   inf   akɔmɔde     1
3400    accompagner  pi3S   akɔ̃paɲ     3
3527       accorder  pi1S     akɔʁd     1
3536       accorder   inf    akɔʁde     1
3884       accouder   inf     akude     1
4095       accourir  ppMP     akuʁy     1
4216     accoutumer  ppMP   akutyme     1
4259      accrocher   inf    akʁɔʃe     1
4291      accrocher  ppMS    akʁɔʃe     1
4510     accueillir  ai3P    akəjiʁ     1
4521     accueillir  pi1P    akəjɔ̃     1
4733        accuser  pi2S      akyz     1
5008       acharner  pi3S     aʃaʁn     1
5119        acheter   inf     aʃəte     1
5126        acheter  ii2P    aʃətje     1
5136        acheter  ppMS     aʃəte     2
5171        achever  ppMS     aʃəve     1
5311        acheter  pi3S      aʃɛt     2
5788     acquiescer  ai1S    akjɛsɛ     1
6863       admettre  pi1S      admɛ     1
...             ...   ...       ...   ...
432552     éprouver  pi3S     ɛpʁuv     1
432650      épuiser  pi1S     ɛpɥiz     1
433575       ériger  ii3P     ɛʁiʒɛ     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ     6
434070         être  ii3S       ɛtɛ    50
434488         être    pP      ɛtɑ̃     1
434727     éteindre    pP    ɛtɛɲɑ̃     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
435054         être  ii2P      ɛtje     3
435085    étinceler  pi3S   ɛtɛ̃sɛl     1
435172         être  ii1P     ɛtjɔ̃     5
435192    étiqueter   inf   ɛtikəte     1
435230    étiqueter  ppFP   ɛtikəte     1
435240       étirer  ii3P     ɛtiʁɛ     1
435244       étirer    pP    ɛtiʁɑ̃     1
435748    étrangler   inf  ɛtʁɑ̃gle     1
435780    étrangler  ppMS  ɛtʁɑ̃gle     1
436205      étudier   inf    ɛtydje     1
436316         être  ppMS       ɛte    16
436402      évacuer   inf    ɛvakye     1
436679     évanouir  pi3S    ɛvanui     1
437301       éviter   inf     ɛvite     1
437314       éviter  pi2S      ɛvit     1
437417      évoquer    pP    ɛvɔkɑ̃     1
437458      évoquer  ppMS     ɛvɔke     1
437474         être  pi2P        ɛt     8
437476         être   inf       ɛtʁ    20
437492         ôter  ai3S       ɔta     1

[1944 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 21.9 s, total: 1min 38s
Wall time: 32.8 s

nbChunk 43
4200
1968

             lexeme  case      phono  tir1
40            avoir  pi3S          a    71
52         abaisser    pP     abɛsɑ̃     1
132      abandonner   inf   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
1399        aboutir  pc3S    abutiʁɛ     1
2339         abuser   inf      abyze     1
2616         abîmer  ppMP      abime     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     2
2975       accepter  pc1S  aksɛptəʁɛ     1
2984       accepter  pi2S     aksɛpt     1
3003       accepter  ppMS    aksɛpte     2
3007       accepter  ppFP    aksɛpte     1
3380    accompagner  ai3S   akɔ̃paɲa     1
3397    accompagner  pi1S    akɔ̃paɲ     1
3536       accorder   inf     akɔʁde     1
3571       accorder  ppMS     akɔʁde     1
3683       accoster  ppFS     akɔste     1
3827      accoucher   inf      akuʃe     1
4230      accrocher  ai3S     akʁɔʃa     1
4238      accrocher    pP    akʁɔʃɑ̃     1
4259      accrocher   inf     akʁɔʃe     1
4509     accueillir   inf     akəjiʁ     1
5119        acheter   inf      aʃəte     3
5125        acheter  pi2P      aʃəte     1
5136        acheter  ppMS      aʃəte     1
5171        achever  ppMS      aʃəve     1
5311        acheter  pi3S       aʃɛt     1
5331        achever  pI2S       aʃɛv     1
5332        achever  pi3S       aʃɛv     1
...             ...   ...        ...   ...
433912      établir  ppMS     ɛtabli     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    13
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    83
434299       étaler  ppMS      ɛtale     1
434300       étaler  ppFS      ɛtale     1
434451     étancher   inf     ɛtɑ̃ʃe     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
434833      étendre  ppFS     ɛtɑ̃dy     1
434923     éternuer   inf    ɛtɛʁnye     1
435172         être  ii1P      ɛtjɔ̃     1
435438      étonner  pi3S       ɛtɔn     1
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435471      étonner  ppMS      ɛtɔne     1
435731    étrangler  ii3S   ɛtʁɑ̃glɛ     1
435838    étreindre  pi3S      ɛtʁɛ̃     2
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    11
436835     éveiller   inf      ɛvɛje     1
437282       éviter  ii1S      ɛvitɛ     1
437301       éviter   inf      ɛvite     3
437302       éviter  fi3S    ɛvitəʁa     1
437424      évoquer  pi1S       ɛvɔk     1
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    22
437505         ôter  pi1S         ot     1
437518         ôter  pc3S      ɔtəʁɛ     1

[1968 rows x 4 columns]

0
CPU times: user 1min 8s, sys: 20.7 s, total: 1min 29s
Wall time: 31.1 s

nbChunk 44
4200
1875

             lexeme  case      phono  tir1
40            avoir  pi3S          a    76
67         abaisser  pi3S       abɛs     1
128      abandonner  pi3S    abɑ̃dɔn     1
170      abandonner  ppMP   abɑ̃dɔne     1
313         abattre  ppMP      abaty     1
1011        abonder  ppMS     abɔ̃de     1
1175        aborder  ppMS     abɔʁde     1
1388        aboutir  ppMS      abuti     1
1415        aboutir  ii3S    abutisɛ     1
1681        abriter  pi1S      abʁit     1
1688        abriter   inf     abʁite     1
2355         abuser  pi2P      abyze     1
2964       accepter  pi1S     aksɛpt     1
2971       accepter   inf    aksɛpte     2
2972       accepter  fi3S  aksɛptəʁa     1
2977       accepter  pc3S  aksɛptəʁɛ     1
3005       accepter  ppFS    aksɛpte     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3406    accompagner   inf   akɔ̃paɲe     1
3434    accompagner  ppFS   akɔ̃paɲe     2
3556       accorder  pi2P     akɔʁde     1
3692        accoter    pP     akɔtɑ̃     1
4320      accroupir  ppMS     akʁupi     1
4381      accroître   inf    akʁwatʁ     1
4503     accueillir  ppFS      akəji     1
5068      acheminer  pi3P     aʃəmin     1
5119        acheter   inf      aʃəte     3
5136        acheter  ppMS      aʃəte     1
5311        acheter  pi3S       aʃɛt     1
6043      actionner  ppMS    aksjɔne     1
...             ...   ...        ...   ...
430616   éparpiller   inf   ɛpaʁpije     1
431992      éponger   inf     ɛpɔ̃ʒe     1
432167      épouser  fi2S    ɛpuzəʁa     1
432532     éprouver  ai3S     ɛpʁuva     1
433912      établir  ppMS     ɛtabli     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    11
434070         être  ii3S        ɛtɛ    77
434147       étaler  pi3S       ɛtal     1
434770     éteindre  pi2S       ɛtɛ̃     1
434868    éterniser   inf   ɛtɛʁnize     1
434950     éternuer  ppMS    ɛtɛʁnye     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     3
435417      étonner  ai3S      ɛtɔna     1
435438      étonner  pi3S       ɛtɔn     1
436203      étudier  pi3P      ɛtydi     1
436205      étudier   inf     ɛtydje     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    24
436520      évaluer   inf     ɛvalye     1
436629     évanouir  ppFS     ɛvanui     1
436867     éveiller  ppMS      ɛvɛje     1
437284       éviter  ii3S      ɛvitɛ     1
437285       éviter    pP     ɛvitɑ̃     1
437292       éviter  pi1S       ɛvit     1
437301       éviter   inf      ɛvite     1
437474         être  pi2P         ɛt    11
437476         être   inf        ɛtʁ    26

[1875 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 21.1 s, total: 1min 33s
Wall time: 31.8 s

nbChunk 45
4200
1919

            lexeme  case       phono  tir1
40           avoir  pi3S           a    84
113     abandonner  ii3S    abɑ̃dɔnɛ     1
125     abandonner  pi1S     abɑ̃dɔn     1
128     abandonner  pi3S     abɑ̃dɔn     1
135     abandonner  pc3P  abɑ̃dɔnəʁɛ     1
313        abattre  ppMP       abaty     1
883         aboyer  pi2S        abwa     1
1950      absenter   inf     absɑ̃te     1
2143      abstenir   inf    abstəniʁ     1
2616        abîmer  ppMP       abime     1
2971      accepter   inf     aksɛpte     3
3003      accepter  ppMS     aksɛpte     2
3322    accommoder  ii3S     akɔmɔdɛ     1
3438     accomplir  ppMS     akɔ̃pli     1
3555      accorder  pI2P      akɔʁde     1
3818     accoucher  pi1S        akuʃ     1
4001     accoupler  ppFS      akuple     1
4626       acculer  ppMS       akyle     1
4685     accumuler  ppFP     akymyle     1
4716       accuser  pi3S        akyz     1
4771       accéder  ii3S      aksɛdɛ     1
5119       acheter   inf       aʃəte     2
6016     actionner   inf     aksjɔne     1
6996       admirer   inf      admiʁe     1
7069    admonester  pi3S    admɔnɛst     1
7294        adorer  ii3P       adɔʁɛ     1
7312        adorer  pi3S        adɔʁ     3
7523      adresser  ii3S      adʁɛsɛ     1
7532      adresser  pi1S       adʁɛs     1
8464      affermir  ppMS      afɛʁmi     1
...            ...   ...         ...   ...
432691     épuiser  ppFS      ɛpɥize     1
433199  équivaloir  pi3P      ɛkival     1
433778     éructer    pP     ɛʁyktɑ̃     1
433922     établir   inf     ɛtabliʁ     1
434048        être  ii3P         ɛtɛ     5
434068        être  ii1S         ɛtɛ    15
434069        être  ii2S         ɛtɛ     1
434070        être  ii3S         ɛtɛ    75
434302      étaler  ppMP       ɛtale     1
434772    éteindre  ppMS        ɛtɛ̃     1
434773    éteindre  pi3S        ɛtɛ̃     1
434868   éterniser   inf    ɛtɛʁnize     1
435054        être  ii2P        ɛtje     2
435172        être  ii1P       ɛtjɔ̃     2
435192   étiqueter   inf     ɛtikəte     1
435417     étonner  ai3S       ɛtɔna     1
435422     étonner  ii3S       ɛtɔnɛ     2
436316        être  ppMS         ɛte    17
436831    éveiller  pi3S        ɛvɛj     1
436833    éveiller  pi3P        ɛvɛj     1
436835    éveiller   inf       ɛvɛje     1
436871    éveiller  ppFP       ɛvɛje     1
437284      éviter  ii3S       ɛvitɛ     1
437285      éviter    pP      ɛvitɑ̃     1
437416     évoquer  ii3S       ɛvɔkɛ     1
437474        être  pi2P          ɛt    15
437476        être   inf         ɛtʁ    17
437492        ôter  ai3S         ɔta     1
437505        ôter  pi1S          ot     1
437512        ôter   inf         ɔte     1

[1919 rows x 4 columns]

0
CPU times: user 1min 3s, sys: 23.1 s, total: 1min 26s
Wall time: 34.4 s

nbChunk 46
4200
1962

             lexeme  case     phono  tir1
40            avoir  pi3S         a    75
108      abandonner  ai3S  abɑ̃dɔna     1
164      abandonner  ppMS  abɑ̃dɔne     2
168      abandonner  ppFP  abɑ̃dɔne     1
259         abattre    pP    abatɑ̃     1
291         abattre  pi1P    abatɔ̃     1
890          abolir   inf    abɔliʁ     1
1393        aboutir   inf    abutiʁ     1
1688        abriter   inf    abʁite     1
1822        abrutir  ii3P  abʁytisɛ     1
2106       absorber  ppMP   absɔʁbe     1
2324         abuser  ii3S     abyzɛ     1
2736       accabler   inf    akable     1
2939       accepter  ai3S   aksɛpta     1
2967       accepter  pi3S    aksɛpt     1
2971       accepter   inf   aksɛpte     2
3003       accepter  ppMS   aksɛpte     2
3382    accompagner  ii3P  akɔ̃paɲɛ     1
3406    accompagner   inf  akɔ̃paɲe     3
3443      accomplir   inf  akɔ̃pliʁ     2
3530       accorder  pi3S     akɔʁd     1
3549       accorder  pi2S     akɔʁd     1
3571       accorder  ppMS    akɔʁde     1
3863       accouder  ai1S     akudɛ     1
4210     accoutumer  ppMS   akutyme     1
4291      accrocher  ppMS    akʁɔʃe     1
4473     accueillir  ii3S     akəjɛ     1
4812      accélérer  pi3S   aksɛlɛʁ     1
4997       acharner  ii3S    aʃaʁnɛ     1
5119        acheter   inf     aʃəte     5
...             ...   ...       ...   ...
431857     éplucher    pP   ɛplyʃɑ̃     1
432164      épouser  pc1S   ɛpuzəʁɛ     1
432173      épouser  pi2S      ɛpuz     1
432552     éprouver  pi3S     ɛpʁuv     1
432556     éprouver   inf    ɛpʁuve     1
432689      épuiser  ppMS    ɛpɥize     1
434048         être  ii3P       ɛtɛ     1
434068         être  ii1S       ɛtɛ    19
434070         être  ii3S       ɛtɛ    78
434773     éteindre  pi3S      ɛtɛ̃     1
434782      étendre  pi3S      ɛtɑ̃     1
434811      étendre  ai3S    ɛtɑ̃di     1
434821      étendre   inf    ɛtɑ̃dʁ     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     3
435425      étonner    pP    ɛtɔnɑ̃     1
435542     étouffer  ppFP     ɛtufe     1
436316         être  ppMS       ɛte    15
436457       évader   inf     ɛvade     1
436815     éveiller  ai3S     ɛvɛja     1
436835     éveiller   inf     ɛvɛje     1
436867     éveiller  ppMS     ɛvɛje     1
437099       évider  ai3S     ɛvida     1
437292       éviter  pi1S      ɛvit     1
437301       éviter   inf     ɛvite     2
437367      évoluer   inf    ɛvɔlye     1
437417      évoquer    pP    ɛvɔkɑ̃     1
437474         être  pi2P        ɛt     9
437476         être   inf       ɛtʁ    15
437508         ôter  pi3S        ot     1

[1962 rows x 4 columns]

0
CPU times: user 1min 4s, sys: 22.8 s, total: 1min 26s
Wall time: 32.6 s

nbChunk 47
4200
1924

             lexeme  case     phono  tir1
40            avoir  pi3S         a    71
52         abaisser    pP    abɛsɑ̃     1
299         abattre   inf     abatʁ     1
307         abattre  ppFS     abaty     1
914          abolir    pP  abɔlisɑ̃     1
1686        abriter  pi3P     abʁit     1
2051       absorber  ii3S   absɔʁbɛ     1
2339         abuser   inf     abyze     1
2887      accentuer  ii3S  aksɑ̃tyɛ     1
3117       acclamer   inf    aklame     1
3400    accompagner  pi3S   akɔ̃paɲ     2
3433    accompagner  ppMS  akɔ̃paɲe     1
3443      accomplir   inf  akɔ̃pliʁ     1
3556       accorder  pi2P    akɔʁde     1
3571       accorder  ppMS    akɔʁde     1
3655       accoster   inf    akɔste     1
4259      accrocher   inf    akʁɔʃe     1
4720        accuser   inf     akyze     1
4812      accélérer  pi3S   aksɛlɛʁ     1
5008       acharner  pi3S     aʃaʁn     1
5112        acheter    pP    aʃətɑ̃     1
5119        acheter   inf     aʃəte     1
5157        achever   inf     aʃəve     1
5325        acheter  fi1P  aʃɛtəʁɔ̃     1
5988      actionner  ai3S   aksjɔna     1
6891       admettre   inf    admɛtʁ     2
6959        admirer  ai3S    admiʁa     1
7176        adonner  ii3S     adɔnɛ     1
7222        adopter  ai3S    adɔpta     1
7297         adorer  ii3S     adɔʁɛ     2
...             ...   ...       ...   ...
427668     éloigner  ppMS    ɛlwaɲe     1
428248       émaner  pi3S      ɛman     1
428410      émerger  pi3P     ɛmɛʁʒ     1
428650     émouvoir  pi3S       ɛmø     1
429349     émouvoir   inf   ɛmuvwaʁ     1
430340     épancher   inf    ɛpɑ̃ʃe     1
430558     épargner  pi3S     ɛpaʁɲ     1
431992      éponger   inf    ɛpɔ̃ʒe     1
432537     éprouver  ii3S    ɛpʁuvɛ     1
432549     éprouver  pi1S     ɛpʁuv     1
432676      épuiser  pI2P    ɛpɥize     1
433912      établir  ppMS    ɛtabli     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    11
434070         être  ii3S       ɛtɛ    69
434762     éteindre   inf    ɛtɛ̃dʁ     1
434866    éterniser  pi3P   ɛtɛʁniz     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     1
435254       étirer  pi3S      ɛtiʁ     1
435418      étonner  ai1S     ɛtɔnɛ     1
435435      étonner  pi1S      ɛtɔn     2
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    31
436418      évacuer  pi2P    ɛvakye     1
436629     évanouir  ppFS    ɛvanui     1
437301       éviter   inf     ɛvite     5
437431      évoquer   inf     ɛvɔke     1
437474         être  pi2P        ɛt    16
437476         être   inf       ɛtʁ    19

[1924 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.2 s, total: 1min 34s
Wall time: 32 s

nbChunk 48
4200
1921

             lexeme  case       phono  tir1
40            avoir  pi3S           a    80
128      abandonner  pi3S     abɑ̃dɔn     2
132      abandonner   inf    abɑ̃dɔne     1
162      abandonner  ai3P   abɑ̃dɔnɛʁ     1
164      abandonner  ppMS    abɑ̃dɔne     1
313         abattre  ppMP       abaty     1
1681        abriter  pi1S       abʁit     1
2116       absoudre   inf      absudʁ     1
2610         abîmer  ppMS       abime     1
2967       accepter  pi3S      aksɛpt     2
2969       accepter  pi3P      aksɛpt     1
2971       accepter   inf     aksɛpte     2
2972       accepter  fi3S   aksɛptəʁa     1
2983       accepter  fi3P  aksɛptəʁɔ̃     1
3349     accommoder   inf     akɔmɔde     1
3380    accompagner  ai3S    akɔ̃paɲa     1
3382    accompagner  ii3P    akɔ̃paɲɛ     1
3406    accompagner   inf    akɔ̃paɲe     1
3436    accompagner  ppMP    akɔ̃paɲe     1
3443      accomplir   inf    akɔ̃pliʁ     1
3468      accomplir    pP  akɔ̃plisɑ̃     1
3490      accomplir  pi3S     akɔ̃pli     1
3530       accorder  pi3S       akɔʁd     1
3536       accorder   inf      akɔʁde     1
3556       accorder  pi2P      akɔʁde     1
4479     accueillir  pi1S        akœj     1
4509     accueillir   inf      akəjiʁ     1
4688        accuser  ai3S       akyza     1
4823      accélérer  ii3S    aksɛlɛʁɛ     1
5005       acharner  pi1S       aʃaʁn     1
...             ...   ...         ...   ...
431971      éponger  pi3S       ɛpɔ̃ʒ     1
431980      éponger  ii3S      ɛpɔ̃ʒɛ     1
432144      épouser  ii3S       ɛpuzɛ     2
432556     éprouver   inf      ɛpʁuve     2
433912      établir  ppMS      ɛtabli     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ    14
434070         être  ii3S         ɛtɛ    61
434131       étaler  ii3P       ɛtalɛ     1
434147       étaler  pi3S        ɛtal     1
434773     éteindre  pi3S        ɛtɛ̃     1
434775     éteindre  ppFS       ɛtɛ̃t     1
434782      étendre  pi3S        ɛtɑ̃     1
434811      étendre  ai3S      ɛtɑ̃di     1
434831      étendre  ppMS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     2
435417      étonner  ai3S       ɛtɔna     1
435500     étouffer  pi3S        ɛtuf     1
435506     étouffer   inf       ɛtufe     1
435540     étouffer  ppFS       ɛtufe     1
436316         être  ppMS         ɛte    18
436430      évacuer  ppMS      ɛvakye     1
436664     évanouir  pi3P     ɛvanuis     1
437049     évertuer  ii3S     ɛvɛʁtyɛ     1
437301       éviter   inf       ɛvite     3
437353      évoluer    pP     ɛvɔlyɑ̃     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    17
437539         ôter  ppMS         ɔte     1

[1921 rows x 4 columns]

0
CPU times: user 1min 2s, sys: 23.5 s, total: 1min 26s
Wall time: 33.6 s

nbChunk 49
4200
1931

             lexeme  case      phono  tir1
40            avoir  pi3S          a    82
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     2
299         abattre   inf      abatʁ     1
1460         aboyer  ii3S     abwajɛ     1
1821        abrutir  pi2S     abʁyti     1
2967       accepter  pi3S     aksɛpt     1
2973       accepter  fi1S  aksɛptəʁɛ     1
2997       accepter  pi1P   aksɛptɔ̃     1
3003       accepter  ppMS    aksɛpte     1
3320     accommoder  ii1S    akɔmɔdɛ     1
3422    accompagner  pi2P   akɔ̃paɲe     1
3438      accomplir  ppMS    akɔ̃pli     1
3443      accomplir   inf   akɔ̃pliʁ     1
3460      accomplir  pi1S    akɔ̃pli     1
3480      accomplir  pi2P  akɔ̃plise     1
3738        accoter  ppFS      akɔte     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4255      accrocher  pi3S      akʁɔʃ     1
4292      accrocher  ppFS     akʁɔʃe     1
4294      accrocher  ppMP     akʁɔʃe     1
4509     accueillir   inf     akəjiʁ     1
4759        accéder  ps3S      aksɛd     1
5136        acheter  ppMS      aʃəte     2
5157        achever   inf      aʃəve     1
5171        achever  ppMS      aʃəve     1
5311        acheter  pi3S       aʃɛt     2
5905       acquérir   inf     akɛʁiʁ     1
6067        activer  pi3S      aktiv     1
6410        adapter  pi3S      adapt     1
...             ...   ...        ...   ...
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    12
434070         être  ii3S        ɛtɛ    65
434131       étaler  ii3P      ɛtalɛ     1
434451     étancher   inf     ɛtɑ̃ʃe     1
434488         être    pP       ɛtɑ̃     1
434729     éteindre  ps3S       ɛtɛɲ     1
434782      étendre  pi3S       ɛtɑ̃     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     2
435254       étirer  pi3S       ɛtiʁ     1
435444      étonner   inf      ɛtɔne     1
435506     étouffer   inf      ɛtufe     1
436233      étudier  ppMS     ɛtydje     2
436316         être  ppMS        ɛte    21
436835     éveiller   inf      ɛvɛje     1
436873     éveiller  ppMP      ɛvɛje     1
437198      évincer  ppMS     ɛvɛ̃se     1
437273       éviter  ai3S      ɛvita     1
437301       éviter   inf      ɛvite     1
437314       éviter  pi2S       ɛvit     1
437328       éviter  ppMS      ɛvite     1
437352      évoluer  ii3S     ɛvɔlyɛ     1
437416      évoquer  ii3S      ɛvɔkɛ     1
437427      évoquer  pi3S       ɛvɔk     1
437437      évoquer  pc3S    ɛvɔkəʁɛ     1
437474         être  pi2P         ɛt    18
437476         être   inf        ɛtʁ    28
437539         ôter  ppMS        ɔte     1

[1931 rows x 4 columns]

0
CPU times: user 1min 10s, sys: 21.6 s, total: 1min 32s
Wall time: 33.6 s

nbChunk 50
4200
1939

             lexeme  case       phono  tir1
40            avoir  pi3S           a    79
132      abandonner   inf    abɑ̃dɔne     2
164      abandonner  ppMS    abɑ̃dɔne     2
259         abattre    pP      abatɑ̃     1
300         abattre  fi2P      abatʁe     1
1147        aborder   inf      abɔʁde     1
1468         aboyer   inf      abwaje     1
1798        abrutir  ppFS      abʁyti     1
2155       abstenir  ppFS     abstəny     1
2763       accabler  ppMS      akable     1
2785      accaparer  pi3S      akapaʁ     1
2904      accentuer   inf    aksɑ̃tye     1
2939       accepter  ai3S     aksɛpta     1
2967       accepter  pi3S      aksɛpt     1
3003       accepter  ppMS     aksɛpte     1
3314        accoler  ppFS       akɔle     1
3536       accorder   inf      akɔʁde     1
3549       accorder  pi2S       akɔʁd     1
4210     accoutumer  ppMS     akutyme     1
4291      accrocher  ppMS      akʁɔʃe     1
4812      accélérer  pi3S     aksɛlɛʁ     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     1
5167        achever  is3S       aʃəva     1
5311        acheter  pi3S        aʃɛt     1
5332        achever  pi3S        aʃɛv     1
5343        achever  pc3S     aʃɛvəʁɛ     1
6958    administrer  ppMP  administʁe     1
7312         adorer  pi3S        adɔʁ     2
7315         adorer  ps3P        adɔʁ     1
...             ...   ...         ...   ...
432302      épouser  ppMS       ɛpuze     1
432390   épouvanter  pi3P     ɛpuvɑ̃t     1
432556     éprouver   inf      ɛpʁuve     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    13
434070         être  ii3S         ɛtɛ    72
434151       étaler  pi3P        ɛtal     1
434153       étaler   inf       ɛtale     1
434488         être    pP        ɛtɑ̃     1
434727     éteindre    pP      ɛtɛɲɑ̃     1
434747     éteindre  ai3S       ɛtɛɲi     1
434772     éteindre  ppMS        ɛtɛ̃     1
434831      étendre  ppMS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     1
435064    étinceler    pP   ɛtɛ̃səlɑ̃     1
435172         être  ii1P       ɛtjɔ̃     5
436316         être  ppMS         ɛte    16
436520      évaluer   inf      ɛvalye     1
436629     évanouir  ppFS      ɛvanui     1
436632     évanouir   inf     ɛvanuiʁ     1
436815     éveiller  ai3S       ɛvɛja     1
437047     évertuer  ii1S     ɛvɛʁtyɛ     1
437285       éviter    pP      ɛvitɑ̃     1
437292       éviter  pi1S        ɛvit     1
437301       éviter   inf       ɛvite     1
437427      évoquer  pi3S        ɛvɔk     1
437431      évoquer   inf       ɛvɔke     1
437474         être  pi2P          ɛt    16
437476         être   inf         ɛtʁ    20
437492         ôter  ai3S         ɔta     1

[1939 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 23.7 s, total: 1min 36s
Wall time: 31.4 s

nbChunk 51
4200
1958

             lexeme  case      phono  tir1
40            avoir  pi3S          a    89
111      abandonner  ii1S   abɑ̃dɔnɛ     1
128      abandonner  pi3S    abɑ̃dɔn     1
164      abandonner  ppMS   abɑ̃dɔne     1
255         abattre  ii3P      abatɛ     1
1121        aborder  ai3S     abɔʁda     1
1147        aborder   inf     abɔʁde     1
1688        abriter   inf     abʁite     1
1856        abréger  pi1S      abʁɛʒ     1
2070       absorber   inf    absɔʁbe     1
2973       accepter  fi1S  aksɛptəʁɛ     1
2978       accepter  fi2S  aksɛptəʁa     1
3349     accommoder   inf    akɔmɔde     1
3406    accompagner   inf   akɔ̃paɲe     1
3434    accompagner  ppFS   akɔ̃paɲe     1
3438      accomplir  ppMS    akɔ̃pli     1
3443      accomplir   inf   akɔ̃pliʁ     2
3530       accorder  pi3S      akɔʁd     1
3571       accorder  ppMS     akɔʁde     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4255      accrocher  pi3S      akʁɔʃ     1
4292      accrocher  ppFS     akʁɔʃe     1
4320      accroupir  ppMS     akʁupi     1
4684      accumuler  ppFS    akymyle     1
4720        accuser   inf      akyze     1
4835      accélérer   inf   aksɛlɛʁe     1
5053      acheminer  ii3S    aʃəminɛ     1
5119        acheter   inf      aʃəte     2
5173        achever  ppFS      aʃəve     1
5316        acheter  fi1S    aʃɛtəʁɛ     1
...             ...   ...        ...   ...
432532     éprouver  ai3S     ɛpʁuva     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
432549     éprouver  pi1S      ɛpʁuv     1
432586     éprouver  ppMS     ɛpʁuve     1
433579       ériger    pP     ɛʁiʒɑ̃     1
434048         être  ii3P        ɛtɛ     7
434068         être  ii1S        ɛtɛ    13
434070         être  ii3S        ɛtɛ    74
434134       étaler  ii3S      ɛtalɛ     1
434147       étaler  pi3S       ɛtal     1
434770     éteindre  pi2S       ɛtɛ̃     1
434775     éteindre  ppFS      ɛtɛ̃t     1
434803      étendre  ai3P    ɛtɑ̃diʁ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     4
435295       étirer  ppFP      ɛtiʁe     1
435445      étonner  fi3S    ɛtɔnəʁa     1
435500     étouffer  pi3S       ɛtuf     1
435732    étrangler    pP  ɛtʁɑ̃glɑ̃     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
436201      étudier  pi3S      ɛtydi     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    27
436818     éveiller  ii1S      ɛvɛjɛ     1
437301       éviter   inf      ɛvite     2
437416      évoquer  ii3S      ɛvɔkɛ     1
437474         être  pi2P         ɛt     7
437476         être   inf        ɛtʁ    20
437497         ôter  ii3S        ɔtɛ     1

[1958 rows x 4 columns]

0
CPU times: user 1min 11s, sys: 23 s, total: 1min 34s
Wall time: 30.3 s

nbChunk 52
4200
1944

             lexeme  case       phono  tir1
40            avoir  pi3S           a    70
109      abandonner  ai1S    abɑ̃dɔnɛ     1
136      abandonner  pc1S  abɑ̃dɔnəʁɛ     1
166      abandonner  ppFS    abɑ̃dɔne     1
305         abattre  ppMS       abaty     1
865          aboyer  pi3S        abwa     1
2566         abîmer    pP      abimɑ̃     1
2964       accepter  pi1S      aksɛpt     1
2971       accepter   inf     aksɛpte     3
2988       accepter  pI2P     aksɛpte     1
3005       accepter  ppFS     aksɛpte     1
3316        accoler  ppMP       akɔle     1
3322     accommoder  ii3S     akɔmɔdɛ     1
3406    accompagner   inf    akɔ̃paɲe     2
3433    accompagner  ppMS    akɔ̃paɲe     1
3530       accorder  pi3S       akɔʁd     2
3536       accorder   inf      akɔʁde     1
4252      accrocher  pi1S       akʁɔʃ     1
4294      accrocher  ppMP      akʁɔʃe     1
4369      accroupir  pi3S      akʁupi     1
4509     accueillir   inf      akəjiʁ     1
4688        accuser  ai3S       akyza     1
4748        accuser  ppMS       akyze     1
5119        acheter   inf       aʃəte     2
5125        acheter  pi2P       aʃəte     1
5136        acheter  ppMS       aʃəte     1
5171        achever  ppMS       aʃəve     1
5311        acheter  pi3S        aʃɛt     1
6863       admettre  pi1S        admɛ     1
7295         adorer  ii1S       adɔʁɛ     1
...             ...   ...         ...   ...
432689      épuiser  ppMS      ɛpɥize     2
433772      éructer  ai3S      ɛʁykta     1
433912      établir  ppMS      ɛtabli     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ    10
434069         être  ii2S         ɛtɛ     1
434070         être  ii3S         ɛtɛ    71
434768     éteindre  pi1S        ɛtɛ̃     1
434782      étendre  pi3S        ɛtɑ̃     1
434804      étendre  ai1S      ɛtɑ̃di     1
434831      étendre  ppMS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     2
435486     étouffer    pP      ɛtufɑ̃     1
435506     étouffer   inf       ɛtufe     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436002      étriper  ppMP      ɛtʁipe     1
436198      étudier  pi1S       ɛtydi     1
436221      étudier  pi2P      ɛtydje     1
436316         être  ppMS         ɛte    30
436485       évader  ppFS       ɛvade     1
436516      évaluer  pi3S       ɛvaly     1
437301       éviter   inf       ɛvite     1
437302       éviter  fi3S     ɛvitəʁa     1
437352      évoluer  ii3S      ɛvɔlyɛ     1
437427      évoquer  pi3S        ɛvɔk     1
437474         être  pi2P          ɛt    14
437476         être   inf         ɛtʁ    22
437508         ôter  pi3S          ot     1

[1944 rows x 4 columns]

0
CPU times: user 1min 11s, sys: 22.8 s, total: 1min 34s
Wall time: 30.1 s

nbChunk 53
4200
1930

             lexeme  case     phono  tir1
40            avoir  pi3S         a   109
67         abaisser  pi3S      abɛs     1
132      abandonner   inf  abɑ̃dɔne     1
166      abandonner  ppFS  abɑ̃dɔne     1
170      abandonner  ppMP  abɑ̃dɔne     1
1174        aborder  ai3P   abɔʁdɛʁ     1
1461         aboyer    pP   abwajɑ̃     1
1673        abriter  ii3S    abʁitɛ     1
2339         abuser   inf     abyze     2
2612         abîmer  ppFS     abime     1
2971       accepter   inf   aksɛpte     3
3003       accepter  ppMS   aksɛpte     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     1
3536       accorder   inf    akɔʁde     1
3805      accoucher  ai3S     akuʃa     2
4252      accrocher  pi1S     akʁɔʃ     1
4279      accrocher  pI2P    akʁɔʃe     1
4290      accrocher  ai3P   akʁɔʃɛʁ     1
4509     accueillir   inf    akəjiʁ     1
4510     accueillir  ai3P    akəjiʁ     1
4997       acharner  ii3S    aʃaʁnɛ     1
5041       acharner  ppMS    aʃaʁne     1
5119        acheter   inf     aʃəte     3
5136        acheter  ppMS     aʃəte     1
5755     acquiescer  pi1S     akjɛs     1
6891       admettre   inf    admɛtʁ     2
7316         adorer   inf     adɔʁe     1
7518       adresser  ai3S    adʁɛsa     1
7539       adresser   inf    adʁɛse     2
...             ...   ...       ...   ...
432302      épouser  ppMS     ɛpuze     1
432303      épouser  ppFS     ɛpuze     1
432590     éprouver  ppFP    ɛpʁuve     1
432689      épuiser  ppMS    ɛpɥize     1
433912      établir  ppMS    ɛtabli     1
433969      établir  pi3S    ɛtabli     1
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ    13
434070         être  ii3S       ɛtɛ    71
434131       étaler  ii3P     ɛtalɛ     1
434692       étayer   inf     ɛtɛje     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
434785      étendre  ii3P    ɛtɑ̃dɛ     1
435054         être  ii2P      ɛtje     1
435074    étinceler   inf  ɛtɛ̃səle     1
435135      étioler   inf    ɛtjɔle     1
435172         être  ii1P     ɛtjɔ̃     3
435232       étirer  ai3S     ɛtiʁa     1
435243       étirer  ii3S     ɛtiʁɛ     1
435448      étonner  pc1S   ɛtɔnəʁɛ     1
435726    étrangler  ai3S  ɛtʁɑ̃gla     1
435742    étrangler  pi3S   ɛtʁɑ̃gl     1
435780    étrangler  ppMS  ɛtʁɑ̃gle     1
436316         être  ppMS       ɛte    26
436520      évaluer   inf    ɛvalye     1
436709     évaporer  pi3P    ɛvapɔʁ     1
437301       éviter   inf     ɛvite     2
437474         être  pi2P        ɛt    13
437476         être   inf       ɛtʁ    21
437512         ôter   inf       ɔte     1

[1930 rows x 4 columns]

0
CPU times: user 1min 7s, sys: 21.4 s, total: 1min 29s
Wall time: 30.2 s

nbChunk 54
4200
1938

             lexeme  case       phono  tir1
40            avoir  pi3S           a    86
128      abandonner  pi3S     abɑ̃dɔn     1
164      abandonner  ppMS    abɑ̃dɔne     1
299         abattre   inf       abatʁ     1
305         abattre  ppMS       abaty     1
1178        aborder  ppMP      abɔʁde     1
1307        abouler  pi3S        abul     1
1354        abouter  ii3S       abutɛ     1
1406        aboutir  fi3P    abutiʁɔ̃     1
2791      accaparer   inf     akapaʁe     1
2888      accentuer    pP   aksɑ̃tyɑ̃     1
2971       accepter   inf     aksɛpte     1
2984       accepter  pi2S      aksɛpt     1
3003       accepter  ppMS     aksɛpte     1
3406    accompagner   inf    akɔ̃paɲe     1
4323      accroupir   inf     akʁupiʁ     1
4716        accuser  pi3S        akyz     1
4748        accuser  ppMS       akyze     1
5119        acheter   inf       aʃəte     3
5140        achever  ai3S       aʃəva     1
5311        acheter  pi3S        aʃɛt     1
5807       acquérir  ppMS         aki     1
7028       admettre  ppMS        admi     1
7233        adopter    pP     adɔptɑ̃     1
7250        adopter   inf      adɔpte     1
7312         adorer  pi3S        adɔʁ     2
7523       adresser  ii3S      adʁɛsɛ     1
7524       adresser    pP     adʁɛsɑ̃     1
7568       adresser  ppFS      adʁɛse     1
8554       afficher   inf       afiʃe     1
...             ...   ...         ...   ...
428608  émerveiller  ppMP    ɛmɛʁvɛje     1
429691      énerver  pi1S       ɛnɛʁv     1
430579     épargner  pi2P      ɛpaʁɲe     1
432160      épouser   inf       ɛpuze     2
432519     éprendre  ppMS        ɛpʁi     1
434004       étager  pi3P        ɛtaʒ     1
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    68
434134       étaler  ii3S       ɛtalɛ     1
434723     éteindre  ii3P       ɛtɛɲɛ     1
434747     éteindre  ai3S       ɛtɛɲi     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434821      étendre   inf      ɛtɑ̃dʁ     1
434907     éternuer    pP    ɛtɛʁnyɑ̃     1
435500     étouffer  pi3S        ɛtuf     1
436205      étudier   inf      ɛtydje     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    25
436520      évaluer   inf      ɛvalye     1
436629     évanouir  ppFS      ɛvanui     1
436711     évaporer   inf     ɛvapɔʁe     1
436723     évaporer  fi3P  ɛvapɔʁəʁɔ̃     1
436869     éveiller  ppFS       ɛvɛje     1
437301       éviter   inf       ɛvite     3
437304       éviter  pc3P     ɛvitəʁɛ     1
437314       éviter  pi2S        ɛvit     1
437367      évoluer   inf      ɛvɔlye     2
437474         être  pi2P          ɛt    14
437476         être   inf         ɛtʁ    19

[1938 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 23.4 s, total: 1min 35s
Wall time: 31 s

nbChunk 55
4200
1962

             lexeme  case     phono  tir1
40            avoir  pi3S         a    86
132      abandonner   inf  abɑ̃dɔne     2
164      abandonner  ppMS  abɑ̃dɔne     1
166      abandonner  ppFS  abɑ̃dɔne     1
299         abattre   inf     abatʁ     1
977         abonder  pi1S     abɔ̃d     1
1673        abriter  ii3S    abʁitɛ     1
2100       absorber  ppMS   absɔʁbe     1
2713       accabler  ii1S    akablɛ     1
2763       accabler  ppMS    akable     1
2971       accepter   inf   aksɛpte     1
3003       accepter  ppMS   aksɛpte     1
3380    accompagner  ai3S  akɔ̃paɲa     1
3385    accompagner  ii3S  akɔ̃paɲɛ     1
3519       accorder  ii3S    akɔʁdɛ     1
3536       accorder   inf    akɔʁde     2
3571       accorder  ppMS    akɔʁde     1
3682       accoster  ppMS    akɔste     1
4162     accoutumer  ii3P   akutymɛ     1
4294      accrocher  ppMP    akʁɔʃe     1
4509     accueillir   inf    akəjiʁ     2
4748        accuser  ppMS     akyze     1
5102        acheter  ai3S     aʃəta     1
5119        acheter   inf     aʃəte     4
5136        acheter  ppMS     aʃəte     1
5313        acheter  pi3P      aʃɛt     1
6865       admettre  pi2S      admɛ     1
6891       admettre   inf    admɛtʁ     1
6959        admirer  ai3S    admiʁa     1
7250        adopter   inf    adɔpte     1
...             ...   ...       ...   ...
428561  émerveiller  ii3S  ɛmɛʁvɛjɛ     1
428609      émettre  pi3S       ɛmɛ     1
429275     émousser  ppMS     ɛmuse     1
430682       épater  pi3S      ɛpat     1
431856     éplucher  ii3S    ɛplyʃɛ     1
431871     éplucher   inf    ɛplyʃe     1
432160      épouser   inf     ɛpuze     2
433063   équilibrer  ppFS  ɛkilibʁe     1
433170      équiper  ppFS     ɛkipe     1
433590       ériger   inf     ɛʁiʒe     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    13
434070         être  ii3S       ɛtɛ    68
434739     éteindre  ai3P    ɛtɛɲiʁ     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
434768     éteindre  pi1S      ɛtɛ̃     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     1
435375      étoiler  pi3S     ɛtwal     1
435450      étonner  pc3S   ɛtɔnəʁɛ     1
435484     étouffer  ii3S     ɛtufɛ     1
436316         être  ppMS       ɛte    24
436835     éveiller   inf     ɛvɛje     1
437273       éviter  ai3S     ɛvita     1
437301       éviter   inf     ɛvite     1
437413      évoquer  ii3P     ɛvɔkɛ     1
437414      évoquer  ii1S     ɛvɔkɛ     1
437417      évoquer    pP    ɛvɔkɑ̃     1
437474         être  pi2P        ɛt    16
437476         être   inf       ɛtʁ    19

[1962 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 23.2 s, total: 1min 35s
Wall time: 30.7 s

nbChunk 56
4200
1961

             lexeme  case      phono  tir1
40            avoir  pi3S          a    87
67         abaisser  pi3S       abɛs     1
111      abandonner  ii1S   abɑ̃dɔnɛ     1
125      abandonner  pi1S    abɑ̃dɔn     1
164      abandonner  ppMS   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
914          abolir    pP   abɔlisɑ̃     1
1147        aborder   inf     abɔʁde     1
2594         abîmer  pi2S       abim     1
2878      accentuer  ai3S   aksɑ̃tya     1
2884      accentuer  ii3P   aksɑ̃tyɛ     1
2946       accepter  ai1S    aksɛptɛ     1
2964       accepter  pi1S     aksɛpt     1
2966       accepter  pI2S     aksɛpt     1
3003       accepter  ppMS    aksɛpte     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3438      accomplir  ppMS    akɔ̃pli     1
3467      accomplir  ii3S  akɔ̃plisɛ     1
3490      accomplir  pi3S    akɔ̃pli     2
3556       accorder  pi2P     akɔʁde     1
4291      accrocher  ppMS     akʁɔʃe     1
4294      accrocher  ppMP     akʁɔʃe     1
4521     accueillir  pi1P     akəjɔ̃     1
4720        accuser   inf      akyze     2
4835      accélérer   inf   aksɛlɛʁe     1
5119        acheter   inf      aʃəte     5
5136        acheter  ppMS      aʃəte     1
5313        acheter  pi3P       aʃɛt     1
6067        activer  pi3S      aktiv     1
...             ...   ...        ...   ...
430610   éparpiller  pi3S    ɛpaʁpij     1
431271       épiler   inf      ɛpile     1
432138      épouser  ai3S      ɛpuza     1
432302      épouser  ppMS      ɛpuze     1
432533     éprouver  ai1S     ɛpʁuvɛ     1
432657      épuiser  pi3P      ɛpɥiz     1
434048         être  ii3P        ɛtɛ     1
434068         être  ii1S        ɛtɛ    12
434070         être  ii3S        ɛtɛ    68
434147       étaler  pi3S       ɛtal     1
434775     éteindre  ppFS      ɛtɛ̃t     1
434779     éteindre  ppMP       ɛtɛ̃     1
434782      étendre  pi3S       ɛtɑ̃     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     3
435232       étirer  ai3S      ɛtiʁa     1
435296       étirer  ppMP      ɛtiʁe     1
435435      étonner  pi1S       ɛtɔn     1
435438      étonner  pi3S       ɛtɔn     1
435445      étonner  fi3S    ɛtɔnəʁa     1
435471      étonner  ppMS      ɛtɔne     1
435837    étreindre  ppMS      ɛtʁɛ̃     1
435899     étriller  ai3S     ɛtʁija     1
436316         être  ppMS        ɛte    22
436820     éveiller  ii3S      ɛvɛjɛ     1
437314       éviter  pi2S       ɛvit     1
437427      évoquer  pi3S       ɛvɔk     1
437458      évoquer  ppMS      ɛvɔke     1
437474         être  pi2P         ɛt    18
437476         être   inf        ɛtʁ    19

[1961 rows x 4 columns]

0
CPU times: user 1min 10s, sys: 21.9 s, total: 1min 31s
Wall time: 30.5 s

nbChunk 57
4200
1913

             lexeme  case      phono  tir1
40            avoir  pi3S          a    80
113      abandonner  ii3S   abɑ̃dɔnɛ     1
132      abandonner   inf   abɑ̃dɔne     1
160      abandonner  is3S   abɑ̃dɔna     1
164      abandonner  ppMS   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
305         abattre  ppMS      abaty     1
865          aboyer  pi3S       abwa     1
1147        aborder   inf     abɔʁde     1
1861        abréger  pi3P      abʁɛʒ     1
2124       absoudre  pi1S       absu     1
2730       accabler  pi3S      akabl     1
2950       accepter  ii3S    aksɛptɛ     1
2952       accepter    pP   aksɛptɑ̃     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     2
2977       accepter  pc3S  aksɛptəʁɛ     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3406    accompagner   inf   akɔ̃paɲe     1
3530       accorder  pi3S      akɔʁd     1
4216     accoutumer  ppMP    akutyme     1
4234      accrocher  ii3P     akʁɔʃɛ     1
4255      accrocher  pi3S      akʁɔʃ     1
4257      accrocher  pi3P      akʁɔʃ     1
4259      accrocher   inf     akʁɔʃe     1
4291      accrocher  ppMS     akʁɔʃe     1
4369      accroupir  pi3S     akʁupi     1
4509     accueillir   inf     akəjiʁ     2
4634      accumuler  ii3P    akymylɛ     1
...             ...   ...        ...   ...
433590       ériger   inf      ɛʁiʒe     1
433928      établir  pc3S   ɛtabliʁɛ     1
433939      établir  pi1S     ɛtabli     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ    11
434070         être  ii3S        ɛtɛ    83
434131       étaler  ii3P      ɛtalɛ     1
434147       étaler  pi3S       ɛtal     1
434772     éteindre  ppMS       ɛtɛ̃     1
434773     éteindre  pi3S       ɛtɛ̃     1
434794      étendre  pi3P      ɛtɑ̃d     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
434939     éternuer  pi2P    ɛtɛʁnye     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     4
435260       étirer   inf      ɛtiʁe     1
435419      étonner  ii3P      ɛtɔnɛ     1
435422      étonner  ii3S      ɛtɔnɛ     2
435442      étonner  pi3P       ɛtɔn     1
435540     étouffer  ppFS      ɛtufe     1
435732    étrangler    pP  ɛtʁɑ̃glɑ̃     1
436316         être  ppMS        ɛte    36
436632     évanouir   inf    ɛvanuiʁ     1
436835     éveiller   inf      ɛvɛje     1
436867     éveiller  ppMS      ɛvɛje     1
437301       éviter   inf      ɛvite     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    16
437476         être   inf        ɛtʁ    19

[1913 rows x 4 columns]

0
CPU times: user 1min 7s, sys: 19.5 s, total: 1min 26s
Wall time: 31.7 s

nbChunk 58
4200
1906

             lexeme  case      phono  tir1
40            avoir  pi3S          a    85
258         abattre  ii3S      abatɛ     1
299         abattre   inf      abatʁ     2
888          abolir  ppFS      abɔli     1
980         abonder  pi3S      abɔ̃d     1
2267      abstraire   inf    abstʁɛʁ     1
2616         abîmer  ppMP      abime     1
2736       accabler   inf     akable     1
2950       accepter  ii3S    aksɛptɛ     1
2969       accepter  pi3P     aksɛpt     1
2971       accepter   inf    aksɛpte     1
2976       accepter  pc2S  aksɛptəʁɛ     1
2989       accepter  pi2P    aksɛpte     1
3003       accepter  ppMS    aksɛpte     1
3376     accommoder  ppMS    akɔmɔde     1
3380    accompagner  ai3S   akɔ̃paɲa     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3440      accomplir  ppFS    akɔ̃pli     1
3460      accomplir  pi1S    akɔ̃pli     1
3536       accorder   inf     akɔʁde     1
4162     accoutumer  ii3P    akutymɛ     1
4230      accrocher  ai3S     akʁɔʃa     1
4473     accueillir  ii3S      akəjɛ     1
4482     accueillir  pi3S       akœj     1
4509     accueillir   inf     akəjiʁ     1
4683      accumuler  ppMS    akymyle     1
4720        accuser   inf      akyze     1
5111        acheter  ii3S      aʃətɛ     1
5136        acheter  ppMS      aʃəte     2
5311        acheter  pi3S       aʃɛt     1
...             ...   ...        ...   ...
432574     éprouver  pi2P     ɛpʁuve     1
433912      établir  ppMS     ɛtabli     1
433914      établir  ppFS     ɛtabli     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    10
434070         être  ii3S        ɛtɛ    68
434147       étaler  pi3S       ɛtal     1
434770     éteindre  pi2S       ɛtɛ̃     1
434773     éteindre  pi3S       ɛtɛ̃     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434853    éterniser  ii3S   ɛtɛʁnizɛ     1
435054         être  ii2P       ɛtje     2
435059    étinceler  ii3P   ɛtɛ̃səlɛ     1
435172         être  ii1P      ɛtjɔ̃     2
435232       étirer  ai3S      ɛtiʁa     1
435497     étouffer  pi1S       ɛtuf     1
435500     étouffer  pi3S       ɛtuf     1
436316         être  ppMS        ɛte    18
436629     évanouir  ppFS     ɛvanui     1
436815     éveiller  ai3S      ɛvɛja     1
436820     éveiller  ii3S      ɛvɛjɛ     1
437284       éviter  ii3S      ɛvitɛ     1
437285       éviter    pP     ɛvitɑ̃     1
437302       éviter  fi3S    ɛvitəʁa     1
437328       éviter  ppMS      ɛvite     1
437352      évoluer  ii3S     ɛvɔlyɛ     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    18
437505         ôter  pi1S         ot     1
437539         ôter  ppMS        ɔte     1

[1906 rows x 4 columns]

0
CPU times: user 1min 10s, sys: 21.3 s, total: 1min 31s
Wall time: 31.4 s

nbChunk 59
4200
1924

             lexeme  case      phono  tir1
40            avoir  pi3S          a    92
114      abandonner    pP  abɑ̃dɔnɑ̃     1
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
162      abandonner  ai3P  abɑ̃dɔnɛʁ     1
164      abandonner  ppMS   abɑ̃dɔne     1
272         abattre  pi2P      abate     1
1050        abonner  pi2P      abɔne     1
1169        aborder  pi1P    abɔʁdɔ̃     1
2100       absorber  ppMS    absɔʁbe     1
2116       absoudre   inf     absudʁ     1
2574         abîmer  pi1S       abim     1
2887      accentuer  ii3S   aksɑ̃tyɛ     1
2971       accepter   inf    aksɛpte     1
2975       accepter  pc1S  aksɛptəʁɛ     1
3003       accepter  ppMS    aksɛpte     2
3380    accompagner  ai3S   akɔ̃paɲa     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3406    accompagner   inf   akɔ̃paɲe     1
3519       accorder  ii3S     akɔʁdɛ     1
3530       accorder  pi3S      akɔʁd     1
3821      accoucher  pi3S       akuʃ     1
4090       accourir  pi3S       akuʁ     1
4238      accrocher    pP    akʁɔʃɑ̃     1
4259      accrocher   inf     akʁɔʃe     1
4381      accroître   inf    akʁwatʁ     1
4470     accueillir  ii3P      akəjɛ     1
4482     accueillir  pi3S       akœj     1
4510     accueillir  ai3P     akəjiʁ     1
4720        accuser   inf      akyze     1
...             ...   ...        ...   ...
432173      épouser  pi2S       ɛpuz     1
432532     éprouver  ai3S     ɛpʁuva     1
433790      éructer  pi3S      ɛʁykt     1
433928      établir  pc3S   ɛtabliʁɛ     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    15
434070         être  ii3S        ɛtɛ    73
434153       étaler   inf      ɛtale     2
434773     éteindre  pi3S       ɛtɛ̃     1
435172         être  ii1P      ɛtjɔ̃     3
435243       étirer  ii3S      ɛtiʁɛ     1
435244       étirer    pP     ɛtiʁɑ̃     1
435419      étonner  ii3P      ɛtɔnɛ     1
435438      étonner  pi3S       ɛtɔn     1
435444      étonner   inf      ɛtɔne     1
435506     étouffer   inf      ɛtufe     1
435540     étouffer  ppFS      ɛtufe     1
435828    étreindre   inf    ɛtʁɛ̃dʁ     1
436205      étudier   inf     ɛtydje     2
436207      étudier  fi1S    ɛtydiʁɛ     1
436316         être  ppMS        ɛte    14
436627     évanouir  ppMS     ɛvanui     1
436815     éveiller  ai3S      ɛvɛja     1
436820     éveiller  ii3S      ɛvɛjɛ     1
437329       éviter  ppFS      ɛvite     1
437413      évoquer  ii3P      ɛvɔkɛ     1
437427      évoquer  pi3S       ɛvɔk     1
437474         être  pi2P         ɛt    14
437476         être   inf        ɛtʁ    10
437505         ôter  pi1S         ot     1

[1924 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.6 s, total: 1min 35s
Wall time: 32.9 s

nbChunk 60
4200
1988

            lexeme  case       phono  tir1
40           avoir  pi3S           a   101
132     abandonner   inf    abɑ̃dɔne     1
134     abandonner  fi1S  abɑ̃dɔnəʁɛ     1
166     abandonner  ppFS    abɑ̃dɔne     1
1673       abriter  ii3S      abʁitɛ     1
1859       abréger  pi3S       abʁɛʒ     1
2579        abîmer  pi3P        abim     1
2950      accepter  ii3S     aksɛptɛ     1
2964      accepter  pi1S      aksɛpt     1
2967      accepter  pi3S      aksɛpt     1
2973      accepter  fi1S   aksɛptəʁɛ     1
2984      accepter  pi2S      aksɛpt     1
2989      accepter  pi2P     aksɛpte     1
2999      accepter  is3S     aksɛpta     1
3003      accepter  ppMS     aksɛpte     1
3347    accommoder  pi3P      akɔmɔd     1
3438     accomplir  ppMS     akɔ̃pli     2
3863      accouder  ai1S       akudɛ     1
4237     accrocher  ii3S      akʁɔʃɛ     2
4259     accrocher   inf      akʁɔʃe     1
4391     accroître  ppFP        akʁy     1
4509    accueillir   inf      akəjiʁ     2
4758       accéder  pi3S       aksɛd     1
4998      acharner    pP     aʃaʁnɑ̃     1
5102       acheter  ai3S       aʃəta     1
5111       acheter  ii3S       aʃətɛ     1
5112       acheter    pP      aʃətɑ̃     1
5119       acheter   inf       aʃəte     3
5136       acheter  ppMS       aʃəte     1
5315       acheter  fi3S     aʃɛtəʁa     1
...            ...   ...         ...   ...
434068        être  ii1S         ɛtɛ    16
434070        être  ii3S         ɛtɛ    70
434151      étaler  pi3P        ɛtal     1
434488        être    pP        ɛtɑ̃     1
434762    éteindre   inf      ɛtɛ̃dʁ     1
434775    éteindre  ppFS       ɛtɛ̃t     1
434779    éteindre  ppMP        ɛtɛ̃     2
434831     étendre  ppMS      ɛtɑ̃dy     1
434833     étendre  ppFS      ɛtɑ̃dy     1
435054        être  ii2P        ɛtje     1
435438     étonner  pi3S        ɛtɔn     1
435444     étonner   inf       ɛtɔne     2
435450     étonner  pc3S     ɛtɔnəʁɛ     1
435472     étonner  ppFS       ɛtɔne     1
435497    étouffer  pi1S        ɛtuf     1
435742   étrangler  pi3S     ɛtʁɑ̃gl     1
436186     étudier  ii3S      ɛtydjɛ     1
436205     étudier   inf      ɛtydje     1
436316        être  ppMS         ɛte    16
436402     évacuer   inf      ɛvakye     2
436484      évader  ppMS       ɛvade     1
436867    éveiller  ppMS       ɛvɛje     1
437025    éventrer  ppFS     ɛvɑ̃tʁe     1
437273      éviter  ai3S       ɛvita     1
437299      éviter  pi3P        ɛvit     1
437431     évoquer   inf       ɛvɔke     1
437474        être  pi2P          ɛt    12
437476        être   inf         ɛtʁ    16
437508        ôter  pi3S          ot     1
437540        ôter  ppFS         ɔte     1

[1988 rows x 4 columns]

0
CPU times: user 1min 11s, sys: 20.5 s, total: 1min 31s
Wall time: 32 s

nbChunk 61
4200
1914

             lexeme  case     phono  tir1
40            avoir  pi3S         a    87
73         abaisser   inf     abɛse     1
108      abandonner  ai3S  abɑ̃dɔna     1
271         abattre  pI2P     abate     1
1147        aborder   inf    abɔʁde     1
1388        aboutir  ppMS     abuti     1
1394        aboutir  fi3S   abutiʁa     1
1460         aboyer  ii3S    abwajɛ     1
2143       abstenir   inf  abstəniʁ     1
2904      accentuer   inf  aksɑ̃tye     1
3003       accepter  ppMS   aksɛpte     1
3189     acclimater  pi2S   aklimat     1
3383    accompagner  ii1S  akɔ̃paɲɛ     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     2
3433    accompagner  ppMS  akɔ̃paɲe     1
3436    accompagner  ppMP  akɔ̃paɲe     1
3970      accoupler   inf    akuple     1
4280      accrocher  pi2P    akʁɔʃe     1
4320      accroupir  ppMS    akʁupi     1
4690        accuser  ii3P     akyzɛ     1
4736        accuser  pi2P     akyze     1
5111        acheter  ii3S     aʃətɛ     1
5136        acheter  ppMS     aʃəte     1
5139        acheter  ppMP     aʃəte     1
5140        achever  ai3S     aʃəva     1
5329        achever  pi1S      aʃɛv     1
5806       acquérir  ppMP       aki     1
5807       acquérir  ppMS       aki     1
6444        adapter  ppFS    adapte     1
...             ...   ...       ...   ...
433946      établir  ii3S  ɛtablisɛ     2
434068         être  ii1S       ɛtɛ    15
434070         être  ii3S       ɛtɛ    69
434147       étaler  pi3S      ɛtal     1
434301       étaler  ppFP     ɛtale     1
434747     éteindre  ai3S     ɛtɛɲi     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
434772     éteindre  ppMS      ɛtɛ̃     1
434785      étendre  ii3P    ɛtɑ̃dɛ     1
434831      étendre  ppMS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     1
435260       étirer   inf     ɛtiʁe     1
435408      étoiler  ppMS    ɛtwale     1
435450      étonner  pc3S   ɛtɔnəʁɛ     1
435457      étonner  pi2S      ɛtɔn     1
435466      étonner  pi1P    ɛtɔnɔ̃     1
435471      étonner  ppMS     ɛtɔne     1
435472      étonner  ppFS     ɛtɔne     1
435500     étouffer  pi3S      ɛtuf     1
436183      étudier  ii3P    ɛtydjɛ     1
436233      étudier  ppMS    ɛtydje     2
436316         être  ppMS       ɛte    18
436520      évaluer   inf    ɛvalye     1
436993     éventrer  pi3S    ɛvɑ̃tʁ     1
437295       éviter  pi3S      ɛvit     1
437301       éviter   inf     ɛvite     1
437431      évoquer   inf     ɛvɔke     2
437474         être  pi2P        ɛt     9
437476         être   inf       ɛtʁ    17

[1914 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 21 s, total: 1min 33s
Wall time: 35.3 s

nbChunk 62
4200
2011

             lexeme  case        phono  tir1
40            avoir  pi3S            a    92
132      abandonner   inf     abɑ̃dɔne     2
164      abandonner  ppMS     abɑ̃dɔne     1
305         abattre  ppMS        abaty     1
1674        abriter    pP      abʁitɑ̃     1
2100       absorber  ppMS      absɔʁbe     1
2106       absorber  ppMP      absɔʁbe     1
2123       absoudre  ppMS         absu     1
2964       accepter  pi1S       aksɛpt     1
2971       accepter   inf      aksɛpte     1
2975       accepter  pc1S    aksɛptəʁɛ     1
3003       accepter  ppMS      aksɛpte     1
3005       accepter  ppFS      aksɛpte     1
3009       accepter  ppMP      aksɛpte     1
3117       acclamer   inf       aklame     1
3397    accompagner  pi1S      akɔ̃paɲ     1
3400    accompagner  pi3S      akɔ̃paɲ     1
3407    accompagner  fi3S   akɔ̃paɲəʁa     1
3418    accompagner  fi3P  akɔ̃paɲəʁɔ̃     1
3438      accomplir  ppMS      akɔ̃pli     1
3884       accouder   inf        akude     1
4321      accroupir  ppFS       akʁupi     1
4488     accueillir  pc3P      akəjəʁɛ     1
4547        acculer   inf        akyle     1
5119        acheter   inf        aʃəte     3
5136        acheter  ppMS        aʃəte     1
5316        acheter  fi1S      aʃɛtəʁɛ     1
5807       acquérir  ppMS          aki     1
6732      adjoindre  ppMS       adʒwɛ̃     1
6863       admettre  pi1S         admɛ     1
...             ...   ...          ...   ...
430558     épargner  pi3S        ɛpaʁɲ     1
430610   éparpiller  pi3S      ɛpaʁpij     1
431064        épier  ii3S         ɛpjɛ     1
431971      éponger  pi3S        ɛpɔ̃ʒ     1
432160      épouser   inf        ɛpuze     1
432303      épouser  ppFS        ɛpuze     1
432549     éprouver  pi1S        ɛpʁuv     1
432552     éprouver  pi3S        ɛpʁuv     1
432691      épuiser  ppFS       ɛpɥize     1
433922      établir   inf      ɛtabliʁ     1
434048         être  ii3P          ɛtɛ     4
434068         être  ii1S          ɛtɛ    13
434070         être  ii3S          ɛtɛ    83
434772     éteindre  ppMS         ɛtɛ̃     1
434773     éteindre  pi3S         ɛtɛ̃     1
434821      étendre   inf       ɛtɑ̃dʁ     1
435172         être  ii1P        ɛtjɔ̃     2
435244       étirer    pP       ɛtiʁɑ̃     1
435254       étirer  pi3S         ɛtiʁ     1
435450      étonner  pc3S      ɛtɔnəʁɛ     1
435457      étonner  pi2S         ɛtɔn     1
435474      étonner  ppMP        ɛtɔne     1
435696     étourdir  pi3P      ɛtuʁdis     1
436201      étudier  pi3S        ɛtydi     1
436316         être  ppMS          ɛte    17
436402      évacuer   inf       ɛvakye     2
436457       évader   inf        ɛvade     1
436835     éveiller   inf        ɛvɛje     1
437474         être  pi2P           ɛt    14
437476         être   inf          ɛtʁ    24

[2011 rows x 4 columns]

0
CPU times: user 1min 1s, sys: 21.6 s, total: 1min 23s
Wall time: 34.9 s

nbChunk 63
4200
1979

             lexeme  case      phono  tir1
40            avoir  pi3S          a    88
108      abandonner  ai3S   abɑ̃dɔna     1
114      abandonner    pP  abɑ̃dɔnɑ̃     1
128      abandonner  pi3S    abɑ̃dɔn     1
164      abandonner  ppMS   abɑ̃dɔne     2
287         abattre  ai3S      abati     1
305         abattre  ppMS      abaty     1
1393        aboutir   inf     abutiʁ     1
2116       absoudre   inf     absudʁ     1
2610         abîmer  ppMS      abime     1
2950       accepter  ii3S    aksɛptɛ     1
2964       accepter  pi1S     aksɛpt     1
3003       accepter  ppMS    aksɛpte     2
3400    accompagner  pi3S    akɔ̃paɲ     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3438      accomplir  ppMS    akɔ̃pli     1
3443      accomplir   inf   akɔ̃pliʁ     1
3490      accomplir  pi3S    akɔ̃pli     1
4210     accoutumer  ppMS    akutyme     1
4255      accrocher  pi3S      akʁɔʃ     1
4291      accrocher  ppMS     akʁɔʃe     1
4294      accrocher  ppMP     akʁɔʃe     1
4337      accroupir  ppMP     akʁupi     1
4373      accroître  pi3S      akʁwa     1
4748        accuser  ppMS      akyze     1
4864      accélérer  ppFS   aksɛlɛʁe     1
5108        acheter  ii3P      aʃətɛ     1
5119        acheter   inf      aʃəte     1
5308        acheter  pi1S       aʃɛt     1
5758     acquiescer  pi3S      akjɛs     1
...             ...   ...        ...   ...
433922      établir   inf    ɛtabliʁ     1
433939      établir  pi1S     ɛtabli     1
433946      établir  ii3S   ɛtablisɛ     1
434048         être  ii3P        ɛtɛ     7
434068         être  ii1S        ɛtɛ    17
434070         être  ii3S        ɛtɛ    76
434153       étaler   inf      ɛtale     1
434723     éteindre  ii3P      ɛtɛɲɛ     1
434772     éteindre  ppMS       ɛtɛ̃     1
435054         être  ii2P       ɛtje     3
435172         être  ii1P      ɛtjɔ̃     1
435438      étonner  pi3S       ɛtɔn     1
435471      étonner  ppMS      ɛtɔne     1
435500     étouffer  pi3S       ɛtuf     1
435540     étouffer  ppFS      ɛtufe     1
435544     étouffer  ppMP      ɛtufe     1
436198      étudier  pi1S      ɛtydi     1
436205      étudier   inf     ɛtydje     1
436231      étudier  ai3P    ɛtydjɛʁ     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    27
436402      évacuer   inf     ɛvakye     1
436679     évanouir  pi3S     ɛvanui     1
436890      éventer    pP    ɛvɑ̃tɑ̃     1
437301       éviter   inf      ɛvite     2
437328       éviter  ppMS      ɛvite     1
437474         être  pi2P         ɛt    13
437476         être   inf        ɛtʁ    24
437512         ôter   inf        ɔte     1
437513         ôter  fi3S      ɔtəʁa     1

[1979 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.2 s, total: 1min 35s
Wall time: 33.8 s

nbChunk 64
4200
1987

             lexeme  case       phono  tir1
40            avoir  pi3S           a    86
108      abandonner  ai3S    abɑ̃dɔna     1
109      abandonner  ai1S    abɑ̃dɔnɛ     1
166      abandonner  ppFS    abɑ̃dɔne     1
305         abattre  ppMS       abaty     1
887          abolir  ppMS       abɔli     1
1388        aboutir  ppMS       abuti     1
2946       accepter  ai1S     aksɛptɛ     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     2
3176     acclimater   inf    aklimate     1
3380    accompagner  ai3S    akɔ̃paɲa     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3438      accomplir  ppMS     akɔ̃pli     1
3490      accomplir  pi3S     akɔ̃pli     1
3536       accorder   inf      akɔʁde     1
4255      accrocher  pi3S       akʁɔʃ     1
4259      accrocher   inf      akʁɔʃe     1
4292      accrocher  ppFS      akʁɔʃe     1
4320      accroupir  ppMS      akʁupi     1
4509     accueillir   inf      akəjiʁ     1
4736        accuser  pi2P       akyze     1
4783        accéder   inf      aksɛde     1
5119        acheter   inf       aʃəte     1
5131        acheter  pi1P      aʃətɔ̃     1
5173        achever  ppFS       aʃəve     1
5326        acheter  fi3P    aʃɛtəʁɔ̃     1
5892       acquérir    pP      akɛʁɑ̃     1
6902    administrer  ii3S  administʁɛ     1
6991        admirer  pi3S       admiʁ     2
...             ...   ...         ...   ...
432302      épouser  ppMS       ɛpuze     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
432556     éprouver   inf      ɛpʁuve     1
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    71
434772     éteindre  ppMS        ɛtɛ̃     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434831      étendre  ppMS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     2
435417      étonner  ai3S       ɛtɔna     1
435420      étonner  ii1S       ɛtɔnɛ     1
435444      étonner   inf       ɛtɔne     1
435475     étouffer  ai3S       ɛtufa     1
435482     étouffer  ii1S       ɛtufɛ     1
435484     étouffer  ii3S       ɛtufɛ     1
435519     étouffer  pi2S        ɛtuf     1
435540     étouffer  ppFS       ɛtufe     1
435731    étrangler  ii3S    ɛtʁɑ̃glɛ     1
436316         être  ppMS         ɛte    24
436402      évacuer   inf      ɛvakye     1
436542      évaluer  pi1P     ɛvalyɔ̃     1
436629     évanouir  ppFS      ɛvanui     1
436632     évanouir   inf     ɛvanuiʁ     1
436815     éveiller  ai3S       ɛvɛja     1
437301       éviter   inf       ɛvite     1
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    23
437492         ôter  ai3S         ɔta     1
437512         ôter   inf         ɔte     1

[1987 rows x 4 columns]

0
CPU times: user 1min 5s, sys: 22.8 s, total: 1min 28s
Wall time: 34.1 s

nbChunk 65
4200
1943

             lexeme  case        phono  tir1
40            avoir  pi3S            a    61
108      abandonner  ai3S     abɑ̃dɔna     2
572        abhorrer  ii1S        abɔʁɛ     1
890          abolir   inf       abɔliʁ     1
1147        aborder   inf       abɔʁde     1
1950       absenter   inf      absɑ̃te     1
2073       absorber  pc3P    absɔʁbəʁɛ     1
2143       abstenir   inf     abstəniʁ     1
2594         abîmer  pi2S         abim     1
2612         abîmer  ppFS        abime     1
2967       accepter  pi3S       aksɛpt     1
2971       accepter   inf      aksɛpte     1
3009       accepter  ppMP      aksɛpte     1
3406    accompagner   inf     akɔ̃paɲe     1
3484      accomplir  ii1P  akɔ̃plisjɔ̃     1
3536       accorder   inf       akɔʁde     1
3827      accoucher   inf        akuʃe     1
4381      accroître   inf      akʁwatʁ     1
4694        accuser    pP       akyzɑ̃     1
4713        accuser  pi1S         akyz     1
4720        accuser   inf        akyze     1
5119        acheter   inf        aʃəte     2
5136        acheter  ppMS        aʃəte     1
5139        acheter  ppMP        aʃəte     1
5140        achever  ai3S        aʃəva     1
5149        achever  ii3S        aʃəvɛ     1
5311        acheter  pi3S         aʃɛt     1
5905       acquérir   inf       akɛʁiʁ     1
6891       admettre   inf       admɛtʁ     1
6991        admirer  pi3S        admiʁ     1
...             ...   ...          ...   ...
429694      énerver  pi3S        ɛnɛʁv     1
429716      énerver  pi2P       ɛnɛʁve     1
431165        épier  pi3P          ɛpi     1
432160      épouser   inf        ɛpuze     4
432302      épouser  ppMS        ɛpuze     1
432420   épouvanter  ppMS     ɛpuvɑ̃te     1
432535     éprouver  ii1S       ɛpʁuvɛ     1
433105      équiper  pi3S         ɛkip     1
433617       ériger  ppMS        ɛʁiʒe     1
433912      établir  ppMS       ɛtabli     1
433922      établir   inf      ɛtabliʁ     1
434048         être  ii3P          ɛtɛ     4
434068         être  ii1S          ɛtɛ    12
434070         être  ii3S          ɛtɛ    78
434788      étendre  ii3S       ɛtɑ̃dɛ     1
435054         être  ii2P         ɛtje     3
435172         être  ii1P        ɛtjɔ̃     3
435442      étonner  pi3P         ɛtɔn     1
435450      étonner  pc3S      ɛtɔnəʁɛ     1
435497     étouffer  pi1S         ɛtuf     1
436316         être  ppMS          ɛte    14
436461       évader  pc1S      ɛvadəʁɛ     1
436520      évaluer   inf       ɛvalye     1
436629     évanouir  ppFS       ɛvanui     1
436871     éveiller  ppFP        ɛvɛje     1
437431      évoquer   inf        ɛvɔke     1
437458      évoquer  ppMS        ɛvɔke     1
437474         être  pi2P           ɛt    14
437476         être   inf          ɛtʁ    23
437492         ôter  ai3S          ɔta     1

[1943 rows x 4 columns]

0
CPU times: user 1min 1s, sys: 22.6 s, total: 1min 24s
Wall time: 34.1 s

nbChunk 66
4200
1900

             lexeme  case      phono  tir1
40            avoir  pi3S          a    95
50         abaisser  ii3S      abɛsɛ     1
101        abaisser  ppMS      abɛse     1
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     3
305         abattre  ppMS      abaty     1
1796        abrutir  ppMS     abʁyti     1
1859        abréger  pi3S      abʁɛʒ     1
1950       absenter   inf    absɑ̃te     1
2098       absorber  ai3P   absɔʁbɛʁ     1
2717       accabler    pP    akablɑ̃     1
2950       accepter  ii3S    aksɛptɛ     1
2964       accepter  pi1S     aksɛpt     1
2974       accepter  pc3P  aksɛptəʁɛ     1
3003       accepter  ppMS    aksɛpte     1
3144       acclamer  ppMS     aklame     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3419    accompagner  pi2S    akɔ̃paɲ     1
3530       accorder  pi3S      akɔʁd     1
4280      accrocher  pi2P     akʁɔʃe     1
4686      accumuler  ppMP    akymyle     1
5108        acheter  ii3P      aʃətɛ     1
5119        acheter   inf      aʃəte     1
5136        acheter  ppMS      aʃəte     1
5137        acheter  ppFS      aʃəte     1
5149        achever  ii3S      aʃəvɛ     2
5150        achever    pP     aʃəvɑ̃     1
5157        achever   inf      aʃəve     1
5338        achever  fi3S    aʃɛvəʁa     1
5788     acquiescer  ai1S     akjɛsɛ     1
...             ...   ...        ...   ...
425638       égarer  pi3S       ɛgaʁ     1
427324       élever  ppFS      ɛləve     1
427641     éloigner   inf     ɛlwaɲe     2
428393      émerger  pi3S      ɛmɛʁʒ     1
430562     épargner   inf     ɛpaʁɲe     1
430645   éparpiller  ppFP   ɛpaʁpije     1
432160      épouser   inf      ɛpuze     1
432420   épouvanter  ppMS   ɛpuvɑ̃te     1
432535     éprouver  ii1S     ɛpʁuvɛ     1
432537     éprouver  ii3S     ɛpʁuvɛ     2
432556     éprouver   inf     ɛpʁuve     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ     5
434070         être  ii3S        ɛtɛ    70
434762     éteindre   inf     ɛtɛ̃dʁ     2
434772     éteindre  ppMS       ɛtɛ̃     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     3
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435481     étouffer  ii3P      ɛtufɛ     1
435798    étreindre  pi3P      ɛtʁɛɲ     1
435972      étriper   inf     ɛtʁipe     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    18
437328       éviter  ppMS      ɛvite     1
437417      évoquer    pP     ɛvɔkɑ̃     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    17
437520         ôter  fi2P      ɔtəʁe     1

[1900 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 21.3 s, total: 1min 33s
Wall time: 34.1 s

nbChunk 67
4200
1932

             lexeme  case       phono  tir1
40            avoir  pi3S           a    89
52         abaisser    pP      abɛsɑ̃     1
147      abandonner  pI2P    abɑ̃dɔne     1
170      abandonner  ppMP    abɑ̃dɔne     1
177      abasourdir  ppMS    abazuʁdi     1
1950       absenter   inf     absɑ̃te     1
2048       absorber  ii3P     absɔʁbɛ     1
2070       absorber   inf     absɔʁbe     1
2581         abîmer   inf       abime     2
2952       accepter    pP    aksɛptɑ̃     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     3
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3468      accomplir    pP  akɔ̃plisɑ̃     1
3471      accomplir  ps3S    akɔ̃plis     1
3519       accorder  ii3S      akɔʁdɛ     1
3858      accoucher  ppMS       akuʃe     1
4212     accoutumer  ppFS     akutyme     1
4291      accrocher  ppMS      akʁɔʃe     1
4381      accroître   inf     akʁwatʁ     1
4484     accueillir  pi3P        akœj     1
4720        accuser   inf       akyze     1
4783        accéder   inf      aksɛde     1
4823      accélérer  ii3S    aksɛlɛʁɛ     1
5111        acheter  ii3S       aʃətɛ     1
5119        acheter   inf       aʃəte     3
5308        acheter  pi1S        aʃɛt     1
5807       acquérir  ppMS         aki     1
...             ...   ...         ...   ...
432537     éprouver  ii3S      ɛpʁuvɛ     2
432691      épuiser  ppFS      ɛpɥize     1
433169      équiper  ppMS       ɛkipe     2
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ    18
434070         être  ii3S         ɛtɛ    63
434675       étayer  ii3S       ɛtɛjɛ     1
434779     éteindre  ppMP        ɛtɛ̃     1
434836      étendre  ppFP      ɛtɑ̃dy     1
435172         être  ii1P       ɛtjɔ̃     3
435192    étiqueter   inf     ɛtikəte     1
435444      étonner   inf       ɛtɔne     2
435482     étouffer  ii1S       ɛtufɛ     1
435500     étouffer  pi3S        ɛtuf     1
435837    étreindre  ppMS       ɛtʁɛ̃     1
436188      étudier    pP     ɛtydjɑ̃     1
436201      étudier  pi3S       ɛtydi     1
436316         être  ppMS         ɛte    22
436453       évader  pi3S        ɛvad     1
436457       évader   inf       ɛvade     1
436627     évanouir  ppMS      ɛvanui     1
436820     éveiller  ii3S       ɛvɛjɛ     1
436867     éveiller  ppMS       ɛvɛje     1
437295       éviter  pi3S        ɛvit     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437424      évoquer  pi1S        ɛvɔk     1
437474         être  pi2P          ɛt    15
437476         être   inf         ɛtʁ    23
437512         ôter   inf         ɔte     1

[1932 rows x 4 columns]

0
CPU times: user 1min 4s, sys: 22.9 s, total: 1min 27s
Wall time: 34.8 s

nbChunk 68
4200
1941

             lexeme  case       phono  tir1
40            avoir  pi3S           a    89
50         abaisser  ii3S       abɛsɛ     2
78         abaisser  pc2S     abɛsəʁɛ     1
132      abandonner   inf    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     1
287         abattre  ai3S       abati     1
299         abattre   inf       abatʁ     1
982         abonder  pi3P       abɔ̃d     1
1130        aborder  ii1S      abɔʁdɛ     1
1175        aborder  ppMS      abɔʁde     1
1950       absenter   inf     absɑ̃te     1
2939       accepter  ai3S     aksɛpta     2
2971       accepter   inf     aksɛpte     1
2984       accepter  pi2S      aksɛpt     1
3003       accepter  ppMS     aksɛpte     2
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3386    accompagner    pP   akɔ̃paɲɑ̃     1
3410    accompagner  pc1S  akɔ̃paɲəʁɛ     1
3419    accompagner  pi2S     akɔ̃paɲ     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3440      accomplir  ppFS     akɔ̃pli     1
3573       accorder  ppFS      akɔʁde     1
4091       accourir  ppMS       akuʁy     2
4238      accrocher    pP     akʁɔʃɑ̃     1
4252      accrocher  pi1S       akʁɔʃ     1
4255      accrocher  pi3S       akʁɔʃ     1
4479     accueillir  pi1S        akœj     1
4482     accueillir  pi3S        akœj     1
4631        acculer  ppMP       akyle     1
4823      accélérer  ii3S    aksɛlɛʁɛ     1
...             ...   ...         ...   ...
432537     éprouver  ii3S      ɛpʁuvɛ     1
432539     éprouver    pP     ɛpʁuvɑ̃     1
432549     éprouver  pi1S       ɛpʁuv     1
432552     éprouver  pi3S       ɛpʁuv     1
433954      établir  pi3P     ɛtablis     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ    19
434070         être  ii3S         ɛtɛ    62
434134       étaler  ii3S       ɛtalɛ     1
434151       étaler  pi3P        ɛtal     1
434488         être    pP        ɛtɑ̃     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434770     éteindre  pi2S        ɛtɛ̃     1
434773     éteindre  pi3S        ɛtɛ̃     1
434786      étendre  ii1S      ɛtɑ̃dɛ     1
434821      étendre   inf      ɛtɑ̃dʁ     1
434831      étendre  ppMS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     1
435422      étonner  ii3S       ɛtɔnɛ     1
435538     étouffer  ppMS       ɛtufe     1
436316         être  ppMS         ɛte    19
436627     évanouir  ppMS      ɛvanui     1
437285       éviter    pP      ɛvitɑ̃     1
437301       éviter   inf       ɛvite     2
437328       éviter  ppMS       ɛvite     1
437367      évoluer   inf      ɛvɔlye     1
437427      évoquer  pi3S        ɛvɔk     1
437474         être  pi2P          ɛt     9
437476         être   inf         ɛtʁ    21

[1941 rows x 4 columns]

0
CPU times: user 1min 2s, sys: 22.4 s, total: 1min 25s
Wall time: 34.8 s

nbChunk 69
4200
1961

             lexeme  case      phono  tir1
40            avoir  pi3S          a    72
111      abandonner  ii1S   abɑ̃dɔnɛ     1
113      abandonner  ii3S   abɑ̃dɔnɛ     1
128      abandonner  pi3S    abɑ̃dɔn     1
305         abattre  ppMS      abaty     1
982         abonder  pi3P      abɔ̃d     1
1147        aborder   inf     abɔʁde     1
2339         abuser   inf      abyze     1
2971       accepter   inf    aksɛpte     1
2972       accepter  fi3S  aksɛptəʁa     1
2973       accepter  fi1S  aksɛptəʁɛ     1
2989       accepter  pi2P    aksɛpte     1
3003       accepter  ppMS    aksɛpte     2
3007       accepter  ppFP    aksɛpte     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3508       accorder  ai3S     akɔʁda     1
3527       accorder  pi1S      akɔʁd     1
3651       accoster  pi3S      akɔst     1
3827      accoucher   inf      akuʃe     2
3864       accouder  ii3P      akudɛ     1
4234      accrocher  ii3P     akʁɔʃɛ     1
4292      accrocher  ppFS     akʁɔʃe     1
4294      accrocher  ppMP     akʁɔʃe     1
4637      accumuler  ii3S    akymylɛ     1
4726        accuser  pc3S    akyzəʁɛ     1
5119        acheter   inf      aʃəte     3
5125        acheter  pi2P      aʃəte     1
5149        achever  ii3S      aʃəvɛ     1
5157        achever   inf      aʃəve     1
5171        achever  ppMS      aʃəve     1
...             ...   ...        ...   ...
428685     émietter   inf     ɛmjɛte     1
430506     épanouir  ii3P   ɛpanuisɛ     1
430590     épargner  ppMS     ɛpaʁɲe     1
432153      épouser  pi1S       ɛpuz     1
432181      épouser  pi2P      ɛpuze     1
432586     éprouver  ppMS     ɛpʁuve     1
433922      établir   inf    ɛtabliʁ     1
433944      établir  ii1S   ɛtablisɛ     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ     8
434070         être  ii3S        ɛtɛ    90
434301       étaler  ppFP      ɛtale     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     1
435254       étirer  pi3S       ɛtiʁ     1
435422      étonner  ii3S      ɛtɔnɛ     1
435472      étonner  ppFS      ɛtɔne     1
435506     étouffer   inf      ɛtufe     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    25
436400      évacuer  pi3P      ɛvaky     1
436520      évaluer   inf     ɛvalye     1
436679     évanouir  pi3S     ɛvanui     2
436815     éveiller  ai3S      ɛvɛja     1
436821     éveiller    pP     ɛvɛjɑ̃     1
437292       éviter  pi1S       ɛvit     1
437314       éviter  pi2S       ɛvit     1
437474         être  pi2P         ɛt    13
437476         être   inf        ɛtʁ    21
437539         ôter  ppMS        ɔte     1

[1961 rows x 4 columns]

0
CPU times: user 1min 5s, sys: 22.5 s, total: 1min 28s
Wall time: 34.3 s

nbChunk 70
4200
1898

             lexeme  case       phono  tir1
40            avoir  pi3S           a    95
125      abandonner  pi1S     abɑ̃dɔn     1
128      abandonner  pi3S     abɑ̃dɔn     1
138      abandonner  pc3S  abɑ̃dɔnəʁɛ     1
1796        abrutir  ppMS      abʁyti     1
2051       absorber  ii3S     absɔʁbɛ     1
2100       absorber  ppMS     absɔʁbe     1
2116       absoudre   inf      absudʁ     1
2332         abuser  pi1S        abyz     1
2337         abuser  pi3P        abyz     1
2339         abuser   inf       abyze     1
2887      accentuer  ii3S    aksɑ̃tyɛ     1
3003       accepter  ppMS     aksɛpte     2
3353     accommoder  pc1S   akɔmɔdəʁɛ     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     1
3440      accomplir  ppFS     akɔ̃pli     1
3516       accorder  ii3P      akɔʁdɛ     1
3530       accorder  pi3S       akɔʁd     1
3536       accorder   inf      akɔʁde     1
4216     accoutumer  ppMP     akutyme     1
4259      accrocher   inf      akʁɔʃe     1
4291      accrocher  ppMS      akʁɔʃe     1
4292      accrocher  ppFS      akʁɔʃe     1
4509     accueillir   inf      akəjiʁ     2
4656      accumuler   inf     akymyle     1
4693        accuser  ii3S       akyzɛ     1
4716        accuser  pi3S        akyz     1
4720        accuser   inf       akyze     1
...             ...   ...         ...   ...
432302      épouser  ppMS       ɛpuze     1
432303      épouser  ppFS       ɛpuze     1
432534     éprouver  ii3P      ɛpʁuvɛ     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
432556     éprouver   inf      ɛpʁuve     1
432635      épuiser  ii3P      ɛpɥizɛ     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ    20
434070         être  ii3S         ɛtɛ    83
434144       étaler  pi1S        ɛtal     1
434302       étaler  ppMP       ɛtale     1
434488         être    pP        ɛtɑ̃     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434785      étendre  ii3P      ɛtɑ̃dɛ     1
434831      étendre  ppMS      ɛtɑ̃dy     1
434833      étendre  ppFS      ɛtɑ̃dy     1
434839      étendre  ppMP      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     2
435412      étoiler  ppFP      ɛtwale     1
435457      étonner  pi2S        ɛtɔn     1
436316         être  ppMS         ɛte    25
436457       évader   inf       ɛvade     1
436867     éveiller  ppMS       ɛvɛje     1
436900      éventer  pi3S       ɛvɑ̃t     1
437301       éviter   inf       ɛvite     1
437317       éviter  pi2P       ɛvite     1
437427      évoquer  pi3S        ɛvɔk     1
437431      évoquer   inf       ɛvɔke     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    30

[1898 rows x 4 columns]

0
CPU times: user 1min 4s, sys: 22.5 s, total: 1min 27s
Wall time: 35.5 s

nbChunk 71
4200
1978

             lexeme  case     phono  tir1
40            avoir  pi3S         a   100
71         abaisser  pi3P      abɛs     1
130      abandonner  pi3P   abɑ̃dɔn     1
132      abandonner   inf  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     1
166      abandonner  ppFS  abɑ̃dɔne     1
310         abattre  ppFP     abaty     1
2143       abstenir   inf  abstəniʁ     1
2339         abuser   inf     abyze     1
2939       accepter  ai3S   aksɛpta     2
2964       accepter  pi1S    aksɛpt     1
2971       accepter   inf   aksɛpte     1
2989       accepter  pi2P   aksɛpte     1
3003       accepter  ppMS   aksɛpte     2
3400    accompagner  pi3S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     3
3433    accompagner  ppMS  akɔ̃paɲe     1
4090       accourir  pi3S      akuʁ     1
4257      accrocher  pi3P     akʁɔʃ     1
4790        accéder  fi2S  aksɛdəʁa     1
5119        acheter   inf     aʃəte     2
5149        achever  ii3S     aʃəvɛ     1
5171        achever  ppMS     aʃəve     1
5322        acheter  fi2P   aʃɛtəʁe     1
5807       acquérir  ppMS       aki     2
6821        adjurer  pi3S     adʒyʁ     1
6890       admettre  fi2S   admɛtʁa     1
6966        admirer  ii3P    admiʁɛ     1
7316         adorer   inf     adɔʁe     1
7398        adosser  ppMS     adɔse     1
...             ...   ...       ...   ...
428561  émerveiller  ii3S  ɛmɛʁvɛjɛ     1
429499     émouvoir  ai1S       ɛmy     1
430340     épancher   inf    ɛpɑ̃ʃe     1
432153      épouser  pi1S      ɛpuz     1
432157      épouser  ps3S      ɛpuz     1
432188   épousseter  ai3S   ɛpusəta     1
432532     éprouver  ai3S    ɛpʁuva     1
432586     éprouver  ppMS    ɛpʁuve     1
433169      équiper  ppMS     ɛkipe     1
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ    11
434070         être  ii3S       ɛtɛ    68
434153       étaler   inf     ɛtale     1
434299       étaler  ppMS     ɛtale     1
434782      étendre  pi3S      ɛtɑ̃     1
435054         être  ii2P      ɛtje     1
435438      étonner  pi3S      ɛtɔn     1
435484     étouffer  ii3S     ɛtufɛ     1
435500     étouffer  pi3S      ɛtuf     1
435512     étouffer  pc3S   ɛtufəʁɛ     1
435654     étourdir  ppMS    ɛtuʁdi     1
436316         être  ppMS       ɛte    23
436629     évanouir  ppFS    ɛvanui     1
436656     évanouir  ii3S  ɛvanuisɛ     1
436835     éveiller   inf     ɛvɛje     1
436873     éveiller  ppMP     ɛvɛje     1
437295       éviter  pi3S      ɛvit     1
437301       éviter   inf     ɛvite     2
437474         être  pi2P        ɛt    15
437476         être   inf       ɛtʁ    17

[1978 rows x 4 columns]

0
CPU times: user 1min 9s, sys: 19.6 s, total: 1min 29s
Wall time: 35.9 s

nbChunk 72
4200
1960

             lexeme  case      phono  tir1
40            avoir  pi3S          a    64
50         abaisser  ii3S      abɛsɛ     1
132      abandonner   inf   abɑ̃dɔne     2
197      abasourdir  ppMP   abazuʁdi     1
1393        aboutir   inf     abutiʁ     1
1425        aboutir  pi3P     abutis     1
1440        aboutir  pi3S      abuti     1
1688        abriter   inf     abʁite     1
1859        abréger  pi3S      abʁɛʒ     1
1943       absenter  pi1S     absɑ̃t     1
2337         abuser  pi3P       abyz     1
2565         abîmer  ii3S      abimɛ     1
2967       accepter  pi3S     aksɛpt     1
2977       accepter  pc3S  aksɛptəʁɛ     1
2994       accepter  ii1P  aksɛptjɔ̃     1
3347     accommoder  pi3P     akɔmɔd     1
3404    accompagner  pi3P    akɔ̃paɲ     1
3438      accomplir  ppMS    akɔ̃pli     1
3556       accorder  pi2P     akɔʁde     1
4009       accourir  ii3S      akuʁɛ     1
4354      accroupir  pi3P    akʁupis     1
4381      accroître   inf    akʁwatʁ     1
4736        accuser  pi2P      akyze     1
4750        accuser  ppFS      akyze     1
4790        accéder  fi2S   aksɛdəʁa     1
5041       acharner  ppMS     aʃaʁne     1
5149        achever  ii3S      aʃəvɛ     1
5311        acheter  pi3S       aʃɛt     1
5327        acheter  pi2S       aʃɛt     1
5792     acquiescer  ii3S     akjɛsɛ     1
...             ...   ...        ...   ...
432160      épouser   inf      ɛpuze     2
432689      épuiser  ppMS     ɛpɥize     1
433026   équilibrer   inf   ɛkilibʁe     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ     8
434070         être  ii3S        ɛtɛ    64
434131       étaler  ii3P      ɛtalɛ     2
434768     éteindre  pi1S       ɛtɛ̃     1
434811      étendre  ai3S     ɛtɑ̃di     1
434833      étendre  ppFS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     3
435172         être  ii1P      ɛtjɔ̃     1
435435      étonner  pi1S       ɛtɔn     1
435444      étonner   inf      ɛtɔne     1
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435540     étouffer  ppFS      ɛtufe     1
435748    étrangler   inf   ɛtʁɑ̃gle     2
435828    étreindre   inf    ɛtʁɛ̃dʁ     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    24
436437       évader  ai3S      ɛvada     1
436457       évader   inf      ɛvade     1
436520      évaluer   inf     ɛvalye     1
436627     évanouir  ppMS     ɛvanui     1
436709     évaporer  pi3P     ɛvapɔʁ     1
437281       éviter  ii3P      ɛvitɛ     1
437303       éviter  fi1S    ɛvitəʁɛ     1
437407      évoluer  ppMS     ɛvɔlye     1
437474         être  pi2P         ɛt    11
437476         être   inf        ɛtʁ    25

[1960 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 21.2 s, total: 1min 38s
Wall time: 35.3 s

nbChunk 73
4200
1997

             lexeme  case        phono  tir1
40            avoir  pi3S            a    80
108      abandonner  ai3S     abɑ̃dɔna     1
128      abandonner  pi3S      abɑ̃dɔn     1
132      abandonner   inf     abɑ̃dɔne     2
147      abandonner  pI2P     abɑ̃dɔne     1
1852        abrutir  pi3S       abʁyti     1
2116       absoudre   inf       absudʁ     1
2325         abuser    pP       abyzɑ̃     1
2339         abuser   inf        abyze     1
2366         abuser  pi1P       abyzɔ̃     1
2763       accabler  ppMS       akable     1
2766       accabler  ppMP       akable     1
2971       accepter   inf      aksɛpte     2
2981       accepter  pc1P  aksɛptəʁjɔ̃     1
3003       accepter  ppMS      aksɛpte     2
3176     acclimater   inf     aklimate     1
3397    accompagner  pi1S      akɔ̃paɲ     1
3406    accompagner   inf     akɔ̃paɲe     1
3418    accompagner  fi3P  akɔ̃paɲəʁɔ̃     1
3433    accompagner  ppMS     akɔ̃paɲe     2
3508       accorder  ai3S       akɔʁda     1
3571       accorder  ppMS       akɔʁde     1
4238      accrocher    pP      akʁɔʃɑ̃     1
4293      accrocher  ppFP       akʁɔʃe     1
4321      accroupir  ppFS       akʁupi     1
4484     accueillir  pi3P         akœj     1
5119        acheter   inf        aʃəte     2
5136        acheter  ppMS        aʃəte     2
5157        achever   inf        aʃəve     1
5807       acquérir  ppMS          aki     2
...             ...   ...          ...   ...
432531     éprendre  ai3S         ɛpʁi     1
432535     éprouver  ii1S       ɛpʁuvɛ     1
432552     éprouver  pi3S        ɛpʁuv     1
432575     éprouver  ii2P      ɛpʁuvje     1
432691      épuiser  ppFS       ɛpɥize     1
433912      établir  ppMS       ɛtabli     1
434048         être  ii3P          ɛtɛ     5
434068         être  ii1S          ɛtɛ    13
434069         être  ii2S          ɛtɛ     2
434070         être  ii3S          ɛtɛ    84
434488         être    pP         ɛtɑ̃     1
434762     éteindre   inf       ɛtɛ̃dʁ     1
434785      étendre  ii3P       ɛtɑ̃dɛ     1
434811      étendre  ai3S       ɛtɑ̃di     1
435054         être  ii2P         ɛtje     2
435172         être  ii1P        ɛtjɔ̃     1
435425      étonner    pP       ɛtɔnɑ̃     1
435438      étonner  pi3S         ɛtɔn     1
435471      étonner  ppMS        ɛtɔne     1
435506     étouffer   inf        ɛtufe     1
436316         être  ppMS          ɛte    26
436457       évader   inf        ɛvade     2
436833     éveiller  pi3P         ɛvɛj     1
436867     éveiller  ppMS        ɛvɛje     1
436889      éventer  ii3S       ɛvɑ̃tɛ     1
437427      évoquer  pi3S         ɛvɔk     1
437431      évoquer   inf        ɛvɔke     1
437474         être  pi2P           ɛt    13
437476         être   inf          ɛtʁ    22
437492         ôter  ai3S          ɔta     1

[1997 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 20.8 s, total: 1min 39s
Wall time: 32.9 s

nbChunk 74
4200
1975

             lexeme  case       phono  tir1
40            avoir  pi3S           a   116
67         abaisser  pi3S        abɛs     1
114      abandonner    pP   abɑ̃dɔnɑ̃     1
130      abandonner  pi3P     abɑ̃dɔn     2
132      abandonner   inf    abɑ̃dɔne     2
164      abandonner  ppMS    abɑ̃dɔne     1
170      abandonner  ppMP    abɑ̃dɔne     1
292         abattre  fi3S      abatʁa     1
1121        aborder  ai3S      abɔʁda     1
2952       accepter    pP    aksɛptɑ̃     1
2964       accepter  pi1S      aksɛpt     1
2979       accepter  fi2P   aksɛptəʁe     1
2982       accepter  fi1P  aksɛptəʁɔ̃     1
3003       accepter  ppMS     aksɛpte     2
3406    accompagner   inf    akɔ̃paɲe     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3490      accomplir  pi3S     akɔ̃pli     1
3536       accorder   inf      akɔʁde     1
3548       accorder  fi3P   akɔʁdəʁɔ̃     1
4259      accrocher   inf      akʁɔʃe     1
4291      accrocher  ppMS      akʁɔʃe     1
4479     accueillir  pi1S        akœj     1
4486     accueillir  fi3S     akəjəʁa     1
4509     accueillir   inf      akəjiʁ     2
4716        accuser  pi3S        akyz     1
4717        accuser  ps3S        akyz     1
4748        accuser  ppMS       akyze     1
4818      accélérer  ai3S    aksɛlɛʁa     1
5119        acheter   inf       aʃəte     1
5135        acheter  ai3P      aʃətɛʁ     1
...             ...   ...         ...   ...
432156      épouser  pi3S        ɛpuz     1
432535     éprouver  ii1S      ɛpʁuvɛ     1
432556     éprouver   inf      ɛpʁuve     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    68
434726     éteindre  ii3S       ɛtɛɲɛ     1
434729     éteindre  ps3S        ɛtɛɲ     1
434782      étendre  pi3S        ɛtɑ̃     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     1
435457      étonner  pi2S        ɛtɔn     1
435471      étonner  ppMS       ɛtɔne     1
435481     étouffer  ii3P       ɛtufɛ     1
435482     étouffer  ii1S       ɛtufɛ     1
435500     étouffer  pi3S        ɛtuf     1
435780    étrangler  ppMS    ɛtʁɑ̃gle     1
436316         être  ppMS         ɛte    15
436831     éveiller  pi3S        ɛvɛj     1
436835     éveiller   inf       ɛvɛje     1
436867     éveiller  ppMS       ɛvɛje     2
437049     évertuer  ii3S     ɛvɛʁtyɛ     1
437295       éviter  pi3S        ɛvit     2
437301       éviter   inf       ɛvite     1
437302       éviter  fi3S     ɛvitəʁa     1
437367      évoluer   inf      ɛvɔlye     1
437431      évoquer   inf       ɛvɔke     1
437461      évoquer  ppMP       ɛvɔke     1
437474         être  pi2P          ɛt    17
437476         être   inf         ɛtʁ    19

[1975 rows x 4 columns]

0
CPU times: user 1min 2s, sys: 8.49 s, total: 1min 10s
Wall time: 37.3 s

nbChunk 75
4200
1950

             lexeme  case       phono  tir1
40            avoir  pi3S           a    94
73         abaisser   inf       abɛse     1
101        abaisser  ppMS       abɛse     1
128      abandonner  pi3S     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     5
164      abandonner  ppMS    abɑ̃dɔne     1
313         abattre  ppMP       abaty     1
862          aboyer  pi1S        abwa     1
1393        aboutir   inf      abutiʁ     1
1440        aboutir  pi3S       abuti     1
2774      accaparer  ii3S     akapaʁɛ     1
2948       accepter  ii1S     aksɛptɛ     1
2969       accepter  pi3P      aksɛpt     1
3003       accepter  ppMS     aksɛpte     4
3433    accompagner  ppMS    akɔ̃paɲe     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3487      accomplir  pI1P  akɔ̃plisɔ̃     1
4259      accrocher   inf      akʁɔʃe     2
4280      accrocher  pi2P      akʁɔʃe     1
4509     accueillir   inf      akəjiʁ     1
5005       acharner  pi1S       aʃaʁn     1
5108        acheter  ii3P       aʃətɛ     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     2
5146        achever  ii3P       aʃəvɛ     1
5157        achever   inf       aʃəve     1
5171        achever  ppMS       aʃəve     1
5311        acheter  pi3S        aʃɛt     2
5787     acquiescer  ai3S      akjɛsa     1
5807       acquérir  ppMS         aki     1
...             ...   ...         ...   ...
434068         être  ii1S         ɛtɛ    11
434070         être  ii3S         ɛtɛ    69
434488         être    pP        ɛtɑ̃     1
434797      étendre  pI2P      ɛtɑ̃de     1
434866    éterniser  pi3P     ɛtɛʁniz     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     3
435254       étirer  pi3S        ɛtiʁ     1
435419      étonner  ii3P       ɛtɔnɛ     1
435438      étonner  pi3S        ɛtɔn     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435471      étonner  ppMS       ɛtɔne     1
435484     étouffer  ii3S       ɛtufɛ     1
435711     étourdir  pi3S      ɛtuʁdi     1
436201      étudier  pi3S       ɛtydi     1
436316         être  ppMS         ɛte    28
436402      évacuer   inf      ɛvakye     1
436516      évaluer  pi3S       ɛvaly     1
436627     évanouir  ppMS      ɛvanui     1
436632     évanouir   inf     ɛvanuiʁ     1
436835     éveiller   inf       ɛvɛje     1
436867     éveiller  ppMS       ɛvɛje     2
437301       éviter   inf       ɛvite     1
437414      évoquer  ii1S       ɛvɔkɛ     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437458      évoquer  ppMS       ɛvɔke     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    28
437492         ôter  ai3S         ɔta     1
437508         ôter  pi3S          ot     1

[1950 rows x 4 columns]

0
CPU times: user 54.7 s, sys: 8.41 s, total: 1min 3s
Wall time: 35.7 s

nbChunk 76
4200
1921

             lexeme  case       phono  tir1
40            avoir  pi3S           a   100
164      abandonner  ppMS    abɑ̃dɔne     1
1480         aboyer  pi1P     abwajɔ̃     1
2560         abîmer  ai3S       abima     1
2581         abîmer   inf       abime     1
2967       accepter  pi3S      aksɛpt     1
2989       accepter  pi2P     aksɛpte     1
3406    accompagner   inf    akɔ̃paɲe     1
3410    accompagner  pc1S  akɔ̃paɲəʁɛ     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3443      accomplir   inf    akɔ̃pliʁ     2
3519       accorder  ii3S      akɔʁdɛ     2
3530       accorder  pi3S       akɔʁd     2
3571       accorder  ppMS      akɔʁde     1
4259      accrocher   inf      akʁɔʃe     1
4280      accrocher  pi2P      akʁɔʃe     1
4748        accuser  ppMS       akyze     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     1
5171        achever  ppMS       aʃəve     1
5885       acquérir  pi3P       akjɛʁ     1
6072        activer   inf      aktive     1
6410        adapter  pi3S       adapt     1
6481    additionner  pc3S  adisjɔnəʁɛ     1
6965        admirer  ai1S      admiʁɛ     1
6991        admirer  pi3S       admiʁ     2
7012        admirer  pi2P      admiʁe     1
7312         adorer  pi3S        adɔʁ     2
7567       adresser  ppMS      adʁɛse     1
8046       affairer  pc3P     afɛʁəʁɛ     1
...             ...   ...         ...   ...
431065        épier    pP       ɛpjɑ̃     1
431167        épier   inf        ɛpje     1
431992      éponger   inf      ɛpɔ̃ʒe     1
432160      épouser   inf       ɛpuze     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
433169      équiper  ppMS       ɛkipe     1
433914      établir  ppFS      ɛtabli     1
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ    15
434070         être  ii3S         ɛtɛ    78
434723     éteindre  ii3P       ɛtɛɲɛ     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434782      étendre  pi3S        ɛtɑ̃     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434811      étendre  ai3S      ɛtɑ̃di     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     4
435232       étirer  ai3S       ɛtiʁa     1
435417      étonner  ai3S       ɛtɔna     1
435497     étouffer  pi1S        ɛtuf     1
435540     étouffer  ppFS       ɛtufe     1
436316         être  ppMS         ɛte    18
437295       éviter  pi3S        ɛvit     1
437301       éviter   inf       ɛvite     1
437314       éviter  pi2S        ɛvit     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437424      évoquer  pi1S        ɛvɔk     1
437474         être  pi2P          ɛt    10
437476         être   inf         ɛtʁ    25
437512         ôter   inf         ɔte     1

[1921 rows x 4 columns]

0
CPU times: user 53.2 s, sys: 13.5 s, total: 1min 6s
Wall time: 37.3 s

nbChunk 77
4200
1965

             lexeme  case     phono  tir1
40            avoir  pi3S         a    92
128      abandonner  pi3S   abɑ̃dɔn     1
132      abandonner   inf  abɑ̃dɔne     1
299         abattre   inf     abatʁ     1
1147        aborder   inf    abɔʁde     1
1417        aboutir    pP  abutisɑ̃     1
1789        abroger  ppMP    abʁɔʒe     1
1979       absenter  ppMS   absɑ̃te     1
2967       accepter  pi3S    aksɛpt     1
2969       accepter  pi3P    aksɛpt     1
2971       accepter   inf   aksɛpte     1
3003       accepter  ppMS   aksɛpte     1
3406    accompagner   inf  akɔ̃paɲe     1
3434    accompagner  ppFS  akɔ̃paɲe     1
3436    accompagner  ppMP  akɔ̃paɲe     1
3527       accorder  pi1S     akɔʁd     1
3530       accorder  pi3S     akɔʁd     1
3913       accouder  ppMS     akude     1
3914       accouder  ppFS     akude     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4736        accuser  pi2P     akyze     1
4994       acharner  ii3P    aʃaʁnɛ     1
5068      acheminer  pi3P    aʃəmin     1
5119        acheter   inf     aʃəte     1
5136        acheter  ppMS     aʃəte     3
5171        achever  ppMS     aʃəve     1
5311        acheter  pi3S      aʃɛt     2
6891       admettre   inf    admɛtʁ     1
6988        admirer  pi1S     admiʁ     1
7246        adopter  pi3S     adɔpt     1
...             ...   ...       ...   ...
432160      épouser   inf     ɛpuze     1
432173      épouser  pi2S      ɛpuz     1
432508     éprendre  pi3P     ɛpʁɛn     1
432689      épuiser  ppMS    ɛpɥize     1
433914      établir  ppFS    ɛtabli     1
433922      établir   inf   ɛtabliʁ     1
433969      établir  pi3S    ɛtabli     1
434048         être  ii3P       ɛtɛ     6
434068         être  ii1S       ɛtɛ     6
434070         être  ii3S       ɛtɛ    76
434762     éteindre   inf    ɛtɛ̃dʁ     1
434773     éteindre  pi3S      ɛtɛ̃     1
434789      étendre    pP   ɛtɑ̃dɑ̃     1
434804      étendre  ai1S    ɛtɑ̃di     1
434839      étendre  ppMP    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     3
435444      étonner   inf     ɛtɔne     1
435472      étonner  ppFS     ɛtɔne     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    34
436457       évader   inf     ɛvade     1
436485       évader  ppFS     ɛvade     1
436631     évanouir  ppFP    ɛvanui     1
436867     éveiller  ppMS     ɛvɛje     1
437292       éviter  pi1S      ɛvit     1
437301       éviter   inf     ɛvite     2
437474         être  pi2P        ɛt     7
437476         être   inf       ɛtʁ    20
437497         ôter  ii3S       ɔtɛ     2

[1965 rows x 4 columns]

0
CPU times: user 52.8 s, sys: 15.4 s, total: 1min 8s
Wall time: 34.4 s

nbChunk 78
4200
1933

             lexeme  case        phono  tir1
40            avoir  pi3S            a   105
129      abandonner  ps3S      abɑ̃dɔn     1
132      abandonner   inf     abɑ̃dɔne     1
144      abandonner  fi3P  abɑ̃dɔnəʁɔ̃     1
164      abandonner  ppMS     abɑ̃dɔne     1
261         abattre  ps3S         abat     1
299         abattre   inf        abatʁ     1
1112        abonner  ppFS        abɔne     1
1121        aborder  ai3S       abɔʁda     1
2594         abîmer  pi2S         abim     1
2932      accentuer  ppMS     aksɑ̃tye     1
3406    accompagner   inf     akɔ̃paɲe     1
3433    accompagner  ppMS     akɔ̃paɲe     1
3534       accorder  pi3P        akɔʁd     1
3737        accoter  ppMS        akɔte     1
4230      accrocher  ai3S       akʁɔʃa     1
4252      accrocher  pi1S        akʁɔʃ     1
4291      accrocher  ppMS       akʁɔʃe     2
4369      accroupir  pi3S       akʁupi     1
4502     accueillir  ppMS        akəji     1
4685      accumuler  ppFP      akymyle     1
5119        acheter   inf        aʃəte     2
5140        achever  ai3S        aʃəva     1
5162        achever  ii1P      aʃəvjɔ̃     1
5853      acquitter  fi3S      akitəʁa     1
6867       admettre  ii1S       admɛtɛ     1
7250        adopter   inf       adɔpte     2
7312         adorer  pi3S         adɔʁ     1
7333         adorer  ii2P       adɔʁje     1
7495        adoucir  pi3P       adusis     1
...             ...   ...          ...   ...
432534     éprouver  ii3P       ɛpʁuvɛ     1
432537     éprouver  ii3S       ɛpʁuvɛ     1
432586     éprouver  ppMS       ɛpʁuve     1
432659      épuiser   inf       ɛpɥize     1
433922      établir   inf      ɛtabliʁ     1
434048         être  ii3P          ɛtɛ     3
434068         être  ii1S          ɛtɛ     8
434069         être  ii2S          ɛtɛ     1
434070         être  ii3S          ɛtɛ    70
434762     éteindre   inf       ɛtɛ̃dʁ     1
434782      étendre  pi3S         ɛtɑ̃     1
434839      étendre  ppMP       ɛtɑ̃dy     1
434853    éterniser  ii3S     ɛtɛʁnizɛ     1
435054         être  ii2P         ɛtje     2
435172         être  ii1P        ɛtjɔ̃     2
435417      étonner  ai3S        ɛtɔna     1
435420      étonner  ii1S        ɛtɔnɛ     1
435425      étonner    pP       ɛtɔnɑ̃     1
435460      étonner  pi2P        ɛtɔne     1
435497     étouffer  pi1S         ɛtuf     1
435538     étouffer  ppMS        ɛtufe     1
436183      étudier  ii3P       ɛtydjɛ     1
436203      étudier  pi3P        ɛtydi     1
436316         être  ppMS          ɛte    21
436484       évader  ppMS        ɛvade     1
436629     évanouir  ppFS       ɛvanui     1
437324       éviter  ai1P       ɛvitam     1
437474         être  pi2P           ɛt    14
437476         être   inf          ɛtʁ    19
437512         ôter   inf          ɔte     1

[1933 rows x 4 columns]

0
CPU times: user 53.9 s, sys: 15.8 s, total: 1min 9s
Wall time: 34 s

nbChunk 79
4200
1960

             lexeme  case       phono  tir1
40            avoir  pi3S           a    82
166      abandonner  ppFS    abɑ̃dɔne     2
243         abattre  pi3S         aba     1
299         abattre   inf       abatʁ     1
869          aboyer  pi3P        abwa     1
1457         aboyer  ii3P      abwajɛ     1
1684        abriter  pi3S       abʁit     1
2100       absorber  ppMS     absɔʁbe     1
2106       absorber  ppMP     absɔʁbe     1
2581         abîmer   inf       abime     1
2904      accentuer   inf    aksɑ̃tye     1
2946       accepter  ai1S     aksɛptɛ     1
2971       accepter   inf     aksɛpte     1
2980       accepter  pc2P  aksɛptəʁje     1
2997       accepter  pi1P    aksɛptɔ̃     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3419    accompagner  pi2S     akɔ̃paɲ     1
3422    accompagner  pi2P    akɔ̃paɲe     1
3435    accompagner  ppFP    akɔ̃paɲe     1
3443      accomplir   inf    akɔ̃pliʁ     1
4291      accrocher  ppMS      akʁɔʃe     1
4688        accuser  ai3S       akyza     1
5005       acharner  pi1S       aʃaʁn     1
5040       acharner  ai3P     aʃaʁnɛʁ     1
5108        acheter  ii3P       aʃətɛ     1
5119        acheter   inf       aʃəte     1
5126        acheter  ii2P      aʃətje     1
5136        acheter  ppMS       aʃəte     3
5147        achever  ii1S       aʃəvɛ     1
5807       acquérir  ppMS         aki     1
...             ...   ...         ...   ...
430183     épaissir    pP    ɛpɛsisɑ̃     1
431160        épier  pi1S         ɛpi     1
431853     éplucher  ii3P      ɛplyʃɛ     1
432160      épouser   inf       ɛpuze     1
432302      épouser  ppMS       ɛpuze     1
432552     éprouver  pi3S       ɛpʁuv     1
433912      établir  ppMS      ɛtabli     1
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ    12
434070         être  ii3S         ɛtɛ    68
434762     éteindre   inf      ɛtɛ̃dʁ     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     2
435294       étirer  ppFS       ɛtiʁe     1
435318      étoffer  pi3S        ɛtɔf     1
435410      étoiler  ppFS      ɛtwale     1
435435      étonner  pi1S        ɛtɔn     1
435438      étonner  pi3S        ɛtɔn     1
435439      étonner  ps3S        ɛtɔn     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436186      étudier  ii3S      ɛtydjɛ     1
436201      étudier  pi3S       ɛtydi     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    31
436820     éveiller  ii3S       ɛvɛjɛ     1
436831     éveiller  pi3S        ɛvɛj     1
437273       éviter  ai3S       ɛvita     1
437301       éviter   inf       ɛvite     1
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    21

[1960 rows x 4 columns]

0
CPU times: user 54.5 s, sys: 16 s, total: 1min 10s
Wall time: 34.8 s

nbChunk 80
4200
1996

             lexeme  case       phono  tir1
40            avoir  pi3S           a    86
45         abaisser  ai3S       abɛsa     1
109      abandonner  ai1S    abɑ̃dɔnɛ     1
128      abandonner  pi3S     abɑ̃dɔn     1
170      abandonner  ppMP    abɑ̃dɔne     1
1178        aborder  ppMP      abɔʁde     1
1688        abriter   inf      abʁite     1
2774      accaparer  ii3S     akapaʁɛ     1
2950       accepter  ii3S     aksɛptɛ     1
2969       accepter  pi3P      aksɛpt     1
2971       accepter   inf     aksɛpte     1
2978       accepter  fi2S   aksɛptəʁa     1
3003       accepter  ppMS     aksɛpte     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3407    accompagner  fi3S  akɔ̃paɲəʁa     1
3436    accompagner  ppMP    akɔ̃paɲe     1
4479     accueillir  pi1S        akœj     1
4783        accéder   inf      aksɛde     1
5108        acheter  ii3P       aʃətɛ     1
5119        acheter   inf       aʃəte     1
5126        acheter  ii2P      aʃətje     1
5137        acheter  ppFS       aʃəte     1
5157        achever   inf       aʃəve     1
5171        achever  ppMS       aʃəve     1
5308        acheter  pi1S        aʃɛt     1
5311        acheter  pi3S        aʃɛt     1
5313        acheter  pi3P        aʃɛt     1
7312         adorer  pi3S        adɔʁ     2
7313         adorer  ps3S        adɔʁ     1
7316         adorer   inf       adɔʁe     1
...             ...   ...         ...   ...
429700      énerver   inf      ɛnɛʁve     1
430727       épater  ppMP       ɛpate     1
432160      épouser   inf       ɛpuze     1
432519     éprendre  ppMS        ɛpʁi     1
433429     érailler  ppMS       ɛʁaje     1
433912      établir  ppMS      ɛtabli     1
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ    12
434069         être  ii2S         ɛtɛ     1
434070         être  ii3S         ɛtɛ    79
434839      étendre  ppMP      ɛtɑ̃dy     1
434868    éterniser   inf    ɛtɛʁnize     1
435172         être  ii1P       ɛtjɔ̃     1
435254       étirer  pi3S        ɛtiʁ     1
435260       étirer   inf       ɛtiʁe     1
435420      étonner  ii1S       ɛtɔnɛ     1
435540     étouffer  ppFS       ɛtufe     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
435749    étrangler  fi3S  ɛtʁɑ̃gləʁa     1
436205      étudier   inf      ɛtydje     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    19
436457       évader   inf       ɛvade     1
437281       éviter  ii3P       ɛvitɛ     1
437292       éviter  pi1S        ɛvit     1
437328       éviter  ppMS       ɛvite     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    22
437539         ôter  ppMS         ɔte     1

[1996 rows x 4 columns]

0
CPU times: user 54 s, sys: 15.8 s, total: 1min 9s
Wall time: 34.5 s

nbChunk 81
4200
1941

             lexeme  case     phono  tir1
40            avoir  pi3S         a    82
45         abaisser  ai3S     abɛsa     1
67         abaisser  pi3S      abɛs     1
108      abandonner  ai3S  abɑ̃dɔna     1
125      abandonner  pi1S   abɑ̃dɔn     1
164      abandonner  ppMS  abɑ̃dɔne     2
287         abattre  ai3S     abati     1
292         abattre  fi3S    abatʁa     1
973         abonder  is3P   abɔ̃das     1
1169        aborder  pi1P   abɔʁdɔ̃     1
1796        abrutir  ppMS    abʁyti     1
1950       absenter   inf   absɑ̃te     1
2070       absorber   inf   absɔʁbe     1
2967       accepter  pi3S    aksɛpt     1
2971       accepter   inf   aksɛpte     1
3117       acclamer   inf    aklame     1
3382    accompagner  ii3P  akɔ̃paɲɛ     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     1
3519       accorder  ii3S    akɔʁdɛ     1
4252      accrocher  pi1S     akʁɔʃ     1
4255      accrocher  pi3S     akʁɔʃ     1
4373      accroître  pi3S     akʁwa     1
4470     accueillir  ii3P     akəjɛ     1
4726        accuser  pc3S   akyzəʁɛ     1
4748        accuser  ppMS     akyze     1
4750        accuser  ppFS     akyze     1
4816      accélérer  pi2S   aksɛlɛʁ     1
5119        acheter   inf     aʃəte     1
5136        acheter  ppMS     aʃəte     2
...             ...   ...       ...   ...
430592     épargner  ppFP    ɛpaʁɲe     1
431856     éplucher  ii3S    ɛplyʃɛ     1
432144      épouser  ii3S     ɛpuzɛ     1
432153      épouser  pi1S      ɛpuz     1
432537     éprouver  ii3S    ɛpʁuvɛ     1
433169      équiper  ppMS     ɛkipe     1
433968      établir  ai3S    ɛtabli     1
434048         être  ii3P       ɛtɛ     5
434068         être  ii1S       ɛtɛ     9
434070         être  ii3S       ɛtɛ    73
434134       étaler  ii3S     ɛtalɛ     1
434144       étaler  pi1S      ɛtal     1
434300       étaler  ppFS     ɛtale     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
434773     éteindre  pi3S      ɛtɛ̃     1
434831      étendre  ppMS    ɛtɑ̃dy     1
434923     éternuer   inf   ɛtɛʁnye     1
435054         être  ii2P      ɛtje     1
435475     étouffer  ai3S     ɛtufa     1
435506     étouffer   inf     ɛtufe     2
436205      étudier   inf    ɛtydje     1
436316         être  ppMS       ɛte    23
436402      évacuer   inf    ɛvakye     1
436418      évacuer  pi2P    ɛvakye     1
436679     évanouir  pi3S    ɛvanui     1
437301       éviter   inf     ɛvite     1
437417      évoquer    pP    ɛvɔkɑ̃     1
437474         être  pi2P        ɛt    18
437476         être   inf       ɛtʁ    20
437528         ôter  pi2P       ɔte     1

[1941 rows x 4 columns]

0
CPU times: user 54.2 s, sys: 15.4 s, total: 1min 9s
Wall time: 34.2 s

nbChunk 82
4200
1970

             lexeme  case      phono  tir1
40            avoir  pi3S          a    98
132      abandonner   inf   abɑ̃dɔne     1
168      abandonner  ppFP   abɑ̃dɔne     1
1112        abonner  ppFS      abɔne     1
1543        abraser  ppMS     abʁaze     1
1688        abriter   inf     abʁite     1
2332         abuser  pi1S       abyz     1
2887      accentuer  ii3S   aksɑ̃tyɛ     1
2904      accentuer   inf   aksɑ̃tye     1
2964       accepter  pi1S     aksɛpt     1
2967       accepter  pi3S     aksɛpt     1
2972       accepter  fi3S  aksɛptəʁa     1
3003       accepter  ppMS    aksɛpte     1
3096       acclamer  ii3S     aklamɛ     1
3397    accompagner  pi1S    akɔ̃paɲ     1
3460      accomplir  pi1S    akɔ̃pli     1
4063       accourir  pi3P       akuʁ     1
4255      accrocher  pi3S      akʁɔʃ     1
4637      accumuler  ii3S    akymylɛ     1
4652      accumuler  pi3S     akymyl     1
4783        accéder   inf     aksɛde     1
4862      accélérer  ppMS   aksɛlɛʁe     1
4864      accélérer  ppFS   aksɛlɛʁe     1
5102        acheter  ai3S      aʃəta     1
5119        acheter   inf      aʃəte     4
5136        acheter  ppMS      aʃəte     1
5316        acheter  fi1S    aʃɛtəʁɛ     1
6443        adapter  ppMS     adapte     1
6567        adhérer  pi2P      adɛʁe     1
6891       admettre   inf     admɛtʁ     1
...             ...   ...        ...   ...
426731      élargir  ii3S   ɛlaʁʒisɛ     1
427322       élever  ppMS      ɛləve     1
427641     éloigner   inf     ɛlwaɲe     1
427783     élucider  ppMS    ɛlyside     1
429700      énerver   inf     ɛnɛʁve     1
430558     épargner  pi3S      ɛpaʁɲ     1
431980      éponger  ii3S     ɛpɔ̃ʒɛ     1
432160      épouser   inf      ɛpuze     1
432552     éprouver  pi3S      ɛpʁuv     2
432634      épuiser  ai1S     ɛpɥizɛ     1
432638      épuiser  ii3S     ɛpɥizɛ     1
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ     9
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    74
434729     éteindre  ps3S       ɛtɛɲ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
434839      étendre  ppMP     ɛtɑ̃dy     1
435172         être  ii1P      ɛtjɔ̃     2
435422      étonner  ii3S      ɛtɔnɛ     2
435425      étonner    pP     ɛtɔnɑ̃     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
436201      étudier  pi3S      ɛtydi     1
436203      étudier  pi3P      ɛtydi     1
436205      étudier   inf     ɛtydje     2
436316         être  ppMS        ɛte    23
436457       évader   inf      ɛvade     1
436835     éveiller   inf      ɛvɛje     1
437474         être  pi2P         ɛt    13
437476         être   inf        ɛtʁ    19

[1970 rows x 4 columns]

0
CPU times: user 53 s, sys: 15 s, total: 1min 8s
Wall time: 33.8 s

nbChunk 83
4200
1912

             lexeme  case       phono  tir1
40            avoir  pi3S           a    79
164      abandonner  ppMS    abɑ̃dɔne     2
170      abandonner  ppMP    abɑ̃dɔne     2
177      abasourdir  ppMS    abazuʁdi     1
299         abattre   inf       abatʁ     2
313         abattre  ppMP       abaty     1
890          abolir   inf      abɔliʁ     1
1132        aborder  ii3S      abɔʁdɛ     1
1393        aboutir   inf      abutiʁ     1
2228       abstenir  pi2S     abstjɛ̃     1
2322         abuser  ii1S       abyzɛ     1
3003       accepter  ppMS     aksɛpte     1
3349     accommoder   inf     akɔmɔde     1
3406    accompagner   inf    akɔ̃paɲe     1
3414    accompagner  fi2P  akɔ̃paɲəʁe     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3564       accorder  pi1P     akɔʁdɔ̃     1
4291      accrocher  ppMS      akʁɔʃe     1
4294      accrocher  ppMP      akʁɔʃe     1
4502     accueillir  ppMS       akəji     1
4519     accueillir  ai3S       akəji     1
4718        accuser  pi3P        akyz     1
4720        accuser   inf       akyze     1
4783        accéder   inf      aksɛde     1
5119        acheter   inf       aʃəte     2
5131        acheter  pi1P      aʃətɔ̃     1
5136        acheter  ppMS       aʃəte     1
5149        achever  ii3S       aʃəvɛ     1
5157        achever   inf       aʃəve     1
5758     acquiescer  pi3S       akjɛs     1
...             ...   ...         ...   ...
427294       élever  ii1S       ɛləvɛ     1
427668     éloigner  ppMS      ɛlwaɲe     1
428167     émailler  ppMS       ɛmaje     1
428442      émerger  ai3P     ɛmɛʁʒɛʁ     1
429691      énerver  pi1S       ɛnɛʁv     1
432153      épouser  pi1S        ɛpuz     1
432160      épouser   inf       ɛpuze     2
432533     éprouver  ai1S      ɛpʁuvɛ     1
433912      établir  ppMS      ɛtabli     1
434048         être  ii3P         ɛtɛ     6
434068         être  ii1S         ɛtɛ    18
434070         être  ii3S         ɛtɛ    72
434727     éteindre    pP      ɛtɛɲɑ̃     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     2
435438      étonner  pi3S        ɛtɔn     1
435544     étouffer  ppMP       ɛtufe     1
435656     étourdir  ppFS      ɛtuʁdi     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436205      étudier   inf      ɛtydje     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    12
436402      évacuer   inf      ɛvakye     1
437301       éviter   inf       ɛvite     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437431      évoquer   inf       ɛvɔke     1
437458      évoquer  ppMS       ɛvɔke     1
437474         être  pi2P          ɛt    19
437476         être   inf         ɛtʁ    14

[1912 rows x 4 columns]

0
CPU times: user 1min 1s, sys: 15 s, total: 1min 16s
Wall time: 33.2 s

nbChunk 84
4200
1969

             lexeme  case     phono  tir1
40            avoir  pi3S         a    73
109      abandonner  ai1S  abɑ̃dɔnɛ     1
125      abandonner  pi1S   abɑ̃dɔn     1
132      abandonner   inf  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     2
1393        aboutir   inf    abutiʁ     1
2051       absorber  ii3S   absɔʁbɛ     1
2964       accepter  pi1S    aksɛpt     1
2989       accepter  pi2P   aksɛpte     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3422    accompagner  pi2P  akɔ̃paɲe     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3530       accorder  pi3S     akɔʁd     1
4072       accourir   inf    akuʁiʁ     1
4090       accourir  pi3S      akuʁ     1
4252      accrocher  pi1S     akʁɔʃ     1
4323      accroupir   inf   akʁupiʁ     1
4368      accroupir  ai3S    akʁupi     2
4381      accroître   inf   akʁwatʁ     1
4482     accueillir  pi3S      akœj     2
4716        accuser  pi3S      akyz     1
4736        accuser  pi2P     akyze     1
4835      accélérer   inf  aksɛlɛʁe     1
5119        acheter   inf     aʃəte     5
5136        acheter  ppMS     aʃəte     1
5308        acheter  pi1S      aʃɛt     1
5311        acheter  pi3S      aʃɛt     1
5316        acheter  fi1S   aʃɛtəʁɛ     1
6072        activer   inf    aktive     1
6085        activer  pi2S     aktiv     1
...             ...   ...       ...   ...
434070         être  ii3S       ɛtɛ    59
434302       étaler  ppMP     ɛtale     1
434488         être    pP      ɛtɑ̃     1
434788      étendre  ii3S    ɛtɑ̃dɛ     1
434789      étendre    pP   ɛtɑ̃dɑ̃     1
434811      étendre  ai3S    ɛtɑ̃di     1
434936     éternuer  pi2S    ɛtɛʁny     1
435054         être  ii2P      ɛtje     1
435062    étinceler  ii3S  ɛtɛ̃səlɛ     1
435085    étinceler  pi3S   ɛtɛ̃sɛl     1
435172         être  ii1P     ɛtjɔ̃     1
435244       étirer    pP    ɛtiʁɑ̃     1
435438      étonner  pi3S      ɛtɔn     1
435474      étonner  ppMP     ɛtɔne     1
435748    étrangler   inf  ɛtʁɑ̃gle     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    19
436400      évacuer  pi3P     ɛvaky     1
436513      évaluer  pi1S     ɛvaly     1
436835     éveiller   inf     ɛvɛje     3
436869     éveiller  ppFS     ɛvɛje     1
437273       éviter  ai3S     ɛvita     1
437285       éviter    pP    ɛvitɑ̃     1
437301       éviter   inf     ɛvite     1
437307       éviter  pc3S   ɛvitəʁɛ     1
437416      évoquer  ii3S     ɛvɔkɛ     1
437417      évoquer    pP    ɛvɔkɑ̃     1
437431      évoquer   inf     ɛvɔke     1
437474         être  pi2P        ɛt    17
437476         être   inf       ɛtʁ    21

[1969 rows x 4 columns]

0
CPU times: user 57.2 s, sys: 15.5 s, total: 1min 12s
Wall time: 33.6 s

nbChunk 85
4200
1948

             lexeme  case      phono  tir1
40            avoir  pi3S          a    98
114      abandonner    pP  abɑ̃dɔnɑ̃     1
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     4
980         abonder  pi3S      abɔ̃d     1
1688        abriter   inf     abʁite     1
2070       absorber   inf    absɔʁbe     1
2102       absorber  ppFS    absɔʁbe     1
2371         abuser  ppMS      abyze     1
2684     acagnarder  ppMS   akaɲaʁde     1
2713       accabler  ii1S     akablɛ     1
2946       accepter  ai1S    aksɛptɛ     1
2952       accepter    pP   aksɛptɑ̃     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     3
3003       accepter  ppMS    aksɛpte     1
3406    accompagner   inf   akɔ̃paɲe     1
3914       accouder  ppFS      akude     1
4293      accrocher  ppFP     akʁɔʃe     1
4354      accroupir  pi3P    akʁupis     1
4373      accroître  pi3S      akʁwa     1
4717        accuser  ps3S       akyz     1
5119        acheter   inf      aʃəte     2
5311        acheter  pi3S       aʃɛt     1
6891       admettre   inf     admɛtʁ     1
6969        admirer  ii3S     admiʁɛ     1
7023        admirer  ppMS     admiʁe     1
7295         adorer  ii1S      adɔʁɛ     1
7567       adresser  ppMS     adʁɛse     1
7570       adresser  ppMP     adʁɛse     1
...             ...   ...        ...   ...
432653      épuiser  pi3S      ɛpɥiz     1
432659      épuiser   inf     ɛpɥize     1
432997   équilibrer  ai3S   ɛkilibʁa     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    13
434070         être  ii3S        ɛtɛ    56
434302       étaler  ppMP      ɛtale     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434768     éteindre  pi1S       ɛtɛ̃     1
434772     éteindre  ppMS       ɛtɛ̃     1
434782      étendre  pi3S       ɛtɑ̃     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     4
435422      étonner  ii3S      ɛtɔnɛ     2
435438      étonner  pi3S       ɛtɔn     1
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435460      étonner  pi2P      ɛtɔne     1
435471      étonner  ppMS      ɛtɔne     1
435500     étouffer  pi3S       ɛtuf     1
435920     étriller   inf     ɛtʁije     1
436316         être  ppMS        ɛte    32
436820     éveiller  ii3S      ɛvɛjɛ     1
436873     éveiller  ppMP      ɛvɛje     1
437301       éviter   inf      ɛvite     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    18
437476         être   inf        ɛtʁ    16
437492         ôter  ai3S        ɔta     1

[1948 rows x 4 columns]

0
CPU times: user 54.2 s, sys: 15.4 s, total: 1min 9s
Wall time: 35.3 s

nbChunk 86
4200
1958

             lexeme  case     phono  tir1
40            avoir  pi3S         a    77
890          abolir   inf    abɔliʁ     1
919          abolir  pi3P    abɔlis     1
1673        abriter  ii3S    abʁitɛ     2
2138       abstenir  pi2P   abstəne     1
2610         abîmer  ppMS     abime     1
2715       accabler  ii3S    akablɛ     1
2766       accabler  ppMP    akable     1
2964       accepter  pi1S    aksɛpt     1
2967       accepter  pi3S    aksɛpt     1
3003       accepter  ppMS   aksɛpte     1
3385    accompagner  ii3S  akɔ̃paɲɛ     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     1
3434    accompagner  ppFS  akɔ̃paɲe     1
3516       accorder  ii3P    akɔʁdɛ     1
3536       accorder   inf    akɔʁde     1
3949      accoupler  ii3P    akuplɛ     1
4259      accrocher   inf    akʁɔʃe     1
4261      accrocher  fi1S  akʁɔʃəʁɛ     1
4291      accrocher  ppMS    akʁɔʃe     1
4292      accrocher  ppFS    akʁɔʃe     1
4293      accrocher  ppFP    akʁɔʃe     1
4509     accueillir   inf    akəjiʁ     1
4634      accumuler  ii3P   akymylɛ     1
4637      accumuler  ii3S   akymylɛ     1
4688        accuser  ai3S     akyza     1
5014       acharner   inf    aʃaʁne     1
5119        acheter   inf     aʃəte     1
5136        acheter  ppMS     aʃəte     4
...             ...   ...       ...   ...
432695      épuiser  ppMP    ɛpɥize     1
433316      érafler  pi1S     ɛʁafl     1
433555     éreinter  ppFS    ɛʁɛ̃te     1
433914      établir  ppFS    ɛtabli     1
433943      établir  ii3P  ɛtablisɛ     1
434048         être  ii3P       ɛtɛ     8
434068         être  ii1S       ɛtɛ    10
434070         être  ii3S       ɛtɛ    79
434134       étaler  ii3S     ɛtalɛ     1
434762     éteindre   inf    ɛtɛ̃dʁ     3
434868    éterniser   inf  ɛtɛʁnize     1
435054         être  ii2P      ɛtje     2
435135      étioler   inf    ɛtjɔle     1
435172         être  ii1P     ɛtjɔ̃     3
435228    étiqueter  ppMS   ɛtikəte     1
435425      étonner    pP    ɛtɔnɑ̃     1
435438      étonner  pi3S      ɛtɔn     1
435471      étonner  ppMS     ɛtɔne     1
435484     étouffer  ii3S     ɛtufɛ     1
435500     étouffer  pi3S      ɛtuf     1
435794    étreindre  ii3S    ɛtʁɛɲɛ     1
435828    étreindre   inf   ɛtʁɛ̃dʁ     2
435839    étreindre  ppFS    ɛtʁɛ̃t     1
436316         être  ppMS       ɛte    11
437301       éviter   inf     ɛvite     1
437431      évoquer   inf     ɛvɔke     1
437461      évoquer  ppMP     ɛvɔke     1
437474         être  pi2P        ɛt    18
437476         être   inf       ɛtʁ    16
437512         ôter   inf       ɔte     1

[1958 rows x 4 columns]

0
CPU times: user 59.8 s, sys: 18.2 s, total: 1min 17s
Wall time: 34.5 s

nbChunk 87
4200
1972

            lexeme  case     phono  tir1
40           avoir  pi3S         a    98
132     abandonner   inf  abɑ̃dɔne     1
148     abandonner  pi2P  abɑ̃dɔne     1
164     abandonner  ppMS  abɑ̃dɔne     1
1175       aborder  ppMS    abɔʁde     1
1688       abriter   inf    abʁite     1
1796       abrutir  ppMS    abʁyti     1
2070      absorber   inf   absɔʁbe     1
2371        abuser  ppMS     abyze     1
2612        abîmer  ppFS     abime     2
2939      accepter  ai3S   aksɛpta     1
3003      accepter  ppMS   aksɛpte     2
3519      accorder  ii3S    akɔʁdɛ     1
3536      accorder   inf    akɔʁde     1
3862      accouder  ai3S     akuda     1
4255     accrocher  pi3S     akʁɔʃ     1
4482    accueillir  pi3S      akœj     1
4511    accueillir  ppMP     akəji     1
5041      acharner  ppMS    aʃaʁne     1
5149       achever  ii3S     aʃəvɛ     1
5157       achever   inf     aʃəve     2
5311       acheter  pi3S      aʃɛt     1
5884      acquérir  ps3S     akjɛʁ     1
6991       admirer  pi3S     admiʁ     1
6996       admirer   inf    admiʁe     1
7028      admettre  ppMS      admi     1
7312        adorer  pi3S      adɔʁ     1
7518      adresser  ai3S    adʁɛsa     1
8567      afficher  pi2S      afiʃ     1
10078      agencer   inf    aʒɑ̃se     1
...            ...   ...       ...   ...
430156    épaissir  ppFS     ɛpɛsi     1
431856    éplucher  ii3S    ɛplyʃɛ     1
432537    éprouver  ii3S    ɛpʁuvɛ     1
432683     épuiser  pi1P   ɛpɥizɔ̃     1
433195  équivaloir  ii3S   ɛkivalɛ     1
434048        être  ii3P       ɛtɛ     6
434068        être  ii1S       ɛtɛ    11
434069        être  ii2S       ɛtɛ     2
434070        être  ii3S       ɛtɛ    74
434762    éteindre   inf    ɛtɛ̃dʁ     1
434772    éteindre  ppMS      ɛtɛ̃     1
434773    éteindre  pi3S      ɛtɛ̃     1
434811     étendre  ai3S    ɛtɑ̃di     1
435054        être  ii2P      ɛtje     2
435172        être  ii1P     ɛtjɔ̃     2
435437     étonner  pI2S      ɛtɔn     1
435438     étonner  pi3S      ɛtɔn     2
435471     étonner  ppMS     ɛtɔne     2
435497    étouffer  pi1S      ɛtuf     1
435500    étouffer  pi3S      ɛtuf     1
435542    étouffer  ppFP     ɛtufe     1
435742   étrangler  pi3S   ɛtʁɑ̃gl     1
436002     étriper  ppMP    ɛtʁipe     1
436316        être  ppMS       ɛte    32
436457      évader   inf     ɛvade     1
436469      évader  fi3P  ɛvadəʁɔ̃     1
437040     éventer  ppMS    ɛvɑ̃te     1
437427     évoquer  pi3S      ɛvɔk     1
437474        être  pi2P        ɛt    15
437476        être   inf       ɛtʁ    25

[1972 rows x 4 columns]

0
CPU times: user 1min 2s, sys: 22 s, total: 1min 24s
Wall time: 35.9 s

nbChunk 88
4200
1977

             lexeme  case       phono  tir1
40            avoir  pi3S           a    84
132      abandonner   inf    abɑ̃dɔne     2
164      abandonner  ppMS    abɑ̃dɔne     2
261         abattre  ps3S        abat     1
305         abattre  ppMS       abaty     1
1147        aborder   inf      abɔʁde     2
1388        aboutir  ppMS       abuti     2
1796        abrutir  ppMS      abʁyti     2
2339         abuser   inf       abyze     1
2371         abuser  ppMS       abyze     1
2565         abîmer  ii3S       abimɛ     1
2736       accabler   inf      akable     1
2939       accepter  ai3S     aksɛpta     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3407    accompagner  fi3S  akɔ̃paɲəʁa     1
3419    accompagner  pi2S     akɔ̃paɲ     1
3432    accompagner  ai3P   akɔ̃paɲɛʁ     1
3443      accomplir   inf    akɔ̃pliʁ     2
3818      accoucher  pi1S        akuʃ     1
3821      accoucher  pi3S        akuʃ     1
3827      accoucher   inf       akuʃe     1
4259      accrocher   inf      akʁɔʃe     1
4292      accrocher  ppFS      akʁɔʃe     1
4293      accrocher  ppFP      akʁɔʃe     1
4323      accroupir   inf     akʁupiʁ     1
4482     accueillir  pi3S        akœj     1
4509     accueillir   inf      akəjiʁ     2
...             ...   ...         ...   ...
429694      énerver  pi3S       ɛnɛʁv     1
429727      énerver  ppMS      ɛnɛʁve     1
429830      énoncer  ppFS      ɛnɔ̃se     1
430156     épaissir  ppFS       ɛpɛsi     1
432160      épouser   inf       ɛpuze     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
432556     éprouver   inf      ɛpʁuve     1
432659      épuiser   inf      ɛpɥize     1
432689      épuiser  ppMS      ɛpɥize     2
433299    éradiquer  ppMS     ɛʁadike     1
433943      établir  ii3P    ɛtablisɛ     1
434048         être  ii3P         ɛtɛ     7
434068         être  ii1S         ɛtɛ    14
434070         être  ii3S         ɛtɛ    83
434134       étaler  ii3S       ɛtalɛ     1
434831      étendre  ppMS      ɛtɑ̃dy     1
434833      étendre  ppFS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     3
435172         être  ii1P       ɛtjɔ̃     2
435244       étirer    pP      ɛtiʁɑ̃     1
435794    étreindre  ii3S      ɛtʁɛɲɛ     1
436205      étudier   inf      ɛtydje     2
436316         être  ppMS         ɛte    22
436627     évanouir  ppMS      ɛvanui     1
437273       éviter  ai3S       ɛvita     1
437301       éviter   inf       ɛvite     3
437307       éviter  pc3S     ɛvitəʁɛ     1
437432      évoquer  fi3S     ɛvɔkəʁa     2
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    22

[1977 rows x 4 columns]

0
CPU times: user 57.9 s, sys: 18.3 s, total: 1min 16s
Wall time: 36.6 s

nbChunk 89
4200
1992

             lexeme  case     phono  tir1
40            avoir  pi3S         a    80
132      abandonner   inf  abɑ̃dɔne     2
170      abandonner  ppMP  abɑ̃dɔne     1
287         abattre  ai3S     abati     1
1143        aborder  pi3S     abɔʁd     1
2143       abstenir   inf  abstəniʁ     1
2324         abuser  ii3S     abyzɛ     1
2715       accabler  ii3S    akablɛ     1
2969       accepter  pi3P    aksɛpt     1
2971       accepter   inf   aksɛpte     1
2997       accepter  pi1P  aksɛptɔ̃     1
2999       accepter  is3S   aksɛpta     1
3003       accepter  ppMS   aksɛpte     1
3005       accepter  ppFS   aksɛpte     1
3380    accompagner  ai3S  akɔ̃paɲa     1
3419    accompagner  pi2S   akɔ̃paɲ     1
3913       accouder  ppMS     akude     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4259      accrocher   inf    akʁɔʃe     1
4292      accrocher  ppFS    akʁɔʃe     1
4321      accroupir  ppFS    akʁupi     1
4473     accueillir  ii3S     akəjɛ     1
4726        accuser  pc3S   akyzəʁɛ     1
5111        acheter  ii3S     aʃətɛ     1
5119        acheter   inf     aʃəte     2
5136        acheter  ppMS     aʃəte     2
5137        acheter  ppFS     aʃəte     1
5139        acheter  ppMP     aʃəte     1
5140        achever  ai3S     aʃəva     2
6996        admirer   inf    admiʁe     1
...             ...   ...       ...   ...
431571     épingler  pi3S    ɛpɛ̃gl     1
431856     éplucher  ii3S    ɛplyʃɛ     1
431909     éplucher  ppMP    ɛplyʃe     1
432153      épouser  pi1S      ɛpuz     1
432160      épouser   inf     ɛpuze     1
432173      épouser  pi2S      ɛpuz     1
433930      établir  ai3P   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     5
434068         être  ii1S       ɛtɛ    13
434070         être  ii3S       ɛtɛ    73
434134       étaler  ii3S     ɛtalɛ     1
434151       étaler  pi3P      ɛtal     1
434770     éteindre  pi2S      ɛtɛ̃     1
434773     éteindre  pi3S      ɛtɛ̃     1
434811      étendre  ai3S    ɛtɑ̃di     1
434812      étendre  pI1P   ɛtɑ̃dɔ̃     1
434821      étendre   inf    ɛtɑ̃dʁ     1
434936     éternuer  pi2S    ɛtɛʁny     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     1
435419      étonner  ii3P     ɛtɔnɛ     1
435422      étonner  ii3S     ɛtɔnɛ     1
435542     étouffer  ppFP     ɛtufe     1
436205      étudier   inf    ɛtydje     1
436218      étudier  pi2S     ɛtydi     1
436316         être  ppMS       ɛte    28
436457       évader   inf     ɛvade     1
437367      évoluer   inf    ɛvɔlye     1
437474         être  pi2P        ɛt    12
437476         être   inf       ɛtʁ    23

[1992 rows x 4 columns]

0
CPU times: user 1min, sys: 21.7 s, total: 1min 22s
Wall time: 33.6 s

nbChunk 90
4200
1907

             lexeme  case      phono  tir1
40            avoir  pi3S          a    88
113      abandonner  ii3S   abɑ̃dɔnɛ     1
114      abandonner    pP  abɑ̃dɔnɑ̃     1
132      abandonner   inf   abɑ̃dɔne     2
164      abandonner  ppMS   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
2070       absorber   inf    absɔʁbe     1
2371         abuser  ppMS      abyze     1
2971       accepter   inf    aksɛpte     2
2988       accepter  pI2P    aksɛpte     1
3386    accompagner    pP  akɔ̃paɲɑ̃     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     3
3530       accorder  pi3S      akɔʁd     1
3536       accorder   inf     akɔʁde     1
3558       accorder  ps2P    akɔʁdje     1
3583       accorder  ppMP     akɔʁde     1
4292      accrocher  ppFS     akʁɔʃe     1
4509     accueillir   inf     akəjiʁ     1
4693        accuser  ii3S      akyzɛ     1
4716        accuser  pi3S       akyz     2
4720        accuser   inf      akyze     1
4783        accéder   inf     aksɛde     2
5119        acheter   inf      aʃəte     1
5136        acheter  ppMS      aʃəte     2
5137        acheter  ppFS      aʃəte     2
5325        acheter  fi1P   aʃɛtəʁɔ̃     1
5350        achever  pi2S       aʃɛv     1
6891       admettre   inf     admɛtʁ     1
6991        admirer  pi3S      admiʁ     2
...             ...   ...        ...   ...
431867     éplucher  pi3S      ɛplyʃ     1
432302      épouser  ppMS      ɛpuze     1
432386   épouvanter  pi3S    ɛpuvɑ̃t     1
432659      épuiser   inf     ɛpɥize     1
434048         être  ii3P        ɛtɛ     6
434068         être  ii1S        ɛtɛ     9
434070         être  ii3S        ɛtɛ    78
434724     éteindre  ii1S      ɛtɛɲɛ     1
434747     éteindre  ai3S      ɛtɛɲi     1
434777     éteindre  ppFP      ɛtɛ̃t     1
434785      étendre  ii3P     ɛtɑ̃dɛ     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434839      étendre  ppMP     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     1
435422      étonner  ii3S      ɛtɔnɛ     1
435444      étonner   inf      ɛtɔne     1
435475     étouffer  ai3S      ɛtufa     1
435481     étouffer  ii3P      ɛtufɛ     1
435500     étouffer  pi3S       ɛtuf     1
435506     étouffer   inf      ɛtufe     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    19
436632     évanouir   inf    ɛvanuiʁ     1
436664     évanouir  pi3P    ɛvanuis     1
437292       éviter  pi1S       ɛvit     1
437301       éviter   inf      ɛvite     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    22
437476         être   inf        ɛtʁ    22

[1907 rows x 4 columns]

0
CPU times: user 1min 5s, sys: 19.6 s, total: 1min 25s
Wall time: 33.2 s

nbChunk 91
4200
1937

             lexeme  case       phono  tir1
40            avoir  pi3S           a    92
108      abandonner  ai3S    abɑ̃dɔna     1
130      abandonner  pi3P     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     2
297         abattre  pc3S      abatʁɛ     1
299         abattre   inf       abatʁ     1
305         abattre  ppMS       abaty     1
1147        aborder   inf      abɔʁde     1
1307        abouler  pi3S        abul     1
1688        abriter   inf      abʁite     1
2138       abstenir  pi2P     abstəne     1
2215       abstenir  fi2S  abstjɛ̃dʁa     1
2324         abuser  ii3S       abyzɛ     1
2971       accepter   inf     aksɛpte     2
2989       accepter  pi2P     aksɛpte     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3468      accomplir    pP  akɔ̃plisɑ̃     1
3818      accoucher  pi1S        akuʃ     1
3821      accoucher  pi3S        akuʃ     1
3858      accoucher  ppMS       akuʃe     1
3916       accouder  ppMP       akude     1
4094       accourir  ai3P      akuʁyʁ     1
4279      accrocher  pI2P      akʁɔʃe     1
4280      accrocher  pi2P      akʁɔʃe     2
4294      accrocher  ppMP      akʁɔʃe     1
4713        accuser  pi1S        akyz     1
4783        accéder   inf      aksɛde     1
5119        acheter   inf       aʃəte     3
5136        acheter  ppMS       aʃəte     1
...             ...   ...         ...   ...
429367     émouvoir  ppFS         ɛmy     1
429727      énerver  ppMS      ɛnɛʁve     1
430486     épanouir  fi3S    ɛpanuiʁa     1
431609     épingler  ppMS     ɛpɛ̃gle     1
432145      épouser    pP      ɛpuzɑ̃     1
432160      épouser   inf       ɛpuze     1
432216   épousseter  pi3S      ɛpusɛt     1
432533     éprouver  ai1S      ɛpʁuvɛ     2
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    80
434451     étancher   inf      ɛtɑ̃ʃe     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434768     éteindre  pi1S        ɛtɛ̃     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     2
435244       étirer    pP      ɛtiʁɑ̃     1
435435      étonner  pi1S        ɛtɔn     1
435471      étonner  ppMS       ɛtɔne     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436186      étudier  ii3S      ɛtydjɛ     1
436233      étudier  ppMS      ɛtydje     2
436316         être  ppMS         ɛte    20
437049     évertuer  ii3S     ɛvɛʁtyɛ     1
437301       éviter   inf       ɛvite     3
437417      évoquer    pP      ɛvɔkɑ̃     1
437474         être  pi2P          ɛt    10
437476         être   inf         ɛtʁ    19
437512         ôter   inf         ɔte     1

[1937 rows x 4 columns]

0
CPU times: user 1min 3s, sys: 23 s, total: 1min 26s
Wall time: 32.8 s

nbChunk 92
4200
1926

             lexeme  case     phono  tir1
40            avoir  pi3S         a    95
132      abandonner   inf  abɑ̃dɔne     1
145      abandonner  pi2S   abɑ̃dɔn     1
243         abattre  pi3S       aba     1
299         abattre   inf     abatʁ     1
1143        aborder  pi3S     abɔʁd     1
1147        aborder   inf    abɔʁde     1
1393        aboutir   inf    abutiʁ     1
1668        abriter  ai3S    abʁita     1
2566         abîmer    pP    abimɑ̃     1
2967       accepter  pi3S    aksɛpt     1
3003       accepter  ppMS   aksɛpte     5
3406    accompagner   inf  akɔ̃paɲe     1
3527       accorder  pi1S     akɔʁd     1
3655       accoster   inf    akɔste     1
3884       accouder   inf     akude     1
4259      accrocher   inf    akʁɔʃe     1
4291      accrocher  ppMS    akʁɔʃe     1
4292      accrocher  ppFS    akʁɔʃe     1
4323      accroupir   inf   akʁupiʁ     1
4502     accueillir  ppMS     akəji     1
4748        accuser  ppMS     akyze     1
4750        accuser  ppFS     akyze     1
5107        acheter  ai1S     aʃətɛ     1
5111        acheter  ii3S     aʃətɛ     1
5119        acheter   inf     aʃəte     1
5136        acheter  ppMS     aʃəte     1
5146        achever  ii3P     aʃəvɛ     1
5171        achever  ppMS     aʃəve     1
6883       admettre  pi1P   admɛtɔ̃     1
...             ...   ...       ...   ...
432650      épuiser  pi1S     ɛpɥiz     1
432691      épuiser  ppFS    ɛpɥize     1
433026   équilibrer   inf  ɛkilibʁe     1
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ    15
434070         être  ii3S       ɛtɛ    55
434821      étendre   inf    ɛtɑ̃dʁ     1
434831      étendre  ppMS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     2
435254       étirer  pi3S      ɛtiʁ     1
435417      étonner  ai3S     ɛtɔna     1
435425      étonner    pP    ɛtɔnɑ̃     1
435444      étonner   inf     ɛtɔne     1
435450      étonner  pc3S   ɛtɔnəʁɛ     2
435457      étonner  pi2S      ɛtɔn     1
435538     étouffer  ppMS     ɛtufe     1
435660     étourdir   inf   ɛtuʁdiʁ     1
435815    étreindre  ai3S    ɛtʁɛɲi     1
436205      étudier   inf    ɛtydje     1
436233      étudier  ppMS    ɛtydje     2
436316         être  ppMS       ɛte    23
436484       évader  ppMS     ɛvade     1
436632     évanouir   inf   ɛvanuiʁ     1
437285       éviter    pP    ɛvitɑ̃     2
437292       éviter  pi1S      ɛvit     1
437328       éviter  ppMS     ɛvite     1
437424      évoquer  pi1S      ɛvɔk     1
437474         être  pi2P        ɛt    17
437476         être   inf       ɛtʁ    23
437497         ôter  ii3S       ɔtɛ     1

[1926 rows x 4 columns]

0
CPU times: user 59.6 s, sys: 20.4 s, total: 1min 19s
Wall time: 33.1 s

nbChunk 93
4200
1943

            lexeme  case        phono  tir1
40           avoir  pi3S            a    90
108     abandonner  ai3S     abɑ̃dɔna     1
113     abandonner  ii3S     abɑ̃dɔnɛ     1
132     abandonner   inf     abɑ̃dɔne     2
264        abattre  pi3P         abat     1
1140       aborder  pi1S        abɔʁd     1
1934      absenter  ii3S      absɑ̃tɛ     1
2053      absorber    pP     absɔʁbɑ̃     1
2100      absorber  ppMS      absɔʁbe     1
2102      absorber  ppFS      absɔʁbe     1
2614        abîmer  ppFP        abime     1
2736      accabler   inf       akable     1
2818     accaparer  ppMS      akapaʁe     1
2950      accepter  ii3S      aksɛptɛ     1
2971      accepter   inf      aksɛpte     3
3455     accomplir  fi1P   akɔ̃pliʁɔ̃     1
3484     accomplir  ii1P  akɔ̃plisjɔ̃     1
3530      accorder  pi3S        akɔʁd     1
3571      accorder  ppMS       akɔʁde     1
3651      accoster  pi3S        akɔst     1
3653      accoster  pi3P        akɔst     1
3868      accouder    pP       akudɑ̃     1
4230     accrocher  ai3S       akʁɔʃa     1
4233     accrocher  ai1S       akʁɔʃɛ     1
4502    accueillir  ppMS        akəji     1
4686     accumuler  ppMP      akymyle     1
4720       accuser   inf        akyze     1
5119       acheter   inf        aʃəte     1
5136       acheter  ppMS        aʃəte     1
5810      acquérir  ai1S          aki     1
...            ...   ...          ...   ...
432519    éprendre  ppMS         ɛpʁi     1
432533    éprouver  ai1S       ɛpʁuvɛ     1
432534    éprouver  ii3P       ɛpʁuvɛ     1
432552    éprouver  pi3S        ɛpʁuv     1
432556    éprouver   inf       ɛpʁuve     1
432650     épuiser  pi1S        ɛpɥiz     1
433026  équilibrer   inf     ɛkilibʁe     1
434048        être  ii3P          ɛtɛ     3
434068        être  ii1S          ɛtɛ    12
434070        être  ii3S          ɛtɛ    85
434131      étaler  ii3P        ɛtalɛ     1
435054        être  ii2P         ɛtje     2
435064   étinceler    pP    ɛtɛ̃səlɑ̃     1
435089   étinceler  pi3P      ɛtɛ̃sɛl     1
435172        être  ii1P        ɛtjɔ̃     2
435293      étirer  ppMS        ɛtiʁe     1
435438     étonner  pi3S         ɛtɔn     1
435486    étouffer    pP       ɛtufɑ̃     1
435782   étrangler  ppFS     ɛtʁɑ̃gle     1
436237     étudier  ppFP       ɛtydje     1
436316        être  ppMS          ɛte    21
436450      évader  pi1S         ɛvad     1
436855    éveiller  pi2P        ɛvɛje     1
436867    éveiller  ppMS        ɛvɛje     1
436890     éventer    pP      ɛvɑ̃tɑ̃     1
437295      éviter  pi3S         ɛvit     1
437301      éviter   inf        ɛvite     2
437447     évoquer  pi2P        ɛvɔke     1
437474        être  pi2P           ɛt    17
437476        être   inf          ɛtʁ    21

[1943 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 20 s, total: 1min 33s
Wall time: 31.5 s

nbChunk 94
4200
1925

             lexeme  case      phono  tir1
40            avoir  pi3S          a    88
259         abattre    pP     abatɑ̃     1
313         abattre  ppMP      abaty     1
890          abolir   inf     abɔliʁ     1
1175        aborder  ppMS     abɔʁde     1
2102       absorber  ppFS    absɔʁbe     1
2106       absorber  ppMP    absɔʁbe     1
2948       accepter  ii1S    aksɛptɛ     1
2971       accepter   inf    aksɛpte     1
2984       accepter  pi2S     aksɛpt     1
3343     accommoder  pi3S     akɔmɔd     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3467      accomplir  ii3S  akɔ̃plisɛ     1
3530       accorder  pi3S      akɔʁd     1
4259      accrocher   inf     akʁɔʃe     1
4291      accrocher  ppMS     akʁɔʃe     1
4509     accueillir   inf     akəjiʁ     1
4713        accuser  pi1S       akyz     1
4724        accuser  pc1S    akyzəʁɛ     1
4862      accélérer  ppMS   aksɛlɛʁe     1
4997       acharner  ii3S     aʃaʁnɛ     1
5119        acheter   inf      aʃəte     1
5137        acheter  ppFS      aʃəte     1
5157        achever   inf      aʃəve     1
5313        acheter  pi3P       aʃɛt     1
5879      acquitter  ppMS      akite     1
6969        admirer  ii3S     admiʁɛ     1
6996        admirer   inf     admiʁe     1
7283        adopter  ppMS     adɔpte     1
7309         adorer  pi1S       adɔʁ     1
...             ...   ...        ...   ...
432519     éprendre  ppMS       ɛpʁi     1
433113      équiper   inf      ɛkipe     1
433912      établir  ppMS     ɛtabli     1
433946      établir  ii3S   ɛtablisɛ     1
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ    13
434070         être  ii3S        ɛtɛ    65
434147       étaler  pi3S       ɛtal     1
434692       étayer   inf      ɛtɛje     1
434730     éteindre  pi3P       ɛtɛɲ     1
434772     éteindre  ppMS       ɛtɛ̃     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     2
435243       étirer  ii3S      ɛtiʁɛ     1
435254       étirer  pi3S       ɛtiʁ     1
435408      étoiler  ppMS     ɛtwale     1
435422      étonner  ii3S      ɛtɔnɛ     1
435438      étonner  pi3S       ɛtɔn     1
435484     étouffer  ii3S      ɛtufɛ     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    25
436632     évanouir   inf    ɛvanuiʁ     1
436649     évanouir  pi1S     ɛvanui     1
436835     éveiller   inf      ɛvɛje     1
437301       éviter   inf      ɛvite     1
437304       éviter  pc3P    ɛvitəʁɛ     1
437411      évoquer  ai3S      ɛvɔka     1
437474         être  pi2P         ɛt    10
437476         être   inf        ɛtʁ    25

[1925 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.2 s, total: 1min 36s
Wall time: 32 s

nbChunk 95
4200
1941

             lexeme  case      phono  tir1
40            avoir  pi3S          a    79
109      abandonner  ai1S   abɑ̃dɔnɛ     1
160      abandonner  is3S   abɑ̃dɔna     1
299         abattre   inf      abatʁ     1
1147        aborder   inf     abɔʁde     1
2579         abîmer  pi3P       abim     1
2888      accentuer    pP  aksɑ̃tyɑ̃     1
2971       accepter   inf    aksɛpte     1
2978       accepter  fi2S  aksɛptəʁa     1
3003       accepter  ppMS    aksɛpte     2
3005       accepter  ppFS    aksɛpte     1
3404    accompagner  pi3P    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     2
3573       accorder  ppFS     akɔʁde     1
4272      accrocher  pi2S      akʁɔʃ     1
4368      accroupir  ai3S     akʁupi     1
4473     accueillir  ii3S      akəjɛ     1
5119        acheter   inf      aʃəte     3
5136        acheter  ppMS      aʃəte     3
5157        achever   inf      aʃəve     1
5171        achever  ppMS      aʃəve     1
5754       acquérir  pi3S      akjɛʁ     1
6108        activer  ppMS     aktive     1
7023        admirer  ppMS     admiʁe     1
7243        adopter  pi1S      adɔpt     1
7539       adresser   inf     adʁɛse     1
7555       adresser  pI2P     adʁɛse     1
7801        advenir  pc3S  advjɛ̃dʁɛ     1
8240        affaler  ppMS      afale     1
...             ...   ...        ...   ...
427927       élever  fi3S    ɛlɛvəʁa     1
428106      émacier  ppFS     ɛmasje     1
429728      énerver  ppFS     ɛnɛʁve     1
432140      épouser  ii3P      ɛpuzɛ     1
432153      épouser  pi1S       ɛpuz     1
432156      épouser  pi3S       ɛpuz     1
432160      épouser   inf      ɛpuze     1
432552     éprouver  pi3S      ɛpʁuv     1
432653      épuiser  pi3S      ɛpɥiz     1
432659      épuiser   inf     ɛpɥize     1
432691      épuiser  ppFS     ɛpɥize     1
433777      éructer  ii3S     ɛʁyktɛ     1
433912      établir  ppMS     ɛtabli     1
434048         être  ii3P        ɛtɛ     1
434068         être  ii1S        ɛtɛ    16
434070         être  ii3S        ɛtɛ    67
434301       étaler  ppFP      ɛtale     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     2
435471      étonner  ppMS      ɛtɔne     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    31
436457       évader   inf      ɛvade     2
436833     éveiller  pi3P       ɛvɛj     1
437282       éviter  ii1S      ɛvitɛ     1
437301       éviter   inf      ɛvite     1
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    16
437498         ôter    pP       ɔtɑ̃     1
437528         ôter  pi2P        ɔte     1

[1941 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 20.6 s, total: 1min 38s
Wall time: 32.1 s

nbChunk 96
4200
1972

             lexeme  case     phono  tir1
40            avoir  pi3S         a    88
50         abaisser  ii3S     abɛsɛ     1
128      abandonner  pi3S   abɑ̃dɔn     1
132      abandonner   inf  abɑ̃dɔne     2
148      abandonner  pi2P  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     2
177      abasourdir  ppMS  abazuʁdi     1
287         abattre  ai3S     abati     1
299         abattre   inf     abatʁ     1
890          abolir   inf    abɔliʁ     1
1143        aborder  pi3S     abɔʁd     1
1688        abriter   inf    abʁite     1
2950       accepter  ii3S   aksɛptɛ     1
2971       accepter   inf   aksɛpte     1
3003       accepter  ppMS   aksɛpte     2
3400    accompagner  pi3S   akɔ̃paɲ     1
3430    accompagner  is3S  akɔ̃paɲa     1
3433    accompagner  ppMS  akɔ̃paɲe     1
4238      accrocher    pP   akʁɔʃɑ̃     1
4259      accrocher   inf    akʁɔʃe     3
4519     accueillir  ai3S     akəji     1
4812      accélérer  pi3S   aksɛlɛʁ     1
4835      accélérer   inf  aksɛlɛʁe     1
5111        acheter  ii3S     aʃətɛ     1
5119        acheter   inf     aʃəte     2
5125        acheter  pi2P     aʃəte     1
5157        achever   inf     aʃəve     2
5173        achever  ppFS     aʃəve     1
5308        acheter  pi1S      aʃɛt     3
5885       acquérir  pi3P     akjɛʁ     1
...             ...   ...       ...   ...
430593     épargner  ppMP    ɛpaʁɲe     1
430723       épater  ppFS     ɛpate     1
432144      épouser  ii3S     ɛpuzɛ     1
432160      épouser   inf     ɛpuze     1
432533     éprouver  ai1S    ɛpʁuvɛ     1
432586     éprouver  ppMS    ɛpʁuve     2
434048         être  ii3P       ɛtɛ     6
434068         être  ii1S       ɛtɛ    12
434070         être  ii3S       ɛtɛ    63
434782      étendre  pi3S      ɛtɑ̃     2
434821      étendre   inf    ɛtɑ̃dʁ     1
434833      étendre  ppFS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     5
435232       étirer  ai3S     ɛtiʁa     1
435417      étonner  ai3S     ɛtɔna     1
435438      étonner  pi3S      ɛtɔn     1
435472      étonner  ppFS     ɛtɔne     1
435782    étrangler  ppFS  ɛtʁɑ̃gle     1
436201      étudier  pi3S     ɛtydi     1
436316         être  ppMS       ɛte    15
436402      évacuer   inf    ɛvakye     1
436499      évaluer  ii3S    ɛvalyɛ     1
436835     éveiller   inf     ɛvɛje     1
436867     éveiller  ppMS     ɛvɛje     1
437284       éviter  ii3S     ɛvitɛ     1
437367      évoluer   inf    ɛvɔlye     1
437416      évoquer  ii3S     ɛvɔkɛ     1
437474         être  pi2P        ɛt    20
437476         être   inf       ɛtʁ    16

[1972 rows x 4 columns]

0
CPU times: user 1min 10s, sys: 18.7 s, total: 1min 29s
Wall time: 32.3 s

nbChunk 97
4200
1963

             lexeme  case       phono  tir1
40            avoir  pi3S           a    96
113      abandonner  ii3S    abɑ̃dɔnɛ     1
164      abandonner  ppMS    abɑ̃dɔne     1
166      abandonner  ppFS    abɑ̃dɔne     1
1110        abonner  ppMS       abɔne     1
1169        aborder  pi1P     abɔʁdɔ̃     1
1468         aboyer   inf      abwaje     1
1684        abriter  pi3S       abʁit     1
2884      accentuer  ii3P    aksɑ̃tyɛ     1
2939       accepter  ai3S     aksɛpta     1
2952       accepter    pP    aksɛptɑ̃     1
2971       accepter   inf     aksɛpte     2
3005       accepter  ppFS     aksɛpte     1
3319     accommoder  ii3P     akɔmɔdɛ     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     4
3440      accomplir  ppFS     akɔ̃pli     1
3442      accomplir  ppFP     akɔ̃pli     1
3443      accomplir   inf    akɔ̃pliʁ     1
3468      accomplir    pP  akɔ̃plisɑ̃     1
3530       accorder  pi3S       akɔʁd     1
3555       accorder  pI2P      akɔʁde     1
3571       accorder  ppMS      akɔʁde     1
3818      accoucher  pi1S        akuʃ     1
4062       accourir  ps3S        akuʁ     1
4095       accourir  ppMP       akuʁy     1
4230      accrocher  ai3S      akʁɔʃa     1
4280      accrocher  pi2P      akʁɔʃe     1
4509     accueillir   inf      akəjiʁ     1
...             ...   ...         ...   ...
432554     éprouver  pi3P       ɛpʁuv     1
432588     éprouver  ppFS      ɛpʁuve     1
432691      épuiser  ppFS      ɛpɥize     1
433778      éructer    pP     ɛʁyktɑ̃     1
433912      établir  ppMS      ɛtabli     2
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    14
434069         être  ii2S         ɛtɛ     1
434070         être  ii3S         ɛtɛ    68
434144       étaler  pi1S        ɛtal     1
434782      étendre  pi3S        ɛtɑ̃     1
434827      étendre  pi1S        ɛtɑ̃     1
434833      étendre  ppFS      ɛtɑ̃dy     1
434914     éternuer  pi1S      ɛtɛʁny     1
435172         être  ii1P       ɛtjɔ̃     4
435254       étirer  pi3S        ɛtiʁ     1
435360      étoiler  ii3P      ɛtwalɛ     1
435500     étouffer  pi3S        ɛtuf     1
435742    étrangler  pi3S     ɛtʁɑ̃gl     1
436205      étudier   inf      ɛtydje     3
436316         être  ppMS         ɛte    26
436398      évacuer  pi3S       ɛvaky     1
436520      évaluer   inf      ɛvalye     1
436821     éveiller    pP      ɛvɛjɑ̃     1
436835     éveiller   inf       ɛvɛje     1
437301       éviter   inf       ɛvite     4
437413      évoquer  ii3P       ɛvɔkɛ     1
437417      évoquer    pP      ɛvɔkɑ̃     1
437474         être  pi2P          ɛt    11
437476         être   inf         ɛtʁ    16

[1963 rows x 4 columns]

0
CPU times: user 1min 10s, sys: 18.2 s, total: 1min 28s
Wall time: 31.5 s

nbChunk 98
4200
1906

             lexeme  case       phono  tir1
40            avoir  pi3S           a    84
109      abandonner  ai1S    abɑ̃dɔnɛ     1
113      abandonner  ii3S    abɑ̃dɔnɛ     1
166      abandonner  ppFS    abɑ̃dɔne     1
252         abattre  pi2S         aba     1
299         abattre   inf       abatʁ     1
883          aboyer  pi2S        abwa     1
1133        aborder    pP     abɔʁdɑ̃     1
1148        aborder  fi3S    abɔʁdəʁa     1
1176        aborder  ppFS      abɔʁde     1
1439        aboutir  ai3S       abuti     1
1956       absenter  pc3S   absɑ̃təʁɛ     1
2610         abîmer  ppMS       abime     1
2612         abîmer  ppFS       abime     1
2971       accepter   inf     aksɛpte     3
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3406    accompagner   inf    akɔ̃paɲe     2
3413    accompagner  fi2S  akɔ̃paɲəʁa     1
3422    accompagner  pi2P    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
3443      accomplir   inf    akɔ̃pliʁ     2
4087       accourir  pi1S        akuʁ     1
4252      accrocher  pi1S       akʁɔʃ     1
4652      accumuler  pi3S      akymyl     1
4683      accumuler  ppMS     akymyle     1
4783        accéder   inf      aksɛde     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     1
5140        achever  ai3S       aʃəva     1
5311        acheter  pi3S        aʃɛt     1
...             ...   ...         ...   ...
434048         être  ii3P         ɛtɛ     6
434068         être  ii1S         ɛtɛ    13
434070         être  ii3S         ɛtɛ    68
434072       étaler  ai3S       ɛtala     1
434153       étaler   inf       ɛtale     1
434299       étaler  ppMS       ɛtale     1
434747     éteindre  ai3S       ɛtɛɲi     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434831      étendre  ppMS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     2
435417      étonner  ai3S       ɛtɔna     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435472      étonner  ppFS       ɛtɔne     1
435500     étouffer  pi3S        ɛtuf     1
435701     étourdir  pi2P    ɛtuʁdise     1
435797    étreindre  ps3S       ɛtʁɛɲ     1
436184      étudier  ii1S      ɛtydjɛ     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    26
436649     évanouir  pi1S      ɛvanui     1
436867     éveiller  ppMS       ɛvɛje     1
437301       éviter   inf       ɛvite     1
437328       éviter  ppMS       ɛvite     1
437367      évoluer   inf      ɛvɔlye     1
437424      évoquer  pi1S        ɛvɔk     1
437474         être  pi2P          ɛt    10
437476         être   inf         ɛtʁ    19
437508         ôter  pi3S          ot     1
437539         ôter  ppMS         ɔte     1

[1906 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 19.6 s, total: 1min 33s
Wall time: 31.9 s

nbChunk 99
4200
1917

             lexeme  case      phono  tir1
40            avoir  pi3S          a    84
102        abaisser  ppFS      abɛse     1
132      abandonner   inf   abɑ̃dɔne     2
252         abattre  pi2S        aba     1
412        abdiquer  pi3S      abdik     1
1457         aboyer  ii3P     abwajɛ     1
1468         aboyer   inf     abwaje     1
2335         abuser  pi3S       abyz     1
2967       accepter  pi3S     aksɛpt     1
3003       accepter  ppMS    aksɛpte     1
3349     accommoder   inf    akɔmɔde     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3419    accompagner  pi2S    akɔ̃paɲ     1
3434    accompagner  ppFS   akɔ̃paɲe     1
3467      accomplir  ii3S  akɔ̃plisɛ     1
3519       accorder  ii3S     akɔʁdɛ     1
3530       accorder  pi3S      akɔʁd     1
3556       accorder  pi2P     akɔʁde     1
3655       accoster   inf     akɔste     1
4291      accrocher  ppMS     akʁɔʃe     1
4303      accroître  ii3S    akʁwasɛ     1
4509     accueillir   inf     akəjiʁ     2
4814      accélérer  pi3P    aksɛlɛʁ     1
5102        acheter  ai3S      aʃəta     1
5111        acheter  ii3S      aʃətɛ     1
5119        acheter   inf      aʃəte     2
5136        acheter  ppMS      aʃəte     2
5157        achever   inf      aʃəve     1
5311        acheter  pi3S       aʃɛt     1
5329        achever  pi1S       aʃɛv     1
...             ...   ...        ...   ...
433912      établir  ppMS     ɛtabli     1
433922      établir   inf    ɛtabliʁ     3
433968      établir  ai3S     ɛtabli     1
434048         être  ii3P        ɛtɛ     1
434068         être  ii1S        ɛtɛ    14
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    91
434134       étaler  ii3S      ɛtalɛ     1
434729     éteindre  ps3S       ɛtɛɲ     1
434734     éteindre  pi2P      ɛtɛɲe     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     1
435232       étirer  ai3S      ɛtiʁa     1
435243       étirer  ii3S      ɛtiʁɛ     1
435422      étonner  ii3S      ɛtɔnɛ     1
435438      étonner  pi3S       ɛtɔn     1
435445      étonner  fi3S    ɛtɔnəʁa     1
435475     étouffer  ai3S      ɛtufa     1
435484     étouffer  ii3S      ɛtufɛ     1
435780    étrangler  ppMS   ɛtʁɑ̃gle     1
436186      étudier  ii3S     ɛtydjɛ     1
436201      étudier  pi3S      ɛtydi     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    15
436867     éveiller  ppMS      ɛvɛje     1
437301       éviter   inf      ɛvite     1
437474         être  pi2P         ɛt    23
437476         être   inf        ɛtʁ    19
437494         ôter  ii3P        ɔtɛ     1

[1917 rows x 4 columns]

0
CPU times: user 58.7 s, sys: 19.9 s, total: 1min 18s
Wall time: 32.4 s

nbChunk 100
4200
1928

             lexeme  case       phono  tir1
40            avoir  pi3S           a    84
109      abandonner  ai1S    abɑ̃dɔnɛ     1
128      abandonner  pi3S     abɑ̃dɔn     2
130      abandonner  pi3P     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
138      abandonner  pc3S  abɑ̃dɔnəʁɛ     1
164      abandonner  ppMS    abɑ̃dɔne     1
888          abolir  ppFS       abɔli     1
955         abonder  ii3P      abɔ̃dɛ     1
1674        abriter    pP     abʁitɑ̃     1
2100       absorber  ppMS     absɔʁbe     1
2339         abuser   inf       abyze     1
2727       accabler  pi1S       akabl     1
2782      accaparer  pi1S      akapaʁ     1
2818      accaparer  ppMS     akapaʁe     1
2948       accepter  ii1S     aksɛptɛ     1
2967       accepter  pi3S      aksɛpt     1
3005       accepter  ppFS     aksɛpte     1
3386    accompagner    pP   akɔ̃paɲɑ̃     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     3
3536       accorder   inf      akɔʁde     1
3575       accorder  ppFP      akɔʁde     1
3868       accouder    pP      akudɑ̃     1
4235      accrocher  ii1S      akʁɔʃɛ     1
4272      accrocher  pi2S       akʁɔʃ     1
4369      accroupir  pi3S      akʁupi     1
4482     accueillir  pi3S        akœj     1
4502     accueillir  ppMS       akəji     1
4626        acculer  ppMS       akyle     1
...             ...   ...         ...   ...
430668       épater    pP      ɛpatɑ̃     1
430878       épeler  pi1S        ɛpɛl     1
432160      épouser   inf       ɛpuze     1
432519     éprendre  ppMS        ɛpʁi     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
432556     éprouver   inf      ɛpʁuve     1
432580     éprouver  pi1P     ɛpʁuvɔ̃     1
433113      équiper   inf       ɛkipe     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    12
434070         être  ii3S         ɛtɛ    68
434302       étaler  ppMP       ɛtale     1
434488         être    pP        ɛtɑ̃     1
434768     éteindre  pi1S        ɛtɛ̃     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
435054         être  ii2P        ɛtje     1
435192    étiqueter   inf     ɛtikəte     1
435422      étonner  ii3S       ɛtɔnɛ     1
435435      étonner  pi1S        ɛtɔn     1
435442      étonner  pi3P        ɛtɔn     1
435506     étouffer   inf       ɛtufe     1
435782    étrangler  ppFS    ɛtʁɑ̃gle     1
436316         être  ppMS         ɛte    23
436520      évaluer   inf      ɛvalye     1
436821     éveiller    pP      ɛvɛjɑ̃     2
436835     éveiller   inf       ɛvɛje     1
437301       éviter   inf       ɛvite     1
437474         être  pi2P          ɛt    15
437476         être   inf         ɛtʁ    23
437512         ôter   inf         ɔte     1

[1928 rows x 4 columns]

0
CPU times: user 1min 2s, sys: 21.1 s, total: 1min 23s
Wall time: 33.3 s

nbChunk 101
4200
1920

             lexeme  case       phono  tir1
40            avoir  pi3S           a    88
164      abandonner  ppMS    abɑ̃dɔne     1
168      abandonner  ppFP    abɑ̃dɔne     1
258         abattre  ii3S       abatɛ     1
1718        abriter  ppFS      abʁite     1
2143       abstenir   inf    abstəniʁ     1
2950       accepter  ii3S     aksɛptɛ     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     3
2983       accepter  fi3P  aksɛptəʁɔ̃     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3419    accompagner  pi2S     akɔ̃paɲ     1
3436    accompagner  ppMP    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     2
3443      accomplir   inf    akɔ̃pliʁ     1
3527       accorder  pi1S       akɔʁd     1
3536       accorder   inf      akɔʁde     1
3914       accouder  ppFS       akude     1
4234      accrocher  ii3P      akʁɔʃɛ     1
4238      accrocher    pP     akʁɔʃɑ̃     1
4294      accrocher  ppMP      akʁɔʃe     1
4473     accueillir  ii3S       akəjɛ     1
4868      accélérer  ppMP    aksɛlɛʁe     1
5308        acheter  pi1S        aʃɛt     1
5315        acheter  fi3S     aʃɛtəʁa     1
5787     acquiescer  ai3S      akjɛsa     1
6064        activer  pi1S       aktiv     1
6733      adjoindre  pi3S      adʒwɛ̃     1
6891       admettre   inf      admɛtʁ     1
6991        admirer  pi3S       admiʁ     1
...             ...   ...         ...   ...
431788        épier  ppMS        ɛpje     1
431856     éplucher  ii3S      ɛplyʃɛ     1
432160      épouser   inf       ɛpuze     1
432167      épouser  fi2S     ɛpuzəʁa     1
432535     éprouver  ii1S      ɛpʁuvɛ     1
432552     éprouver  pi3S       ɛpʁuv     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ     8
434069         être  ii2S         ɛtɛ     1
434070         être  ii3S         ɛtɛ    87
434072       étaler  ai3S       ɛtala     1
434723     éteindre  ii3P       ɛtɛɲɛ     1
434733     éteindre  pI2P       ɛtɛɲe     1
434747     éteindre  ai3S       ɛtɛɲi     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434794      étendre  pi3P       ɛtɑ̃d     1
434811      étendre  ai3S      ɛtɑ̃di     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     2
435417      étonner  ai3S       ɛtɔna     1
436186      étudier  ii3S      ɛtydjɛ     1
436205      étudier   inf      ɛtydje     2
436316         être  ppMS         ɛte    19
437176      évincer   inf      ɛvɛ̃se     1
437295       éviter  pi3S        ɛvit     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437431      évoquer   inf       ɛvɔke     1
437474         être  pi2P          ɛt     7
437476         être   inf         ɛtʁ    24
437528         ôter  pi2P         ɔte     1

[1920 rows x 4 columns]

0
CPU times: user 1min 2s, sys: 22.4 s, total: 1min 24s
Wall time: 35 s

nbChunk 102
4200
1959

             lexeme  case       phono  tir1
40            avoir  pi3S           a    73
128      abandonner  pi3S     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
133      abandonner  fi3S  abɑ̃dɔnəʁa     1
151      abandonner  ii1P  abɑ̃dɔnjɔ̃     1
160      abandonner  is3S    abɑ̃dɔna     1
256         abattre  ii1S       abatɛ     1
299         abattre   inf       abatʁ     2
305         abattre  ppMS       abaty     1
1143        aborder  pi3S       abɔʁd     1
2579         abîmer  pi3P        abim     1
2715       accabler  ii3S      akablɛ     1
2984       accepter  pi2S      aksɛpt     1
3003       accepter  ppMS     aksɛpte     2
3404    accompagner  pi3P     akɔ̃paɲ     1
3443      accomplir   inf    akɔ̃pliʁ     1
3536       accorder   inf      akɔʁde     1
3571       accorder  ppMS      akɔʁde     1
3912       accouder  ai3P      akudɛʁ     1
4252      accrocher  pi1S       akʁɔʃ     1
4693        accuser  ii3S       akyzɛ     1
4720        accuser   inf       akyze     1
4754        accuser  ppMP       akyze     1
5102        acheter  ai3S       aʃəta     1
5107        acheter  ai1S       aʃətɛ     1
5119        acheter   inf       aʃəte     3
5125        acheter  pi2P       aʃəte     1
5136        acheter  ppMS       aʃəte     2
5171        achever  ppMS       aʃəve     1
5311        acheter  pi3S        aʃɛt     3
...             ...   ...         ...   ...
427624     éloigner  ii3S      ɛlwaɲɛ     1
427641     éloigner   inf      ɛlwaɲe     2
428401      émerger    pP     ɛmɛʁʒɑ̃     1
428609      émettre  pi3S         ɛmɛ     1
428844      émettre  ppMS         ɛmi     1
428995   émotionner  ppMS    ɛmɔsjɔne     1
429365     émouvoir  ppMS         ɛmy     2
429730      énerver  ppMP      ɛnɛʁve     1
432153      épouser  pi1S        ɛpuz     1
432156      épouser  pi3S        ɛpuz     1
432160      épouser   inf       ɛpuze     1
432302      épouser  ppMS       ɛpuze     1
432535     éprouver  ii1S      ɛpʁuvɛ     1
432586     éprouver  ppMS      ɛpʁuve     1
433943      établir  ii3P    ɛtablisɛ     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ    11
434070         être  ii3S         ɛtɛ    83
434773     éteindre  pi3S        ɛtɛ̃     1
434785      étendre  ii3P      ɛtɑ̃dɛ     1
434836      étendre  ppFP      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     1
435055    étinceler  ai3S    ɛtɛ̃səla     1
435232       étirer  ai3S       ɛtiʁa     1
435444      étonner   inf       ɛtɔne     1
435726    étrangler  ai3S    ɛtʁɑ̃gla     1
436316         être  ppMS         ɛte    31
437046     évertuer  ii3P     ɛvɛʁtyɛ     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    15

[1959 rows x 4 columns]

0
CPU times: user 1min 2s, sys: 22.1 s, total: 1min 24s
Wall time: 34.1 s

nbChunk 103
4200
1944

             lexeme  case      phono  tir1
40            avoir  pi3S          a    87
132      abandonner   inf   abɑ̃dɔne     1
255         abattre  ii3P      abatɛ     1
305         abattre  ppMS      abaty     1
1147        aborder   inf     abɔʁde     1
1722        abriter  ppMP     abʁite     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     5
2975       accepter  pc1S  aksɛptəʁɛ     1
2984       accepter  pi2S     aksɛpt     1
3003       accepter  ppMS    aksɛpte     1
3380    accompagner  ai3S   akɔ̃paɲa     1
3443      accomplir   inf   akɔ̃pliʁ     1
3527       accorder  pi1S      akɔʁd     1
3536       accorder   inf     akɔʁde     1
4210     accoutumer  ppMS    akutyme     1
4509     accueillir   inf     akəjiʁ     1
4683      accumuler  ppMS    akymyle     1
4720        accuser   inf      akyze     1
4997       acharner  ii3S     aʃaʁnɛ     1
5107        acheter  ai1S      aʃətɛ     1
5119        acheter   inf      aʃəte     3
5136        acheter  ppMS      aʃəte     1
5311        acheter  pi3S       aʃɛt     2
6891       admettre   inf     admɛtʁ     1
6965        admirer  ai1S     admiʁɛ     1
6969        admirer  ii3S     admiʁɛ     1
6996        admirer   inf     admiʁe     1
7250        adopter   inf     adɔpte     1
7312         adorer  pi3S       adɔʁ     2
...             ...   ...        ...   ...
432535     éprouver  ii1S     ɛpʁuvɛ     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
432552     éprouver  pi3S      ɛpʁuv     1
432691      épuiser  ppFS     ɛpɥize     1
432739       épurer   inf      ɛpyʁe     1
434048         être  ii3P        ɛtɛ     6
434068         être  ii1S        ɛtɛ    12
434070         être  ii3S        ɛtɛ    82
434134       étaler  ii3S      ɛtalɛ     1
434772     éteindre  ppMS       ɛtɛ̃     1
434773     éteindre  pi3S       ɛtɛ̃     2
434779     éteindre  ppMP       ɛtɛ̃     1
434789      étendre    pP    ɛtɑ̃dɑ̃     1
434804      étendre  ai1S     ɛtɑ̃di     1
435074    étinceler   inf   ɛtɛ̃səle     1
435172         être  ii1P      ɛtjɔ̃     1
435471      étonner  ppMS      ɛtɔne     1
435506     étouffer   inf      ɛtufe     1
436201      étudier  pi3S      ɛtydi     1
436316         être  ppMS        ɛte    21
436402      évacuer   inf     ɛvakye     1
436457       évader   inf      ɛvade     1
436484       évader  ppMS      ɛvade     1
436629     évanouir  ppFS     ɛvanui     1
437285       éviter    pP     ɛvitɑ̃     1
437301       éviter   inf      ɛvite     1
437363      évoluer  pi3S      ɛvɔly     1
437416      évoquer  ii3S      ɛvɔkɛ     1
437474         être  pi2P         ɛt     3
437476         être   inf        ɛtʁ    26

[1944 rows x 4 columns]

0
CPU times: user 1min 10s, sys: 20.4 s, total: 1min 30s
Wall time: 33.1 s

nbChunk 104
4200
1913

            lexeme  case     phono  tir1
40           avoir  pi3S         a    80
113     abandonner  ii3S  abɑ̃dɔnɛ     1
128     abandonner  pi3S   abɑ̃dɔn     1
243        abattre  pi3S       aba     1
299        abattre   inf     abatʁ     1
887         abolir  ppMS     abɔli     1
1147       aborder   inf    abɔʁde     1
1468        aboyer   inf    abwaje     1
2051      absorber  ii3S   absɔʁbɛ     1
2124      absoudre  pi1S      absu     1
2325        abuser    pP    abyzɑ̃     1
2752      accabler  pi2P    akable     1
2887     accentuer  ii3S  aksɑ̃tyɛ     1
2971      accepter   inf   aksɛpte     1
3003      accepter  ppMS   aksɛpte     1
3322    accommoder  ii3S   akɔmɔdɛ     1
3564      accorder  pi1P   akɔʁdɔ̃     1
3683      accoster  ppFS    akɔste     1
3827     accoucher   inf     akuʃe     2
3858     accoucher  ppMS     akuʃe     1
4255     accrocher  pi3S     akʁɔʃ     1
4509    accueillir   inf    akəjiʁ     1
4716       accuser  pi3S      akyz     1
4803       accéder  pi1P   aksɛdɔ̃     1
4812     accélérer  pi3S   aksɛlɛʁ     1
5119       acheter   inf     aʃəte     3
5136       acheter  ppMS     aʃəte     1
5137       acheter  ppFS     aʃəte     1
5157       achever   inf     aʃəve     1
5322       acheter  fi2P   aʃɛtəʁe     1
...            ...   ...       ...   ...
430688      épater   inf     ɛpate     1
431871    éplucher   inf    ɛplyʃe     1
432156     épouser  pi3S      ɛpuz     1
432160     épouser   inf     ɛpuze     2
432421  épouvanter  ppFS  ɛpuvɑ̃te     1
432532    éprouver  ai3S    ɛpʁuva     2
432659     épuiser   inf    ɛpɥize     1
434048        être  ii3P       ɛtɛ     4
434068        être  ii1S       ɛtɛ    16
434070        être  ii3S       ɛtɛ    61
434762    éteindre   inf    ɛtɛ̃dʁ     1
434788     étendre  ii3S    ɛtɑ̃dɛ     2
434821     étendre   inf    ɛtɑ̃dʁ     1
435054        être  ii2P      ɛtje     2
435172        être  ii1P     ɛtjɔ̃     1
435258      étirer  pi3P      ɛtiʁ     1
435438     étonner  pi3S      ɛtɔn     1
435450     étonner  pc3S   ɛtɔnəʁɛ     1
435500    étouffer  pi3S      ɛtuf     1
435526    étouffer  pi2P     ɛtufe     1
436316        être  ppMS       ɛte    29
436457      évader   inf     ɛvade     1
436484      évader  ppMS     ɛvade     1
436679    évanouir  pi3S    ɛvanui     1
437046    évertuer  ii3P   ɛvɛʁtyɛ     1
437307      éviter  pc3S   ɛvitəʁɛ     1
437411     évoquer  ai3S     ɛvɔka     1
437474        être  pi2P        ɛt    12
437476        être   inf       ɛtʁ    20
437492        ôter  ai3S       ɔta     1

[1913 rows x 4 columns]

0
CPU times: user 1min, sys: 21.4 s, total: 1min 22s
Wall time: 33 s

nbChunk 105
4200
1943

             lexeme  case       phono  tir1
40            avoir  pi3S           a    91
125      abandonner  pi1S     abɑ̃dɔn     1
128      abandonner  pi3S     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
258         abattre  ii3S       abatɛ     1
887          abolir  ppMS       abɔli     1
1175        aborder  ppMS      abɔʁde     1
2736       accabler   inf      akable     1
2950       accepter  ii3S     aksɛptɛ     1
2971       accepter   inf     aksɛpte     1
3003       accepter  ppMS     aksɛpte     1
3343     accommoder  pi3S      akɔmɔd     1
3380    accompagner  ai3S    akɔ̃paɲa     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3400    accompagner  pi3S     akɔ̃paɲ     2
3530       accorder  pi3S       akɔʁd     1
4291      accrocher  ppMS      akʁɔʃe     1
4502     accueillir  ppMS       akəji     1
4509     accueillir   inf      akəjiʁ     1
4803        accéder  pi1P     aksɛdɔ̃     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     4
5140        achever  ai3S       aʃəva     1
5329        achever  pi1S        aʃɛv     1
6872       admettre  ps3S       admɛt     1
6883       admettre  pi1P     admɛtɔ̃     1
6928    administrer   inf  administʁe     1
7187        adonner  pi3S        adɔn     1
7309         adorer  pi1S        adɔʁ     1
7312         adorer  pi3S        adɔʁ     3
...             ...   ...         ...   ...
433914      établir  ppFS      ɛtabli     1
434048         être  ii3P         ɛtɛ     8
434068         être  ii1S         ɛtɛ    15
434069         être  ii2S         ɛtɛ     1
434070         être  ii3S         ɛtɛ    66
434730     éteindre  pi3P        ɛtɛɲ     1
434734     éteindre  pi2P       ɛtɛɲe     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434768     éteindre  pi1S        ɛtɛ̃     1
434773     éteindre  pi3S        ɛtɛ̃     2
434833      étendre  ppFS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     3
435202    étiqueter  pi1S      ɛtikɛt     1
435232       étirer  ai3S       ɛtiʁa     2
435471      étonner  ppMS       ɛtɔne     1
435472      étonner  ppFS       ɛtɔne     1
436188      étudier    pP     ɛtydjɑ̃     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    24
436423      évacuer  pI1P     ɛvakyɔ̃     1
436520      évaluer   inf      ɛvalye     1
436547      évaluer  ppMS      ɛvalye     1
436632     évanouir   inf     ɛvanuiʁ     2
437282       éviter  ii1S       ɛvitɛ     1
437295       éviter  pi3S        ɛvit     1
437427      évoquer  pi3S        ɛvɔk     1
437474         être  pi2P          ɛt    18
437476         être   inf         ɛtʁ    18
437512         ôter   inf         ɔte     1

[1943 rows x 4 columns]

0
CPU times: user 1min 2s, sys: 21.1 s, total: 1min 23s
Wall time: 34.2 s

nbChunk 106
4200
1944

             lexeme  case       phono  tir1
40            avoir  pi3S           a    76
108      abandonner  ai3S    abɑ̃dɔna     1
110      abandonner  ii3P    abɑ̃dɔnɛ     1
128      abandonner  pi3S     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
168      abandonner  ppFP    abɑ̃dɔne     1
1716        abriter  ppMS      abʁite     1
1798        abrutir  ppFS      abʁyti     1
2053       absorber    pP    absɔʁbɑ̃     1
2971       accepter   inf     aksɛpte     1
2997       accepter  pi1P    aksɛptɔ̃     1
3406    accompagner   inf    akɔ̃paɲe     1
3412    accompagner  pc3S  akɔ̃paɲəʁɛ     1
3438      accomplir  ppMS     akɔ̃pli     1
3827      accoucher   inf       akuʃe     1
3884       accouder   inf       akude     1
4280      accrocher  pi2P      akʁɔʃe     1
4291      accrocher  ppMS      akʁɔʃe     1
4292      accrocher  ppFS      akʁɔʃe     1
4374      accroître  fi3S    akʁwatʁa     1
4748        accuser  ppMS       akyze     1
5012       acharner  pi3P       aʃaʁn     1
5042       acharner  ppFS      aʃaʁne     1
5070      acheminer   inf     aʃəmine     1
5102        acheter  ai3S       aʃəta     1
5109        acheter  ii1S       aʃətɛ     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     4
5327        acheter  pi2S        aʃɛt     1
5332        achever  pi3S        aʃɛv     1
...             ...   ...         ...   ...
428685     émietter   inf      ɛmjɛte     1
429728      énerver  ppFS      ɛnɛʁve     1
430646   éparpiller  ppMP    ɛpaʁpije     1
431611     épingler  ppFS     ɛpɛ̃gle     1
432156      épouser  pi3S        ɛpuz     1
432160      épouser   inf       ɛpuze     1
432168      épouser  fi2P     ɛpuzəʁe     1
432302      épouser  ppMS       ɛpuze     1
432691      épuiser  ppFS      ɛpɥize     1
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ    22
434070         être  ii3S         ɛtɛ    81
434300       étaler  ppFS       ɛtale     1
434804      étendre  ai1S      ɛtɑ̃di     1
434821      étendre   inf      ɛtɑ̃dʁ     1
435410      étoiler  ppFS      ɛtwale     1
435794    étreindre  ii3S      ɛtʁɛɲɛ     1
436205      étudier   inf      ɛtydje     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    21
436430      évacuer  ppMS      ɛvakye     1
436831     éveiller  pi3S        ɛvɛj     1
437301       éviter   inf       ɛvite     2
437316       éviter  pI2P       ɛvite     1
437353      évoluer    pP     ɛvɔlyɑ̃     1
437367      évoluer   inf      ɛvɔlye     1
437427      évoquer  pi3S        ɛvɔk     1
437431      évoquer   inf       ɛvɔke     2
437474         être  pi2P          ɛt    11
437476         être   inf         ɛtʁ    26

[1944 rows x 4 columns]

0
CPU times: user 58.2 s, sys: 19.1 s, total: 1min 17s
Wall time: 34 s

nbChunk 107
4200
1936

             lexeme  case       phono  tir1
40            avoir  pi3S           a    81
130      abandonner  pi3P     abɑ̃dɔn     1
164      abandonner  ppMS    abɑ̃dɔne     1
297         abattre  pc3S      abatʁɛ     1
299         abattre   inf       abatʁ     1
1175        aborder  ppMS      abɔʁde     1
1176        aborder  ppFS      abɔʁde     1
1861        abréger  pi3P       abʁɛʒ     1
1934       absenter  ii3S     absɑ̃tɛ     1
1943       absenter  pi1S      absɑ̃t     1
2116       absoudre   inf      absudʁ     1
2581         abîmer   inf       abime     1
2950       accepter  ii3S     aksɛptɛ     1
2964       accepter  pi1S      aksɛpt     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     1
3003       accepter  ppMS     aksɛpte     1
3009       accepter  ppMP     aksɛpte     1
3380    accompagner  ai3S    akɔ̃paɲa     1
3468      accomplir    pP  akɔ̃plisɑ̃     1
3536       accorder   inf      akɔʁde     1
3708        accoter   inf       akɔte     1
4291      accrocher  ppMS      akʁɔʃe     1
4519     accueillir  ai3S       akəji     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     2
5149        achever  ii3S       aʃəvɛ     1
5308        acheter  pi1S        aʃɛt     1
5326        acheter  fi3P    aʃɛtəʁɔ̃     1
5758     acquiescer  pi3S       akjɛs     1
...             ...   ...         ...   ...
429727      énerver  ppMS      ɛnɛʁve     1
430590     épargner  ppMS      ɛpaʁɲe     1
431872     éplucher  fi3S    ɛplyʃəʁa     1
432145      épouser    pP      ɛpuzɑ̃     1
432160      épouser   inf       ɛpuze     2
432302      épouser  ppMS       ɛpuze     1
432390   épouvanter  pi3P     ɛpuvɑ̃t     1
432556     éprouver   inf      ɛpʁuve     1
432586     éprouver  ppMS      ɛpʁuve     1
432689      épuiser  ppMS      ɛpɥize     1
433617       ériger  ppMS       ɛʁiʒe     1
433914      établir  ppFS      ɛtabli     1
433922      établir   inf     ɛtabliʁ     2
433946      établir  ii3S    ɛtablisɛ     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ    14
434070         être  ii3S         ɛtɛ    65
434853    éterniser  ii3S    ɛtɛʁnizɛ     1
434923     éternuer   inf     ɛtɛʁnye     1
435054         être  ii2P        ɛtje     3
435172         être  ii1P       ɛtjɔ̃     3
435742    étrangler  pi3S     ɛtʁɑ̃gl     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436316         être  ppMS         ɛte    29
436424      évacuer  pi1P     ɛvakyɔ̃     1
436649     évanouir  pi1S      ɛvanui     1
437301       éviter   inf       ɛvite     2
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    28
437507         ôter  pI2S          ot     1

[1936 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 20.1 s, total: 1min 36s
Wall time: 33.3 s

nbChunk 108
4200
1960

             lexeme  case      phono  tir1
40            avoir  pi3S          a    86
104        abaisser  ppMP      abɛse     1
164      abandonner  ppMS   abɑ̃dɔne     1
1174        aborder  ai3P    abɔʁdɛʁ     1
1393        aboutir   inf     abutiʁ     1
1439        aboutir  ai3S      abuti     1
1796        abrutir  ppMS     abʁyti     1
2116       absoudre   inf     absudʁ     1
2967       accepter  pi3S     aksɛpt     2
2973       accepter  fi1S  aksɛptəʁɛ     1
3319     accommoder  ii3P    akɔmɔdɛ     1
3349     accommoder   inf    akɔmɔde     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3805      accoucher  ai3S      akuʃa     1
4252      accrocher  pi1S      akʁɔʃ     1
4486     accueillir  fi3S    akəjəʁa     1
4509     accueillir   inf     akəjiʁ     2
4720        accuser   inf      akyze     2
4748        accuser  ppMS      akyze     1
5012       acharner  pi3P      aʃaʁn     1
5102        acheter  ai3S      aʃəta     1
5119        acheter   inf      aʃəte     1
5131        acheter  pi1P     aʃətɔ̃     1
5136        acheter  ppMS      aʃəte     1
5140        achever  ai3S      aʃəva     1
5311        acheter  pi3S       aʃɛt     1
5329        achever  pi1S       aʃɛv     1
5338        achever  fi3S    aʃɛvəʁa     1
6089        activer  pi2P     aktive     1
7250        adopter   inf     adɔpte     1
...             ...   ...        ...   ...
434068         être  ii1S        ɛtɛ    12
434070         être  ii3S        ɛtɛ    63
434302       étaler  ppMP      ɛtale     1
434488         être    pP       ɛtɑ̃     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434773     éteindre  pi3S       ɛtɛ̃     3
434821      étendre   inf     ɛtɑ̃dʁ     1
434836      étendre  ppFP     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     2
435254       étirer  pi3S       ɛtiʁ     1
435417      étonner  ai3S      ɛtɔna     1
435471      étonner  ppMS      ɛtɔne     1
435482     étouffer  ii1S      ɛtufɛ     1
435486     étouffer    pP     ɛtufɑ̃     1
435500     étouffer  pi3S       ɛtuf     1
435540     étouffer  ppFS      ɛtufe     1
435794    étreindre  ii3S     ɛtʁɛɲɛ     1
436203      étudier  pi3P      ɛtydi     1
436205      étudier   inf     ɛtydje     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    28
436632     évanouir   inf    ɛvanuiʁ     2
436664     évanouir  pi3P    ɛvanuis     1
437060     évertuer  pi3S     ɛvɛʁty     1
437301       éviter   inf      ɛvite     2
437352      évoluer  ii3S     ɛvɔlyɛ     1
437416      évoquer  ii3S      ɛvɔkɛ     2
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    19
437492         ôter  ai3S        ɔta     1

[1960 rows x 4 columns]

0
CPU times: user 1min 11s, sys: 19.7 s, total: 1min 30s
Wall time: 31.3 s

nbChunk 109
4200
1875

             lexeme  case      phono  tir1
40            avoir  pi3S          a    85
45         abaisser  ai3S      abɛsa     1
108      abandonner  ai3S   abɑ̃dɔna     2
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     2
145      abandonner  pi2S    abɑ̃dɔn     1
164      abandonner  ppMS   abɑ̃dɔne     3
170      abandonner  ppMP   abɑ̃dɔne     1
2577         abîmer  pi3S       abim     1
2887      accentuer  ii3S   aksɑ̃tyɛ     1
2904      accentuer   inf   aksɑ̃tye     1
2971       accepter   inf    aksɛpte     1
2972       accepter  fi3S  aksɛptəʁa     1
2977       accepter  pc3S  aksɛptəʁɛ     1
2989       accepter  pi2P    aksɛpte     1
2999       accepter  is3S    aksɛpta     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     2
3573       accorder  ppFS     akɔʁde     1
4291      accrocher  ppMS     akʁɔʃe     1
4294      accrocher  ppMP     akʁɔʃe     1
4321      accroupir  ppFS     akʁupi     1
4509     accueillir   inf     akəjiʁ     1
4812      accélérer  pi3S    aksɛlɛʁ     1
4997       acharner  ii3S     aʃaʁnɛ     1
5014       acharner   inf     aʃaʁne     1
5107        acheter  ai1S      aʃətɛ     1
5111        acheter  ii3S      aʃətɛ     2
5119        acheter   inf      aʃəte     5
...             ...   ...        ...   ...
430579     épargner  pi2P     ɛpaʁɲe     1
432160      épouser   inf      ɛpuze     1
432162      épouser  fi1S    ɛpuzəʁɛ     1
432556     éprouver   inf     ɛpʁuve     1
433922      établir   inf    ɛtabliʁ     1
434004       étager  pi3P       ɛtaʒ     1
434048         être  ii3P        ɛtɛ     1
434068         être  ii1S        ɛtɛ    13
434070         être  ii3S        ɛtɛ    81
434770     éteindre  pi2S       ɛtɛ̃     1
434772     éteindre  ppMS       ɛtɛ̃     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     1
435059    étinceler  ii3P   ɛtɛ̃səlɛ     1
435414      étoiler  ppMP     ɛtwale     1
435422      étonner  ii3S      ɛtɔnɛ     1
435471      étonner  ppMS      ɛtɔne     2
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    30
436402      évacuer   inf     ɛvakye     1
436647     évanouir  ppMP     ɛvanui     1
436649     évanouir  pi1S     ɛvanui     1
437024     éventrer  ppMS    ɛvɑ̃tʁe     1
437285       éviter    pP     ɛvitɑ̃     2
437301       éviter   inf      ɛvite     3
437416      évoquer  ii3S      ɛvɔkɛ     1
437427      évoquer  pi3S       ɛvɔk     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    18

[1875 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 18.9 s, total: 1min 31s
Wall time: 33 s

nbChunk 110
4200
1950

             lexeme  case       phono  tir1
40            avoir  pi3S           a    86
132      abandonner   inf    abɑ̃dɔne     3
170      abandonner  ppMP    abɑ̃dɔne     1
1307        abouler  pi3S        abul     1
1415        aboutir  ii3S     abutisɛ     1
1485         aboyer  ppMS      abwaje     1
2371         abuser  ppMS       abyze     1
2581         abîmer   inf       abime     1
2610         abîmer  ppMS       abime     1
2920      accentuer  pi2P    aksɑ̃tye     1
2971       accepter   inf     aksɛpte     1
2973       accepter  fi1S   aksɛptəʁɛ     1
2975       accepter  pc1S   aksɛptəʁɛ     1
3005       accepter  ppFS     aksɛpte     1
3382    accompagner  ii3P    akɔ̃paɲɛ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     1
3443      accomplir   inf    akɔ̃pliʁ     1
4259      accrocher   inf      akʁɔʃe     1
4272      accrocher  pi2S       akʁɔʃ     1
4373      accroître  pi3S       akʁwa     1
4720        accuser   inf       akyze     1
4998       acharner    pP     aʃaʁnɑ̃     1
5119        acheter   inf       aʃəte     1
5157        achever   inf       aʃəve     1
5173        achever  ppFS       aʃəve     1
5308        acheter  pi1S        aʃɛt     1
5332        achever  pi3S        aʃɛv     2
5787     acquiescer  ai3S      akjɛsa     1
5903       acquérir  ii1P     akɛʁjɔ̃     1
...             ...   ...         ...   ...
429716      énerver  pi2P      ɛnɛʁve     1
430562     épargner   inf      ɛpaʁɲe     2
430973    éperonner  ppMS     ɛpəʁɔne     1
432160      épouser   inf       ɛpuze     1
432518     éprendre  ppMP        ɛpʁi     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
432588     éprouver  ppFS      ɛpʁuve     1
433946      établir  ii3S    ɛtablisɛ     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ     9
434070         être  ii3S         ɛtɛ    65
434299       étaler  ppMS       ɛtale     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     1
435422      étonner  ii3S       ɛtɔnɛ     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435506     étouffer   inf       ɛtufe     1
435749    étrangler  fi3S  ɛtʁɑ̃gləʁa     1
436316         être  ppMS         ɛte    32
436629     évanouir  ppFS      ɛvanui     1
436656     évanouir  ii3S    ɛvanuisɛ     1
436739     évaporer  ppMS     ɛvapɔʁe     1
436980     éventrer  ii3S     ɛvɑ̃tʁɛ     1
437285       éviter    pP      ɛvitɑ̃     1
437295       éviter  pi3S        ɛvit     1
437413      évoquer  ii3P       ɛvɔkɛ     1
437427      évoquer  pi3S        ɛvɔk     1
437431      évoquer   inf       ɛvɔke     1
437474         être  pi2P          ɛt    18
437476         être   inf         ɛtʁ    18

[1950 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 20.1 s, total: 1min 36s
Wall time: 31.8 s

nbChunk 111
4200
1938

             lexeme  case     phono  tir1
40            avoir  pi3S         a    82
100        abaisser  ai3P    abɛsɛʁ     1
128      abandonner  pi3S   abɑ̃dɔn     1
299         abattre   inf     abatʁ     1
1393        aboutir   inf    abutiʁ     1
1716        abriter  ppMS    abʁite     1
1825        abrutir  ii3S  abʁytisɛ     1
1950       absenter   inf   absɑ̃te     1
1979       absenter  ppMS   absɑ̃te     1
2332         abuser  pi1S      abyz     1
2337         abuser  pi3P      abyz     1
2579         abîmer  pi3P      abim     1
2610         abîmer  ppMS     abime     1
2904      accentuer   inf  aksɑ̃tye     1
2967       accepter  pi3S    aksɛpt     1
2971       accepter   inf   aksɛpte     1
3003       accepter  ppMS   aksɛpte     2
3385    accompagner  ii3S  akɔ̃paɲɛ     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     1
3436    accompagner  ppMP  akɔ̃paɲe     1
3443      accomplir   inf  akɔ̃pliʁ     1
3583       accorder  ppMP    akɔʁde     1
4009       accourir  ii3S     akuʁɛ     1
4280      accrocher  pi2P    akʁɔʃe     1
4293      accrocher  ppFP    akʁɔʃe     1
4394      accroître  ppMP      akʁy     1
4403      accroître  ai3S      akʁy     1
4509     accueillir   inf    akəjiʁ     1
4626        acculer  ppMS     akyle     1
...             ...   ...       ...   ...
428351    émasculer  pi3S   ɛmaskyl     1
428844      émettre  ppMS       ɛmi     1
429349     émouvoir   inf   ɛmuvwaʁ     1
429694      énerver  pi3S     ɛnɛʁv     1
429727      énerver  ppMS    ɛnɛʁve     1
430590     épargner  ppMS    ɛpaʁɲe     1
432160      épouser   inf     ɛpuze     3
432549     éprouver  pi1S     ɛpʁuv     1
432689      épuiser  ppMS    ɛpɥize     3
432691      épuiser  ppFS    ɛpɥize     1
433912      établir  ppMS    ɛtabli     1
433922      établir   inf   ɛtabliʁ     2
434048         être  ii3P       ɛtɛ     5
434068         être  ii1S       ɛtɛ    11
434069         être  ii2S       ɛtɛ     1
434070         être  ii3S       ɛtɛ    88
434811      étendre  ai3S    ɛtɑ̃di     1
435054         être  ii2P      ɛtje     2
435074    étinceler   inf  ɛtɛ̃səle     1
435172         être  ii1P     ɛtjɔ̃     1
435425      étonner    pP    ɛtɔnɑ̃     1
435438      étonner  pi3S      ɛtɔn     1
435791    étreindre  ii3P    ɛtʁɛɲɛ     1
436227      étudier  pi1P   ɛtydjɔ̃     1
436316         être  ppMS       ɛte    21
436820     éveiller  ii3S     ɛvɛjɛ     1
436831     éveiller  pi3S      ɛvɛj     1
437027     éventrer  ppMP   ɛvɑ̃tʁe     1
437474         être  pi2P        ɛt    16
437476         être   inf       ɛtʁ    25

[1938 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 20.9 s, total: 1min 38s
Wall time: 32.1 s

nbChunk 112
4200
1937

             lexeme  case      phono  tir1
40            avoir  pi3S          a    86
52         abaisser    pP     abɛsɑ̃     1
111      abandonner  ii1S   abɑ̃dɔnɛ     1
113      abandonner  ii3S   abɑ̃dɔnɛ     1
114      abandonner    pP  abɑ̃dɔnɑ̃     1
132      abandonner   inf   abɑ̃dɔne     2
1147        aborder   inf     abɔʁde     1
1174        aborder  ai3P    abɔʁdɛʁ     1
1175        aborder  ppMS     abɔʁde     1
1950       absenter   inf    absɑ̃te     1
2100       absorber  ppMS    absɔʁbe     1
2124       absoudre  pi1S       absu     1
2967       accepter  pi3S     aksɛpt     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3490      accomplir  pi3S    akɔ̃pli     1
3530       accorder  pi3S      akɔʁd     2
3629       accoster  ai3S     akɔsta     1
4255      accrocher  pi3S      akʁɔʃ     1
4291      accrocher  ppMS     akʁɔʃe     1
4373      accroître  pi3S      akʁwa     1
4482     accueillir  pi3S       akœj     1
4502     accueillir  ppMS      akəji     1
4716        accuser  pi3S       akyz     1
4758        accéder  pi3S      aksɛd     1
4862      accélérer  ppMS   aksɛlɛʁe     2
5107        acheter  ai1S      aʃətɛ     1
5119        acheter   inf      aʃəte     3
5136        acheter  ppMS      aʃəte     3
...             ...   ...        ...   ...
432519     éprendre  ppMS       ɛpʁi     1
432537     éprouver  ii3S     ɛpʁuvɛ     2
432556     éprouver   inf     ɛpʁuve     1
433325      érafler   inf     ɛʁafle     1
433790      éructer  pi3S      ɛʁykt     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    13
434070         être  ii3S        ɛtɛ    66
434299       étaler  ppMS      ɛtale     1
434488         être    pP       ɛtɑ̃     1
434762     éteindre   inf     ɛtɛ̃dʁ     2
434773     éteindre  pi3S       ɛtɛ̃     1
434833      étendre  ppFS     ɛtɑ̃dy     1
434889    éterniser  pI1P  ɛtɛʁnizɔ̃     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     2
435243       étirer  ii3S      ɛtiʁɛ     1
435425      étonner    pP     ɛtɔnɑ̃     1
435500     étouffer  pi3S       ɛtuf     1
436188      étudier    pP    ɛtydjɑ̃     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    29
436520      évaluer   inf     ɛvalye     1
436869     éveiller  ppFS      ɛvɛje     1
437295       éviter  pi3S       ɛvit     1
437301       éviter   inf      ɛvite     1
437431      évoquer   inf      ɛvɔke     2
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    18
437539         ôter  ppMS        ɔte     1

[1937 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 20.5 s, total: 1min 35s
Wall time: 30.5 s

nbChunk 113
4200
1914

             lexeme  case     phono  tir1
40            avoir  pi3S         a    81
132      abandonner   inf  abɑ̃dɔne     2
164      abandonner  ppMS  abɑ̃dɔne     1
305         abattre  ppMS     abaty     1
307         abattre  ppFS     abaty     1
887          abolir  ppMS     abɔli     1
1171        aborder  ai1P   abɔʁdam     1
1388        aboutir  ppMS     abuti     1
1393        aboutir   inf    abutiʁ     2
1425        aboutir  pi3P    abutis     1
1946       absenter  pi3S    absɑ̃t     1
2345         abuser  pc3S   abyzəʁɛ     1
2736       accabler   inf    akable     1
2887      accentuer  ii3S  aksɑ̃tyɛ     1
2967       accepter  pi3S    aksɛpt     1
2971       accepter   inf   aksɛpte     2
3385    accompagner  ii3S  akɔ̃paɲɛ     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3419    accompagner  pi2S   akɔ̃paɲ     1
3443      accomplir   inf  akɔ̃pliʁ     1
3538       accorder  fi1S  akɔʁdəʁɛ     1
4259      accrocher   inf    akʁɔʃe     1
4337      accroupir  ppMP    akʁupi     1
4748        accuser  ppMS     akyze     1
5119        acheter   inf     aʃəte     3
5136        acheter  ppMS     aʃəte     1
5165        achever  pi1P    aʃəvɔ̃     1
5329        achever  pi1S      aʃɛv     1
5812       acquérir  ppFS      akiz     1
6108        activer  ppMS    aktive     1
...             ...   ...       ...   ...
428572  émerveiller  pi3S   ɛmɛʁvɛj     1
428640      émettre   inf     ɛmɛtʁ     1
428742      émigrer   inf    ɛmigʁe     1
429694      énerver  pi3S     ɛnɛʁv     1
429700      énerver   inf    ɛnɛʁve     1
430668       épater    pP    ɛpatɑ̃     1
432519     éprendre  ppMS      ɛpʁi     1
432691      épuiser  ppFS    ɛpɥize     1
434048         être  ii3P       ɛtɛ     1
434068         être  ii1S       ɛtɛ    14
434070         être  ii3S       ɛtɛ    74
434147       étaler  pi3S      ɛtal     1
434300       étaler  ppFS     ɛtale     1
434773     éteindre  pi3S      ɛtɛ̃     3
434833      étendre  ppFS    ɛtɑ̃dy     1
435062    étinceler  ii3S  ɛtɛ̃səlɛ     1
435172         être  ii1P     ɛtjɔ̃     1
435438      étonner  pi3S      ɛtɔn     2
435471      étonner  ppMS     ɛtɔne     1
435484     étouffer  ii3S     ɛtufɛ     1
435504     étouffer  pi3P      ɛtuf     1
436201      étudier  pi3S     ɛtydi     1
436316         être  ppMS       ɛte    29
436821     éveiller    pP    ɛvɛjɑ̃     1
436835     éveiller   inf     ɛvɛje     2
437285       éviter    pP    ɛvitɑ̃     1
437301       éviter   inf     ɛvite     1
437474         être  pi2P        ɛt    20
437476         être   inf       ɛtʁ    16
437519         ôter  fi2S     ɔtəʁa     1

[1914 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 20.4 s, total: 1min 35s
Wall time: 30.8 s

nbChunk 114
4200
1907

            lexeme  case       phono  tir1
40           avoir  pi3S           a    81
128     abandonner  pi3S     abɑ̃dɔn     1
132     abandonner   inf    abɑ̃dɔne     1
297        abattre  pc3S      abatʁɛ     1
299        abattre   inf       abatʁ     1
1393       aboutir   inf      abutiʁ     1
1688       abriter   inf      abʁite     1
1801       abrutir   inf     abʁytiʁ     1
2070      absorber   inf     absɔʁbe     1
2967      accepter  pi3S      aksɛpt     1
2971      accepter   inf     aksɛpte     1
2973      accepter  fi1S   aksɛptəʁɛ     1
2983      accepter  fi3P  aksɛptəʁɔ̃     1
3003      accepter  ppMS     aksɛpte     1
3009      accepter  ppMP     aksɛpte     1
3443     accomplir   inf    akɔ̃pliʁ     2
3475     accomplir  pi3P    akɔ̃plis     1
3490     accomplir  pi3S     akɔ̃pli     1
3583      accorder  ppMP      akɔʁde     1
4290     accrocher  ai3P     akʁɔʃɛʁ     1
4303     accroître  ii3S     akʁwasɛ     1
4502    accueillir  ppMS       akəji     1
4509    accueillir   inf      akəjiʁ     1
4783       accéder   inf      aksɛde     2
4812     accélérer  pi3S     aksɛlɛʁ     1
5008      acharner  pi3S       aʃaʁn     1
5119       acheter   inf       aʃəte     2
5136       acheter  ppMS       aʃəte     3
5146       achever  ii3P       aʃəvɛ     1
5308       acheter  pi1S        aʃɛt     1
...            ...   ...         ...   ...
432184     épouser  ii1P     ɛpuzjɔ̃     1
432303     épouser  ppFS       ɛpuze     1
432535    éprouver  ii1S      ɛpʁuvɛ     1
432537    éprouver  ii3S      ɛpʁuvɛ     1
432552    éprouver  pi3S       ɛpʁuv     1
432635     épuiser  ii3P      ɛpɥizɛ     1
432657     épuiser  pi3P       ɛpɥiz     1
434048        être  ii3P         ɛtɛ     3
434068        être  ii1S         ɛtɛ    12
434070        être  ii3S         ɛtɛ    77
434762    éteindre   inf      ɛtɛ̃dʁ     1
434794     étendre  pi3P       ɛtɑ̃d     1
434831     étendre  ppMS      ɛtɑ̃dy     1
434868   éterniser   inf    ɛtɛʁnize     1
435054        être  ii2P        ɛtje     1
435111   étinceler  ai3P   ɛtɛ̃səlɛʁ     1
435172        être  ii1P       ɛtjɔ̃     2
435260      étirer   inf       ɛtiʁe     1
435442     étonner  pi3P        ɛtɔn     1
435739   étrangler  pi1S     ɛtʁɑ̃gl     1
436316        être  ppMS         ɛte    21
436535     évaluer  pI2P      ɛvalye     1
436831    éveiller  pi3S        ɛvɛj     1
437284      éviter  ii3S       ɛvitɛ     1
437301      éviter   inf       ɛvite     1
437474        être  pi2P          ɛt    16
437476        être   inf         ɛtʁ    30
437497        ôter  ii3S         ɔtɛ     1
437512        ôter   inf         ɔte     1
437539        ôter  ppMS         ɔte     1

[1907 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 20.4 s, total: 1min 36s
Wall time: 30.4 s

nbChunk 115
4200
1912

             lexeme  case      phono  tir1
40            avoir  pi3S          a    85
113      abandonner  ii3S   abɑ̃dɔnɛ     1
128      abandonner  pi3S    abɑ̃dɔn     1
164      abandonner  ppMS   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
1147        aborder   inf     abɔʁde     1
1393        aboutir   inf     abutiʁ     1
1415        aboutir  ii3S    abutisɛ     1
1543        abraser  ppMS     abʁaze     1
1979       absenter  ppMS    absɑ̃te     1
2267      abstraire   inf    abstʁɛʁ     1
2581         abîmer   inf      abime     1
2950       accepter  ii3S    aksɛptɛ     1
2964       accepter  pi1S     aksɛpt     1
3003       accepter  ppMS    aksɛpte     1
3406    accompagner   inf   akɔ̃paɲe     1
3438      accomplir  ppMS    akɔ̃pli     3
4009       accourir  ii3S      akuʁɛ     1
4074       accourir  pi1P     akuʁɔ̃     1
4511     accueillir  ppMP      akəji     1
4652      accumuler  pi3S     akymyl     1
4693        accuser  ii3S      akyzɛ     1
4716        accuser  pi3S       akyz     1
4816      accélérer  pi2S    aksɛlɛʁ     1
5014       acharner   inf     aʃaʁne     1
5027       acharner  pi2S      aʃaʁn     1
5119        acheter   inf      aʃəte     1
5171        achever  ppMS      aʃəve     1
6457    additionner    pP  adisjɔnɑ̃     1
6988        admirer  pi1S      admiʁ     1
...             ...   ...        ...   ...
429275     émousser  ppMS      ɛmuse     1
429337     émouvoir  ii3S      ɛmuvɛ     1
429694      énerver  pi3S      ɛnɛʁv     1
429727      énerver  ppMS     ɛnɛʁve     1
430340     épancher   inf     ɛpɑ̃ʃe     1
432160      épouser   inf      ɛpuze     2
432537     éprouver  ii3S     ɛpʁuvɛ     1
432588     éprouver  ppFS     ɛpʁuve     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    11
434070         être  ii3S        ɛtɛ    77
434488         être    pP       ɛtɑ̃     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434770     éteindre  pi2S       ɛtɛ̃     1
434772     éteindre  ppMS       ɛtɛ̃     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     3
435438      étonner  pi3S       ɛtɔn     1
435444      étonner   inf      ɛtɔne     1
436198      étudier  pi1S      ɛtydi     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    13
436402      évacuer   inf     ɛvakye     1
436473       évader  pi2P      ɛvade     1
436820     éveiller  ii3S      ɛvɛjɛ     1
436835     éveiller   inf      ɛvɛje     1
437474         être  pi2P         ɛt    10
437476         être   inf        ɛtʁ    21

[1912 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 21 s, total: 1min 39s
Wall time: 31.8 s

nbChunk 116
4200
1993

             lexeme  case       phono  tir1
40            avoir  pi3S           a    86
67         abaisser  pi3S        abɛs     1
109      abandonner  ai1S    abɑ̃dɔnɛ     1
132      abandonner   inf    abɑ̃dɔne     1
166      abandonner  ppFS    abɑ̃dɔne     1
243         abattre  pi3S         aba     1
313         abattre  ppMP       abaty     1
2950       accepter  ii3S     aksɛptɛ     2
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     3
3397    accompagner  pi1S     akɔ̃paɲ     1
3549       accorder  pi2S       akɔʁd     1
3913       accouder  ppMS       akude     1
4230      accrocher  ai3S      akʁɔʃa     2
4237      accrocher  ii3S      akʁɔʃɛ     1
4321      accroupir  ppFS      akʁupi     1
4748        accuser  ppMS       akyze     1
4818      accélérer  ai3S    aksɛlɛʁa     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     2
5316        acheter  fi1S     aʃɛtəʁɛ     1
5332        achever  pi3S        aʃɛv     1
6481    additionner  pc3S  adisjɔnəʁɛ     1
6970        admirer    pP     admiʁɑ̃     1
7283        adopter  ppMS      adɔpte     2
7332         adorer  pi2P       adɔʁe     1
7523       adresser  ii3S      adʁɛsɛ     1
7532       adresser  pi1S       adʁɛs     1
7539       adresser   inf      adʁɛse     3
7777        advenir  ppMS      advəny     1
...             ...   ...         ...   ...
427733        élire  ppMS         ɛly     1
430645   éparpiller  ppFP    ɛpaʁpije     1
431971      éponger  pi3S       ɛpɔ̃ʒ     1
432158      épouser  pi3P        ɛpuz     1
432160      épouser   inf       ɛpuze     1
432164      épouser  pc1S     ɛpuzəʁɛ     1
432173      épouser  pi2S        ɛpuz     1
432556     éprouver   inf      ɛpʁuve     1
433912      établir  ppMS      ɛtabli     1
433914      établir  ppFS      ɛtabli     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    11
434070         être  ii3S         ɛtɛ    75
434134       étaler  ii3S       ɛtalɛ     1
434833      étendre  ppFS      ɛtɑ̃dy     1
434836      étendre  ppFP      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     4
435422      étonner  ii3S       ɛtɔnɛ     1
435438      étonner  pi3S        ɛtɔn     1
436316         être  ppMS         ɛte    17
436536      évaluer  pi2P      ɛvalye     1
436629     évanouir  ppFS      ɛvanui     1
437292       éviter  pi1S        ɛvit     1
437301       éviter   inf       ɛvite     1
437427      évoquer  pi3S        ɛvɔk     1
437431      évoquer   inf       ɛvɔke     1
437474         être  pi2P          ɛt    10
437476         être   inf         ɛtʁ    14

[1993 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 21.2 s, total: 1min 39s
Wall time: 31.2 s

nbChunk 117
4200
1981

             lexeme  case      phono  tir1
40            avoir  pi3S          a    91
111      abandonner  ii1S   abɑ̃dɔnɛ     1
148      abandonner  pi2P   abɑ̃dɔne     1
299         abattre   inf      abatʁ     2
305         abattre  ppMS      abaty     1
1110        abonner  ppMS      abɔne     1
2610         abîmer  ppMS      abime     1
2967       accepter  pi3S     aksɛpt     1
2978       accepter  fi2S  aksɛptəʁa     1
2989       accepter  pi2P    aksɛpte     1
3003       accepter  ppMS    aksɛpte     2
3115       acclamer  pi3P      aklam     1
3319     accommoder  ii3P    akɔmɔdɛ     1
3404    accompagner  pi3P    akɔ̃paɲ     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3434    accompagner  ppFS   akɔ̃paɲe     1
3571       accorder  ppMS     akɔʁde     2
3827      accoucher   inf      akuʃe     1
3913       accouder  ppMS      akude     1
3916       accouder  ppMP      akude     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4684      accumuler  ppFS    akymyle     1
4720        accuser   inf      akyze     2
4755        accéder  pi1S      aksɛd     1
4771        accéder  ii3S     aksɛdɛ     1
4783        accéder   inf     aksɛde     1
4835      accélérer   inf   aksɛlɛʁe     1
4997       acharner  ii3S     aʃaʁnɛ     1
5070      acheminer   inf    aʃəmine     1
5108        acheter  ii3P      aʃətɛ     1
...             ...   ...        ...   ...
432586     éprouver  ppMS     ɛpʁuve     1
432689      épuiser  ppMS     ɛpɥize     1
433790      éructer  pi3S      ɛʁykt     1
433939      établir  pi1S     ɛtabli     1
433943      établir  ii3P   ɛtablisɛ     1
434048         être  ii3P        ɛtɛ     6
434068         être  ii1S        ɛtɛ     7
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    65
434772     éteindre  ppMS       ɛtɛ̃     1
434833      étendre  ppFS     ɛtɑ̃dy     1
434836      étendre  ppFP     ɛtɑ̃dy     1
434839      étendre  ppMP     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     4
435172         être  ii1P      ɛtjɔ̃     1
435444      étonner   inf      ɛtɔne     1
435471      étonner  ppMS      ɛtɔne     2
435748    étrangler   inf   ɛtʁɑ̃gle     1
435795    étreindre    pP    ɛtʁɛɲɑ̃     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    19
436711     évaporer   inf    ɛvapɔʁe     1
436815     éveiller  ai3S      ɛvɛja     1
436835     éveiller   inf      ɛvɛje     1
437295       éviter  pi3S       ɛvit     1
437301       éviter   inf      ɛvite     2
437407      évoluer  ppMS     ɛvɔlye     1
437474         être  pi2P         ɛt    10
437476         être   inf        ɛtʁ    23
437512         ôter   inf        ɔte     2

[1981 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 21.3 s, total: 1min 39s
Wall time: 31.2 s

nbChunk 118
4200
1993

            lexeme  case     phono  tir1
40           avoir  pi3S         a    90
128     abandonner  pi3S   abɑ̃dɔn     1
129     abandonner  ps3S   abɑ̃dɔn     1
132     abandonner   inf  abɑ̃dɔne     2
164     abandonner  ppMS  abɑ̃dɔne     1
166     abandonner  ppFS  abɑ̃dɔne     3
299        abattre   inf     abatʁ     2
1555      abreuver    pP   abʁəvɑ̃     1
2068      absorber  pi3P    absɔʁb     1
2123      absoudre  ppMS      absu     1
2371        abuser  ppMS     abyze     1
2984      accepter  pi2S    aksɛpt     1
3003      accepter  ppMS   aksɛpte     3
3573      accorder  ppFS    akɔʁde     1
3868      accouder    pP    akudɑ̃     1
4294     accrocher  ppMP    akʁɔʃe     1
4736       accuser  pi2P     akyze     1
5119       acheter   inf     aʃəte     3
5136       acheter  ppMS     aʃəte     1
5157       achever   inf     aʃəve     1
5308       acheter  pi1S      aʃɛt     1
5843     acquitter  pi1S      akit     1
6862      admettre  pi3S      admɛ     1
6967       admirer  ii1S    admiʁɛ     1
7312        adorer  pi3S      adɔʁ     1
7343        adorer  ppMS     adɔʁe     1
7344        adorer  ppFS     adɔʁe     1
7524      adresser    pP   adʁɛsɑ̃     1
7569      adresser  ppFP    adʁɛse     1
8240       affaler  ppMS     afale     1
...            ...   ...       ...   ...
429698     énerver  pi3P     ɛnɛʁv     1
429700     énerver   inf    ɛnɛʁve     1
429834     énoncer  ai3S    ɛnɔ̃sa     1
430480    épanouir  ppMS    ɛpanui     1
430591    épargner  ppFS    ɛpaʁɲe     1
432160     épouser   inf     ɛpuze     2
432302     épouser  ppMS     ɛpuze     1
432482    éprendre    pP   ɛpʁənɑ̃     1
432537    éprouver  ii3S    ɛpʁuvɛ     1
434048        être  ii3P       ɛtɛ     1
434068        être  ii1S       ɛtɛ    16
434070        être  ii3S       ɛtɛ    67
434747    éteindre  ai3S     ɛtɛɲi     1
434789     étendre    pP   ɛtɑ̃dɑ̃     1
435054        être  ii2P      ɛtje     4
435172        être  ii1P     ɛtjɔ̃     1
435417     étonner  ai3S     ɛtɔna     1
435438     étonner  pi3S      ɛtɔn     1
435782   étrangler  ppFS  ɛtʁɑ̃gle     1
436218     étudier  pi2S     ɛtydi     1
436233     étudier  ppMS    ɛtydje     2
436316        être  ppMS       ɛte    21
436520     évaluer   inf    ɛvalye     1
437301      éviter   inf     ɛvite     2
437414     évoquer  ii1S     ɛvɔkɛ     1
437417     évoquer    pP    ɛvɔkɑ̃     1
437437     évoquer  pc3S   ɛvɔkəʁɛ     1
437474        être  pi2P        ɛt    11
437476        être   inf       ɛtʁ    22
437508        ôter  pi3S        ot     2

[1993 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 20 s, total: 1min 34s
Wall time: 30.1 s

nbChunk 119
4200
1904

             lexeme  case       phono  tir1
40            avoir  pi3S           a    72
45         abaisser  ai3S       abɛsa     1
125      abandonner  pi1S     abɑ̃dɔn     1
128      abandonner  pi3S     abɑ̃dɔn     1
138      abandonner  pc3S  abɑ̃dɔnəʁɛ     1
890          abolir   inf      abɔliʁ     1
1681        abriter  pi1S       abʁit     1
2581         abîmer   inf       abime     1
2610         abîmer  ppMS       abime     1
2964       accepter  pi1S      aksɛpt     1
2971       accepter   inf     aksɛpte     3
2984       accepter  pi2S      aksɛpt     1
3005       accepter  ppFS     aksɛpte     1
3400    accompagner  pi3S     akɔ̃paɲ     2
3406    accompagner   inf    akɔ̃paɲe     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
3519       accorder  ii3S      akɔʁdɛ     1
3573       accorder  ppFS      akɔʁde     1
3949      accoupler  ii3P      akuplɛ     1
4252      accrocher  pi1S       akʁɔʃ     1
4473     accueillir  ii3S       akəjɛ     1
4693        accuser  ii3S       akyzɛ     1
4783        accéder   inf      aksɛde     1
5119        acheter   inf       aʃəte     2
5159        achever  pi2P       aʃəve     1
5311        acheter  pi3S        aʃɛt     1
5316        acheter  fi1S     aʃɛtəʁɛ     1
5807       acquérir  ppMS         aki     1
5905       acquérir   inf      akɛʁiʁ     1
...             ...   ...         ...   ...
431973      éponger  ai3S      ɛpɔ̃ʒa     1
432162      épouser  fi1S     ɛpuzəʁɛ     1
432532     éprouver  ai3S      ɛpʁuva     1
432556     éprouver   inf      ɛpʁuve     1
432770       épurer  ppFS       ɛpyʁe     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     7
434068         être  ii1S         ɛtɛ    12
434070         être  ii3S         ɛtɛ    83
434779     éteindre  ppMP        ɛtɛ̃     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434836      étendre  ppFP      ɛtɑ̃dy     1
434917     éternuer  pi3S      ɛtɛʁny     1
435054         être  ii2P        ɛtje     2
435133      étioler  pi3P       ɛtjɔl     1
435172         être  ii1P       ɛtjɔ̃     3
435229    étiqueter  ppFS     ɛtikəte     1
435444      étonner   inf       ɛtɔne     1
435470      étonner  ai3P      ɛtɔnɛʁ     1
435484     étouffer  ii3S       ɛtufɛ     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    18
436547      évaluer  ppMS      ɛvalye     1
436815     éveiller  ai3S       ɛvɛja     1
437025     éventrer  ppFS     ɛvɑ̃tʁe     1
437295       éviter  pi3S        ɛvit     1
437301       éviter   inf       ɛvite     1
437474         être  pi2P          ɛt    15
437476         être   inf         ɛtʁ    19
437495         ôter  ii1S         ɔtɛ     1

[1904 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 21 s, total: 1min 38s
Wall time: 30.8 s

nbChunk 120
4200
1961

             lexeme  case      phono  tir1
40            avoir  pi3S          a   109
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     2
166      abandonner  ppFS   abɑ̃dɔne     1
170      abandonner  ppMP   abɑ̃dɔne     1
243         abattre  pi3S        aba     1
258         abattre  ii3S      abatɛ     1
305         abattre  ppMS      abaty     1
412        abdiquer  pi3S      abdik     1
1166        aborder  ii1P   abɔʁdjɔ̃     1
1169        aborder  pi1P    abɔʁdɔ̃     1
2339         abuser   inf      abyze     1
2581         abîmer   inf      abime     1
2887      accentuer  ii3S   aksɑ̃tyɛ     2
2939       accepter  ai3S    aksɛpta     3
2975       accepter  pc1S  aksɛptəʁɛ     1
3003       accepter  ppMS    aksɛpte     1
3386    accompagner    pP  akɔ̃paɲɑ̃     1
3406    accompagner   inf   akɔ̃paɲe     1
3530       accorder  pi3S      akɔʁd     1
3536       accorder   inf     akɔʁde     1
3825      accoucher  pi3P       akuʃ     1
4291      accrocher  ppMS     akʁɔʃe     2
4320      accroupir  ppMS     akʁupi     1
4995       acharner  ii1S     aʃaʁnɛ     1
5111        acheter  ii3S      aʃətɛ     1
5119        acheter   inf      aʃəte     4
5136        acheter  ppMS      aʃəte     2
5137        acheter  ppFS      aʃəte     1
5139        acheter  ppMP      aʃəte     1
...             ...   ...        ...   ...
433916      établir  ppFP     ɛtabli     1
433928      établir  pc3S   ɛtabliʁɛ     1
434048         être  ii3P        ɛtɛ     1
434068         être  ii1S        ɛtɛ    10
434070         être  ii3S        ɛtɛ    70
434721       étayer  ppFP      ɛtɛje     1
434768     éteindre  pi1S       ɛtɛ̃     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
434841      étendre  is3S     ɛtɑ̃di     1
434950     éternuer  ppMS    ɛtɛʁnye     1
435054         être  ii2P       ɛtje     1
435244       étirer    pP     ɛtiʁɑ̃     1
435254       étirer  pi3S       ɛtiʁ     1
435293       étirer  ppMS      ɛtiʁe     1
435422      étonner  ii3S      ɛtɔnɛ     1
435438      étonner  pi3S       ɛtɔn     1
435542     étouffer  ppFP      ɛtufe     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    20
436457       évader   inf      ɛvade     1
436484       évader  ppMS      ɛvade     1
436627     évanouir  ppMS     ɛvanui     1
437301       éviter   inf      ɛvite     2
437413      évoquer  ii3P      ɛvɔkɛ     2
437414      évoquer  ii1S      ɛvɔkɛ     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    15
437492         ôter  ai3S        ɔta     1
437508         ôter  pi3S         ot     1

[1961 rows x 4 columns]

0
CPU times: user 1min 19s, sys: 20.2 s, total: 1min 39s
Wall time: 30.7 s

nbChunk 121
4200
1942

             lexeme  case     phono  tir1
40            avoir  pi3S         a    88
164      abandonner  ppMS  abɑ̃dɔne     1
168      abandonner  ppFP  abɑ̃dɔne     1
292         abattre  fi3S    abatʁa     1
955         abonder  ii3P    abɔ̃dɛ     1
1147        aborder   inf    abɔʁde     1
2371         abuser  ppMS     abyze     1
2887      accentuer  ii3S  aksɑ̃tyɛ     1
2952       accepter    pP  aksɛptɑ̃     1
2967       accepter  pi3S    aksɛpt     1
2971       accepter   inf   aksɛpte     1
3385    accompagner  ii3S  akɔ̃paɲɛ     1
3397    accompagner  pi1S   akɔ̃paɲ     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3571       accorder  ppMS    akɔʁde     1
4255      accrocher  pi3S     akʁɔʃ     1
4257      accrocher  pi3P     akʁɔʃ     1
4283      accrocher  ii1P  akʁɔʃjɔ̃     1
4748        accuser  ppMS     akyze     2
4771        accéder  ii3S    aksɛdɛ     1
4784        accéder  fi3S  aksɛdəʁa     1
4835      accélérer   inf  aksɛlɛʁe     1
4862      accélérer  ppMS  aksɛlɛʁe     1
5111        acheter  ii3S     aʃətɛ     1
5119        acheter   inf     aʃəte     1
5308        acheter  pi1S      aʃɛt     1
5311        acheter  pi3S      aʃɛt     2
6068        activer  ps3S     aktiv     1
6108        activer  ppMS    aktive     1
6967        admirer  ii1S    admiʁɛ     1
...             ...   ...       ...   ...
429365     émouvoir  ppMS       ɛmy     1
429694      énerver  pi3S     ɛnɛʁv     1
430017     énumérer  pi3S    ɛnymɛʁ     1
431321    épiloguer   inf   ɛpilɔge     1
432056    épouiller   inf     ɛpuje     1
432160      épouser   inf     ɛpuze     2
432302      épouser  ppMS     ɛpuze     1
432537     éprouver  ii3S    ɛpʁuvɛ     1
432689      épuiser  ppMS    ɛpɥize     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ    11
434070         être  ii3S       ɛtɛ    76
434147       étaler  pi3S      ɛtal     1
434773     éteindre  pi3S      ɛtɛ̃     1
434782      étendre  pi3S      ɛtɑ̃     2
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     3
435422      étonner  ii3S     ɛtɔnɛ     1
435435      étonner  pi1S      ɛtɔn     1
435438      étonner  pi3S      ɛtɔn     2
435471      étonner  ppMS     ɛtɔne     1
435506     étouffer   inf     ɛtufe     1
436201      étudier  pi3S     ɛtydi     1
436316         être  ppMS       ɛte    13
437301       éviter   inf     ɛvite     1
437424      évoquer  pi1S      ɛvɔk     1
437474         être  pi2P        ɛt    13
437476         être   inf       ɛtʁ    16
437512         ôter   inf       ɔte     1
437539         ôter  ppMS       ɔte     1

[1942 rows x 4 columns]

0
CPU times: user 1min 19s, sys: 21.2 s, total: 1min 40s
Wall time: 31.2 s

nbChunk 122
4200
2008

             lexeme  case       phono  tir1
40            avoir  pi3S           a    78
305         abattre  ppMS       abaty     2
1468         aboyer   inf      abwaje     1
1796        abrutir  ppMS      abʁyti     1
2277      abstraire  ppMS      abstʁɛ     1
2339         abuser   inf       abyze     1
2560         abîmer  ai3S       abima     1
2977       accepter  pc3S   aksɛptəʁɛ     1
3003       accepter  ppMS     aksɛpte     2
3406    accompagner   inf    akɔ̃paɲe     1
3408    accompagner  fi1S  akɔ̃paɲəʁɛ     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3443      accomplir   inf    akɔ̃pliʁ     1
3530       accorder  pi3S       akɔʁd     1
3536       accorder   inf      akɔʁde     1
3573       accorder  ppFS      akɔʁde     1
4255      accrocher  pi3S       akʁɔʃ     2
4473     accueillir  ii3S       akəjɛ     1
4748        accuser  ppMS       akyze     1
4862      accélérer  ppMS    aksɛlɛʁe     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     4
5149        achever  ii3S       aʃəvɛ     1
5308        acheter  pi1S        aʃɛt     1
5311        acheter  pi3S        aʃɛt     1
6410        adapter  pi3S       adapt     1
7031       admettre  ppFS       admiz     1
7309         adorer  pi1S        adɔʁ     1
7312         adorer  pi3S        adɔʁ     2
7314         adorer  pi3P        adɔʁ     1
...             ...   ...         ...   ...
434070         être  ii3S         ɛtɛ    65
434134       étaler  ii3S       ɛtalɛ     1
434147       étaler  pi3S        ɛtal     1
434488         être    pP        ɛtɑ̃     1
434727     éteindre    pP      ɛtɛɲɑ̃     1
434729     éteindre  ps3S        ɛtɛɲ     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434768     éteindre  pi1S        ɛtɛ̃     1
434794      étendre  pi3P       ɛtɑ̃d     1
434831      étendre  ppMS      ɛtɑ̃dy     1
434833      étendre  ppFS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     1
435239       étirer  ai1S       ɛtiʁɛ     1
435422      étonner  ii3S       ɛtɔnɛ     1
435471      étonner  ppMS       ɛtɔne     1
435474      étonner  ppMP       ɛtɔne     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436221      étudier  pi2P      ɛtydje     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    22
436484       évader  ppMS       ɛvade     1
436831     éveiller  pi3S        ɛvɛj     1
437282       éviter  ii1S       ɛvitɛ     1
437285       éviter    pP      ɛvitɑ̃     1
437302       éviter  fi3S     ɛvitəʁa     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437429      évoquer  pi3P        ɛvɔk     1
437474         être  pi2P          ɛt    15
437476         être   inf         ɛtʁ    19

[2008 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 19.4 s, total: 1min 35s
Wall time: 31.1 s

nbChunk 123
4200
1915

             lexeme  case      phono  tir1
40            avoir  pi3S          a    99
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
148      abandonner  pi2P   abɑ̃dɔne     2
164      abandonner  ppMS   abɑ̃dɔne     2
277         abattre  ai3P     abatiʁ     1
299         abattre   inf      abatʁ     1
1121        aborder  ai3S     abɔʁda     1
2339         abuser   inf      abyze     1
2616         abîmer  ppMP      abime     1
2939       accepter  ai3S    aksɛpta     1
2952       accepter    pP   aksɛptɑ̃     1
2971       accepter   inf    aksɛpte     1
2973       accepter  fi1S  aksɛptəʁɛ     1
2990       accepter  ii2P   aksɛptje     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3406    accompagner   inf   akɔ̃paɲe     2
3471      accomplir  ps3S   akɔ̃plis     1
3536       accorder   inf     akɔʁde     2
4509     accueillir   inf     akəjiʁ     1
4652      accumuler  pi3S     akymyl     1
4713        accuser  pi1S       akyz     1
4716        accuser  pi3S       akyz     2
4835      accélérer   inf   aksɛlɛʁe     1
5119        acheter   inf      aʃəte     3
5136        acheter  ppMS      aʃəte     1
5140        achever  ai3S      aʃəva     1
5879      acquitter  ppMS      akite     1
6891       admettre   inf     admɛtʁ     1
6991        admirer  pi3S      admiʁ     1
...             ...   ...        ...   ...
432303      épouser  ppFS      ɛpuze     1
432580     éprouver  pi1P    ɛpʁuvɔ̃     1
432586     éprouver  ppMS     ɛpʁuve     1
434048         être  ii3P        ɛtɛ     7
434068         être  ii1S        ɛtɛ    12
434070         être  ii3S        ɛtɛ    69
434153       étaler   inf      ɛtale     1
434723     éteindre  ii3P      ɛtɛɲɛ     1
434727     éteindre    pP     ɛtɛɲɑ̃     1
434773     éteindre  pi3S       ɛtɛ̃     1
434775     éteindre  ppFS      ɛtɛ̃t     2
434785      étendre  ii3P     ɛtɑ̃dɛ     1
434794      étendre  pi3P      ɛtɑ̃d     1
435054         être  ii2P       ɛtje     4
435306      étoffer  ii3S      ɛtɔfɛ     1
435435      étonner  pi1S       ɛtɔn     1
435438      étonner  pi3S       ɛtɔn     1
435472      étonner  ppFS      ɛtɔne     1
435504     étouffer  pi3P       ɛtuf     1
435519     étouffer  pi2S       ɛtuf     1
435540     étouffer  ppFS      ɛtufe     1
436184      étudier  ii1S     ɛtydjɛ     1
436316         être  ppMS        ɛte    18
436632     évanouir   inf    ɛvanuiʁ     1
437301       éviter   inf      ɛvite     1
437367      évoluer   inf     ɛvɔlye     1
437474         être  pi2P         ɛt    13
437476         être   inf        ɛtʁ    25
437508         ôter  pi3S         ot     1
437512         ôter   inf        ɔte     1

[1915 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 20.7 s, total: 1min 39s
Wall time: 31.2 s

nbChunk 124
4200
1928

             lexeme  case     phono  tir1
40            avoir  pi3S         a    80
125      abandonner  pi1S   abɑ̃dɔn     1
259         abattre    pP    abatɑ̃     1
287         abattre  ai3S     abati     1
305         abattre  ppMS     abaty     1
1147        aborder   inf    abɔʁde     1
1393        aboutir   inf    abutiʁ     1
1571       abreuver   inf    abʁəve     1
2371         abuser  ppMS     abyze     1
2947       accepter  ii3P   aksɛptɛ     1
2967       accepter  pi3S    aksɛpt     1
2969       accepter  pi3P    aksɛpt     1
3314        accoler  ppFS     akɔle     1
3383    accompagner  ii1S  akɔ̃paɲɛ     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     1
3519       accorder  ii3S    akɔʁdɛ     2
3530       accorder  pi3S     akɔʁd     1
3536       accorder   inf    akɔʁde     1
3834      accoucher  fi2S   akuʃəʁa     1
3914       accouder  ppFS     akude     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4368      accroupir  ai3S    akʁupi     1
4473     accueillir  ii3S     akəjɛ     1
4634      accumuler  ii3P   akymylɛ     1
4720        accuser   inf     akyze     1
4803        accéder  pi1P   aksɛdɔ̃     1
5102        acheter  ai3S     aʃəta     1
5119        acheter   inf     aʃəte     3
5136        acheter  ppMS     aʃəte     1
...             ...   ...       ...   ...
429728      énerver  ppFS    ɛnɛʁve     1
430042     énumérer   inf   ɛnymɛʁe     1
430482     épanouir  ppFS    ɛpanui     1
430555     épargner  pi1S     ɛpaʁɲ     1
432689      épuiser  ppMS    ɛpɥize     1
433113      équiper   inf     ɛkipe     1
434048         être  ii3P       ɛtɛ     5
434068         être  ii1S       ɛtɛ     9
434070         être  ii3S       ɛtɛ    72
434488         être    pP      ɛtɑ̃     2
434762     éteindre   inf    ɛtɛ̃dʁ     1
434853    éterniser  ii3S  ɛtɛʁnizɛ     1
435054         être  ii2P      ɛtje     3
435172         être  ii1P     ɛtjɔ̃     2
435417      étonner  ai3S     ɛtɔna     1
435435      étonner  pi1S      ɛtɔn     1
435444      étonner   inf     ɛtɔne     1
435450      étonner  pc3S   ɛtɔnəʁɛ     1
435484     étouffer  ii3S     ɛtufɛ     1
435795    étreindre    pP   ɛtʁɛɲɑ̃     1
436205      étudier   inf    ɛtydje     1
436316         être  ppMS       ɛte    19
436632     évanouir   inf   ɛvanuiʁ     1
437292       éviter  pi1S      ɛvit     1
437301       éviter   inf     ɛvite     2
437414      évoquer  ii1S     ɛvɔkɛ     1
437416      évoquer  ii3S     ɛvɔkɛ     1
437431      évoquer   inf     ɛvɔke     1
437474         être  pi2P        ɛt    18
437476         être   inf       ɛtʁ    23

[1928 rows x 4 columns]

0
CPU times: user 1min 7s, sys: 14.3 s, total: 1min 21s
Wall time: 45.7 s

nbChunk 125
4200
1952

             lexeme  case      phono  tir1
40            avoir  pi3S          a    84
108      abandonner  ai3S   abɑ̃dɔna     1
113      abandonner  ii3S   abɑ̃dɔnɛ     1
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     1
258         abattre  ii3S      abatɛ     1
1175        aborder  ppMS     abɔʁde     1
1716        abriter  ppMS     abʁite     1
2335         abuser  pi3S       abyz     1
2947       accepter  ii3P    aksɛptɛ     1
2964       accepter  pi1S     aksɛpt     1
2971       accepter   inf    aksɛpte     2
3003       accepter  ppMS    aksɛpte     1
3379     accommoder  ppMP    akɔmɔde     1
3386    accompagner    pP  akɔ̃paɲɑ̃     1
3400    accompagner  pi3S    akɔ̃paɲ     2
3406    accompagner   inf   akɔ̃paɲe     1
3438      accomplir  ppMS    akɔ̃pli     1
3530       accorder  pi3S      akɔʁd     1
3805      accoucher  ai3S      akuʃa     1
3858      accoucher  ppMS      akuʃe     1
3916       accouder  ppMP      akude     1
4255      accrocher  pi3S      akʁɔʃ     1
4294      accrocher  ppMP     akʁɔʃe     1
4502     accueillir  ppMS      akəji     1
4509     accueillir   inf     akəjiʁ     2
4523     accueillir  is3S      akəji     1
4684      accumuler  ppFS    akymyle     1
4733        accuser  pi2S       akyz     1
...             ...   ...        ...   ...
430646   éparpiller  ppMP   ɛpaʁpije     1
431261       épiler  pi3S       ɛpil     1
431609     épingler  ppMS    ɛpɛ̃gle     1
432156      épouser  pi3S       ɛpuz     1
432160      épouser   inf      ɛpuze     2
432491     éprendre   inf    ɛpʁɑ̃dʁ     1
432533     éprouver  ai1S     ɛpʁuvɛ     1
432556     éprouver   inf     ɛpʁuve     1
433169      équiper  ppMS      ɛkipe     1
433916      établir  ppFP     ɛtabli     1
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ    20
434070         être  ii3S        ɛtɛ    87
434147       étaler  pi3S       ɛtal     1
434747     éteindre  ai3S      ɛtɛɲi     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434772     éteindre  ppMS       ɛtɛ̃     1
434777     éteindre  ppFP      ɛtɛ̃t     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435172         être  ii1P      ɛtjɔ̃     2
435422      étonner  ii3S      ɛtɔnɛ     1
436205      étudier   inf     ɛtydje     2
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    21
436681     évanouir  is3S     ɛvanui     1
436745     évaporer  ppMP    ɛvapɔʁe     2
437301       éviter   inf      ɛvite     3
437474         être  pi2P         ɛt     6
437476         être   inf        ɛtʁ    28
437512         ôter   inf        ɔte     1

[1952 rows x 4 columns]

0
CPU times: user 1min 9s, sys: 17 s, total: 1min 26s
Wall time: 33.4 s

nbChunk 126
4200
1939

             lexeme  case     phono  tir1
40            avoir  pi3S         a    86
128      abandonner  pi3S   abɑ̃dɔn     1
1132        aborder  ii3S    abɔʁdɛ     1
1722        abriter  ppMP    abʁite     1
1789        abroger  ppMP    abʁɔʒe     1
1950       absenter   inf   absɑ̃te     1
2114       absoudre  pc3S   absudʁɛ     1
2610         abîmer  ppMS     abime     1
2939       accepter  ai3S   aksɛpta     1
2968       accepter  ps3S    aksɛpt     1
2971       accepter   inf   aksɛpte     1
2984       accepter  pi2S    aksɛpt     2
3003       accepter  ppMS   aksɛpte     2
3385    accompagner  ii3S  akɔ̃paɲɛ     1
3489      accomplir  ai3S   akɔ̃pli     1
3508       accorder  ai3S    akɔʁda     1
3583       accorder  ppMP    akɔʁde     1
3655       accoster   inf    akɔste     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4280      accrocher  pi2P    akʁɔʃe     1
4291      accrocher  ppMS    akʁɔʃe     1
4720        accuser   inf     akyze     1
5112        acheter    pP    aʃətɑ̃     1
5119        acheter   inf     aʃəte     2
5136        acheter  ppMS     aʃəte     3
6443        adapter  ppMS    adapte     1
6882       admettre  pI1P   admɛtɔ̃     1
6969        admirer  ii3S    admiʁɛ     1
6991        admirer  pi3S     admiʁ     1
6994        admirer  pi3P     admiʁ     1
...             ...   ...       ...   ...
432161      épouser  fi3S   ɛpuzəʁa     1
432166      épouser  pc3S   ɛpuzəʁɛ     1
433912      établir  ppMS    ɛtabli     1
433946      établir  ii3S  ɛtablisɛ     1
433991       étager  ii3P     ɛtaʒɛ     1
434048         être  ii3P       ɛtɛ     6
434068         être  ii1S       ɛtɛ     8
434070         être  ii3S       ɛtɛ    64
435172         être  ii1P     ɛtjɔ̃     2
435410      étoiler  ppFS    ɛtwale     1
435418      étonner  ai1S     ɛtɔnɛ     1
435425      étonner    pP    ɛtɔnɑ̃     1
435435      étonner  pi1S      ɛtɔn     2
435438      étonner  pi3S      ɛtɔn     1
435471      étonner  ppMS     ɛtɔne     1
435504     étouffer  pi3P      ɛtuf     1
435506     étouffer   inf     ɛtufe     1
435839    étreindre  ppFS    ɛtʁɛ̃t     1
436205      étudier   inf    ɛtydje     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    19
436627     évanouir  ppMS    ɛvanui     1
436685     évaporer  ii3P   ɛvapɔʁɛ     1
436711     évaporer   inf   ɛvapɔʁe     1
436902      éventer  pi3P     ɛvɑ̃t     1
436997     éventrer   inf   ɛvɑ̃tʁe     1
437176      évincer   inf    ɛvɛ̃se     1
437474         être  pi2P        ɛt    20
437476         être   inf       ɛtʁ    19
437508         ôter  pi3S        ot     1

[1939 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.6 s, total: 1min 37s
Wall time: 32.6 s

nbChunk 127
4200
1908

             lexeme  case       phono  tir1
40            avoir  pi3S           a   101
134      abandonner  fi1S  abɑ̃dɔnəʁɛ     1
2042       absorber  ai3S     absɔʁba     1
2070       absorber   inf     absɔʁbe     1
2715       accabler  ii3S      akablɛ     2
2766       accabler  ppMP      akable     1
2939       accepter  ai3S     aksɛpta     1
2971       accepter   inf     aksɛpte     1
3003       accepter  ppMS     aksɛpte     2
3382    accompagner  ii3P    akɔ̃paɲɛ     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     2
3443      accomplir   inf    akɔ̃pliʁ     2
3516       accorder  ii3P      akɔʁdɛ     1
3913       accouder  ppMS       akude     1
4237      accrocher  ii3S      akʁɔʃɛ     1
4291      accrocher  ppMS      akʁɔʃe     1
4387      accroître  ppMS        akʁy     1
4625        acculer  ai3P      akylɛʁ     1
4693        accuser  ii3S       akyzɛ     1
4720        accuser   inf       akyze     1
4997       acharner  ii3S      aʃaʁnɛ     1
5005       acharner  pi1S       aʃaʁn     1
5102        acheter  ai3S       aʃəta     1
5119        acheter   inf       aʃəte     1
5125        acheter  pi2P       aʃəte     1
5136        acheter  ppMS       aʃəte     2
5149        achever  ii3S       aʃəvɛ     2
5316        acheter  fi1S     aʃɛtəʁɛ     1
...             ...   ...         ...   ...
424177       écrire   inf       ɛkʁiʁ     2
424183       écrire  pi1S        ɛkʁi     1
424188       écrire  pi3S        ɛkʁi     2
427296       élever  ii3S       ɛləvɛ     1
427641     éloigner   inf      ɛlwaɲe     2
429365     émouvoir  ppMS         ɛmy     1
429677      énerver  ii3S      ɛnɛʁvɛ     1
432156      épouser  pi3S        ɛpuz     1
432691      épuiser  ppFS      ɛpɥize     1
433170      équiper  ppFS       ɛkipe     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    13
434070         être  ii3S         ɛtɛ    71
434724     éteindre  ii1S       ɛtɛɲɛ     1
434773     éteindre  pi3S        ɛtɛ̃     1
434775     éteindre  ppFS       ɛtɛ̃t     1
434821      étendre   inf      ɛtɑ̃dʁ     1
435064    étinceler    pP   ɛtɛ̃səlɑ̃     1
435243       étirer  ii3S       ɛtiʁɛ     1
435244       étirer    pP      ɛtiʁɑ̃     1
435444      étonner   inf       ɛtɔne     1
435474      étonner  ppMP       ɛtɔne     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    15
436457       évader   inf       ɛvade     1
436867     éveiller  ppMS       ɛvɛje     2
437284       éviter  ii3S       ɛvitɛ     1
437301       éviter   inf       ɛvite     1
437474         être  pi2P          ɛt    10
437476         être   inf         ɛtʁ    24

[1908 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 21.9 s, total: 1min 39s
Wall time: 32.8 s

nbChunk 128
4200
1921

             lexeme  case      phono  tir1
40            avoir  pi3S          a    71
111      abandonner  ii1S   abɑ̃dɔnɛ     1
114      abandonner    pP  abɑ̃dɔnɑ̃     1
130      abandonner  pi3P    abɑ̃dɔn     1
145      abandonner  pi2S    abɑ̃dɔn     1
243         abattre  pi3S        aba     1
299         abattre   inf      abatʁ     1
305         abattre  ppMS      abaty     1
1307        abouler  pi3S       abul     1
1554       abreuver  ii3S     abʁəvɛ     1
2950       accepter  ii3S    aksɛptɛ     1
2971       accepter   inf    aksɛpte     2
2972       accepter  fi3S  aksɛptəʁa     1
2973       accepter  fi1S  aksɛptəʁɛ     1
2978       accepter  fi2S  aksɛptəʁa     1
3003       accepter  ppMS    aksɛpte     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3571       accorder  ppMS     akɔʁde     1
3573       accorder  ppFS     akɔʁde     1
4009       accourir  ii3S      akuʁɛ     1
4093       accourir  ppFP      akuʁy     1
4252      accrocher  pi1S      akʁɔʃ     1
4291      accrocher  ppMS     akʁɔʃe     1
4473     accueillir  ii3S      akəjɛ     1
4690        accuser  ii3P      akyzɛ     1
4693        accuser  ii3S      akyzɛ     1
4716        accuser  pi3S       akyz     1
5119        acheter   inf      aʃəte     3
5125        acheter  pi2P      aʃəte     1
...             ...   ...        ...   ...
432302      épouser  ppMS      ɛpuze     1
432556     éprouver   inf     ɛpʁuve     1
432691      épuiser  ppFS     ɛpɥize     1
433238   équivaloir  pi3S      ɛkivo     2
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    10
434070         être  ii3S        ɛtɛ    71
434131       étaler  ii3P      ɛtalɛ     1
434147       étaler  pi3S       ɛtal     1
434730     éteindre  pi3P       ɛtɛɲ     1
434734     éteindre  pi2P      ɛtɛɲe     2
434747     éteindre  ai3S      ɛtɛɲi     1
434772     éteindre  ppMS       ɛtɛ̃     1
434773     éteindre  pi3S       ɛtɛ̃     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     2
435438      étonner  pi3S       ɛtɔn     1
435500     étouffer  pi3S       ɛtuf     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
436188      étudier    pP    ɛtydjɑ̃     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    28
436402      évacuer   inf     ɛvakye     1
436430      évacuer  ppMS     ɛvakye     1
437301       éviter   inf      ɛvite     2
437360      évoluer  pi1S      ɛvɔly     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    16
437476         être   inf        ɛtʁ    24

[1921 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 21.8 s, total: 1min 39s
Wall time: 32.1 s

nbChunk 129
4200
1906

             lexeme  case        phono  tir1
40            avoir  pi3S            a    80
108      abandonner  ai3S     abɑ̃dɔna     2
299         abattre   inf        abatʁ     1
305         abattre  ppMS        abaty     1
313         abattre  ppMP        abaty     1
890          abolir   inf       abɔliʁ     2
1684        abriter  pi3S        abʁit     1
1716        abriter  ppMS       abʁite     2
2123       absoudre  ppMS         absu     1
2887      accentuer  ii3S     aksɑ̃tyɛ     1
2964       accepter  pi1S       aksɛpt     1
2967       accepter  pi3S       aksɛpt     1
3417    accompagner  fi1P  akɔ̃paɲəʁɔ̃     1
3573       accorder  ppFS       akɔʁde     1
4094       accourir  ai3P       akuʁyʁ     1
4259      accrocher   inf       akʁɔʃe     2
4293      accrocher  ppFP       akʁɔʃe     1
4509     accueillir   inf       akəjiʁ     1
4694        accuser    pP       akyzɑ̃     1
4748        accuser  ppMS        akyze     1
5041       acharner  ppMS       aʃaʁne     1
5119        acheter   inf        aʃəte     4
5125        acheter  pi2P        aʃəte     1
5136        acheter  ppMS        aʃəte     2
5137        acheter  ppFS        aʃəte     1
5149        achever  ii3S        aʃəvɛ     1
5311        acheter  pi3S         aʃɛt     1
5315        acheter  fi3S      aʃɛtəʁa     1
5792     acquiescer  ii3S       akjɛsɛ     1
5905       acquérir   inf       akɛʁiʁ     1
...             ...   ...          ...   ...
433914      établir  ppFS       ɛtabli     1
434048         être  ii3P          ɛtɛ     1
434068         être  ii1S          ɛtɛ    11
434069         être  ii2S          ɛtɛ     1
434070         être  ii3S          ɛtɛ    64
434739     éteindre  ai3P       ɛtɛɲiʁ     1
434762     éteindre   inf       ɛtɛ̃dʁ     1
434768     éteindre  pi1S         ɛtɛ̃     1
434782      étendre  pi3S         ɛtɑ̃     1
435054         être  ii2P         ɛtje     2
435240       étirer  ii3P        ɛtiʁɛ     1
435358      étoiler  ai3S       ɛtwala     1
435444      étonner   inf        ɛtɔne     1
435472      étonner  ppFS        ɛtɔne     1
435920     étriller   inf       ɛtʁije     1
436181      étudier  ai3S       ɛtydja     1
436205      étudier   inf       ɛtydje     1
436233      étudier  ppMS       ɛtydje     1
436316         être  ppMS          ɛte    21
436402      évacuer   inf       ɛvakye     1
436485       évader  ppFS        ɛvade     1
436490      évaluer  ai3S       ɛvalya     1
436629     évanouir  ppFS       ɛvanui     1
437295       éviter  pi3S         ɛvit     1
437367      évoluer   inf       ɛvɔlye     1
437411      évoquer  ai3S        ɛvɔka     1
437427      évoquer  pi3S         ɛvɔk     1
437431      évoquer   inf        ɛvɔke     1
437474         être  pi2P           ɛt    12
437476         être   inf          ɛtʁ    29

[1906 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22 s, total: 1min 40s
Wall time: 32.5 s

nbChunk 130
4200
1925

             lexeme  case      phono  tir1
40            avoir  pi3S          a    85
73         abaisser   inf      abɛse     1
125      abandonner  pi1S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
148      abandonner  pi2P   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
292         abattre  fi3S     abatʁa     1
1722        abriter  ppMP     abʁite     1
2102       absorber  ppFS    absɔʁbe     2
2128       absoudre  ppFS      absut     1
2371         abuser  ppMS      abyze     1
2969       accepter  pi3P     aksɛpt     1
2978       accepter  fi2S  aksɛptəʁa     1
2997       accepter  pi1P   aksɛptɔ̃     1
3406    accompagner   inf   akɔ̃paɲe     2
3434    accompagner  ppFS   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
3536       accorder   inf     akɔʁde     1
4103       accourir  ai3S      akuʁy     1
4291      accrocher  ppMS     akʁɔʃe     2
4294      accrocher  ppMP     akʁɔʃe     2
4471     accueillir  ii1S      akəjɛ     1
4509     accueillir   inf     akəjiʁ     2
4686      accumuler  ppMP    akymyle     1
5111        acheter  ii3S      aʃətɛ     2
5119        acheter   inf      aʃəte     1
5136        acheter  ppMS      aʃəte     4
5313        acheter  pi3P       aʃɛt     1
5807       acquérir  ppMS        aki     1
5905       acquérir   inf     akɛʁiʁ     1
...             ...   ...        ...   ...
432160      épouser   inf      ɛpuze     2
432556     éprouver   inf     ɛpʁuve     1
432691      épuiser  ppFS     ɛpɥize     1
432709       épurer  ii3S      ɛpyʁɛ     1
433618       ériger  ppFS      ɛʁiʒe     1
433912      établir  ppMS     ɛtabli     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    16
434070         être  ii3S        ɛtɛ    79
434762     éteindre   inf     ɛtɛ̃dʁ     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
435054         être  ii2P       ɛtje     3
435172         être  ii1P      ɛtjɔ̃     3
435360      étoiler  ii3P     ɛtwalɛ     1
435438      étonner  pi3S       ɛtɔn     1
435484     étouffer  ii3S      ɛtufɛ     1
435532     étouffer  pi1P     ɛtufɔ̃     1
435544     étouffer  ppMP      ɛtufe     1
435748    étrangler   inf   ɛtʁɑ̃gle     2
436201      étudier  pi3S      ɛtydi     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    17
436653     évanouir  ii3P   ɛvanuisɛ     1
436820     éveiller  ii3S      ɛvɛjɛ     1
437301       éviter   inf      ɛvite     2
437352      évoluer  ii3S     ɛvɔlyɛ     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    14
437476         être   inf        ɛtʁ    15

[1925 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.2 s, total: 1min 40s
Wall time: 33.3 s

nbChunk 131
4200
1975

             lexeme  case       phono  tir1
40            avoir  pi3S           a    81
114      abandonner    pP   abɑ̃dɔnɑ̃     1
132      abandonner   inf    abɑ̃dɔne     1
134      abandonner  fi1S  abɑ̃dɔnəʁɛ     1
164      abandonner  ppMS    abɑ̃dɔne     1
1147        aborder   inf      abɔʁde     1
1412        aboutir  ii3P     abutisɛ     1
1801        abrutir   inf     abʁytiʁ     1
1884        abréger   inf      abʁɛʒe     1
2971       accepter   inf     aksɛpte     3
3003       accepter  ppMS     aksɛpte     1
3319     accommoder  ii3P     akɔmɔdɛ     1
3406    accompagner   inf    akɔ̃paɲe     1
3443      accomplir   inf    akɔ̃pliʁ     1
3508       accorder  ai3S      akɔʁda     1
4010       accourir    pP      akuʁɑ̃     1
4238      accrocher    pP     akʁɔʃɑ̃     1
4292      accrocher  ppFS      akʁɔʃe     1
4368      accroupir  ai3S      akʁupi     1
4473     accueillir  ii3S       akəjɛ     1
4509     accueillir   inf      akəjiʁ     1
4783        accéder   inf      aksɛde     1
5030       acharner  pi2P      aʃaʁne     1
5112        acheter    pP      aʃətɑ̃     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     3
5308        acheter  pi1S        aʃɛt     1
5755     acquiescer  pi1S       akjɛs     1
5758     acquiescer  pi3S       akjɛs     1
5807       acquérir  ppMS         aki     1
...             ...   ...         ...   ...
432549     éprouver  pi1S       ɛpʁuv     1
432657      épuiser  pi3P       ɛpɥiz     1
432689      épuiser  ppMS      ɛpɥize     1
433169      équiper  ppMS       ɛkipe     1
433170      équiper  ppFS       ɛkipe     1
433914      établir  ppFS      ɛtabli     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    78
434770     éteindre  pi2S        ɛtɛ̃     1
435054         être  ii2P        ɛtje     1
435135      étioler   inf      ɛtjɔle     1
435172         être  ii1P       ɛtjɔ̃     3
435419      étonner  ii3P       ɛtɔnɛ     1
435444      étonner   inf       ɛtɔne     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435826    étreindre  pc3S    ɛtʁɛ̃dʁɛ     1
435972      étriper   inf      ɛtʁipe     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    26
436678     évanouir  ai3S      ɛvanui     1
437328       éviter  ppMS       ɛvite     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437427      évoquer  pi3S        ɛvɔk     1
437431      évoquer   inf       ɛvɔke     1
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    15
437498         ôter    pP        ɔtɑ̃     1
437512         ôter   inf         ɔte     1
437513         ôter  fi3S       ɔtəʁa     1

[1975 rows x 4 columns]

0
CPU times: user 1min 11s, sys: 22.4 s, total: 1min 34s
Wall time: 33.3 s

nbChunk 132
4200
1963

             lexeme  case      phono  tir1
40            avoir  pi3S          a    91
113      abandonner  ii3S   abɑ̃dɔnɛ     1
114      abandonner    pP  abɑ̃dɔnɑ̃     1
132      abandonner   inf   abɑ̃dɔne     2
164      abandonner  ppMS   abɑ̃dɔne     2
259         abattre    pP     abatɑ̃     1
305         abattre  ppMS      abaty     1
1121        aborder  ai3S     abɔʁda     1
1393        aboutir   inf     abutiʁ     1
1417        aboutir    pP   abutisɑ̃     1
1674        abriter    pP    abʁitɑ̃     2
2371         abuser  ppMS      abyze     1
2939       accepter  ai3S    aksɛpta     1
2977       accepter  pc3S  aksɛptəʁɛ     1
2989       accepter  pi2P    aksɛpte     1
2997       accepter  pi1P   aksɛptɔ̃     1
3383    accompagner  ii1S   akɔ̃paɲɛ     1
3406    accompagner   inf   akɔ̃paɲe     2
3436    accompagner  ppMP   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
3490      accomplir  pi3S    akɔ̃pli     1
3519       accorder  ii3S     akɔʁdɛ     1
3567       accorder  is3S     akɔʁda     1
3569       accorder  ai3P    akɔʁdɛʁ     1
3916       accouder  ppMP      akude     1
4292      accrocher  ppFS     akʁɔʃe     1
4294      accrocher  ppMP     akʁɔʃe     1
4736        accuser  pi2P      akyze     1
5014       acharner   inf     aʃaʁne     1
5119        acheter   inf      aʃəte     5
...             ...   ...        ...   ...
433062   équilibrer  ppMS   ɛkilibʁe     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ    14
434070         être  ii3S        ɛtɛ    56
434299       étaler  ppMS      ɛtale     1
434747     éteindre  ai3S      ɛtɛɲi     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434827      étendre  pi1S       ɛtɑ̃     1
434950     éternuer  ppMS    ɛtɛʁnye     1
435054         être  ii2P       ɛtje     4
435172         être  ii1P      ɛtjɔ̃     5
435438      étonner  pi3S       ɛtɔn     1
435444      étonner   inf      ɛtɔne     1
435472      étonner  ppFS      ɛtɔne     1
435475     étouffer  ai3S      ɛtufa     1
435481     étouffer  ii3P      ɛtufɛ     1
435538     étouffer  ppMS      ɛtufe     1
435732    étrangler    pP  ɛtʁɑ̃glɑ̃     1
436316         être  ppMS        ɛte    16
436820     éveiller  ii3S      ɛvɛjɛ     1
437272    éviscérer  ppMP    ɛvisɛʁe     1
437282       éviter  ii1S      ɛvitɛ     1
437301       éviter   inf      ɛvite     1
437458      évoquer  ppMS      ɛvɔke     1
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    17
437525         ôter  pi2S         ot     1
437539         ôter  ppMS        ɔte     1

[1963 rows x 4 columns]

0
CPU times: user 1min 19s, sys: 21.9 s, total: 1min 41s
Wall time: 31.6 s

nbChunk 133
4200
1934

             lexeme  case      phono  tir1
40            avoir  pi3S          a    90
108      abandonner  ai3S   abɑ̃dɔna     1
164      abandonner  ppMS   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
277         abattre  ai3P     abatiʁ     1
299         abattre   inf      abatʁ     1
953         abonder  ai3S     abɔ̃da     1
1175        aborder  ppMS     abɔʁde     1
1718        abriter  ppFS     abʁite     1
2952       accepter    pP   aksɛptɑ̃     1
2967       accepter  pi3S     aksɛpt     1
3003       accepter  ppMS    aksɛpte     1
3322     accommoder  ii3S    akɔmɔdɛ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     2
3508       accorder  ai3S     akɔʁda     1
4162     accoutumer  ii3P    akutymɛ     1
4210     accoutumer  ppMS    akutyme     1
4252      accrocher  pi1S      akʁɔʃ     1
4292      accrocher  ppFS     akʁɔʃe     1
4502     accueillir  ppMS      akəji     1
4656      accumuler   inf    akymyle     1
5102        acheter  ai3S      aʃəta     1
5136        acheter  ppMS      aʃəte     1
5145        achever  ai1S      aʃəvɛ     1
5329        achever  pi1S       aʃɛv     1
6390        adapter    pP    adaptɑ̃     1
6444        adapter  ppFS     adapte     1
7031       admettre  ppFS      admiz     1
7250        adopter   inf     adɔpte     1
...             ...   ...        ...   ...
427671     éloigner  ppMP     ɛlwaɲe     1
428400      émerger  ii3S     ɛmɛʁʒɛ     3
428605  émerveiller  ppMS   ɛmɛʁvɛje     1
429365     émouvoir  ppMS        ɛmy     1
429367     émouvoir  ppFS        ɛmy     1
429700      énerver   inf     ɛnɛʁve     1
430178     épaissir  ii3P    ɛpɛsisɛ     1
432160      épouser   inf      ɛpuze     2
432549     éprouver  pi1S      ɛpʁuv     1
432552     éprouver  pi3S      ɛpʁuv     1
433947      établir    pP  ɛtablisɑ̃     1
434048         être  ii3P        ɛtɛ     6
434068         être  ii1S        ɛtɛ    12
434070         être  ii3S        ɛtɛ    77
434762     éteindre   inf     ɛtɛ̃dʁ     2
434773     éteindre  pi3S       ɛtɛ̃     1
434785      étendre  ii3P     ɛtɑ̃dɛ     1
435054         être  ii2P       ɛtje     3
435172         être  ii1P      ɛtjɔ̃     2
435481     étouffer  ii3P      ɛtufɛ     1
435538     étouffer  ppMS      ɛtufe     1
436198      étudier  pi1S      ɛtydi     1
436316         être  ppMS        ɛte    25
436485       évader  ppFS      ɛvade     1
436831     éveiller  pi3S       ɛvɛj     1
437049     évertuer  ii3S    ɛvɛʁtyɛ     1
437281       éviter  ii3P      ɛvitɛ     1
437301       éviter   inf      ɛvite     1
437474         être  pi2P         ɛt    14
437476         être   inf        ɛtʁ    19

[1934 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.2 s, total: 1min 38s
Wall time: 30.4 s

nbChunk 134
4200
1959

              lexeme  case      phono  tir1
40             avoir  pi3S          a    84
108       abandonner  ai3S   abɑ̃dɔna     1
114       abandonner    pP  abɑ̃dɔnɑ̃     1
299          abattre   inf      abatʁ     1
305          abattre  ppMS      abaty     1
616         abhorrer  ppMS      abɔʁe     1
890           abolir   inf     abɔliʁ     1
1121         aborder  ai3S     abɔʁda     1
1673         abriter  ii3S     abʁitɛ     1
2319          abuser  ai3S      abyza     1
2339          abuser   inf      abyze     1
2614          abîmer  ppFP      abime     1
2785       accaparer  pi3S     akapaʁ     1
2934       accentuer  ppFS   aksɑ̃tye     1
3003        accepter  ppMS    aksɛpte     1
3433     accompagner  ppMS   akɔ̃paɲe     2
3471       accomplir  ps3S   akɔ̃plis     1
3536        accorder   inf     akɔʁde     1
3556        accorder  pi2P     akɔʁde     1
3827       accoucher   inf      akuʃe     1
4631         acculer  ppMP      akyle     1
4685       accumuler  ppFP    akymyle     1
4716         accuser  pi3S       akyz     1
4748         accuser  ppMS      akyze     1
4864       accélérer  ppFS   aksɛlɛʁe     1
5012        acharner  pi3P      aʃaʁn     1
5111         acheter  ii3S      aʃətɛ     1
5119         acheter   inf      aʃəte     1
5157         achever   inf      aʃəve     1
5313         acheter  pi3P       aʃɛt     1
...              ...   ...        ...   ...
432294  époustoufler  ppMS  ɛpustufle     1
432532      éprouver  ai3S     ɛpʁuva     1
432556      éprouver   inf     ɛpʁuve     1
434048          être  ii3P        ɛtɛ     5
434068          être  ii1S        ɛtɛ    16
434070          être  ii3S        ɛtɛ    67
434134        étaler  ii3S      ɛtalɛ     1
434302        étaler  ppMP      ɛtale     1
434727      éteindre    pP     ɛtɛɲɑ̃     1
434768      éteindre  pi1S       ɛtɛ̃     1
434770      éteindre  pi2S       ɛtɛ̃     1
434773      éteindre  pi3S       ɛtɛ̃     1
435054          être  ii2P       ɛtje     1
435172          être  ii1P      ɛtjɔ̃     2
435484      étouffer  ii3S      ɛtufɛ     1
435506      étouffer   inf      ɛtufe     1
435732     étrangler    pP  ɛtʁɑ̃glɑ̃     1
435768     étrangler  pi2P   ɛtʁɑ̃gle     1
436239       étudier  ppMP     ɛtydje     1
436316          être  ppMS        ɛte    16
436547       évaluer  ppMS     ɛvalye     1
436709      évaporer  pi3P     ɛvapɔʁ     1
436745      évaporer  ppMP    ɛvapɔʁe     1
436820      éveiller  ii3S      ɛvɛjɛ     1
437301        éviter   inf      ɛvite     1
437414       évoquer  ii1S      ɛvɔkɛ     1
437417       évoquer    pP     ɛvɔkɑ̃     1
437474          être  pi2P         ɛt    13
437476          être   inf        ɛtʁ    15
437512          ôter   inf        ɔte     1

[1959 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 21.9 s, total: 1min 38s
Wall time: 30.2 s

nbChunk 135
4200
1952

             lexeme  case      phono  tir1
40            avoir  pi3S          a    83
114      abandonner    pP  abɑ̃dɔnɑ̃     1
130      abandonner  pi3P    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     2
164      abandonner  ppMS   abɑ̃dɔne     1
264         abattre  pi3P       abat     1
299         abattre   inf      abatʁ     1
865          aboyer  pi3S       abwa     1
1132        aborder  ii3S     abɔʁdɛ     1
1946       absenter  pi3S     absɑ̃t     1
2341         abuser  fi1S    abyzəʁɛ     1
2581         abîmer   inf      abime     1
2610         abîmer  ppMS      abime     1
2736       accabler   inf     akable     1
2950       accepter  ii3S    aksɛptɛ     1
2969       accepter  pi3P     aksɛpt     2
3005       accepter  ppFS    aksɛpte     1
3380    accompagner  ai3S   akɔ̃paɲa     1
3382    accompagner  ii3P   akɔ̃paɲɛ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3470      accomplir  ps1S   akɔ̃plis     1
3471      accomplir  ps3S   akɔ̃plis     1
3527       accorder  pi1S      akɔʁd     1
3536       accorder   inf     akɔʁde     1
3549       accorder  pi2S      akɔʁd     1
3827      accoucher   inf      akuʃe     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4238      accrocher    pP    akʁɔʃɑ̃     1
4259      accrocher   inf     akʁɔʃe     1
...             ...   ...        ...   ...
430591     épargner  ppFS     ɛpaʁɲe     1
430786      épauler  ii3S      ɛpɔlɛ     1
430806      épauler   inf      ɛpɔle     1
430946    éperonner   inf    ɛpəʁɔne     1
432160      épouser   inf      ɛpuze     1
432533     éprouver  ai1S     ɛpʁuvɛ     1
432549     éprouver  pi1S      ɛpʁuv     1
432691      épuiser  ppFS     ɛpɥize     1
433677       éroder  ppFS      ɛʁɔde     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ    11
434070         être  ii3S        ɛtɛ    78
434488         être    pP       ɛtɑ̃     2
434762     éteindre   inf     ɛtɛ̃dʁ     1
434821      étendre   inf     ɛtɑ̃dʁ     2
434833      étendre  ppFS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     6
435425      étonner    pP     ɛtɔnɑ̃     1
435438      étonner  pi3S       ɛtɔn     2
435457      étonner  pi2S       ɛtɔn     1
436186      étudier  ii3S     ɛtydjɛ     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    26
437049     évertuer  ii3S    ɛvɛʁtyɛ     1
437301       éviter   inf      ɛvite     1
437474         être  pi2P         ɛt    17
437476         être   inf        ɛtʁ    17
437505         ôter  pi1S         ot     1

[1952 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.3 s, total: 1min 39s
Wall time: 30 s

nbChunk 136
4200
1964

             lexeme  case        phono  tir1
40            avoir  pi3S            a    96
132      abandonner   inf     abɑ̃dɔne     2
143      abandonner  fi1P  abɑ̃dɔnəʁɔ̃     1
164      abandonner  ppMS     abɑ̃dɔne     1
313         abattre  ppMP        abaty     1
887          abolir  ppMS        abɔli     1
2143       abstenir   inf     abstəniʁ     1
2332         abuser  pi1S         abyz     1
2335         abuser  pi3S         abyz     1
2581         abîmer   inf        abime     1
2710       accabler  ai3S       akabla     1
2734       accabler  pi3P        akabl     1
2971       accepter   inf      aksɛpte     1
2984       accepter  pi2S       aksɛpt     1
3003       accepter  ppMS      aksɛpte     1
3314        accoler  ppFS        akɔle     1
3385    accompagner  ii3S     akɔ̃paɲɛ     1
3406    accompagner   inf     akɔ̃paɲe     1
3443      accomplir   inf     akɔ̃pliʁ     1
3527       accorder  pi1S        akɔʁd     1
3530       accorder  pi3S        akɔʁd     2
3571       accorder  ppMS       akɔʁde     1
3575       accorder  ppFP       akɔʁde     1
4094       accourir  ai3P       akuʁyʁ     1
4230      accrocher  ai3S       akʁɔʃa     2
4280      accrocher  pi2P       akʁɔʃe     1
4292      accrocher  ppFS       akʁɔʃe     2
4484     accueillir  pi3P         akœj     1
4736        accuser  pi2P        akyze     1
4754        accuser  ppMP        akyze     1
...             ...   ...          ...   ...
432160      épouser   inf        ɛpuze     2
432181      épouser  pi2P        ɛpuze     1
432537     éprouver  ii3S       ɛpʁuvɛ     1
432691      épuiser  ppFS       ɛpɥize     1
433111      équiper  pi3P         ɛkip     1
433922      établir   inf      ɛtabliʁ     1
434048         être  ii3P          ɛtɛ     3
434068         être  ii1S          ɛtɛ    13
434069         être  ii2S          ɛtɛ     1
434070         être  ii3S          ɛtɛ    61
434131       étaler  ii3P        ɛtalɛ     1
434730     éteindre  pi3P         ɛtɛɲ     2
434821      étendre   inf       ɛtɑ̃dʁ     1
434866    éterniser  pi3P      ɛtɛʁniz     1
435172         être  ii1P        ɛtjɔ̃     2
435254       étirer  pi3S         ɛtiʁ     1
435435      étonner  pi1S         ɛtɔn     1
435444      étonner   inf        ɛtɔne     1
436181      étudier  ai3S       ɛtydja     1
436201      étudier  pi3S        ɛtydi     1
436205      étudier   inf       ɛtydje     2
436233      étudier  ppMS       ɛtydje     1
436316         être  ppMS          ɛte    27
436402      évacuer   inf       ɛvakye     1
436520      évaluer   inf       ɛvalye     1
437223    éviscérer  pi3S       ɛvisɛʁ     1
437301       éviter   inf        ɛvite     1
437474         être  pi2P           ɛt    12
437476         être   inf          ɛtʁ    24
437495         ôter  ii1S          ɔtɛ     1

[1964 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.3 s, total: 1min 38s
Wall time: 30.5 s

nbChunk 137
4200
1945

             lexeme  case      phono  tir1
40            avoir  pi3S          a    75
164      abandonner  ppMS   abɑ̃dɔne     1
292         abattre  fi3S     abatʁa     1
888          abolir  ppFS      abɔli     1
1798        abrutir  ppFS     abʁyti     1
1979       absenter  ppMS    absɑ̃te     1
2352         abuser  pi2S       abyz     1
2506         abêtir   inf     abɛtiʁ     1
2710       accabler  ai3S     akabla     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     4
3003       accepter  ppMS    aksɛpte     2
3380    accompagner  ai3S   akɔ̃paɲa     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3435    accompagner  ppFP   akɔ̃paɲe     1
3556       accorder  pi2P     akɔʁde     1
4255      accrocher  pi3S      akʁɔʃ     1
4721        accuser  fi3S    akyzəʁa     1
4783        accéder   inf     aksɛde     1
4812      accélérer  pi3S    aksɛlɛʁ     1
5119        acheter   inf      aʃəte     2
5136        acheter  ppMS      aʃəte     2
5308        acheter  pi1S       aʃɛt     1
5323        acheter  pc2P   aʃɛtəʁje     1
5332        achever  pi3S       aʃɛv     1
6414        adapter   inf     adapte     1
6875       admettre  ps2S      admɛt     1
6884       admettre  fi3S    admɛtʁa     1
6996        admirer   inf     admiʁe     1
7012        admirer  pi2P     admiʁe     1
...             ...   ...        ...   ...
432556     éprouver   inf     ɛpʁuve     1
432689      épuiser  ppMS     ɛpɥize     1
433026   équilibrer   inf   ɛkilibʁe     1
433912      établir  ppMS     ɛtabli     1
434004       étager  pi3P       ɛtaʒ     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    24
434070         être  ii3S        ɛtɛ    86
434134       étaler  ii3S      ɛtalɛ     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434770     éteindre  pi2S       ɛtɛ̃     1
434811      étendre  ai3S     ɛtɑ̃di     1
435054         être  ii2P       ɛtje     2
435064    étinceler    pP  ɛtɛ̃səlɑ̃     1
435172         être  ii1P      ɛtjɔ̃     2
435438      étonner  pi3S       ɛtɔn     2
435444      étonner   inf      ɛtɔne     1
435457      étonner  pi2S       ɛtɔn     1
435499     étouffer  pI2S       ɛtuf     1
435506     étouffer   inf      ɛtufe     1
435540     étouffer  ppFS      ɛtufe     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    20
436457       évader   inf      ɛvade     1
436835     éveiller   inf      ɛvɛje     1
437328       éviter  ppMS      ɛvite     1
437416      évoquer  ii3S      ɛvɔkɛ     2
437474         être  pi2P         ɛt    18
437476         être   inf        ɛtʁ    18
437512         ôter   inf        ɔte     1

[1945 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22 s, total: 1min 38s
Wall time: 29.6 s

nbChunk 138
4200
1929

             lexeme  case      phono  tir1
40            avoir  pi3S          a    92
113      abandonner  ii3S   abɑ̃dɔnɛ     1
128      abandonner  pi3S    abɑ̃dɔn     1
130      abandonner  pi3P    abɑ̃dɔn     1
299         abattre   inf      abatʁ     1
305         abattre  ppMS      abaty     1
1979       absenter  ppMS    absɑ̃te     1
2100       absorber  ppMS    absɔʁbe     1
2102       absorber  ppFS    absɔʁbe     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     3
2984       accepter  pi2S     aksɛpt     1
3003       accepter  ppMS    aksɛpte     3
3382    accompagner  ii3P   akɔ̃paɲɛ     1
3406    accompagner   inf   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
3480      accomplir  pi2P  akɔ̃plise     1
3536       accorder   inf     akɔʁde     1
3862       accouder  ai3S      akuda     1
4473     accueillir  ii3S      akəjɛ     1
4631        acculer  ppMP      akyle     1
4783        accéder   inf     aksɛde     2
4811      accélérer  pI2S    aksɛlɛʁ     1
4814      accélérer  pi3P    aksɛlɛʁ     1
5044       acharner  ppMP     aʃaʁne     1
5119        acheter   inf      aʃəte     1
5136        acheter  ppMS      aʃəte     3
5140        achever  ai3S      aʃəva     1
5157        achever   inf      aʃəve     1
5311        acheter  pi3S       aʃɛt     1
...             ...   ...        ...   ...
430694       épater  pc3S    ɛpatəʁɛ     1
432160      épouser   inf      ɛpuze     2
432554     éprouver  pi3P      ɛpʁuv     1
433571       ériger  pi3S       ɛʁiʒ     1
433912      établir  ppMS     ɛtabli     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    16
434069         être  ii2S        ɛtɛ     2
434070         être  ii3S        ɛtɛ    80
434153       étaler   inf      ɛtale     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434773     éteindre  pi3S       ɛtɛ̃     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434811      étendre  ai3S     ɛtɑ̃di     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     5
435172         être  ii1P      ɛtjɔ̃     2
435239       étirer  ai1S      ɛtiʁɛ     1
435444      étonner   inf      ɛtɔne     1
435732    étrangler    pP  ɛtʁɑ̃glɑ̃     1
435780    étrangler  ppMS   ɛtʁɑ̃gle     1
436186      étudier  ii3S     ɛtydjɛ     1
436205      étudier   inf     ɛtydje     1
436206      étudier  fi3S    ɛtydiʁa     1
436316         être  ppMS        ɛte    28
437328       éviter  ppMS      ɛvite     1
437365      évoluer  pi3P      ɛvɔly     1
437474         être  pi2P         ɛt    11
437476         être   inf        ɛtʁ    11
437508         ôter  pi3S         ot     1

[1929 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.5 s, total: 1min 36s
Wall time: 29.6 s

nbChunk 139
4200
1926

             lexeme  case       phono  tir1
40            avoir  pi3S           a    70
45         abaisser  ai3S       abɛsa     1
164      abandonner  ppMS    abɑ̃dɔne     1
197      abasourdir  ppMP    abazuʁdi     1
890          abolir   inf      abɔliʁ     1
1485         aboyer  ppMS      abwaje     1
1688        abriter   inf      abʁite     1
2070       absorber   inf     absɔʁbe     2
2133       abstenir  ii1S     abstənɛ     1
3343     accommoder  pi3S      akɔmɔd     1
3379     accommoder  ppMP     akɔmɔde     1
3382    accompagner  ii3P    akɔ̃paɲɛ     1
3421    accompagner  pI2P    akɔ̃paɲe     1
3443      accomplir   inf    akɔ̃pliʁ     1
3682       accoster  ppMS      akɔste     1
3913       accouder  ppMS       akude     1
4502     accueillir  ppMS       akəji     1
4716        accuser  pi3S        akyz     1
4748        accuser  ppMS       akyze     1
5119        acheter   inf       aʃəte     3
5131        acheter  pi1P      aʃətɔ̃     1
5171        achever  ppMS       aʃəve     1
5175        achever  ppFP       aʃəve     1
5308        acheter  pi1S        aʃɛt     1
5311        acheter  pi3S        aʃɛt     1
5807       acquérir  ppMS         aki     1
6414        adapter   inf      adapte     1
6891       admettre   inf      admɛtʁ     2
6928    administrer   inf  administʁe     2
6996        admirer   inf      admiʁe     1
...             ...   ...         ...   ...
428176       émaner  ii3S       ɛmanɛ     1
428897      émonder   inf      ɛmɔ̃de     1
430562     épargner   inf      ɛpaʁɲe     1
432160      épouser   inf       ɛpuze     2
432552     éprouver  pi3S       ɛpʁuv     1
432577     éprouver  ii1P    ɛpʁuvjɔ̃     1
432586     éprouver  ppMS      ɛpʁuve     1
433091      équiper  ii3S       ɛkipɛ     1
433272    éradiquer   inf     ɛʁadike     1
433617       ériger  ppMS       ɛʁiʒe     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ    15
434070         être  ii3S         ɛtɛ    87
434488         être    pP        ɛtɑ̃     2
434831      étendre  ppMS      ɛtɑ̃dy     3
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     2
435296       étirer  ppMP       ɛtiʁe     1
435438      étonner  pi3S        ɛtɔn     1
435500     étouffer  pi3S        ɛtuf     1
435746    étrangler  pi3P     ɛtʁɑ̃gl     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436316         être  ppMS         ɛte    24
436632     évanouir   inf     ɛvanuiʁ     1
437273       éviter  ai3S       ɛvita     1
437301       éviter   inf       ɛvite     1
437474         être  pi2P          ɛt    16
437476         être   inf         ɛtʁ    26
437492         ôter  ai3S         ɔta     1

[1926 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.6 s, total: 1min 36s
Wall time: 29.5 s

nbChunk 140
4200
1924

             lexeme  case     phono  tir1
40            avoir  pi3S         a    74
307         abattre  ppFS     abaty     1
1801        abrutir   inf   abʁytiʁ     1
2950       accepter  ii3S   aksɛptɛ     1
2971       accepter   inf   aksɛpte     2
3313        accoler  ppMS     akɔle     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3419    accompagner  pi2S   akɔ̃paɲ     1
3443      accomplir   inf  akɔ̃pliʁ     1
4292      accrocher  ppFS    akʁɔʃe     1
4473     accueillir  ii3S     akəjɛ     1
4502     accueillir  ppMS     akəji     1
4509     accueillir   inf    akəjiʁ     1
4547        acculer   inf     akyle     1
4783        accéder   inf    aksɛde     1
5119        acheter   inf     aʃəte     3
5136        acheter  ppMS     aʃəte     4
5157        achever   inf     aʃəve     1
5171        achever  ppMS     aʃəve     1
5311        acheter  pi3S      aʃɛt     1
5812       acquérir  ppFS      akiz     1
5905       acquérir   inf    akɛʁiʁ     1
6473    additionner  pi3P   adisjɔn     1
6539        adhérer  ii3S     adɛʁɛ     1
6889       admettre  pc3S   admɛtʁɛ     1
6891       admettre   inf    admɛtʁ     1
6991        admirer  pi3S     admiʁ     1
7309         adorer  pi1S      adɔʁ     1
7312         adorer  pi3S      adɔʁ     1
7518       adresser  ai3S    adʁɛsa     1
...             ...   ...       ...   ...
429700      énerver   inf    ɛnɛʁve     1
430665       épater  ii3S     ɛpatɛ     1
432144      épouser  ii3S     ɛpuzɛ     2
432160      épouser   inf     ɛpuze     1
432374   épouvanter  ii3S  ɛpuvɑ̃tɛ     1
432537     éprouver  ii3S    ɛpʁuvɛ     1
432556     éprouver   inf    ɛpʁuve     1
432564     éprouver  fi2P  ɛpʁuvəʁe     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ    10
434070         être  ii3S       ɛtɛ    65
434131       étaler  ii3P     ɛtalɛ     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
434788      étendre  ii3S    ɛtɑ̃dɛ     1
434798      étendre  pi2P    ɛtɑ̃de     1
434811      étendre  ai3S    ɛtɑ̃di     1
435172         être  ii1P     ɛtjɔ̃     1
435438      étonner  pi3S      ɛtɔn     1
435472      étonner  ppFS     ɛtɔne     1
436003     étriquer  ai3S    ɛtʁika     1
436205      étudier   inf    ɛtydje     1
436316         être  ppMS       ɛte    26
436520      évaluer   inf    ɛvalye     1
436709     évaporer  pi3P    ɛvapɔʁ     1
437295       éviter  pi3S      ɛvit     1
437301       éviter   inf     ɛvite     1
437328       éviter  ppMS     ɛvite     1
437427      évoquer  pi3S      ɛvɔk     1
437474         être  pi2P        ɛt     8
437476         être   inf       ɛtʁ    19

[1924 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 21.9 s, total: 1min 38s
Wall time: 29.9 s

nbChunk 141
4200
1937

             lexeme  case     phono  tir1
40            avoir  pi3S         a    73
50         abaisser  ii3S     abɛsɛ     1
130      abandonner  pi3P   abɑ̃dɔn     1
145      abandonner  pi2S   abɑ̃dɔn     1
272         abattre  pi2P     abate     1
1163        aborder  pi2P    abɔʁde     1
1688        abriter   inf    abʁite     2
2100       absorber  ppMS   absɔʁbe     1
2143       abstenir   inf  abstəniʁ     1
2566         abîmer    pP    abimɑ̃     1
2887      accentuer  ii3S  aksɑ̃tyɛ     1
2971       accepter   inf   aksɛpte     1
3313        accoler  ppMS     akɔle     1
3406    accompagner   inf  akɔ̃paɲe     1
3434    accompagner  ppFS  akɔ̃paɲe     1
3443      accomplir   inf  akɔ̃pliʁ     1
3575       accorder  ppFP    akɔʁde     1
4254      accrocher  pI2S     akʁɔʃ     1
4291      accrocher  ppMS    akʁɔʃe     1
4473     accueillir  ii3S     akəjɛ     1
4482     accueillir  pi3S      akœj     1
4509     accueillir   inf    akəjiʁ     1
4724        accuser  pc1S   akyzəʁɛ     1
4748        accuser  ppMS     akyze     2
4812      accélérer  pi3S   aksɛlɛʁ     1
5070      acheminer   inf   aʃəmine     1
5119        acheter   inf     aʃəte     3
5136        acheter  ppMS     aʃəte     1
5140        achever  ai3S     aʃəva     1
6801        adjuger  ppMS    adʒyʒe     1
...             ...   ...       ...   ...
432537     éprouver  ii3S    ɛpʁuvɛ     1
432539     éprouver    pP   ɛpʁuvɑ̃     1
432554     éprouver  pi3P     ɛpʁuv     1
432586     éprouver  ppMS    ɛpʁuve     1
433950      établir  ps3S   ɛtablis     1
433969      établir  pi3S    ɛtabli     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ    13
434069         être  ii2S       ɛtɛ     1
434070         être  ii3S       ɛtɛ    72
434821      étendre   inf    ɛtɑ̃dʁ     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     1
435425      étonner    pP    ɛtɔnɑ̃     1
435459      étonner  pI2P     ɛtɔne     1
435484     étouffer  ii3S     ɛtufɛ     1
435538     étouffer  ppMS     ɛtufe     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    19
436533      évaluer  pi2S     ɛvaly     1
436629     évanouir  ppFS    ɛvanui     1
436631     évanouir  ppFP    ɛvanui     1
436835     éveiller   inf     ɛvɛje     2
437282       éviter  ii1S     ɛvitɛ     1
437301       éviter   inf     ɛvite     1
437328       éviter  ppMS     ɛvite     1
437407      évoluer  ppMS    ɛvɔlye     1
437474         être  pi2P        ɛt    19
437476         être   inf       ɛtʁ    23
437512         ôter   inf       ɔte     1

[1937 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22 s, total: 1min 38s
Wall time: 30 s

nbChunk 142
4200
1935

             lexeme  case      phono  tir1
40            avoir  pi3S          a    79
243         abattre  pi3S        aba     1
1129        aborder  ii3P     abɔʁdɛ     1
1415        aboutir  ii3S    abutisɛ     1
1673        abriter  ii3S     abʁitɛ     1
2102       absorber  ppFS    absɔʁbe     1
2324         abuser  ii3S      abyzɛ     1
2946       accepter  ai1S    aksɛptɛ     1
2971       accepter   inf    aksɛpte     1
3380    accompagner  ai3S   akɔ̃paɲa     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     2
3480      accomplir  pi2P  akɔ̃plise     1
3490      accomplir  pi3S    akɔ̃pli     1
3827      accoucher   inf      akuʃe     1
4091       accourir  ppMS      akuʁy     1
4257      accrocher  pi3P      akʁɔʃ     1
4509     accueillir   inf     akəjiʁ     1
4733        accuser  pi2S       akyz     1
4748        accuser  ppMS      akyze     1
4862      accélérer  ppMS   aksɛlɛʁe     1
5119        acheter   inf      aʃəte     3
5136        acheter  ppMS      aʃəte     4
5146        achever  ii3P      aʃəvɛ     1
5157        achever   inf      aʃəve     1
5311        acheter  pi3S       aʃɛt     1
5807       acquérir  ppMS        aki     1
5905       acquérir   inf     akɛʁiʁ     1
6072        activer   inf     aktive     1
6967        admirer  ii1S     admiʁɛ     1
...             ...   ...        ...   ...
430973    éperonner  ppMS    ɛpəʁɔne     1
431611     épingler  ppFS    ɛpɛ̃gle     1
432156      épouser  pi3S       ɛpuz     1
432160      épouser   inf      ɛpuze     1
432303      épouser  ppFS      ɛpuze     1
432653      épuiser  pi3S      ɛpɥiz     1
432689      épuiser  ppMS     ɛpɥize     1
434021       étager  pi2S       ɛtaʒ     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ     6
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    77
434762     éteindre   inf     ɛtɛ̃dʁ     1
434813      étendre  pi1P    ɛtɑ̃dɔ̃     1
434827      étendre  pi1S       ɛtɑ̃     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     3
435172         être  ii1P      ɛtjɔ̃     1
435654     étourdir  ppMS     ɛtuʁdi     1
435795    étreindre    pP    ɛtʁɛɲɑ̃     1
436316         être  ppMS        ɛte    25
436430      évacuer  ppMS     ɛvakye     1
436815     éveiller  ai3S      ɛvɛja     1
436869     éveiller  ppFS      ɛvɛje     1
437301       éviter   inf      ɛvite     2
437328       éviter  ppMS      ɛvite     1
437417      évoquer    pP     ɛvɔkɑ̃     1
437431      évoquer   inf      ɛvɔke     2
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    27

[1935 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.6 s, total: 1min 36s
Wall time: 29.5 s

nbChunk 143
4200
1919

             lexeme  case       phono  tir1
40            avoir  pi3S           a    85
114      abandonner    pP   abɑ̃dɔnɑ̃     1
1130        aborder  ii1S      abɔʁdɛ     1
2070       absorber   inf     absɔʁbe     2
2285      abstraire  ppMP      abstʁɛ     1
2339         abuser   inf       abyze     1
2971       accepter   inf     aksɛpte     1
3003       accepter  ppMS     aksɛpte     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3419    accompagner  pi2S     akɔ̃paɲ     1
3443      accomplir   inf    akɔ̃pliʁ     1
3827      accoucher   inf       akuʃe     1
4093       accourir  ppFP       akuʁy     1
4255      accrocher  pi3S       akʁɔʃ     2
4482     accueillir  pi3S        akœj     1
4519     accueillir  ai3S       akəji     1
4713        accuser  pi1S        akyz     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     3
5332        achever  pi3S        aʃɛv     1
5843      acquitter  pi1S        akit     1
5879      acquitter  ppMS       akite     1
6268         acérer  ppMS       asɛʁe     1
6410        adapter  pi3S       adapt     1
6733      adjoindre  pi3S      adʒwɛ̃     1
6928    administrer   inf  administʁe     1
6959        admirer  ai3S      admiʁa     1
6996        admirer   inf      admiʁe     1
7250        adopter   inf      adɔpte     1
7320         adorer  pc1S     adɔʁəʁɛ     1
...             ...   ...         ...   ...
427923       élever  pi3S        ɛlɛv     1
428640      émettre   inf       ɛmɛtʁ     1
429700      énerver   inf      ɛnɛʁve     1
432138      épouser  ai3S       ɛpuza     1
432158      épouser  pi3P        ɛpuz     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
433169      équiper  ppMS       ɛkipe     1
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ    13
434070         être  ii3S         ɛtɛ    79
434770     éteindre  pi2S        ɛtɛ̃     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434819      étendre  pc3S     ɛtɑ̃dʁɛ     1
434836      étendre  ppFP      ɛtɑ̃dy     1
435172         être  ii1P       ɛtjɔ̃     2
435254       étirer  pi3S        ɛtiʁ     1
435417      étonner  ai3S       ɛtɔna     1
436057     étriquer  ppMP      ɛtʁike     1
436201      étudier  pi3S       ɛtydi     1
436205      étudier   inf      ɛtydje     2
436316         être  ppMS         ɛte    23
436627     évanouir  ppMS      ɛvanui     1
437285       éviter    pP      ɛvitɑ̃     1
437301       éviter   inf       ɛvite     3
437323       éviter  pi1P      ɛvitɔ̃     1
437365      évoluer  pi3P       ɛvɔly     1
437431      évoquer   inf       ɛvɔke     2
437474         être  pi2P          ɛt    25
437476         être   inf         ɛtʁ    16
437512         ôter   inf         ɔte     1

[1919 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.5 s, total: 1min 41s
Wall time: 30.5 s

nbChunk 144
4200
1980

             lexeme  case      phono  tir1
40            avoir  pi3S          a    94
132      abandonner   inf   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
255         abattre  ii3P      abatɛ     1
264         abattre  pi3P       abat     1
299         abattre   inf      abatʁ     1
305         abattre  ppMS      abaty     2
1818        abrutir  pi1S     abʁyti     1
2371         abuser  ppMS      abyze     1
2616         abîmer  ppMP      abime     1
2900      accentuer  pi3S    aksɑ̃ty     1
2971       accepter   inf    aksɛpte     1
2974       accepter  pc3P  aksɛptəʁɛ     1
3005       accepter  ppFS    aksɛpte     1
3386    accompagner    pP  akɔ̃paɲɑ̃     1
3406    accompagner   inf   akɔ̃paɲe     1
3536       accorder   inf     akɔʁde     1
4291      accrocher  ppMS     akʁɔʃe     2
4387      accroître  ppMS       akʁy     1
4503     accueillir  ppFS      akəji     1
4509     accueillir   inf     akəjiʁ     1
4720        accuser   inf      akyze     1
4748        accuser  ppMS      akyze     2
4787        accéder  pc1S   aksɛdəʁɛ     1
5119        acheter   inf      aʃəte     2
5136        acheter  ppMS      aʃəte     3
5311        acheter  pi3S       aʃɛt     1
5313        acheter  pi3P       aʃɛt     1
5315        acheter  fi3S    aʃɛtəʁa     1
6089        activer  pi2P     aktive     1
...             ...   ...        ...   ...
432160      épouser   inf      ɛpuze     1
432523     éprendre  ppFS      ɛpʁiz     1
432533     éprouver  ai1S     ɛpʁuvɛ     1
433912      établir  ppMS     ɛtabli     1
433914      établir  ppFS     ɛtabli     1
433922      établir   inf    ɛtabliʁ     1
433947      établir    pP  ɛtablisɑ̃     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    12
434070         être  ii3S        ɛtɛ    62
434153       étaler   inf      ɛtale     1
434300       étaler  ppFS      ɛtale     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     3
435244       étirer    pP     ɛtiʁɑ̃     1
435293       étirer  ppMS      ɛtiʁe     1
435435      étonner  pi1S       ɛtɔn     1
435438      étonner  pi3S       ɛtɔn     1
435486     étouffer    pP     ɛtufɑ̃     1
435500     étouffer  pi3S       ɛtuf     2
435506     étouffer   inf      ɛtufe     1
435739    étrangler  pi1S    ɛtʁɑ̃gl     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    17
437284       éviter  ii3S      ɛvitɛ     1
437295       éviter  pi3S       ɛvit     1
437301       éviter   inf      ɛvite     2
437474         être  pi2P         ɛt    17
437476         être   inf        ɛtʁ    20

[1980 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.4 s, total: 1min 39s
Wall time: 30.5 s

nbChunk 145
4200
1998

             lexeme  case       phono  tir1
40            avoir  pi3S           a    85
109      abandonner  ai1S    abɑ̃dɔnɛ     2
132      abandonner   inf    abɑ̃dɔne     2
170      abandonner  ppMP    abɑ̃dɔne     1
1133        aborder    pP     abɔʁdɑ̃     1
1147        aborder   inf      abɔʁde     2
1393        aboutir   inf      abutiʁ     1
2355         abuser  pi2P       abyze     1
2730       accabler  pi3S       akabl     1
2904      accentuer   inf    aksɑ̃tye     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     2
3003       accepter  ppMS     aksɛpte     1
3340     accommoder  pi1S      akɔmɔd     1
3376     accommoder  ppMS     akɔmɔde     1
3530       accorder  pi3S       akɔʁd     2
4259      accrocher   inf      akʁɔʃe     2
4656      accumuler   inf     akymyle     1
4685      accumuler  ppFP     akymyle     1
4748        accuser  ppMS       akyze     2
5119        acheter   inf       aʃəte     2
5137        acheter  ppFS       aʃəte     2
5157        achever   inf       aʃəve     1
5308        acheter  pi1S        aʃɛt     1
5311        acheter  pi3S        aʃɛt     2
5332        achever  pi3S        aʃɛv     1
5905       acquérir   inf      akɛʁiʁ     1
6870       admettre    pP     admɛtɑ̃     1
6955    administrer  ppMS  administʁe     1
7009        admirer  pi2S       admiʁ     1
...             ...   ...         ...   ...
432586     éprouver  ppMS      ɛpʁuve     1
433922      établir   inf     ɛtabliʁ     1
433924      établir  fi1S    ɛtabliʁɛ     1
433969      établir  pi3S      ɛtabli     1
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ    16
434070         être  ii3S         ɛtɛ    74
434173       étaler  pi2P       ɛtale     1
434730     éteindre  pi3P        ɛtɛɲ     1
434740     éteindre  ai1S       ɛtɛɲi     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434794      étendre  pi3P       ɛtɑ̃d     1
434801      étendre  ii1P    ɛtɑ̃djɔ̃     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     2
435422      étonner  ii3S       ɛtɔnɛ     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435471      étonner  ppMS       ɛtɔne     1
436182      étudier  ai1S      ɛtydjɛ     1
436198      étudier  pi1S       ɛtydi     1
436233      étudier  ppMS      ɛtydje     2
436316         être  ppMS         ɛte    26
436520      évaluer   inf      ɛvalye     1
436627     évanouir  ppMS      ɛvanui     1
437301       éviter   inf       ɛvite     2
437304       éviter  pc3P     ɛvitəʁɛ     1
437305       éviter  pc1S     ɛvitəʁɛ     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    17
437508         ôter  pi3S          ot     2

[1998 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.4 s, total: 1min 39s
Wall time: 30.1 s

nbChunk 146
4200
1974

             lexeme  case      phono  tir1
40            avoir  pi3S          a    83
164      abandonner  ppMS   abɑ̃dɔne     2
166      abandonner  ppFS   abɑ̃dɔne     1
292         abattre  fi3S     abatʁa     1
299         abattre   inf      abatʁ     1
688         abjurer  ppMS     abʒyʁe     1
1147        aborder   inf     abɔʁde     1
1415        aboutir  ii3S    abutisɛ     1
1571       abreuver   inf     abʁəve     1
2736       accabler   inf     akable     1
2967       accepter  pi3S     aksɛpt     1
2977       accepter  pc3S  aksɛptəʁɛ     1
3003       accepter  ppMS    aksɛpte     2
3397    accompagner  pi1S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3438      accomplir  ppMS    akɔ̃pli     1
3490      accomplir  pi3S    akɔ̃pli     2
3536       accorder   inf     akɔʁde     1
3913       accouder  ppMS      akude     1
4252      accrocher  pi1S      akʁɔʃ     1
4259      accrocher   inf     akʁɔʃe     2
4293      accrocher  ppFP     akʁɔʃe     1
4656      accumuler   inf    akymyle     1
4683      accumuler  ppMS    akymyle     1
4718        accuser  pi3P       akyz     1
4748        accuser  ppMS      akyze     1
4812      accélérer  pi3S    aksɛlɛʁ     1
4864      accélérer  ppFS   aksɛlɛʁe     1
5108        acheter  ii3P      aʃətɛ     1
5119        acheter   inf      aʃəte     4
...             ...   ...        ...   ...
428410      émerger  pi3P      ɛmɛʁʒ     1
428609      émettre  pi3S        ɛmɛ     1
428640      émettre   inf      ɛmɛtʁ     1
429333  émoustiller  ppMP   ɛmustije     1
432156      épouser  pi3S       ɛpuz     1
432160      épouser   inf      ɛpuze     1
432689      épuiser  ppMS     ɛpɥize     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    13
434070         être  ii3S        ɛtɛ    66
434762     éteindre   inf     ɛtɛ̃dʁ     1
434773     éteindre  pi3S       ɛtɛ̃     1
434775     éteindre  ppFS      ɛtɛ̃t     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     1
435243       étirer  ii3S      ɛtiʁɛ     1
435244       étirer    pP     ɛtiʁɑ̃     1
435748    étrangler   inf   ɛtʁɑ̃gle     2
435828    étreindre   inf    ɛtʁɛ̃dʁ     1
435972      étriper   inf     ɛtʁipe     1
436233      étudier  ppMS     ɛtydje     2
436316         être  ppMS        ɛte    24
436867     éveiller  ppMS      ɛvɛje     1
437292       éviter  pi1S       ɛvit     1
437301       éviter   inf      ɛvite     4
437411      évoquer  ai3S      ɛvɔka     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    11
437476         être   inf        ɛtʁ    17
437492         ôter  ai3S        ɔta     1

[1974 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.5 s, total: 1min 36s
Wall time: 29.2 s

nbChunk 147
4200
1912

            lexeme  case      phono  tir1
40           avoir  pi3S          a    77
125     abandonner  pi1S    abɑ̃dɔn     2
132     abandonner   inf   abɑ̃dɔne     1
164     abandonner  ppMS   abɑ̃dɔne     1
305        abattre  ppMS      abaty     1
1147       aborder   inf     abɔʁde     1
1160       aborder  pi2S      abɔʁd     1
1480        aboyer  pi1P    abwajɔ̃     1
1670       abriter  ii3P     abʁitɛ     1
2143      abstenir   inf   abstəniʁ     1
2610        abîmer  ppMS      abime     1
2763      accabler  ppMS     akable     1
2946      accepter  ai1S    aksɛptɛ     1
2948      accepter  ii1S    aksɛptɛ     1
2971      accepter   inf    aksɛpte     3
2977      accepter  pc3S  aksɛptəʁɛ     1
2989      accepter  pi2P    aksɛpte     1
3003      accepter  ppMS    aksɛpte     2
3440     accomplir  ppFS    akɔ̃pli     1
3443     accomplir   inf   akɔ̃pliʁ     1
3567      accorder  is3S     akɔʁda     1
4255     accrocher  pi3S      akʁɔʃ     1
4347     accroupir    pP  akʁupisɑ̃     1
4783       accéder   inf     aksɛde     1
5008      acharner  pi3S      aʃaʁn     2
5119       acheter   inf      aʃəte     5
5136       acheter  ppMS      aʃəte     1
5139       acheter  ppMP      aʃəte     1
5311       acheter  pi3S       aʃɛt     2
5319       acheter  pc2S    aʃɛtəʁɛ     1
...            ...   ...        ...   ...
432592    éprouver  ppMP     ɛpʁuve     1
433113     équiper   inf      ɛkipe     1
434021      étager  pi2S       ɛtaʒ     1
434048        être  ii3P        ɛtɛ     4
434068        être  ii1S        ɛtɛ     9
434070        être  ii3S        ɛtɛ    68
434734    éteindre  pi2P      ɛtɛɲe     1
434762    éteindre   inf     ɛtɛ̃dʁ     1
434775    éteindre  ppFS      ɛtɛ̃t     1
434821     étendre   inf     ɛtɑ̃dʁ     1
435054        être  ii2P       ɛtje     2
435172        être  ii1P      ɛtjɔ̃     1
435417     étonner  ai3S      ɛtɔna     1
435422     étonner  ii3S      ɛtɔnɛ     1
435457     étonner  pi2S       ɛtɔn     1
435460     étonner  pi2P      ɛtɔne     1
435838   étreindre  pi3S      ɛtʁɛ̃     1
436316        être  ppMS        ɛte    15
436402     évacuer   inf     ɛvakye     1
436484      évader  ppMS      ɛvade     1
436520     évaluer   inf     ɛvalye     1
436817    éveiller  ii3P      ɛvɛjɛ     1
436828    éveiller  pi1S       ɛvɛj     1
437328      éviter  ppMS      ɛvite     1
437367     évoluer   inf     ɛvɔlye     1
437413     évoquer  ii3P      ɛvɔkɛ     1
437424     évoquer  pi1S       ɛvɔk     1
437457     évoquer  ai3P     ɛvɔkɛʁ     1
437474        être  pi2P         ɛt    18
437476        être   inf        ɛtʁ    26

[1912 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 21.9 s, total: 1min 38s
Wall time: 30.5 s

nbChunk 148
4200
1974

             lexeme  case       phono  tir1
40            avoir  pi3S           a    74
114      abandonner    pP   abɑ̃dɔnɑ̃     2
132      abandonner   inf    abɑ̃dɔne     1
305         abattre  ppMS       abaty     2
399        abdiquer  ii1S      abdikɛ     1
589        abhorrer   inf       abɔʁe     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     1
3003       accepter  ppMS     aksɛpte     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     1
3519       accorder  ii3S      akɔʁdɛ     2
4255      accrocher  pi3S       akʁɔʃ     1
4369      accroupir  pi3S      akʁupi     1
4511     accueillir  ppMP       akəji     1
5111        acheter  ii3S       aʃətɛ     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     3
5157        achever   inf       aʃəve     1
5308        acheter  pi1S        aʃɛt     1
5807       acquérir  ppMS         aki     1
5833      acquitter  ii1S       akitɛ     1
5846      acquitter  pi3S        akit     1
6067        activer  pi3S       aktiv     1
6553        adhérer   inf       adɛʁe     1
6891       admettre   inf      admɛtʁ     1
6899    administrer  ii3P  administʁɛ     1
6969        admirer  ii3S      admiʁɛ     2
6988        admirer  pi1S       admiʁ     1
...             ...   ...         ...   ...
433199   équivaloir  pi3P      ɛkival     1
433912      établir  ppMS      ɛtabli     1
433954      établir  pi3P     ɛtablis     1
434048         être  ii3P         ɛtɛ     7
434068         être  ii1S         ɛtɛ    10
434069         être  ii2S         ɛtɛ     1
434070         être  ii3S         ɛtɛ    83
434488         être    pP        ɛtɑ̃     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434782      étendre  pi3S        ɛtɑ̃     1
434821      étendre   inf      ɛtɑ̃dʁ     1
434831      étendre  ppMS      ɛtɑ̃dy     2
434833      étendre  ppFS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     6
435460      étonner  pi2P       ɛtɔne     1
435475     étouffer  ai3S       ɛtufa     1
436205      étudier   inf      ɛtydje     3
436316         être  ppMS         ɛte    16
436402      évacuer   inf      ɛvakye     1
436453       évader  pi3S        ɛvad     1
437273       éviter  ai3S       ɛvita     1
437284       éviter  ii3S       ɛvitɛ     1
437301       éviter   inf       ɛvite     1
437314       éviter  pi2S        ɛvit     1
437407      évoluer  ppMS      ɛvɔlye     1
437427      évoquer  pi3S        ɛvɔk     1
437474         être  pi2P          ɛt     6
437476         être   inf         ɛtʁ    23
437539         ôter  ppMS         ɔte     1

[1974 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.8 s, total: 1min 37s
Wall time: 29.7 s

nbChunk 149
4200
1923

             lexeme  case      phono  tir1
40            avoir  pi3S          a    80
132      abandonner   inf   abɑ̃dɔne     2
166      abandonner  ppFS   abɑ̃dɔne     1
243         abattre  pi3S        aba     1
399        abdiquer  ii1S     abdikɛ     1
1393        aboutir   inf     abutiʁ     1
1718        abriter  ppFS     abʁite     1
2100       absorber  ppMS    absɔʁbe     1
2138       abstenir  pi2P    abstəne     1
2371         abuser  ppMS      abyze     1
2566         abîmer    pP     abimɑ̃     1
2581         abîmer   inf      abime     1
2947       accepter  ii3P    aksɛptɛ     1
2950       accepter  ii3S    aksɛptɛ     1
2952       accepter    pP   aksɛptɑ̃     1
2971       accepter   inf    aksɛpte     1
3386    accompagner    pP  akɔ̃paɲɑ̃     1
3397    accompagner  pi1S    akɔ̃paɲ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3422    accompagner  pi2P   akɔ̃paɲe     1
3490      accomplir  pi3S    akɔ̃pli     1
3519       accorder  ii3S     akɔʁdɛ     1
3530       accorder  pi3S      akɔʁd     1
3864       accouder  ii3P      akudɛ     1
4072       accourir   inf     akuʁiʁ     1
4259      accrocher   inf     akʁɔʃe     1
4716        accuser  pi3S       akyz     1
4771        accéder  ii3S     aksɛdɛ     1
4849      accélérer  pi2P   aksɛlɛʁe     1
4862      accélérer  ppMS   aksɛlɛʁe     1
...             ...   ...        ...   ...
432554     éprouver  pi3P      ɛpʁuv     1
432659      épuiser   inf     ɛpɥize     1
432689      épuiser  ppMS     ɛpɥize     1
433113      équiper   inf      ɛkipe     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ    17
434070         être  ii3S        ɛtɛ    67
434676       étayer    pP     ɛtɛjɑ̃     1
434740     éteindre  ai1S      ɛtɛɲi     1
434772     éteindre  ppMS       ɛtɛ̃     1
434775     éteindre  ppFS      ɛtɛ̃t     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     3
435172         être  ii1P      ɛtjɔ̃     4
435229    étiqueter  ppFS    ɛtikəte     1
435457      étonner  pi2S       ɛtɔn     1
435472      étonner  ppFS      ɛtɔne     1
436205      étudier   inf     ɛtydje     1
436212      étudier  fi2S    ɛtydiʁa     1
436237      étudier  ppFP     ɛtydje     1
436316         être  ppMS        ɛte    24
436402      évacuer   inf     ɛvakye     1
436436      évacuer  ppMP     ɛvakye     1
436835     éveiller   inf      ɛvɛje     1
437305       éviter  pc1S    ɛvitəʁɛ     1
437367      évoluer   inf     ɛvɔlye     1
437416      évoquer  ii3S      ɛvɔkɛ     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    13
437476         être   inf        ɛtʁ    14

[1923 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.2 s, total: 1min 35s
Wall time: 29 s

nbChunk 150
4200
1889

             lexeme  case     phono  tir1
40            avoir  pi3S         a    76
132      abandonner   inf  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     3
170      abandonner  ppMP  abɑ̃dɔne     1
243         abattre  pi3S       aba     2
280         abattre  ai1S     abati     1
890          abolir   inf    abɔliʁ     1
1148        aborder  fi3S  abɔʁdəʁa     1
1178        aborder  ppMP    abɔʁde     1
1242       aboucher  ii3P     abuʃɛ     1
2278      abstraire  pi3S    abstʁɛ     1
2971       accepter   inf   aksɛpte     3
3003       accepter  ppMS   aksɛpte     2
3380    accompagner  ai3S  akɔ̃paɲa     1
3397    accompagner  pi1S   akɔ̃paɲ     1
3399    accompagner  pI2S   akɔ̃paɲ     1
3527       accorder  pi1S     akɔʁd     2
3555       accorder  pI2P    akɔʁde     1
3571       accorder  ppMS    akɔʁde     1
3827      accoucher   inf     akuʃe     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4255      accrocher  pi3S     akʁɔʃ     1
4320      accroupir  ppMS    akʁupi     1
4754        accuser  ppMP     akyze     1
4771        accéder  ii3S    aksɛdɛ     1
4783        accéder   inf    aksɛde     1
5136        acheter  ppMS     aʃəte     1
5173        achever  ppFS     aʃəve     1
5787     acquiescer  ai3S    akjɛsa     1
6274         acérer  ppMP     asɛʁe     1
...             ...   ...       ...   ...
432552     éprouver  pi3S     ɛpʁuv     1
432586     éprouver  ppMS    ɛpʁuve     1
432695      épuiser  ppMP    ɛpɥize     1
433354      érafler  ppMS    ɛʁafle     1
433928      établir  pc3S  ɛtabliʁɛ     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ    10
434070         être  ii3S       ɛtɛ    70
434451     étancher   inf    ɛtɑ̃ʃe     1
434794      étendre  pi3P     ɛtɑ̃d     1
434831      étendre  ppMS    ɛtɑ̃dy     2
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     1
435438      étonner  pi3S      ɛtɔn     1
435460      étonner  pi2P     ɛtɔne     1
435471      étonner  ppMS     ɛtɔne     1
435540     étouffer  ppFS     ɛtufe     1
435786    étrangler  ppMP  ɛtʁɑ̃gle     1
436233      étudier  ppMS    ɛtydje     2
436316         être  ppMS       ɛte    20
436632     évanouir   inf   ɛvanuiʁ     1
436855     éveiller  pi2P     ɛvɛje     1
437301       éviter   inf     ɛvite     1
437407      évoluer  ppMS    ɛvɔlye     1
437413      évoquer  ii3P     ɛvɔkɛ     1
437431      évoquer   inf     ɛvɔke     1
437474         être  pi2P        ɛt    19
437476         être   inf       ɛtʁ    18
437512         ôter   inf       ɔte     1
437513         ôter  fi3S     ɔtəʁa     1

[1889 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.1 s, total: 1min 38s
Wall time: 29.6 s

nbChunk 151
4200
1941

             lexeme  case       phono  tir1
40            avoir  pi3S           a    92
132      abandonner   inf    abɑ̃dɔne     1
287         abattre  ai3S       abati     1
299         abattre   inf       abatʁ     1
1396        aboutir  pc3P     abutiʁɛ     1
2118       absoudre  pc2P    absudʁie     1
2339         abuser   inf       abyze     1
2904      accentuer   inf    aksɑ̃tye     1
2939       accepter  ai3S     aksɛpta     1
2980       accepter  pc2P  aksɛptəʁje     1
3003       accepter  ppMS     aksɛpte     1
3420    accompagner  ps2S     akɔ̃paɲ     1
3435    accompagner  ppFP    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
3443      accomplir   inf    akɔ̃pliʁ     1
3471      accomplir  ps3S    akɔ̃plis     1
3530       accorder  pi3S       akɔʁd     1
3536       accorder   inf      akɔʁde     1
4212     accoutumer  ppFS     akutyme     1
4272      accrocher  pi2S       akʁɔʃ     1
4511     accueillir  ppMP       akəji     1
4748        accuser  ppMS       akyze     1
4783        accéder   inf      aksɛde     1
5119        acheter   inf       aʃəte     3
5311        acheter  pi3S        aʃɛt     1
5316        acheter  fi1S     aʃɛtəʁɛ     1
5812       acquérir  ppFS        akiz     1
6414        adapter   inf      adapte     1
6883       admettre  pi1P     admɛtɔ̃     1
7250        adopter   inf      adɔpte     1
...             ...   ...         ...   ...
430558     épargner  pi3S       ɛpaʁɲ     1
431609     épingler  ppMS     ɛpɛ̃gle     1
432173      épouser  pi2S        ɛpuz     1
432532     éprouver  ai3S      ɛpʁuva     1
432534     éprouver  ii3P      ɛpʁuvɛ     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
433113      équiper   inf       ɛkipe     1
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ    17
434070         être  ii3S         ɛtɛ    75
434299       étaler  ppMS       ɛtale     1
434726     éteindre  ii3S       ɛtɛɲɛ     1
434773     éteindre  pi3S        ɛtɛ̃     1
434819      étendre  pc3S     ɛtɑ̃dʁɛ     1
435054         être  ii2P        ɛtje     1
435062    étinceler  ii3S    ɛtɛ̃səlɛ     1
435172         être  ii1P       ɛtjɔ̃     1
435244       étirer    pP      ɛtiʁɑ̃     1
435500     étouffer  pi3S        ɛtuf     1
435504     étouffer  pi3P        ɛtuf     1
435506     étouffer   inf       ɛtufe     1
435739    étrangler  pi1S     ɛtʁɑ̃gl     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
435780    étrangler  ppMS    ɛtʁɑ̃gle     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    20
436980     éventrer  ii3S     ɛvɑ̃tʁɛ     1
437301       éviter   inf       ɛvite     3
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    16

[1941 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.5 s, total: 1min 36s
Wall time: 29.9 s

nbChunk 152
4200
1944

             lexeme  case      phono  tir1
40            avoir  pi3S          a    76
132      abandonner   inf   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
255         abattre  ii3P      abatɛ     1
1132        aborder  ii3S     abɔʁdɛ     1
1143        aborder  pi3S      abɔʁd     1
1396        aboutir  pc3P    abutiʁɛ     1
2102       absorber  ppFS    absɔʁbe     1
2335         abuser  pi3S       abyz     1
2948       accepter  ii1S    aksɛptɛ     2
2964       accepter  pi1S     aksɛpt     1
2967       accepter  pi3S     aksɛpt     2
2971       accepter   inf    aksɛpte     1
2972       accepter  fi3S  aksɛptəʁa     1
3003       accepter  ppMS    aksɛpte     2
3382    accompagner  ii3P   akɔ̃paɲɛ     1
3821      accoucher  pi3S       akuʃ     1
3858      accoucher  ppMS      akuʃe     1
4088       accourir  pI2S       akuʁ     1
4259      accrocher   inf     akʁɔʃe     2
4280      accrocher  pi2P     akʁɔʃe     1
4293      accrocher  ppFP     akʁɔʃe     1
4482     accueillir  pi3S       akœj     1
4720        accuser   inf      akyze     1
4783        accéder   inf     aksɛde     1
4835      accélérer   inf   aksɛlɛʁe     1
5125        acheter  pi2P      aʃəte     1
5137        acheter  ppFS      aʃəte     1
5311        acheter  pi3S       aʃɛt     1
5316        acheter  fi1S    aʃɛtəʁɛ     2
...             ...   ...        ...   ...
432160      épouser   inf      ɛpuze     1
432390   épouvanter  pi3P    ɛpuvɑ̃t     1
432535     éprouver  ii1S     ɛpʁuvɛ     1
432549     éprouver  pi1S      ɛpʁuv     1
432586     éprouver  ppMS     ɛpʁuve     2
433912      établir  ppMS     ɛtabli     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ     9
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    82
434147       étaler  pi3S       ɛtal     1
434772     éteindre  ppMS       ɛtɛ̃     1
434782      étendre  pi3S       ɛtɑ̃     1
435172         être  ii1P      ɛtjɔ̃     2
435243       étirer  ii3S      ɛtiʁɛ     1
435435      étonner  pi1S       ɛtɔn     1
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435506     étouffer   inf      ɛtufe     1
435828    étreindre   inf    ɛtʁɛ̃dʁ     1
435865     étrenner   inf     ɛtʁɛne     1
436205      étudier   inf     ɛtydje     1
436207      étudier  fi1S    ɛtydiʁɛ     1
436316         être  ppMS        ɛte    31
436457       évader   inf      ɛvade     1
436520      évaluer   inf     ɛvalye     1
437301       éviter   inf      ɛvite     1
437413      évoquer  ii3P      ɛvɔkɛ     1
437416      évoquer  ii3S      ɛvɔkɛ     1
437474         être  pi2P         ɛt    11
437476         être   inf        ɛtʁ    18

[1944 rows x 4 columns]

0
CPU times: user 1min 9s, sys: 17.4 s, total: 1min 27s
Wall time: 31 s

nbChunk 153
4200
1929

             lexeme  case       phono  tir1
40            avoir  pi3S           a    78
101        abaisser  ppMS       abɛse     1
132      abandonner   inf    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     1
299         abattre   inf       abatʁ     2
1288       aboucher  ppFS       abuʃe     1
1455         aboyer  ai3S      abwaja     1
2100       absorber  ppMS     absɔʁbe     1
2371         abuser  ppMS       abyze     1
2973       accepter  fi1S   aksɛptəʁɛ     1
2980       accepter  pc2P  aksɛptəʁje     1
2989       accepter  pi2P     aksɛpte     1
2999       accepter  is3S     aksɛpta     1
3003       accepter  ppMS     aksɛpte     1
3313        accoler  ppMS       akɔle     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3573       accorder  ppFS      akɔʁde     1
4259      accrocher   inf      akʁɔʃe     2
4293      accrocher  ppFP      akʁɔʃe     1
4320      accroupir  ppMS      akʁupi     1
4521     accueillir  pi1P      akəjɔ̃     1
4818      accélérer  ai3S    aksɛlɛʁa     1
4849      accélérer  pi2P    aksɛlɛʁe     1
4864      accélérer  ppFS    aksɛlɛʁe     1
5102        acheter  ai3S       aʃəta     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     2
5311        acheter  pi3S        aʃɛt     1
6865       admettre  pi2S        admɛ     1
6928    administrer   inf  administʁe     1
...             ...   ...         ...   ...
428605  émerveiller  ppMS    ɛmɛʁvɛje     1
430591     épargner  ppFS      ɛpaʁɲe     1
430646   éparpiller  ppMP    ɛpaʁpije     1
432156      épouser  pi3S        ɛpuz     1
432160      épouser   inf       ɛpuze     2
432519     éprendre  ppMS        ɛpʁi     1
432535     éprouver  ii1S      ɛpʁuvɛ     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
432552     éprouver  pi3S       ɛpʁuv     1
432556     éprouver   inf      ɛpʁuve     1
432638      épuiser  ii3S      ɛpɥizɛ     1
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ     8
434070         être  ii3S         ɛtɛ    65
434788      étendre  ii3S      ɛtɑ̃dɛ     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     1
435244       étirer    pP      ɛtiʁɑ̃     1
435419      étonner  ii3P       ɛtɔnɛ     1
435438      étonner  pi3S        ɛtɔn     1
435542     étouffer  ppFP       ɛtufe     1
435780    étrangler  ppMS    ɛtʁɑ̃gle     1
435794    étreindre  ii3S      ɛtʁɛɲɛ     1
436316         être  ppMS         ɛte    11
436398      évacuer  pi3S       ɛvaky     1
436869     éveiller  ppFS       ɛvɛje     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    21
437497         ôter  ii3S         ɔtɛ     1

[1929 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 18.9 s, total: 1min 30s
Wall time: 30.7 s

nbChunk 154
4200
1944

             lexeme  case      phono  tir1
40            avoir  pi3S          a    71
148      abandonner  pi2P   abɑ̃dɔne     1
159      abandonner  ai1P  abɑ̃dɔnam     1
164      abandonner  ppMS   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
1480         aboyer  pi1P    abwajɔ̃     1
2143       abstenir   inf   abstəniʁ     1
2736       accabler   inf     akable     1
2904      accentuer   inf   aksɑ̃tye     1
2950       accepter  ii3S    aksɛptɛ     1
2971       accepter   inf    aksɛpte     1
2977       accepter  pc3S  aksɛptəʁɛ     1
3406    accompagner   inf   akɔ̃paɲe     1
4095       accourir  ppMP      akuʁy     1
4259      accrocher   inf     akʁɔʃe     1
4339      accroupir  pi1S     akʁupi     1
4656      accumuler   inf    akymyle     1
5102        acheter  ai3S      aʃəta     1
5119        acheter   inf      aʃəte     3
5140        achever  ai3S      aʃəva     1
6414        adapter   inf     adapte     1
6808        adjurer  ii1S     adʒyʁɛ     1
6885       admettre  fi1S    admɛtʁɛ     1
6996        admirer   inf     admiʁe     1
7028       admettre  ppMS       admi     1
7187        adonner  pi3S       adɔn     1
7294         adorer  ii3P      adɔʁɛ     1
7312         adorer  pi3S       adɔʁ     2
7343         adorer  ppMS      adɔʁe     1
7518       adresser  ai3S     adʁɛsa     1
...             ...   ...        ...   ...
430616   éparpiller   inf   ɛpaʁpije     1
431165        épier  pi3P        ɛpi     1
432160      épouser   inf      ɛpuze     2
432161      épouser  fi3S    ɛpuzəʁa     1
432392   épouvanter   inf   ɛpuvɑ̃te     1
432539     éprouver    pP    ɛpʁuvɑ̃     1
432552     éprouver  pi3S      ɛpʁuv     1
432556     éprouver   inf     ɛpʁuve     1
434048         être  ii3P        ɛtɛ     7
434068         être  ii1S        ɛtɛ    17
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    87
434147       étaler  pi3S       ɛtal     1
434300       étaler  ppFS      ɛtale     2
434804      étendre  ai1S     ɛtɑ̃di     1
435054         être  ii2P       ɛtje     3
435172         être  ii1P      ɛtjɔ̃     2
435471      étonner  ppMS      ɛtɔne     1
436198      étudier  pi1S      ɛtydi     1
436233      étudier  ppMS     ɛtydje     2
436316         être  ppMS        ɛte    26
436398      évacuer  pi3S      ɛvaky     1
436831     éveiller  pi3S       ɛvɛj     1
436867     éveiller  ppMS      ɛvɛje     1
436869     éveiller  ppFS      ɛvɛje     1
437284       éviter  ii3S      ɛvitɛ     2
437292       éviter  pi1S       ɛvit     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    14
437476         être   inf        ɛtʁ    18

[1944 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.1 s, total: 1min 38s
Wall time: 30 s

nbChunk 155
4200
1953

             lexeme  case       phono  tir1
40            avoir  pi3S           a    96
164      abandonner  ppMS    abɑ̃dɔne     1
307         abattre  ppFS       abaty     1
2610         abîmer  ppMS       abime     1
2977       accepter  pc3S   aksɛptəʁɛ     1
3003       accepter  ppMS     aksɛpte     1
3147       acclamer  ppMP      aklame     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     3
3508       accorder  ai3S      akɔʁda     1
3536       accorder   inf      akɔʁde     1
3556       accorder  pi2P      akɔʁde     1
4237      accrocher  ii3S      akʁɔʃɛ     1
4280      accrocher  pi2P      akʁɔʃe     1
4510     accueillir  ai3P      akəjiʁ     1
4726        accuser  pc3S     akyzəʁɛ     1
5050      acheminer  ii3P     aʃəminɛ     1
5053      acheminer  ii3S     aʃəminɛ     1
5157        achever   inf       aʃəve     1
5313        acheter  pi3P        aʃɛt     1
5332        achever  pi3S        aʃɛv     1
5880      acquitter  ppFS       akite     1
6443        adapter  ppMS      adapte     1
6877       admettre  pi2P      admɛte     1
7295         adorer  ii1S       adɔʁɛ     1
7309         adorer  pi1S        adɔʁ     2
7316         adorer   inf       adɔʁe     2
7535       adresser  pi3S       adʁɛs     1
7539       adresser   inf      adʁɛse     1
7755         aduler  ppMS       adyle     1
...             ...   ...         ...   ...
432689      épuiser  ppMS      ɛpɥize     1
433590       ériger   inf       ɛʁiʒe     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ     6
434070         être  ii3S         ɛtɛ    85
434134       étaler  ii3S       ɛtalɛ     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434831      étendre  ppMS      ɛtɑ̃dy     1
434868    éterniser   inf    ɛtɛʁnize     1
435054         être  ii2P        ɛtje     3
435172         être  ii1P       ɛtjɔ̃     1
435258       étirer  pi3P        ɛtiʁ     1
435420      étonner  ii1S       ɛtɔnɛ     1
435439      étonner  ps3S        ɛtɔn     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435500     étouffer  pi3S        ɛtuf     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
435752    étrangler  pc1S  ɛtʁɑ̃gləʁɛ     1
435776    étrangler  is3S    ɛtʁɑ̃gla     1
436316         être  ppMS         ɛte    13
436457       évader   inf       ɛvade     1
436869     éveiller  ppFS       ɛvɛje     1
437040      éventer  ppMS      ɛvɑ̃te     1
437295       éviter  pi3S        ɛvit     1
437301       éviter   inf       ɛvite     1
437325       éviter  is3S       ɛvita     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    23
437508         ôter  pi3S          ot     1

[1953 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22 s, total: 1min 38s
Wall time: 29.8 s

nbChunk 156
4200
1930

             lexeme  case     phono  tir1
40            avoir  pi3S         a   103
132      abandonner   inf  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     2
287         abattre  ai3S     abati     1
865          aboyer  pi3S      abwa     1
1147        aborder   inf    abɔʁde     1
1153        aborder  pc3S  abɔʁdəʁɛ     1
1457         aboyer  ii3P    abwajɛ     1
1571       abreuver   inf    abʁəve     1
1872        abréger  ii3S    abʁɛʒɛ     1
1950       absenter   inf   absɑ̃te     1
2100       absorber  ppMS   absɔʁbe     1
2715       accabler  ii3S    akablɛ     1
2950       accepter  ii3S   aksɛptɛ     2
2967       accepter  pi3S    aksɛpt     2
2971       accepter   inf   aksɛpte     1
2989       accepter  pi2P   aksɛpte     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3530       accorder  pi3S     akɔʁd     1
3862       accouder  ai3S     akuda     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4293      accrocher  ppFP    akʁɔʃe     1
4320      accroupir  ppMS    akʁupi     1
4509     accueillir   inf    akəjiʁ     1
4654      accumuler  pi3P    akymyl     1
4720        accuser   inf     akyze     1
5119        acheter   inf     aʃəte     2
5136        acheter  ppMS     aʃəte     3
...             ...   ...       ...   ...
427809    élucubrer   inf  ɛlykybʁe     1
427920       élever  pi1S      ɛlɛv     1
427923       élever  pi3S      ɛlɛv     1
428606  émerveiller  ppFS  ɛmɛʁvɛje     1
428609      émettre  pi3S       ɛmɛ     1
429839      énoncer  ii3S    ɛnɔ̃sɛ     1
430042     énumérer   inf   ɛnymɛʁe     1
430590     épargner  ppMS    ɛpaʁɲe     1
431992      éponger   inf    ɛpɔ̃ʒe     1
432519     éprendre  ppMS      ɛpʁi     1
432689      épuiser  ppMS    ɛpɥize     1
433590       ériger   inf     ɛʁiʒe     1
433981      établir  is3S    ɛtabli     1
434068         être  ii1S       ɛtɛ    14
434070         être  ii3S       ɛtɛ    72
434488         être    pP      ɛtɑ̃     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     1
435417      étonner  ai3S     ɛtɔna     1
435728    étrangler  ii3P  ɛtʁɑ̃glɛ     1
435748    étrangler   inf  ɛtʁɑ̃gle     1
436198      étudier  pi1S     ɛtydi     1
436316         être  ppMS       ɛte    15
436869     éveiller  ppFS     ɛvɛje     1
437280       éviter  ai1S     ɛvitɛ     1
437307       éviter  pc3S   ɛvitəʁɛ     1
437411      évoquer  ai3S     ɛvɔka     1
437474         être  pi2P        ɛt    12
437476         être   inf       ɛtʁ    22
437497         ôter  ii3S       ɔtɛ     1

[1930 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.6 s, total: 1min 40s
Wall time: 30.4 s

nbChunk 157
4200
1989

             lexeme  case     phono  tir1
40            avoir  pi3S         a    89
168      abandonner  ppFP  abɑ̃dɔne     1
292         abattre  fi3S    abatʁa     1
305         abattre  ppMS     abaty     1
582        abhorrer  pi1S      abɔʁ     1
2939       accepter  ai3S   aksɛpta     1
2950       accepter  ii3S   aksɛptɛ     1
2971       accepter   inf   aksɛpte     1
3316        accoler  ppMP     akɔle     1
3340     accommoder  pi1S    akɔmɔd     1
3434    accompagner  ppFS  akɔ̃paɲe     1
3443      accomplir   inf  akɔ̃pliʁ     1
3534       accorder  pi3P     akɔʁd     1
3556       accorder  pi2P    akɔʁde     1
3567       accorder  is3S    akɔʁda     1
3571       accorder  ppMS    akɔʁde     1
3916       accouder  ppMP     akude     1
4233      accrocher  ai1S    akʁɔʃɛ     1
4259      accrocher   inf    akʁɔʃe     2
4272      accrocher  pi2S     akʁɔʃ     1
4637      accumuler  ii3S   akymylɛ     1
4716        accuser  pi3S      akyz     1
4736        accuser  pi2P     akyze     1
4997       acharner  ii3S    aʃaʁnɛ     1
5068      acheminer  pi3P    aʃəmin     1
5108        acheter  ii3P     aʃətɛ     2
5119        acheter   inf     aʃəte     1
5316        acheter  fi1S   aʃɛtəʁɛ     1
5318        acheter  pc1S   aʃɛtəʁɛ     1
5321        acheter  fi2S   aʃɛtəʁa     1
...             ...   ...       ...   ...
432162      épouser  fi1S   ɛpuzəʁɛ     1
432181      épouser  pi2P     ɛpuze     1
432537     éprouver  ii3S    ɛpʁuvɛ     1
432562     éprouver  pc3S  ɛpʁuvəʁɛ     1
432689      épuiser  ppMS    ɛpɥize     1
433062   équilibrer  ppMS  ɛkilibʁe     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    16
434069         être  ii2S       ɛtɛ     2
434070         être  ii3S       ɛtɛ    64
434301       étaler  ppFP     ɛtale     1
434747     éteindre  ai3S     ɛtɛɲi     1
434839      étendre  ppMP    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     2
435417      étonner  ai3S     ɛtɔna     1
435472      étonner  ppFS     ɛtɔne     1
436203      étudier  pi3P     ɛtydi     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    18
436739     évaporer  ppMS   ɛvapɔʁe     1
436835     éveiller   inf     ɛvɛje     1
437285       éviter    pP    ɛvitɑ̃     1
437328       éviter  ppMS     ɛvite     1
437367      évoluer   inf    ɛvɔlye     1
437431      évoquer   inf     ɛvɔke     1
437474         être  pi2P        ɛt    13
437476         être   inf       ɛtʁ    24
437508         ôter  pi3S        ot     1
437525         ôter  pi2S        ot     1

[1989 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22 s, total: 1min 37s
Wall time: 29.9 s

nbChunk 158
4200
1945

             lexeme  case      phono  tir1
40            avoir  pi3S          a    77
67         abaisser  pi3S       abɛs     1
128      abandonner  pi3S    abɑ̃dɔn     1
305         abattre  ppMS      abaty     1
887          abolir  ppMS      abɔli     1
2610         abîmer  ppMS      abime     1
2897      accentuer  pi1S    aksɑ̃ty     1
2900      accentuer  pi3S    aksɑ̃ty     1
2950       accepter  ii3S    aksɛptɛ     1
2967       accepter  pi3S     aksɛpt     1
2997       accepter  pi1P   aksɛptɔ̃     1
3003       accepter  ppMS    aksɛpte     1
3400    accompagner  pi3S    akɔ̃paɲ     2
3406    accompagner   inf   akɔ̃paɲe     1
3434    accompagner  ppFS   akɔ̃paɲe     1
4090       accourir  pi3S       akuʁ     1
4291      accrocher  ppMS     akʁɔʃe     1
4426     accréditer   inf   akʁɛdite     1
4684      accumuler  ppFS    akymyle     1
5042       acharner  ppFS     aʃaʁne     1
5119        acheter   inf      aʃəte     2
5137        acheter  ppFS      aʃəte     1
5311        acheter  pi3S       aʃɛt     1
5315        acheter  fi3S    aʃɛtəʁa     1
6875       admettre  ps2S      admɛt     1
7309         adorer  pi1S       adɔʁ     1
7312         adorer  pi3S       adɔʁ     1
7398        adosser  ppMS      adɔse     1
7477        adoucir  pi2S      adusi     1
7519       adresser  ai1S     adʁɛsɛ     1
...             ...   ...        ...   ...
432640      épuiser    pP    ɛpɥizɑ̃     1
433912      établir  ppMS     ɛtabli     1
433922      établir   inf    ɛtabliʁ     2
434048         être  ii3P        ɛtɛ     1
434068         être  ii1S        ɛtɛ    21
434070         être  ii3S        ɛtɛ    78
434134       étaler  ii3S      ɛtalɛ     1
434734     éteindre  pi2P      ɛtɛɲe     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434839      étendre  ppMP     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     3
435064    étinceler    pP  ɛtɛ̃səlɑ̃     1
435417      étonner  ai3S      ɛtɔna     1
435425      étonner    pP     ɛtɔnɑ̃     1
435435      étonner  pi1S       ɛtɔn     1
435438      étonner  pi3S       ɛtɔn     1
435497     étouffer  pi1S       ɛtuf     1
435511     étouffer  pc2S    ɛtufəʁɛ     1
435739    étrangler  pi1S    ɛtʁɑ̃gl     1
435742    étrangler  pi3S    ɛtʁɑ̃gl     1
436235      étudier  ppFS     ɛtydje     1
436316         être  ppMS        ɛte    23
436402      évacuer   inf     ɛvakye     2
436632     évanouir   inf    ɛvanuiʁ     1
436752       évaser    pP     ɛvazɑ̃     1
436831     éveiller  pi3S       ɛvɛj     1
437301       éviter   inf      ɛvite     2
437407      évoluer  ppMS     ɛvɔlye     1
437474         être  pi2P         ɛt     5
437476         être   inf        ɛtʁ    28

[1945 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.1 s, total: 1min 34s
Wall time: 28.8 s

nbChunk 159
4200
1873

             lexeme  case        phono  tir1
40            avoir  pi3S            a    93
143      abandonner  fi1P  abɑ̃dɔnəʁɔ̃     1
148      abandonner  pi2P     abɑ̃dɔne     1
255         abattre  ii3P        abatɛ     1
264         abattre  pi3P         abat     1
616        abhorrer  ppMS        abɔʁe     1
1132        aborder  ii3S       abɔʁdɛ     1
1670        abriter  ii3P       abʁitɛ     1
2063       absorber  pi1S       absɔʁb     1
2610         abîmer  ppMS        abime     1
2764       accabler  ppFS       akable     1
2967       accepter  pi3S       aksɛpt     2
2971       accepter   inf      aksɛpte     2
3003       accepter  ppMS      aksɛpte     2
3400    accompagner  pi3S      akɔ̃paɲ     1
3406    accompagner   inf     akɔ̃paɲe     1
3490      accomplir  pi3S      akɔ̃pli     1
3527       accorder  pi1S        akɔʁd     1
3858      accoucher  ppMS        akuʃe     1
4255      accrocher  pi3S        akʁɔʃ     1
4502     accueillir  ppMS        akəji     1
4509     accueillir   inf       akəjiʁ     1
4683      accumuler  ppMS      akymyle     1
4691        accuser  ii1S        akyzɛ     1
4713        accuser  pi1S         akyz     1
4783        accéder   inf       aksɛde     1
5008       acharner  pi3S        aʃaʁn     1
5092      acheminer  pi1P     aʃəminɔ̃     1
5119        acheter   inf        aʃəte     4
5150        achever    pP       aʃəvɑ̃     1
...             ...   ...          ...   ...
432586     éprouver  ppMS       ɛpʁuve     1
433196   équivaloir    pP     ɛkivalɑ̃     1
434004       étager  pi3P         ɛtaʒ     1
434048         être  ii3P          ɛtɛ     2
434068         être  ii1S          ɛtɛ    12
434070         être  ii3S          ɛtɛ    72
434166       étaler  pi2S         ɛtal     1
434782      étendre  pi3S         ɛtɑ̃     1
434811      étendre  ai3S       ɛtɑ̃di     2
435054         être  ii2P         ɛtje     1
435059    étinceler  ii3P     ɛtɛ̃səlɛ     1
435172         être  ii1P        ɛtjɔ̃     1
435435      étonner  pi1S         ɛtɔn     1
435437      étonner  pI2S         ɛtɔn     1
435438      étonner  pi3S         ɛtɔn     1
435471      étonner  ppMS        ɛtɔne     1
435472      étonner  ppFS        ɛtɔne     1
435486     étouffer    pP       ɛtufɑ̃     1
435506     étouffer   inf        ɛtufe     1
436205      étudier   inf       ɛtydje     1
436233      étudier  ppMS       ɛtydje     2
436316         être  ppMS          ɛte    27
436457       évader   inf        ɛvade     1
436520      évaluer   inf       ɛvalye     1
437285       éviter    pP       ɛvitɑ̃     1
437301       éviter   inf        ɛvite     2
437431      évoquer   inf        ɛvɔke     1
437474         être  pi2P           ɛt    13
437476         être   inf          ɛtʁ    14
437512         ôter   inf          ɔte     1

[1873 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.2 s, total: 1min 38s
Wall time: 29.8 s

nbChunk 160
4200
1941

             lexeme  case     phono  tir1
40            avoir  pi3S         a    72
132      abandonner   inf  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     1
166      abandonner  ppFS  abɑ̃dɔne     1
883          aboyer  pi2S      abwa     1
1112        abonner  ppFS     abɔne     2
1388        aboutir  ppMS     abuti     1
1440        aboutir  pi3S     abuti     1
2332         abuser  pi1S      abyz     1
2764       accabler  ppFS    akable     1
2967       accepter  pi3S    aksɛpt     1
3003       accepter  ppMS   aksɛpte     1
3385    accompagner  ii3S  akɔ̃paɲɛ     1
3397    accompagner  pi1S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     1
3443      accomplir   inf  akɔ̃pliʁ     2
3573       accorder  ppFS    akɔʁde     1
3655       accoster   inf    akɔste     1
4255      accrocher  pi3S     akʁɔʃ     1
4280      accrocher  pi2P    akʁɔʃe     1
4691        accuser  ii1S     akyzɛ     1
4720        accuser   inf     akyze     1
5102        acheter  ai3S     aʃəta     1
5119        acheter   inf     aʃəte     2
5139        acheter  ppMP     aʃəte     1
5140        achever  ai3S     aʃəva     1
5332        achever  pi3S      aʃɛv     1
5338        achever  fi3S   aʃɛvəʁa     1
6053        activer  ii3S    aktivɛ     1
6891       admettre   inf    admɛtʁ     1
...             ...   ...       ...   ...
429691      énerver  pi1S     ɛnɛʁv     1
429694      énerver  pi3S     ɛnɛʁv     2
429700      énerver   inf    ɛnɛʁve     1
430590     épargner  ppMS    ɛpaʁɲe     2
432160      épouser   inf     ɛpuze     2
432164      épouser  pc1S   ɛpuzəʁɛ     1
432689      épuiser  ppMS    ɛpɥize     1
434048         être  ii3P       ɛtɛ     6
434068         être  ii1S       ɛtɛ     6
434070         être  ii3S       ɛtɛ    68
434782      étendre  pi3S      ɛtɑ̃     1
434827      étendre  pi1S      ɛtɑ̃     1
434831      étendre  ppMS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     2
435062    étinceler  ii3S  ɛtɛ̃səlɛ     1
435417      étonner  ai3S     ɛtɔna     1
435444      étonner   inf     ɛtɔne     1
435506     étouffer   inf     ɛtufe     1
435748    étrangler   inf  ɛtʁɑ̃gle     1
435815    étreindre  ai3S    ɛtʁɛɲi     1
436183      étudier  ii3P    ɛtydjɛ     1
436188      étudier    pP   ɛtydjɑ̃     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    20
436629     évanouir  ppFS    ɛvanui     1
437301       éviter   inf     ɛvite     1
437411      évoquer  ai3S     ɛvɔka     1
437431      évoquer   inf     ɛvɔke     1
437474         être  pi2P        ɛt    13
437476         être   inf       ɛtʁ    18

[1941 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.4 s, total: 1min 40s
Wall time: 30.3 s

nbChunk 161
4200
1965

             lexeme  case     phono  tir1
40            avoir  pi3S         a    87
109      abandonner  ai1S  abɑ̃dɔnɛ     1
132      abandonner   inf  abɑ̃dɔne     1
166      abandonner  ppFS  abɑ̃dɔne     1
299         abattre   inf     abatʁ     1
1393        aboutir   inf    abutiʁ     1
1412        aboutir  ii3P   abutisɛ     1
1761        abroger   inf    abʁɔʒe     1
2339         abuser   inf     abyze     1
2964       accepter  pi1S    aksɛpt     1
2971       accepter   inf   aksɛpte     1
3406    accompagner   inf  akɔ̃paɲe     1
3443      accomplir   inf  akɔ̃pliʁ     1
3519       accorder  ii3S    akɔʁdɛ     1
3527       accorder  pi1S     akɔʁd     1
3536       accorder   inf    akɔʁde     2
4255      accrocher  pi3S     akʁɔʃ     1
4259      accrocher   inf    akʁɔʃe     1
4323      accroupir   inf   akʁupiʁ     1
4509     accueillir   inf    akəjiʁ     1
4720        accuser   inf     akyze     1
5119        acheter   inf     aʃəte     2
5124        acheter  pI2P     aʃəte     1
5136        acheter  ppMS     aʃəte     2
5137        acheter  ppFS     aʃəte     1
5149        achever  ii3S     aʃəvɛ     1
5308        acheter  pi1S      aʃɛt     1
5311        acheter  pi3S      aʃɛt     1
6966        admirer  ii3P    admiʁɛ     1
6991        admirer  pi3S     admiʁ     1
...             ...   ...       ...   ...
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    17
434070         être  ii3S       ɛtɛ    76
434153       étaler   inf     ɛtale     1
434166       étaler  pi2S      ɛtal     1
434299       étaler  ppMS     ɛtale     1
434762     éteindre   inf    ɛtɛ̃dʁ     2
434773     éteindre  pi3S      ɛtɛ̃     2
434831      étendre  ppMS    ɛtɑ̃dy     1
434866    éterniser  pi3P   ɛtɛʁniz     1
434923     éternuer   inf   ɛtɛʁnye     1
435054         être  ii2P      ɛtje     3
435172         être  ii1P     ɛtjɔ̃     4
435450      étonner  pc3S   ɛtɔnəʁɛ     1
435457      étonner  pi2S      ɛtɔn     1
435500     étouffer  pi3S      ɛtuf     1
435780    étrangler  ppMS  ɛtʁɑ̃gle     1
435972      étriper   inf    ɛtʁipe     1
436188      étudier    pP   ɛtydjɑ̃     1
436205      étudier   inf    ɛtydje     1
436220      étudier  pI2P    ɛtydje     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    27
436457       évader   inf     ɛvade     1
436518      évaluer  pi3P     ɛvaly     1
436656     évanouir  ii3S  ɛvanuisɛ     1
436867     éveiller  ppMS     ɛvɛje     1
437474         être  pi2P        ɛt    17
437476         être   inf       ɛtʁ    21
437497         ôter  ii3S       ɔtɛ     1

[1965 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.7 s, total: 1min 36s
Wall time: 29.5 s

nbChunk 162
4200
1915

             lexeme  case     phono  tir1
40            avoir  pi3S         a    77
261         abattre  ps3S      abat     1
1110        abonner  ppMS     abɔne     1
1147        aborder   inf    abɔʁde     1
1393        aboutir   inf    abutiʁ     1
1603       abreuver  ppMP    abʁəve     1
2763       accabler  ppMS    akable     1
2971       accepter   inf   aksɛpte     2
3003       accepter  ppMS   aksɛpte     1
3385    accompagner  ii3S  akɔ̃paɲɛ     1
3397    accompagner  pi1S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     3
3443      accomplir   inf  akɔ̃pliʁ     1
3475      accomplir  pi3P  akɔ̃plis     1
3573       accorder  ppFS    akɔʁde     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4255      accrocher  pi3S     akʁɔʃ     1
4512     accueillir  ai1S     akəji     1
4656      accumuler   inf   akymyle     1
4720        accuser   inf     akyze     1
4733        accuser  pi2S      akyz     1
4746        accuser  ai3P    akyzɛʁ     1
4812      accélérer  pi3S   aksɛlɛʁ     1
5119        acheter   inf     aʃəte     3
5136        acheter  ppMS     aʃəte     3
5323        acheter  pc2P  aʃɛtəʁje     1
5852      acquitter   inf     akite     1
6443        adapter  ppMS    adapte     1
6865       admettre  pi2S      admɛ     1
6891       admettre   inf    admɛtʁ     1
...             ...   ...       ...   ...
429700      énerver   inf    ɛnɛʁve     1
430590     épargner  ppMS    ɛpaʁɲe     2
432160      épouser   inf     ɛpuze     1
432303      épouser  ppFS     ɛpuze     1
432659      épuiser   inf    ɛpɥize     1
433170      équiper  ppFS     ɛkipe     1
433525     éreinter   inf    ɛʁɛ̃te     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ     9
434070         être  ii3S       ɛtɛ    78
434153       étaler   inf     ɛtale     1
434302       étaler  ppMP     ɛtale     1
434831      étendre  ppMS    ɛtɑ̃dy     1
434833      étendre  ppFS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     1
435438      étonner  pi3S      ɛtɔn     1
435500     étouffer  pi3S      ɛtuf     1
435544     étouffer  ppMP     ɛtufe     1
436316         être  ppMS       ɛte    23
437024     éventrer  ppMS   ɛvɑ̃tʁe     1
437292       éviter  pi1S      ɛvit     1
437301       éviter   inf     ɛvite     1
437317       éviter  pi2P     ɛvite     1
437330       éviter  ppFP     ɛvite     1
437352      évoluer  ii3S    ɛvɔlyɛ     1
437474         être  pi2P        ɛt     6
437476         être   inf       ɛtʁ    20
437539         ôter  ppMS       ɔte     1

[1915 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.8 s, total: 1min 37s
Wall time: 30 s

nbChunk 163
4200
1947

             lexeme  case      phono  tir1
40            avoir  pi3S          a    85
113      abandonner  ii3S   abɑ̃dɔnɛ     1
125      abandonner  pi1S    abɑ̃dɔn     1
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
305         abattre  ppMS      abaty     1
914          abolir    pP   abɔlisɑ̃     1
1393        aboutir   inf     abutiʁ     1
2063       absorber  pi1S     absɔʁb     1
2964       accepter  pi1S     aksɛpt     2
2971       accepter   inf    aksɛpte     1
3003       accepter  ppMS    aksɛpte     1
3144       acclamer  ppMS     aklame     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3419    accompagner  pi2S    akɔ̃paɲ     1
3438      accomplir  ppMS    akɔ̃pli     1
3443      accomplir   inf   akɔ̃pliʁ     1
3467      accomplir  ii3S  akɔ̃plisɛ     1
3516       accorder  ii3P     akɔʁdɛ     1
3536       accorder   inf     akɔʁde     1
3862       accouder  ai3S      akuda     1
3878       accouder  pi3S       akud     1
4178     accoutumer  pi3S     akutym     1
4259      accrocher   inf     akʁɔʃe     1
4292      accrocher  ppFS     akʁɔʃe     1
4473     accueillir  ii3S      akəjɛ     1
4688        accuser  ai3S      akyza     1
4720        accuser   inf      akyze     1
...             ...   ...        ...   ...
432153      épouser  pi1S       ɛpuz     1
432160      épouser   inf      ɛpuze     2
432534     éprouver  ii3P     ɛpʁuvɛ     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
432552     éprouver  pi3S      ɛpʁuv     1
432586     éprouver  ppMS     ɛpʁuve     2
432691      épuiser  ppFS     ɛpɥize     2
433354      érafler  ppMS     ɛʁafle     1
433912      établir  ppMS     ɛtabli     1
433914      établir  ppFS     ɛtabli     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    19
434070         être  ii3S        ɛtɛ    64
434134       étaler  ii3S      ɛtalɛ     1
434151       étaler  pi3P       ɛtal     1
434747     éteindre  ai3S      ɛtɛɲi     1
435054         être  ii2P       ɛtje     2
435243       étirer  ii3S      ɛtiʁɛ     1
435438      étonner  pi3S       ɛtɔn     1
435497     étouffer  pi1S       ɛtuf     1
436183      étudier  ii3P     ɛtydjɛ     1
436316         être  ppMS        ɛte    18
436453       évader  pi3S       ɛvad     1
436831     éveiller  pi3S       ɛvɛj     1
437301       éviter   inf      ɛvite     1
437367      évoluer   inf     ɛvɔlye     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    25
437505         ôter  pi1S         ot     1

[1947 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.2 s, total: 1min 39s
Wall time: 29.7 s

nbChunk 164
4200
1952

             lexeme  case       phono  tir1
40            avoir  pi3S           a    88
132      abandonner   inf    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     1
166      abandonner  ppFS    abɑ̃dɔne     1
1121        aborder  ai3S      abɔʁda     1
1147        aborder   inf      abɔʁde     1
1175        aborder  ppMS      abɔʁde     1
1393        aboutir   inf      abutiʁ     1
1688        abriter   inf      abʁite     1
2051       absorber  ii3S     absɔʁbɛ     1
2581         abîmer   inf       abime     1
2766       accabler  ppMP      akable     1
2950       accepter  ii3S     aksɛptɛ     1
3003       accepter  ppMS     aksɛpte     3
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3490      accomplir  pi3S     akɔ̃pli     1
4072       accourir   inf      akuʁiʁ     1
4090       accourir  pi3S        akuʁ     1
4210     accoutumer  ppMS     akutyme     1
4238      accrocher    pP     akʁɔʃɑ̃     1
4280      accrocher  pi2P      akʁɔʃe     1
4689        accuser  ai1S       akyzɛ     1
4748        accuser  ppMS       akyze     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     2
5311        acheter  pi3S        aʃɛt     2
6958    administrer  ppMP  administʁe     1
7023        admirer  ppMS      admiʁe     1
7173        adonner  ii3P       adɔnɛ     1
...             ...   ...         ...   ...
429677      énerver  ii3S      ɛnɛʁvɛ     1
432160      épouser   inf       ɛpuze     1
432374   épouvanter  ii3S    ɛpuvɑ̃tɛ     1
432535     éprouver  ii1S      ɛpʁuvɛ     1
433912      établir  ppMS      ɛtabli     1
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    83
434747     éteindre  ai3S       ɛtɛɲi     1
434762     éteindre   inf      ɛtɛ̃dʁ     2
434773     éteindre  pi3S        ɛtɛ̃     1
434821      étendre   inf      ɛtɑ̃dʁ     1
435054         être  ii2P        ɛtje     4
435172         être  ii1P       ɛtjɔ̃     3
435438      étonner  pi3S        ɛtɔn     1
435444      étonner   inf       ɛtɔne     1
435456      étonner  fi3P    ɛtɔnəʁɔ̃     1
435472      étonner  ppFS       ɛtɔne     1
435538     étouffer  ppMS       ɛtufe     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436186      étudier  ii3S      ɛtydjɛ     1
436316         être  ppMS         ɛte    29
436627     évanouir  ppMS      ɛvanui     1
436654     évanouir  ii1S    ɛvanuisɛ     1
436820     éveiller  ii3S       ɛvɛjɛ     1
436865     éveiller  ai3P      ɛvɛjɛʁ     1
437301       éviter   inf       ɛvite     1
437474         être  pi2P          ɛt    24
437476         être   inf         ɛtʁ    25
437505         ôter  pi1S          ot     1

[1952 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.7 s, total: 1min 37s
Wall time: 29.5 s

nbChunk 165
4200
1924

             lexeme  case      phono  tir1
40            avoir  pi3S          a    86
114      abandonner    pP  abɑ̃dɔnɑ̃     2
129      abandonner  ps3S    abɑ̃dɔn     1
164      abandonner  ppMS   abɑ̃dɔne     1
1980       absenter  ppFS    absɑ̃te     1
2102       absorber  ppFS    absɔʁbe     1
2715       accabler  ii3S     akablɛ     1
2971       accepter   inf    aksɛpte     3
3003       accepter  ppMS    aksɛpte     1
3397    accompagner  pi1S    akɔ̃paɲ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3443      accomplir   inf   akɔ̃pliʁ     1
3467      accomplir  ii3S  akɔ̃plisɛ     1
3671       accoster  pi2P     akɔste     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4716        accuser  pi3S       akyz     1
4812      accélérer  pi3S    aksɛlɛʁ     2
5053      acheminer  ii3S    aʃəminɛ     1
5119        acheter   inf      aʃəte     2
5136        acheter  ppMS      aʃəte     1
5140        achever  ai3S      aʃəva     1
5146        achever  ii3P      aʃəvɛ     1
5149        achever  ii3S      aʃəvɛ     1
5157        achever   inf      aʃəve     1
5173        achever  ppFS      aʃəve     1
5311        acheter  pi3S       aʃɛt     1
5336        achever  pi3P       aʃɛv     1
5807       acquérir  ppMS        aki     1
6072        activer   inf     aktive     1
6553        adhérer   inf      adɛʁe     1
...             ...   ...        ...   ...
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ     7
434070         être  ii3S        ɛtɛ    67
434299       étaler  ppMS      ɛtale     1
434423       étamer  ppMS      ɛtame     1
434488         être    pP       ɛtɑ̃     1
434727     éteindre    pP     ɛtɛɲɑ̃     1
434747     éteindre  ai3S      ɛtɛɲi     1
434768     éteindre  pi1S       ɛtɛ̃     1
434773     éteindre  pi3S       ɛtɛ̃     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     2
435062    étinceler  ii3S   ɛtɛ̃səlɛ     1
435172         être  ii1P      ɛtjɔ̃     2
435243       étirer  ii3S      ɛtiʁɛ     1
435422      étonner  ii3S      ɛtɔnɛ     1
435444      étonner   inf      ɛtɔne     1
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435470      étonner  ai3P     ɛtɔnɛʁ     1
435472      étonner  ppFS      ɛtɔne     1
435484     étouffer  ii3S      ɛtufɛ     1
436316         être  ppMS        ɛte    23
436629     évanouir  ppFS     ɛvanui     1
436977     éventrer  ii3P    ɛvɑ̃tʁɛ     1
437301       éviter   inf      ɛvite     2
437328       éviter  ppMS      ɛvite     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    18

[1924 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.1 s, total: 1min 38s
Wall time: 30.1 s

nbChunk 166
4200
1955

            lexeme  case     phono  tir1
40           avoir  pi3S         a   106
50        abaisser  ii3S     abɛsɛ     1
148     abandonner  pi2P  abɑ̃dɔne     1
299        abattre   inf     abatʁ     1
300        abattre  fi2P    abatʁe     1
305        abattre  ppMS     abaty     1
1147       aborder   inf    abɔʁde     1
1674       abriter    pP   abʁitɑ̃     1
2577        abîmer  pi3S      abim     1
2900     accentuer  pi3S   aksɑ̃ty     1
2938     accentuer  ppMP  aksɑ̃tye     1
2967      accepter  pi3S    aksɛpt     1
2989      accepter  pi2P   aksɛpte     1
3003      accepter  ppMS   aksɛpte     2
3113      acclamer  pi3S     aklam     1
3349    accommoder   inf   akɔmɔde     1
3438     accomplir  ppMS   akɔ̃pli     1
3443     accomplir   inf  akɔ̃pliʁ     1
3489     accomplir  ai3S   akɔ̃pli     1
3492     accomplir  is3S   akɔ̃pli     1
3527      accorder  pi1S     akɔʁd     1
3544      accorder  fi2P  akɔʁdəʁe     1
3827     accoucher   inf     akuʃe     1
3840     accoucher  pi2S      akuʃ     1
4009      accourir  ii3S     akuʁɛ     1
4094      accourir  ai3P    akuʁyʁ     1
4252     accrocher  pi1S     akʁɔʃ     1
4259     accrocher   inf    akʁɔʃe     1
4509    accueillir   inf    akəjiʁ     1
4716       accuser  pi3S      akyz     1
...            ...   ...       ...   ...
430610  éparpiller  pi3S   ɛpaʁpij     1
430905      épeler  ppMS     ɛpəle     1
431575    épingler   inf   ɛpɛ̃gle     1
432556    éprouver   inf    ɛpʁuve     1
432588    éprouver  ppFS    ɛpʁuve     1
433922     établir   inf   ɛtabliʁ     1
433939     établir  pi1S    ɛtabli     1
434048        être  ii3P       ɛtɛ     6
434068        être  ii1S       ɛtɛ    17
434070        être  ii3S       ɛtɛ    69
434300      étaler  ppFS     ɛtale     1
434488        être    pP      ɛtɑ̃     1
434772    éteindre  ppMS      ɛtɛ̃     1
434773    éteindre  pi3S      ɛtɛ̃     1
434821     étendre   inf    ɛtɑ̃dʁ     1
434827     étendre  pi1S      ɛtɑ̃     1
434914    éternuer  pi1S    ɛtɛʁny     1
435054        être  ii2P      ɛtje     2
435172        être  ii1P     ɛtjɔ̃     1
435438     étonner  pi3S      ɛtɔn     2
435457     étonner  pi2S      ɛtɔn     1
435519    étouffer  pi2S      ɛtuf     1
435794   étreindre  ii3S    ɛtʁɛɲɛ     1
436205     étudier   inf    ɛtydje     1
436316        être  ppMS       ɛte    30
437198     évincer  ppMS    ɛvɛ̃se     1
437295      éviter  pi3S      ɛvit     1
437413     évoquer  ii3P     ɛvɔkɛ     1
437474        être  pi2P        ɛt     8
437476        être   inf       ɛtʁ    10

[1955 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.2 s, total: 1min 35s
Wall time: 29.5 s

nbChunk 167
4200
1906

             lexeme  case     phono  tir1
40            avoir  pi3S         a    89
129      abandonner  ps3S   abɑ̃dɔn     1
130      abandonner  pi3P   abɑ̃dɔn     1
132      abandonner   inf  abɑ̃dɔne     1
259         abattre    pP    abatɑ̃     1
1145        aborder  pi3P     abɔʁd     1
2971       accepter   inf   aksɛpte     1
3001       accepter  ai3P  aksɛptɛʁ     1
3003       accepter  ppMS   aksɛpte     1
3319     accommoder  ii3P   akɔmɔdɛ     1
3380    accompagner  ai3S  akɔ̃paɲa     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3443      accomplir   inf  akɔ̃pliʁ     1
3534       accorder  pi3P     akɔʁd     1
4255      accrocher  pi3S     akʁɔʃ     1
4259      accrocher   inf    akʁɔʃe     1
4291      accrocher  ppMS    akʁɔʃe     1
4368      accroupir  ai3S    akʁupi     1
4503     accueillir  ppFS     akəji     1
4713        accuser  pi1S      akyz     1
4716        accuser  pi3S      akyz     1
5012       acharner  pi3P     aʃaʁn     1
5119        acheter   inf     aʃəte     2
5136        acheter  ppMS     aʃəte     1
5173        achever  ppFS     aʃəve     1
5308        acheter  pi1S      aʃɛt     1
6865       admettre  pi2S      admɛ     1
7028       admettre  ppMS      admi     2
7312         adorer  pi3S      adɔʁ     1
7495        adoucir  pi3P    adusis     1
...             ...   ...       ...   ...
429349     émouvoir   inf   ɛmuvwaʁ     1
429365     émouvoir  ppMS       ɛmy     1
430562     épargner   inf    ɛpaʁɲe     1
431555     épingler  ai1S   ɛpɛ̃glɛ     1
431789        épier  ppFS      ɛpje     1
432160      épouser   inf     ɛpuze     1
432537     éprouver  ii3S    ɛpʁuvɛ     1
432552     éprouver  pi3S     ɛpʁuv     1
434068         être  ii1S       ɛtɛ    20
434070         être  ii3S       ɛtɛ    63
434488         être    pP      ɛtɑ̃     1
434734     éteindre  pi2P     ɛtɛɲe     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
434770     éteindre  pi2S      ɛtɛ̃     1
434773     éteindre  pi3S      ɛtɛ̃     1
434833      étendre  ppFS    ɛtɑ̃dy     1
434923     éternuer   inf   ɛtɛʁnye     1
435054         être  ii2P      ɛtje     1
435074    étinceler   inf  ɛtɛ̃səle     1
435232       étirer  ai3S     ɛtiʁa     1
435435      étonner  pi1S      ɛtɔn     1
435444      étonner   inf     ɛtɔne     1
435484     étouffer  ii3S     ɛtufɛ     1
435500     étouffer  pi3S      ɛtuf     1
436316         être  ppMS       ɛte    18
436402      évacuer   inf    ɛvakye     1
436520      évaluer   inf    ɛvalye     1
437301       éviter   inf     ɛvite     1
437474         être  pi2P        ɛt    14
437476         être   inf       ɛtʁ    17

[1906 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.3 s, total: 1min 41s
Wall time: 30.8 s

nbChunk 168
4200
1988

             lexeme  case       phono  tir1
40            avoir  pi3S           a    92
132      abandonner   inf    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     3
307         abattre  ppFS       abaty     1
1121        aborder  ai3S      abɔʁda     1
1688        abriter   inf      abʁite     1
2102       absorber  ppFS     absɔʁbe     1
2226       abstenir  pi1S     abstjɛ̃     1
2581         abîmer   inf       abime     1
2887      accentuer  ii3S    aksɑ̃tyɛ     1
2939       accepter  ai3S     aksɛpta     1
2964       accepter  pi1S      aksɛpt     1
2994       accepter  ii1P   aksɛptjɔ̃     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     1
3433    accompagner  ppMS    akɔ̃paɲe     2
3440      accomplir  ppFS     akɔ̃pli     1
3468      accomplir    pP  akɔ̃plisɑ̃     1
3536       accorder   inf      akɔʁde     1
3846      accoucher  pI2P       akuʃe     1
4255      accrocher  pi3S       akʁɔʃ     1
4321      accroupir  ppFS      akʁupi     1
4864      accélérer  ppFS    aksɛlɛʁe     1
5042       acharner  ppFS      aʃaʁne     1
5119        acheter   inf       aʃəte     4
5135        acheter  ai3P      aʃətɛʁ     1
5136        acheter  ppMS       aʃəte     1
5149        achever  ii3S       aʃəvɛ     1
5171        achever  ppMS       aʃəve     1
...             ...   ...         ...   ...
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    12
434070         être  ii3S         ɛtɛ    80
434134       étaler  ii3S       ɛtalɛ     1
434762     éteindre   inf      ɛtɛ̃dʁ     3
434768     éteindre  pi1S        ɛtɛ̃     1
434773     éteindre  pi3S        ɛtɛ̃     1
434831      étendre  ppMS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     2
435085    étinceler  pi3S     ɛtɛ̃sɛl     1
435172         être  ii1P       ɛtjɔ̃     1
435232       étirer  ai3S       ɛtiʁa     1
435293       étirer  ppMS       ɛtiʁe     1
435417      étonner  ai3S       ɛtɔna     1
435425      étonner    pP      ɛtɔnɑ̃     1
435457      étonner  pi2S        ɛtɔn     1
435471      étonner  ppMS       ɛtɔne     1
436184      étudier  ii1S      ɛtydjɛ     1
436186      étudier  ii3S      ɛtydjɛ     1
436316         être  ppMS         ɛte    23
436453       évader  pi3S        ɛvad     1
436499      évaluer  ii3S      ɛvalyɛ     1
436820     éveiller  ii3S       ɛvɛjɛ     1
436867     éveiller  ppMS       ɛvɛje     1
437284       éviter  ii3S       ɛvitɛ     1
437295       éviter  pi3S        ɛvit     1
437329       éviter  ppFS       ɛvite     2
437413      évoquer  ii3P       ɛvɔkɛ     1
437474         être  pi2P          ɛt    11
437476         être   inf         ɛtʁ    21

[1988 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.4 s, total: 1min 40s
Wall time: 30.2 s

nbChunk 169
4200
1968

             lexeme  case     phono  tir1
40            avoir  pi3S         a    77
73         abaisser   inf     abɛse     1
125      abandonner  pi1S   abɑ̃dɔn     1
299         abattre   inf     abatʁ     1
574        abhorrer  ii3S     abɔʁɛ     1
1116        abonner  ppMP     abɔne     1
1415        aboutir  ii3S   abutisɛ     1
1425        aboutir  pi3P    abutis     1
2371         abuser  ppMS     abyze     1
2594         abîmer  pi2S      abim     1
2610         abîmer  ppMS     abime     1
2971       accepter   inf   aksɛpte     1
3003       accepter  ppMS   aksɛpte     1
3176     acclimater   inf  aklimate     1
3380    accompagner  ai3S  akɔ̃paɲa     1
3382    accompagner  ii3P  akɔ̃paɲɛ     1
3406    accompagner   inf  akɔ̃paɲe     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3434    accompagner  ppFS  akɔ̃paɲe     1
3438      accomplir  ppMS   akɔ̃pli     2
3536       accorder   inf    akɔʁde     1
3827      accoucher   inf     akuʃe     1
4090       accourir  pi3S      akuʁ     1
4322      accroupir  ppFP    akʁupi     1
4637      accumuler  ii3S   akymylɛ     1
4718        accuser  pi3P      akyz     1
4783        accéder   inf    aksɛde     1
5119        acheter   inf     aʃəte     2
5136        acheter  ppMS     aʃəte     2
5313        acheter  pi3P      aʃɛt     1
...             ...   ...       ...   ...
430156     épaissir  ppFS     ɛpɛsi     1
432160      épouser   inf     ɛpuze     1
432638      épuiser  ii3S    ɛpɥizɛ     1
432689      épuiser  ppMS    ɛpɥize     2
433618       ériger  ppFS     ɛʁiʒe     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    15
434070         être  ii3S       ɛtɛ    70
434147       étaler  pi3S      ɛtal     1
434756     éteindre  fi1S   ɛtɛ̃dʁɛ     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
434782      étendre  pi3S      ɛtɑ̃     1
434821      étendre   inf    ɛtɑ̃dʁ     1
434831      étendre  ppMS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     1
435295       étirer  ppFP     ɛtiʁe     1
435450      étonner  pc3S   ɛtɔnəʁɛ     1
435486     étouffer    pP    ɛtufɑ̃     1
435497     étouffer  pi1S      ɛtuf     1
436205      étudier   inf    ɛtydje     2
436316         être  ppMS       ɛte    22
436835     éveiller   inf     ɛvɛje     3
436869     éveiller  ppFS     ɛvɛje     1
437273       éviter  ai3S     ɛvita     1
437301       éviter   inf     ɛvite     2
437353      évoluer    pP   ɛvɔlyɑ̃     1
437429      évoquer  pi3P      ɛvɔk     1
437458      évoquer  ppMS     ɛvɔke     1
437474         être  pi2P        ɛt    21
437476         être   inf       ɛtʁ    10

[1968 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22 s, total: 1min 38s
Wall time: 29.6 s

nbChunk 170
4200
1942

            lexeme  case     phono  tir1
40           avoir  pi3S         a    71
125     abandonner  pi1S   abɑ̃dɔn     2
132     abandonner   inf  abɑ̃dɔne     1
160     abandonner  is3S  abɑ̃dɔna     1
890         abolir   inf    abɔliʁ     1
1147       aborder   inf    abɔʁde     1
1884       abréger   inf    abʁɛʒe     1
2143      abstenir   inf  abstəniʁ     1
2581        abîmer   inf     abime     1
2950      accepter  ii3S   aksɛptɛ     1
2971      accepter   inf   aksɛpte     2
3003      accepter  ppMS   aksɛpte     1
3443     accomplir   inf  akɔ̃pliʁ     1
4255     accrocher  pi3S     akʁɔʃ     1
4294     accrocher  ppMP    akʁɔʃe     1
4493    accueillir  fi2P   akəjəʁe     1
4716       accuser  pi3S      akyz     1
4750       accuser  ppFS     akyze     1
4783       accéder   inf    aksɛde     1
5119       acheter   inf     aʃəte     3
5136       acheter  ppMS     aʃəte     2
5137       acheter  ppFS     aʃəte     1
5140       achever  ai3S     aʃəva     1
5171       achever  ppMS     aʃəve     1
5321       acheter  fi2S   aʃɛtəʁa     1
6067       activer  pi3S     aktiv     1
7023       admirer  ppMS    admiʁe     1
7297        adorer  ii3S     adɔʁɛ     3
7332        adorer  pi2P     adɔʁe     1
7343        adorer  ppMS     adɔʁe     1
...            ...   ...       ...   ...
427920      élever  pi1S      ɛlɛv     1
427923      élever  pi3S      ɛlɛv     1
430590    épargner  ppMS    ɛpaʁɲe     1
432303     épouser  ppFS     ɛpuze     1
432537    éprouver  ii3S    ɛpʁuvɛ     2
432640     épuiser    pP   ɛpɥizɑ̃     1
433916     établir  ppFP    ɛtabli     1
433922     établir   inf   ɛtabliʁ     1
434048        être  ii3P       ɛtɛ     2
434068        être  ii1S       ɛtɛ    13
434070        être  ii3S       ɛtɛ    74
434134      étaler  ii3S     ɛtalɛ     2
434747    éteindre  ai3S     ɛtɛɲi     1
434755    éteindre  fi3S   ɛtɛ̃dʁa     1
434762    éteindre   inf    ɛtɛ̃dʁ     1
434773    éteindre  pi3S      ɛtɛ̃     1
434775    éteindre  ppFS     ɛtɛ̃t     1
435054        être  ii2P      ɛtje     2
435172        être  ii1P     ɛtjɔ̃     1
435244      étirer    pP    ɛtiʁɑ̃     1
435438     étonner  pi3S      ɛtɔn     1
436316        être  ppMS       ɛte    22
436490     évaluer  ai3S    ɛvalya     1
436629    évanouir  ppFS    ɛvanui     1
436632    évanouir   inf   ɛvanuiʁ     1
436835    éveiller   inf     ɛvɛje     1
437301      éviter   inf     ɛvite     2
437474        être  pi2P        ɛt    22
437476        être   inf       ɛtʁ    21
437508        ôter  pi3S        ot     1

[1942 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.7 s, total: 1min 36s
Wall time: 29.1 s

nbChunk 171
4200
1901

             lexeme  case     phono  tir1
40            avoir  pi3S         a   105
132      abandonner   inf  abɑ̃dɔne     2
164      abandonner  ppMS  abɑ̃dɔne     1
166      abandonner  ppFS  abɑ̃dɔne     1
170      abandonner  ppMP  abɑ̃dɔne     1
980         abonder  pi3S     abɔ̃d     2
1555       abreuver    pP   abʁəvɑ̃     1
1673        abriter  ii3S    abʁitɛ     1
2070       absorber   inf   absɔʁbe     2
2335         abuser  pi3S      abyz     1
2964       accepter  pi1S    aksɛpt     1
2971       accepter   inf   aksɛpte     1
2988       accepter  pI2P   aksɛpte     1
3406    accompagner   inf  akɔ̃paɲe     1
3433    accompagner  ppMS  akɔ̃paɲe     2
3434    accompagner  ppFS  akɔ̃paɲe     1
3438      accomplir  ppMS   akɔ̃pli     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4280      accrocher  pi2P    akʁɔʃe     1
4291      accrocher  ppMS    akʁɔʃe     1
4292      accrocher  ppFS    akʁɔʃe     1
4293      accrocher  ppFP    akʁɔʃe     1
4294      accrocher  ppMP    akʁɔʃe     2
4470     accueillir  ii3P     akəjɛ     1
4509     accueillir   inf    akəjiʁ     1
4688        accuser  ai3S     akyza     1
4748        accuser  ppMS     akyze     1
5119        acheter   inf     aʃəte     1
5137        acheter  ppFS     aʃəte     1
5157        achever   inf     aʃəve     1
...             ...   ...       ...   ...
432160      épouser   inf     ɛpuze     3
432482     éprendre    pP   ɛpʁənɑ̃     1
432537     éprouver  ii3S    ɛpʁuvɛ     2
432556     éprouver   inf    ɛpʁuve     1
432560     éprouver  pc1S  ɛpʁuvəʁɛ     1
433170      équiper  ppFS     ɛkipe     1
433912      établir  ppMS    ɛtabli     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    16
434070         être  ii3S       ɛtɛ    89
434772     éteindre  ppMS      ɛtɛ̃     1
434773     éteindre  pi3S      ɛtɛ̃     2
434819      étendre  pc3S   ɛtɑ̃dʁɛ     1
434831      étendre  ppMS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     2
435232       étirer  ai3S     ɛtiʁa     1
435244       étirer    pP    ɛtiʁɑ̃     1
435435      étonner  pi1S      ɛtɔn     1
435471      étonner  ppMS     ɛtɔne     1
435484     étouffer  ii3S     ɛtufɛ     1
435500     étouffer  pi3S      ɛtuf     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    19
436871     éveiller  ppFP     ɛvɛje     2
437301       éviter   inf     ɛvite     2
437347      évoluer  ai3S    ɛvɔlya     1
437474         être  pi2P        ɛt    13
437476         être   inf       ɛtʁ    24
437512         ôter   inf       ɔte     1

[1901 rows x 4 columns]

0
CPU times: user 1min 5s, sys: 14 s, total: 1min 19s
Wall time: 35.1 s

nbChunk 172
4200
1950

             lexeme  case       phono  tir1
40            avoir  pi3S           a   103
45         abaisser  ai3S       abɛsa     1
132      abandonner   inf    abɑ̃dɔne     1
166      abandonner  ppFS    abɑ̃dɔne     1
1457         aboyer  ii3P      abwajɛ     1
2939       accepter  ai3S     aksɛpta     1
2948       accepter  ii1S     aksɛptɛ     1
2967       accepter  pi3S      aksɛpt     3
2983       accepter  fi3P  aksɛptəʁɔ̃     1
2989       accepter  pi2P     aksɛpte     1
3397    accompagner  pi1S     akɔ̃paɲ     2
3400    accompagner  pi3S     akɔ̃paɲ     1
3422    accompagner  pi2P    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
3527       accorder  pi1S       akɔʁd     1
3530       accorder  pi3S       akɔʁd     1
3564       accorder  pi1P     akɔʁdɔ̃     1
3640       accoster  ii3S      akɔstɛ     1
4322      accroupir  ppFP      akʁupi     1
4339      accroupir  pi1S      akʁupi     1
5041       acharner  ppMS      aʃaʁne     1
5119        acheter   inf       aʃəte     3
5125        acheter  pi2P       aʃəte     2
5136        acheter  ppMS       aʃəte     2
5149        achever  ii3S       aʃəvɛ     1
5157        achever   inf       aʃəve     1
5787     acquiescer  ai3S      akjɛsa     1
5997      actionner  ii3S     aksjɔnɛ     1
6111        activer  ppMP      aktive     1
6876       admettre  pI2P      admɛte     1
...             ...   ...         ...   ...
432160      épouser   inf       ɛpuze     3
432168      épouser  fi2P     ɛpuzəʁe     1
432519     éprendre  ppMS        ɛpʁi     1
432535     éprouver  ii1S      ɛpʁuvɛ     2
433571       ériger  pi3S        ɛʁiʒ     1
433912      établir  ppMS      ɛtabli     1
433916      établir  ppFP      ɛtabli     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    73
434753     éteindre  is3S       ɛtɛɲi     1
434772     éteindre  ppMS        ɛtɛ̃     1
434779     éteindre  ppMP        ɛtɛ̃     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     1
435422      étonner  ii3S       ɛtɔnɛ     1
435438      étonner  pi3S        ɛtɔn     2
435444      étonner   inf       ɛtɔne     1
436316         être  ppMS         ɛte    14
436402      évacuer   inf      ɛvakye     1
436627     évanouir  ppMS      ɛvanui     1
436815     éveiller  ai3S       ɛvɛja     1
436831     éveiller  pi3S        ɛvɛj     1
436835     éveiller   inf       ɛvɛje     1
437295       éviter  pi3S        ɛvit     1
437301       éviter   inf       ɛvite     1
437427      évoquer  pi3S        ɛvɔk     1
437474         être  pi2P          ɛt    11
437476         être   inf         ɛtʁ    18

[1950 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.1 s, total: 1min 39s
Wall time: 30.3 s

nbChunk 173
4200
1965

             lexeme  case     phono  tir1
40            avoir  pi3S         a   103
125      abandonner  pi1S   abɑ̃dɔn     1
1867        abréger  ai3S    abʁɛʒa     1
2562         abîmer  ii3P     abimɛ     1
2771      accaparer  ii3P   akapaʁɛ     1
2964       accepter  pi1S    aksɛpt     1
2967       accepter  pi3S    aksɛpt     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3419    accompagner  pi2S   akɔ̃paɲ     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3434    accompagner  ppFS  akɔ̃paɲe     1
3443      accomplir   inf  akɔ̃pliʁ     1
3821      accoucher  pi3S      akuʃ     1
3863       accouder  ai1S     akudɛ     1
4072       accourir   inf    akuʁiʁ     1
4234      accrocher  ii3P    akʁɔʃɛ     1
4257      accrocher  pi3P     akʁɔʃ     1
4369      accroupir  pi3S    akʁupi     1
4381      accroître   inf   akʁwatʁ     1
4509     accueillir   inf    akəjiʁ     1
5041       acharner  ppMS    aʃaʁne     1
5044       acharner  ppMP    aʃaʁne     1
5119        acheter   inf     aʃəte     5
5135        acheter  ai3P    aʃətɛʁ     1
5136        acheter  ppMS     aʃəte     3
5332        achever  pi3S      aʃɛv     1
5806       acquérir  ppMP       aki     1
5905       acquérir   inf    akɛʁiʁ     1
6988        admirer  pi1S     admiʁ     1
6991        admirer  pi3S     admiʁ     1
...             ...   ...       ...   ...
429367     émouvoir  ppFS       ɛmy     1
429840      énoncer    pP   ɛnɔ̃sɑ̃     1
430614   éparpiller  pi3P   ɛpaʁpij     1
432160      épouser   inf     ɛpuze     1
432167      épouser  fi2S   ɛpuzəʁa     1
432535     éprouver  ii1S    ɛpʁuvɛ     1
432556     éprouver   inf    ɛpʁuve     1
433553     éreinter  ppMS    ɛʁɛ̃te     1
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ    13
434070         être  ii3S       ɛtɛ    67
434451     étancher   inf    ɛtɑ̃ʃe     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
434763     éteindre  fi2P   ɛtɛ̃dʁe     1
434767     éteindre  fi3P  ɛtɛ̃dʁɔ̃     1
434788      étendre  ii3S    ɛtɑ̃dɛ     1
434821      étendre   inf    ɛtɑ̃dʁ     1
435172         être  ii1P     ɛtjɔ̃     2
435457      étonner  pi2S      ɛtɔn     1
435500     étouffer  pi3S      ɛtuf     1
435681     étourdir  ii3P  ɛtuʁdisɛ     1
436316         être  ppMS       ɛte    24
436395      évacuer  pi1S     ɛvaky     1
436815     éveiller  ai3S     ɛvɛja     1
436873     éveiller  ppMP     ɛvɛje     1
437284       éviter  ii3S     ɛvitɛ     1
437417      évoquer    pP    ɛvɔkɑ̃     1
437459      évoquer  ppFS     ɛvɔke     1
437474         être  pi2P        ɛt    14
437476         être   inf       ɛtʁ    21

[1965 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.3 s, total: 1min 39s
Wall time: 30 s

nbChunk 174
4200
1971

             lexeme  case     phono  tir1
40            avoir  pi3S         a    83
108      abandonner  ai3S  abɑ̃dɔna     1
113      abandonner  ii3S  abɑ̃dɔnɛ     1
164      abandonner  ppMS  abɑ̃dɔne     1
250         abattre  pi1S       aba     1
1121        aborder  ai3S    abɔʁda     1
1147        aborder   inf    abɔʁde     1
1796        abrutir  ppMS    abʁyti     1
2616         abîmer  ppMP     abime     1
2971       accepter   inf   aksɛpte     1
2989       accepter  pi2P   aksɛpte     2
3176     acclimater   inf  aklimate     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     2
3422    accompagner  pi2P  akɔ̃paɲe     1
3434    accompagner  ppFS  akɔ̃paɲe     1
3438      accomplir  ppMS   akɔ̃pli     1
3865       accouder  ii1S     akudɛ     1
4259      accrocher   inf    akʁɔʃe     1
4503     accueillir  ppFS     akəji     1
4509     accueillir   inf    akəjiʁ     1
4519     accueillir  ai3S     akəji     1
4637      accumuler  ii3S   akymylɛ     1
4748        accuser  ppMS     akyze     1
4783        accéder   inf    aksɛde     1
4823      accélérer  ii3S  aksɛlɛʁɛ     1
5097      acheminer  ppMS   aʃəmine     1
5119        acheter   inf     aʃəte     1
5308        acheter  pi1S      aʃɛt     1
5315        acheter  fi3S   aʃɛtəʁa     1
...             ...   ...       ...   ...
429672      énerver  ai3S    ɛnɛʁva     1
429691      énerver  pi1S     ɛnɛʁv     1
431065        épier    pP     ɛpjɑ̃     1
431973      éponger  ai3S    ɛpɔ̃ʒa     1
432160      épouser   inf     ɛpuze     2
432173      épouser  pi2S      ɛpuz     1
432302      épouser  ppMS     ɛpuze     1
432532     éprouver  ai3S    ɛpʁuva     1
432537     éprouver  ii3S    ɛpʁuvɛ     1
434068         être  ii1S       ɛtɛ    12
434070         être  ii3S       ɛtɛ    79
434131       étaler  ii3P     ɛtalɛ     1
434134       étaler  ii3S     ɛtalɛ     1
434147       étaler  pi3S      ɛtal     1
434770     éteindre  pi2S      ɛtɛ̃     1
434782      étendre  pi3S      ɛtɑ̃     1
435172         être  ii1P     ɛtjɔ̃     3
435417      étonner  ai3S     ɛtɔna     1
435538     étouffer  ppMS     ɛtufe     1
436205      étudier   inf    ɛtydje     1
436227      étudier  pi1P   ɛtydjɔ̃     1
436233      étudier  ppMS    ɛtydje     2
436316         être  ppMS       ɛte    30
436679     évanouir  pi3S    ɛvanui     1
436688     évaporer  ii3S   ɛvapɔʁɛ     1
437301       éviter   inf     ɛvite     1
437424      évoquer  pi1S      ɛvɔk     1
437461      évoquer  ppMP     ɛvɔke     1
437474         être  pi2P        ɛt    18
437476         être   inf       ɛtʁ    15

[1971 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.2 s, total: 1min 39s
Wall time: 30.1 s

nbChunk 175
4200
1955

             lexeme  case     phono  tir1
40            avoir  pi3S         a    75
132      abandonner   inf  abɑ̃dɔne     1
258         abattre  ii3S     abatɛ     1
1160        aborder  pi2S     abɔʁd     1
1688        abriter   inf    abʁite     1
1694        abriter  pc3S  abʁitəʁɛ     1
2971       accepter   inf   aksɛpte     1
3003       accepter  ppMS   aksɛpte     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3419    accompagner  pi2S   akɔ̃paɲ     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3536       accorder   inf    akɔʁde     1
3827      accoucher   inf     akuʃe     1
4230      accrocher  ai3S    akʁɔʃa     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4259      accrocher   inf    akʁɔʃe     1
4293      accrocher  ppFP    akʁɔʃe     1
4294      accrocher  ppMP    akʁɔʃe     1
4381      accroître   inf   akʁwatʁ     1
4519     accueillir  ai3S     akəji     1
4654      accumuler  pi3P    akymyl     1
4720        accuser   inf     akyze     1
4724        accuser  pc1S   akyzəʁɛ     1
4748        accuser  ppMS     akyze     1
5008       acharner  pi3S     aʃaʁn     1
5041       acharner  ppMS    aʃaʁne     1
5070      acheminer   inf   aʃəmine     1
5119        acheter   inf     aʃəte     2
5124        acheter  pI2P     aʃəte     1
5136        acheter  ppMS     aʃəte     1
...             ...   ...       ...   ...
432552     éprouver  pi3S     ɛpʁuv     1
433912      établir  ppMS    ɛtabli     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    16
434070         être  ii3S       ɛtɛ    65
434299       étaler  ppMS     ɛtale     1
434726     éteindre  ii3S     ɛtɛɲɛ     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
434788      étendre  ii3S    ɛtɑ̃dɛ     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     1
435244       étirer    pP    ɛtiʁɑ̃     1
435254       étirer  pi3S      ɛtiʁ     2
435417      étonner  ai3S     ɛtɔna     1
435418      étonner  ai1S     ɛtɔnɛ     1
435438      étonner  pi3S      ɛtɔn     1
435444      étonner   inf     ɛtɔne     1
435519     étouffer  pi2S      ɛtuf     1
435794    étreindre  ii3S    ɛtʁɛɲɛ     1
436188      étudier    pP   ɛtydjɑ̃     1
436201      étudier  pi3S     ɛtydi     3
436316         être  ppMS       ɛte    23
436518      évaluer  pi3P     ɛvaly     1
436629     évanouir  ppFS    ɛvanui     1
436820     éveiller  ii3S     ɛvɛjɛ     1
436869     éveiller  ppFS     ɛvɛje     1
437474         être  pi2P        ɛt    17
437476         être   inf       ɛtʁ    22
437492         ôter  ai3S       ɔta     1
437512         ôter   inf       ɔte     1

[1955 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22 s, total: 1min 37s
Wall time: 29.6 s

nbChunk 176
4200
1921

             lexeme  case       phono  tir1
40            avoir  pi3S           a    74
132      abandonner   inf    abɑ̃dɔne     1
134      abandonner  fi1S  abɑ̃dɔnəʁɛ     1
145      abandonner  pi2S     abɑ̃dɔn     1
305         abattre  ppMS       abaty     1
313         abattre  ppMP       abaty     1
2042       absorber  ai3S     absɔʁba     1
2051       absorber  ii3S     absɔʁbɛ     1
2102       absorber  ppFS     absɔʁbe     1
2267      abstraire   inf     abstʁɛʁ     1
2948       accepter  ii1S     aksɛptɛ     1
2967       accepter  pi3S      aksɛpt     2
2969       accepter  pi3P      aksɛpt     1
3003       accepter  ppMS     aksɛpte     1
3110       acclamer  pi1S       aklam     1
3144       acclamer  ppMS      aklame     1
3347     accommoder  pi3P      akɔmɔd     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3519       accorder  ii3S      akɔʁdɛ     1
4259      accrocher   inf      akʁɔʃe     3
4280      accrocher  pi2P      akʁɔʃe     1
4294      accrocher  ppMP      akʁɔʃe     1
4634      accumuler  ii3P     akymylɛ     1
4783        accéder   inf      aksɛde     1
5008       acharner  pi3S       aʃaʁn     1
5119        acheter   inf       aʃəte     3
5125        acheter  pi2P       aʃəte     1
5136        acheter  ppMS       aʃəte     2
5758     acquiescer  pi3S       akjɛs     1
6414        adapter   inf      adapte     1
...             ...   ...         ...   ...
429694      énerver  pi3S       ɛnɛʁv     1
429713      énerver  pi2S       ɛnɛʁv     1
431271       épiler   inf       ɛpile     1
432156      épouser  pi3S        ɛpuz     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
432556     éprouver   inf      ɛpʁuve     1
432582     éprouver  is3S      ɛpʁuva     1
432689      épuiser  ppMS      ɛpɥize     1
433939      établir  pi1S      ɛtabli     1
434048         être  ii3P         ɛtɛ     7
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    78
434762     éteindre   inf      ɛtɛ̃dʁ     1
434839      étendre  ppMP      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     4
435059    étinceler  ii3P    ɛtɛ̃səlɛ     1
435172         être  ii1P       ɛtjɔ̃     1
435296       étirer  ppMP       ɛtiʁe     1
435417      étonner  ai3S       ɛtɔna     1
435780    étrangler  ppMS    ɛtʁɑ̃gle     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    28
436487       évader  ppMP       ɛvade     1
436821     éveiller    pP      ɛvɛjɑ̃     1
436835     éveiller   inf       ɛvɛje     1
437292       éviter  pi1S        ɛvit     1
437301       éviter   inf       ɛvite     2
437416      évoquer  ii3S       ɛvɔkɛ     1
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    24

[1921 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.4 s, total: 1min 38s
Wall time: 30 s

nbChunk 177
4200
1955

             lexeme  case       phono  tir1
40            avoir  pi3S           a    98
128      abandonner  pi3S     abɑ̃dɔn     2
132      abandonner   inf    abɑ̃dɔne     1
145      abandonner  pi2S     abɑ̃dɔn     1
158      abandonner  pi1P   abɑ̃dɔnɔ̃     1
164      abandonner  ppMS    abɑ̃dɔne     2
1307        abouler  pi3S        abul     1
1440        aboutir  pi3S       abuti     1
2967       accepter  pi3S      aksɛpt     1
2989       accepter  pi2P     aksɛpte     1
3003       accepter  ppMS     aksɛpte     3
3397    accompagner  pi1S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     1
3408    accompagner  fi1S  akɔ̃paɲəʁɛ     1
3523       accorder  is3P     akɔʁdas     1
3536       accorder   inf      akɔʁde     1
4090       accourir  pi3S        akuʁ     1
4230      accrocher  ai3S      akʁɔʃa     1
4252      accrocher  pi1S       akʁɔʃ     1
4502     accueillir  ppMS       akəji     1
4511     accueillir  ppMP       akəji     1
4720        accuser   inf       akyze     1
5112        acheter    pP      aʃətɑ̃     1
5119        acheter   inf       aʃəte     1
5137        acheter  ppFS       aʃəte     1
5140        achever  ai3S       aʃəva     1
5311        acheter  pi3S        aʃɛt     1
5787     acquiescer  ai3S      akjɛsa     1
5835      acquitter  ii3S       akitɛ     1
6109        activer  ppFS      aktive     1
...             ...   ...         ...   ...
429672      énerver  ai3S      ɛnɛʁva     1
429713      énerver  pi2S       ɛnɛʁv     1
431992      éponger   inf      ɛpɔ̃ʒe     1
433022   équilibrer  pi3S     ɛkilibʁ     1
433777      éructer  ii3S      ɛʁyktɛ     1
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ     9
434070         être  ii3S         ɛtɛ    67
434131       étaler  ii3P       ɛtalɛ     1
434144       étaler  pi1S        ɛtal     1
434730     éteindre  pi3P        ɛtɛɲ     1
434739     éteindre  ai3P      ɛtɛɲiʁ     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434775     éteindre  ppFS       ɛtɛ̃t     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
435054         être  ii2P        ɛtje     3
435172         être  ii1P       ɛtjɔ̃     3
435471      étonner  ppMS       ɛtɔne     1
435506     étouffer   inf       ɛtufe     1
435780    étrangler  ppMS    ɛtʁɑ̃gle     1
435838    étreindre  pi3S       ɛtʁɛ̃     1
436205      étudier   inf      ɛtydje     2
436316         être  ppMS         ɛte    19
436627     évanouir  ppMS      ɛvanui     1
436835     éveiller   inf       ɛvɛje     1
437474         être  pi2P          ɛt    17
437476         être   inf         ɛtʁ    25
437493         ôter  ai1S         ɔtɛ     1
437512         ôter   inf         ɔte     1
437539         ôter  ppMS         ɔte     1

[1955 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.8 s, total: 1min 37s
Wall time: 30 s

nbChunk 178
4200
1933

             lexeme  case      phono  tir1
40            avoir  pi3S          a    83
129      abandonner  ps3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     1
313         abattre  ppMP      abaty     1
616        abhorrer  ppMS      abɔʁe     1
869          aboyer  pi3P       abwa     1
890          abolir   inf     abɔliʁ     1
1145        aborder  pi3P      abɔʁd     1
1688        abriter   inf     abʁite     1
2366         abuser  pi1P     abyzɔ̃     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     1
2978       accepter  fi2S  aksɛptəʁa     1
3003       accepter  ppMS    aksɛpte     1
3382    accompagner  ii3P   akɔ̃paɲɛ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3436    accompagner  ppMP   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
3530       accorder  pi3S      akɔʁd     1
3536       accorder   inf     akɔʁde     2
4238      accrocher    pP    akʁɔʃɑ̃     1
4721        accuser  fi3S    akyzəʁa     1
4733        accuser  pi2S       akyz     1
4748        accuser  ppMS      akyze     1
4783        accéder   inf     aksɛde     1
4820      accélérer  ii3P   aksɛlɛʁɛ     1
4823      accélérer  ii3S   aksɛlɛʁɛ     1
5119        acheter   inf      aʃəte     2
...             ...   ...        ...   ...
432739       épurer   inf      ɛpyʁe     1
433912      établir  ppMS     ɛtabli     2
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ    13
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    63
434488         être    pP       ɛtɑ̃     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434833      étendre  ppFS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     1
435417      étonner  ai3S      ɛtɔna     1
435438      étonner  pi3S       ɛtɔn     1
435439      étonner  ps3S       ɛtɔn     1
435444      étonner   inf      ɛtɔne     3
435542     étouffer  ppFP      ɛtufe     1
435544     étouffer  ppMP      ɛtufe     1
436203      étudier  pi3P      ɛtydi     1
436316         être  ppMS        ɛte    20
436548      évaluer  ppFS     ɛvalye     1
436820     éveiller  ii3S      ɛvɛjɛ     1
437043      éventer  ppMP     ɛvɑ̃te     1
437285       éviter    pP     ɛvitɑ̃     1
437295       éviter  pi3S       ɛvit     2
437323       éviter  pi1P     ɛvitɔ̃     1
437416      évoquer  ii3S      ɛvɔkɛ     1
437417      évoquer    pP     ɛvɔkɑ̃     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    17
437498         ôter    pP       ɔtɑ̃     1

[1933 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.9 s, total: 1min 37s
Wall time: 30.1 s

nbChunk 179
4200
1949

             lexeme  case      phono  tir1
40            avoir  pi3S          a   104
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
416        abdiquer   inf     abdike     1
1163        aborder  pi2P     abɔʁde     1
1468         aboyer   inf     abwaje     1
1673        abriter  ii3S     abʁitɛ     1
1907        abréger  ppMS     abʁɛʒe     1
1943       absenter  pi1S     absɑ̃t     1
2070       absorber   inf    absɔʁbe     1
2324         abuser  ii3S      abyzɛ     1
2374         abuser  ppMP      abyze     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     1
3003       accepter  ppMS    aksɛpte     1
3322     accommoder  ii3S    akɔmɔdɛ     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     2
3434    accompagner  ppFS   akɔ̃paɲe     2
3536       accorder   inf     akɔʁde     1
3544       accorder  fi2P   akɔʁdəʁe     1
3549       accorder  pi2S      akɔʁd     1
3858      accoucher  ppMS      akuʃe     1
4486     accueillir  fi3S    akəjəʁa     1
4502     accueillir  ppMS      akəji     1
4684      accumuler  ppFS    akymyle     1
5102        acheter  ai3S      aʃəta     1
5111        acheter  ii3S      aʃətɛ     1
5119        acheter   inf      aʃəte     2
5136        acheter  ppMS      aʃəte     2
...             ...   ...        ...   ...
432160      épouser   inf      ɛpuze     1
432169      épouser  pc2P   ɛpuzəʁje     1
432173      épouser  pi2S       ɛpuz     1
432586     éprouver  ppMS     ɛpʁuve     2
432689      épuiser  ppMS     ɛpɥize     2
433571       ériger  pi3S       ɛʁiʒ     1
433912      établir  ppMS     ɛtabli     1
433914      établir  ppFS     ɛtabli     1
433947      établir    pP  ɛtablisɑ̃     1
433967      établir  pi1P  ɛtablisɔ̃     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ    14
434070         être  ii3S        ɛtɛ    84
434131       étaler  ii3P      ɛtalɛ     1
434147       étaler  pi3S       ɛtal     1
434730     éteindre  pi3P       ɛtɛɲ     1
434755     éteindre  fi3S    ɛtɛ̃dʁa     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     4
436218      étudier  pi2S      ɛtydi     1
436221      étudier  pi2P     ɛtydje     1
436316         être  ppMS        ɛte    17
436381      évacuer  ii3S     ɛvakyɛ     1
436654     évanouir  ii1S   ɛvanuisɛ     1
436815     éveiller  ai3S      ɛvɛja     1
437285       éviter    pP     ɛvitɑ̃     1
437365      évoluer  pi3P      ɛvɔly     1
437474         être  pi2P         ɛt    10
437476         être   inf        ɛtʁ    23

[1949 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.5 s, total: 1min 35s
Wall time: 29.9 s

nbChunk 180
4200
1941

             lexeme  case     phono  tir1
40            avoir  pi3S         a    85
132      abandonner   inf  abɑ̃dɔne     2
164      abandonner  ppMS  abɑ̃dɔne     3
299         abattre   inf     abatʁ     1
305         abattre  ppMS     abaty     1
1169        aborder  pi1P   abɔʁdɔ̃     1
1393        aboutir   inf    abutiʁ     1
1412        aboutir  ii3P   abutisɛ     1
2971       accepter   inf   aksɛpte     2
3003       accepter  ppMS   aksɛpte     1
3404    accompagner  pi3P   akɔ̃paɲ     2
3436    accompagner  ppMP  akɔ̃paɲe     1
3571       accorder  ppMS    akɔʁde     1
4255      accrocher  pi3S     akʁɔʃ     1
4259      accrocher   inf    akʁɔʃe     1
4294      accrocher  ppMP    akʁɔʃe     1
4303      accroître  ii3S   akʁwasɛ     1
4381      accroître   inf   akʁwatʁ     1
4509     accueillir   inf    akəjiʁ     1
4519     accueillir  ai3S     akəji     1
5119        acheter   inf     aʃəte     4
5136        acheter  ppMS     aʃəte     4
5146        achever  ii3P     aʃəvɛ     1
5157        achever   inf     aʃəve     1
5754       acquérir  pi3S     akjɛʁ     1
6553        adhérer   inf     adɛʁe     1
6967        admirer  ii1S    admiʁɛ     1
7028       admettre  ppMS      admi     1
7250        adopter   inf    adɔpte     2
7312         adorer  pi3S      adɔʁ     1
...             ...   ...       ...   ...
432158      épouser  pi3P      ɛpuz     1
432160      épouser   inf     ɛpuze     2
432239   épousseter  ppMS   ɛpusəte     1
432302      épouser  ppMS     ɛpuze     1
432369   épouvanter  ii3P  ɛpuvɑ̃tɛ     1
432691      épuiser  ppFS    ɛpɥize     1
433169      équiper  ppMS     ɛkipe     1
433912      établir  ppMS    ɛtabli     1
433922      établir   inf   ɛtabliʁ     3
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ     7
434070         être  ii3S       ɛtɛ    68
434131       étaler  ii3P     ɛtalɛ     1
434134       étaler  ii3S     ɛtalɛ     1
434772     éteindre  ppMS      ɛtɛ̃     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     2
435251       étirer  pi1S      ɛtiʁ     1
435438      étonner  pi3S      ɛtɔn     2
435484     étouffer  ii3S     ɛtufɛ     1
435506     étouffer   inf     ɛtufe     1
435517     étouffer  fi1P  ɛtufəʁɔ̃     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    13
436499      évaluer  ii3S    ɛvalyɛ     1
436842     éveiller  fi2S   ɛvɛjəʁa     1
436867     éveiller  ppMS     ɛvɛje     1
437301       éviter   inf     ɛvite     2
437474         être  pi2P        ɛt    15
437476         être   inf       ɛtʁ    23

[1941 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.1 s, total: 1min 37s
Wall time: 29.8 s

nbChunk 181
4200
1960

             lexeme  case     phono  tir1
40            avoir  pi3S         a    89
108      abandonner  ai3S  abɑ̃dɔna     1
125      abandonner  pi1S   abɑ̃dɔn     1
132      abandonner   inf  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     2
287         abattre  ai3S     abati     1
299         abattre   inf     abatʁ     1
304         abattre  fi3P   abatʁɔ̃     1
1175        aborder  ppMS    abɔʁde     1
1290       aboucher  ppMP     abuʃe     1
2106       absorber  ppMP   absɔʁbe     1
2324         abuser  ii3S     abyzɛ     1
2964       accepter  pi1S    aksɛpt     1
2971       accepter   inf   aksɛpte     1
2984       accepter  pi2S    aksɛpt     1
2989       accepter  pi2P   aksɛpte     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3438      accomplir  ppMS   akɔ̃pli     1
3443      accomplir   inf  akɔ̃pliʁ     1
3519       accorder  ii3S    akɔʁdɛ     1
3629       accoster  ai3S    akɔsta     1
3913       accouder  ppMS     akude     1
4067       accourir  pi2P     akuʁe     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4238      accrocher    pP   akʁɔʃɑ̃     1
4291      accrocher  ppMS    akʁɔʃe     1
4690        accuser  ii3P     akyzɛ     1
4748        accuser  ppMS     akyze     1
4758        accéder  pi3S     aksɛd     1
4809      accélérer  pi1S   aksɛlɛʁ     1
...             ...   ...       ...   ...
432145      épouser    pP    ɛpuzɑ̃     1
432156      épouser  pi3S      ɛpuz     1
432160      épouser   inf     ɛpuze     1
432549     éprouver  pi1S     ɛpʁuv     1
433169      équiper  ppMS     ɛkipe     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ    14
434069         être  ii2S       ɛtɛ     1
434070         être  ii3S       ɛtɛ    68
434488         être    pP      ɛtɑ̃     1
434692       étayer   inf     ɛtɛje     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
434772     éteindre  ppMS      ɛtɛ̃     1
434923     éternuer   inf   ɛtɛʁnye     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     3
435438      étonner  pi3S      ɛtɔn     1
435500     étouffer  pi3S      ɛtuf     1
435504     étouffer  pi3P      ɛtuf     1
435656     étourdir  ppFS    ɛtuʁdi     1
436316         être  ppMS       ɛte    33
436835     éveiller   inf     ɛvɛje     1
437273       éviter  ai3S     ɛvita     1
437285       éviter    pP    ɛvitɑ̃     1
437305       éviter  pc1S   ɛvitəʁɛ     1
437416      évoquer  ii3S     ɛvɔkɛ     1
437417      évoquer    pP    ɛvɔkɑ̃     1
437474         être  pi2P        ɛt    16
437476         être   inf       ɛtʁ    23

[1960 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22 s, total: 1min 37s
Wall time: 30 s

nbChunk 182
4200
1949

             lexeme  case       phono  tir1
40            avoir  pi3S           a    84
128      abandonner  pi3S     abɑ̃dɔn     2
132      abandonner   inf    abɑ̃dɔne     1
148      abandonner  pi2P    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     3
256         abattre  ii1S       abatɛ     1
521         aberrer    pP      abɛʁɑ̃     1
2950       accepter  ii3S     aksɛptɛ     2
2984       accepter  pi2S      aksɛpt     1
2988       accepter  pI2P     aksɛpte     1
3007       accepter  ppFP     aksɛpte     1
3383    accompagner  ii1S    akɔ̃paɲɛ     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
3440      accomplir  ppFS     akɔ̃pli     1
3443      accomplir   inf    akɔ̃pliʁ     1
3468      accomplir    pP  akɔ̃plisɑ̃     1
3542       accorder  pc3S    akɔʁdəʁɛ     1
3556       accorder  pi2P      akɔʁde     1
4279      accrocher  pI2P      akʁɔʃe     1
4291      accrocher  ppMS      akʁɔʃe     1
4381      accroître   inf     akʁwatʁ     1
4716        accuser  pi3S        akyz     1
4720        accuser   inf       akyze     1
4771        accéder  ii3S      aksɛdɛ     1
4783        accéder   inf      aksɛde     1
4835      accélérer   inf    aksɛlɛʁe     1
5119        acheter   inf       aʃəte     1
5124        acheter  pI2P       aʃəte     1
...             ...   ...         ...   ...
432162      épouser  fi1S     ɛpuzəʁɛ     1
432302      épouser  ppMS       ɛpuze     1
432537     éprouver  ii3S      ɛpʁuvɛ     2
432539     éprouver    pP     ɛpʁuvɑ̃     1
432552     éprouver  pi3S       ɛpʁuv     1
432586     éprouver  ppMS      ɛpʁuve     1
433001   équilibrer  ii3P    ɛkilibʁɛ     1
433969      établir  pi3S      ɛtabli     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    11
434070         être  ii3S         ɛtɛ    71
434147       étaler  pi3S        ɛtal     1
434153       étaler   inf       ɛtale     1
435054         être  ii2P        ɛtje     3
435293       étirer  ppMS       ɛtiʁe     1
435435      étonner  pi1S        ɛtɔn     1
435438      étonner  pi3S        ɛtɔn     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435471      étonner  ppMS       ɛtɔne     1
435497     étouffer  pi1S        ɛtuf     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436316         être  ppMS         ɛte    22
436402      évacuer   inf      ɛvakye     1
436815     éveiller  ai3S       ɛvɛja     2
436843     éveiller  fi2P     ɛvɛjəʁe     1
437295       éviter  pi3S        ɛvit     1
437431      évoquer   inf       ɛvɔke     1
437453      évoquer  pi1P      ɛvɔkɔ̃     1
437474         être  pi2P          ɛt    23
437476         être   inf         ɛtʁ    21

[1949 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.4 s, total: 1min 35s
Wall time: 29 s

nbChunk 183
4200
1906

             lexeme  case       phono  tir1
40            avoir  pi3S           a   102
128      abandonner  pi3S     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
162      abandonner  ai3P   abɑ̃dɔnɛʁ     1
305         abattre  ppMS       abaty     1
1112        abonner  ppFS       abɔne     1
2766       accabler  ppMP      akable     1
2939       accepter  ai3S     aksɛpta     1
2964       accepter  pi1S      aksɛpt     1
2971       accepter   inf     aksɛpte     1
3406    accompagner   inf    akɔ̃paɲe     1
3443      accomplir   inf    akɔ̃pliʁ     1
3488      accomplir  pi1P  akɔ̃plisɔ̃     1
3530       accorder  pi3S       akɔʁd     2
3827      accoucher   inf       akuʃe     1
4339      accroupir  pi1S      akʁupi     1
4381      accroître   inf     akʁwatʁ     1
4426     accréditer   inf    akʁɛdite     1
4473     accueillir  ii3S       akəjɛ     1
4637      accumuler  ii3S     akymylɛ     1
4693        accuser  ii3S       akyzɛ     1
4809      accélérer  pi1S     aksɛlɛʁ     1
5042       acharner  ppFS      aʃaʁne     1
5119        acheter   inf       aʃəte     6
5125        acheter  pi2P       aʃəte     1
5136        acheter  ppMS       aʃəte     1
5140        achever  ai3S       aʃəva     1
5149        achever  ii3S       aʃəvɛ     1
6415        adapter  fi3S    adaptəʁa     1
6863       admettre  pi1S        admɛ     2
...             ...   ...         ...   ...
430562     épargner   inf      ɛpaʁɲe     1
432160      épouser   inf       ɛpuze     1
432182      épouser  ii2P      ɛpuzje     1
432552     éprouver  pi3S       ɛpʁuv     1
433916      établir  ppFP      ɛtabli     1
434068         être  ii1S         ɛtɛ    12
434070         être  ii3S         ɛtɛ    74
434692       étayer   inf       ɛtɛje     1
434727     éteindre    pP      ɛtɛɲɑ̃     1
434760     éteindre  pc3S     ɛtɛ̃dʁɛ     1
434773     éteindre  pi3S        ɛtɛ̃     1
434811      étendre  ai3S      ɛtɑ̃di     1
434833      étendre  ppFS      ɛtɑ̃dy     2
435054         être  ii2P        ɛtje     2
435064    étinceler    pP   ɛtɛ̃səlɑ̃     2
435172         être  ii1P       ɛtjɔ̃     2
435425      étonner    pP      ɛtɔnɑ̃     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435474      étonner  ppMP       ɛtɔne     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    16
436835     éveiller   inf       ɛvɛje     1
437273       éviter  ai3S       ɛvita     1
437281       éviter  ii3P       ɛvitɛ     1
437284       éviter  ii3S       ɛvitɛ     2
437292       éviter  pi1S        ɛvit     1
437301       éviter   inf       ɛvite     1
437328       éviter  ppMS       ɛvite     1
437474         être  pi2P          ɛt     7
437476         être   inf         ɛtʁ    19

[1906 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 21.6 s, total: 1min 34s
Wall time: 29 s

nbChunk 184
4200
1910

             lexeme  case       phono  tir1
40            avoir  pi3S           a    88
299         abattre   inf       abatʁ     1
313         abattre  ppMP       abaty     1
887          abolir  ppMS       abɔli     1
914          abolir    pP    abɔlisɑ̃     1
1147        aborder   inf      abɔʁde     1
1393        aboutir   inf      abutiʁ     1
1684        abriter  pi3S       abʁit     1
2948       accepter  ii1S     aksɛptɛ     1
2967       accepter  pi3S      aksɛpt     1
2969       accepter  pi3P      aksɛpt     1
2971       accepter   inf     aksɛpte     2
3003       accepter  ppMS     aksɛpte     2
3005       accepter  ppFS     aksɛpte     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3386    accompagner    pP   akɔ̃paɲɑ̃     2
3406    accompagner   inf    akɔ̃paɲe     3
3434    accompagner  ppFS    akɔ̃paɲe     1
3444      accomplir  fi3S   akɔ̃pliʁa     1
3468      accomplir    pP  akɔ̃plisɑ̃     1
3490      accomplir  pi3S     akɔ̃pli     1
4237      accrocher  ii3S      akʁɔʃɛ     1
4293      accrocher  ppFP      akʁɔʃe     1
4716        accuser  pi3S        akyz     1
4717        accuser  ps3S        akyz     1
4720        accuser   inf       akyze     1
4771        accéder  ii3S      aksɛdɛ     1
5119        acheter   inf       aʃəte     3
5136        acheter  ppMS       aʃəte     2
5171        achever  ppMS       aʃəve     1
...             ...   ...         ...   ...
432138      épouser  ai3S       ɛpuza     1
432160      épouser   inf       ɛpuze     3
432556     éprouver   inf      ɛpʁuve     1
432653      épuiser  pi3S       ɛpɥiz     1
433912      établir  ppMS      ɛtabli     1
434048         être  ii3P         ɛtɛ     6
434068         être  ii1S         ɛtɛ    16
434070         être  ii3S         ɛtɛ    76
434300       étaler  ppFS       ɛtale     1
434488         être    pP        ɛtɑ̃     1
434727     éteindre    pP      ɛtɛɲɑ̃     1
434747     éteindre  ai3S       ɛtɛɲi     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434773     éteindre  pi3S        ɛtɛ̃     1
434782      étendre  pi3S        ɛtɑ̃     1
434917     éternuer  pi3S      ɛtɛʁny     1
435054         être  ii2P        ɛtje     2
435129      étioler  pi3S       ɛtjɔl     1
435172         être  ii1P       ɛtjɔ̃     1
435232       étirer  ai3S       ɛtiʁa     1
435438      étonner  pi3S        ɛtɔn     1
435457      étonner  pi2S        ɛtɔn     1
435544     étouffer  ppMP       ɛtufe     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    18
437301       éviter   inf       ɛvite     2
437349      évoluer  ii3P      ɛvɔlyɛ     1
437474         être  pi2P          ɛt     9
437476         être   inf         ɛtʁ    20
437507         ôter  pI2S          ot     1

[1910 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.7 s, total: 1min 35s
Wall time: 29.3 s

nbChunk 185
4200
1922

             lexeme  case       phono  tir1
40            avoir  pi3S           a    84
113      abandonner  ii3S    abɑ̃dɔnɛ     1
114      abandonner    pP   abɑ̃dɔnɑ̃     1
132      abandonner   inf    abɑ̃dɔne     2
166      abandonner  ppFS    abɑ̃dɔne     1
913          abolir  ii3S     abɔlisɛ     1
1393        aboutir   inf      abutiʁ     1
2739       accabler  pc3P    akabləʁɛ     1
2763       accabler  ppMS      akable     1
2782      accaparer  pi1S      akapaʁ     1
2967       accepter  pi3S      aksɛpt     1
3414    accompagner  fi2P  akɔ̃paɲəʁe     1
3422    accompagner  pi2P    akɔ̃paɲe     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3443      accomplir   inf    akɔ̃pliʁ     1
3460      accomplir  pi1S     akɔ̃pli     1
3884       accouder   inf       akude     1
4210     accoutumer  ppMS     akutyme     1
4280      accrocher  pi2P      akʁɔʃe     1
4387      accroître  ppMS        akʁy     1
4716        accuser  pi3S        akyz     1
4742        accuser  pi1P      akyzɔ̃     1
4748        accuser  ppMS       akyze     1
4750        accuser  ppFS       akyze     1
4783        accéder   inf      aksɛde     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     1
5140        achever  ai3S       aʃəva     1
5146        achever  ii3P       aʃəvɛ     1
5147        achever  ii1S       aʃəvɛ     1
...             ...   ...         ...   ...
430682       épater  pi3S        ɛpat     1
430881       épeler  pi3S        ɛpɛl     1
431992      éponger   inf      ɛpɔ̃ʒe     1
432160      épouser   inf       ɛpuze     3
432491     éprendre   inf     ɛpʁɑ̃dʁ     1
432586     éprouver  ppMS      ɛpʁuve     1
432653      épuiser  pi3S       ɛpɥiz     1
433790      éructer  pi3S       ɛʁykt     1
433912      établir  ppMS      ɛtabli     1
433922      établir   inf     ɛtabliʁ     2
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ    13
434070         être  ii3S         ɛtɛ    89
434770     éteindre  pi2S        ɛtɛ̃     1
434775     éteindre  ppFS       ɛtɛ̃t     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434821      étendre   inf      ɛtɑ̃dʁ     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     3
435438      étonner  pi3S        ɛtɔn     1
435500     étouffer  pi3S        ɛtuf     1
435780    étrangler  ppMS    ɛtʁɑ̃gle     1
436316         être  ppMS         ɛte    20
436835     éveiller   inf       ɛvɛje     1
436867     éveiller  ppMS       ɛvɛje     1
437301       éviter   inf       ɛvite     2
437328       éviter  ppMS       ɛvite     1
437427      évoquer  pi3S        ɛvɔk     1
437474         être  pi2P          ɛt     8
437476         être   inf         ɛtʁ    16

[1922 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.6 s, total: 1min 36s
Wall time: 29.7 s

nbChunk 186
4200
1924

             lexeme  case       phono  tir1
40            avoir  pi3S           a    81
45         abaisser  ai3S       abɛsa     1
128      abandonner  pi3S     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     1
243         abattre  pi3S         aba     1
299         abattre   inf       abatʁ     1
2581         abîmer   inf       abime     1
2763       accabler  ppMS      akable     1
2939       accepter  ai3S     aksɛpta     1
2971       accepter   inf     aksɛpte     1
3349     accommoder   inf     akɔmɔde     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3432    accompagner  ai3P   akɔ̃paɲɛʁ     1
3436    accompagner  ppMP    akɔ̃paɲe     2
3516       accorder  ii3P      akɔʁdɛ     1
3519       accorder  ii3S      akɔʁdɛ     2
4210     accoutumer  ppMS     akutyme     1
4259      accrocher   inf      akʁɔʃe     1
4294      accrocher  ppMP      akʁɔʃe     1
4321      accroupir  ppFS      akʁupi     1
4337      accroupir  ppMP      akʁupi     1
4381      accroître   inf     akʁwatʁ     1
4473     accueillir  ii3S       akəjɛ     1
4502     accueillir  ppMS       akəji     1
4509     accueillir   inf      akəjiʁ     1
4686      accumuler  ppMP     akymyle     1
4688        accuser  ai3S       akyza     1
4748        accuser  ppMS       akyze     1
4754        accuser  ppMP       akyze     1
...             ...   ...         ...   ...
432302      épouser  ppMS       ɛpuze     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
433024   équilibrer  pi3P     ɛkilibʁ     1
433912      établir  ppMS      ɛtabli     1
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ    11
434070         être  ii3S         ɛtɛ    69
434072       étaler  ai3S       ɛtala     1
434134       étaler  ii3S       ɛtalɛ     1
434147       étaler  pi3S        ɛtal     1
434451     étancher   inf      ɛtɑ̃ʃe     1
434782      étendre  pi3S        ɛtɑ̃     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434833      étendre  ppFS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     3
435422      étonner  ii3S       ɛtɔnɛ     1
435425      étonner    pP      ɛtɔnɑ̃     1
435438      étonner  pi3S        ɛtɔn     1
435739    étrangler  pi1S     ɛtʁɑ̃gl     1
435815    étreindre  ai3S      ɛtʁɛɲi     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    22
436536      évaluer  pi2P      ɛvalye     1
436622  évangéliser  ppMS  ɛvɑ̃ʒɛlize     1
437301       éviter   inf       ɛvite     1
437349      évoluer  ii3P      ɛvɔlyɛ     1
437474         être  pi2P          ɛt    11
437476         être   inf         ɛtʁ    21
437497         ôter  ii3S         ɔtɛ     1

[1924 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 22 s, total: 1min 36s
Wall time: 30.4 s

nbChunk 187
4200
1971

             lexeme  case       phono  tir1
40            avoir  pi3S           a    85
128      abandonner  pi3S     abɑ̃dɔn     1
168      abandonner  ppFP    abɑ̃dɔne     1
264         abattre  pi3P        abat     1
2371         abuser  ppMS       abyze     1
2947       accepter  ii3P     aksɛptɛ     2
2971       accepter   inf     aksɛpte     1
2989       accepter  pi2P     aksɛpte     1
3536       accorder   inf      akɔʁde     1
4252      accrocher  pi1S       akʁɔʃ     1
4259      accrocher   inf      akʁɔʃe     1
4320      accroupir  ppMS      akʁupi     1
4484     accueillir  pi3P        akœj     1
4684      accumuler  ppFS     akymyle     1
4688        accuser  ai3S       akyza     1
4694        accuser    pP      akyzɑ̃     1
4716        accuser  pi3S        akyz     1
4718        accuser  pi3P        akyz     1
4736        accuser  pi2P       akyze     1
4849      accélérer  pi2P    aksɛlɛʁe     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     2
5329        achever  pi1S        aʃɛv     1
5332        achever  pi3S        aʃɛv     1
5787     acquiescer  ai3S      akjɛsa     1
5812       acquérir  ppFS        akiz     1
5997      actionner  ii3S     aksjɔnɛ     1
6043      actionner  ppMS     aksjɔne     1
6944    administrer  pi2P  administʁe     1
6970        admirer    pP     admiʁɑ̃     1
...             ...   ...         ...   ...
429330  émoustiller  ppMS    ɛmustije     1
430562     épargner   inf      ɛpaʁɲe     1
432157      épouser  ps3S        ɛpuz     1
432160      épouser   inf       ɛpuze     1
432302      épouser  ppMS       ɛpuze     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
432657      épuiser  pi3P       ɛpɥiz     1
432695      épuiser  ppMP      ɛpɥize     1
433912      établir  ppMS      ɛtabli     1
433922      établir   inf     ɛtabliʁ     2
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ    16
434070         être  ii3S         ɛtɛ    84
434747     éteindre  ai3S       ɛtɛɲi     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434788      étendre  ii3S      ɛtɑ̃dɛ     2
435260       étirer   inf       ɛtiʁe     1
435435      étonner  pi1S        ɛtɔn     1
435538     étouffer  ppMS       ɛtufe     1
436051     étriquer  ppMS      ɛtʁike     1
436316         être  ppMS         ɛte    22
436402      évacuer   inf      ɛvakye     1
436484       évader  ppMS       ɛvade     1
436707     évaporer  pi3S      ɛvapɔʁ     1
437301       éviter   inf       ɛvite     1
437307       éviter  pc3S     ɛvitəʁɛ     1
437328       éviter  ppMS       ɛvite     1
437461      évoquer  ppMP       ɛvɔke     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    21

[1971 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.4 s, total: 1min 37s
Wall time: 30.1 s

nbChunk 188
4200
1968

             lexeme  case        phono  tir1
40            avoir  pi3S            a    83
132      abandonner   inf     abɑ̃dɔne     1
166      abandonner  ppFS     abɑ̃dɔne     1
1716        abriter  ppMS       abʁite     1
1884        abréger   inf       abʁɛʒe     1
2339         abuser   inf        abyze     1
2601         abîmer  ii1P      abimjɔ̃     1
2710       accabler  ai3S       akabla     1
2774      accaparer  ii3S      akapaʁɛ     1
2878      accentuer  ai3S     aksɑ̃tya     1
2948       accepter  ii1S      aksɛptɛ     1
2964       accepter  pi1S       aksɛpt     1
2967       accepter  pi3S       aksɛpt     1
2971       accepter   inf      aksɛpte     2
2972       accepter  fi3S    aksɛptəʁa     1
2983       accepter  fi3P   aksɛptəʁɔ̃     1
3003       accepter  ppMS      aksɛpte     1
3397    accompagner  pi1S      akɔ̃paɲ     1
3406    accompagner   inf     akɔ̃paɲe     2
3436    accompagner  ppMP     akɔ̃paɲe     1
3484      accomplir  ii1P  akɔ̃plisjɔ̃     1
3571       accorder  ppMS       akɔʁde     1
4005      accoupler  ppMP       akuple     2
4252      accrocher  pi1S        akʁɔʃ     1
4292      accrocher  ppFS       akʁɔʃe     1
4373      accroître  pi3S        akʁwa     1
4464     accréditer  ppMP     akʁɛdite     1
4509     accueillir   inf       akəjiʁ     1
4811      accélérer  pI2S      aksɛlɛʁ     1
5119        acheter   inf        aʃəte     1
...             ...   ...          ...   ...
432689      épuiser  ppMS       ɛpɥize     1
433777      éructer  ii3S       ɛʁyktɛ     1
433912      établir  ppMS       ɛtabli     2
434048         être  ii3P          ɛtɛ     1
434068         être  ii1S          ɛtɛ    19
434069         être  ii2S          ɛtɛ     1
434070         être  ii3S          ɛtɛ    59
434488         être    pP         ɛtɑ̃     1
434773     éteindre  pi3S         ɛtɛ̃     1
434782      étendre  pi3S         ɛtɑ̃     1
434811      étendre  ai3S       ɛtɑ̃di     1
435054         être  ii2P         ɛtje     2
435172         être  ii1P        ɛtjɔ̃     1
435251       étirer  pi1S         ɛtiʁ     1
435422      étonner  ii3S        ɛtɔnɛ     1
435425      étonner    pP       ɛtɔnɑ̃     1
435471      étonner  ppMS        ɛtɔne     1
435472      étonner  ppFS        ɛtɔne     1
435486     étouffer    pP       ɛtufɑ̃     1
435504     étouffer  pi3P         ɛtuf     1
436205      étudier   inf       ɛtydje     1
436316         être  ppMS          ɛte    30
436402      évacuer   inf       ɛvakye     1
436430      évacuer  ppMS       ɛvakye     1
436833     éveiller  pi3P         ɛvɛj     1
436835     éveiller   inf        ɛvɛje     1
437301       éviter   inf        ɛvite     1
437314       éviter  pi2S         ɛvit     1
437474         être  pi2P           ɛt    18
437476         être   inf          ɛtʁ    19

[1968 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.2 s, total: 1min 38s
Wall time: 30 s

nbChunk 189
4200
1964

             lexeme  case      phono  tir1
40            avoir  pi3S          a    87
128      abandonner  pi3S    abɑ̃dɔn     1
164      abandonner  ppMS   abɑ̃dɔne     1
299         abattre   inf      abatʁ     2
1394        aboutir  fi3S    abutiʁa     1
1468         aboyer   inf     abwaje     1
2581         abîmer   inf      abime     1
2972       accepter  fi3S  aksɛptəʁa     1
3003       accepter  ppMS    aksɛpte     1
3382    accompagner  ii3P   akɔ̃paɲɛ     1
3406    accompagner   inf   akɔ̃paɲe     1
3445      accomplir  fi1S  akɔ̃pliʁɛ     1
3573       accorder  ppFS     akɔʁde     1
3884       accouder   inf      akude     1
4293      accrocher  ppFP     akʁɔʃe     1
4387      accroître  ppMS       akʁy     1
4654      accumuler  pi3P     akymyl     1
4716        accuser  pi3S       akyz     1
5102        acheter  ai3S      aʃəta     1
5119        acheter   inf      aʃəte     1
5136        acheter  ppMS      aʃəte     1
5140        achever  ai3S      aʃəva     1
5311        acheter  pi3S       aʃɛt     1
6891       admettre   inf     admɛtʁ     1
6996        admirer   inf     admiʁe     1
7246        adopter  pi3S      adɔpt     1
7283        adopter  ppMS     adɔpte     1
7312         adorer  pi3S       adɔʁ     2
7535       adresser  pi3S      adʁɛs     1
7552       adresser  pi2S      adʁɛs     1
...             ...   ...        ...   ...
432535     éprouver  ii1S     ɛpʁuvɛ     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
432552     éprouver  pi3S      ɛpʁuv     1
432659      épuiser   inf     ɛpɥize     1
433914      établir  ppFS     ɛtabli     1
433922      établir   inf    ɛtabliʁ     2
433936      établir  ppMP     ɛtabli     1
433946      établir  ii3S   ɛtablisɛ     1
434038       étager  ppFP      ɛtaʒe     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ    13
434070         être  ii3S        ɛtɛ    67
434299       étaler  ppMS      ɛtale     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434950     éternuer  ppMS    ɛtɛʁnye     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     2
435425      étonner    pP     ɛtɔnɑ̃     1
435438      étonner  pi3S       ɛtɔn     1
435500     étouffer  pi3S       ɛtuf     2
435742    étrangler  pi3S    ɛtʁɑ̃gl     1
436198      étudier  pi1S      ɛtydi     1
436201      étudier  pi3S      ɛtydi     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    22
436820     éveiller  ii3S      ɛvɛjɛ     1
436867     éveiller  ppMS      ɛvɛje     1
437301       éviter   inf      ɛvite     2
437474         être  pi2P         ɛt    11
437476         être   inf        ɛtʁ    16

[1964 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.5 s, total: 1min 35s
Wall time: 29.3 s

nbChunk 190
4200
1914

             lexeme  case      phono  tir1
40            avoir  pi3S          a    82
114      abandonner    pP  abɑ̃dɔnɑ̃     1
162      abandonner  ai3P  abɑ̃dɔnɛʁ     1
258         abattre  ii3S      abatɛ     1
299         abattre   inf      abatʁ     1
883          aboyer  pi2S       abwa     1
2116       absoudre   inf     absudʁ     1
2610         abîmer  ppMS      abime     1
2977       accepter  pc3S  aksɛptəʁɛ     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3386    accompagner    pP  akɔ̃paɲɑ̃     1
3508       accorder  ai3S     akɔʁda     1
4080       accourir  pc3S     akuʁʁɛ     1
4165     accoutumer  ii3S    akutymɛ     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4259      accrocher   inf     akʁɔʃe     2
4510     accueillir  ai3P     akəjiʁ     1
4683      accumuler  ppMS    akymyle     1
4716        accuser  pi3S       akyz     1
5119        acheter   inf      aʃəte     1
5125        acheter  pi2P      aʃəte     1
5136        acheter  ppMS      aʃəte     1
5311        acheter  pi3S       aʃɛt     1
5787     acquiescer  ai3S     akjɛsa     1
6969        admirer  ii3S     admiʁɛ     1
7028       admettre  ppMS       admi     1
7312         adorer  pi3S       adɔʁ     1
7320         adorer  pc1S    adɔʁəʁɛ     1
7552       adresser  pi2S      adʁɛs     1
7755         aduler  ppMS      adyle     1
...             ...   ...        ...   ...
432160      épouser   inf      ɛpuze     1
432166      épouser  pc3S    ɛpuzəʁɛ     1
432552     éprouver  pi3S      ɛpʁuv     1
432653      épuiser  pi3S      ɛpɥiz     1
433113      équiper   inf      ɛkipe     1
433195   équivaloir  ii3S    ɛkivalɛ     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ    18
434070         être  ii3S        ɛtɛ    72
434726     éteindre  ii3S      ɛtɛɲɛ     1
434747     éteindre  ai3S      ɛtɛɲi     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434773     éteindre  pi3S       ɛtɛ̃     1
434785      étendre  ii3P     ɛtɑ̃dɛ     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
434833      étendre  ppFS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     2
435951     étriller  ppMP     ɛtʁije     1
436201      étudier  pi3S      ɛtydi     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    21
436484       évader  ppMS      ɛvade     1
436627     évanouir  ppMS     ɛvanui     1
437301       éviter   inf      ɛvite     1
437328       éviter  ppMS      ɛvite     1
437367      évoluer   inf     ɛvɔlye     1
437427      évoquer  pi3S       ɛvɔk     1
437474         être  pi2P         ɛt    16
437476         être   inf        ɛtʁ    23

[1914 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.6 s, total: 1min 35s
Wall time: 29.2 s

nbChunk 191
4200
1923

             lexeme  case      phono  tir1
40            avoir  pi3S          a    97
130      abandonner  pi3P    abɑ̃dɔn     2
164      abandonner  ppMS   abɑ̃dɔne     1
305         abattre  ppMS      abaty     1
443        abdiquer  ppMS     abdike     1
2102       absorber  ppFS    absɔʁbe     1
2888      accentuer    pP  aksɑ̃tyɑ̃     1
2939       accepter  ai3S    aksɛpta     1
2989       accepter  pi2P    aksɛpte     1
2997       accepter  pi1P   aksɛptɔ̃     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3433    accompagner  ppMS   akɔ̃paɲe     2
3434    accompagner  ppFS   akɔ̃paɲe     1
3436    accompagner  ppMP   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     2
3489      accomplir  ai3S    akɔ̃pli     1
3530       accorder  pi3S      akɔʁd     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4272      accrocher  pi2S      akʁɔʃ     1
4502     accueillir  ppMS      akəji     1
4629        acculer  ppFP      akyle     1
4812      accélérer  pi3S    aksɛlɛʁ     1
5008       acharner  pi3S      aʃaʁn     1
5119        acheter   inf      aʃəte     3
5136        acheter  ppMS      aʃəte     2
5137        acheter  ppFS      aʃəte     1
5157        achever   inf      aʃəve     1
5311        acheter  pi3S       aʃɛt     1
5327        acheter  pi2S       aʃɛt     1
5814       acquérir  ppFP       akiz     1
...             ...   ...        ...   ...
432554     éprouver  pi3P      ɛpʁuv     1
432659      épuiser   inf     ɛpɥize     1
433912      établir  ppMS     ɛtabli     1
433936      établir  ppMP     ɛtabli     1
433946      établir  ii3S   ɛtablisɛ     1
434048         être  ii3P        ɛtɛ     7
434068         être  ii1S        ɛtɛ    13
434070         être  ii3S        ɛtɛ    80
434131       étaler  ii3P      ɛtalɛ     1
434739     éteindre  ai3P     ɛtɛɲiʁ     1
434747     éteindre  ai3S      ɛtɛɲi     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434811      étendre  ai3S     ɛtɑ̃di     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     2
435504     étouffer  pi3P       ɛtuf     1
435538     étouffer  ppMS      ɛtufe     1
435780    étrangler  ppMS   ɛtʁɑ̃gle     1
435837    étreindre  ppMS      ɛtʁɛ̃     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    29
436632     évanouir   inf    ɛvanuiʁ     1
436820     éveiller  ii3S      ɛvɛjɛ     1
437295       éviter  pi3S       ɛvit     1
437301       éviter   inf      ɛvite     1
437352      évoluer  ii3S     ɛvɔlyɛ     1
437474         être  pi2P         ɛt    17
437476         être   inf        ɛtʁ    15
437505         ôter  pi1S         ot     1

[1923 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 21.9 s, total: 1min 38s
Wall time: 30 s

nbChunk 192
4200
1945

             lexeme  case        phono  tir1
40            avoir  pi3S            a   103
164      abandonner  ppMS     abɑ̃dɔne     2
166      abandonner  ppFS     abɑ̃dɔne     1
307         abattre  ppFS        abaty     1
1393        aboutir   inf       abutiʁ     1
2337         abuser  pi3P         abyz     1
2939       accepter  ai3S      aksɛpta     1
2971       accepter   inf      aksɛpte     1
2984       accepter  pi2S       aksɛpt     1
3003       accepter  ppMS      aksɛpte     1
3093       acclamer  ii3P       aklamɛ     1
3400    accompagner  pi3S      akɔ̃paɲ     1
3418    accompagner  fi3P  akɔ̃paɲəʁɔ̃     1
3433    accompagner  ppMS     akɔ̃paɲe     1
3527       accorder  pi1S        akɔʁd     1
3536       accorder   inf       akɔʁde     1
3556       accorder  pi2P       akɔʁde     1
3575       accorder  ppFP       akɔʁde     1
4006       accourir  ii3P        akuʁɛ     1
4009       accourir  ii3S        akuʁɛ     1
4072       accourir   inf       akuʁiʁ     1
4255      accrocher  pi3S        akʁɔʃ     1
4259      accrocher   inf       akʁɔʃe     1
4502     accueillir  ppMS        akəji     1
4638      accumuler    pP     akymylɑ̃     1
4771        accéder  ii3S       aksɛdɛ     1
4812      accélérer  pi3S      aksɛlɛʁ     1
4862      accélérer  ppMS     aksɛlɛʁe     1
5008       acharner  pi3S        aʃaʁn     1
5119        acheter   inf        aʃəte     1
...             ...   ...          ...   ...
429498     émouvoir  ppMP          ɛmy     1
429716      énerver  pi2P       ɛnɛʁve     1
432156      épouser  pi3S         ɛpuz     1
432549     éprouver  pi1S        ɛpʁuv     1
432552     éprouver  pi3S        ɛpʁuv     1
432689      épuiser  ppMS       ɛpɥize     1
433967      établir  pi1P    ɛtablisɔ̃     1
434048         être  ii3P          ɛtɛ     5
434068         être  ii1S          ɛtɛ    11
434069         être  ii2S          ɛtɛ     1
434070         être  ii3S          ɛtɛ    68
434739     éteindre  ai3P       ɛtɛɲiʁ     1
434762     éteindre   inf       ɛtɛ̃dʁ     1
434831      étendre  ppMS       ɛtɑ̃dy     1
435054         être  ii2P         ɛtje     3
435417      étonner  ai3S        ɛtɔna     1
435435      étonner  pi1S         ɛtɔn     1
435439      étonner  ps3S         ɛtɔn     1
435457      étonner  pi2S         ɛtɔn     1
435471      étonner  ppMS        ɛtɔne     1
435837    étreindre  ppMS        ɛtʁɛ̃     1
436233      étudier  ppMS       ɛtydje     1
436316         être  ppMS          ɛte    24
436430      évacuer  ppMS       ɛvakye     1
436484       évader  ppMS        ɛvade     1
436516      évaluer  pi3S        ɛvaly     1
436820     éveiller  ii3S        ɛvɛjɛ     1
437474         être  pi2P           ɛt    17
437476         être   inf          ɛtʁ    26
437492         ôter  ai3S          ɔta     1

[1945 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.8 s, total: 1min 37s
Wall time: 29.5 s

nbChunk 193
4200
1934

             lexeme  case      phono  tir1
40            avoir  pi3S          a   103
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
890          abolir   inf     abɔliʁ     1
982         abonder  pi3P      abɔ̃d     1
1673        abriter  ii3S     abʁitɛ     1
1979       absenter  ppMS    absɑ̃te     1
2339         abuser   inf      abyze     1
2581         abîmer   inf      abime     1
2610         abîmer  ppMS      abime     2
2710       accabler  ai3S     akabla     1
2971       accepter   inf    aksɛpte     1
3380    accompagner  ai3S   akɔ̃paɲa     1
3406    accompagner   inf   akɔ̃paɲe     2
3422    accompagner  pi2P   akɔ̃paɲe     1
3573       accorder  ppFS     akɔʁde     1
3949      accoupler  ii3P     akuplɛ     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4337      accroupir  ppMP     akʁupi     1
4339      accroupir  pi1S     akʁupi     1
4824      accélérer    pP  aksɛlɛʁɑ̃     1
5092      acheminer  pi1P   aʃəminɔ̃     1
5125        acheter  pi2P      aʃəte     1
5128        acheter  ii1P    aʃətjɔ̃     1
5308        acheter  pi1S       aʃɛt     1
5332        achever  pi3S       aʃɛv     1
5905       acquérir   inf     akɛʁiʁ     1
6475    additionner   inf   adisjɔne     2
7284        adopter  ppFS     adɔpte     1
...             ...   ...        ...   ...
431135       épicer  ppFS      ɛpise     1
432160      épouser   inf      ɛpuze     2
432303      épouser  ppFS      ɛpuze     1
432535     éprouver  ii1S     ɛpʁuvɛ     2
432549     éprouver  pi1S      ɛpʁuv     1
432556     éprouver   inf     ɛpʁuve     2
433022   équilibrer  pi3S    ɛkilibʁ     1
433922      établir   inf    ɛtabliʁ     2
434048         être  ii3P        ɛtɛ     9
434068         être  ii1S        ɛtɛ     9
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    66
434299       étaler  ppMS      ɛtale     1
434301       étaler  ppFP      ɛtale     1
434302       étaler  ppMP      ɛtale     1
434729     éteindre  ps3S       ɛtɛɲ     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     5
435172         être  ii1P      ɛtjɔ̃     1
435258       étirer  pi3P       ɛtiʁ     1
435506     étouffer   inf      ɛtufe     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    34
436632     évanouir   inf    ɛvanuiʁ     1
436867     éveiller  ppMS      ɛvɛje     1
436993     éventrer  pi3S     ɛvɑ̃tʁ     1
437301       éviter   inf      ɛvite     3
437474         être  pi2P         ɛt    10
437476         être   inf        ɛtʁ    20
437492         ôter  ai3S        ɔta     1

[1934 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.3 s, total: 1min 38s
Wall time: 30.2 s

nbChunk 194
4200
1973

             lexeme  case       phono  tir1
40            avoir  pi3S           a    80
90         abaisser  pi2P       abɛse     1
113      abandonner  ii3S    abɑ̃dɔnɛ     1
132      abandonner   inf    abɑ̃dɔne     1
168      abandonner  ppFP    abɑ̃dɔne     1
287         abattre  ai3S       abati     1
305         abattre  ppMS       abaty     2
1147        aborder   inf      abɔʁde     1
1461         aboyer    pP     abwajɑ̃     1
2339         abuser   inf       abyze     1
2734       accabler  pi3P       akabl     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     1
3003       accepter  ppMS     aksɛpte     1
3322     accommoder  ii3S     akɔmɔdɛ     1
3380    accompagner  ai3S    akɔ̃paɲa     1
3406    accompagner   inf    akɔ̃paɲe     1
3408    accompagner  fi1S  akɔ̃paɲəʁɛ     1
3433    accompagner  ppMS    akɔ̃paɲe     2
3438      accomplir  ppMS     akɔ̃pli     2
3516       accorder  ii3P      akɔʁdɛ     1
3530       accorder  pi3S       akɔʁd     1
4291      accrocher  ppMS      akʁɔʃe     1
4720        accuser   inf       akyze     1
5119        acheter   inf       aʃəte     1
5332        achever  pi3S        aʃɛv     1
6862       admettre  pi3S        admɛ     1
6869       admettre  ii3S      admɛtɛ     1
6878       admettre  ii2P     admɛtje     1
6991        admirer  pi3S       admiʁ     1
...             ...   ...         ...   ...
426585     élaborer  ppFS     ɛlabɔʁe     1
427304       élever   inf       ɛləve     1
427324       élever  ppFS       ɛləve     1
430688       épater   inf       ɛpate     1
431057        épier  ii3P        ɛpjɛ     2
432160      épouser   inf       ɛpuze     3
432689      épuiser  ppMS      ɛpɥize     1
432693      épuiser  ppFP      ɛpɥize     1
433969      établir  pi3S      ɛtabli     1
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ    11
434070         être  ii3S         ɛtɛ    70
434723     éteindre  ii3P       ɛtɛɲɛ     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434775     éteindre  ppFS       ɛtɛ̃t     1
434811      étendre  ai3S      ɛtɑ̃di     1
435054         être  ii2P        ɛtje     4
435172         être  ii1P       ɛtjɔ̃     1
435438      étonner  pi3S        ɛtɔn     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435711     étourdir  pi3S      ɛtuʁdi     1
435828    étreindre   inf     ɛtʁɛ̃dʁ     1
436233      étudier  ppMS      ɛtydje     2
436316         être  ppMS         ɛte    15
436457       évader   inf       ɛvade     1
437301       éviter   inf       ɛvite     3
437352      évoluer  ii3S      ɛvɔlyɛ     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    19
437512         ôter   inf         ɔte     1

[1973 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.3 s, total: 1min 38s
Wall time: 30.1 s

nbChunk 195
4200
1990

             lexeme  case     phono  tir1
40            avoir  pi3S         a    83
110      abandonner  ii3P  abɑ̃dɔnɛ     1
132      abandonner   inf  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     1
264         abattre  pi3P      abat     1
299         abattre   inf     abatʁ     1
1415        aboutir  ii3S   abutisɛ     1
1950       absenter   inf   absɑ̃te     1
2102       absorber  ppFS   absɔʁbe     1
2339         abuser   inf     abyze     1
2964       accepter  pi1S    aksɛpt     1
2971       accepter   inf   aksɛpte     3
2989       accepter  pi2P   aksɛpte     1
3385    accompagner  ii3S  akɔ̃paɲɛ     1
3397    accompagner  pi1S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     1
3419    accompagner  pi2S   akɔ̃paɲ     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3536       accorder   inf    akɔʁde     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4294      accrocher  ppMP    akʁɔʃe     1
4369      accroupir  pi3S    akʁupi     1
4479     accueillir  pi1S      akœj     1
4736        accuser  pi2P     akyze     1
5044       acharner  ppMP    aʃaʁne     1
5119        acheter   inf     aʃəte     2
5132        acheter  ai1P    aʃətam     1
5136        acheter  ppMS     aʃəte     1
5157        achever   inf     aʃəve     2
5311        acheter  pi3S      aʃɛt     2
...             ...   ...       ...   ...
431962     épointer  ppMS   ɛpwɛ̃te     1
432160      épouser   inf     ɛpuze     1
432166      épouser  pc3S   ɛpuzəʁɛ     1
432537     éprouver  ii3S    ɛpʁuvɛ     2
432552     éprouver  pi3S     ɛpʁuv     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     1
434068         être  ii1S       ɛtɛ    20
434070         être  ii3S       ɛtɛ    78
434153       étaler   inf     ɛtale     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
434782      étendre  pi3S      ɛtɑ̃     2
434786      étendre  ii1S    ɛtɑ̃dɛ     1
434788      étendre  ii3S    ɛtɑ̃dɛ     1
434811      étendre  ai3S    ɛtɑ̃di     1
435172         être  ii1P     ɛtjɔ̃     5
435438      étonner  pi3S      ɛtɔn     1
435444      étonner   inf     ɛtɔne     1
435450      étonner  pc3S   ɛtɔnəʁɛ     1
435506     étouffer   inf     ɛtufe     1
436233      étudier  ppMS    ɛtydje     1
436237      étudier  ppFP    ɛtydje     1
436316         être  ppMS       ɛte    25
436835     éveiller   inf     ɛvɛje     1
436867     éveiller  ppMS     ɛvɛje     1
436993     éventrer  pi3S    ɛvɑ̃tʁ     1
437299       éviter  pi3P      ɛvit     1
437427      évoquer  pi3S      ɛvɔk     2
437474         être  pi2P        ɛt    15
437476         être   inf       ɛtʁ    19

[1990 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.5 s, total: 1min 34s
Wall time: 29.3 s

nbChunk 196
4200
1894

             lexeme  case       phono  tir1
40            avoir  pi3S           a    84
164      abandonner  ppMS    abɑ̃dɔne     1
1129        aborder  ii3P      abɔʁdɛ     1
1143        aborder  pi3S       abɔʁd     1
1175        aborder  ppMS      abɔʁde     1
2066       absorber  pi3S      absɔʁb     1
2335         abuser  pi3S        abyz     1
2560         abîmer  ai3S       abima     1
2939       accepter  ai3S     aksɛpta     1
2950       accepter  ii3S     aksɛptɛ     1
2971       accepter   inf     aksɛpte     1
2975       accepter  pc1S   aksɛptəʁɛ     1
2977       accepter  pc3S   aksɛptəʁɛ     2
2980       accepter  pc2P  aksɛptəʁje     1
2989       accepter  pi2P     aksɛpte     1
3380    accompagner  ai3S    akɔ̃paɲa     1
3400    accompagner  pi3S     akɔ̃paɲ     2
3406    accompagner   inf    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
3862       accouder  ai3S       akuda     1
4339      accroupir  pi1S      akʁupi     1
4484     accueillir  pi3P        akœj     1
4733        accuser  pi2S        akyz     1
4748        accuser  ppMS       akyze     1
4783        accéder   inf      aksɛde     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     1
6089        activer  pi2P      aktive     1
6414        adapter   inf      adapte     1
6443        adapter  ppMS      adapte     1
...             ...   ...         ...   ...
429694      énerver  pi3S       ɛnɛʁv     1
429828      énoncer  ppMS      ɛnɔ̃se     1
431575     épingler   inf     ɛpɛ̃gle     1
432535     éprouver  ii1S      ɛpʁuvɛ     3
432588     éprouver  ppFS      ɛpʁuve     1
432689      épuiser  ppMS      ɛpɥize     1
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ     6
434070         être  ii3S         ɛtɛ    56
434788      étendre  ii3S      ɛtɑ̃dɛ     3
434829      étendre  pi2S        ɛtɑ̃     1
435054         être  ii2P        ɛtje     3
435172         être  ii1P       ɛtjɔ̃     4
435444      étonner   inf       ɛtɔne     1
435540     étouffer  ppFS       ɛtufe     1
435748    étrangler   inf    ɛtʁɑ̃gle     2
435843    étreindre  ppMP       ɛtʁɛ̃     1
436188      étudier    pP     ɛtydjɑ̃     1
436201      étudier  pi3S       ɛtydi     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    23
436402      évacuer   inf      ɛvakye     1
436591  évangéliser   inf  ɛvɑ̃ʒɛlize     1
436629     évanouir  ppFS      ɛvanui     1
436828     éveiller  pi1S        ɛvɛj     1
437301       éviter   inf       ɛvite     1
437431      évoquer   inf       ɛvɔke     1
437474         être  pi2P          ɛt    15
437476         être   inf         ɛtʁ    20
437512         ôter   inf         ɔte     1

[1894 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.3 s, total: 1min 38s
Wall time: 29.7 s

nbChunk 197
4200
1952

              lexeme  case      phono  tir1
40             avoir  pi3S          a    85
132       abandonner   inf   abɑ̃dɔne     1
272          abattre  pi2P      abate     1
2371          abuser  ppMS      abyze     1
2763        accabler  ppMS     akable     1
2999        accepter  is3S    aksɛpta     1
3434     accompagner  ppFS   akɔ̃paɲe     1
3519        accorder  ii3S     akɔʁdɛ     1
3538        accorder  fi1S   akɔʁdəʁɛ     1
4006        accourir  ii3P      akuʁɛ     1
4259       accrocher   inf     akʁɔʃe     1
4291       accrocher  ppMS     akʁɔʃe     1
4716         accuser  pi3S       akyz     1
4812       accélérer  pi3S    aksɛlɛʁ     1
4814       accélérer  pi3P    aksɛlɛʁ     1
5119         acheter   inf      aʃəte     4
5136         acheter  ppMS      aʃəte     2
5905        acquérir   inf     akɛʁiʁ     1
7028        admettre  ppMS       admi     1
7250         adopter   inf     adɔpte     1
7293          adorer  ai1S      adɔʁɛ     1
7312          adorer  pi3S       adɔʁ     1
7455         adoucir  ppMS      adusi     1
7535        adresser  pi3S      adʁɛs     1
7539        adresser   inf     adʁɛse     1
8240         affaler  ppMS      afale     1
8349    affectionner  ii3S  afɛksjɔnɛ     1
8589        afficher  ppFS      afiʃe     1
10010         agacer  ppMS      agase     1
10475           agir  pi3S        aʒi     1
...              ...   ...        ...   ...
428248        émaner  pi3S       ɛman     1
428659      émouvoir  pi3P       ɛmœv     1
430579      épargner  pi2P     ɛpaʁɲe     1
432160       épouser   inf      ɛpuze     1
432302       épouser  ppMS      ɛpuze     1
432421    épouvanter  ppFS   ɛpuvɑ̃te     1
432553      éprouver  ps3S      ɛpʁuv     1
433922       établir   inf    ɛtabliʁ     1
434048          être  ii3P        ɛtɛ     2
434068          être  ii1S        ɛtɛ    11
434070          être  ii3S        ɛtɛ    80
434299        étaler  ppMS      ɛtale     1
434768      éteindre  pi1S       ɛtɛ̃     1
434782       étendre  pi3S       ɛtɑ̃     2
434831       étendre  ppMS     ɛtɑ̃dy     1
435054          être  ii2P       ɛtje     1
435172          être  ii1P      ɛtjɔ̃     4
435484      étouffer  ii3S      ɛtufɛ     1
436316          être  ppMS        ɛte    24
436402       évacuer   inf     ɛvakye     1
436484        évader  ppMS      ɛvade     1
436679      évanouir  pi3S     ɛvanui     1
436835      éveiller   inf      ɛvɛje     1
437281        éviter  ii3P      ɛvitɛ     1
437284        éviter  ii3S      ɛvitɛ     1
437328        éviter  ppMS      ɛvite     1
437413       évoquer  ii3P      ɛvɔkɛ     1
437429       évoquer  pi3P       ɛvɔk     1
437474          être  pi2P         ɛt     6
437476          être   inf        ɛtʁ    22

[1952 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22 s, total: 1min 38s
Wall time: 30 s

nbChunk 198
4200
1957

            lexeme  case     phono  tir1
40           avoir  pi3S         a    73
109     abandonner  ai1S  abɑ̃dɔnɛ     1
128     abandonner  pi3S   abɑ̃dɔn     1
130     abandonner  pi3P   abɑ̃dɔn     1
132     abandonner   inf  abɑ̃dɔne     1
164     abandonner  ppMS  abɑ̃dɔne     1
1133       aborder    pP   abɔʁdɑ̃     1
1147       aborder   inf    abɔʁde     1
1393       aboutir   inf    abutiʁ     1
1440       aboutir  pi3S     abuti     1
1801       abrutir   inf   abʁytiʁ     1
1867       abréger  ai3S    abʁɛʒa     1
2715      accabler  ii3S    akablɛ     1
2971      accepter   inf   aksɛpte     1
3003      accepter  ppMS   aksɛpte     1
3097      acclamer    pP   aklamɑ̃     1
3539      accorder  pc3P  akɔʁdəʁɛ     1
3575      accorder  ppFP    akɔʁde     1
3833     accoucher  pc3S   akuʃəʁɛ     1
3884      accouder   inf     akude     1
4075      accourir  fi3S    akuʁʁa     1
4090      accourir  pi3S      akuʁ     1
4291     accrocher  ppMS    akʁɔʃe     1
4320     accroupir  ppMS    akʁupi     1
4498    accueillir  pi2S      akœj     1
4509    accueillir   inf    akəjiʁ     1
4683     accumuler  ppMS   akymyle     1
4685     accumuler  ppFP   akymyle     1
4693       accuser  ii3S     akyzɛ     1
5119       acheter   inf     aʃəte     4
...            ...   ...       ...   ...
432554    éprouver  pi3P     ɛpʁuv     1
432689     épuiser  ppMS    ɛpɥize     1
433922     établir   inf   ɛtabliʁ     1
434048        être  ii3P       ɛtɛ     4
434068        être  ii1S       ɛtɛ    16
434069        être  ii2S       ɛtɛ     1
434070        être  ii3S       ɛtɛ    56
434135      étaler    pP    ɛtalɑ̃     1
434779    éteindre  ppMP      ɛtɛ̃     2
434831     étendre  ppMS    ɛtɑ̃dy     1
435054        être  ii2P      ɛtje     1
435055   étinceler  ai3S  ɛtɛ̃səla     1
435172        être  ii1P     ɛtjɔ̃     1
435422     étonner  ii3S     ɛtɔnɛ     1
435438     étonner  pi3S      ɛtɔn     2
435457     étonner  pi2S      ɛtɔn     1
435471     étonner  ppMS     ɛtɔne     1
435473     étonner  ppFP     ɛtɔne     1
435481    étouffer  ii3P     ɛtufɛ     1
435497    étouffer  pi1S      ɛtuf     1
436183     étudier  ii3P    ɛtydjɛ     1
436316        être  ppMS       ɛte    27
436402     évacuer   inf    ɛvakye     1
436484      évader  ppMS     ɛvade     1
436632    évanouir   inf   ɛvanuiʁ     1
436867    éveiller  ppMS     ɛvɛje     2
437295      éviter  pi3S      ɛvit     1
437474        être  pi2P        ɛt    13
437476        être   inf       ɛtʁ    26
437512        ôter   inf       ɔte     2

[1957 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.2 s, total: 1min 38s
Wall time: 30.2 s

nbChunk 199
4200
1966

             lexeme  case      phono  tir1
40            avoir  pi3S          a    83
111      abandonner  ii1S   abɑ̃dɔnɛ     1
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
1129        aborder  ii3P     abɔʁdɛ     1
1440        aboutir  pi3S      abuti     1
1455         aboyer  ai3S     abwaja     1
2106       absorber  ppMP    absɔʁbe     1
2565         abîmer  ii3S      abimɛ     1
2977       accepter  pc3S  aksɛptəʁɛ     1
2989       accepter  pi2P    aksɛpte     1
3406    accompagner   inf   akɔ̃paɲe     1
3519       accorder  ii3S     akɔʁdɛ     1
3530       accorder  pi3S      akɔʁd     2
4072       accourir   inf     akuʁiʁ     1
4403      accroître  ai3S       akʁy     1
4720        accuser   inf      akyze     1
4771        accéder  ii3S     aksɛdɛ     1
5119        acheter   inf      aʃəte     2
5126        acheter  ii2P     aʃətje     1
5136        acheter  ppMS      aʃəte     2
5150        achever    pP     aʃəvɑ̃     1
5852      acquitter   inf      akite     1
5905       acquérir   inf     akɛʁiʁ     1
6967        admirer  ii1S     admiʁɛ     1
6988        admirer  pi1S      admiʁ     1
6996        admirer   inf     admiʁe     1
7028       admettre  ppMS       admi     1
...             ...   ...        ...   ...
429694      énerver  pi3S      ɛnɛʁv     1
430531     épanouir  ai3S     ɛpanui     1
430643   éparpiller  ppMS   ɛpaʁpije     1
432162      épouser  fi1S    ɛpuzəʁɛ     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
432640      épuiser    pP    ɛpɥizɑ̃     1
432653      épuiser  pi3S      ɛpɥiz     1
432689      épuiser  ppMS     ɛpɥize     1
433272    éradiquer   inf    ɛʁadike     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    10
434070         être  ii3S        ɛtɛ    79
434301       étaler  ppFP      ɛtale     1
434755     éteindre  fi3S    ɛtɛ̃dʁa     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434833      étendre  ppFS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     1
435062    étinceler  ii3S   ɛtɛ̃səlɛ     1
435172         être  ii1P      ɛtjɔ̃     2
435748    étrangler   inf   ɛtʁɑ̃gle     1
436233      étudier  ppMS     ɛtydje     1
436239      étudier  ppMP     ɛtydje     1
436316         être  ppMS        ɛte    23
436395      évacuer  pi1S      ɛvaky     1
437301       éviter   inf      ɛvite     3
437413      évoquer  ii3P      ɛvɔkɛ     2
437474         être  pi2P         ɛt     5
437476         être   inf        ɛtʁ    29
437498         ôter    pP       ɔtɑ̃     1
437527         ôter  pI2P        ɔte     1

[1966 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.7 s, total: 1min 37s
Wall time: 29.5 s

nbChunk 200
4200
1917

             lexeme  case      phono  tir1
40            avoir  pi3S          a    86
114      abandonner    pP  abɑ̃dɔnɑ̃     1
132      abandonner   inf   abɑ̃dɔne     3
164      abandonner  ppMS   abɑ̃dɔne     1
1147        aborder   inf     abɔʁde     1
1415        aboutir  ii3S    abutisɛ     1
1946       absenter  pi3S     absɑ̃t     1
2950       accepter  ii3S    aksɛptɛ     1
2971       accepter   inf    aksɛpte     1
2973       accepter  fi1S  aksɛptəʁɛ     1
2990       accepter  ii2P   aksɛptje     1
3003       accepter  ppMS    aksɛpte     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3536       accorder   inf     akɔʁde     1
3537       accorder  fi3S   akɔʁdəʁa     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4509     accueillir   inf     akəjiʁ     2
4683      accumuler  ppMS    akymyle     1
4716        accuser  pi3S       akyz     1
4750        accuser  ppFS      akyze     1
5008       acharner  pi3S      aʃaʁn     1
5119        acheter   inf      aʃəte     3
5136        acheter  ppMS      aʃəte     2
5139        acheter  ppMP      aʃəte     1
5140        achever  ai3S      aʃəva     1
5171        achever  ppMS      aʃəve     2
5316        acheter  fi1S    aʃɛtəʁɛ     1
5329        achever  pi1S       aʃɛv     1
5332        achever  pi3S       aʃɛv     1
...             ...   ...        ...   ...
432588     éprouver  ppFS     ɛpʁuve     1
432689      épuiser  ppMS     ɛpɥize     1
433354      érafler  ppMS     ɛʁafle     1
433912      établir  ppMS     ɛtabli     1
433914      établir  ppFS     ɛtabli     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ    17
434070         être  ii3S        ɛtɛ    76
434773     éteindre  pi3S       ɛtɛ̃     1
434782      étendre  pi3S       ɛtɑ̃     1
434786      étendre  ii1S     ɛtɑ̃dɛ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435172         être  ii1P      ɛtjɔ̃     5
435192    étiqueter   inf    ɛtikəte     1
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435506     étouffer   inf      ɛtufe     1
435742    étrangler  pi3S    ɛtʁɑ̃gl     1
435815    étreindre  ai3S     ɛtʁɛɲi     1
436316         être  ppMS        ɛte    21
436629     évanouir  ppFS     ɛvanui     2
436679     évanouir  pi3S     ɛvanui     1
436820     éveiller  ii3S      ɛvɛjɛ     1
436867     éveiller  ppMS      ɛvɛje     1
437044     évertuer  ai3S    ɛvɛʁtya     1
437301       éviter   inf      ɛvite     1
437417      évoquer    pP     ɛvɔkɑ̃     1
437458      évoquer  ppMS      ɛvɔke     1
437459      évoquer  ppFS      ɛvɔke     1
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    17

[1917 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.1 s, total: 1min 37s
Wall time: 29.9 s

nbChunk 201
4200
1956

             lexeme  case      phono  tir1
40            avoir  pi3S          a    93
108      abandonner  ai3S   abɑ̃dɔna     1
114      abandonner    pP  abɑ̃dɔnɑ̃     1
132      abandonner   inf   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
250         abattre  pi1S        aba     1
1412        aboutir  ii3P    abutisɛ     1
1673        abriter  ii3S     abʁitɛ     1
1856        abréger  pi1S      abʁɛʒ     1
1884        abréger   inf     abʁɛʒe     1
2339         abuser   inf      abyze     1
2574         abîmer  pi1S       abim     1
2967       accepter  pi3S     aksɛpt     2
2973       accepter  fi1S  aksɛptəʁɛ     1
2977       accepter  pc3S  aksɛptəʁɛ     1
3005       accepter  ppFS    aksɛpte     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
3519       accorder  ii3S     akɔʁdɛ     1
3536       accorder   inf     akɔʁde     1
4234      accrocher  ii3P     akʁɔʃɛ     1
4293      accrocher  ppFP     akʁɔʃe     1
4320      accroupir  ppMS     akʁupi     1
4475     accueillir    pP     akəjɑ̃     1
4509     accueillir   inf     akəjiʁ     2
4820      accélérer  ii3P   aksɛlɛʁɛ     1
5042       acharner  ppFS     aʃaʁne     1
5119        acheter   inf      aʃəte     3
5136        acheter  ppMS      aʃəte     2
5137        acheter  ppFS      aʃəte     1
...             ...   ...        ...   ...
433170      équiper  ppFS      ɛkipe     1
433916      établir  ppFP     ɛtabli     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    11
434070         être  ii3S        ɛtɛ    76
434147       étaler  pi3S       ɛtal     1
434153       étaler   inf      ɛtale     1
434488         être    pP       ɛtɑ̃     1
434739     éteindre  ai3P     ɛtɛɲiʁ     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434775     éteindre  ppFS      ɛtɛ̃t     1
434786      étendre  ii1S     ɛtɑ̃dɛ     1
434836      étendre  ppFP     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     2
435295       étirer  ppFP      ɛtiʁe     1
435435      étonner  pi1S       ɛtɔn     1
435438      étonner  pi3S       ɛtɔn     2
435540     étouffer  ppFS      ɛtufe     1
436316         être  ppMS        ɛte    19
436484       évader  ppMS      ɛvade     1
436520      évaluer   inf     ɛvalye     1
436890      éventer    pP    ɛvɑ̃tɑ̃     1
437282       éviter  ii1S      ɛvitɛ     1
437301       éviter   inf      ɛvite     2
437424      évoquer  pi1S       ɛvɔk     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    18
437476         être   inf        ɛtʁ    16

[1956 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.6 s, total: 1min 36s
Wall time: 29.4 s

nbChunk 202
4200
1921

             lexeme  case       phono  tir1
40            avoir  pi3S           a    70
128      abandonner  pi3S     abɑ̃dɔn     1
272         abattre  pi2P       abate     1
1143        aborder  pi3S       abɔʁd     1
1147        aborder   inf      abɔʁde     1
1160        aborder  pi2S       abɔʁd     1
1571       abreuver   inf      abʁəve     1
1950       absenter   inf     absɑ̃te     1
2614         abîmer  ppFP       abime     1
2971       accepter   inf     aksɛpte     1
3003       accepter  ppMS     aksɛpte     1
3380    accompagner  ai3S    akɔ̃paɲa     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3443      accomplir   inf    akɔ̃pliʁ     1
3519       accorder  ii3S      akɔʁdɛ     1
3536       accorder   inf      akɔʁde     1
4255      accrocher  pi3S       akʁɔʃ     1
4783        accéder   inf      aksɛde     1
4812      accélérer  pi3S     aksɛlɛʁ     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     3
5137        acheter  ppFS       aʃəte     1
5139        acheter  ppMP       aʃəte     1
5311        acheter  pi3S        aʃɛt     1
5327        acheter  pi2S        aʃɛt     1
6891       admettre   inf      admɛtʁ     1
7312         adorer  pi3S        adɔʁ     2
7539       adresser   inf      adʁɛse     1
7803        advenir  ps3S      advjɛn     1
8080       affairer  ppFS       afɛʁe     1
...             ...   ...         ...   ...
432160      épouser   inf       ɛpuze     2
432482     éprendre    pP     ɛpʁənɑ̃     1
432519     éprendre  ppMS        ɛpʁi     1
432689      épuiser  ppMS      ɛpɥize     2
433619       ériger  ppFP       ɛʁiʒe     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    17
434070         être  ii3S         ɛtɛ    70
434134       étaler  ii3S       ɛtalɛ     1
434144       étaler  pi1S        ɛtal     1
434727     éteindre    pP      ɛtɛɲɑ̃     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434811      étendre  ai3S      ɛtɑ̃di     1
434827      étendre  pi1S        ɛtɑ̃     1
434831      étendre  ppMS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     2
435243       étirer  ii3S       ɛtiʁɛ     1
435422      étonner  ii3S       ɛtɔnɛ     2
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    24
436402      évacuer   inf      ɛvakye     1
436520      évaluer   inf      ɛvalye     1
436625  évangéliser  ppMP  ɛvɑ̃ʒɛlize     1
436627     évanouir  ppMS      ɛvanui     1
436629     évanouir  ppFS      ɛvanui     1
436837     éveiller  fi1S     ɛvɛjəʁɛ     1
437301       éviter   inf       ɛvite     1
437474         être  pi2P          ɛt     7
437476         être   inf         ɛtʁ    18

[1921 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.8 s, total: 1min 37s
Wall time: 29.8 s

nbChunk 203
4200
1956

             lexeme  case      phono  tir1
40            avoir  pi3S          a    95
64         abaisser  pi1S       abɛs     1
128      abandonner  pi3S    abɑ̃dɔn     1
299         abattre   inf      abatʁ     2
2715       accabler  ii3S     akablɛ     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     2
2984       accepter  pi2S     aksɛpt     1
3003       accepter  ppMS    aksɛpte     1
3386    accompagner    pP  akɔ̃paɲɑ̃     1
3433    accompagner  ppMS   akɔ̃paɲe     2
3443      accomplir   inf   akɔ̃pliʁ     1
3467      accomplir  ii3S  akɔ̃plisɛ     1
3471      accomplir  ps3S   akɔ̃plis     1
4094       accourir  ai3P     akuʁyʁ     1
4519     accueillir  ai3S      akəji     1
4716        accuser  pi3S       akyz     1
5015       acharner  fi3S   aʃaʁnəʁa     1
5119        acheter   inf      aʃəte     1
5136        acheter  ppMS      aʃəte     2
5157        achever   inf      aʃəve     1
5173        achever  ppFS      aʃəve     1
5308        acheter  pi1S       aʃɛt     1
5311        acheter  pi3S       aʃɛt     1
5313        acheter  pi3P       aʃɛt     1
5327        acheter  pi2S       aʃɛt     1
5764     acquiescer   inf     akjɛse     1
5807       acquérir  ppMS        aki     1
6863       admettre  pi1S       admɛ     1
6885       admettre  fi1S    admɛtʁɛ     1
...             ...   ...        ...   ...
432695      épuiser  ppMP     ɛpɥize     1
433922      établir   inf    ɛtabliʁ     1
433924      établir  fi1S   ɛtabliʁɛ     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    15
434070         être  ii3S        ɛtɛ    73
434134       étaler  ii3S      ɛtalɛ     1
434488         être    pP       ɛtɑ̃     1
434747     éteindre  ai3S      ɛtɛɲi     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434773     éteindre  pi3S       ɛtɛ̃     2
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434831      étendre  ppMS     ɛtɑ̃dy     4
435054         être  ii2P       ɛtje     3
435172         être  ii1P      ɛtjɔ̃     3
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435475     étouffer  ai3S      ɛtufa     1
435486     étouffer    pP     ɛtufɑ̃     1
435686     étourdir    pP  ɛtuʁdisɑ̃     1
435731    étrangler  ii3S   ɛtʁɑ̃glɛ     1
436316         être  ppMS        ɛte    15
436398      évacuer  pi3S      ɛvaky     1
436402      évacuer   inf     ɛvakye     1
436632     évanouir   inf    ɛvanuiʁ     1
436835     éveiller   inf      ɛvɛje     1
437295       éviter  pi3S       ɛvit     1
437301       éviter   inf      ɛvite     2
437302       éviter  fi3S    ɛvitəʁa     1
437474         être  pi2P         ɛt     9
437476         être   inf        ɛtʁ    18

[1956 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.2 s, total: 1min 37s
Wall time: 29.9 s

nbChunk 204
4200
1960

             lexeme  case     phono  tir1
40            avoir  pi3S         a    79
108      abandonner  ai3S  abɑ̃dɔna     1
128      abandonner  pi3S   abɑ̃dɔn     2
132      abandonner   inf  abɑ̃dɔne     2
145      abandonner  pi2S   abɑ̃dɔn     1
243         abattre  pi3S       aba     1
299         abattre   inf     abatʁ     1
2335         abuser  pi3S      abyz     1
2355         abuser  pi2P     abyze     1
2964       accepter  pi1S    aksɛpt     1
2969       accepter  pi3P    aksɛpt     1
2971       accepter   inf   aksɛpte     2
3003       accepter  ppMS   aksɛpte     1
3406    accompagner   inf  akɔ̃paɲe     1
3471      accomplir  ps3S  akɔ̃plis     1
3536       accorder   inf    akɔʁde     2
3556       accorder  pi2P    akɔʁde     1
3682       accoster  ppMS    akɔste     1
4063       accourir  pi3P      akuʁ     1
4234      accrocher  ii3P    akʁɔʃɛ     1
4292      accrocher  ppFS    akʁɔʃe     1
4626        acculer  ppMS     akyle     1
4748        accuser  ppMS     akyze     1
5041       acharner  ppMS    aʃaʁne     1
5119        acheter   inf     aʃəte     3
5137        acheter  ppFS     aʃəte     1
5149        achever  ii3S     aʃəvɛ     1
5327        acheter  pi2S      aʃɛt     1
5807       acquérir  ppMS       aki     1
6443        adapter  ppMS    adapte     1
...             ...   ...       ...   ...
434134       étaler  ii3S     ɛtalɛ     1
434135       étaler    pP    ɛtalɑ̃     1
434302       étaler  ppMP     ɛtale     1
434488         être    pP      ɛtɑ̃     1
434768     éteindre  pi1S      ɛtɛ̃     1
434779     éteindre  ppMP      ɛtɛ̃     1
434821      étendre   inf    ɛtɑ̃dʁ     1
435054         être  ii2P      ɛtje     3
435059    étinceler  ii3P  ɛtɛ̃səlɛ     1
435172         être  ii1P     ɛtjɔ̃     2
435240       étirer  ii3P     ɛtiʁɛ     1
435450      étonner  pc3S   ɛtɔnəʁɛ     1
435456      étonner  fi3P  ɛtɔnəʁɔ̃     1
435457      étonner  pi2S      ɛtɔn     1
435471      étonner  ppMS     ɛtɔne     2
435780    étrangler  ppMS  ɛtʁɑ̃gle     1
435815    étreindre  ai3S    ɛtʁɛɲi     1
435972      étriper   inf    ɛtʁipe     1
436316         être  ppMS       ɛte    21
436627     évanouir  ppMS    ɛvanui     1
436679     évanouir  pi3S    ɛvanui     1
436833     éveiller  pi3P      ɛvɛj     1
437301       éviter   inf     ɛvite     3
437328       éviter  ppMS     ɛvite     1
437427      évoquer  pi3S      ɛvɔk     1
437429      évoquer  pi3P      ɛvɔk     1
437474         être  pi2P        ɛt    14
437476         être   inf       ɛtʁ    26
437492         ôter  ai3S       ɔta     2
437512         ôter   inf       ɔte     1

[1960 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.4 s, total: 1min 41s
Wall time: 30.5 s

nbChunk 205
4200
1977

             lexeme  case        phono  tir1
40            avoir  pi3S            a    78
114      abandonner    pP    abɑ̃dɔnɑ̃     1
132      abandonner   inf     abɑ̃dɔne     1
144      abandonner  fi3P  abɑ̃dɔnəʁɔ̃     1
148      abandonner  pi2P     abɑ̃dɔne     1
259         abattre    pP       abatɑ̃     1
264         abattre  pi3P         abat     1
299         abattre   inf        abatʁ     4
313         abattre  ppMP        abaty     1
958         abonder  ii3S       abɔ̃dɛ     1
1468         aboyer   inf       abwaje     1
2070       absorber   inf      absɔʁbe     1
2244       abstenir  ai3S       abstɛ̃     1
2371         abuser  ppMS        abyze     1
2947       accepter  ii3P      aksɛptɛ     1
2969       accepter  pi3P       aksɛpt     1
2971       accepter   inf      aksɛpte     2
3380    accompagner  ai3S     akɔ̃paɲa     1
3400    accompagner  pi3S      akɔ̃paɲ     1
3443      accomplir   inf     akɔ̃pliʁ     2
3683       accoster  ppFS       akɔste     1
3868       accouder    pP       akudɑ̃     1
3913       accouder  ppMS        akude     1
4234      accrocher  ii3P       akʁɔʃɛ     1
4291      accrocher  ppMS       akʁɔʃe     1
4292      accrocher  ppFS       akʁɔʃe     1
4736        accuser  pi2P        akyze     1
5119        acheter   inf        aʃəte     1
5136        acheter  ppMS        aʃəte     1
5140        achever  ai3S        aʃəva     1
...             ...   ...          ...   ...
431611     épingler  ppFS      ɛpɛ̃gle     1
431867     éplucher  pi3S        ɛplyʃ     1
432173      épouser  pi2S         ɛpuz     1
432302      épouser  ppMS        ɛpuze     1
432534     éprouver  ii3P       ɛpʁuvɛ     1
432535     éprouver  ii1S       ɛpʁuvɛ     1
432691      épuiser  ppFS       ɛpɥize     1
433922      établir   inf      ɛtabliʁ     1
434048         être  ii3P          ɛtɛ     6
434068         être  ii1S          ɛtɛ     7
434070         être  ii3S          ɛtɛ    98
434072       étaler  ai3S        ɛtala     1
434775     éteindre  ppFS        ɛtɛ̃t     1
434782      étendre  pi3S         ɛtɑ̃     1
434829      étendre  pi2S         ɛtɑ̃     1
434831      étendre  ppMS       ɛtɑ̃dy     2
435172         être  ii1P        ɛtjɔ̃     2
435306      étoffer  ii3S        ɛtɔfɛ     1
435417      étonner  ai3S        ɛtɔna     1
435438      étonner  pi3S         ɛtɔn     1
436233      étudier  ppMS       ɛtydje     1
436316         être  ppMS          ɛte    21
436457       évader   inf        ɛvade     1
436656     évanouir  ii3S     ɛvanuisɛ     1
437285       éviter    pP       ɛvitɑ̃     1
437301       éviter   inf        ɛvite     1
437302       éviter  fi3S      ɛvitəʁa     1
437474         être  pi2P           ɛt    19
437476         être   inf          ɛtʁ    16
437497         ôter  ii3S          ɔtɛ     1

[1977 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 22.5 s, total: 1min 35s
Wall time: 29.5 s

nbChunk 206
4200
1902

             lexeme  case      phono  tir1
40            avoir  pi3S          a    86
114      abandonner    pP  abɑ̃dɔnɑ̃     1
132      abandonner   inf   abɑ̃dɔne     1
1147        aborder   inf     abɔʁde     1
2324         abuser  ii3S      abyzɛ     1
2964       accepter  pi1S     aksɛpt     1
2971       accepter   inf    aksɛpte     1
2989       accepter  pi2P    aksɛpte     1
3406    accompagner   inf   akɔ̃paɲe     1
3438      accomplir  ppMS    akɔ̃pli     1
3440      accomplir  ppFS    akɔ̃pli     1
3443      accomplir   inf   akɔ̃pliʁ     1
3471      accomplir  ps3S   akɔ̃plis     1
3530       accorder  pi3S      akɔʁd     2
3548       accorder  fi3P  akɔʁdəʁɔ̃     1
4092       accourir  ppFS      akuʁy     1
4259      accrocher   inf     akʁɔʃe     1
4292      accrocher  ppFS     akʁɔʃe     1
4369      accroupir  pi3S     akʁupi     1
4688        accuser  ai3S      akyza     1
4720        accuser   inf      akyze     1
5111        acheter  ii3S      aʃətɛ     1
5119        acheter   inf      aʃəte     3
5137        acheter  ppFS      aʃəte     1
5149        achever  ii3S      aʃəvɛ     1
5310        acheter  pI2S       aʃɛt     1
5311        acheter  pi3S       aʃɛt     1
5787     acquiescer  ai3S     akjɛsa     1
6085        activer  pi2S      aktiv     1
6891       admettre   inf     admɛtʁ     1
...             ...   ...        ...   ...
430590     épargner  ppMS     ɛpaʁɲe     1
430646   éparpiller  ppMP   ɛpaʁpije     1
432164      épouser  pc1S    ɛpuzəʁɛ     1
432302      épouser  ppMS      ɛpuze     1
432532     éprouver  ai3S     ɛpʁuva     1
432549     éprouver  pi1S      ɛpʁuv     1
433947      établir    pP  ɛtablisɑ̃     1
433987       étager  pi3S       ɛtaʒ     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    18
434070         être  ii3S        ɛtɛ    84
434134       étaler  ii3S      ɛtalɛ     1
434153       étaler   inf      ɛtale     1
434299       étaler  ppMS      ɛtale     1
434723     éteindre  ii3P      ɛtɛɲɛ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435172         être  ii1P      ɛtjɔ̃     1
435295       étirer  ppFP      ɛtiʁe     1
435438      étonner  pi3S       ɛtɔn     1
435475     étouffer  ai3S      ɛtufa     1
435654     étourdir  ppMS     ɛtuʁdi     1
436316         être  ppMS        ɛte    17
436484       évader  ppMS      ɛvade     1
437284       éviter  ii3S      ɛvitɛ     1
437301       éviter   inf      ɛvite     1
437416      évoquer  ii3S      ɛvɔkɛ     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    13
437476         être   inf        ɛtʁ    26
437508         ôter  pi3S         ot     1

[1902 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.2 s, total: 1min 39s
Wall time: 30 s

nbChunk 207
4200
1943

             lexeme  case       phono  tir1
40            avoir  pi3S           a    93
132      abandonner   inf    abɑ̃dɔne     1
133      abandonner  fi3S  abɑ̃dɔnəʁa     1
166      abandonner  ppFS    abɑ̃dɔne     1
261         abattre  ps3S        abat     1
934          abolir  pi3S       abɔli     1
1260       aboucher   inf       abuʃe     1
1461         aboyer    pP     abwajɑ̃     1
2939       accepter  ai3S     aksɛpta     1
2971       accepter   inf     aksɛpte     2
2989       accepter  pi2P     aksɛpte     1
3176     acclimater   inf    aklimate     1
3382    accompagner  ii3P    akɔ̃paɲɛ     1
4255      accrocher  pi3S       akʁɔʃ     1
4280      accrocher  pi2P      akʁɔʃe     1
4291      accrocher  ppMS      akʁɔʃe     1
4293      accrocher  ppFP      akʁɔʃe     2
4484     accueillir  pi3P        akœj     1
4502     accueillir  ppMS       akəji     1
4509     accueillir   inf      akəjiʁ     1
4686      accumuler  ppMP     akymyle     1
4716        accuser  pi3S        akyz     1
4726        accuser  pc3S     akyzəʁɛ     1
4733        accuser  pi2S        akyz     1
5014       acharner   inf      aʃaʁne     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     2
5139        acheter  ppMP       aʃəte     1
5157        achever   inf       aʃəve     1
5171        achever  ppMS       aʃəve     1
...             ...   ...         ...   ...
429677      énerver  ii3S      ɛnɛʁvɛ     1
429727      énerver  ppMS      ɛnɛʁve     1
429839      énoncer  ii3S      ɛnɔ̃sɛ     1
430029     énumérer    pP    ɛnymɛʁɑ̃     1
430590     épargner  ppMS      ɛpaʁɲe     1
431163        épier  pi3S         ɛpi     1
432162      épouser  fi1S     ɛpuzəʁɛ     1
432534     éprouver  ii3P      ɛpʁuvɛ     1
432657      épuiser  pi3P       ɛpɥiz     1
432691      épuiser  ppFS      ɛpɥize     1
433912      établir  ppMS      ɛtabli     1
433914      établir  ppFS      ɛtabli     1
433922      établir   inf     ɛtabliʁ     2
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ     7
434070         être  ii3S         ɛtɛ    68
434147       étaler  pi3S        ɛtal     1
434773     éteindre  pi3S        ɛtɛ̃     1
434782      étendre  pi3S        ɛtɑ̃     1
434819      étendre  pc3S     ɛtɑ̃dʁɛ     1
435055    étinceler  ai3S    ɛtɛ̃səla     1
435172         être  ii1P       ɛtjɔ̃     1
435422      étonner  ii3S       ɛtɔnɛ     1
435497     étouffer  pi1S        ɛtuf     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    27
436828     éveiller  pi1S        ɛvɛj     1
436835     éveiller   inf       ɛvɛje     2
437474         être  pi2P          ɛt    10
437476         être   inf         ɛtʁ    18

[1943 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.9 s, total: 1min 36s
Wall time: 29.5 s

nbChunk 208
4200
1901

             lexeme  case     phono  tir1
40            avoir  pi3S         a    82
45         abaisser  ai3S     abɛsa     1
128      abandonner  pi3S   abɑ̃dɔn     1
164      abandonner  ppMS  abɑ̃dɔne     1
243         abattre  pi3S       aba     1
250         abattre  pi1S       aba     1
259         abattre    pP    abatɑ̃     1
982         abonder  pi3P     abɔ̃d     1
1417        aboutir    pP  abutisɑ̃     1
1718        abriter  ppFS    abʁite     1
2102       absorber  ppFS   absɔʁbe     1
2610         abîmer  ppMS     abime     1
2763       accabler  ppMS    akable     2
2947       accepter  ii3P   aksɛptɛ     1
2971       accepter   inf   aksɛpte     2
3003       accepter  ppMS   aksɛpte     1
3005       accepter  ppFS   aksɛpte     1
3406    accompagner   inf  akɔ̃paɲe     1
3442      accomplir  ppFP   akɔ̃pli     1
3821      accoucher  pi3S      akuʃ     1
4006       accourir  ii3P     akuʁɛ     1
4252      accrocher  pi1S     akʁɔʃ     1
4291      accrocher  ppMS    akʁɔʃe     1
4521     accueillir  pi1P    akəjɔ̃     1
4716        accuser  pi3S      akyz     3
4720        accuser   inf     akyze     1
4728        accuser  fi2P   akyzəʁe     1
4997       acharner  ii3S    aʃaʁnɛ     1
5119        acheter   inf     aʃəte     1
5136        acheter  ppMS     aʃəte     1
...             ...   ...       ...   ...
430562     épargner   inf    ɛpaʁɲe     1
432156      épouser  pi3S      ɛpuz     1
432160      épouser   inf     ɛpuze     1
432556     éprouver   inf    ɛpʁuve     1
432586     éprouver  ppMS    ɛpʁuve     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     5
434068         être  ii1S       ɛtɛ    12
434070         être  ii3S       ɛtɛ    85
434480     étancher  ppMS    ɛtɑ̃ʃe     1
434488         être    pP      ɛtɑ̃     1
434772     éteindre  ppMS      ɛtɛ̃     1
434775     éteindre  ppFS     ɛtɛ̃t     1
434782      étendre  pi3S      ɛtɑ̃     1
435059    étinceler  ii3P  ɛtɛ̃səlɛ     1
435243       étirer  ii3S     ɛtiʁɛ     1
435438      étonner  pi3S      ɛtɔn     1
435506     étouffer   inf     ɛtufe     1
435519     étouffer  pi2S      ɛtuf     1
436316         être  ppMS       ɛte    17
436457       évader   inf     ɛvade     1
436634     évanouir  fi1S  ɛvanuiʁɛ     1
436831     éveiller  pi3S      ɛvɛj     1
437124       évider  pi3P      ɛvid     1
437301       éviter   inf     ɛvite     2
437307       éviter  pc3S   ɛvitəʁɛ     1
437413      évoquer  ii3P     ɛvɔkɛ     1
437474         être  pi2P        ɛt    11
437476         être   inf       ɛtʁ    20
437539         ôter  ppMS       ɔte     1

[1901 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 23.1 s, total: 1min 40s
Wall time: 31.3 s

nbChunk 209
4200
2012

             lexeme  case      phono  tir1
40            avoir  pi3S          a    99
125      abandonner  pi1S    abɑ̃dɔn     1
128      abandonner  pi3S    abɑ̃dɔn     2
145      abandonner  pi2S    abɑ̃dɔn     1
166      abandonner  ppFS   abɑ̃dɔne     1
170      abandonner  ppMP   abɑ̃dɔne     1
1147        aborder   inf     abɔʁde     1
2324         abuser  ii3S      abyzɛ     1
2964       accepter  pi1S     aksɛpt     1
2971       accepter   inf    aksɛpte     2
3003       accepter  ppMS    aksɛpte     1
3379     accommoder  ppMP    akɔmɔde     1
3406    accompagner   inf   akɔ̃paɲe     1
3467      accomplir  ii3S  akɔ̃plisɛ     1
3536       accorder   inf     akɔʁde     1
3583       accorder  ppMP     akɔʁde     1
3827      accoucher   inf      akuʃe     1
4280      accrocher  pi2P     akʁɔʃe     1
4292      accrocher  ppFS     akʁɔʃe     1
4502     accueillir  ppMS      akəji     1
4509     accueillir   inf     akəjiʁ     2
4685      accumuler  ppFP    akymyle     1
4748        accuser  ppMS      akyze     1
4783        accéder   inf     aksɛde     1
4819      accélérer  ai1S   aksɛlɛʁɛ     1
5119        acheter   inf      aʃəte     6
5136        acheter  ppMS      aʃəte     4
5311        acheter  pi3S       aʃɛt     1
5318        acheter  pc1S    aʃɛtəʁɛ     1
5336        achever  pi3P       aʃɛv     1
...             ...   ...        ...   ...
432160      épouser   inf      ɛpuze     1
432532     éprouver  ai3S     ɛpʁuva     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
432562     éprouver  pc3S   ɛpʁuvəʁɛ     1
432586     éprouver  ppMS     ɛpʁuve     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    12
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    77
434753     éteindre  is3S      ɛtɛɲi     1
434762     éteindre   inf     ɛtɛ̃dʁ     2
434772     éteindre  ppMS       ɛtɛ̃     1
434773     éteindre  pi3S       ɛtɛ̃     1
434782      étendre  pi3S       ɛtɑ̃     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435172         être  ii1P      ɛtjɔ̃     2
435460      étonner  pi2P      ɛtɔne     1
435534     étouffer  is3S      ɛtufa     2
436002      étriper  ppMP     ɛtʁipe     1
436316         être  ppMS        ɛte    26
436485       évader  ppFS      ɛvade     1
436490      évaluer  ai3S     ɛvalya     1
436997     éventrer   inf    ɛvɑ̃tʁe     1
437284       éviter  ii3S      ɛvitɛ     1
437301       éviter   inf      ɛvite     1
437417      évoquer    pP     ɛvɔkɑ̃     1
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    18
437492         ôter  ai3S        ɔta     1

[2012 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.2 s, total: 1min 38s
Wall time: 29.6 s

nbChunk 210
4200
1927

             lexeme  case      phono  tir1
40            avoir  pi3S          a    85
73         abaisser   inf      abɛse     1
1147        aborder   inf     abɔʁde     1
2717       accabler    pP    akablɑ̃     1
2971       accepter   inf    aksɛpte     5
2990       accepter  ii2P   aksɛptje     1
3376     accommoder  ppMS    akɔmɔde     1
3382    accompagner  ii3P   akɔ̃paɲɛ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     3
3433    accompagner  ppMS   akɔ̃paɲe     1
3467      accomplir  ii3S  akɔ̃plisɛ     1
3556       accorder  pi2P     akɔʁde     1
3827      accoucher   inf      akuʃe     1
4080       accourir  pc3S     akuʁʁɛ     1
4323      accroupir   inf    akʁupiʁ     1
4748        accuser  ppMS      akyze     1
4750        accuser  ppFS      akyze     1
5119        acheter   inf      aʃəte     3
5125        acheter  pi2P      aʃəte     1
5136        acheter  ppMS      aʃəte     1
5807       acquérir  ppMS        aki     1
5830      acquitter  ai3S      akita     1
5843      acquitter  pi1S       akit     1
6864       admettre  pI2S       admɛ     1
6996        admirer   inf     admiʁe     1
7027       admettre  ppMP       admi     1
7283        adopter  ppMS     adɔpte     2
7297         adorer  ii3S      adɔʁɛ     1
7309         adorer  pi1S       adɔʁ     1
...             ...   ...        ...   ...
427920       élever  pi1S       ɛlɛv     1
428248       émaner  pi3S       ɛman     1
429365     émouvoir  ppMS        ɛmy     1
429700      énerver   inf     ɛnɛʁve     1
430806      épauler   inf      ɛpɔle     1
432160      épouser   inf      ɛpuze     2
432173      épouser  pi2S       ɛpuz     1
432302      épouser  ppMS      ɛpuze     1
432556     éprouver   inf     ɛpʁuve     2
434048         être  ii3P        ɛtɛ     6
434068         être  ii1S        ɛtɛ    13
434070         être  ii3S        ɛtɛ    83
434730     éteindre  pi3P       ɛtɛɲ     1
434773     éteindre  pi3S       ɛtɛ̃     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434794      étendre  pi3P      ɛtɑ̃d     1
434811      étendre  ai3S     ɛtɑ̃di     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     4
435506     étouffer   inf      ɛtufe     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
436218      étudier  pi2S      ɛtydi     1
436316         être  ppMS        ɛte    25
436629     évanouir  ppFS     ɛvanui     1
437328       éviter  ppMS      ɛvite     1
437414      évoquer  ii1S      ɛvɔkɛ     1
437474         être  pi2P         ɛt    14
437476         être   inf        ɛtʁ    31
437539         ôter  ppMS        ɔte     1

[1927 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.6 s, total: 1min 41s
Wall time: 30.5 s

nbChunk 211
4200
1968

              lexeme  case       phono  tir1
40             avoir  pi3S           a    89
132       abandonner   inf    abɑ̃dɔne     1
148       abandonner  pi2P    abɑ̃dɔne     1
164       abandonner  ppMS    abɑ̃dɔne     2
305          abattre  ppMS       abaty     1
1934        absenter  ii3S     absɑ̃tɛ     1
2066        absorber  pi3S      absɔʁb     1
2763        accabler  ppMS      akable     1
2967        accepter  pi3S      aksɛpt     1
3003        accepter  ppMS     aksɛpte     1
3206      acclimater  ppMP    aklimate     1
3315         accoler  ppFP       akɔle     1
3397     accompagner  pi1S     akɔ̃paɲ     1
3400     accompagner  pi3S     akɔ̃paɲ     1
3443       accomplir   inf    akɔ̃pliʁ     1
3455       accomplir  fi1P  akɔ̃pliʁɔ̃     1
3527        accorder  pi1S       akɔʁd     1
3571        accorder  ppMS      akɔʁde     1
4006        accourir  ii3P       akuʁɛ     1
4090        accourir  pi3S        akuʁ     1
4259       accrocher   inf      akʁɔʃe     1
4519      accueillir  ai3S       akəji     1
4693         accuser  ii3S       akyzɛ     1
5119         acheter   inf       aʃəte     1
5136         acheter  ppMS       aʃəte     1
5137         acheter  ppFS       aʃəte     1
5140         achever  ai3S       aʃəva     1
5787      acquiescer  ai3S      akjɛsa     1
5814        acquérir  ppFP        akiz     1
5882       acquitter  ppMP       akite     1
...              ...   ...         ...   ...
428933       émonder  ppFP      ɛmɔ̃de     1
430181      épaissir  ii3S     ɛpɛsisɛ     1
430682        épater  pi3S        ɛpat     1
431613      épingler  ppFP     ɛpɛ̃gle     1
432153       épouser  pi1S        ɛpuz     1
432160       épouser   inf       ɛpuze     1
432297  époustoufler  ppMP   ɛpustufle     1
432420    épouvanter  ppMS    ɛpuvɑ̃te     1
432423    épouvanter  ppMP    ɛpuvɑ̃te     1
432556      éprouver   inf      ɛpʁuve     1
432562      éprouver  pc3S    ɛpʁuvəʁɛ     1
432584      éprouver  ai3P     ɛpʁuvɛʁ     1
432695       épuiser  ppMP      ɛpɥize     1
433170       équiper  ppFS       ɛkipe     1
433939       établir  pi1S      ɛtabli     1
434048          être  ii3P         ɛtɛ     5
434068          être  ii1S         ɛtɛ    15
434070          être  ii3S         ɛtɛ    71
434134        étaler  ii3S       ɛtalɛ     1
434782       étendre  pi3S        ɛtɑ̃     1
434833       étendre  ppFS      ɛtɑ̃dy     1
435054          être  ii2P        ɛtje     2
435172          être  ii1P       ɛtjɔ̃     1
435471       étonner  ppMS       ɛtɔne     1
436316          être  ppMS         ɛte    29
436402       évacuer   inf      ɛvakye     1
436632      évanouir   inf     ɛvanuiʁ     1
437301        éviter   inf       ɛvite     4
437474          être  pi2P          ɛt    22
437476          être   inf         ɛtʁ    14

[1968 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22 s, total: 1min 38s
Wall time: 29.6 s

nbChunk 212
4200
1930

             lexeme  case       phono  tir1
40            avoir  pi3S           a    92
138      abandonner  pc3S  abɑ̃dɔnəʁɛ     1
164      abandonner  ppMS    abɑ̃dɔne     1
1393        aboutir   inf      abutiʁ     1
2967       accepter  pi3S      aksɛpt     2
2971       accepter   inf     aksɛpte     1
2989       accepter  pi2P     aksɛpte     2
3259      accointer  ppMP     akwɛ̃te     1
3407    accompagner  fi3S  akɔ̃paɲəʁa     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3517       accorder  ii1S      akɔʁdɛ     1
3547       accorder  fi1P   akɔʁdəʁɔ̃     1
3827      accoucher   inf       akuʃe     1
4009       accourir  ii3S       akuʁɛ     1
4237      accrocher  ii3S      akʁɔʃɛ     1
4354      accroupir  pi3P     akʁupis     1
4511     accueillir  ppMP       akəji     1
4519     accueillir  ai3S       akəji     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     1
5140        achever  ai3S       aʃəva     1
5157        achever   inf       aʃəve     1
5754       acquérir  pi3S       akjɛʁ     1
5807       acquérir  ppMS         aki     1
6869       admettre  ii3S      admɛtɛ     1
6891       admettre   inf      admɛtʁ     1
7017        admirer  pI1P     admiʁɔ̃     1
7023        admirer  ppMS      admiʁe     1
7210        adonner  ii1P     adɔnjɔ̃     1
7294         adorer  ii3P       adɔʁɛ     1
...             ...   ...         ...   ...
430178     épaissir  ii3P     ɛpɛsisɛ     1
432160      épouser   inf       ɛpuze     1
432549     éprouver  pi1S       ɛpʁuv     1
432556     éprouver   inf      ɛpʁuve     2
432580     éprouver  pi1P     ɛpʁuvɔ̃     1
432584     éprouver  ai3P     ɛpʁuvɛʁ     1
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ    11
434070         être  ii3S         ɛtɛ    68
434134       étaler  ii3S       ɛtalɛ     1
434144       étaler  pi1S        ɛtal     1
434151       étaler  pi3P        ɛtal     1
434302       étaler  ppMP       ɛtale     1
434756     éteindre  fi1S     ɛtɛ̃dʁɛ     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434782      étendre  pi3S        ɛtɑ̃     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     2
435420      étonner  ii1S       ɛtɔnɛ     1
435422      étonner  ii3S       ɛtɔnɛ     1
435471      étonner  ppMS       ɛtɔne     1
435684     étourdir  ii3S    ɛtuʁdisɛ     1
436316         être  ppMS         ɛte    25
436402      évacuer   inf      ɛvakye     1
436542      évaluer  pi1P     ɛvalyɔ̃     1
437317       éviter  pi2P       ɛvite     1
437350      évoluer  ii1S      ɛvɔlyɛ     1
437431      évoquer   inf       ɛvɔke     1
437474         être  pi2P          ɛt     6
437476         être   inf         ɛtʁ    29

[1930 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.5 s, total: 1min 34s
Wall time: 30 s

nbChunk 213
4200
1934

             lexeme  case     phono  tir1
40            avoir  pi3S         a    84
130      abandonner  pi3P   abɑ̃dɔn     1
132      abandonner   inf  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     1
1034        abonner   inf     abɔne     1
1147        aborder   inf    abɔʁde     1
1388        aboutir  ppMS     abuti     2
1415        aboutir  ii3S   abutisɛ     1
1884        abréger   inf    abʁɛʒe     1
2588         abîmer  fi2S   abiməʁa     1
2932      accentuer  ppMS  aksɑ̃tye     1
2939       accepter  ai3S   aksɛpta     1
2964       accepter  pi1S    aksɛpt     1
2967       accepter  pi3S    aksɛpt     1
2971       accepter   inf   aksɛpte     2
3380    accompagner  ai3S  akɔ̃paɲa     1
3404    accompagner  pi3P   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     1
3433    accompagner  ppMS  akɔ̃paɲe     2
3571       accorder  ppMS    akɔʁde     2
4684      accumuler  ppFS   akymyle     1
4720        accuser   inf     akyze     1
4812      accélérer  pi3S   aksɛlɛʁ     1
4818      accélérer  ai3S  aksɛlɛʁa     1
5119        acheter   inf     aʃəte     1
5157        achever   inf     aʃəve     1
5329        achever  pi1S      aʃɛv     1
5332        achever  pi3S      aʃɛv     1
5787     acquiescer  ai3S    akjɛsa     1
5852      acquitter   inf     akite     1
...             ...   ...       ...   ...
430610   éparpiller  pi3S   ɛpaʁpij     1
432156      épouser  pi3S      ɛpuz     1
432160      épouser   inf     ɛpuze     2
432302      épouser  ppMS     ɛpuze     1
432534     éprouver  ii3P    ɛpʁuvɛ     1
434068         être  ii1S       ɛtɛ     9
434070         être  ii3S       ɛtɛ    67
434131       étaler  ii3P     ɛtalɛ     1
434772     éteindre  ppMS      ɛtɛ̃     1
434786      étendre  ii1S    ɛtɑ̃dɛ     1
434811      étendre  ai3S    ɛtɑ̃di     1
434833      étendre  ppFS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     3
435172         être  ii1P     ɛtjɔ̃     2
435231    étiqueter  ppMP   ɛtikəte     1
435438      étonner  pi3S      ɛtɔn     1
435460      étonner  pi2P     ɛtɔne     1
435481     étouffer  ii3P     ɛtufɛ     1
435748    étrangler   inf  ɛtʁɑ̃gle     1
435786    étrangler  ppMP  ɛtʁɑ̃gle     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    18
436430      évacuer  ppMS    ɛvakye     1
436835     éveiller   inf     ɛvɛje     1
437295       éviter  pi3S      ɛvit     1
437323       éviter  pi1P    ɛvitɔ̃     1
437458      évoquer  ppMS     ɛvɔke     1
437474         être  pi2P        ɛt     7
437476         être   inf       ɛtʁ    25
437520         ôter  fi2P     ɔtəʁe     1

[1934 rows x 4 columns]

0
CPU times: user 1min 19s, sys: 22.7 s, total: 1min 41s
Wall time: 31 s

nbChunk 214
4200
1989

             lexeme  case      phono  tir1
40            avoir  pi3S          a    70
108      abandonner  ai3S   abɑ̃dɔna     1
158      abandonner  pi1P  abɑ̃dɔnɔ̃     1
164      abandonner  ppMS   abɑ̃dɔne     1
1147        aborder   inf     abɔʁde     1
1673        abriter  ii3S     abʁitɛ     1
1684        abriter  pi3S      abʁit     1
1867        abréger  ai3S     abʁɛʒa     1
2143       abstenir   inf   abstəniʁ     1
2581         abîmer   inf      abime     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     2
3381    accompagner  ai1S   akɔ̃paɲɛ     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3520       accorder    pP    akɔʁdɑ̃     1
3655       accoster   inf     akɔste     1
3858      accoucher  ppMS      akuʃe     1
4009       accourir  ii3S      akuʁɛ     1
4259      accrocher   inf     akʁɔʃe     1
4291      accrocher  ppMS     akʁɔʃe     2
4509     accueillir   inf     akəjiʁ     1
4748        accuser  ppMS      akyze     1
4754        accuser  ppMP      akyze     1
5119        acheter   inf      aʃəte     2
5136        acheter  ppMS      aʃəte     3
6443        adapter  ppMS     adapte     1
6991        admirer  pi3S      admiʁ     1
7031       admettre  ppFS      admiz     1
7312         adorer  pi3S       adɔʁ     2
7314         adorer  pi3P       adɔʁ     1
...             ...   ...        ...   ...
432533     éprouver  ai1S     ɛpʁuvɛ     1
432689      épuiser  ppMS     ɛpɥize     1
433912      établir  ppMS     ɛtabli     1
434048         être  ii3P        ɛtɛ     6
434068         être  ii1S        ɛtɛ     8
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    55
434131       étaler  ii3P      ɛtalɛ     1
434299       étaler  ppMS      ɛtale     1
434762     éteindre   inf     ɛtɛ̃dʁ     3
434773     éteindre  pi3S       ɛtɛ̃     1
434831      étendre  ppMS     ɛtɑ̃dy     1
434833      étendre  ppFS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     2
435062    étinceler  ii3S   ɛtɛ̃səlɛ     1
435064    étinceler    pP  ɛtɛ̃səlɑ̃     1
435172         être  ii1P      ɛtjɔ̃     2
435506     étouffer   inf      ɛtufe     1
435544     étouffer  ppMP      ɛtufe     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
435968      étriper  pi3S      ɛtʁip     1
436316         être  ppMS        ɛte    20
436402      évacuer   inf     ɛvakye     1
436499      évaluer  ii3S     ɛvalyɛ     1
436821     éveiller    pP     ɛvɛjɑ̃     1
436835     éveiller   inf      ɛvɛje     1
437299       éviter  pi3P       ɛvit     1
437301       éviter   inf      ɛvite     2
437474         être  pi2P         ɛt    17
437476         être   inf        ɛtʁ    31

[1989 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.6 s, total: 1min 36s
Wall time: 30.3 s

nbChunk 215
4200
1967

             lexeme  case       phono  tir1
40            avoir  pi3S           a    91
50         abaisser  ii3S       abɛsɛ     1
113      abandonner  ii3S    abɑ̃dɔnɛ     1
148      abandonner  pi2P    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     2
1147        aborder   inf      abɔʁde     1
2371         abuser  ppMS       abyze     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     2
2977       accepter  pc3S   aksɛptəʁɛ     1
2989       accepter  pi2P     aksɛpte     2
3290        accoler  pc1S     akɔləʁɛ     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3406    accompagner   inf    akɔ̃paɲe     1
3433    accompagner  ppMS    akɔ̃paɲe     2
3443      accomplir   inf    akɔ̃pliʁ     1
3465      accomplir  ii1S   akɔ̃plisɛ     1
3530       accorder  pi3S       akɔʁd     2
3556       accorder  pi2P      akɔʁde     1
4233      accrocher  ai1S      akʁɔʃɛ     1
4291      accrocher  ppMS      akʁɔʃe     1
4716        accuser  pi3S        akyz     1
5102        acheter  ai3S       aʃəta     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     2
5147        achever  ii1S       aʃəvɛ     1
5311        acheter  pi3S        aʃɛt     3
5755     acquiescer  pi1S       akjɛs     1
5905       acquérir   inf      akɛʁiʁ     1
6064        activer  pi1S       aktiv     1
...             ...   ...         ...   ...
430619   éparpiller  pc3P  ɛpaʁpijəʁɛ     1
432173      épouser  pi2S        ɛpuz     1
432302      épouser  ppMS       ɛpuze     1
432303      épouser  ppFS       ɛpuze     1
432533     éprouver  ai1S      ɛpʁuvɛ     1
433062   équilibrer  ppMS    ɛkilibʁe     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    16
434070         être  ii3S         ɛtɛ    56
434726     éteindre  ii3S       ɛtɛɲɛ     1
434730     éteindre  pi3P        ɛtɛɲ     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434821      étendre   inf      ɛtɑ̃dʁ     1
434864    éterniser  pi3S     ɛtɛʁniz     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     3
435486     étouffer    pP      ɛtufɑ̃     1
435540     étouffer  ppFS       ɛtufe     1
435828    étreindre   inf     ɛtʁɛ̃dʁ     1
436233      étudier  ppMS      ɛtydje     2
436316         être  ppMS         ɛte    14
436402      évacuer   inf      ɛvakye     1
436627     évanouir  ppMS      ɛvanui     1
436709     évaporer  pi3P      ɛvapɔʁ     1
436835     éveiller   inf       ɛvɛje     2
437301       éviter   inf       ɛvite     2
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    24
437512         ôter   inf         ɔte     1

[1967 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.8 s, total: 1min 37s
Wall time: 29.9 s

nbChunk 216
4200
1926

             lexeme  case     phono  tir1
40            avoir  pi3S         a   115
74         abaisser  fi3S   abɛsəʁa     1
125      abandonner  pi1S   abɑ̃dɔn     2
132      abandonner   inf  abɑ̃dɔne     1
1460         aboyer  ii3S    abwajɛ     1
1468         aboyer   inf    abwaje     1
1796        abrutir  ppMS    abʁyti     1
2100       absorber  ppMS   absɔʁbe     1
2339         abuser   inf     abyze     2
2902      accentuer  pi3P   aksɑ̃ty     1
2948       accepter  ii1S   aksɛptɛ     1
2964       accepter  pi1S    aksɛpt     1
2967       accepter  pi3S    aksɛpt     1
2969       accepter  pi3P    aksɛpt     1
2971       accepter   inf   aksɛpte     2
3003       accepter  ppMS   aksɛpte     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3434    accompagner  ppFS  akɔ̃paɲe     2
3530       accorder  pi3S     akɔʁd     2
3556       accorder  pi2P    akɔʁde     1
4216     accoutumer  ppMP   akutyme     1
4255      accrocher  pi3S     akʁɔʃ     1
4259      accrocher   inf    akʁɔʃe     1
4502     accueillir  ppMS     akəji     1
4748        accuser  ppMS     akyze     1
4783        accéder   inf    aksɛde     1
5136        acheter  ppMS     aʃəte     3
5139        acheter  ppMP     aʃəte     1
5149        achever  ii3S     aʃəvɛ     1
5308        acheter  pi1S      aʃɛt     1
...             ...   ...       ...   ...
430562     épargner   inf    ɛpaʁɲe     1
431973      éponger  ai3S    ɛpɔ̃ʒa     1
432386   épouvanter  pi3S   ɛpuvɑ̃t     1
432535     éprouver  ii1S    ɛpʁuvɛ     1
432549     éprouver  pi1S     ɛpʁuv     1
432586     éprouver  ppMS    ɛpʁuve     1
433579       ériger    pP    ɛʁiʒɑ̃     1
434068         être  ii1S       ɛtɛ    14
434070         être  ii3S       ɛtɛ    81
434747     éteindre  ai3S     ɛtɛɲi     1
434773     éteindre  pi3S      ɛtɛ̃     1
434788      étendre  ii3S    ɛtɑ̃dɛ     1
435054         être  ii2P      ɛtje     4
435172         être  ii1P     ɛtjɔ̃     2
435232       étirer  ai3S     ɛtiʁa     1
435260       étirer   inf     ɛtiʁe     1
435447      étonner  pc3P   ɛtɔnəʁɛ     1
435838    étreindre  pi3S     ɛtʁɛ̃     1
436205      étudier   inf    ɛtydje     1
436233      étudier  ppMS    ɛtydje     2
436316         être  ppMS       ɛte    18
436450       évader  pi1S      ɛvad     1
436490      évaluer  ai3S    ɛvalya     1
436627     évanouir  ppMS    ɛvanui     1
436632     évanouir   inf   ɛvanuiʁ     1
437301       éviter   inf     ɛvite     3
437427      évoquer  pi3S      ɛvɔk     1
437431      évoquer   inf     ɛvɔke     1
437474         être  pi2P        ɛt    16
437476         être   inf       ɛtʁ    22

[1926 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.2 s, total: 1min 39s
Wall time: 29.8 s

nbChunk 217
4200
1946

             lexeme  case       phono  tir1
40            avoir  pi3S           a    90
104        abaisser  ppMP       abɛse     1
132      abandonner   inf    abɑ̃dɔne     1
145      abandonner  pi2S     abɑ̃dɔn     1
243         abattre  pi3S         aba     1
443        abdiquer  ppMS      abdike     1
865          aboyer  pi3S        abwa     1
1440        aboutir  pi3S       abuti     1
1716        abriter  ppMS      abʁite     1
1979       absenter  ppMS     absɑ̃te     1
2610         abîmer  ppMS       abime     1
2975       accepter  pc1S   aksɛptəʁɛ     1
3340     accommoder  pi1S      akɔmɔd     1
3515       accorder  ai1S      akɔʁdɛ     1
3527       accorder  pi1S       akɔʁd     1
3530       accorder  pi3S       akɔʁd     1
3537       accorder  fi3S    akɔʁdəʁa     1
4103       accourir  ai3S       akuʁy     1
4238      accrocher    pP     akʁɔʃɑ̃     1
4339      accroupir  pi1S      akʁupi     1
4511     accueillir  ppMP       akəji     1
4812      accélérer  pi3S     aksɛlɛʁ     1
5136        acheter  ppMS       aʃəte     2
5320        acheter  pc3S     aʃɛtəʁɛ     1
6443        adapter  ppMS      adapte     1
6862       admettre  pi3S        admɛ     1
6956    administrer  ppFS  administʁe     1
6969        admirer  ii3S      admiʁɛ     1
6991        admirer  pi3S       admiʁ     1
7046       admettre  ai3S        admi     1
...             ...   ...         ...   ...
432374   épouvanter  ii3S    ɛpuvɑ̃tɛ     1
432586     éprouver  ppMS      ɛpʁuve     1
432635      épuiser  ii3P      ɛpɥizɛ     1
432653      épuiser  pi3S       ɛpɥiz     1
433169      équiper  ppMS       ɛkipe     1
433433     érailler  ppFP       ɛʁaje     1
433590       ériger   inf       ɛʁiʒe     1
434048         être  ii3P         ɛtɛ     6
434068         être  ii1S         ɛtɛ    12
434070         être  ii3S         ɛtɛ    62
434134       étaler  ii3S       ɛtalɛ     1
434730     éteindre  pi3P        ɛtɛɲ     1
435054         être  ii2P        ɛtje     4
435417      étonner  ai3S       ɛtɔna     1
435422      étonner  ii3S       ɛtɔnɛ     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435471      étonner  ppMS       ɛtɔne     2
435484     étouffer  ii3S       ɛtufɛ     1
435500     étouffer  pi3S        ɛtuf     1
435506     étouffer   inf       ɛtufe     1
435526     étouffer  pi2P       ɛtufe     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436316         être  ppMS         ɛte    19
436402      évacuer   inf      ɛvakye     1
436865     éveiller  ai3P      ɛvɛjɛʁ     1
436867     éveiller  ppMS       ɛvɛje     1
437301       éviter   inf       ɛvite     3
437474         être  pi2P          ɛt    14
437476         être   inf         ɛtʁ    20
437512         ôter   inf         ɔte     1

[1946 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.8 s, total: 1min 39s
Wall time: 30.1 s

nbChunk 218
4200
1946

             lexeme  case     phono  tir1
40            avoir  pi3S         a    72
50         abaisser  ii3S     abɛsɛ     1
67         abaisser  pi3S      abɛs     1
132      abandonner   inf  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     1
661         abjurer   inf    abʒyʁe     1
1132        aborder  ii3S    abɔʁdɛ     1
1147        aborder   inf    abɔʁde     1
1393        aboutir   inf    abutiʁ     1
2335         abuser  pi3S      abyz     1
2581         abîmer   inf     abime     1
2950       accepter  ii3S   aksɛptɛ     1
2967       accepter  pi3S    aksɛpt     1
2971       accepter   inf   aksɛpte     3
3005       accepter  ppFS   aksɛpte     1
3385    accompagner  ii3S  akɔ̃paɲɛ     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3438      accomplir  ppMS   akɔ̃pli     1
3443      accomplir   inf  akɔ̃pliʁ     1
3536       accorder   inf    akɔʁde     1
4103       accourir  ai3S     akuʁy     1
4259      accrocher   inf    akʁɔʃe     1
4293      accrocher  ppFP    akʁɔʃe     1
4519     accueillir  ai3S     akəji     1
5119        acheter   inf     aʃəte     4
5136        acheter  ppMS     aʃəte     1
5311        acheter  pi3S      aʃɛt     1
5807       acquérir  ppMS       aki     1
6414        adapter   inf    adapte     1
6891       admettre   inf    admɛtʁ     1
...             ...   ...       ...   ...
432145      épouser    pP    ɛpuzɑ̃     1
432153      épouser  pi1S      ɛpuz     1
432156      épouser  pi3S      ɛpuz     1
432160      épouser   inf     ɛpuze     1
432691      épuiser  ppFS    ɛpɥize     1
433946      établir  ii3S  ɛtablisɛ     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    15
434069         être  ii2S       ɛtɛ     1
434070         être  ii3S       ɛtɛ    88
434692       étayer   inf     ɛtɛje     1
434727     éteindre    pP    ɛtɛɲɑ̃     1
434773     éteindre  pi3S      ɛtɛ̃     1
435054         être  ii2P      ɛtje     1
435418      étonner  ai1S     ɛtɔnɛ     1
435435      étonner  pi1S      ɛtɔn     1
435538     étouffer  ppMS     ɛtufe     1
436201      étudier  pi3S     ɛtydi     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    22
436402      évacuer   inf    ɛvakye     1
436455       évader  pi3P      ɛvad     1
436457       évader   inf     ɛvade     1
436869     éveiller  ppFS     ɛvɛje     1
437292       éviter  pi1S      ɛvit     1
437328       éviter  ppMS     ɛvite     1
437373      évoluer  pc3S   ɛvɔlyʁɛ     1
437474         être  pi2P        ɛt    17
437476         être   inf       ɛtʁ    20
437540         ôter  ppFS       ɔte     1

[1946 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.1 s, total: 1min 39s
Wall time: 30.3 s

nbChunk 219
4200
1958

             lexeme  case       phono  tir1
40            avoir  pi3S           a    88
132      abandonner   inf    abɑ̃dɔne     1
170      abandonner  ppMP    abɑ̃dɔne     2
307         abattre  ppFS       abaty     1
2736       accabler   inf      akable     1
2971       accepter   inf     aksɛpte     1
2984       accepter  pi2S      aksɛpt     2
2988       accepter  pI2P     aksɛpte     1
3003       accepter  ppMS     aksɛpte     1
3382    accompagner  ii3P    akɔ̃paɲɛ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
3440      accomplir  ppFS     akɔ̃pli     1
3468      accomplir    pP  akɔ̃plisɑ̃     1
3536       accorder   inf      akɔʁde     1
4280      accrocher  pi2P      akʁɔʃe     1
4291      accrocher  ppMS      akʁɔʃe     2
4368      accroupir  ai3S      akʁupi     1
5107        acheter  ai1S       aʃətɛ     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     3
5171        achever  ppMS       aʃəve     1
5332        achever  pi3S        aʃɛv     1
5812       acquérir  ppFS        akiz     1
6443        adapter  ppMS      adapte     1
6891       admettre   inf      admɛtʁ     1
6991        admirer  pi3S       admiʁ     3
7297         adorer  ii3S       adɔʁɛ     1
7312         adorer  pi3S        adɔʁ     1
...             ...   ...         ...   ...
428606  émerveiller  ppFS    ɛmɛʁvɛje     1
429349     émouvoir   inf     ɛmuvwaʁ     1
430590     épargner  ppMS      ɛpaʁɲe     1
431271       épiler   inf       ɛpile     1
431575     épingler   inf     ɛpɛ̃gle     1
432160      épouser   inf       ɛpuze     1
432164      épouser  pc1S     ɛpuzəʁɛ     1
432691      épuiser  ppFS      ɛpɥize     1
433169      équiper  ppMS       ɛkipe     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    17
434070         être  ii3S         ɛtɛ    60
434762     éteindre   inf      ɛtɛ̃dʁ     1
434773     éteindre  pi3S        ɛtɛ̃     1
434831      étendre  ppMS      ɛtɑ̃dy     1
434833      étendre  ppFS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     1
435506     étouffer   inf       ɛtufe     2
436188      étudier    pP     ɛtydjɑ̃     1
436198      étudier  pi1S       ɛtydi     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    28
436402      évacuer   inf      ɛvakye     1
437295       éviter  pi3S        ɛvit     1
437301       éviter   inf       ɛvite     1
437307       éviter  pc3S     ɛvitəʁɛ     1
437314       éviter  pi2S        ɛvit     1
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    23

[1958 rows x 4 columns]

0
CPU times: user 1min 19s, sys: 22.6 s, total: 1min 41s
Wall time: 30.3 s

nbChunk 220
4200
1979

             lexeme  case       phono  tir1
40            avoir  pi3S           a    80
114      abandonner    pP   abɑ̃dɔnɑ̃     1
164      abandonner  ppMS    abɑ̃dɔne     2
168      abandonner  ppFP    abɑ̃dɔne     1
243         abattre  pi3S         aba     2
1401        aboutir  ai3P      abutiʁ     1
1571       abreuver   inf      abʁəve     1
1668        abriter  ai3S      abʁita     1
2042       absorber  ai3S     absɔʁba     1
2211       abstenir  pc3P  abstjɛ̃dʁɛ     1
2228       abstenir  pi2S     abstjɛ̃     1
2730       accabler  pi3S       akabl     1
2967       accepter  pi3S      aksɛpt     1
2990       accepter  ii2P    aksɛptje     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3438      accomplir  ppMS     akɔ̃pli     1
3443      accomplir   inf    akɔ̃pliʁ     1
3534       accorder  pi3P       akɔʁd     1
4291      accrocher  ppMS      akʁɔʃe     1
4292      accrocher  ppFS      akʁɔʃe     1
4634      accumuler  ii3P     akymylɛ     1
5119        acheter   inf       aʃəte     1
5318        acheter  pc1S     aʃɛtəʁɛ     1
5327        acheter  pi2S        aʃɛt     1
5807       acquérir  ppMS         aki     1
6390        adapter    pP     adaptɑ̃     1
7024        admirer  ppFS      admiʁe     1
7250        adopter   inf      adɔpte     1
7309         adorer  pi1S        adɔʁ     2
7312         adorer  pi3S        adɔʁ     1
...             ...   ...         ...   ...
432303      épouser  ppFS       ɛpuze     2
432535     éprouver  ii1S      ɛpʁuvɛ     2
432549     éprouver  pi1S       ɛpʁuv     1
432590     éprouver  ppFP      ɛpʁuve     1
432659      épuiser   inf      ɛpɥize     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ    16
434070         être  ii3S         ɛtɛ    71
434762     éteindre   inf      ɛtɛ̃dʁ     1
434811      étendre  ai3S      ɛtɑ̃di     1
434831      étendre  ppMS      ɛtɑ̃dy     1
434833      étendre  ppFS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     2
435232       étirer  ai3S       ɛtiʁa     1
435360      étoiler  ii3P      ɛtwalɛ     1
435460      étonner  pi2P       ɛtɔne     1
436201      étudier  pi3S       ɛtydi     2
436316         être  ppMS         ɛte    22
436418      évacuer  pi2P      ɛvakye     1
436457       évader   inf       ɛvade     1
436652     évanouir  pi2S      ɛvanui     1
436815     éveiller  ai3S       ɛvɛja     1
436837     éveiller  fi1S     ɛvɛjəʁɛ     1
436869     éveiller  ppFS       ɛvɛje     1
437301       éviter   inf       ɛvite     1
437424      évoquer  pi1S        ɛvɔk     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    28
437518         ôter  pc3S       ɔtəʁɛ     1

[1979 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.3 s, total: 1min 40s
Wall time: 29.9 s

nbChunk 221
4200
1954

             lexeme  case      phono  tir1
40            avoir  pi3S          a    95
113      abandonner  ii3S   abɑ̃dɔnɛ     2
128      abandonner  pi3S    abɑ̃dɔn     1
305         abattre  ppMS      abaty     1
1174        aborder  ai3P    abɔʁdɛʁ     1
1175        aborder  ppMS     abɔʁde     1
1694        abriter  pc3S   abʁitəʁɛ     1
2324         abuser  ii3S      abyzɛ     1
2581         abîmer   inf      abime     1
2971       accepter   inf    aksɛpte     1
3380    accompagner  ai3S   akɔ̃paɲa     1
3381    accompagner  ai1S   akɔ̃paɲɛ     1
3383    accompagner  ii1S   akɔ̃paɲɛ     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3443      accomplir   inf   akɔ̃pliʁ     1
3536       accorder   inf     akɔʁde     1
3549       accorder  pi2S      akɔʁd     1
4502     accueillir  ppMS      akəji     1
4849      accélérer  pi2P   aksɛlɛʁe     1
5111        acheter  ii3S      aʃətɛ     1
5119        acheter   inf      aʃəte     4
5136        acheter  ppMS      aʃəte     1
5139        acheter  ppMP      aʃəte     1
5140        achever  ai3S      aʃəva     1
5315        acheter  fi3S    aʃɛtəʁa     1
6010      actionner  pi3S     aksjɔn     1
6991        admirer  pi3S      admiʁ     1
7172        adonner  ai1S      adɔnɛ     1
7283        adopter  ppMS     adɔpte     1
...             ...   ...        ...   ...
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    71
434131       étaler  ii3P      ɛtalɛ     1
434299       étaler  ppMS      ɛtale     1
434755     éteindre  fi3S    ɛtɛ̃dʁa     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434831      étendre  ppMS     ɛtɑ̃dy     2
434853    éterniser  ii3S   ɛtɛʁnizɛ     1
435054         être  ii2P       ɛtje     2
435064    étinceler    pP  ɛtɛ̃səlɑ̃     1
435074    étinceler   inf   ɛtɛ̃səle     1
435172         être  ii1P      ɛtjɔ̃     1
435540     étouffer  ppFS      ɛtufe     1
435542     étouffer  ppFP      ɛtufe     1
435780    étrangler  ppMS   ɛtʁɑ̃gle     1
436316         être  ppMS        ɛte    28
436402      évacuer   inf     ɛvakye     1
436430      évacuer  ppMS     ɛvakye     1
436707     évaporer  pi3S     ɛvapɔʁ     1
436711     évaporer   inf    ɛvapɔʁe     1
436820     éveiller  ii3S      ɛvɛjɛ     2
436869     éveiller  ppFS      ɛvɛje     1
436904      éventer   inf     ɛvɑ̃te     1
437285       éviter    pP     ɛvitɑ̃     1
437301       éviter   inf      ɛvite     1
437363      évoluer  pi3S      ɛvɔly     1
437367      évoluer   inf     ɛvɔlye     1
437427      évoquer  pi3S       ɛvɔk     1
437474         être  pi2P         ɛt    17
437476         être   inf        ɛtʁ    20

[1954 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.2 s, total: 1min 38s
Wall time: 29.8 s

nbChunk 222
4200
1951

             lexeme  case      phono  tir1
40            avoir  pi3S          a    75
71         abaisser  pi3P       abɛs     1
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     2
299         abattre   inf      abatʁ     1
305         abattre  ppMS      abaty     1
1394        aboutir  fi3S    abutiʁa     1
2371         abuser  ppMS      abyze     1
2888      accentuer    pP  aksɑ̃tyɑ̃     1
2939       accepter  ai3S    aksɛpta     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     1
3428    accompagner  pi1P  akɔ̃paɲɔ̃     1
3443      accomplir   inf   akɔ̃pliʁ     2
3536       accorder   inf     akɔʁde     2
4272      accrocher  pi2S      akʁɔʃ     1
4369      accroupir  pi3S     akʁupi     1
4634      accumuler  ii3P    akymylɛ     1
5119        acheter   inf      aʃəte     2
5311        acheter  pi3S       aʃɛt     1
6863       admettre  pi1S       admɛ     1
6883       admettre  pi1P    admɛtɔ̃     1
6991        admirer  pi3S      admiʁ     1
7028       admettre  ppMS       admi     1
7295         adorer  ii1S      adɔʁɛ     1
7312         adorer  pi3S       adɔʁ     1
7535       adresser  pi3S      adʁɛs     1
7539       adresser   inf     adʁɛse     2
7567       adresser  ppMS     adʁɛse     1
7569       adresser  ppFP     adʁɛse     1
...             ...   ...        ...   ...
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    16
434070         être  ii3S        ɛtɛ    69
434298       étaler  ai3P     ɛtalɛʁ     1
434299       étaler  ppMS      ɛtale     1
434451     étancher   inf     ɛtɑ̃ʃe     1
434794      étendre  pi3P      ɛtɑ̃d     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     1
435293       étirer  ppMS      ɛtiʁe     1
435418      étonner  ai1S      ɛtɔnɛ     1
435420      étonner  ii1S      ɛtɔnɛ     1
435422      étonner  ii3S      ɛtɔnɛ     1
435460      étonner  pi2P      ɛtɔne     1
435471      étonner  ppMS      ɛtɔne     1
435506     étouffer   inf      ɛtufe     1
435540     étouffer  ppFS      ɛtufe     1
435861     étrenner  pi3S      ɛtʁɛn     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    17
436656     évanouir  ii3S   ɛvanuisɛ     1
436711     évaporer   inf    ɛvapɔʁe     1
436835     éveiller   inf      ɛvɛje     1
436836     éveiller  fi3S    ɛvɛjəʁa     1
437301       éviter   inf      ɛvite     1
437424      évoquer  pi1S       ɛvɔk     1
437474         être  pi2P         ɛt    16
437476         être   inf        ɛtʁ    18
437512         ôter   inf        ɔte     1

[1951 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 23 s, total: 1min 41s
Wall time: 30.6 s

nbChunk 223
4200
2006

             lexeme  case       phono  tir1
40            avoir  pi3S           a    92
115      abandonner  ai2S    abɑ̃dɔna     1
134      abandonner  fi1S  abɑ̃dɔnəʁɛ     1
299         abattre   inf       abatʁ     2
1600       abreuver  ppMS      abʁəve     1
2100       absorber  ppMS     absɔʁbe     1
2904      accentuer   inf    aksɑ̃tye     1
2950       accepter  ii3S     aksɛptɛ     1
2971       accepter   inf     aksɛpte     1
2975       accepter  pc1S   aksɛptəʁɛ     1
3003       accepter  ppMS     aksɛpte     1
3322     accommoder  ii3S     akɔmɔdɛ     1
3349     accommoder   inf     akɔmɔde     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3406    accompagner   inf    akɔ̃paɲe     1
3419    accompagner  pi2S     akɔ̃paɲ     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3465      accomplir  ii1S   akɔ̃plisɛ     1
3536       accorder   inf      akɔʁde     1
3640       accoster  ii3S      akɔstɛ     1
4072       accourir   inf      akuʁiʁ     1
4094       accourir  ai3P      akuʁyʁ     1
4237      accrocher  ii3S      akʁɔʃɛ     1
4255      accrocher  pi3S       akʁɔʃ     1
4294      accrocher  ppMP      akʁɔʃe     1
4373      accroître  pi3S       akʁwa     1
4684      accumuler  ppFS     akymyle     1
4720        accuser   inf       akyze     1
4755        accéder  pi1S       aksɛd     1
...             ...   ...         ...   ...
432691      épuiser  ppFS      ɛpɥize     1
432695      épuiser  ppMP      ɛpɥize     1
433169      équiper  ppMS       ɛkipe     1
433914      établir  ppFS      ɛtabli     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ    16
434069         être  ii2S         ɛtɛ     2
434070         être  ii3S         ɛtɛ    65
434072       étaler  ai3S       ɛtala     1
434726     éteindre  ii3S       ɛtɛɲɛ     1
434772     éteindre  ppMS        ɛtɛ̃     1
435172         être  ii1P       ɛtjɔ̃     2
435240       étirer  ii3P       ɛtiʁɛ     1
435534     étouffer  is3S       ɛtufa     1
435540     étouffer  ppFS       ɛtufe     1
436002      étriper  ppMP      ɛtʁipe     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    17
436627     évanouir  ppMS      ɛvanui     1
436831     éveiller  pi3S        ɛvɛj     1
436835     éveiller   inf       ɛvɛje     1
437284       éviter  ii3S       ɛvitɛ     1
437301       éviter   inf       ɛvite     2
437407      évoluer  ppMS      ɛvɔlye     1
437413      évoquer  ii3P       ɛvɔkɛ     1
437459      évoquer  ppFS       ɛvɔke     1
437474         être  pi2P          ɛt    11
437476         être   inf         ɛtʁ    21
437512         ôter   inf         ɔte     1
437540         ôter  ppFS         ɔte     1

[2006 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.3 s, total: 1min 39s
Wall time: 29.7 s

nbChunk 224
4200
1945

             lexeme  case      phono  tir1
40            avoir  pi3S          a    91
108      abandonner  ai3S   abɑ̃dɔna     1
132      abandonner   inf   abɑ̃dɔne     1
148      abandonner  pi2P   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
313         abattre  ppMP      abaty     1
399        abdiquer  ii1S     abdikɛ     1
1468         aboyer   inf     abwaje     1
1688        abriter   inf     abʁite     1
2308       abstenir  is3S     abstɛ̃     1
2763       accabler  ppMS     akable     2
2971       accepter   inf    aksɛpte     2
2972       accepter  fi3S  aksɛptəʁa     1
2977       accepter  pc3S  aksɛptəʁɛ     1
2988       accepter  pI2P    aksɛpte     1
3176     acclimater   inf   aklimate     1
3406    accompagner   inf   akɔ̃paɲe     1
3434    accompagner  ppFS   akɔ̃paɲe     1
3442      accomplir  ppFP    akɔ̃pli     1
3443      accomplir   inf   akɔ̃pliʁ     1
3536       accorder   inf     akɔʁde     1
4234      accrocher  ii3P     akʁɔʃɛ     1
4238      accrocher    pP    akʁɔʃɑ̃     1
4290      accrocher  ai3P    akʁɔʃɛʁ     1
4835      accélérer   inf   aksɛlɛʁe     1
5119        acheter   inf      aʃəte     2
5136        acheter  ppMS      aʃəte     1
5157        achever   inf      aʃəve     1
5311        acheter  pi3S       aʃɛt     1
...             ...   ...        ...   ...
432659      épuiser   inf     ɛpɥize     1
432691      épuiser  ppFS     ɛpɥize     1
433195   équivaloir  ii3S    ɛkivalɛ     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ    13
434070         être  ii3S        ɛtɛ    71
434072       étaler  ai3S      ɛtala     1
434299       étaler  ppMS      ɛtale     1
434488         être    pP       ɛtɑ̃     1
434811      étendre  ai3S     ɛtɑ̃di     1
434868    éterniser   inf   ɛtɛʁnize     1
435054         être  ii2P       ɛtje     4
435172         être  ii1P      ɛtjɔ̃     1
435260       étirer   inf      ɛtiʁe     1
435417      étonner  ai3S      ɛtɔna     1
435444      étonner   inf      ɛtɔne     1
435500     étouffer  pi3S       ɛtuf     1
435540     étouffer  ppFS      ɛtufe     1
435731    étrangler  ii3S   ɛtʁɑ̃glɛ     1
435742    étrangler  pi3S    ɛtʁɑ̃gl     1
436205      étudier   inf     ɛtydje     2
436316         être  ppMS        ɛte    23
437024     éventrer  ppMS    ɛvɑ̃tʁe     1
437301       éviter   inf      ɛvite     1
437429      évoquer  pi3P       ɛvɔk     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    13
437512         ôter   inf        ɔte     2
437541         ôter  ppFP        ɔte     1

[1945 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.8 s, total: 1min 41s
Wall time: 30.4 s

nbChunk 225
4200
1986

             lexeme  case        phono  tir1
40            avoir  pi3S            a    90
128      abandonner  pi3S      abɑ̃dɔn     1
144      abandonner  fi3P  abɑ̃dɔnəʁɔ̃     1
299         abattre   inf        abatʁ     1
305         abattre  ppMS        abaty     1
1175        aborder  ppMS       abɔʁde     1
1394        aboutir  fi3S      abutiʁa     1
1425        aboutir  pi3P       abutis     1
1569       abreuver  pi3P        abʁœv     1
2371         abuser  ppMS        abyze     1
2560         abîmer  ai3S        abima     1
2904      accentuer   inf     aksɑ̃tye     1
2950       accepter  ii3S      aksɛptɛ     1
2967       accepter  pi3S       aksɛpt     1
2983       accepter  fi3P   aksɛptəʁɔ̃     1
3005       accepter  ppFS      aksɛpte     1
3397    accompagner  pi1S      akɔ̃paɲ     1
3400    accompagner  pi3S      akɔ̃paɲ     2
3406    accompagner   inf     akɔ̃paɲe     1
3433    accompagner  ppMS     akɔ̃paɲe     1
3489      accomplir  ai3S      akɔ̃pli     1
3521       accorder  ai2S       akɔʁda     1
3536       accorder   inf       akɔʁde     1
3571       accorder  ppMS       akɔʁde     1
3840      accoucher  pi2S         akuʃ     1
4009       accourir  ii3S        akuʁɛ     1
4091       accourir  ppMS        akuʁy     1
4470     accueillir  ii3P        akəjɛ     1
4482     accueillir  pi3S         akœj     1
4720        accuser   inf        akyze     1
...             ...   ...          ...   ...
432653      épuiser  pi3S        ɛpɥiz     1
432691      épuiser  ppFS       ɛpɥize     1
433912      établir  ppMS       ɛtabli     2
434048         être  ii3P          ɛtɛ     1
434068         être  ii1S          ɛtɛ    19
434069         être  ii2S          ɛtɛ     1
434070         être  ii3S          ɛtɛ    68
434488         être    pP         ɛtɑ̃     1
434768     éteindre  pi1S         ɛtɛ̃     1
434775     éteindre  ppFS        ɛtɛ̃t     1
434788      étendre  ii3S       ɛtɑ̃dɛ     1
435054         être  ii2P         ɛtje     2
435055    étinceler  ai3S     ɛtɛ̃səla     1
435062    étinceler  ii3S     ɛtɛ̃səlɛ     1
435230    étiqueter  ppFP      ɛtikəte     1
435422      étonner  ii3S        ɛtɔnɛ     1
435438      étonner  pi3S         ɛtɔn     1
435450      étonner  pc3S      ɛtɔnəʁɛ     1
435506     étouffer   inf        ɛtufe     1
435780    étrangler  ppMS     ɛtʁɑ̃gle     1
436205      étudier   inf       ɛtydje     1
436316         être  ppMS          ɛte    20
436398      évacuer  pi3S        ɛvaky     1
436455       évader  pi3P         ɛvad     1
437301       éviter   inf        ɛvite     3
437328       éviter  ppMS        ɛvite     1
437416      évoquer  ii3S        ɛvɔkɛ     1
437458      évoquer  ppMS        ɛvɔke     2
437474         être  pi2P           ɛt    14
437476         être   inf          ɛtʁ    20

[1986 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.7 s, total: 1min 35s
Wall time: 29 s

nbChunk 226
4200
1892

             lexeme  case     phono  tir1
40            avoir  pi3S         a    96
132      abandonner   inf  abɑ̃dɔne     1
1421        aboutir  ps3S    abutis     1
1716        abriter  ppMS    abʁite     1
2971       accepter   inf   aksɛpte     2
2984       accepter  pi2S    aksɛpt     1
3003       accepter  ppMS   aksɛpte     1
3397    accompagner  pi1S   akɔ̃paɲ     1
3434    accompagner  ppFS  akɔ̃paɲe     1
3443      accomplir   inf  akɔ̃pliʁ     1
3575       accorder  ppFP    akɔʁde     1
4063       accourir  pi3P      akuʁ     1
4252      accrocher  pi1S     akʁɔʃ     1
4292      accrocher  ppFS    akʁɔʃe     1
4864      accélérer  ppFS  aksɛlɛʁe     1
5005       acharner  pi1S     aʃaʁn     1
5041       acharner  ppMS    aʃaʁne     1
5119        acheter   inf     aʃəte     2
5135        acheter  ai3P    aʃətɛʁ     1
5318        acheter  pc1S   aʃɛtəʁɛ     1
5332        achever  pi3S      aʃɛv     1
5786     acquiescer  ppMS    akjɛse     1
6891       admettre   inf    admɛtʁ     1
6994        admirer  pi3P     admiʁ     1
6996        admirer   inf    admiʁe     1
7023        admirer  ppMS    admiʁe     1
7284        adopter  ppFS    adɔpte     1
7295         adorer  ii1S     adɔʁɛ     1
7309         adorer  pi1S      adɔʁ     1
7312         adorer  pi3S      adɔʁ     3
...             ...   ...       ...   ...
432162      épouser  fi1S   ɛpuzəʁɛ     1
432302      épouser  ppMS     ɛpuze     1
432420   épouvanter  ppMS  ɛpuvɑ̃te     1
432535     éprouver  ii1S    ɛpʁuvɛ     1
432537     éprouver  ii3S    ɛpʁuvɛ     1
432586     éprouver  ppMS    ɛpʁuve     1
432659      épuiser   inf    ɛpɥize     1
433954      établir  pi3P   ɛtablis     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    15
434070         être  ii3S       ɛtɛ    82
434756     éteindre  fi1S   ɛtɛ̃dʁɛ     1
434785      étendre  ii3P    ɛtɑ̃dɛ     1
434821      étendre   inf    ɛtɑ̃dʁ     1
434833      étendre  ppFS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     1
435418      étonner  ai1S     ɛtɔnɛ     1
435435      étonner  pi1S      ɛtɔn     1
435438      étonner  pi3S      ɛtɔn     2
435442      étonner  pi3P      ɛtɔn     1
435447      étonner  pc3P   ɛtɔnəʁɛ     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    22
436835     éveiller   inf     ɛvɛje     1
437295       éviter  pi3S      ɛvit     1
437301       éviter   inf     ɛvite     4
437427      évoquer  pi3S      ɛvɔk     1
437474         être  pi2P        ɛt    11
437476         être   inf       ɛtʁ    15

[1892 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.4 s, total: 1min 38s
Wall time: 29.8 s

nbChunk 227
4200
1956

             lexeme  case     phono  tir1
40            avoir  pi3S         a    88
132      abandonner   inf  abɑ̃dɔne     1
243         abattre  pi3S       aba     1
299         abattre   inf     abatʁ     1
1688        abriter   inf    abʁite     1
2042       absorber  ai3S   absɔʁba     1
2116       absoudre   inf    absudʁ     1
2948       accepter  ii1S   aksɛptɛ     1
2964       accepter  pi1S    aksɛpt     1
2967       accepter  pi3S    aksɛpt     2
2969       accepter  pi3P    aksɛpt     1
2971       accepter   inf   aksɛpte     2
2989       accepter  pi2P   aksɛpte     1
3003       accepter  ppMS   aksɛpte     1
3404    accompagner  pi3P   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     2
3433    accompagner  ppMS  akɔ̃paɲe     1
4255      accrocher  pi3S     akʁɔʃ     1
4259      accrocher   inf    akʁɔʃe     1
4292      accrocher  ppFS    akʁɔʃe     1
4294      accrocher  ppMP    akʁɔʃe     1
4339      accroupir  pi1S    akʁupi     1
4502     accueillir  ppMS     akəji     1
4767        accéder  ai1S    aksɛdɛ     1
5119        acheter   inf     aʃəte     5
5136        acheter  ppMS     aʃəte     1
5165        achever  pi1P    aʃəvɔ̃     1
5329        achever  pi1S      aʃɛv     1
6016      actionner   inf   aksjɔne     1
6891       admettre   inf    admɛtʁ     1
...             ...   ...       ...   ...
432551     éprouver  pI2S     ɛpʁuv     1
433195   équivaloir  ii3S   ɛkivalɛ     1
433555     éreinter  ppFS    ɛʁɛ̃te     1
433928      établir  pc3S  ɛtabliʁɛ     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ     6
434069         être  ii2S       ɛtɛ     1
434070         être  ii3S       ɛtɛ    69
434300       étaler  ppFS     ɛtale     1
434729     éteindre  ps3S      ɛtɛɲ     1
434782      étendre  pi3S      ɛtɑ̃     1
434786      étendre  ii1S    ɛtɑ̃dɛ     1
434861    éterniser  pi1S   ɛtɛʁniz     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     1
435438      étonner  pi3S      ɛtɔn     1
435506     étouffer   inf     ɛtufe     1
435742    étrangler  pi3S   ɛtʁɑ̃gl     1
435748    étrangler   inf  ɛtʁɑ̃gle     1
436221      étudier  pi2P    ɛtydje     1
436297       étuver  ppMS     ɛtyve     1
436316         être  ppMS       ɛte    12
436627     évanouir  ppMS    ɛvanui     1
436820     éveiller  ii3S     ɛvɛjɛ     1
436867     éveiller  ppMS     ɛvɛje     1
437124       évider  pi3P      ɛvid     1
437284       éviter  ii3S     ɛvitɛ     1
437328       éviter  ppMS     ɛvite     1
437474         être  pi2P        ɛt    10
437476         être   inf       ɛtʁ    18

[1956 rows x 4 columns]

0
CPU times: user 1min 4s, sys: 18.3 s, total: 1min 23s
Wall time: 30.3 s

nbChunk 228
4200
1946

             lexeme  case       phono  tir1
40            avoir  pi3S           a    85
128      abandonner  pi3S     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
134      abandonner  fi1S  abɑ̃dɔnəʁɛ     1
145      abandonner  pi2S     abɑ̃dɔn     1
164      abandonner  ppMS    abɑ̃dɔne     1
1148        aborder  fi3S    abɔʁdəʁa     1
1468         aboyer   inf      abwaje     1
1716        abriter  ppMS      abʁite     1
2339         abuser   inf       abyze     1
2967       accepter  pi3S      aksɛpt     1
2972       accepter  fi3S   aksɛptəʁa     1
2975       accepter  pc1S   aksɛptəʁɛ     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3490      accomplir  pi3S     akɔ̃pli     1
3519       accorder  ii3S      akɔʁdɛ     1
3536       accorder   inf      akɔʁde     2
3821      accoucher  pi3S        akuʃ     1
4259      accrocher   inf      akʁɔʃe     1
4272      accrocher  pi2S       akʁɔʃ     1
4291      accrocher  ppMS      akʁɔʃe     1
4683      accumuler  ppMS     akymyle     1
4835      accélérer   inf    aksɛlɛʁe     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     3
5137        acheter  ppFS       aʃəte     1
5315        acheter  fi3S     aʃɛtəʁa     1
5327        acheter  pi2S        aʃɛt     1
5787     acquiescer  ai3S      akjɛsa     1
...             ...   ...         ...   ...
434068         être  ii1S         ɛtɛ    13
434070         être  ii3S         ɛtɛ    80
434072       étaler  ai3S       ɛtala     1
434132       étaler  ii1S       ɛtalɛ     1
434299       étaler  ppMS       ɛtale     1
434734     éteindre  pi2P       ɛtɛɲe     1
434821      étendre   inf      ɛtɑ̃dʁ     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     2
435444      étonner   inf       ɛtɔne     1
435497     étouffer  pi1S        ɛtuf     1
435506     étouffer   inf       ɛtufe     1
435742    étrangler  pi3S     ɛtʁɑ̃gl     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436201      étudier  pi3S       ɛtydi     1
436205      étudier   inf      ɛtydje     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    26
436402      évacuer   inf      ɛvakye     1
437282       éviter  ii1S       ɛvitɛ     1
437284       éviter  ii3S       ɛvitɛ     1
437301       éviter   inf       ɛvite     3
437327       éviter  ai3P      ɛvitɛʁ     1
437328       éviter  ppMS       ɛvite     1
437367      évoluer   inf      ɛvɔlye     1
437411      évoquer  ai3S       ɛvɔka     1
437427      évoquer  pi3S        ɛvɔk     1
437474         être  pi2P          ɛt    15
437476         être   inf         ɛtʁ    16
437510         ôter  pi3P          ot     1

[1946 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22 s, total: 1min 38s
Wall time: 29.9 s

nbChunk 229
4200
1938

            lexeme  case      phono  tir1
40           avoir  pi3S          a    89
113     abandonner  ii3S   abɑ̃dɔnɛ     1
287        abattre  ai3S      abati     1
299        abattre   inf      abatʁ     1
305        abattre  ppMS      abaty     1
890         abolir   inf     abɔliʁ     1
1884       abréger   inf     abʁɛʒe     1
2106      absorber  ppMP    absɔʁbe     1
2610        abîmer  ppMS      abime     1
2715      accabler  ii3S     akablɛ     1
2972      accepter  fi3S  aksɛptəʁa     1
3508      accorder  ai3S     akɔʁda     1
3556      accorder  pi2P     akɔʁde     1
3913      accouder  ppMS      akude     1
4237     accrocher  ii3S     akʁɔʃɛ     1
4461    accréditer  ppMS   akʁɛdite     1
4503    accueillir  ppFS      akəji     1
5119       acheter   inf      aʃəte     6
5136       acheter  ppMS      aʃəte     1
5137       acheter  ppFS      aʃəte     1
5157       achever   inf      aʃəve     1
6032     actionner  pi2P    aksjɔne     1
6967       admirer  ii1S     admiʁɛ     1
6997       admirer  fi3S   admiʁəʁa     1
7284       adopter  ppFS     adɔpte     1
7312        adorer  pi3S       adɔʁ     2
7316        adorer   inf      adɔʁe     1
7399       adosser  ppFS      adɔse     1
7758        aduler  ppMP      adyle     1
8199       affaler    pP     afalɑ̃     1
...            ...   ...        ...   ...
430616  éparpiller   inf   ɛpaʁpije     1
432569    éprouver  pi2S      ɛpʁuv     1
432659     épuiser   inf     ɛpɥize     1
433303     érafler  ai3S     ɛʁafla     1
433922     établir   inf    ɛtabliʁ     2
433930     établir  ai3P    ɛtabliʁ     1
434048        être  ii3P        ɛtɛ     6
434068        être  ii1S        ɛtɛ    10
434070        être  ii3S        ɛtɛ    87
434300      étaler  ppFS      ɛtale     1
434726    éteindre  ii3S      ɛtɛɲɛ     1
434768    éteindre  pi1S       ɛtɛ̃     1
434788     étendre  ii3S     ɛtɑ̃dɛ     1
434811     étendre  ai3S     ɛtɑ̃di     1
434821     étendre   inf     ɛtɑ̃dʁ     1
434831     étendre  ppMS     ɛtɑ̃dy     2
435054        être  ii2P       ɛtje     2
435172        être  ii1P      ɛtjɔ̃     4
435438     étonner  pi3S       ɛtɔn     1
435450     étonner  pc3S    ɛtɔnəʁɛ     1
436205     étudier   inf     ɛtydje     1
436316        être  ppMS        ɛte    21
436678    évanouir  ai3S     ɛvanui     1
437295      éviter  pi3S       ɛvit     1
437301      éviter   inf      ɛvite     1
437323      éviter  pi1P     ɛvitɔ̃     1
437427     évoquer  pi3S       ɛvɔk     1
437474        être  pi2P         ɛt    11
437476        être   inf        ɛtʁ    20
437512        ôter   inf        ɔte     1

[1938 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 21.7 s, total: 1min 38s
Wall time: 29.6 s

nbChunk 230
4200
1922

             lexeme  case      phono  tir1
40            avoir  pi3S          a   100
125      abandonner  pi1S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
148      abandonner  pi2P   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     1
1147        aborder   inf     abɔʁde     1
1148        aborder  fi3S   abɔʁdəʁa     1
1175        aborder  ppMS     abɔʁde     1
1440        aboutir  pi3S      abuti     1
1934       absenter  ii3S    absɑ̃tɛ     1
2337         abuser  pi3P       abyz     1
2503         abêtir  ppMS      abɛti     1
2581         abîmer   inf      abime     1
2971       accepter   inf    aksɛpte     1
2974       accepter  pc3P  aksɛptəʁɛ     1
3003       accepter  ppMS    aksɛpte     3
3400    accompagner  pi3S    akɔ̃paɲ     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3490      accomplir  pi3S    akɔ̃pli     1
3916       accouder  ppMP      akude     1
4214     accoutumer  ppFP    akutyme     1
4255      accrocher  pi3S      akʁɔʃ     2
4320      accroupir  ppMS     akʁupi     1
4323      accroupir   inf    akʁupiʁ     1
4750        accuser  ppFS      akyze     1
5102        acheter  ai3S      aʃəta     1
5119        acheter   inf      aʃəte     3
5136        acheter  ppMS      aʃəte     2
5150        achever    pP     aʃəvɑ̃     1
5308        acheter  pi1S       aʃɛt     1
...             ...   ...        ...   ...
430591     épargner  ppFS     ɛpaʁɲe     1
430869       épeler   inf      ɛpəle     1
432153      épouser  pi1S       ɛpuz     1
432374   épouvanter  ii3S   ɛpuvɑ̃tɛ     1
433914      établir  ppFS     ɛtabli     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    22
434070         être  ii3S        ɛtɛ    61
434130       étaler  ai1S      ɛtalɛ     1
434147       étaler  pi3S       ɛtal     1
434151       étaler  pi3P       ɛtal     1
434299       étaler  ppMS      ɛtale     1
434301       étaler  ppFP      ɛtale     1
434302       étaler  ppMP      ɛtale     1
434768     éteindre  pi1S       ɛtɛ̃     1
434829      étendre  pi2S       ɛtɑ̃     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     3
435244       étirer    pP     ɛtiʁɑ̃     1
435417      étonner  ai3S      ɛtɔna     1
435435      étonner  pi1S       ɛtɔn     1
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435972      étriper   inf     ɛtʁipe     1
436316         être  ppMS        ɛte    28
436402      évacuer   inf     ɛvakye     1
436632     évanouir   inf    ɛvanuiʁ     1
437273       éviter  ai3S      ɛvita     1
437301       éviter   inf      ɛvite     2
437474         être  pi2P         ɛt    14
437476         être   inf        ɛtʁ    20

[1922 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.8 s, total: 1min 37s
Wall time: 29.1 s

nbChunk 231
4200
1897

             lexeme  case       phono  tir1
40            avoir  pi3S           a    89
164      abandonner  ppMS    abɑ̃dɔne     1
299         abattre   inf       abatʁ     1
1884        abréger   inf      abʁɛʒe     1
2684     acagnarder  ppMS    akaɲaʁde     1
2712       accabler  ii3P      akablɛ     1
2964       accepter  pi1S      aksɛpt     1
2969       accepter  pi3P      aksɛpt     1
2971       accepter   inf     aksɛpte     2
2983       accepter  fi3P  aksɛptəʁɔ̃     1
3003       accepter  ppMS     aksɛpte     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     1
3421    accompagner  pI2P    akɔ̃paɲe     1
3530       accorder  pi3S       akɔʁd     1
3913       accouder  ppMS       akude     1
4255      accrocher  pi3S       akʁɔʃ     1
4369      accroupir  pi3S      akʁupi     1
4479     accueillir  pi1S        akœj     1
4503     accueillir  ppFS       akəji     1
4634      accumuler  ii3P     akymylɛ     1
4748        accuser  ppMS       akyze     1
4760        accéder  pi3P       aksɛd     1
5119        acheter   inf       aʃəte     3
5136        acheter  ppMS       aʃəte     1
5137        acheter  ppFS       aʃəte     1
5169        achever  ai3P      aʃəvɛʁ     1
5320        acheter  pc3S     aʃɛtəʁɛ     1
5332        achever  pi3S        aʃɛv     1
6709      adjoindre  ai3S     adʒwaɲi     1
...             ...   ...         ...   ...
432638      épuiser  ii3S      ɛpɥizɛ     2
433914      établir  ppFS      ɛtabli     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    73
434072       étaler  ai3S       ɛtala     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434821      étendre   inf      ɛtɑ̃dʁ     1
435054         être  ii2P        ɛtje     2
435055    étinceler  ai3S    ɛtɛ̃səla     1
435172         être  ii1P       ɛtjɔ̃     4
435232       étirer  ai3S       ɛtiʁa     1
435244       étirer    pP      ɛtiʁɑ̃     1
435438      étonner  pi3S        ɛtɔn     1
435484     étouffer  ii3S       ɛtufɛ     1
435497     étouffer  pi1S        ɛtuf     1
435540     étouffer  ppFS       ɛtufe     1
435542     étouffer  ppFP       ɛtufe     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436188      étudier    pP     ɛtydjɑ̃     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    25
436664     évanouir  pi3P     ɛvanuis     1
437124       évider  pi3P        ɛvid     1
437281       éviter  ii3P       ɛvitɛ     1
437301       éviter   inf       ɛvite     1
437427      évoquer  pi3S        ɛvɔk     1
437474         être  pi2P          ɛt     9
437476         être   inf         ɛtʁ    17

[1897 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.2 s, total: 1min 37s
Wall time: 29.7 s

nbChunk 232
4200
1948

            lexeme  case       phono  tir1
40           avoir  pi3S           a    89
50        abaisser  ii3S       abɛsɛ     1
128     abandonner  pi3S     abɑ̃dɔn     2
162     abandonner  ai3P   abɑ̃dɔnɛʁ     1
865         aboyer  pi3S        abwa     1
934         abolir  pi3S       abɔli     1
2051      absorber  ii3S     absɔʁbɛ     1
2371        abuser  ppMS       abyze     1
2969      accepter  pi3P      aksɛpt     1
2971      accepter   inf     aksɛpte     2
2974      accepter  pc3P   aksɛptəʁɛ     1
2980      accepter  pc2P  aksɛptəʁje     1
3003      accepter  ppMS     aksɛpte     2
3443     accomplir   inf    akɔ̃pliʁ     1
3557      accorder  ii2P     akɔʁdje     1
3571      accorder  ppMS      akɔʁde     1
4090      accourir  pi3S        akuʁ     1
4292     accrocher  ppFS      akʁɔʃe     1
4473    accueillir  ii3S       akəjɛ     1
4509    accueillir   inf      akəjiʁ     1
5119       acheter   inf       aʃəte     1
5136       acheter  ppMS       aʃəte     1
5140       achever  ai3S       aʃəva     1
5149       achever  ii3S       aʃəvɛ     1
5171       achever  ppMS       aʃəve     1
5316       acheter  fi1S     aʃɛtəʁɛ     2
5807      acquérir  ppMS         aki     1
7028      admettre  ppMS        admi     1
7297        adorer  ii3S       adɔʁɛ     1
7312        adorer  pi3S        adɔʁ     2
...            ...   ...         ...   ...
432552    éprouver  pi3S       ɛpʁuv     1
432556    éprouver   inf      ɛpʁuve     1
432689     épuiser  ppMS      ɛpɥize     1
433912     établir  ppMS      ɛtabli     1
433922     établir   inf     ɛtabliʁ     1
434048        être  ii3P         ɛtɛ     3
434068        être  ii1S         ɛtɛ    14
434070        être  ii3S         ɛtɛ    78
434773    éteindre  pi3S        ɛtɛ̃     1
434779    éteindre  ppMP        ɛtɛ̃     2
434788     étendre  ii3S      ɛtɑ̃dɛ     2
434811     étendre  ai3S      ɛtɑ̃di     1
434814     étendre  fi3S     ɛtɑ̃dʁa     1
434821     étendre   inf      ɛtɑ̃dʁ     1
435054        être  ii2P        ɛtje     1
435064   étinceler    pP   ɛtɛ̃səlɑ̃     1
435172        être  ii1P       ɛtjɔ̃     3
435471     étonner  ppMS       ɛtɔne     1
435482    étouffer  ii1S       ɛtufɛ     1
435500    étouffer  pi3S        ɛtuf     1
435509    étouffer  pc3P     ɛtufəʁɛ     1
435540    étouffer  ppFS       ɛtufe     1
435794   étreindre  ii3S      ɛtʁɛɲɛ     1
436316        être  ppMS         ɛte    31
436402     évacuer   inf      ɛvakye     1
437284      éviter  ii3S       ɛvitɛ     1
437301      éviter   inf       ɛvite     2
437474        être  pi2P          ɛt    12
437476        être   inf         ɛtʁ    23
437497        ôter  ii3S         ɔtɛ     1

[1948 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22 s, total: 1min 39s
Wall time: 29.9 s

nbChunk 233
4200
1946

             lexeme  case      phono  tir1
40            avoir  pi3S          a    87
113      abandonner  ii3S   abɑ̃dɔnɛ     1
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     1
243         abattre  pi3S        aba     1
299         abattre   inf      abatʁ     1
865          aboyer  pi3S       abwa     1
888          abolir  ppFS      abɔli     1
1147        aborder   inf     abɔʁde     1
2339         abuser   inf      abyze     1
2371         abuser  ppMS      abyze     1
2967       accepter  pi3S     aksɛpt     1
2972       accepter  fi3S  aksɛptəʁa     2
3436    accompagner  ppMP   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
3475      accomplir  pi3P   akɔ̃plis     1
3913       accouder  ppMS      akude     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4259      accrocher   inf     akʁɔʃe     1
4291      accrocher  ppMS     akʁɔʃe     1
4502     accueillir  ppMS      akəji     1
4694        accuser    pP     akyzɑ̃     1
4754        accuser  ppMP      akyze     1
5102        acheter  ai3S      aʃəta     1
5119        acheter   inf      aʃəte     1
5136        acheter  ppMS      aʃəte     1
5137        acheter  ppFS      aʃəte     1
5332        achever  pi3S       aʃɛv     2
5905       acquérir   inf     akɛʁiʁ     1
...             ...   ...        ...   ...
430558     épargner  pi3S      ɛpaʁɲ     1
432160      épouser   inf      ɛpuze     2
432552     éprouver  pi3S      ɛpʁuv     2
432592     éprouver  ppMP     ɛpʁuve     1
433195   équivaloir  ii3S    ɛkivalɛ     1
433912      établir  ppMS     ɛtabli     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    15
434070         être  ii3S        ɛtɛ    72
434451     étancher   inf     ɛtɑ̃ʃe     1
434772     éteindre  ppMS       ɛtɛ̃     2
434917     éternuer  pi3S     ɛtɛʁny     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     3
435251       étirer  pi1S       ɛtiʁ     1
435417      étonner  ai3S      ɛtɔna     2
435472      étonner  ppFS      ɛtɔne     1
435506     étouffer   inf      ɛtufe     1
435968      étriper  pi3S      ɛtʁip     1
436316         être  ppMS        ɛte    36
436381      évacuer  ii3S     ɛvakyɛ     1
436457       évader   inf      ɛvade     1
436835     éveiller   inf      ɛvɛje     1
436867     éveiller  ppMS      ɛvɛje     1
437301       éviter   inf      ɛvite     1
437307       éviter  pc3S    ɛvitəʁɛ     1
437367      évoluer   inf     ɛvɔlye     1
437411      évoquer  ai3S      ɛvɔka     1
437474         être  pi2P         ɛt    14
437476         être   inf        ɛtʁ    22

[1946 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.3 s, total: 1min 39s
Wall time: 30.2 s

nbChunk 234
4200
1945

             lexeme  case       phono  tir1
40            avoir  pi3S           a    80
110      abandonner  ii3P    abɑ̃dɔnɛ     1
132      abandonner   inf    abɑ̃dɔne     1
166      abandonner  ppFS    abɑ̃dɔne     2
287         abattre  ai3S       abati     2
2581         abîmer   inf       abime     1
2967       accepter  pi3S      aksɛpt     1
3349     accommoder   inf     akɔmɔde     1
3406    accompagner   inf    akɔ̃paɲe     1
4255      accrocher  pi3S       akʁɔʃ     2
4259      accrocher   inf      akʁɔʃe     1
4491     accueillir  pc3S     akəjəʁɛ     1
4748        accuser  ppMS       akyze     1
4808        accéder  ppMS      aksɛde     1
5111        acheter  ii3S       aʃətɛ     1
5119        acheter   inf       aʃəte     1
5125        acheter  pi2P       aʃəte     1
5136        acheter  ppMS       aʃəte     3
5157        achever   inf       aʃəve     1
5173        achever  ppFS       aʃəve     1
6865       admettre  pi2S        admɛ     1
6955    administrer  ppMS  administʁe     1
7023        admirer  ppMS      admiʁe     1
7311         adorer  pI2S        adɔʁ     1
7312         adorer  pi3S        adɔʁ     3
7524       adresser    pP     adʁɛsɑ̃     1
8091      affaisser    pP      afɛsɑ̃     1
9559      affronter    pP    afʁɔ̃tɑ̃     1
9575      affronter   inf     afʁɔ̃te     1
9682       affréter   inf      afʁɛte     1
...             ...   ...         ...   ...
432196   épousseter    pP    ɛpusətɑ̃     1
432302      épouser  ppMS       ɛpuze     1
432586     éprouver  ppMS      ɛpʁuve     1
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ    11
434070         être  ii3S         ɛtɛ    68
434134       étaler  ii3S       ɛtalɛ     1
434147       étaler  pi3S        ɛtal     1
434762     éteindre   inf      ɛtɛ̃dʁ     2
434827      étendre  pi1S        ɛtɑ̃     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     1
435282       étirer  pi2P       ɛtiʁe     1
435471      étonner  ppMS       ɛtɔne     1
435782    étrangler  ppFS    ɛtʁɑ̃gle     1
436201      étudier  pi3S       ɛtydi     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    14
436402      évacuer   inf      ɛvakye     1
436460       évader  pc3P     ɛvadəʁɛ     1
436653     évanouir  ii3P    ɛvanuisɛ     1
436704     évaporer  pi1S      ɛvapɔʁ     1
436711     évaporer   inf     ɛvapɔʁe     1
437049     évertuer  ii3S     ɛvɛʁtyɛ     1
437367      évoluer   inf      ɛvɔlye     1
437407      évoluer  ppMS      ɛvɔlye     1
437431      évoquer   inf       ɛvɔke     2
437474         être  pi2P          ɛt    11
437476         être   inf         ɛtʁ    20
437512         ôter   inf         ɔte     1

[1945 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22 s, total: 1min 38s
Wall time: 29.3 s

nbChunk 235
4200
1922

             lexeme  case       phono  tir1
40            avoir  pi3S           a    85
164      abandonner  ppMS    abɑ̃dɔne     1
252         abattre  pi2S         aba     1
293         abattre  fi1S      abatʁɛ     1
299         abattre   inf       abatʁ     1
1121        aborder  ai3S      abɔʁda     1
2900      accentuer  pi3S     aksɑ̃ty     1
2971       accepter   inf     aksɛpte     1
3003       accepter  ppMS     aksɛpte     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
3571       accorder  ppMS      akɔʁde     1
3573       accorder  ppFS      akɔʁde     1
3913       accouder  ppMS       akude     1
4291      accrocher  ppMS      akʁɔʃe     1
4369      accroupir  pi3S      akʁupi     1
4509     accueillir   inf      akəjiʁ     1
4783        accéder   inf      aksɛde     1
5119        acheter   inf       aʃəte     3
5136        acheter  ppMS       aʃəte     4
5137        acheter  ppFS       aʃəte     1
6032      actionner  pi2P     aksjɔne     1
6414        adapter   inf      adapte     1
6891       admettre   inf      admɛtʁ     1
6928    administrer   inf  administʁe     1
7250        adopter   inf      adɔpte     1
7312         adorer  pi3S        adɔʁ     2
7567       adresser  ppMS      adʁɛse     1
7963      affaiblir  ppMS      afɛbli     1
...             ...   ...         ...   ...
431909     éplucher  ppMP      ɛplyʃe     1
432160      épouser   inf       ɛpuze     3
432552     éprouver  pi3S       ɛpʁuv     1
432691      épuiser  ppFS      ɛpɥize     1
433196   équivaloir    pP    ɛkivalɑ̃     1
433922      établir   inf     ɛtabliʁ     1
434021       étager  pi2S        ɛtaʒ     1
434048         être  ii3P         ɛtɛ     6
434068         être  ii1S         ɛtɛ     7
434070         être  ii3S         ɛtɛ    84
434773     éteindre  pi3S        ɛtɛ̃     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434833      étendre  ppFS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     2
435417      étonner  ai3S       ɛtɔna     1
435435      étonner  pi1S        ɛtɔn     1
435438      étonner  pi3S        ɛtɔn     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
435780    étrangler  ppMS    ɛtʁɑ̃gle     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    27
436402      évacuer   inf      ɛvakye     1
436632     évanouir   inf     ɛvanuiʁ     1
436657     évanouir    pP   ɛvanuisɑ̃     1
436831     éveiller  pi3S        ɛvɛj     1
437303       éviter  fi1S     ɛvitəʁɛ     1
437328       éviter  ppMS       ɛvite     1
437474         être  pi2P          ɛt    14
437476         être   inf         ɛtʁ    22
437508         ôter  pi3S          ot     1

[1922 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.5 s, total: 1min 40s
Wall time: 30.4 s

nbChunk 236
4200
1972

             lexeme  case     phono  tir1
40            avoir  pi3S         a    94
125      abandonner  pi1S   abɑ̃dɔn     1
132      abandonner   inf  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     1
299         abattre   inf     abatʁ     1
416        abdiquer   inf    abdike     1
2339         abuser   inf     abyze     1
2967       accepter  pi3S    aksɛpt     2
2971       accepter   inf   aksɛpte     1
2989       accepter  pi2P   aksɛpte     1
3003       accepter  ppMS   aksɛpte     1
3007       accepter  ppFP   aksɛpte     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3443      accomplir   inf  akɔ̃pliʁ     2
3516       accorder  ii3P    akɔʁdɛ     1
4255      accrocher  pi3S     akʁɔʃ     1
4783        accéder   inf    aksɛde     1
4809      accélérer  pi1S   aksɛlɛʁ     1
4818      accélérer  ai3S  aksɛlɛʁa     1
4997       acharner  ii3S    aʃaʁnɛ     1
5119        acheter   inf     aʃəte     2
5130        acheter  pI1P    aʃətɔ̃     1
5136        acheter  ppMS     aʃəte     1
5149        achever  ii3S     aʃəvɛ     1
5157        achever   inf     aʃəve     1
5311        acheter  pi3S      aʃɛt     2
5332        achever  pi3S      aʃɛv     1
5807       acquérir  ppMS       aki     2
6863       admettre  pi1S      admɛ     1
6996        admirer   inf    admiʁe     1
...             ...   ...       ...   ...
432173      épouser  pi2S      ɛpuz     1
432537     éprouver  ii3S    ɛpʁuvɛ     1
432556     éprouver   inf    ɛpʁuve     1
432689      épuiser  ppMS    ɛpɥize     1
432691      épuiser  ppFS    ɛpɥize     1
433912      établir  ppMS    ɛtabli     1
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ     8
434069         être  ii2S       ɛtɛ     1
434070         être  ii3S       ɛtɛ    71
434488         être    pP      ɛtɑ̃     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
434811      étendre  ai3S    ɛtɑ̃di     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     3
435231    étiqueter  ppMP   ɛtikəte     1
435444      étonner   inf     ɛtɔne     1
435450      étonner  pc3S   ɛtɔnəʁɛ     1
435500     étouffer  pi3S      ɛtuf     1
435519     étouffer  pi2S      ɛtuf     1
435795    étreindre    pP   ɛtʁɛɲɑ̃     1
436205      étudier   inf    ɛtydje     1
436316         être  ppMS       ɛte    20
436457       évader   inf     ɛvade     1
436483       évader  ai3P    ɛvadɛʁ     1
436835     éveiller   inf     ɛvɛje     1
437328       éviter  ppMS     ɛvite     3
437461      évoquer  ppMP     ɛvɔke     1
437474         être  pi2P        ɛt     7
437476         être   inf       ɛtʁ    26

[1972 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22 s, total: 1min 37s
Wall time: 29.6 s

nbChunk 237
4200
1952

             lexeme  case     phono  tir1
40            avoir  pi3S         a    67
71         abaisser  pi3P      abɛs     1
132      abandonner   inf  abɑ̃dɔne     1
243         abattre  pi3S       aba     1
256         abattre  ii1S     abatɛ     1
299         abattre   inf     abatʁ     2
1174        aborder  ai3P   abɔʁdɛʁ     1
1260       aboucher   inf     abuʃe     1
1684        abriter  pi3S     abʁit     1
2322         abuser  ii1S     abyzɛ     1
2818      accaparer  ppMS   akapaʁe     1
2971       accepter   inf   aksɛpte     1
3382    accompagner  ii3P  akɔ̃paɲɛ     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     1
3433    accompagner  ppMS  akɔ̃paɲe     2
3536       accorder   inf    akɔʁde     2
3571       accorder  ppMS    akɔʁde     1
3737        accoter  ppMS     akɔte     1
4210     accoutumer  ppMS   akutyme     1
4255      accrocher  pi3S     akʁɔʃ     1
4259      accrocher   inf    akʁɔʃe     1
4373      accroître  pi3S     akʁwa     1
5109        acheter  ii1S     aʃətɛ     1
5119        acheter   inf     aʃəte     2
5136        acheter  ppMS     aʃəte     2
5149        achever  ii3S     aʃəvɛ     1
5308        acheter  pi1S      aʃɛt     1
5329        achever  pi1S      aʃɛv     1
5764     acquiescer   inf    akjɛse     1
...             ...   ...       ...   ...
431167        épier   inf      ɛpje     1
432156      épouser  pi3S      ɛpuz     1
432586     éprouver  ppMS    ɛpʁuve     1
432691      épuiser  ppFS    ɛpɥize     1
434048         être  ii3P       ɛtɛ     1
434068         être  ii1S       ɛtɛ     8
434070         être  ii3S       ɛtɛ    94
434131       étaler  ii3P     ɛtalɛ     1
434692       étayer   inf     ɛtɛje     1
434768     éteindre  pi1S      ɛtɛ̃     1
434811      étendre  ai3S    ɛtɑ̃di     1
434827      étendre  pi1S      ɛtɑ̃     1
434833      étendre  ppFS    ɛtɑ̃dy     1
434839      étendre  ppMP    ɛtɑ̃dy     1
434917     éternuer  pi3S    ɛtɛʁny     1
435172         être  ii1P     ɛtjɔ̃     2
435232       étirer  ai3S     ɛtiʁa     1
435293       étirer  ppMS     ɛtiʁe     1
435457      étonner  pi2S      ɛtɔn     1
435540     étouffer  ppFS     ɛtufe     1
436316         être  ppMS       ɛte    16
436821     éveiller    pP    ɛvɛjɑ̃     1
437301       éviter   inf     ɛvite     1
437331       éviter  ppMP     ɛvite     1
437416      évoquer  ii3S     ɛvɔkɛ     1
437474         être  pi2P        ɛt    15
437476         être   inf       ɛtʁ    23
437492         ôter  ai3S       ɔta     1
437497         ôter  ii3S       ɔtɛ     1
437512         ôter   inf       ɔte     1

[1952 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.3 s, total: 1min 39s
Wall time: 30 s

nbChunk 238
4200
1967

             lexeme  case      phono  tir1
40            avoir  pi3S          a    94
114      abandonner    pP  abɑ̃dɔnɑ̃     1
162      abandonner  ai3P  abɑ̃dɔnɛʁ     1
164      abandonner  ppMS   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
307         abattre  ppFS      abaty     1
2971       accepter   inf    aksɛpte     1
3003       accepter  ppMS    aksɛpte     1
3406    accompagner   inf   akɔ̃paɲe     1
4010       accourir    pP     akuʁɑ̃     1
4094       accourir  ai3P     akuʁyʁ     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4403      accroître  ai3S       akʁy     1
4683      accumuler  ppMS    akymyle     1
4720        accuser   inf      akyze     1
4835      accélérer   inf   aksɛlɛʁe     1
4997       acharner  ii3S     aʃaʁnɛ     1
5005       acharner  pi1S      aʃaʁn     1
5102        acheter  ai3S      aʃəta     1
5119        acheter   inf      aʃəte     2
5139        acheter  ppMP      aʃəte     1
5140        achever  ai3S      aʃəva     1
5311        acheter  pi3S       aʃɛt     1
5313        acheter  pi3P       aʃɛt     1
6872       admettre  ps3S      admɛt     1
7320         adorer  pc1S    adɔʁəʁɛ     1
7399        adosser  ppFS      adɔse     1
7456        adoucir  ppFS      adusi     1
7539       adresser   inf     adʁɛse     1
8022       affairer  ii3P      afɛʁɛ     1
...             ...   ...        ...   ...
432659      épuiser   inf     ɛpɥize     1
432691      épuiser  ppFS     ɛpɥize     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ     9
434070         être  ii3S        ɛtɛ    73
434135       étaler    pP     ɛtalɑ̃     1
434299       étaler  ppMS      ɛtale     1
434773     éteindre  pi3S       ɛtɛ̃     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435119      étioler    pP    ɛtjɔlɑ̃     1
435172         être  ii1P      ɛtjɔ̃     1
435232       étirer  ai3S      ɛtiʁa     1
435422      étonner  ii3S      ɛtɔnɛ     1
435438      étonner  pi3S       ɛtɔn     1
435444      étonner   inf      ɛtɔne     1
435538     étouffer  ppMS      ɛtufe     1
435742    étrangler  pi3S    ɛtʁɑ̃gl     1
436188      étudier    pP    ɛtydjɑ̃     1
436201      étudier  pi3S      ɛtydi     1
436205      étudier   inf     ɛtydje     2
436316         être  ppMS        ɛte    22
436457       évader   inf      ɛvade     1
436490      évaluer  ai3S     ɛvalya     1
436533      évaluer  pi2S      ɛvaly     1
436679     évanouir  pi3S     ɛvanui     1
436869     éveiller  ppFS      ɛvɛje     1
437021     éventrer  is3S    ɛvɑ̃tʁa     1
437474         être  pi2P         ɛt    11
437476         être   inf        ɛtʁ    14
437497         ôter  ii3S        ɔtɛ     1

[1967 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22 s, total: 1min 38s
Wall time: 30 s

nbChunk 239
4200
1930

             lexeme  case      phono  tir1
40            avoir  pi3S          a    83
125      abandonner  pi1S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     2
162      abandonner  ai3P  abɑ̃dɔnɛʁ     1
292         abattre  fi3S     abatʁa     1
305         abattre  ppMS      abaty     1
307         abattre  ppFS      abaty     1
1129        aborder  ii3P     abɔʁdɛ     1
1148        aborder  fi3S   abɔʁdəʁa     1
1395        aboutir  fi1S    abutiʁɛ     1
1856        abréger  pi1S      abʁɛʒ     1
1859        abréger  pi3S      abʁɛʒ     1
2356         abuser  ii2P     abyzje     1
2579         abîmer  pi3P       abim     1
2774      accaparer  ii3S    akapaʁɛ     1
2964       accepter  pi1S     aksɛpt     1
2969       accepter  pi3P     aksɛpt     1
2971       accepter   inf    aksɛpte     1
3003       accepter  ppMS    aksɛpte     2
3397    accompagner  pi1S    akɔ̃paɲ     1
3434    accompagner  ppFS   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
3475      accomplir  pi3P   akɔ̃plis     1
3517       accorder  ii1S     akɔʁdɛ     1
3519       accorder  ii3S     akɔʁdɛ     1
3536       accorder   inf     akɔʁde     1
3573       accorder  ppFS     akɔʁde     1
3651       accoster  pi3S      akɔst     1
3913       accouder  ppMS      akude     1
4234      accrocher  ii3P     akʁɔʃɛ     1
...             ...   ...        ...   ...
430412      épandre   inf     ɛpɑ̃dʁ     1
431057        épier  ii3P       ɛpjɛ     1
431167        épier   inf       ɛpje     1
432539     éprouver    pP    ɛpʁuvɑ̃     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ     8
434070         être  ii3S        ɛtɛ    68
434134       étaler  ii3S      ɛtalɛ     1
434153       étaler   inf      ɛtale     1
434299       étaler  ppMS      ɛtale     1
434755     éteindre  fi3S    ɛtɛ̃dʁa     1
434782      étendre  pi3S       ɛtɑ̃     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435172         être  ii1P      ɛtjɔ̃     1
435438      étonner  pi3S       ɛtɔn     1
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435471      étonner  ppMS      ɛtɔne     1
435506     étouffer   inf      ɛtufe     1
436201      étudier  pi3S      ɛtydi     1
436227      étudier  pi1P    ɛtydjɔ̃     1
436297       étuver  ppMS      ɛtyve     1
436316         être  ppMS        ɛte    17
436457       évader   inf      ɛvade     1
437301       éviter   inf      ɛvite     1
437417      évoquer    pP     ɛvɔkɑ̃     1
437474         être  pi2P         ɛt    20
437476         être   inf        ɛtʁ    16
437512         ôter   inf        ɔte     1
437536         ôter  is3S        ɔta     1

[1930 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.3 s, total: 1min 37s
Wall time: 29.7 s

nbChunk 240
4200
1934

             lexeme  case     phono  tir1
40            avoir  pi3S         a    80
128      abandonner  pi3S   abɑ̃dɔn     1
297         abattre  pc3S    abatʁɛ     1
299         abattre   inf     abatʁ     3
305         abattre  ppMS     abaty     1
1673        abriter  ii3S    abʁitɛ     1
3406    accompagner   inf  akɔ̃paɲe     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3434    accompagner  ppFS  akɔ̃paɲe     1
3519       accorder  ii3S    akɔʁdɛ     1
3556       accorder  pi2P    akɔʁde     1
3573       accorder  ppFS    akɔʁde     1
4291      accrocher  ppMS    akʁɔʃe     1
4292      accrocher  ppFS    akʁɔʃe     2
4343      accroupir  ii3P  akʁupisɛ     1
4512     accueillir  ai1S     akəji     1
4652      accumuler  pi3S    akymyl     1
4721        accuser  fi3S   akyzəʁa     1
4748        accuser  ppMS     akyze     2
5008       acharner  pi3S     aʃaʁn     1
5119        acheter   inf     aʃəte     2
5136        acheter  ppMS     aʃəte     2
5308        acheter  pi1S      aʃɛt     1
5311        acheter  pi3S      aʃɛt     1
5316        acheter  fi1S   aʃɛtəʁɛ     1
5332        achever  pi3S      aʃɛv     1
6443        adapter  ppMS    adapte     1
6867       admettre  ii1S    admɛtɛ     1
6969        admirer  ii3S    admiʁɛ     1
7012        admirer  pi2P    admiʁe     1
...             ...   ...       ...   ...
424319       écrire  ps3S     ɛkʁiv     1
425650       égarer  pc3S   ɛgaʁəʁɛ     1
425826    égosiller  pi3S    ɛgɔzij     1
427296       élever  ii3S     ɛləvɛ     1
427304       élever   inf     ɛləve     1
427485     éliminer  ppMP   ɛlimine     1
427923       élever  pi3S      ɛlɛv     1
430486     épanouir  fi3S  ɛpanuiʁa     1
431871     éplucher   inf    ɛplyʃe     1
432166      épouser  pc3S   ɛpuzəʁɛ     1
432302      épouser  ppMS     ɛpuze     1
432532     éprouver  ai3S    ɛpʁuva     1
432539     éprouver    pP   ɛpʁuvɑ̃     1
433238   équivaloir  pi3S     ɛkivo     1
433946      établir  ii3S  ɛtablisɛ     1
434048         être  ii3P       ɛtɛ     1
434068         être  ii1S       ɛtɛ    11
434070         être  ii3S       ɛtɛ    69
435054         être  ii2P      ɛtje     3
435172         être  ii1P     ɛtjɔ̃     2
435450      étonner  pc3S   ɛtɔnəʁɛ     2
435471      étonner  ppMS     ɛtɔne     1
436205      étudier   inf    ɛtydje     1
436316         être  ppMS       ɛte    23
437024     éventrer  ppMS   ɛvɑ̃tʁe     1
437299       éviter  pi3P      ɛvit     2
437474         être  pi2P        ɛt    16
437476         être   inf       ɛtʁ    25
437492         ôter  ai3S       ɔta     1
437539         ôter  ppMS       ɔte     1

[1934 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.4 s, total: 1min 39s
Wall time: 29.9 s

nbChunk 241
4200
1955

             lexeme  case      phono  tir1
40            avoir  pi3S          a   102
108      abandonner  ai3S   abɑ̃dɔna     1
114      abandonner    pP  abɑ̃dɔnɑ̃     1
128      abandonner  pi3S    abɑ̃dɔn     1
164      abandonner  ppMS   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
259         abattre    pP     abatɑ̃     1
305         abattre  ppMS      abaty     1
1440        aboutir  pi3S      abuti     1
1884        abréger   inf     abʁɛʒe     1
2070       absorber   inf    absɔʁbe     1
2339         abuser   inf      abyze     1
2574         abîmer  pi1S       abim     1
2763       accabler  ppMS     akable     1
2904      accentuer   inf   aksɑ̃tye     1
2984       accepter  pi2S     aksɛpt     1
3256      accointer  ppMS    akwɛ̃te     1
3400    accompagner  pi3S    akɔ̃paɲ     2
3571       accorder  ppMS     akɔʁde     1
3862       accouder  ai3S      akuda     1
4009       accourir  ii3S      akuʁɛ     1
4234      accrocher  ii3P     akʁɔʃɛ     1
4255      accrocher  pi3S      akʁɔʃ     1
4267      accrocher  fi2P   akʁɔʃəʁe     1
4291      accrocher  ppMS     akʁɔʃe     1
4343      accroupir  ii3P   akʁupisɛ     1
4484     accueillir  pi3P       akœj     1
4688        accuser  ai3S      akyza     1
4849      accélérer  pi2P   aksɛlɛʁe     1
5041       acharner  ppMS     aʃaʁne     1
...             ...   ...        ...   ...
431064        épier  ii3S       ɛpjɛ     1
432156      épouser  pi3S       ɛpuz     1
432160      épouser   inf      ɛpuze     2
432519     éprendre  ppMS       ɛpʁi     1
432535     éprouver  ii1S     ɛpʁuvɛ     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    17
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    71
434135       étaler    pP     ɛtalɑ̃     1
434144       étaler  pi1S       ɛtal     1
434299       étaler  ppMS      ɛtale     1
434726     éteindre  ii3S      ɛtɛɲɛ     1
434768     éteindre  pi1S       ɛtɛ̃     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     2
435254       étirer  pi3S       ɛtiʁ     1
435417      étonner  ai3S      ɛtɔna     1
435422      étonner  ii3S      ɛtɔnɛ     1
435500     étouffer  pi3S       ɛtuf     1
435506     étouffer   inf      ɛtufe     1
436205      étudier   inf     ɛtydje     2
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    16
436815     éveiller  ai3S      ɛvɛja     1
437301       éviter   inf      ɛvite     1
437413      évoquer  ii3P      ɛvɔkɛ     1
437474         être  pi2P         ɛt    10
437476         être   inf        ɛtʁ    13
437492         ôter  ai3S        ɔta     1

[1955 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 21.8 s, total: 1min 38s
Wall time: 29.4 s

nbChunk 242
4200
1907

             lexeme  case       phono  tir1
40            avoir  pi3S           a    87
132      abandonner   inf    abɑ̃dɔne     1
300         abattre  fi2P      abatʁe     1
862          aboyer  pi1S        abwa     1
865          aboyer  pi3S        abwa     1
1133        aborder    pP     abɔʁdɑ̃     1
1169        aborder  pi1P     abɔʁdɔ̃     1
2765       accabler  ppFP      akable     1
2948       accepter  ii1S     aksɛptɛ     1
2950       accepter  ii3S     aksɛptɛ     1
2964       accepter  pi1S      aksɛpt     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     1
3313        accoler  ppMS       akɔle     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3422    accompagner  pi2P    akɔ̃paɲe     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3455      accomplir  fi1P  akɔ̃pliʁɔ̃     1
3571       accorder  ppMS      akɔʁde     1
4237      accrocher  ii3S      akʁɔʃɛ     1
4291      accrocher  ppMS      akʁɔʃe     1
4509     accueillir   inf      akəjiʁ     1
4519     accueillir  ai3S       akəji     1
4720        accuser   inf       akyze     1
5040       acharner  ai3P     aʃaʁnɛʁ     1
5102        acheter  ai3S       aʃəta     1
5119        acheter   inf       aʃəte     5
5125        acheter  pi2P       aʃəte     1
5136        acheter  ppMS       aʃəte     2
5137        acheter  ppFS       aʃəte     1
...             ...   ...         ...   ...
432160      épouser   inf       ɛpuze     1
432532     éprouver  ai3S      ɛpʁuva     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
432556     éprouver   inf      ɛpʁuve     1
432586     éprouver  ppMS      ɛpʁuve     1
433575       ériger  ii3P       ɛʁiʒɛ     1
433586       ériger  pi3P        ɛʁiʒ     1
433922      établir   inf     ɛtabliʁ     1
433969      établir  pi3S      ɛtabli     1
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ    11
434070         être  ii3S         ɛtɛ    83
434831      étendre  ppMS      ɛtɑ̃dy     1
434833      étendre  ppFS      ɛtɑ̃dy     1
434836      étendre  ppFP      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     2
435062    étinceler  ii3S    ɛtɛ̃səlɛ     1
435172         être  ii1P       ɛtjɔ̃     3
435417      étonner  ai3S       ɛtɔna     1
435474      étonner  ppMP       ɛtɔne     1
435512     étouffer  pc3S     ɛtufəʁɛ     1
435538     étouffer  ppMS       ɛtufe     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    22
436629     évanouir  ppFS      ɛvanui     1
436656     évanouir  ii3S    ɛvanuisɛ     1
437301       éviter   inf       ɛvite     1
437458      évoquer  ppMS       ɛvɔke     1
437474         être  pi2P          ɛt    11
437476         être   inf         ɛtʁ    18

[1907 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22 s, total: 1min 37s
Wall time: 29.9 s

nbChunk 243
4200
1935

             lexeme  case     phono  tir1
40            avoir  pi3S         a    93
67         abaisser  pi3S      abɛs     1
164      abandonner  ppMS  abɑ̃dɔne     1
166      abandonner  ppFS  abɑ̃dɔne     2
862          aboyer  pi1S      abwa     1
1133        aborder    pP   abɔʁdɑ̃     1
1884        abréger   inf    abʁɛʒe     1
2070       absorber   inf   absɔʁbe     1
2715       accabler  ii3S    akablɛ     1
2717       accabler    pP   akablɑ̃     1
2902      accentuer  pi3P   aksɑ̃ty     1
2952       accepter    pP  aksɛptɑ̃     1
2964       accepter  pi1S    aksɛpt     1
3385    accompagner  ii3S  akɔ̃paɲɛ     1
3571       accorder  ppMS    akɔʁde     2
4259      accrocher   inf    akʁɔʃe     2
4484     accueillir  pi3P      akœj     1
4503     accueillir  ppFS     akəji     1
4509     accueillir   inf    akəjiʁ     1
4748        accuser  ppMS     akyze     1
5119        acheter   inf     aʃəte     4
5139        acheter  ppMP     aʃəte     2
5311        acheter  pi3S      aʃɛt     1
5313        acheter  pi3P      aʃɛt     1
6414        adapter   inf    adapte     1
6891       admettre   inf    admɛtʁ     1
6969        admirer  ii3S    admiʁɛ     1
7026        admirer  ppMP    admiʁe     1
7028       admettre  ppMS      admi     1
7283        adopter  ppMS    adɔpte     1
...             ...   ...       ...   ...
430590     épargner  ppMS    ɛpaʁɲe     1
430665       épater  ii3S     ɛpatɛ     1
431604     épingler  pi1P  ɛpɛ̃glɔ̃     1
432160      épouser   inf     ɛpuze     3
432532     éprouver  ai3S    ɛpʁuva     1
432537     éprouver  ii3S    ɛpʁuvɛ     1
432586     éprouver  ppMS    ɛpʁuve     1
433231   équivaloir  pc3S  ɛkivɔdʁɛ     1
433939      établir  pi1S    ɛtabli     1
434048         être  ii3P       ɛtɛ     1
434068         être  ii1S       ɛtɛ    13
434070         être  ii3S       ɛtɛ    71
434153       étaler   inf     ɛtale     1
434766     éteindre  fi1P  ɛtɛ̃dʁɔ̃     1
434779     éteindre  ppMP      ɛtɛ̃     1
434821      étendre   inf    ɛtɑ̃dʁ     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     1
435417      étonner  ai3S     ɛtɔna     1
435425      étonner    pP    ɛtɔnɑ̃     1
435438      étonner  pi3S      ɛtɔn     1
436051     étriquer  ppMS    ɛtʁike     1
436316         être  ppMS       ɛte    17
436457       évader   inf     ɛvade     1
436739     évaporer  ppMS   ɛvapɔʁe     1
436820     éveiller  ii3S     ɛvɛjɛ     1
437302       éviter  fi3S   ɛvitəʁa     1
437427      évoquer  pi3S      ɛvɔk     1
437474         être  pi2P        ɛt    15
437476         être   inf       ɛtʁ    20

[1935 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 17 s, total: 1min 29s
Wall time: 52.6 s

nbChunk 244
4200
1912

             lexeme  case     phono  tir1
40            avoir  pi3S         a    95
71         abaisser  pi3P      abɛs     1
132      abandonner   inf  abɑ̃dɔne     1
166      abandonner  ppFS  abɑ̃dɔne     1
170      abandonner  ppMP  abɑ̃dɔne     1
277         abattre  ai3P    abatiʁ     1
887          abolir  ppMS     abɔli     1
1393        aboutir   inf    abutiʁ     1
2116       absoudre   inf    absudʁ     1
2791      accaparer   inf   akapaʁe     1
2948       accepter  ii1S   aksɛptɛ     1
2950       accepter  ii3S   aksɛptɛ     1
2967       accepter  pi3S    aksɛpt     2
2971       accepter   inf   aksɛpte     2
2989       accepter  pi2P   aksɛpte     1
3003       accepter  ppMS   aksɛpte     1
3400    accompagner  pi3S   akɔ̃paɲ     2
4252      accrocher  pi1S     akʁɔʃ     1
4255      accrocher  pi3S     akʁɔʃ     1
4263      accrocher  pc1S  akʁɔʃəʁɛ     1
4292      accrocher  ppFS    akʁɔʃe     1
4320      accroupir  ppMS    akʁupi     1
4501     accueillir  pi2P     akəje     1
4509     accueillir   inf    akəjiʁ     2
4835      accélérer   inf  aksɛlɛʁe     1
5119        acheter   inf     aʃəte     3
5125        acheter  pi2P     aʃəte     1
5136        acheter  ppMS     aʃəte     1
5137        acheter  ppFS     aʃəte     1
5315        acheter  fi3S   aʃɛtəʁa     1
...             ...   ...       ...   ...
432586     éprouver  ppMS    ɛpʁuve     1
432695      épuiser  ppMP    ɛpɥize     1
433111      équiper  pi3P      ɛkip     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     1
434068         être  ii1S       ɛtɛ     8
434070         être  ii3S       ɛtɛ    83
434134       étaler  ii3S     ɛtalɛ     1
434772     éteindre  ppMS      ɛtɛ̃     1
434793      étendre  ps3S     ɛtɑ̃d     1
434811      étendre  ai3S    ɛtɑ̃di     1
434831      étendre  ppMS    ɛtɑ̃dy     1
435172         être  ii1P     ɛtjɔ̃     3
435438      étonner  pi3S      ɛtɔn     1
435444      étonner   inf     ɛtɔne     1
435506     étouffer   inf     ɛtufe     1
435748    étrangler   inf  ɛtʁɑ̃gle     1
435968      étriper  pi3S     ɛtʁip     1
436205      étudier   inf    ɛtydje     1
436218      étudier  pi2S     ɛtydi     1
436316         être  ppMS       ɛte    23
436629     évanouir  ppFS    ɛvanui     1
436835     éveiller   inf     ɛvɛje     2
437025     éventrer  ppFS   ɛvɑ̃tʁe     1
437284       éviter  ii3S     ɛvitɛ     1
437301       éviter   inf     ɛvite     1
437307       éviter  pc3S   ɛvitəʁɛ     1
437424      évoquer  pi1S      ɛvɔk     1
437474         être  pi2P        ɛt     6
437476         être   inf       ɛtʁ    21

[1912 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 15.1 s, total: 1min 27s
Wall time: 47.8 s

nbChunk 245
4200
1905

             lexeme  case       phono  tir1
40            avoir  pi3S           a    85
132      abandonner   inf    abɑ̃dɔne     1
182      abasourdir   inf   abazuʁdiʁ     1
1121        aborder  ai3S      abɔʁda     1
1461         aboyer    pP     abwajɑ̃     1
1543        abraser  ppMS      abʁaze     1
1688        abriter   inf      abʁite     1
1689        abriter  fi3S    abʁitəʁa     1
2042       absorber  ai3S     absɔʁba     1
2228       abstenir  pi2S     abstjɛ̃     1
2715       accabler  ii3S      akablɛ     1
2762       accabler  ai3P     akablɛʁ     1
2766       accabler  ppMP      akable     1
2887      accentuer  ii3S    aksɑ̃tyɛ     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3468      accomplir    pP  akɔ̃plisɑ̃     1
3519       accorder  ii3S      akɔʁdɛ     1
4235      accrocher  ii1S      akʁɔʃɛ     1
4501     accueillir  pi2P       akəje     1
4503     accueillir  ppFS       akəji     1
4509     accueillir   inf      akəjiʁ     2
4713        accuser  pi1S        akyz     1
4748        accuser  ppMS       akyze     1
5119        acheter   inf       aʃəte     4
5136        acheter  ppMS       aʃəte     1
5137        acheter  ppFS       aʃəte     2
5308        acheter  pi1S        aʃɛt     2
5311        acheter  pi3S        aʃɛt     1
...             ...   ...         ...   ...
427923       élever  pi3S        ɛlɛv     1
428561  émerveiller  ii3S    ɛmɛʁvɛjɛ     1
430688       épater   inf       ɛpate     1
432303      épouser  ppFS       ɛpuze     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
432552     éprouver  pi3S       ɛpʁuv     1
432588     éprouver  ppFS      ɛpʁuve     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ    14
434070         être  ii3S         ɛtɛ    75
434762     éteindre   inf      ɛtɛ̃dʁ     1
434794      étendre  pi3P       ɛtɑ̃d     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     1
435438      étonner  pi3S        ɛtɔn     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435726    étrangler  ai3S    ɛtʁɑ̃gla     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
435968      étriper  pi3S       ɛtʁip     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    17
436395      évacuer  pi1S       ɛvaky     1
436820     éveiller  ii3S       ɛvɛjɛ     1
436833     éveiller  pi3P        ɛvɛj     1
436867     éveiller  ppMS       ɛvɛje     1
437301       éviter   inf       ɛvite     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437474         être  pi2P          ɛt    20
437476         être   inf         ɛtʁ    15

[1905 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.2 s, total: 1min 39s
Wall time: 30.9 s

nbChunk 246
4200
1995

             lexeme  case      phono  tir1
40            avoir  pi3S          a    77
125      abandonner  pi1S    abɑ̃dɔn     1
197      abasourdir  ppMP   abazuʁdi     1
261         abattre  ps3S       abat     1
1175        aborder  ppMS     abɔʁde     1
1388        aboutir  ppMS      abuti     1
1934       absenter  ii3S    absɑ̃tɛ     1
2051       absorber  ii3S    absɔʁbɛ     1
2322         abuser  ii1S      abyzɛ     1
2581         abîmer   inf      abime     1
2764       accabler  ppFS     akable     1
3093       acclamer  ii3P     aklamɛ     1
3322     accommoder  ii3S    akɔmɔdɛ     1
3380    accompagner  ai3S   akɔ̃paɲa     1
3381    accompagner  ai1S   akɔ̃paɲɛ     1
3382    accompagner  ii3P   akɔ̃paɲɛ     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3386    accompagner    pP  akɔ̃paɲɑ̃     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     2
3443      accomplir   inf   akɔ̃pliʁ     1
3460      accomplir  pi1S    akɔ̃pli     1
3530       accorder  pi3S      akɔʁd     1
3827      accoucher   inf      akuʃe     1
3913       accouder  ppMS      akude     1
4259      accrocher   inf     akʁɔʃe     1
4293      accrocher  ppFP     akʁɔʃe     1
4511     accueillir  ppMP      akəji     1
4519     accueillir  ai3S      akəji     1
4736        accuser  pi2P      akyze     1
...             ...   ...        ...   ...
432552     éprouver  pi3S      ɛpʁuv     2
432586     éprouver  ppMS     ɛpʁuve     1
432689      épuiser  ppMS     ɛpɥize     1
433922      établir   inf    ɛtabliʁ     2
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ     8
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    58
434782      étendre  pi3S       ɛtɑ̃     1
434831      étendre  ppMS     ɛtɑ̃dy     1
434833      étendre  ppFS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     3
435172         être  ii1P      ɛtjɔ̃     1
435471      étonner  ppMS      ɛtɔne     1
435480     étouffer  ai1S      ɛtufɛ     1
435506     étouffer   inf      ɛtufe     1
435794    étreindre  ii3S     ɛtʁɛɲɛ     1
436201      étudier  pi3S      ɛtydi     1
436205      étudier   inf     ɛtydje     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    22
436647     évanouir  ppMP     ɛvanui     1
436678     évanouir  ai3S     ɛvanui     1
436835     éveiller   inf      ɛvɛje     1
437282       éviter  ii1S      ɛvitɛ     1
437301       éviter   inf      ɛvite     2
437308       éviter  fi2S    ɛvitəʁa     1
437320       éviter  ii1P    ɛvitjɔ̃     1
437474         être  pi2P         ɛt     9
437476         être   inf        ɛtʁ    21

[1995 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22 s, total: 1min 39s
Wall time: 29.7 s

nbChunk 247
4200
1930

             lexeme  case       phono  tir1
40            avoir  pi3S           a    96
67         abaisser  pi3S        abɛs     1
109      abandonner  ai1S    abɑ̃dɔnɛ     1
128      abandonner  pi3S     abɑ̃dɔn     1
133      abandonner  fi3S  abɑ̃dɔnəʁa     1
145      abandonner  pi2S     abɑ̃dɔn     1
1415        aboutir  ii3S     abutisɛ     1
1670        abriter  ii3P      abʁitɛ     1
1897        abréger  pI2P      abʁɛʒe     1
2100       absorber  ppMS     absɔʁbe     1
2574         abîmer  pi1S        abim     1
2967       accepter  pi3S      aksɛpt     1
2997       accepter  pi1P    aksɛptɔ̃     1
3003       accepter  ppMS     aksɛpte     1
3380    accompagner  ai3S    akɔ̃paɲa     1
3386    accompagner    pP   akɔ̃paɲɑ̃     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     3
3436    accompagner  ppMP    akɔ̃paɲe     1
3475      accomplir  pi3P    akɔ̃plis     1
3519       accorder  ii3S      akɔʁdɛ     1
3536       accorder   inf      akɔʁde     2
4103       accourir  ai3S       akuʁy     1
4470     accueillir  ii3P       akəjɛ     1
4720        accuser   inf       akyze     1
4750        accuser  ppFS       akyze     1
4819      accélérer  ai1S    aksɛlɛʁɛ     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     2
5311        acheter  pi3S        aʃɛt     2
...             ...   ...         ...   ...
429700      énerver   inf      ɛnɛʁve     1
430421      épandre  ppMS      ɛpɑ̃dy     1
430557     épargner  pI2S       ɛpaʁɲ     1
432556     éprouver   inf      ɛpʁuve     1
432586     éprouver  ppMS      ɛpʁuve     1
433024   équilibrer  pi3P     ɛkilibʁ     1
433170      équiper  ppFS       ɛkipe     1
433912      établir  ppMS      ɛtabli     1
433923      établir  fi3S    ɛtabliʁa     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    11
434070         être  ii3S         ɛtɛ    81
434782      étendre  pi3S        ɛtɑ̃     1
434833      étendre  ppFS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     2
435438      étonner  pi3S        ɛtɔn     1
435504     étouffer  pi3P        ɛtuf     1
435742    étrangler  pi3S     ɛtʁɑ̃gl     1
435780    étrangler  ppMS    ɛtʁɑ̃gle     1
436316         être  ppMS         ɛte    19
436679     évanouir  pi3S      ɛvanui     1
436820     éveiller  ii3S       ɛvɛjɛ     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437427      évoquer  pi3S        ɛvɔk     1
437431      évoquer   inf       ɛvɔke     1
437458      évoquer  ppMS       ɛvɔke     1
437474         être  pi2P          ɛt    14
437476         être   inf         ɛtʁ    21
437492         ôter  ai3S         ɔta     1

[1930 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.5 s, total: 1min 40s
Wall time: 30.1 s

nbChunk 248
4200
1971

             lexeme  case      phono  tir1
40            avoir  pi3S          a    73
128      abandonner  pi3S    abɑ̃dɔn     1
243         abattre  pi3S        aba     1
299         abattre   inf      abatʁ     1
1034        abonner   inf      abɔne     1
1393        aboutir   inf     abutiʁ     1
1884        abréger   inf     abʁɛʒe     1
2106       absorber  ppMP    absɔʁbe     1
2888      accentuer    pP  aksɑ̃tyɑ̃     1
2971       accepter   inf    aksɛpte     2
3397    accompagner  pi1S    akɔ̃paɲ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3421    accompagner  pI2P   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
3516       accorder  ii3P     akɔʁdɛ     2
3519       accorder  ii3S     akɔʁdɛ     1
3530       accorder  pi3S      akɔʁd     1
3573       accorder  ppFS     akɔʁde     1
3692        accoter    pP     akɔtɑ̃     1
3827      accoucher   inf      akuʃe     1
4482     accueillir  pi3S       akœj     1
4519     accueillir  ai3S      akəji     1
4654      accumuler  pi3P     akymyl     1
5119        acheter   inf      aʃəte     1
5136        acheter  ppMS      aʃəte     1
5173        achever  ppFS      aʃəve     1
5880      acquitter  ppFS      akite     1
6410        adapter  pi3S      adapt     1
6722      adjoindre   inf   adʒwɛ̃dʁ     1
6801        adjuger  ppMS     adʒyʒe     1
...             ...   ...        ...   ...
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    15
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    73
434072       étaler  ai3S      ɛtala     1
434153       étaler   inf      ɛtale     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434775     éteindre  ppFS      ɛtɛ̃t     1
434782      étendre  pi3S       ɛtɑ̃     1
434786      étendre  ii1S     ɛtɑ̃dɛ     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     2
435244       étirer    pP     ɛtiʁɑ̃     1
435254       étirer  pi3S       ɛtiʁ     1
435417      étonner  ai3S      ɛtɔna     1
435435      étonner  pi1S       ɛtɔn     1
435444      étonner   inf      ɛtɔne     1
435500     étouffer  pi3S       ɛtuf     1
435972      étriper   inf     ɛtʁipe     1
436186      étudier  ii3S     ɛtydjɛ     1
436316         être  ppMS        ɛte    23
436398      évacuer  pi3S      ɛvaky     1
436820     éveiller  ii3S      ɛvɛjɛ     1
436867     éveiller  ppMS      ɛvɛje     2
437301       éviter   inf      ɛvite     1
437434      évoquer  pc3P    ɛvɔkəʁɛ     1
437474         être  pi2P         ɛt    13
437476         être   inf        ɛtʁ    14

[1971 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.8 s, total: 1min 36s
Wall time: 29.3 s

nbChunk 249
4200
1907

             lexeme  case       phono  tir1
40            avoir  pi3S           a    90
113      abandonner  ii3S    abɑ̃dɔnɛ     1
132      abandonner   inf    abɑ̃dɔne     1
134      abandonner  fi1S  abɑ̃dɔnəʁɛ     1
243         abattre  pi3S         aba     1
287         abattre  ai3S       abati     1
305         abattre  ppMS       abaty     2
1121        aborder  ai3S      abɔʁda     1
1950       absenter   inf     absɑ̃te     1
2971       accepter   inf     aksɛpte     1
3003       accepter  ppMS     aksɛpte     2
3400    accompagner  pi3S     akɔ̃paɲ     1
3419    accompagner  pi2S     akɔ̃paɲ     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
3440      accomplir  ppFS     akɔ̃pli     1
3443      accomplir   inf    akɔ̃pliʁ     1
3536       accorder   inf      akɔʁde     1
3571       accorder  ppMS      akɔʁde     1
3821      accoucher  pi3S        akuʃ     1
4072       accourir   inf      akuʁiʁ     1
4235      accrocher  ii1S      akʁɔʃɛ     1
4720        accuser   inf       akyze     1
4783        accéder   inf      aksɛde     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     1
5171        achever  ppMS       aʃəve     1
5308        acheter  pi1S        aʃɛt     1
5327        acheter  pi2S        aʃɛt     1
6996        admirer   inf      admiʁe     1
...             ...   ...         ...   ...
429365     émouvoir  ppMS         ɛmy     1
429677      énerver  ii3S      ɛnɛʁvɛ     1
430590     épargner  ppMS      ɛpaʁɲe     1
431163        épier  pi3S         ɛpi     1
432144      épouser  ii3S       ɛpuzɛ     1
432160      épouser   inf       ɛpuze     3
432491     éprendre   inf     ɛpʁɑ̃dʁ     1
432539     éprouver    pP     ɛpʁuvɑ̃     1
432569     éprouver  pi2S       ɛpʁuv     1
433195   équivaloir  ii3S     ɛkivalɛ     1
433912      établir  ppMS      ɛtabli     2
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ    15
434070         être  ii3S         ɛtɛ    86
434768     éteindre  pi1S        ɛtɛ̃     1
434773     éteindre  pi3S        ɛtɛ̃     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
435054         être  ii2P        ɛtje     1
435422      étonner  ii3S       ɛtɔnɛ     1
435438      étonner  pi3S        ɛtɔn     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435471      étonner  ppMS       ɛtɔne     1
435782    étrangler  ppFS    ɛtʁɑ̃gle     1
436316         être  ppMS         ɛte    25
436402      évacuer   inf      ɛvakye     1
436457       évader   inf       ɛvade     1
437301       éviter   inf       ɛvite     2
437474         être  pi2P          ɛt    11
437476         être   inf         ɛtʁ    18
437512         ôter   inf         ɔte     1

[1907 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.3 s, total: 1min 40s
Wall time: 30.3 s

nbChunk 250
4200
1964

             lexeme  case      phono  tir1
40            avoir  pi3S          a    88
132      abandonner   inf   abɑ̃dɔne     2
299         abattre   inf      abatʁ     1
1121        aborder  ai3S     abɔʁda     1
1169        aborder  pi1P    abɔʁdɔ̃     1
1393        aboutir   inf     abutiʁ     1
1460         aboyer  ii3S     abwajɛ     1
2068       absorber  pi3P     absɔʁb     1
2371         abuser  ppMS      abyze     1
2971       accepter   inf    aksɛpte     1
2977       accepter  pc3S  aksɛptəʁɛ     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3438      accomplir  ppMS    akɔ̃pli     1
3475      accomplir  pi3P   akɔ̃plis     1
3536       accorder   inf     akɔʁde     1
4320      accroupir  ppMS     akʁupi     1
4339      accroupir  pi1S     akʁupi     1
4688        accuser  ai3S      akyza     1
5044       acharner  ppMP     aʃaʁne     1
5112        acheter    pP     aʃətɑ̃     1
5119        acheter   inf      aʃəte     1
5136        acheter  ppMS      aʃəte     3
5311        acheter  pi3S       aʃɛt     1
5754       acquérir  pi3S      akjɛʁ     1
6863       admettre  pi1S       admɛ     1
6867       admettre  ii1S     admɛtɛ     1
6872       admettre  ps3S      admɛt     1
7028       admettre  ppMS       admi     1
7283        adopter  ppMS     adɔpte     1
7295         adorer  ii1S      adɔʁɛ     1
...             ...   ...        ...   ...
430856       épeler  ai3S      ɛpəla     1
432303      épouser  ppFS      ɛpuze     1
432533     éprouver  ai1S     ɛpʁuvɛ     1
432535     éprouver  ii1S     ɛpʁuvɛ     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
433912      établir  ppMS     ɛtabli     1
433939      établir  pi1S     ɛtabli     1
434048         être  ii3P        ɛtɛ     1
434068         être  ii1S        ɛtɛ    12
434070         être  ii3S        ɛtɛ    76
434151       étaler  pi3P       ɛtal     1
434768     éteindre  pi1S       ɛtɛ̃     2
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     4
435419      étonner  ii3P      ɛtɔnɛ     1
435420      étonner  ii1S      ɛtɔnɛ     1
435538     étouffer  ppMS      ɛtufe     1
435726    étrangler  ai3S   ɛtʁɑ̃gla     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
436316         être  ppMS        ɛte    21
436484       évader  ppMS      ɛvade     1
436632     évanouir   inf    ɛvanuiʁ     1
436820     éveiller  ii3S      ɛvɛjɛ     1
437025     éventrer  ppFS    ɛvɑ̃tʁe     1
437295       éviter  pi3S       ɛvit     1
437474         être  pi2P         ɛt    24
437476         être   inf        ɛtʁ    17
437497         ôter  ii3S        ɔtɛ     1
437539         ôter  ppMS        ɔte     2

[1964 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.4 s, total: 1min 38s
Wall time: 29.8 s

nbChunk 251
4200
1945

             lexeme  case      phono  tir1
40            avoir  pi3S          a    84
113      abandonner  ii3S   abɑ̃dɔnɛ     1
114      abandonner    pP  abɑ̃dɔnɑ̃     1
128      abandonner  pi3S    abɑ̃dɔn     1
148      abandonner  pi2P   abɑ̃dɔne     2
162      abandonner  ai3P  abɑ̃dɔnɛʁ     1
250         abattre  pi1S        aba     1
1106        abonner  is3S      abɔna     1
1145        aborder  pi3P      abɔʁd     1
1455         aboyer  ai3S     abwaja     1
1457         aboyer  ii3P     abwajɛ     1
1718        abriter  ppFS     abʁite     1
1761        abroger   inf     abʁɔʒe     1
2887      accentuer  ii3S   aksɑ̃tyɛ     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     1
3003       accepter  ppMS    aksɛpte     2
3380    accompagner  ai3S   akɔ̃paɲa     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3527       accorder  pi1S      akɔʁd     1
3534       accorder  pi3P      akɔʁd     1
3556       accorder  pi2P     akɔʁde     1
3827      accoucher   inf      akuʃe     1
3913       accouder  ppMS      akude     1
4230      accrocher  ai3S     akʁɔʃa     1
4259      accrocher   inf     akʁɔʃe     1
4509     accueillir   inf     akəjiʁ     1
4716        accuser  pi3S       akyz     1
4720        accuser   inf      akyze     1
4754        accuser  ppMP      akyze     1
...             ...   ...        ...   ...
428620      émettre  pi3P       ɛmɛt     1
428650     émouvoir  pi3S        ɛmø     1
429691      énerver  pi1S      ɛnɛʁv     1
430558     épargner  pi3S      ɛpaʁɲ     1
430688       épater   inf      ɛpate     1
432386   épouvanter  pi3S    ɛpuvɑ̃t     1
432533     éprouver  ai1S     ɛpʁuvɛ     1
432689      épuiser  ppMS     ɛpɥize     1
433969      établir  pi3S     ɛtabli     1
434048         être  ii3P        ɛtɛ     1
434068         être  ii1S        ɛtɛ    14
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    83
434773     éteindre  pi3S       ɛtɛ̃     1
434782      étendre  pi3S       ɛtɑ̃     1
434811      étendre  ai3S     ɛtɑ̃di     2
434831      étendre  ppMS     ɛtɑ̃dy     1
434853    éterniser  ii3S   ɛtɛʁnizɛ     1
435054         être  ii2P       ɛtje     3
435172         être  ii1P      ɛtjɔ̃     4
435425      étonner    pP     ɛtɔnɑ̃     1
435504     étouffer  pi3P       ɛtuf     1
435538     étouffer  ppMS      ɛtufe     1
436206      étudier  fi3S    ɛtydiʁa     1
436316         être  ppMS        ɛte    18
436867     éveiller  ppMS      ɛvɛje     1
437285       éviter    pP     ɛvitɑ̃     1
437301       éviter   inf      ɛvite     2
437474         être  pi2P         ɛt    14
437476         être   inf        ɛtʁ    20

[1945 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.1 s, total: 1min 37s
Wall time: 29.5 s

nbChunk 252
4200
1922

             lexeme  case      phono  tir1
40            avoir  pi3S          a    80
1121        aborder  ai3S     abɔʁda     1
1393        aboutir   inf     abutiʁ     1
1943       absenter  pi1S     absɑ̃t     1
2967       accepter  pi3S     aksɛpt     2
2971       accepter   inf    aksɛpte     1
2975       accepter  pc1S  aksɛptəʁɛ     1
3003       accepter  ppMS    aksɛpte     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
4178     accoutumer  pi3S     akutym     1
4233      accrocher  ai1S     akʁɔʃɛ     1
4252      accrocher  pi1S      akʁɔʃ     1
4255      accrocher  pi3S      akʁɔʃ     1
4291      accrocher  ppMS     akʁɔʃe     1
4482     accueillir  pi3S       akœj     1
4809      accélérer  pi1S    aksɛlɛʁ     1
5119        acheter   inf      aʃəte     2
5136        acheter  ppMS      aʃəte     1
5140        achever  ai3S      aʃəva     1
5149        achever  ii3S      aʃəvɛ     1
5171        achever  ppMS      aʃəve     2
5321        acheter  fi2S    aʃɛtəʁa     1
6016      actionner   inf    aksjɔne     1
6810        adjurer  ii3S     adʒyʁɛ     1
6862       admettre  pi3S       admɛ     1
6869       admettre  ii3S     admɛtɛ     1
6966        admirer  ii3P     admiʁɛ     1
7297         adorer  ii3S      adɔʁɛ     1
...             ...   ...        ...   ...
432533     éprouver  ai1S     ɛpʁuvɛ     1
432535     éprouver  ii1S     ɛpʁuvɛ     1
432539     éprouver    pP    ɛpʁuvɑ̃     1
432556     éprouver   inf     ɛpʁuve     2
432802     équarrir  ppMS      ɛkaʁi     1
433026   équilibrer   inf   ɛkilibʁe     1
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ    24
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    76
434302       étaler  ppMP      ɛtale     1
434488         être    pP       ɛtɑ̃     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
435054         être  ii2P       ɛtje     1
435129      étioler  pi3S      ɛtjɔl     1
435133      étioler  pi3P      ɛtjɔl     1
435205    étiqueter  pi3S     ɛtikɛt     1
435419      étonner  ii3P      ɛtɔnɛ     1
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435460      étonner  pi2P      ɛtɔne     1
435471      étonner  ppMS      ɛtɔne     1
435538     étouffer  ppMS      ɛtufe     1
436205      étudier   inf     ɛtydje     2
436316         être  ppMS        ɛte    27
436457       évader   inf      ɛvade     1
437285       éviter    pP     ɛvitɑ̃     1
437447      évoquer  pi2P      ɛvɔke     1
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    23

[1922 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22 s, total: 1min 37s
Wall time: 29.4 s

nbChunk 253
4200
1923

              lexeme  case       phono  tir1
40             avoir  pi3S           a    94
101         abaisser  ppMS       abɛse     1
128       abandonner  pi3S     abɑ̃dɔn     1
166       abandonner  ppFS    abɑ̃dɔne     1
170       abandonner  ppMP    abɑ̃dɔne     1
287          abattre  ai3S       abati     1
1132         aborder  ii3S      abɔʁdɛ     1
1133         aborder    pP     abɔʁdɑ̃     1
1147         aborder   inf      abɔʁde     1
1673         abriter  ii3S      abʁitɛ     1
2321          abuser  ii3P       abyzɛ     1
2971        accepter   inf     aksɛpte     2
3003        accepter  ppMS     aksɛpte     1
3406     accompagner   inf    akɔ̃paɲe     1
3410     accompagner  pc1S  akɔ̃paɲəʁɛ     1
3434     accompagner  ppFS    akɔ̃paɲe     1
3443       accomplir   inf    akɔ̃pliʁ     2
3913        accouder  ppMS       akude     1
4292       accrocher  ppFS      akʁɔʃe     1
4294       accrocher  ppMP      akʁɔʃe     1
4337       accroupir  ppMP      akʁupi     1
4482      accueillir  pi3S        akœj     1
4718         accuser  pi3P        akyz     1
4720         accuser   inf       akyze     1
4809       accélérer  pi1S     aksɛlɛʁ     1
5102         acheter  ai3S       aʃəta     1
5119         acheter   inf       aʃəte     1
5136         acheter  ppMS       aʃəte     3
5327         acheter  pi2S        aʃɛt     1
6016       actionner   inf     aksjɔne     1
...              ...   ...         ...   ...
432160       épouser   inf       ɛpuze     1
432297  époustoufler  ppMP   ɛpustufle     1
432421    épouvanter  ppFS    ɛpuvɑ̃te     1
432537      éprouver  ii3S      ɛpʁuvɛ     1
432552      éprouver  pi3S       ɛpʁuv     1
432586      éprouver  ppMS      ɛpʁuve     2
432592      éprouver  ppMP      ɛpʁuve     1
432657       épuiser  pi3P       ɛpɥiz     1
432659       épuiser   inf      ɛpɥize     1
433062    équilibrer  ppMS    ɛkilibʁe     1
433618        ériger  ppFS       ɛʁiʒe     1
433914       établir  ppFS      ɛtabli     1
433922       établir   inf     ɛtabliʁ     1
434048          être  ii3P         ɛtɛ     6
434068          être  ii1S         ɛtɛ     9
434070          être  ii3S         ɛtɛ    79
434135        étaler    pP      ɛtalɑ̃     1
434768      éteindre  pi1S        ɛtɛ̃     1
435172          être  ii1P       ɛtjɔ̃     4
435471       étonner  ppMS       ɛtɔne     1
436218       étudier  pi2S       ɛtydi     1
436316          être  ppMS         ɛte    23
436835      éveiller   inf       ɛvɛje     1
436867      éveiller  ppMS       ɛvɛje     1
437301        éviter   inf       ɛvite     1
437413       évoquer  ii3P       ɛvɔkɛ     1
437416       évoquer  ii3S       ɛvɔkɛ     1
437474          être  pi2P          ɛt     9
437476          être   inf         ɛtʁ    16
437539          ôter  ppMS         ɔte     1

[1923 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.8 s, total: 1min 35s
Wall time: 28.9 s

nbChunk 254
4200
1897

             lexeme  case     phono  tir1
40            avoir  pi3S         a    89
67         abaisser  pi3S      abɛs     1
132      abandonner   inf  abɑ̃dɔne     2
164      abandonner  ppMS  abɑ̃dɔne     1
170      abandonner  ppMP  abɑ̃dɔne     1
243         abattre  pi3S       aba     1
1132        aborder  ii3S    abɔʁdɛ     1
1415        aboutir  ii3S   abutisɛ     1
1440        aboutir  pi3S     abuti     1
2335         abuser  pi3S      abyz     1
2616         abîmer  ppMP     abime     1
2763       accabler  ppMS    akable     1
2904      accentuer   inf  aksɑ̃tye     1
3419    accompagner  pi2S   akɔ̃paɲ     1
3438      accomplir  ppMS   akɔ̃pli     1
4259      accrocher   inf    akʁɔʃe     1
4339      accroupir  pi1S    akʁupi     1
4502     accueillir  ppMS     akəji     1
4686      accumuler  ppMP   akymyle     1
4716        accuser  pi3S      akyz     1
5119        acheter   inf     aʃəte     2
5136        acheter  ppMS     aʃəte     1
5157        achever   inf     aʃəve     1
5171        achever  ppMS     aʃəve     1
5308        acheter  pi1S      aʃɛt     1
6959        admirer  ai3S    admiʁa     1
7184        adonner  pi1S      adɔn     1
7283        adopter  ppMS    adɔpte     1
7313         adorer  ps3S      adɔʁ     1
7535       adresser  pi3S     adʁɛs     1
...             ...   ...       ...   ...
430579     épargner  pi2P    ɛpaʁɲe     1
430668       épater    pP    ɛpatɑ̃     1
430800      épauler  pi3S      ɛpol     1
433954      établir  pi3P   ɛtablis     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    14
434070         être  ii3S       ɛtɛ    74
434147       étaler  pi3S      ɛtal     1
434727     éteindre    pP    ɛtɛɲɑ̃     1
434772     éteindre  ppMS      ɛtɛ̃     1
434811      étendre  ai3S    ɛtɑ̃di     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     2
435244       étirer    pP    ɛtiʁɑ̃     1
435482     étouffer  ii1S     ɛtufɛ     1
435500     étouffer  pi3S      ɛtuf     1
435504     étouffer  pi3P      ɛtuf     1
436316         être  ppMS       ɛte    30
436418      évacuer  pi2P    ɛvakye     1
436432      évacuer  ppFS    ɛvakye     1
436679     évanouir  pi3S    ɛvanui     1
436688     évaporer  ii3S   ɛvapɔʁɛ     1
436867     éveiller  ppMS     ɛvɛje     1
437282       éviter  ii1S     ɛvitɛ     1
437301       éviter   inf     ɛvite     2
437328       éviter  ppMS     ɛvite     1
437453      évoquer  pi1P    ɛvɔkɔ̃     1
437474         être  pi2P        ɛt    12
437476         être   inf       ɛtʁ    26
437508         ôter  pi3S        ot     1

[1897 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.2 s, total: 1min 39s
Wall time: 30 s

nbChunk 255
4200
1952

             lexeme  case       phono  tir1
40            avoir  pi3S           a    92
86         abaisser  pi2S        abɛs     1
128      abandonner  pi3S     abɑ̃dɔn     1
299         abattre   inf       abatʁ     1
313         abattre  ppMP       abaty     1
1050        abonner  pi2P       abɔne     1
1988       absenter  ppMP     absɑ̃te     1
2577         abîmer  pi3S        abim     1
2939       accepter  ai3S     aksɛpta     1
2971       accepter   inf     aksɛpte     2
3404    accompagner  pi3P     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     1
3463      accomplir  pi2S     akɔ̃pli     1
3530       accorder  pi3S       akɔʁd     2
3827      accoucher   inf       akuʃe     1
4237      accrocher  ii3S      akʁɔʃɛ     1
4292      accrocher  ppFS      akʁɔʃe     1
4479     accueillir  pi1S        akœj     1
4511     accueillir  ppMP       akəji     1
4748        accuser  ppMS       akyze     1
4783        accéder   inf      aksɛde     1
5119        acheter   inf       aʃəte     1
5125        acheter  pi2P       aʃəte     1
5136        acheter  ppMS       aʃəte     1
5157        achever   inf       aʃəve     1
5313        acheter  pi3P        aʃɛt     1
5326        acheter  fi3P    aʃɛtəʁɔ̃     1
5327        acheter  pi2S        aʃɛt     1
6016      actionner   inf     aksjɔne     1
6928    administrer   inf  administʁe     1
...             ...   ...         ...   ...
431573     épingler  pi3P      ɛpɛ̃gl     1
432144      épouser  ii3S       ɛpuzɛ     1
432160      épouser   inf       ɛpuze     1
432166      épouser  pc3S     ɛpuzəʁɛ     1
432534     éprouver  ii3P      ɛpʁuvɛ     1
432556     éprouver   inf      ɛpʁuve     1
432689      épuiser  ppMS      ɛpɥize     1
433914      établir  ppFS      ɛtabli     1
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ     7
434070         être  ii3S         ɛtɛ    73
434772     éteindre  ppMS        ɛtɛ̃     1
434773     éteindre  pi3S        ɛtɛ̃     1
434821      étendre   inf      ɛtɑ̃dʁ     1
434868    éterniser   inf    ɛtɛʁnize     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     1
435444      étonner   inf       ɛtɔne     1
435460      étonner  pi2P       ɛtɔne     1
435474      étonner  ppMP       ɛtɔne     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    27
436627     évanouir  ppMS      ɛvanui     1
436807       évaser  ppFS       ɛvaze     1
436821     éveiller    pP      ɛvɛjɑ̃     1
437301       éviter   inf       ɛvite     5
437474         être  pi2P          ɛt    11
437476         être   inf         ɛtʁ    18
437498         ôter    pP        ɔtɑ̃     1
437508         ôter  pi3S          ot     1

[1952 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.7 s, total: 1min 36s
Wall time: 28.8 s

nbChunk 256
4200
1889

             lexeme  case     phono  tir1
40            avoir  pi3S         a    99
71         abaisser  pi3P      abɛs     1
132      abandonner   inf  abɑ̃dɔne     1
168      abandonner  ppFP  abɑ̃dɔne     1
1147        aborder   inf    abɔʁde     1
1175        aborder  ppMS    abɔʁde     1
2610         abîmer  ppMS     abime     1
2971       accepter   inf   aksɛpte     1
2984       accepter  pi2S    aksɛpt     1
3003       accepter  ppMS   aksɛpte     1
3400    accompagner  pi3S   akɔ̃paɲ     3
3440      accomplir  ppFS   akɔ̃pli     1
4291      accrocher  ppMS    akʁɔʃe     1
4540        acculer  pi1S      akyl     1
4862      accélérer  ppMS  aksɛlɛʁe     1
4994       acharner  ii3P    aʃaʁnɛ     1
4997       acharner  ii3S    aʃaʁnɛ     1
5014       acharner   inf    aʃaʁne     1
5102        acheter  ai3S     aʃəta     1
5136        acheter  ppMS     aʃəte     1
5171        achever  ppMS     aʃəve     1
5308        acheter  pi1S      aʃɛt     1
5311        acheter  pi3S      aʃɛt     1
5321        acheter  fi2S   aʃɛtəʁa     1
6064        activer  pi1S     aktiv     1
7297         adorer  ii3S     adɔʁɛ     1
7309         adorer  pi1S      adɔʁ     1
7539       adresser   inf    adʁɛse     1
7541       adresser  fi1S  adʁɛsəʁɛ     1
7989      affaiblir  ii3S  afɛblisɛ     1
...             ...   ...       ...   ...
430562     épargner   inf    ɛpaʁɲe     1
432160      épouser   inf     ɛpuze     1
432586     éprouver  ppMS    ɛpʁuve     2
432691      épuiser  ppFS    ɛpɥize     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     1
434068         être  ii1S       ɛtɛ    21
434069         être  ii2S       ɛtɛ     1
434070         être  ii3S       ɛtɛ    70
434488         être    pP      ɛtɑ̃     2
434768     éteindre  pi1S      ɛtɛ̃     1
434773     éteindre  pi3S      ɛtɛ̃     1
434831      étendre  ppMS    ɛtɑ̃dy     1
434901     éternuer  ai3S   ɛtɛʁnya     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     1
435417      étonner  ai3S     ɛtɔna     1
435748    étrangler   inf  ɛtʁɑ̃gle     1
436316         être  ppMS       ɛte    20
436402      évacuer   inf    ɛvakye     1
436414      évacuer  fi3P  ɛvakyʁɔ̃     1
436457       évader   inf     ɛvade     1
436485       évader  ppFS     ɛvade     1
436516      évaluer  pi3S     ɛvaly     1
437025     éventrer  ppFS   ɛvɑ̃tʁe     1
437295       éviter  pi3S      ɛvit     1
437301       éviter   inf     ɛvite     2
437365      évoluer  pi3P     ɛvɔly     1
437474         être  pi2P        ɛt     8
437476         être   inf       ɛtʁ    22

[1889 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.2 s, total: 1min 39s
Wall time: 30.4 s

nbChunk 257
4200
1961

             lexeme  case      phono  tir1
40            avoir  pi3S          a    97
52         abaisser    pP     abɛsɑ̃     1
114      abandonner    pP  abɑ̃dɔnɑ̃     1
125      abandonner  pi1S    abɑ̃dɔn     1
148      abandonner  pi2P   abɑ̃dɔne     1
243         abattre  pi3S        aba     1
1796        abrutir  ppMS     abʁyti     1
2332         abuser  pi1S       abyz     1
2339         abuser   inf      abyze     1
2594         abîmer  pi2S       abim     1
2947       accepter  ii3P    aksɛptɛ     1
2984       accepter  pi2S     aksɛpt     1
3381    accompagner  ai1S   akɔ̃paɲɛ     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
3571       accorder  ppMS     akɔʁde     2
3827      accoucher   inf      akuʃe     2
4237      accrocher  ii3S     akʁɔʃɛ     1
4255      accrocher  pi3S      akʁɔʃ     1
4293      accrocher  ppFP     akʁɔʃe     1
4323      accroupir   inf    akʁupiʁ     1
4473     accueillir  ii3S      akəjɛ     4
4694        accuser    pP     akyzɑ̃     1
4715        accuser  pI2S       akyz     1
4783        accéder   inf     aksɛde     1
5119        acheter   inf      aʃəte     2
5136        acheter  ppMS      aʃəte     1
5157        achever   inf      aʃəve     1
5171        achever  ppMS      aʃəve     1
...             ...   ...        ...   ...
428882      émonder  ii3S     ɛmɔ̃dɛ     1
430590     épargner  ppMS     ɛpaʁɲe     1
431321    épiloguer   inf    ɛpilɔge     1
432103    époumoner  pi3S     ɛpumɔn     1
432160      épouser   inf      ɛpuze     1
432302      épouser  ppMS      ɛpuze     1
432535     éprouver  ii1S     ɛpʁuvɛ     1
432586     éprouver  ppMS     ɛpʁuve     1
432653      épuiser  pi3S      ɛpɥiz     1
432689      épuiser  ppMS     ɛpɥize     1
434048         être  ii3P        ɛtɛ     1
434068         être  ii1S        ɛtɛ    12
434070         être  ii3S        ɛtɛ    66
434480     étancher  ppMS     ɛtɑ̃ʃe     1
434768     éteindre  pi1S       ɛtɛ̃     1
434789      étendre    pP    ɛtɑ̃dɑ̃     1
434811      étendre  ai3S     ɛtɑ̃di     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434827      étendre  pi1S       ɛtɑ̃     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     1
435442      étonner  pi3P       ɛtɔn     1
435457      étonner  pi2S       ɛtɔn     1
435731    étrangler  ii3S   ɛtʁɑ̃glɛ     1
435999      étriper  ppMS     ɛtʁipe     1
436201      étudier  pi3S      ɛtydi     1
436316         être  ppMS        ɛte    29
437301       éviter   inf      ɛvite     2
437474         être  pi2P         ɛt    10
437476         être   inf        ɛtʁ    22

[1961 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.4 s, total: 1min 40s
Wall time: 30 s

nbChunk 258
4200
1966

             lexeme  case      phono  tir1
40            avoir  pi3S          a    88
114      abandonner    pP  abɑ̃dɔnɑ̃     1
115      abandonner  ai2S   abɑ̃dɔna     1
130      abandonner  pi3P    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     1
258         abattre  ii3S      abatɛ     1
305         abattre  ppMS      abaty     1
1177        aborder  ppFP     abɔʁde     1
1412        aboutir  ii3P    abutisɛ     1
2324         abuser  ii3S      abyzɛ     1
2335         abuser  pi3S       abyz     1
2878      accentuer  ai3S   aksɑ̃tya     1
2884      accentuer  ii3P   aksɑ̃tyɛ     1
2971       accepter   inf    aksɛpte     1
2977       accepter  pc3S  aksɛptəʁɛ     1
3003       accepter  ppMS    aksɛpte     2
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3397    accompagner  pi1S    akɔ̃paɲ     1
3400    accompagner  pi3S    akɔ̃paɲ     2
3433    accompagner  ppMS   akɔ̃paɲe     1
3434    accompagner  ppFS   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     2
4237      accrocher  ii3S     akʁɔʃɛ     1
4259      accrocher   inf     akʁɔʃe     1
4733        accuser  pi2S       akyz     1
4997       acharner  ii3S     aʃaʁnɛ     2
5119        acheter   inf      aʃəte     2
5136        acheter  ppMS      aʃəte     2
5149        achever  ii3S      aʃəvɛ     1
...             ...   ...        ...   ...
429694      énerver  pi3S      ɛnɛʁv     1
429713      énerver  pi2S      ɛnɛʁv     1
429834      énoncer  ai3S     ɛnɔ̃sa     1
432160      épouser   inf      ɛpuze     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
432650      épuiser  pi1S      ɛpɥiz     1
432659      épuiser   inf     ɛpɥize     1
433794      éructer   inf     ɛʁykte     1
433912      établir  ppMS     ɛtabli     1
434048         être  ii3P        ɛtɛ     7
434068         être  ii1S        ɛtɛ    13
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    81
434153       étaler   inf      ɛtale     1
434768     éteindre  pi1S       ɛtɛ̃     1
434782      étendre  pi3S       ɛtɑ̃     2
434831      étendre  ppMS     ɛtɑ̃dy     2
435054         être  ii2P       ɛtje     3
435438      étonner  pi3S       ɛtɔn     1
435444      étonner   inf      ɛtɔne     1
435484     étouffer  ii3S      ɛtufɛ     1
435544     étouffer  ppMP      ɛtufe     1
436198      étudier  pi1S      ɛtydi     1
436201      étudier  pi3S      ɛtydi     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    23
437049     évertuer  ii3S    ɛvɛʁtyɛ     1
437367      évoluer   inf     ɛvɔlye     1
437474         être  pi2P         ɛt    14
437476         être   inf        ɛtʁ    22

[1966 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.8 s, total: 1min 36s
Wall time: 29.3 s

nbChunk 259
4200
1914

             lexeme  case       phono  tir1
40            avoir  pi3S           a    86
164      abandonner  ppMS    abɑ̃dɔne     1
287         abattre  ai3S       abati     2
1393        aboutir   inf      abutiʁ     1
1434        aboutir  ii1P   abutisjɔ̃     1
1943       absenter  pi1S      absɑ̃t     1
2355         abuser  pi2P       abyze     1
2887      accentuer  ii3S    aksɑ̃tyɛ     1
2964       accepter  pi1S      aksɛpt     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     2
2997       accepter  pi1P    aksɛptɔ̃     1
3003       accepter  ppMS     aksɛpte     1
3324     accommoder    pP    akɔmɔdɑ̃     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     1
3421    accompagner  pI2P    akɔ̃paɲe     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3468      accomplir    pP  akɔ̃plisɑ̃     1
3488      accomplir  pi1P  akɔ̃plisɔ̃     1
4212     accoutumer  ppFS     akutyme     1
4272      accrocher  pi2S       akʁɔʃ     1
4291      accrocher  ppMS      akʁɔʃe     1
4294      accrocher  ppMP      akʁɔʃe     1
4713        accuser  pi1S        akyz     1
4748        accuser  ppMS       akyze     1
4750        accuser  ppFS       akyze     1
5012       acharner  pi3P       aʃaʁn     1
5119        acheter   inf       aʃəte     1
...             ...   ...         ...   ...
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    79
434299       étaler  ppMS       ɛtale     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434831      étendre  ppMS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     3
435172         être  ii1P       ɛtjɔ̃     1
435438      étonner  pi3S        ɛtɔn     1
435526     étouffer  pi2P       ɛtufe     1
435540     étouffer  ppFS       ɛtufe     1
436201      étudier  pi3S       ɛtydi     1
436203      étudier  pi3P       ɛtydi     1
436316         être  ppMS         ɛte    20
436398      évacuer  pi3S       ɛvaky     1
436402      évacuer   inf      ɛvakye     1
436432      évacuer  ppFS      ɛvakye     1
436442       évader  ii3S       ɛvadɛ     1
436520      évaluer   inf      ɛvalye     1
436817     éveiller  ii3P       ɛvɛjɛ     1
436835     éveiller   inf       ɛvɛje     1
436890      éventer    pP     ɛvɑ̃tɑ̃     1
436997     éventrer   inf     ɛvɑ̃tʁe     1
437040      éventer  ppMS      ɛvɑ̃te     1
437301       éviter   inf       ɛvite     1
437363      évoluer  pi3S       ɛvɔly     2
437417      évoquer    pP      ɛvɔkɑ̃     1
437427      évoquer  pi3S        ɛvɔk     1
437474         être  pi2P          ɛt     9
437476         être   inf         ɛtʁ    16

[1914 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.5 s, total: 1min 35s
Wall time: 29 s

nbChunk 260
4200
1885

             lexeme  case       phono  tir1
40            avoir  pi3S           a    98
52         abaisser    pP      abɛsɑ̃     1
111      abandonner  ii1S    abɑ̃dɔnɛ     1
164      abandonner  ppMS    abɑ̃dɔne     1
170      abandonner  ppMP    abɑ̃dɔne     1
401        abdiquer  ii3S      abdikɛ     1
865          aboyer  pi3S        abwa     1
1147        aborder   inf      abɔʁde     1
1169        aborder  pi1P     abɔʁdɔ̃     1
1440        aboutir  pi3S       abuti     1
1468         aboyer   inf      abwaje     1
1485         aboyer  ppMS      abwaje     1
1673        abriter  ii3S      abʁitɛ     1
1802        abrutir  fi3S    abʁytiʁa     1
2143       abstenir   inf    abstəniʁ     1
2950       accepter  ii3S     aksɛptɛ     1
2969       accepter  pi3P      aksɛpt     1
2971       accepter   inf     aksɛpte     1
2976       accepter  pc2S   aksɛptəʁɛ     1
3003       accepter  ppMS     aksɛpte     1
3176     acclimater   inf    aklimate     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3537       accorder  fi3S    akɔʁdəʁa     1
4280      accrocher  pi2P      akʁɔʃe     1
4309      accroître  pi3P      akʁwas     1
5107        acheter  ai1S       aʃətɛ     1
5119        acheter   inf       aʃəte     6
5136        acheter  ppMS       aʃəte     3
5157        achever   inf       aʃəve     2
...             ...   ...         ...   ...
432303      épouser  ppFS       ɛpuze     1
432554     éprouver  pi3P       ɛpʁuv     1
432586     éprouver  ppMS      ɛpʁuve     1
432677      épuiser  pi2P      ɛpɥize     1
432770       épurer  ppFS       ɛpyʁe     1
433914      établir  ppFS      ɛtabli     1
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ    15
434070         être  ii3S         ɛtɛ    67
434302       étaler  ppMP       ɛtale     1
434488         être    pP        ɛtɑ̃     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434773     éteindre  pi3S        ɛtɛ̃     1
434831      étendre  ppMS      ɛtɑ̃dy     1
434833      étendre  ppFS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     4
435417      étonner  ai3S       ɛtɔna     1
435435      étonner  pi1S        ɛtɔn     1
435544     étouffer  ppMP       ɛtufe     1
435732    étrangler    pP   ɛtʁɑ̃glɑ̃     1
436316         être  ppMS         ɛte    21
436591  évangéliser   inf  ɛvɑ̃ʒɛlize     1
436629     évanouir  ppFS      ɛvanui     1
436815     éveiller  ai3S       ɛvɛja     1
437301       éviter   inf       ɛvite     1
437413      évoquer  ii3P       ɛvɔkɛ     1
437414      évoquer  ii1S       ɛvɔkɛ     1
437429      évoquer  pi3P        ɛvɔk     1
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    18

[1885 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 21.6 s, total: 1min 37s
Wall time: 29.6 s

nbChunk 261
4200
1908

             lexeme  case        phono  tir1
40            avoir  pi3S            a    98
113      abandonner  ii3S     abɑ̃dɔnɛ     1
125      abandonner  pi1S      abɑ̃dɔn     1
128      abandonner  pi3S      abɑ̃dɔn     1
164      abandonner  ppMS     abɑ̃dɔne     3
1393        aboutir   inf       abutiʁ     1
1425        aboutir  pi3P       abutis     1
1440        aboutir  pi3S        abuti     1
1716        abriter  ppMS       abʁite     1
2070       absorber   inf      absɔʁbe     1
2219       abstenir  fi1P  abstjɛ̃dʁɔ̃     1
2278      abstraire  pi3S       abstʁɛ     1
2371         abuser  ppMS        abyze     1
2506         abêtir   inf       abɛtiʁ     1
2967       accepter  pi3S       aksɛpt     1
2969       accepter  pi3P       aksɛpt     1
2971       accepter   inf      aksɛpte     2
2990       accepter  ii2P     aksɛptje     1
3003       accepter  ppMS      aksɛpte     1
3385    accompagner  ii3S     akɔ̃paɲɛ     1
3400    accompagner  pi3S      akɔ̃paɲ     2
3438      accomplir  ppMS      akɔ̃pli     1
3536       accorder   inf       akɔʁde     1
3571       accorder  ppMS       akɔʁde     1
3573       accorder  ppFS       akɔʁde     1
3868       accouder    pP       akudɑ̃     1
4291      accrocher  ppMS       akʁɔʃe     1
4369      accroupir  pi3S       akʁupi     1
4475     accueillir    pP       akəjɑ̃     1
4509     accueillir   inf       akəjiʁ     1
...             ...   ...          ...   ...
431970      éponger  pI2S        ɛpɔ̃ʒ     1
432056    épouiller   inf        ɛpuje     1
432160      épouser   inf        ɛpuze     1
432302      épouser  ppMS        ɛpuze     1
432586     éprouver  ppMS       ɛpʁuve     1
433196   équivaloir    pP     ɛkivalɑ̃     1
434048         être  ii3P          ɛtɛ     5
434068         être  ii1S          ɛtɛ    18
434070         être  ii3S          ɛtɛ    65
434730     éteindre  pi3P         ɛtɛɲ     1
434773     éteindre  pi3S         ɛtɛ̃     1
434788      étendre  ii3S       ɛtɑ̃dɛ     1
434827      étendre  pi1S         ɛtɑ̃     1
435172         être  ii1P        ɛtjɔ̃     5
435363      étoiler  ii3S       ɛtwalɛ     1
435460      étonner  pi2P        ɛtɔne     1
435471      étonner  ppMS        ɛtɔne     1
435506     étouffer   inf        ɛtufe     1
435540     étouffer  ppFS        ɛtufe     1
436201      étudier  pi3S        ɛtydi     1
436316         être  ppMS          ɛte    28
436490      évaluer  ai3S       ɛvalya     1
436828     éveiller  pi1S         ɛvɛj     1
436831     éveiller  pi3S         ɛvɛj     1
436867     éveiller  ppMS        ɛvɛje     1
437301       éviter   inf        ɛvite     2
437328       éviter  ppMS        ɛvite     2
437474         être  pi2P           ɛt    12
437476         être   inf          ɛtʁ    14
437539         ôter  ppMS          ɔte     1

[1908 rows x 4 columns]

0
CPU times: user 1min 19s, sys: 22.7 s, total: 1min 42s
Wall time: 30.6 s

nbChunk 262
4200
1984

             lexeme  case      phono  tir1
40            avoir  pi3S          a    94
108      abandonner  ai3S   abɑ̃dɔna     1
113      abandonner  ii3S   abɑ̃dɔnɛ     1
164      abandonner  ppMS   abɑ̃dɔne     1
170      abandonner  ppMP   abɑ̃dɔne     1
287         abattre  ai3S      abati     1
1147        aborder   inf     abɔʁde     1
1884        abréger   inf     abʁɛʒe     1
2100       absorber  ppMS    absɔʁbe     1
2734       accabler  pi3P      akabl     1
2947       accepter  ii3P    aksɛptɛ     1
2971       accepter   inf    aksɛpte     1
2973       accepter  fi1S  aksɛptəʁɛ     1
2984       accepter  pi2S     aksɛpt     1
3003       accepter  ppMS    aksɛpte     2
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3438      accomplir  ppMS    akɔ̃pli     1
4234      accrocher  ii3P     akʁɔʃɛ     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4255      accrocher  pi3S      akʁɔʃ     1
4502     accueillir  ppMS      akəji     1
4509     accueillir   inf     akəjiʁ     1
4652      accumuler  pi3S     akymyl     1
4748        accuser  ppMS      akyze     2
5102        acheter  ai3S      aʃəta     1
5108        acheter  ii3P      aʃətɛ     1
5119        acheter   inf      aʃəte     2
5136        acheter  ppMS      aʃəte     2
5137        acheter  ppFS      aʃəte     1
...             ...   ...        ...   ...
432586     éprouver  ppMS     ɛpʁuve     2
433645       éroder  pi3S       ɛʁɔd     1
433912      établir  ppMS     ɛtabli     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ     9
434070         être  ii3S        ɛtɛ    78
434726     éteindre  ii3S      ɛtɛɲɛ     1
434747     éteindre  ai3S      ɛtɛɲi     1
434762     éteindre   inf     ɛtɛ̃dʁ     2
434775     éteindre  ppFS      ɛtɛ̃t     2
434782      étendre  pi3S       ɛtɑ̃     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434811      étendre  ai3S     ɛtɑ̃di     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     4
435260       étirer   inf      ɛtiʁe     1
435417      étonner  ai3S      ɛtɔna     2
435420      étonner  ii1S      ɛtɔnɛ     1
435656     étourdir  ppFS     ɛtuʁdi     1
436316         être  ppMS        ɛte    24
436873     éveiller  ppMP      ɛvɛje     1
437285       éviter    pP     ɛvitɑ̃     1
437295       éviter  pi3S       ɛvit     1
437301       éviter   inf      ɛvite     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    10
437476         être   inf        ɛtʁ    17
437498         ôter    pP       ɔtɑ̃     1

[1984 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.8 s, total: 1min 36s
Wall time: 29.7 s

nbChunk 263
4200
1938

             lexeme  case      phono  tir1
40            avoir  pi3S          a    91
108      abandonner  ai3S   abɑ̃dɔna     1
132      abandonner   inf   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
305         abattre  ppMS      abaty     1
1307        abouler  pi3S       abul     1
1856        abréger  pi1S      abʁɛʒ     1
1951       absenter  fi3S  absɑ̃təʁa     1
2565         abîmer  ii3S      abimɛ     1
2969       accepter  pi3P     aksɛpt     1
2971       accepter   inf    aksɛpte     2
3003       accepter  ppMS    aksɛpte     1
3005       accepter  ppFS    aksɛpte     1
3406    accompagner   inf   akɔ̃paɲe     1
3419    accompagner  pi2S    akɔ̃paɲ     1
3559       accorder  ii1P   akɔʁdjɔ̃     1
3867       accouder  ii3S      akudɛ     1
4291      accrocher  ppMS     akʁɔʃe     2
4652      accumuler  pi3S     akymyl     1
4716        accuser  pi3S       akyz     1
4809      accélérer  pi1S    aksɛlɛʁ     2
4812      accélérer  pi3S    aksɛlɛʁ     1
5119        acheter   inf      aʃəte     1
5136        acheter  ppMS      aʃəte     1
5157        achever   inf      aʃəve     1
5171        achever  ppMS      aʃəve     1
6444        adapter  ppFS     adapte     1
6445        adapter  ppFP     adapte     1
6991        admirer  pi3S      admiʁ     1
7283        adopter  ppMS     adɔpte     1
...             ...   ...        ...   ...
432532     éprouver  ai3S     ɛpʁuva     1
432552     éprouver  pi3S      ɛpʁuv     1
432586     éprouver  ppMS     ɛpʁuve     1
433195   équivaloir  ii3S    ɛkivalɛ     1
433922      établir   inf    ɛtabliʁ     1
433968      établir  ai3S     ɛtabli     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    11
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    55
434672       étayer  ii3P      ɛtɛjɛ     1
434773     éteindre  pi3S       ɛtɛ̃     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     3
435243       étirer  ii3S      ɛtiʁɛ     1
435419      étonner  ii3P      ɛtɔnɛ     1
435460      étonner  pi2P      ɛtɔne     1
435506     étouffer   inf      ɛtufe     1
435542     étouffer  ppFP      ɛtufe     1
435654     étourdir  ppMS     ɛtuʁdi     1
436218      étudier  pi2S      ɛtydi     1
436316         être  ppMS        ɛte    20
436487       évader  ppMP      ɛvade     1
437301       éviter   inf      ɛvite     1
437328       éviter  ppMS      ɛvite     1
437416      évoquer  ii3S      ɛvɔkɛ     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    16

[1938 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.2 s, total: 1min 38s
Wall time: 29.9 s

nbChunk 264
4200
1941

             lexeme  case       phono  tir1
40            avoir  pi3S           a    82
130      abandonner  pi3P     abɑ̃dɔn     1
134      abandonner  fi1S  abɑ̃dɔnəʁɛ     1
148      abandonner  pi2P    abɑ̃dɔne     1
287         abattre  ai3S       abati     1
299         abattre   inf       abatʁ     1
887          abolir  ppMS       abɔli     1
1121        aborder  ai3S      abɔʁda     1
1147        aborder   inf      abɔʁde     1
1415        aboutir  ii3S     abutisɛ     1
1417        aboutir    pP    abutisɑ̃     1
1818        abrutir  pi1S      abʁyti     1
1950       absenter   inf     absɑ̃te     1
2371         abuser  ppMS       abyze     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     4
3406    accompagner   inf    akɔ̃paɲe     2
3434    accompagner  ppFS    akɔ̃paɲe     1
3468      accomplir    pP  akɔ̃plisɑ̃     1
3519       accorder  ii3S      akɔʁdɛ     1
3655       accoster   inf      akɔste     1
3827      accoucher   inf       akuʃe     1
4006       accourir  ii3P       akuʁɛ     1
4237      accrocher  ii3S      akʁɔʃɛ     1
4252      accrocher  pi1S       akʁɔʃ     1
4259      accrocher   inf      akʁɔʃe     1
4292      accrocher  ppFS      akʁɔʃe     1
4502     accueillir  ppMS       akəji     1
4693        accuser  ii3S       akyzɛ     2
4809      accélérer  pi1S     aksɛlɛʁ     1
...             ...   ...         ...   ...
432160      épouser   inf       ɛpuze     2
432167      épouser  fi2S     ɛpuzəʁa     1
432386   épouvanter  pi3S     ɛpuvɑ̃t     1
432552     éprouver  pi3S       ɛpʁuv     2
432659      épuiser   inf      ɛpɥize     1
433195   équivaloir  ii3S     ɛkivalɛ     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    13
434070         être  ii3S         ɛtɛ    72
434692       étayer   inf       ɛtɛje     1
434811      étendre  ai3S      ɛtɑ̃di     1
434831      étendre  ppMS      ɛtɑ̃dy     2
434839      étendre  ppMP      ɛtɑ̃dy     1
434950     éternuer  ppMS     ɛtɛʁnye     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     3
435232       étirer  ai3S       ɛtiʁa     1
435240       étirer  ii3P       ɛtiʁɛ     1
435417      étonner  ai3S       ɛtɔna     1
435438      étonner  pi3S        ɛtɔn     1
435504     étouffer  pi3P        ɛtuf     1
435794    étreindre  ii3S      ɛtʁɛɲɛ     1
436316         être  ppMS         ɛte    17
436458       évader  fi3S     ɛvadəʁa     1
436484       évader  ppMS       ɛvade     1
437301       éviter   inf       ɛvite     2
437367      évoluer   inf      ɛvɔlye     2
437474         être  pi2P          ɛt    18
437476         être   inf         ɛtʁ    13

[1941 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 21.9 s, total: 1min 38s
Wall time: 29.4 s

nbChunk 265
4200
1916

             lexeme  case      phono  tir1
40            avoir  pi3S          a    72
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
162      abandonner  ai3P  abɑ̃dɔnɛʁ     1
164      abandonner  ppMS   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
2051       absorber  ii3S    absɔʁbɛ     1
2143       abstenir   inf   abstəniʁ     1
2755       accabler  ii1P   akabljɔ̃     1
2791      accaparer   inf    akapaʁe     1
3144       acclamer  ppMS     aklame     1
3421    accompagner  pI2P   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
3818      accoucher  pi1S       akuʃ     1
4255      accrocher  pi3S      akʁɔʃ     2
4259      accrocher   inf     akʁɔʃe     1
4291      accrocher  ppMS     akʁɔʃe     1
4713        accuser  pi1S       akyz     1
4748        accuser  ppMS      akyze     1
4783        accéder   inf     aksɛde     1
4835      accélérer   inf   aksɛlɛʁe     1
5012       acharner  pi3P      aʃaʁn     1
5136        acheter  ppMS      aʃəte     3
5171        achever  ppMS      aʃəve     1
5311        acheter  pi3S       aʃɛt     1
5338        achever  fi3S    aʃɛvəʁa     1
5806       acquérir  ppMP        aki     1
5814       acquérir  ppFP       akiz     1
5998      actionner    pP   aksjɔnɑ̃     1
6414        adapter   inf     adapte     1
...             ...   ...        ...   ...
432660      épuiser  fi3S   ɛpɥizəʁa     1
432689      épuiser  ppMS     ɛpɥize     1
433922      établir   inf    ɛtabliʁ     1
433943      établir  ii3P   ɛtablisɛ     1
433968      établir  ai3S     ɛtabli     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    15
434070         être  ii3S        ɛtɛ    77
434727     éteindre    pP     ɛtɛɲɑ̃     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434773     éteindre  pi3S       ɛtɛ̃     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434829      étendre  pi2S       ɛtɑ̃     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     2
435251       étirer  pi1S       ɛtiʁ     1
435438      étonner  pi3S       ɛtɔn     1
435457      étonner  pi2S       ɛtɔn     1
435544     étouffer  ppMP      ɛtufe     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    19
436381      évacuer  ii3S     ɛvakyɛ     1
436835     éveiller   inf      ɛvɛje     1
437328       éviter  ppMS      ɛvite     1
437474         être  pi2P         ɛt    10
437476         être   inf        ɛtʁ    19
437497         ôter  ii3S        ɔtɛ     1
437510         ôter  pi3P         ot     1

[1916 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.5 s, total: 1min 41s
Wall time: 30.2 s

nbChunk 266
4200
1982

             lexeme  case      phono  tir1
40            avoir  pi3S          a    95
128      abandonner  pi3S    abɑ̃dɔn     2
132      abandonner   inf   abɑ̃dɔne     1
1147        aborder   inf     abɔʁde     1
1688        abriter   inf     abʁite     1
2237       abstenir  ai1S     abstɛ̃     1
2347         abuser  fi2P    abyzəʁe     1
2904      accentuer   inf   aksɑ̃tye     1
2946       accepter  ai1S    aksɛptɛ     1
2952       accepter    pP   aksɛptɑ̃     2
2967       accepter  pi3S     aksɛpt     1
3007       accepter  ppFP    aksɛpte     1
3096       acclamer  ii3S     aklamɛ     1
3386    accompagner    pP  akɔ̃paɲɑ̃     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3404    accompagner  pi3P    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3465      accomplir  ii1S  akɔ̃plisɛ     1
3530       accorder  pi3S      akɔʁd     1
3827      accoucher   inf      akuʃe     1
4234      accrocher  ii3P     akʁɔʃɛ     1
4291      accrocher  ppMS     akʁɔʃe     1
4381      accroître   inf    akʁwatʁ     1
4504     accueillir  ppFP      akəji     1
4720        accuser   inf      akyze     1
5119        acheter   inf      aʃəte     5
5136        acheter  ppMS      aʃəte     2
5807       acquérir  ppMS        aki     1
6528        adhérer  pi3S       adɛʁ     1
...             ...   ...        ...   ...
428663     émietter  ai3S     ɛmjɛta     1
430485     épanouir   inf    ɛpanuiʁ     1
431609     épingler  ppMS    ɛpɛ̃gle     1
432160      épouser   inf      ɛpuze     2
432537     éprouver  ii3S     ɛpʁuvɛ     2
432552     éprouver  pi3S      ɛpʁuv     1
432588     éprouver  ppFS     ɛpʁuve     1
433170      équiper  ppFS      ɛkipe     1
433355      érafler  ppFS     ɛʁafle     1
434048         être  ii3P        ɛtɛ     1
434068         être  ii1S        ɛtɛ    12
434070         être  ii3S        ɛtɛ    76
434758     éteindre  pc1S    ɛtɛ̃dʁɛ     1
434773     éteindre  pi3S       ɛtɛ̃     2
434868    éterniser   inf   ɛtɛʁnize     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     5
435417      étonner  ai3S      ɛtɔna     1
435422      étonner  ii3S      ɛtɔnɛ     1
435442      étonner  pi3P       ɛtɔn     1
435451      étonner  fi2S    ɛtɔnəʁa     1
435506     étouffer   inf      ɛtufe     3
436226      étudier  pI1P    ɛtydjɔ̃     1
436316         être  ppMS        ɛte    27
437301       éviter   inf      ɛvite     2
437328       éviter  ppMS      ɛvite     1
437474         être  pi2P         ɛt    10
437476         être   inf        ɛtʁ    15
437508         ôter  pi3S         ot     1
437539         ôter  ppMS        ɔte     1

[1982 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.5 s, total: 1min 40s
Wall time: 30 s

nbChunk 267
4200
1967

             lexeme  case      phono  tir1
40            avoir  pi3S          a    85
114      abandonner    pP  abɑ̃dɔnɑ̃     1
128      abandonner  pi3S    abɑ̃dɔn     1
130      abandonner  pi3P    abɑ̃dɔn     1
1147        aborder   inf     abɔʁde     1
1461         aboyer    pP    abwajɑ̃     1
2971       accepter   inf    aksɛpte     1
3003       accepter  ppMS    aksɛpte     4
3313        accoler  ppMS      akɔle     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3460      accomplir  pi1S    akɔ̃pli     1
3563       accorder  pI1P    akɔʁdɔ̃     1
3862       accouder  ai3S      akuda     1
4259      accrocher   inf     akʁɔʃe     1
4280      accrocher  pi2P     akʁɔʃe     1
4291      accrocher  ppMS     akʁɔʃe     1
4294      accrocher  ppMP     akʁɔʃe     1
4502     accueillir  ppMS      akəji     1
4504     accueillir  ppFP      akəji     1
4716        accuser  pi3S       akyz     1
5048      acheminer  ai3S    aʃəmina     1
5119        acheter   inf      aʃəte     5
5137        acheter  ppFS      aʃəte     1
5150        achever    pP     aʃəvɑ̃     1
5316        acheter  fi1S    aʃɛtəʁɛ     1
5327        acheter  pi2S       aʃɛt     1
5905       acquérir   inf     akɛʁiʁ     1
6108        activer  ppMS     aktive     1
6414        adapter   inf     adapte     1
...             ...   ...        ...   ...
432537     éprouver  ii3S     ɛpʁuvɛ     1
433571       ériger  pi3S       ɛʁiʒ     1
433912      établir  ppMS     ɛtabli     1
433939      établir  pi1S     ɛtabli     1
433947      établir    pP  ɛtablisɑ̃     1
434048         être  ii3P        ɛtɛ     6
434068         être  ii1S        ɛtɛ    16
434069         être  ii2S        ɛtɛ     2
434070         être  ii3S        ɛtɛ    68
434147       étaler  pi3S       ɛtal     1
434296       étaler  is3S      ɛtala     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434831      étendre  ppMS     ɛtɑ̃dy     2
435172         être  ii1P      ɛtjɔ̃     3
435435      étonner  pi1S       ɛtɔn     1
435457      étonner  pi2S       ɛtɔn     1
435472      étonner  ppFS      ɛtɔne     1
435742    étrangler  pi3S    ɛtʁɑ̃gl     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
436205      étudier   inf     ɛtydje     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    23
436500      évaluer    pP    ɛvalyɑ̃     1
437027     éventrer  ppMP    ɛvɑ̃tʁe     1
437284       éviter  ii3S      ɛvitɛ     1
437301       éviter   inf      ɛvite     2
437367      évoluer   inf     ɛvɔlye     1
437413      évoquer  ii3P      ɛvɔkɛ     2
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    21

[1967 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22 s, total: 1min 39s
Wall time: 29.8 s

nbChunk 268
4200
1936

             lexeme  case     phono  tir1
40            avoir  pi3S         a    70
113      abandonner  ii3S  abɑ̃dɔnɛ     1
128      abandonner  pi3S   abɑ̃dɔn     1
148      abandonner  pi2P  abɑ̃dɔne     1
177      abasourdir  ppMS  abazuʁdi     1
305         abattre  ppMS     abaty     1
2335         abuser  pi3S      abyz     1
2371         abuser  ppMS     abyze     1
2372         abuser  ppFS     abyze     1
2581         abîmer   inf     abime     1
2948       accepter  ii1S   aksɛptɛ     1
2971       accepter   inf   aksɛpte     2
3003       accepter  ppMS   aksɛpte     1
3005       accepter  ppFS   aksɛpte     2
3406    accompagner   inf  akɔ̃paɲe     2
3433    accompagner  ppMS  akɔ̃paɲe     1
3436    accompagner  ppMP  akɔ̃paɲe     1
3438      accomplir  ppMS   akɔ̃pli     1
3440      accomplir  ppFS   akɔ̃pli     1
3443      accomplir   inf  akɔ̃pliʁ     1
3519       accorder  ii3S    akɔʁdɛ     1
3530       accorder  pi3S     akɔʁd     1
3571       accorder  ppMS    akɔʁde     1
4006       accourir  ii3P     akuʁɛ     1
4291      accrocher  ppMS    akʁɔʃe     2
5119        acheter   inf     aʃəte     3
5315        acheter  fi3S   aʃɛtəʁa     1
6054        activer    pP   aktivɑ̃     1
7312         adorer  pi3S      adɔʁ     2
7314         adorer  pi3P      adɔʁ     1
...             ...   ...       ...   ...
432636      épuiser  ii1S    ɛpɥizɛ     1
432660      épuiser  fi3S  ɛpɥizəʁa     1
433113      équiper   inf     ɛkipe     1
433912      établir  ppMS    ɛtabli     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    14
434070         être  ii3S       ɛtɛ    72
434134       étaler  ii3S     ɛtalɛ     1
434135       étaler    pP    ɛtalɑ̃     1
434488         être    pP      ɛtɑ̃     1
434726     éteindre  ii3S     ɛtɛɲɛ     1
434747     éteindre  ai3S     ɛtɛɲi     1
434821      étendre   inf    ɛtɑ̃dʁ     1
434831      étendre  ppMS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     1
435254       étirer  pi3S      ɛtiʁ     1
435422      étonner  ii3S     ɛtɔnɛ     1
436205      étudier   inf    ɛtydje     2
436316         être  ppMS       ɛte    12
436457       évader   inf     ɛvade     1
436867     éveiller  ppMS     ɛvɛje     1
436869     éveiller  ppFS     ɛvɛje     1
437060     évertuer  pi3S    ɛvɛʁty     1
437301       éviter   inf     ɛvite     1
437365      évoluer  pi3P     ɛvɔly     1
437417      évoquer    pP    ɛvɔkɑ̃     1
437474         être  pi2P        ɛt    14
437476         être   inf       ɛtʁ    20

[1936 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.7 s, total: 1min 36s
Wall time: 29 s

nbChunk 269
4200
1900

             lexeme  case      phono  tir1
40            avoir  pi3S          a    79
113      abandonner  ii3S   abɑ̃dɔnɛ     1
128      abandonner  pi3S    abɑ̃dɔn     1
304         abattre  fi3P    abatʁɔ̃     1
1159        aborder  fi3P  abɔʁdəʁɔ̃     1
1455         aboyer  ai3S     abwaja     1
1818        abrutir  pi1S     abʁyti     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     1
3003       accepter  ppMS    aksɛpte     2
3315        accoler  ppFP      akɔle     1
3382    accompagner  ii3P   akɔ̃paɲɛ     2
3406    accompagner   inf   akɔ̃paɲe     1
3436    accompagner  ppMP   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     2
4482     accueillir  pi3S       akœj     1
4509     accueillir   inf     akəjiʁ     2
4748        accuser  ppMS      akyze     1
4994       acharner  ii3P     aʃaʁnɛ     1
5008       acharner  pi3S      aʃaʁn     1
5119        acheter   inf      aʃəte     2
5125        acheter  pi2P      aʃəte     1
5137        acheter  ppFS      aʃəte     1
5315        acheter  fi3S    aʃɛtəʁa     1
5788     acquiescer  ai1S     akjɛsɛ     1
6967        admirer  ii1S     admiʁɛ     1
6996        admirer   inf     admiʁe     1
7018        admirer  pi1P    admiʁɔ̃     1
7283        adopter  ppMS     adɔpte     1
7309         adorer  pi1S       adɔʁ     1
...             ...   ...        ...   ...
434488         être    pP       ɛtɑ̃     2
434762     éteindre   inf     ɛtɛ̃dʁ     2
434772     éteindre  ppMS       ɛtɛ̃     1
434775     éteindre  ppFS      ɛtɛ̃t     1
434811      étendre  ai3S     ɛtɑ̃di     1
434861    éterniser  pi1S    ɛtɛʁniz     1
435054         être  ii2P       ɛtje     3
435172         être  ii1P      ɛtjɔ̃     2
435230    étiqueter  ppFP    ɛtikəte     1
435293       étirer  ppMS      ɛtiʁe     1
435422      étonner  ii3S      ɛtɔnɛ     1
435438      étonner  pi3S       ɛtɔn     1
435484     étouffer  ii3S      ɛtufɛ     1
435500     étouffer  pi3S       ɛtuf     1
435794    étreindre  ii3S     ɛtʁɛɲɛ     1
435828    étreindre   inf    ɛtʁɛ̃dʁ     1
436000      étriper  ppFS     ɛtʁipe     1
436186      étudier  ii3S     ɛtydjɛ     1
436316         être  ppMS        ɛte    19
436402      évacuer   inf     ɛvakye     1
436816     éveiller  ai1S      ɛvɛjɛ     1
436867     éveiller  ppMS      ɛvɛje     1
436873     éveiller  ppMP      ɛvɛje     1
437285       éviter    pP     ɛvitɑ̃     1
437295       éviter  pi3S       ɛvit     1
437301       éviter   inf      ɛvite     4
437303       éviter  fi1S    ɛvitəʁɛ     1
437328       éviter  ppMS      ɛvite     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    17

[1900 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 21.9 s, total: 1min 38s
Wall time: 29.7 s

nbChunk 270
4200
1938

             lexeme  case      phono  tir1
40            avoir  pi3S          a    76
45         abaisser  ai3S      abɛsa     1
132      abandonner   inf   abɑ̃dɔne     2
148      abandonner  pi2P   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
305         abattre  ppMS      abaty     1
982         abonder  pi3P      abɔ̃d     1
1468         aboyer   inf     abwaje     1
1884        abréger   inf     abʁɛʒe     1
2031       absoudre  pi3P     absɔlv     1
2581         abîmer   inf      abime     1
2967       accepter  pi3S     aksɛpt     2
3144       acclamer  ppMS     aklame     1
3422    accompagner  pi2P   akɔ̃paɲe     1
3434    accompagner  ppFS   akɔ̃paɲe     1
3438      accomplir  ppMS    akɔ̃pli     2
3443      accomplir   inf   akɔ̃pliʁ     1
3445      accomplir  fi1S  akɔ̃pliʁɛ     1
3530       accorder  pi3S      akɔʁd     1
3536       accorder   inf     akɔʁde     1
3863       accouder  ai1S      akudɛ     1
4072       accourir   inf     akuʁiʁ     1
5119        acheter   inf      aʃəte     5
5311        acheter  pi3S       aʃɛt     1
5318        acheter  pc1S    aʃɛtəʁɛ     1
6446        adapter  ppMP     adapte     1
6991        admirer  pi3S      admiʁ     1
7011        admirer  pI2P     admiʁe     1
7031       admettre  ppFS      admiz     1
7284        adopter  ppFS     adɔpte     1
...             ...   ...        ...   ...
430042     énumérer   inf    ɛnymɛʁe     1
430562     épargner   inf     ɛpaʁɲe     2
431575     épingler   inf    ɛpɛ̃gle     1
431611     épingler  ppFS    ɛpɛ̃gle     1
432160      épouser   inf      ɛpuze     2
432169      épouser  pc2P   ɛpuzəʁje     1
432302      épouser  ppMS      ɛpuze     1
432539     éprouver    pP    ɛpʁuvɑ̃     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    10
434070         être  ii3S        ɛtɛ    48
434775     éteindre  ppFS      ɛtɛ̃t     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434831      étendre  ppMS     ɛtɑ̃dy     2
435054         être  ii2P       ɛtje     1
435438      étonner  pi3S       ɛtɔn     1
435500     étouffer  pi3S       ɛtuf     1
435684     étourdir  ii3S   ɛtuʁdisɛ     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    24
436484       évader  ppMS      ɛvade     1
436520      évaluer   inf     ɛvalye     1
436632     évanouir   inf    ɛvanuiʁ     1
436817     éveiller  ii3P      ɛvɛjɛ     1
436869     éveiller  ppFS      ɛvɛje     1
436890      éventer    pP    ɛvɑ̃tɑ̃     1
437284       éviter  ii3S      ɛvitɛ     1
437474         être  pi2P         ɛt    20
437476         être   inf        ɛtʁ    22
437498         ôter    pP       ɔtɑ̃     1

[1938 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.6 s, total: 1min 40s
Wall time: 30.7 s

nbChunk 271
4200
1983

             lexeme  case      phono  tir1
40            avoir  pi3S          a    93
132      abandonner   inf   abɑ̃dɔne     2
305         abattre  ppMS      abaty     1
307         abattre  ppFS      abaty     1
1388        aboutir  ppMS      abuti     1
1684        abriter  pi3S      abʁit     1
1688        abriter   inf     abʁite     1
2736       accabler   inf     akable     2
2763       accabler  ppMS     akable     1
2888      accentuer    pP  aksɑ̃tyɑ̃     1
2947       accepter  ii3P    aksɛptɛ     1
2971       accepter   inf    aksɛpte     1
2994       accepter  ii1P  aksɛptjɔ̃     1
2997       accepter  pi1P   aksɛptɔ̃     1
2999       accepter  is3S    aksɛpta     1
3386    accompagner    pP  akɔ̃paɲɑ̃     1
3406    accompagner   inf   akɔ̃paɲe     1
3463      accomplir  pi2S    akɔ̃pli     1
3556       accorder  pi2P     akɔʁde     1
4093       accourir  ppFP      akuʁy     1
4473     accueillir  ii3S      akəjɛ     1
4482     accueillir  pi3S       akœj     1
4720        accuser   inf      akyze     1
5119        acheter   inf      aʃəte     1
5146        achever  ii3P      aʃəvɛ     2
5332        achever  pi3S       aʃɛv     1
5807       acquérir  ppMS        aki     1
6732      adjoindre  ppMS     adʒwɛ̃     1
6969        admirer  ii3S     admiʁɛ     1
6996        admirer   inf     admiʁe     1
...             ...   ...        ...   ...
432162      épouser  fi1S    ɛpuzəʁɛ     1
432532     éprouver  ai3S     ɛpʁuva     1
433195   équivaloir  ii3S    ɛkivalɛ     1
433922      établir   inf    ɛtabliʁ     1
433969      établir  pi3S     ɛtabli     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ     8
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    83
434072       étaler  ai3S      ɛtala     1
434773     éteindre  pi3S       ɛtɛ̃     1
434811      étendre  ai3S     ɛtɑ̃di     1
434833      étendre  ppFS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     2
435231    étiqueter  ppMP    ɛtikəte     1
435506     étouffer   inf      ɛtufe     1
435742    étrangler  pi3S    ɛtʁɑ̃gl     1
436186      étudier  ii3S     ɛtydjɛ     1
436316         être  ppMS        ɛte    20
436890      éventer    pP    ɛvɑ̃tɑ̃     1
436997     éventrer   inf    ɛvɑ̃tʁe     1
437244    éviscérer   inf    ɛvisɛʁe     1
437301       éviter   inf      ɛvite     1
437302       éviter  fi3S    ɛvitəʁa     1
437328       éviter  ppMS      ɛvite     1
437417      évoquer    pP     ɛvɔkɑ̃     1
437474         être  pi2P         ɛt    16
437476         être   inf        ɛtʁ    23
437512         ôter   inf        ɔte     1

[1983 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.9 s, total: 1min 36s
Wall time: 29.1 s

nbChunk 272
4200
1917

             lexeme  case      phono  tir1
40            avoir  pi3S          a    98
73         abaisser   inf      abɛse     1
108      abandonner  ai3S   abɑ̃dɔna     1
164      abandonner  ppMS   abɑ̃dɔne     2
313         abattre  ppMP      abaty     1
1326        abouler  pI2P      abule     1
1485         aboyer  ppMS     abwaje     1
1859        abréger  pi3S      abʁɛʒ     1
1884        abréger   inf     abʁɛʒe     1
2027       absoudre  ii3S    absɔlvɛ     1
2730       accabler  pi3S      akabl     1
2766       accabler  ppMP     akable     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     1
2974       accepter  pc3P  aksɛptəʁɛ     1
3322     accommoder  ii3S    akɔmɔdɛ     1
3397    accompagner  pi1S    akɔ̃paɲ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3422    accompagner  pi2P   akɔ̃paɲe     1
3527       accorder  pi1S      akɔʁd     1
3534       accorder  pi3P      akɔʁd     1
3571       accorder  ppMS     akɔʁde     1
4091       accourir  ppMS      akuʁy     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4255      accrocher  pi3S      akʁɔʃ     1
4812      accélérer  pi3S    aksɛlɛʁ     1
5119        acheter   inf      aʃəte     1
5136        acheter  ppMS      aʃəte     1
5792     acquiescer  ii3S     akjɛsɛ     1
5807       acquérir  ppMS        aki     1
...             ...   ...        ...   ...
432552     éprouver  pi3S      ɛpʁuv     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     6
434068         être  ii1S        ɛtɛ    17
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    69
434821      étendre   inf     ɛtɑ̃dʁ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     4
435172         être  ii1P      ɛtjɔ̃     7
435254       étirer  pi3S       ɛtiʁ     1
435417      étonner  ai3S      ɛtɔna     1
435435      étonner  pi1S       ɛtɔn     1
435471      étonner  ppMS      ɛtɔne     1
435506     étouffer   inf      ɛtufe     1
435780    étrangler  ppMS   ɛtʁɑ̃gle     1
436205      étudier   inf     ɛtydje     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    16
436402      évacuer   inf     ɛvakye     1
436457       évader   inf      ɛvade     1
436828     éveiller  pi1S       ɛvɛj     1
437282       éviter  ii1S      ɛvitɛ     1
437285       éviter    pP     ɛvitɑ̃     1
437295       éviter  pi3S       ɛvit     1
437301       éviter   inf      ɛvite     2
437316       éviter  pI2P      ɛvite     1
437474         être  pi2P         ɛt    13
437476         être   inf        ɛtʁ    24
437522         ôter  pc1P    ɔtəʁjɔ̃     1

[1917 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.1 s, total: 1min 37s
Wall time: 29.8 s

nbChunk 273
4200
1940

             lexeme  case     phono  tir1
40            avoir  pi3S         a    90
108      abandonner  ai3S  abɑ̃dɔna     1
111      abandonner  ii1S  abɑ̃dɔnɛ     1
148      abandonner  pi2P  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     1
287         abattre  ai3S     abati     1
1670        abriter  ii3P    abʁitɛ     1
1796        abrutir  ppMS    abʁyti     1
2717       accabler    pP   akablɑ̃     1
2964       accepter  pi1S    aksɛpt     1
3385    accompagner  ii3S  akɔ̃paɲɛ     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3419    accompagner  pi2S   akɔ̃paɲ     1
3435    accompagner  ppFP  akɔ̃paɲe     1
3438      accomplir  ppMS   akɔ̃pli     1
3443      accomplir   inf  akɔ̃pliʁ     1
3536       accorder   inf    akɔʁde     2
3571       accorder  ppMS    akɔʁde     1
3827      accoucher   inf     akuʃe     1
4255      accrocher  pi3S     akʁɔʃ     2
4471     accueillir  ii1S     akəjɛ     1
4521     accueillir  pi1P    akəjɔ̃     1
5107        acheter  ai1S     aʃətɛ     1
5119        acheter   inf     aʃəte     2
5136        acheter  ppMS     aʃəte     3
5137        acheter  ppFS     aʃəte     1
5139        acheter  ppMP     aʃəte     1
5308        acheter  pi1S      aʃɛt     1
5316        acheter  fi1S   aʃɛtəʁɛ     1
6877       admettre  pi2P    admɛte     1
...             ...   ...       ...   ...
432160      épouser   inf     ɛpuze     3
432537     éprouver  ii3S    ɛpʁuvɛ     1
432552     éprouver  pi3S     ɛpʁuv     2
433912      établir  ppMS    ɛtabli     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    12
434069         être  ii2S       ɛtɛ     1
434070         être  ii3S       ɛtɛ    71
434131       étaler  ii3P     ɛtalɛ     1
434302       étaler  ppMP     ɛtale     1
434747     éteindre  ai3S     ɛtɛɲi     1
434786      étendre  ii1S    ɛtɑ̃dɛ     1
434839      étendre  ppMP    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     4
435243       étirer  ii3S     ɛtiʁɛ     1
435258       étirer  pi3P      ɛtiʁ     1
435474      étonner  ppMP     ɛtɔne     1
435500     étouffer  pi3S      ɛtuf     1
436316         être  ppMS       ɛte    15
436402      évacuer   inf    ɛvakye     1
436980     éventrer  ii3S   ɛvɑ̃tʁɛ     1
437292       éviter  pi1S      ɛvit     1
437295       éviter  pi3S      ɛvit     1
437301       éviter   inf     ɛvite     4
437349      évoluer  ii3P    ɛvɔlyɛ     1
437474         être  pi2P        ɛt    17
437476         être   inf       ɛtʁ    24
437512         ôter   inf       ɔte     1
437539         ôter  ppMS       ɔte     1

[1940 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.7 s, total: 1min 40s
Wall time: 30.1 s

nbChunk 274
4200
1981

             lexeme  case      phono  tir1
40            avoir  pi3S          a    73
113      abandonner  ii3S   abɑ̃dɔnɛ     1
132      abandonner   inf   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
1393        aboutir   inf     abutiʁ     1
2371         abuser  ppMS      abyze     1
2506         abêtir   inf     abɛtiʁ     1
2972       accepter  fi3S  aksɛptəʁa     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3573       accorder  ppFS     akɔʁde     2
4255      accrocher  pi3S      akʁɔʃ     1
4323      accroupir   inf    akʁupiʁ     1
4502     accueillir  ppMS      akəji     1
4509     accueillir   inf     akəjiʁ     1
4720        accuser   inf      akyze     1
4812      accélérer  pi3S    aksɛlɛʁ     1
4864      accélérer  ppFS   aksɛlɛʁe     1
5119        acheter   inf      aʃəte     3
5125        acheter  pi2P      aʃəte     2
5159        achever  pi2P      aʃəve     1
5905       acquérir   inf     akɛʁiʁ     1
6072        activer   inf     aktive     1
7028       admettre  ppMS       admi     1
7031       admettre  ppFS      admiz     1
7314         adorer  pi3P       adɔʁ     1
7764        advenir   inf    advəniʁ     1
7809        advenir  ai3S      advɛ̃     1
8305       affecter  ii3S     afɛktɛ     1
8422       affecter  ppMP     afɛkte     1
...             ...   ...        ...   ...
433912      établir  ppMS     ɛtabli     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ     8
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    72
434730     éteindre  pi3P       ɛtɛɲ     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434811      étendre  ai3S     ɛtɑ̃di     1
434827      étendre  pi1S       ɛtɑ̃     1
434836      étendre  ppFP     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     2
435420      étonner  ii1S      ɛtɔnɛ     1
435445      étonner  fi3S    ɛtɔnəʁa     1
435471      étonner  ppMS      ɛtɔne     2
435482     étouffer  ii1S      ɛtufɛ     1
435497     étouffer  pi1S       ɛtuf     1
435677     étourdir  pi1S     ɛtuʁdi     1
435686     étourdir    pP  ɛtuʁdisɑ̃     1
436203      étudier  pi3P      ɛtydi     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    29
436867     éveiller  ppMS      ɛvɛje     1
437301       éviter   inf      ɛvite     2
437331       éviter  ppMP      ɛvite     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    18
437476         être   inf        ɛtʁ    12
437497         ôter  ii3S        ɔtɛ     1
437512         ôter   inf        ɔte     1

[1981 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.6 s, total: 1min 40s
Wall time: 30.4 s

nbChunk 275
4200
1976

            lexeme  case       phono  tir1
40           avoir  pi3S           a    75
132     abandonner   inf    abɑ̃dɔne     1
145     abandonner  pi2S     abɑ̃dɔn     1
166     abandonner  ppFS    abɑ̃dɔne     1
170     abandonner  ppMP    abɑ̃dɔne     1
259        abattre    pP      abatɑ̃     1
305        abattre  ppMS       abaty     1
865         aboyer  pi3S        abwa     1
1856       abréger  pi1S       abʁɛʒ     1
2063      absorber  pi1S      absɔʁb     1
2143      abstenir   inf    abstəniʁ     1
2155      abstenir  ppFS     abstəny     1
2577        abîmer  pi3S        abim     1
2818     accaparer  ppMS     akapaʁe     1
2900     accentuer  pi3S     aksɑ̃ty     1
2971      accepter   inf     aksɛpte     2
2980      accepter  pc2P  aksɛptəʁje     1
2984      accepter  pi2S      aksɛpt     1
3003      accepter  ppMS     aksɛpte     1
3438     accomplir  ppMS     akɔ̃pli     1
3442     accomplir  ppFP     akɔ̃pli     1
3534      accorder  pi3P       akɔʁd     1
3651      accoster  pi3S       akɔst     1
3862      accouder  ai3S       akuda     1
4090      accourir  pi3S        akuʁ     1
4291     accrocher  ppMS      akʁɔʃe     1
4482    accueillir  pi3S        akœj     1
4656     accumuler   inf     akymyle     1
4716       accuser  pi3S        akyz     1
5119       acheter   inf       aʃəte     2
...            ...   ...         ...   ...
429365    émouvoir  ppMS         ɛmy     1
429367    émouvoir  ppFS         ɛmy     1
429796     énoncer  pi3S       ɛnɔ̃s     1
430155    épaissir  ppMS       ɛpɛsi     1
432160     épouser   inf       ɛpuze     1
432588    éprouver  ppFS      ɛpʁuve     1
432638     épuiser  ii3S      ɛpɥizɛ     1
432691     épuiser  ppFS      ɛpɥize     1
433912     établir  ppMS      ɛtabli     1
434048        être  ii3P         ɛtɛ     7
434068        être  ii1S         ɛtɛ    15
434070        être  ii3S         ɛtɛ    93
435054        être  ii2P        ɛtje     4
435062   étinceler  ii3S    ɛtɛ̃səlɛ     1
435232      étirer  ai3S       ɛtiʁa     1
435293      étirer  ppMS       ɛtiʁe     1
435410     étoiler  ppFS      ɛtwale     1
435506    étouffer   inf       ɛtufe     3
435782   étrangler  ppFS    ɛtʁɑ̃gle     1
436316        être  ppMS         ɛte    25
436484      évader  ppMS       ɛvade     1
436997    éventrer   inf     ɛvɑ̃tʁe     1
437294      éviter  pI2S        ɛvit     1
437295      éviter  pi3S        ɛvit     1
437301      éviter   inf       ɛvite     3
437307      éviter  pc3S     ɛvitəʁɛ     1
437317      éviter  pi2P       ɛvite     1
437328      éviter  ppMS       ɛvite     1
437474        être  pi2P          ɛt    18
437476        être   inf         ɛtʁ    23

[1976 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.6 s, total: 1min 41s
Wall time: 30.5 s

nbChunk 276
4200
1985

             lexeme  case       phono  tir1
40            avoir  pi3S           a    88
108      abandonner  ai3S    abɑ̃dɔna     1
168      abandonner  ppFP    abɑ̃dɔne     1
303         abattre  fi1P     abatʁɔ̃     1
1934       absenter  ii3S     absɑ̃tɛ     1
2715       accabler  ii3S      akablɛ     1
2989       accepter  pi2P     aksɛpte     1
3003       accepter  ppMS     aksɛpte     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
4292      accrocher  ppFS      akʁɔʃe     1
4368      accroupir  ai3S      akʁupi     1
5107        acheter  ai1S       aʃətɛ     1
5119        acheter   inf       aʃəte     3
5137        acheter  ppFS       aʃəte     1
5311        acheter  pi3S        aʃɛt     1
5332        achever  pi3S        aʃɛv     1
6862       admettre  pi3S        admɛ     2
6863       admettre  pi1S        admɛ     1
6958    administrer  ppMP  administʁe     1
6988        admirer  pi1S       admiʁ     1
7028       admettre  ppMS        admi     1
7294         adorer  ii3P       adɔʁɛ     1
7309         adorer  pi1S        adɔʁ     2
7570       adresser  ppMP      adʁɛse     1
8022       affairer  ii3P       afɛʁɛ     1
8240        affaler  ppMS       afale     1
8295        affamer  ppMS       afame     1
...             ...   ...         ...   ...
429337     émouvoir  ii3S       ɛmuvɛ     1
429713      énerver  pi2S       ɛnɛʁv     1
430610   éparpiller  pi3S     ɛpaʁpij     1
432021      éponger  ppMP      ɛpɔ̃ʒe     1
432144      épouser  ii3S       ɛpuzɛ     1
432156      épouser  pi3S        ɛpuz     1
432531     éprendre  ai3S        ɛpʁi     1
432534     éprouver  ii3P      ɛpʁuvɛ     1
432586     éprouver  ppMS      ɛpʁuve     1
433105      équiper  pi3S        ɛkip     1
433169      équiper  ppMS       ɛkipe     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ     7
434070         être  ii3S         ɛtɛ    71
434072       étaler  ai3S       ɛtala     1
434134       étaler  ii3S       ɛtalɛ     1
434772     éteindre  ppMS        ɛtɛ̃     1
434773     éteindre  pi3S        ɛtɛ̃     1
434839      étendre  ppMP      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     3
435422      étonner  ii3S       ɛtɔnɛ     1
435438      étonner  pi3S        ɛtɔn     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
435828    étreindre   inf     ɛtʁɛ̃dʁ     1
435965      étriper  pi1S       ɛtʁip     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    28
437301       éviter   inf       ɛvite     2
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    27

[1985 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 21.8 s, total: 1min 38s
Wall time: 29.9 s

nbChunk 277
4200
1917

             lexeme  case       phono  tir1
40            avoir  pi3S           a    93
45         abaisser  ai3S       abɛsa     1
132      abandonner   inf    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     1
166      abandonner  ppFS    abɑ̃dɔne     1
259         abattre    pP      abatɑ̃     1
292         abattre  fi3S      abatʁa     1
1130        aborder  ii1S      abɔʁdɛ     1
1147        aborder   inf      abɔʁde     2
1388        aboutir  ppMS       abuti     1
1460         aboyer  ii3S      abwajɛ     1
1703        abriter  pI2P      abʁite     1
2581         abîmer   inf       abime     1
2610         abîmer  ppMS       abime     1
2939       accepter  ai3S     aksɛpta     1
2964       accepter  pi1S      aksɛpt     1
3003       accepter  ppMS     aksɛpte     2
3408    accompagner  fi1S  akɔ̃paɲəʁɛ     1
3519       accorder  ii3S      akɔʁdɛ     1
3571       accorder  ppMS      akɔʁde     2
3827      accoucher   inf       akuʃe     1
4252      accrocher  pi1S       akʁɔʃ     1
4255      accrocher  pi3S       akʁɔʃ     1
4292      accrocher  ppFS      akʁɔʃe     1
4321      accroupir  ppFS      akʁupi     1
4369      accroupir  pi3S      akʁupi     1
4509     accueillir   inf      akəjiʁ     1
4684      accumuler  ppFS     akymyle     1
4736        accuser  pi2P       akyze     1
4754        accuser  ppMP       akyze     1
...             ...   ...         ...   ...
430590     épargner  ppMS      ɛpaʁɲe     1
430646   éparpiller  ppMP    ɛpaʁpije     1
431349    épiloguer  ppMS     ɛpilɔge     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
432549     éprouver  pi1S       ɛpʁuv     1
432556     éprouver   inf      ɛpʁuve     1
432659      épuiser   inf      ɛpɥize     1
433912      établir  ppMS      ɛtabli     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ    11
434070         être  ii3S         ɛtɛ    80
434762     éteindre   inf      ɛtɛ̃dʁ     1
434773     éteindre  pi3S        ɛtɛ̃     1
434821      étendre   inf      ɛtɑ̃dʁ     1
435054         être  ii2P        ɛtje     1
435085    étinceler  pi3S     ɛtɛ̃sɛl     1
435232       étirer  ai3S       ɛtiʁa     1
435435      étonner  pi1S        ɛtɔn     1
435660     étourdir   inf     ɛtuʁdiʁ     1
436316         être  ppMS         ɛte    17
436395      évacuer  pi1S       ɛvaky     1
436516      évaluer  pi3S       ɛvaly     1
436843     éveiller  fi2P     ɛvɛjəʁe     1
436869     éveiller  ppFS       ɛvɛje     1
437367      évoluer   inf      ɛvɔlye     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437427      évoquer  pi3S        ɛvɔk     1
437474         être  pi2P          ɛt    10
437476         être   inf         ɛtʁ    15
437512         ôter   inf         ɔte     1

[1917 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22 s, total: 1min 37s
Wall time: 29.5 s

nbChunk 278
4200
1927

             lexeme  case     phono  tir1
40            avoir  pi3S         a    84
125      abandonner  pi1S   abɑ̃dɔn     1
130      abandonner  pi3P   abɑ̃dɔn     1
132      abandonner   inf  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     1
277         abattre  ai3P    abatiʁ     1
292         abattre  fi3S    abatʁa     1
299         abattre   inf     abatʁ     1
1455         aboyer  ai3S    abwaja     1
1468         aboyer   inf    abwaje     1
1673        abriter  ii3S    abʁitɛ     1
3380    accompagner  ai3S  akɔ̃paɲa     1
3419    accompagner  pi2S   akɔ̃paɲ     1
3438      accomplir  ppMS   akɔ̃pli     2
3489      accomplir  ai3S   akɔ̃pli     1
3536       accorder   inf    akɔʁde     2
3571       accorder  ppMS    akɔʁde     1
4238      accrocher    pP   akʁɔʃɑ̃     1
4255      accrocher  pi3S     akʁɔʃ     1
4322      accroupir  ppFP    akʁupi     1
4748        accuser  ppMS     akyze     1
4820      accélérer  ii3P  aksɛlɛʁɛ     1
4998       acharner    pP   aʃaʁnɑ̃     1
5102        acheter  ai3S     aʃəta     1
5111        acheter  ii3S     aʃətɛ     1
5119        acheter   inf     aʃəte     1
5139        acheter  ppMP     aʃəte     1
5150        achever    pP    aʃəvɑ̃     1
5835      acquitter  ii3S     akitɛ     1
6877       admettre  pi2P    admɛte     1
...             ...   ...       ...   ...
432160      épouser   inf     ɛpuze     3
432302      épouser  ppMS     ɛpuze     1
432569     éprouver  pi2S     ɛpʁuv     1
433916      établir  ppFP    ɛtabli     1
433946      établir  ii3S  ɛtablisɛ     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ    10
434069         être  ii2S       ɛtɛ     1
434070         être  ii3S       ɛtɛ    71
434154       étaler  fi3S   ɛtaləʁa     1
434480     étancher  ppMS    ɛtɑ̃ʃe     1
434726     éteindre  ii3S     ɛtɛɲɛ     1
434773     éteindre  pi3S      ɛtɛ̃     1
434794      étendre  pi3P     ɛtɑ̃d     1
434811      étendre  ai3S    ɛtɑ̃di     2
434833      étendre  ppFS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     1
435417      étonner  ai3S     ɛtɔna     1
435438      étonner  pi3S      ɛtɔn     1
435450      étonner  pc3S   ɛtɔnəʁɛ     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    18
436632     évanouir   inf   ɛvanuiʁ     2
437301       éviter   inf     ɛvite     1
437417      évoquer    pP    ɛvɔkɑ̃     1
437442      évoquer  fi1P  ɛvɔkəʁɔ̃     1
437474         être  pi2P        ɛt     8
437476         être   inf       ɛtʁ    17
437512         ôter   inf       ɔte     1

[1927 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.2 s, total: 1min 39s
Wall time: 29.9 s

nbChunk 279
4200
1951

             lexeme  case      phono  tir1
40            avoir  pi3S          a    94
125      abandonner  pi1S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     2
164      abandonner  ppMS   abɑ̃dɔne     1
168      abandonner  ppFP   abɑ̃dɔne     1
307         abattre  ppFS      abaty     1
956         abonder  ii1S     abɔ̃dɛ     1
1686        abriter  pi3P      abʁit     1
1720        abriter  ppFP     abʁite     1
2066       absorber  pi3S     absɔʁb     1
2339         abuser   inf      abyze     1
2581         abîmer   inf      abime     1
2934      accentuer  ppFS   aksɑ̃tye     1
2939       accepter  ai3S    aksɛpta     1
2968       accepter  ps3S     aksɛpt     1
2971       accepter   inf    aksɛpte     1
2977       accepter  pc3S  aksɛptəʁɛ     1
2979       accepter  fi2P  aksɛptəʁe     1
3382    accompagner  ii3P   akɔ̃paɲɛ     1
3406    accompagner   inf   akɔ̃paɲe     1
3527       accorder  pi1S      akɔʁd     1
3571       accorder  ppMS     akɔʁde     1
3821      accoucher  pi3S       akuʃ     1
3827      accoucher   inf      akuʃe     1
4090       accourir  pi3S       akuʁ     1
4255      accrocher  pi3S      akʁɔʃ     1
4291      accrocher  ppMS     akʁɔʃe     1
4693        accuser  ii3S      akyzɛ     1
4718        accuser  pi3P       akyz     1
4835      accélérer   inf   aksɛlɛʁe     1
...             ...   ...        ...   ...
434068         être  ii1S        ɛtɛ    12
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    72
434488         être    pP       ɛtɑ̃     1
434782      étendre  pi3S       ɛtɑ̃     1
434811      étendre  ai3S     ɛtɑ̃di     1
434827      étendre  pi1S       ɛtɑ̃     1
434917     éternuer  pi3S     ɛtɛʁny     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     1
435422      étonner  ii3S      ɛtɔnɛ     1
435444      étonner   inf      ɛtɔne     1
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435506     étouffer   inf      ɛtufe     1
436186      étudier  ii3S     ɛtydjɛ     1
436316         être  ppMS        ɛte    24
436547      évaluer  ppMS     ɛvalye     1
436656     évanouir  ii3S   ɛvanuisɛ     1
436835     éveiller   inf      ɛvɛje     2
436867     éveiller  ppMS      ɛvɛje     1
437284       éviter  ii3S      ɛvitɛ     1
437295       éviter  pi3S       ɛvit     1
437301       éviter   inf      ɛvite     3
437367      évoluer   inf     ɛvɔlye     1
437413      évoquer  ii3P      ɛvɔkɛ     1
437417      évoquer    pP     ɛvɔkɑ̃     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    14
437476         être   inf        ɛtʁ    15
437512         ôter   inf        ɔte     2

[1951 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22 s, total: 1min 37s
Wall time: 29.8 s

nbChunk 280
4200
1933

             lexeme  case       phono  tir1
40            avoir  pi3S           a    94
164      abandonner  ppMS    abɑ̃dɔne     2
243         abattre  pi3S         aba     2
287         abattre  ai3S       abati     1
299         abattre   inf       abatʁ     1
1175        aborder  ppMS      abɔʁde     1
1884        abréger   inf      abʁɛʒe     1
2070       absorber   inf     absɔʁbe     1
2267      abstraire   inf     abstʁɛʁ     1
2967       accepter  pi3S      aksɛpt     2
2983       accepter  fi3P  aksɛptəʁɔ̃     1
3003       accepter  ppMS     aksɛpte     2
3383    accompagner  ii1S    akɔ̃paɲɛ     1
3386    accompagner    pP   akɔ̃paɲɑ̃     1
3404    accompagner  pi3P     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
3556       accorder  pi2P      akɔʁde     1
4294      accrocher  ppMP      akʁɔʃe     2
4656      accumuler   inf     akymyle     1
4693        accuser  ii3S       akyzɛ     1
4783        accéder   inf      aksɛde     1
5136        acheter  ppMS       aʃəte     1
5169        achever  ai3P      aʃəvɛʁ     1
5311        acheter  pi3S        aʃɛt     1
5316        acheter  fi1S     aʃɛtəʁɛ     1
5338        achever  fi3S     aʃɛvəʁa     1
6103        activer  pi1P     aktivɔ̃     1
7233        adopter    pP     adɔptɑ̃     1
7312         adorer  pi3S        adɔʁ     1
...             ...   ...         ...   ...
427455     éliminer   inf     ɛlimine     1
427482     éliminer  ppMS     ɛlimine     1
427635     éloigner  pi3S       ɛlwaɲ     1
428650     émouvoir  pi3S         ɛmø     1
429365     émouvoir  ppMS         ɛmy     1
430563     épargner  fi3S    ɛpaʁɲəʁa     1
430645   éparpiller  ppFP    ɛpaʁpije     1
431186        épier  pi2S         ɛpi     1
432160      épouser   inf       ɛpuze     1
432166      épouser  pc3S     ɛpuzəʁɛ     1
432549     éprouver  pi1S       ɛpʁuv     1
433939      établir  pi1S      ɛtabli     1
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ     9
434070         être  ii3S         ɛtɛ    82
434301       étaler  ppFP       ɛtale     1
434836      étendre  ppFP      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     6
435172         être  ii1P       ɛtjɔ̃     2
435438      étonner  pi3S        ɛtɔn     2
435475     étouffer  ai3S       ɛtufa     2
435484     étouffer  ii3S       ɛtufɛ     1
435500     étouffer  pi3S        ɛtuf     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    22
436835     éveiller   inf       ɛvɛje     1
437024     éventrer  ppMS     ɛvɑ̃tʁe     1
437285       éviter    pP      ɛvitɑ̃     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    23

[1933 rows x 4 columns]

0
CPU times: user 1min 19s, sys: 23.1 s, total: 1min 42s
Wall time: 31.4 s

nbChunk 281
4200
2021

             lexeme  case        phono  tir1
40            avoir  pi3S            a    95
132      abandonner   inf     abɑ̃dɔne     1
299         abattre   inf        abatʁ     1
1147        aborder   inf       abɔʁde     1
1684        abriter  pi3S        abʁit     1
1716        abriter  ppMS       abʁite     1
2339         abuser   inf        abyze     1
2560         abîmer  ai3S        abima     1
2581         abîmer   inf        abime     1
2601         abîmer  ii1P      abimjɔ̃     1
2964       accepter  pi1S       aksɛpt     1
2967       accepter  pi3S       aksɛpt     1
2971       accepter   inf      aksɛpte     2
2984       accepter  pi2S       aksɛpt     1
3003       accepter  ppMS      aksɛpte     1
3406    accompagner   inf     akɔ̃paɲe     1
3433    accompagner  ppMS     akɔ̃paɲe     2
4255      accrocher  pi3S        akʁɔʃ     1
4259      accrocher   inf       akʁɔʃe     2
4293      accrocher  ppFP       akʁɔʃe     1
4404     accréditer  ai3S     akʁɛdita     1
5111        acheter  ii3S        aʃətɛ     1
5119        acheter   inf        aʃəte     1
5131        acheter  pi1P       aʃətɔ̃     1
5807       acquérir  ppMS          aki     1
6445        adapter  ppFP       adapte     1
6877       admettre  pi2P       admɛte     1
6891       admettre   inf       admɛtʁ     1
6903    administrer    pP  administʁɑ̃     1
7028       admettre  ppMS         admi     1
...             ...   ...          ...   ...
432160      épouser   inf        ɛpuze     1
432302      épouser  ppMS        ɛpuze     2
432556     éprouver   inf       ɛpʁuve     1
432580     éprouver  pi1P      ɛpʁuvɔ̃     1
434048         être  ii3P          ɛtɛ     1
434068         être  ii1S          ɛtɛ    14
434070         être  ii3S          ɛtɛ    79
434729     éteindre  ps3S         ɛtɛɲ     1
434762     éteindre   inf       ɛtɛ̃dʁ     1
434831      étendre  ppMS       ɛtɑ̃dy     1
434833      étendre  ppFS       ɛtɑ̃dy     1
435172         être  ii1P        ɛtjɔ̃     3
435422      étonner  ii3S        ɛtɔnɛ     1
435444      étonner   inf        ɛtɔne     1
435450      étonner  pc3S      ɛtɔnəʁɛ     1
435794    étreindre  ii3S       ɛtʁɛɲɛ     1
435815    étreindre  ai3S       ɛtʁɛɲi     1
436316         être  ppMS          ɛte    24
436627     évanouir  ppMS       ɛvanui     1
436679     évanouir  pi3S       ɛvanui     1
436815     éveiller  ai3S        ɛvɛja     1
436833     éveiller  pi3P         ɛvɛj     1
437130       évider   inf        ɛvide     1
437295       éviter  pi3S         ɛvit     1
437453      évoquer  pi1P       ɛvɔkɔ̃     1
437458      évoquer  ppMS        ɛvɔke     1
437474         être  pi2P           ɛt    14
437476         être   inf          ɛtʁ    19
437492         ôter  ai3S          ɔta     1
437497         ôter  ii3S          ɔtɛ     1

[2021 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.2 s, total: 1min 40s
Wall time: 29.9 s

nbChunk 282
4200
1943

             lexeme  case       phono  tir1
40            avoir  pi3S           a    89
114      abandonner    pP   abɑ̃dɔnɑ̃     1
128      abandonner  pi3S     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     1
166      abandonner  ppFS    abɑ̃dɔne     1
264         abattre  pi3P        abat     1
272         abattre  pi2P       abate     1
313         abattre  ppMP       abaty     1
2610         abîmer  ppMS       abime     1
2902      accentuer  pi3P     aksɑ̃ty     1
2946       accepter  ai1S     aksɛptɛ     1
2950       accepter  ii3S     aksɛptɛ     1
2964       accepter  pi1S      aksɛpt     1
2972       accepter  fi3S   aksɛptəʁa     1
2979       accepter  fi2P   aksɛptəʁe     1
2980       accepter  pc2P  aksɛptəʁje     1
2984       accepter  pi2S      aksɛpt     1
2988       accepter  pI2P     aksɛpte     1
3508       accorder  ai3S      akɔʁda     1
3573       accorder  ppFS      akɔʁde     1
4279      accrocher  pI2P      akʁɔʃe     1
4293      accrocher  ppFP      akʁɔʃe     1
4502     accueillir  ppMS       akəji     1
4736        accuser  pi2P       akyze     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     1
5146        achever  ii3P       aʃəvɛ     1
5157        achever   inf       aʃəve     1
5313        acheter  pi3P        aʃɛt     1
...             ...   ...         ...   ...
427641     éloigner   inf      ɛlwaɲe     2
429330  émoustiller  ppMS    ɛmustije     1
429365     émouvoir  ppMS         ɛmy     3
430558     épargner  pi3S       ɛpaʁɲ     2
430587     épargner  is3S      ɛpaʁɲa     1
431965     épointer  ppMP     ɛpwɛ̃te     1
431992      éponger   inf      ɛpɔ̃ʒe     1
432184      épouser  ii1P     ɛpuzjɔ̃     1
432586     éprouver  ppMS      ɛpʁuve     1
432638      épuiser  ii3S      ɛpɥizɛ     1
432689      épuiser  ppMS      ɛpɥize     2
433238   équivaloir  pi3S       ɛkivo     1
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ    15
434070         être  ii3S         ɛtɛ    86
434131       étaler  ii3P       ɛtalɛ     1
434770     éteindre  pi2S        ɛtɛ̃     1
434775     éteindre  ppFS       ɛtɛ̃t     1
434833      étendre  ppFS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     4
435243       étirer  ii3S       ɛtiʁɛ     1
435422      étonner  ii3S       ɛtɔnɛ     1
435506     étouffer   inf       ɛtufe     1
435681     étourdir  ii3P    ɛtuʁdisɛ     1
436316         être  ppMS         ɛte    19
436627     évanouir  ppMS      ɛvanui     1
436876      éventer  ai3S      ɛvɑ̃ta     1
437301       éviter   inf       ɛvite     2
437474         être  pi2P          ɛt     7
437476         être   inf         ɛtʁ    20

[1943 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.6 s, total: 1min 36s
Wall time: 30.1 s

nbChunk 283
4200
1941

             lexeme  case     phono  tir1
40            avoir  pi3S         a    79
164      abandonner  ppMS  abɑ̃dɔne     1
677         abjurer  pi2P    abʒyʁe     1
1175        aborder  ppMS    abɔʁde     1
1440        aboutir  pi3S     abuti     2
1686        abriter  pi3P     abʁit     1
1818        abrutir  pi1S    abʁyti     1
2106       absorber  ppMP   absɔʁbe     1
2335         abuser  pi3S      abyz     1
2565         abîmer  ii3S     abimɛ     1
2581         abîmer   inf     abime     1
2763       accabler  ppMS    akable     1
2947       accepter  ii3P   aksɛptɛ     1
2971       accepter   inf   aksɛpte     1
3003       accepter  ppMS   aksɛpte     1
3009       accepter  ppMP   aksɛpte     1
3397    accompagner  pi1S   akɔ̃paɲ     1
3422    accompagner  pi2P  akɔ̃paɲe     1
3435    accompagner  ppFP  akɔ̃paɲe     1
3530       accorder  pi3S     akɔʁd     1
3549       accorder  pi2S     akɔʁd     1
4006       accourir  ii3P     akuʁɛ     1
4090       accourir  pi3S      akuʁ     1
4259      accrocher   inf    akʁɔʃe     1
4690        accuser  ii3P     akyzɛ     1
4713        accuser  pi1S      akyz     1
4783        accéder   inf    aksɛde     2
5111        acheter  ii3S     aʃətɛ     1
5119        acheter   inf     aʃəte     1
5136        acheter  ppMS     aʃəte     2
...             ...   ...       ...   ...
432156      épouser  pi3S      ɛpuz     1
432160      épouser   inf     ɛpuze     3
432182      épouser  ii2P    ɛpuzje     1
432302      épouser  ppMS     ɛpuze     1
432532     éprouver  ai3S    ɛpʁuva     1
432638      épuiser  ii3S    ɛpɥizɛ     1
432672      épuiser  pi2S     ɛpɥiz     1
433026   équilibrer   inf  ɛkilibʁe     1
433325      érafler   inf    ɛʁafle     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    10
434070         être  ii3S       ɛtɛ    69
434302       étaler  ppMP     ɛtale     1
434821      étendre   inf    ɛtɑ̃dʁ     1
435135      étioler   inf    ɛtjɔle     1
435172         être  ii1P     ɛtjɔ̃     1
435438      étonner  pi3S      ɛtɔn     1
435444      étonner   inf     ɛtɔne     1
435450      étonner  pc3S   ɛtɔnəʁɛ     1
435460      étonner  pi2P     ɛtɔne     1
435500     étouffer  pi3S      ɛtuf     1
436316         être  ppMS       ɛte    29
436402      évacuer   inf    ɛvakye     1
436430      évacuer  ppMS    ɛvakye     1
436632     évanouir   inf   ɛvanuiʁ     2
437301       éviter   inf     ɛvite     1
437431      évoquer   inf     ɛvɔke     1
437474         être  pi2P        ɛt    14
437476         être   inf       ɛtʁ    22
437508         ôter  pi3S        ot     1

[1941 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.2 s, total: 1min 39s
Wall time: 29.7 s

nbChunk 284
4200
1947

             lexeme  case       phono  tir1
40            avoir  pi3S           a    73
108      abandonner  ai3S    abɑ̃dɔna     1
113      abandonner  ii3S    abɑ̃dɔnɛ     1
125      abandonner  pi1S     abɑ̃dɔn     1
128      abandonner  pi3S     abɑ̃dɔn     1
133      abandonner  fi3S  abɑ̃dɔnəʁa     1
166      abandonner  ppFS    abɑ̃dɔne     1
243         abattre  pi3S         aba     1
272         abattre  pi2P       abate     1
299         abattre   inf       abatʁ     1
904          abolir  ppMP       abɔli     1
1388        aboutir  ppMS       abuti     1
2051       absorber  ii3S     absɔʁbɛ     1
2324         abuser  ii3S       abyzɛ     1
2734       accabler  pi3P       akabl     1
2969       accepter  pi3P      aksɛpt     1
2971       accepter   inf     aksɛpte     1
3003       accepter  ppMS     aksɛpte     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3419    accompagner  pi2S     akɔ̃paɲ     1
3429    accompagner  ai1P   akɔ̃paɲam     1
3467      accomplir  ii3S   akɔ̃plisɛ     1
4234      accrocher  ii3P      akʁɔʃɛ     1
4237      accrocher  ii3S      akʁɔʃɛ     1
4279      accrocher  pI2P      akʁɔʃe     1
4291      accrocher  ppMS      akʁɔʃe     2
4294      accrocher  ppMP      akʁɔʃe     1
4685      accumuler  ppFP     akymyle     1
4809      accélérer  pi1S     aksɛlɛʁ     1
4835      accélérer   inf    aksɛlɛʁe     1
...             ...   ...         ...   ...
430962    éperonner  pi2P     ɛpəʁɔne     1
432156      épouser  pi3S        ɛpuz     1
432160      épouser   inf       ɛpuze     2
432167      épouser  fi2S     ɛpuzəʁa     1
432552     éprouver  pi3S       ɛpʁuv     1
432691      épuiser  ppFS      ɛpɥize     1
433102      équiper  pi1S        ɛkip     1
433169      équiper  ppMS       ɛkipe     1
434048         être  ii3P         ɛtɛ     6
434068         être  ii1S         ɛtɛ     8
434070         être  ii3S         ɛtɛ    85
434147       étaler  pi3S        ɛtal     1
434773     éteindre  pi3S        ɛtɛ̃     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     2
435471      étonner  ppMS       ɛtɔne     1
435538     étouffer  ppMS       ɛtufe     1
435726    étrangler  ai3S    ɛtʁɑ̃gla     1
436316         être  ppMS         ɛte    24
436402      évacuer   inf      ɛvakye     2
436632     évanouir   inf     ɛvanuiʁ     1
436831     éveiller  pi3S        ɛvɛj     1
436835     éveiller   inf       ɛvɛje     1
436867     éveiller  ppMS       ɛvɛje     1
437284       éviter  ii3S       ɛvitɛ     1
437301       éviter   inf       ɛvite     1
437302       éviter  fi3S     ɛvitəʁa     1
437474         être  pi2P          ɛt    14
437476         être   inf         ɛtʁ    17
437528         ôter  pi2P         ɔte     1

[1947 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.1 s, total: 1min 38s
Wall time: 29.7 s

nbChunk 285
4200
1940

             lexeme  case      phono  tir1
40            avoir  pi3S          a    82
52         abaisser    pP     abɛsɑ̃     1
164      abandonner  ppMS   abɑ̃dɔne     2
166      abandonner  ppFS   abɑ̃dɔne     1
258         abattre  ii3S      abatɛ     1
2070       absorber   inf    absɔʁbe     1
2155       abstenir  ppFS    abstəny     1
2335         abuser  pi3S       abyz     1
2791      accaparer   inf    akapaʁe     1
2971       accepter   inf    aksɛpte     1
2972       accepter  fi3S  aksɛptəʁa     1
3003       accepter  ppMS    aksɛpte     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3397    accompagner  pi1S    akɔ̃paɲ     1
3400    accompagner  pi3S    akɔ̃paɲ     2
3404    accompagner  pi3P    akɔ̃paɲ     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3536       accorder   inf     akɔʁde     1
3545       accorder  pc2P  akɔʁdəʁje     1
3827      accoucher   inf      akuʃe     1
4291      accrocher  ppMS     akʁɔʃe     1
4321      accroupir  ppFS     akʁupi     1
4373      accroître  pi3S      akʁwa     1
4475     accueillir    pP     akəjɑ̃     1
4509     accueillir   inf     akəjiʁ     1
4713        accuser  pi1S       akyz     1
4716        accuser  pi3S       akyz     1
4718        accuser  pi3P       akyz     1
4835      accélérer   inf   aksɛlɛʁe     1
5136        acheter  ppMS      aʃəte     4
...             ...   ...        ...   ...
432537     éprouver  ii3S     ɛpʁuvɛ     1
432586     éprouver  ppMS     ɛpʁuve     1
433169      équiper  ppMS      ɛkipe     1
433912      établir  ppMS     ɛtabli     1
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ    11
434070         être  ii3S        ɛtɛ    64
434151       étaler  pi3P       ɛtal     1
434299       étaler  ppMS      ɛtale     1
434488         être    pP       ɛtɑ̃     3
434672       étayer  ii3P      ɛtɛjɛ     1
434782      étendre  pi3S       ɛtɑ̃     1
434811      étendre  ai3S     ɛtɑ̃di     1
435054         être  ii2P       ɛtje     2
435064    étinceler    pP  ɛtɛ̃səlɑ̃     1
435172         être  ii1P      ɛtjɔ̃     1
435241       étirer  ii1S      ɛtiʁɛ     1
435254       étirer  pi3S       ɛtiʁ     1
435450      étonner  pc3S    ɛtɔnəʁɛ     2
435739    étrangler  pi1S    ɛtʁɑ̃gl     1
436316         être  ppMS        ɛte    19
436815     éveiller  ai3S      ɛvɛja     1
436867     éveiller  ppMS      ɛvɛje     1
437282       éviter  ii1S      ɛvitɛ     1
437295       éviter  pi3S       ɛvit     1
437301       éviter   inf      ɛvite     2
437474         être  pi2P         ɛt    14
437476         être   inf        ɛtʁ    14
437493         ôter  ai1S        ɔtɛ     1
437497         ôter  ii3S        ɔtɛ     1

[1940 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.5 s, total: 1min 40s
Wall time: 30.2 s

nbChunk 286
4200
1973

             lexeme  case     phono  tir1
40            avoir  pi3S         a    80
111      abandonner  ii1S  abɑ̃dɔnɛ     1
128      abandonner  pi3S   abɑ̃dɔn     1
132      abandonner   inf  abɑ̃dɔne     2
164      abandonner  ppMS  abɑ̃dɔne     1
299         abattre   inf     abatʁ     1
1673        abriter  ii3S    abʁitɛ     1
2135       abstenir  ii3S   abstənɛ     1
2155       abstenir  ppFS   abstəny     1
2610         abîmer  ppMS     abime     1
2952       accepter    pP  aksɛptɑ̃     1
2964       accepter  pi1S    aksɛpt     1
2967       accepter  pi3S    aksɛpt     2
2971       accepter   inf   aksɛpte     1
3400    accompagner  pi3S   akɔ̃paɲ     1
4072       accourir   inf    akuʁiʁ     1
4255      accrocher  pi3S     akʁɔʃ     2
4320      accroupir  ppMS    akʁupi     1
4473     accueillir  ii3S     akəjɛ     1
4486     accueillir  fi3S   akəjəʁa     1
4502     accueillir  ppMS     akəji     1
4654      accumuler  pi3P    akymyl     1
4716        accuser  pi3S      akyz     1
5119        acheter   inf     aʃəte     3
5311        acheter  pi3S      aʃɛt     1
6862       admettre  pi3S      admɛ     1
6865       admettre  pi2S      admɛ     1
6882       admettre  pI1P   admɛtɔ̃     1
6996        admirer   inf    admiʁe     1
7297         adorer  ii3S     adɔʁɛ     1
...             ...   ...       ...   ...
431167        épier   inf      ɛpje     1
432018      éponger  ppMS    ɛpɔ̃ʒe     1
432537     éprouver  ii3S    ɛpʁuvɛ     1
433092      équiper    pP    ɛkipɑ̃     1
433238   équivaloir  pi3S     ɛkivo     1
433943      établir  ii3P  ɛtablisɛ     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ     8
434070         être  ii3S       ɛtɛ    81
434153       étaler   inf     ɛtale     1
434293       étaler  pi1P    ɛtalɔ̃     1
434779     éteindre  ppMP      ɛtɛ̃     1
434853    éterniser  ii3S  ɛtɛʁnizɛ     1
435054         être  ii2P      ɛtje     3
435172         être  ii1P     ɛtjɔ̃     1
435254       étirer  pi3S      ɛtiʁ     1
435742    étrangler  pi3S   ɛtʁɑ̃gl     1
436201      étudier  pi3S     ɛtydi     1
436205      étudier   inf    ɛtydje     3
436212      étudier  fi2S   ɛtydiʁa     1
436316         être  ppMS       ɛte    27
436627     évanouir  ppMS    ɛvanui     1
436656     évanouir  ii3S  ɛvanuisɛ     1
437284       éviter  ii3S     ɛvitɛ     1
437301       éviter   inf     ɛvite     1
437367      évoluer   inf    ɛvɔlye     1
437417      évoquer    pP    ɛvɔkɑ̃     1
437474         être  pi2P        ɛt    19
437476         être   inf       ɛtʁ    15
437494         ôter  ii3P       ɔtɛ     1

[1973 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.5 s, total: 1min 39s
Wall time: 29.9 s

nbChunk 287
4200
1960

             lexeme  case     phono  tir1
40            avoir  pi3S         a    81
52         abaisser    pP    abɛsɑ̃     1
128      abandonner  pi3S   abɑ̃dɔn     1
132      abandonner   inf  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     2
299         abattre   inf     abatʁ     1
890          abolir   inf    abɔliʁ     1
1393        aboutir   inf    abutiʁ     1
1980       absenter  ppFS   absɑ̃te     1
2138       abstenir  pi2P   abstəne     1
2581         abîmer   inf     abime     1
2610         abîmer  ppMS     abime     1
2736       accabler   inf    akable     1
2887      accentuer  ii3S  aksɑ̃tyɛ     1
2946       accepter  ai1S   aksɛptɛ     1
2971       accepter   inf   aksɛpte     5
2989       accepter  pi2P   aksɛpte     1
3349     accommoder   inf   akɔmɔde     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3536       accorder   inf    akɔʁde     1
3571       accorder  ppMS    akɔʁde     1
3818      accoucher  pi1S      akuʃ     1
4009       accourir  ii3S     akuʁɛ     1
4484     accueillir  pi3P      akœj     1
4652      accumuler  pi3S    akymyl     1
4656      accumuler   inf   akymyle     1
4688        accuser  ai3S     akyza     1
4736        accuser  pi2P     akyze     1
4812      accélérer  pi3S   aksɛlɛʁ     1
4997       acharner  ii3S    aʃaʁnɛ     1
...             ...   ...       ...   ...
430973    éperonner  ppMS   ɛpəʁɔne     1
431790        épier  ppFP      ɛpje     1
431871     éplucher   inf    ɛplyʃe     1
432162      épouser  fi1S   ɛpuzəʁɛ     1
432303      épouser  ppFS     ɛpuze     1
432405   épouvanter  pi2S   ɛpuvɑ̃t     1
432659      épuiser   inf    ɛpɥize     1
433195   équivaloir  ii3S   ɛkivalɛ     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    18
434069         être  ii2S       ɛtɛ     1
434070         être  ii3S       ɛtɛ    85
434773     éteindre  pi3S      ɛtɛ̃     1
434775     éteindre  ppFS     ɛtɛ̃t     1
434821      étendre   inf    ɛtɑ̃dʁ     1
435054         être  ii2P      ɛtje     3
435172         être  ii1P     ɛtjɔ̃     1
435450      étonner  pc3S   ɛtɔnəʁɛ     2
435748    étrangler   inf  ɛtʁɑ̃gle     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    21
436679     évanouir  pi3S    ɛvanui     1
437049     évertuer  ii3S   ɛvɛʁtyɛ     1
437284       éviter  ii3S     ɛvitɛ     2
437292       éviter  pi1S      ɛvit     1
437301       éviter   inf     ɛvite     4
437307       éviter  pc3S   ɛvitəʁɛ     1
437474         être  pi2P        ɛt    14
437476         être   inf       ɛtʁ    22

[1960 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.4 s, total: 1min 40s
Wall time: 29.9 s

nbChunk 288
4200
1960

             lexeme  case       phono  tir1
40            avoir  pi3S           a    85
128      abandonner  pi3S     abɑ̃dɔn     1
1393        aboutir   inf      abutiʁ     1
1934       absenter  ii3S     absɑ̃tɛ     1
2952       accepter    pP    aksɛptɑ̃     1
2967       accepter  pi3S      aksɛpt     1
2984       accepter  pi2S      aksɛpt     1
3003       accepter  ppMS     aksɛpte     1
3406    accompagner   inf    akɔ̃paɲe     2
3438      accomplir  ppMS     akɔ̃pli     1
3540       accorder  pc1S    akɔʁdəʁɛ     1
3544       accorder  fi2P    akɔʁdəʁe     1
4090       accourir  pi3S        akuʁ     1
4339      accroupir  pi1S      akʁupi     1
4502     accueillir  ppMS       akəji     1
4748        accuser  ppMS       akyze     1
5070      acheminer   inf     aʃəmine     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     1
5150        achever    pP      aʃəvɑ̃     1
5308        acheter  pi1S        aʃɛt     1
5311        acheter  pi3S        aʃɛt     1
6072        activer   inf      aktive     1
6414        adapter   inf      adapte     1
6865       admettre  pi2S        admɛ     1
6965        admirer  ai1S      admiʁɛ     1
7173        adonner  ii3P       adɔnɛ     1
7297         adorer  ii3S       adɔʁɛ     1
7312         adorer  pi3S        adɔʁ     2
7316         adorer   inf       adɔʁe     1
...             ...   ...         ...   ...
434070         être  ii3S         ɛtɛ    74
434739     éteindre  ai3P      ɛtɛɲiʁ     1
434762     éteindre   inf      ɛtɛ̃dʁ     3
434768     éteindre  pi1S        ɛtɛ̃     1
434786      étendre  ii1S      ɛtɑ̃dɛ     1
434831      étendre  ppMS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     1
435417      étonner  ai3S       ɛtɔna     1
435420      étonner  ii1S       ɛtɔnɛ     1
435422      étonner  ii3S       ɛtɔnɛ     1
435435      étonner  pi1S        ɛtɔn     1
435538     étouffer  ppMS       ɛtufe     1
435752    étrangler  pc1S  ɛtʁɑ̃gləʁɛ     1
435754    étrangler  pc3S  ɛtʁɑ̃gləʁɛ     1
435795    étreindre    pP     ɛtʁɛɲɑ̃     1
435797    étreindre  ps3S       ɛtʁɛɲ     1
435828    étreindre   inf     ɛtʁɛ̃dʁ     1
436316         être  ppMS         ɛte    16
436544      évaluer  is3S      ɛvalya     1
436627     évanouir  ppMS      ɛvanui     1
436632     évanouir   inf     ɛvanuiʁ     1
436656     évanouir  ii3S    ɛvanuisɛ     1
436820     éveiller  ii3S       ɛvɛjɛ     1
436835     éveiller   inf       ɛvɛje     1
437273       éviter  ai3S       ɛvita     1
437285       éviter    pP      ɛvitɑ̃     1
437301       éviter   inf       ɛvite     4
437474         être  pi2P          ɛt    11
437476         être   inf         ɛtʁ    20

[1960 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.7 s, total: 1min 41s
Wall time: 30.2 s

nbChunk 289
4200
1974

            lexeme  case     phono  tir1
40           avoir  pi3S         a    89
67        abaisser  pi3S      abɛs     1
125     abandonner  pi1S   abɑ̃dɔn     1
132     abandonner   inf  abɑ̃dɔne     1
145     abandonner  pi2S   abɑ̃dɔn     1
305        abattre  ppMS     abaty     1
887         abolir  ppMS     abɔli     1
1684       abriter  pi3S     abʁit     2
2337        abuser  pi3P      abyz     1
2371        abuser  ppMS     abyze     1
2506        abêtir   inf    abɛtiʁ     1
2581        abîmer   inf     abime     1
2616        abîmer  ppMP     abime     1
2969      accepter  pi3P    aksɛpt     1
2971      accepter   inf   aksɛpte     1
3003      accepter  ppMS   aksɛpte     1
3376    accommoder  ppMS   akɔmɔde     1
3438     accomplir  ppMS   akɔ̃pli     1
3575      accorder  ppFP    akɔʁde     1
3884      accouder   inf     akude     1
5119       acheter   inf     aʃəte     2
5124       acheter  pI2P     aʃəte     1
5311       acheter  pi3S      aʃɛt     1
5313       acheter  pi3P      aʃɛt     1
5317       acheter  pc3P   aʃɛtəʁɛ     1
5332       achever  pi3S      aʃɛv     1
6969       admirer  ii3S    admiʁɛ     1
7312        adorer  pi3S      adɔʁ     3
7539      adresser   inf    adʁɛse     1
8023      affairer  ii1S     afɛʁɛ     1
...            ...   ...       ...   ...
432156     épouser  pi3S      ɛpuz     2
432160     épouser   inf     ɛpuze     1
432302     épouser  ppMS     ɛpuze     1
432535    éprouver  ii1S    ɛpʁuvɛ     1
432689     épuiser  ppMS    ɛpɥize     1
433912     établir  ppMS    ɛtabli     1
433922     établir   inf   ɛtabliʁ     1
434048        être  ii3P       ɛtɛ     1
434068        être  ii1S       ɛtɛ    14
434069        être  ii2S       ɛtɛ     1
434070        être  ii3S       ɛtɛ    69
434072      étaler  ai3S     ɛtala     1
434153      étaler   inf     ɛtale     1
434762    éteindre   inf    ɛtɛ̃dʁ     1
435089   étinceler  pi3P   ɛtɛ̃sɛl     1
435172        être  ii1P     ɛtjɔ̃     1
435232      étirer  ai3S     ɛtiʁa     1
435450     étonner  pc3S   ɛtɔnəʁɛ     1
435486    étouffer    pP    ɛtufɑ̃     1
435660    étourdir   inf   ɛtuʁdiʁ     1
435742   étrangler  pi3S   ɛtʁɑ̃gl     1
435748   étrangler   inf  ɛtʁɑ̃gle     1
436186     étudier  ii3S    ɛtydjɛ     1
436316        être  ppMS       ɛte    23
437299      éviter  pi3P      ɛvit     1
437411     évoquer  ai3S     ɛvɔka     1
437474        être  pi2P        ɛt    10
437476        être   inf       ɛtʁ    17
437492        ôter  ai3S       ɔta     1
437540        ôter  ppFS       ɔte     1

[1974 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.1 s, total: 1min 39s
Wall time: 30.3 s

nbChunk 290
4200
1956

             lexeme  case     phono  tir1
40            avoir  pi3S         a    75
243         abattre  pi3S       aba     1
955         abonder  ii3P    abɔ̃dɛ     1
1461         aboyer    pP   abwajɑ̃     1
1468         aboyer   inf    abwaje     1
1884        abréger   inf    abʁɛʒe     1
2948       accepter  ii1S   aksɛptɛ     1
2967       accepter  pi3S    aksɛpt     1
2971       accepter   inf   aksɛpte     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3434    accompagner  ppFS  akɔ̃paɲe     1
3443      accomplir   inf  akɔ̃pliʁ     1
3519       accorder  ii3S    akɔʁdɛ     1
3536       accorder   inf    akɔʁde     1
4238      accrocher    pP   akʁɔʃɑ̃     1
4267      accrocher  fi2P  akʁɔʃəʁe     1
4291      accrocher  ppMS    akʁɔʃe     1
4394      accroître  ppMP      akʁy     1
4475     accueillir    pP    akəjɑ̃     1
4482     accueillir  pi3S      akœj     1
4812      accélérer  pi3S   aksɛlɛʁ     1
4835      accélérer   inf  aksɛlɛʁe     1
5008       acharner  pi3S     aʃaʁn     1
5119        acheter   inf     aʃəte     2
5136        acheter  ppMS     aʃəte     3
5806       acquérir  ppMP       aki     1
6996        admirer   inf    admiʁe     1
7295         adorer  ii1S     adɔʁɛ     1
7297         adorer  ii3S     adɔʁɛ     1
...             ...   ...       ...   ...
431359       épiler  ppMP     ɛpile     1
431992      éponger   inf    ɛpɔ̃ʒe     1
432302      épouser  ppMS     ɛpuze     1
432549     éprouver  pi1S     ɛpʁuv     1
432689      épuiser  ppMS    ɛpɥize     1
432691      épuiser  ppFS    ɛpɥize     1
433354      érafler  ppMS    ɛʁafle     1
433922      établir   inf   ɛtabliʁ     1
433969      établir  pi3S    ɛtabli     1
434048         être  ii3P       ɛtɛ     5
434068         être  ii1S       ɛtɛ    14
434069         être  ii2S       ɛtɛ     1
434070         être  ii3S       ɛtɛ    80
434488         être    pP      ɛtɑ̃     1
434811      étendre  ai3S    ɛtɑ̃di     1
434821      étendre   inf    ɛtɑ̃dʁ     1
435172         être  ii1P     ɛtjɔ̃     2
435243       étirer  ii3S     ɛtiʁɛ     1
435506     étouffer   inf     ɛtufe     1
436181      étudier  ai3S    ɛtydja     1
436205      étudier   inf    ɛtydje     1
436316         être  ppMS       ɛte    26
436627     évanouir  ppMS    ɛvanui     1
436835     éveiller   inf     ɛvɛje     1
437301       éviter   inf     ɛvite     2
437407      évoluer  ppMS    ɛvɔlye     1
437432      évoquer  fi3S   ɛvɔkəʁa     1
437474         être  pi2P        ɛt    16
437476         être   inf       ɛtʁ    24
437497         ôter  ii3S       ɔtɛ     1

[1956 rows x 4 columns]

0
CPU times: user 1min 11s, sys: 19.6 s, total: 1min 30s
Wall time: 30.6 s

nbChunk 291
4200
1939

             lexeme  case        phono  tir1
40            avoir  pi3S            a    87
114      abandonner    pP    abɑ̃dɔnɑ̃     1
141      abandonner  pc2P  abɑ̃dɔnəʁje     1
164      abandonner  ppMS     abɑ̃dɔne     2
168      abandonner  ppFP     abɑ̃dɔne     1
287         abattre  ai3S        abati     1
299         abattre   inf        abatʁ     1
1147        aborder   inf       abɔʁde     1
2051       absorber  ii3S      absɔʁbɛ     1
2116       absoudre   inf       absudʁ     1
2888      accentuer    pP    aksɑ̃tyɑ̃     1
2971       accepter   inf      aksɛpte     1
3385    accompagner  ii3S     akɔ̃paɲɛ     1
3397    accompagner  pi1S      akɔ̃paɲ     1
3406    accompagner   inf     akɔ̃paɲe     1
3515       accorder  ai1S       akɔʁdɛ     1
3519       accorder  ii3S       akɔʁdɛ     1
3583       accorder  ppMP       akɔʁde     1
4280      accrocher  pi2P       akʁɔʃe     1
4369      accroupir  pi3S       akʁupi     1
4509     accueillir   inf       akəjiʁ     1
4656      accumuler   inf      akymyle     1
4685      accumuler  ppFP      akymyle     1
4716        accuser  pi3S         akyz     1
4720        accuser   inf        akyze     2
4783        accéder   inf       aksɛde     1
4835      accélérer   inf     aksɛlɛʁe     1
5119        acheter   inf        aʃəte     1
5171        achever  ppMS        aʃəve     1
5308        acheter  pi1S         aʃɛt     1
...             ...   ...          ...   ...
432160      épouser   inf        ɛpuze     1
432537     éprouver  ii3S       ɛpʁuvɛ     1
432554     éprouver  pi3P        ɛpʁuv     2
432568     éprouver  fi3P    ɛpʁuvəʁɔ̃     1
433912      établir  ppMS       ɛtabli     1
434048         être  ii3P          ɛtɛ     6
434068         être  ii1S          ɛtɛ    19
434070         être  ii3S          ɛtɛ    74
434300       étaler  ppFS        ɛtale     1
434726     éteindre  ii3S        ɛtɛɲɛ     1
434770     éteindre  pi2S         ɛtɛ̃     1
434772     éteindre  ppMS         ɛtɛ̃     1
434782      étendre  pi3S         ɛtɑ̃     1
434901     éternuer  ai3S      ɛtɛʁnya     1
435054         être  ii2P         ɛtje     1
435172         être  ii1P        ɛtjɔ̃     6
435472      étonner  ppFS        ɛtɔne     1
435680     étourdir  pi2S       ɛtuʁdi     1
436205      étudier   inf       ɛtydje     1
436316         être  ppMS          ɛte    23
436457       évader   inf        ɛvade     1
436520      évaluer   inf       ɛvalye     1
436679     évanouir  pi3S       ɛvanui     1
437285       éviter    pP       ɛvitɑ̃     1
437295       éviter  pi3S         ɛvit     1
437301       éviter   inf        ɛvite     1
437318       éviter  ii2P       ɛvitje     1
437323       éviter  pi1P       ɛvitɔ̃     1
437474         être  pi2P           ɛt    13
437476         être   inf          ɛtʁ    26

[1939 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.8 s, total: 1min 37s
Wall time: 29.3 s

nbChunk 292
4200
1914

             lexeme  case      phono  tir1
40            avoir  pi3S          a    86
67         abaisser  pi3S       abɛs     1
128      abandonner  pi3S    abɑ̃dɔn     1
305         abattre  ppMS      abaty     1
890          abolir   inf     abɔliʁ     1
2127       absoudre  pi3S       absu     1
2581         abîmer   inf      abime     1
2764       accabler  ppFS     akable     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     1
2973       accepter  fi1S  aksɛptəʁɛ     1
2977       accepter  pc3S  aksɛptəʁɛ     1
3406    accompagner   inf   akɔ̃paɲe     1
3827      accoucher   inf      akuʃe     1
3913       accouder  ppMS      akude     1
3916       accouder  ppMP      akude     1
4006       accourir  ii3P      akuʁɛ     1
4095       accourir  ppMP      akuʁy     1
4259      accrocher   inf     akʁɔʃe     2
4291      accrocher  ppMS     akʁɔʃe     1
4320      accroupir  ppMS     akʁupi     1
4479     accueillir  pi1S       akœj     1
4509     accueillir   inf     akəjiʁ     2
4748        accuser  ppMS      akyze     1
5119        acheter   inf      aʃəte     1
5124        acheter  pI2P      aʃəte     1
5786     acquiescer  ppMS     akjɛse     1
5905       acquérir   inf     akɛʁiʁ     1
6869       admettre  ii3S     admɛtɛ     1
6883       admettre  pi1P    admɛtɔ̃     1
...             ...   ...        ...   ...
432160      épouser   inf      ɛpuze     1
432302      épouser  ppMS      ɛpuze     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
432556     éprouver   inf     ɛpʁuve     1
432635      épuiser  ii3P     ɛpɥizɛ     1
432689      épuiser  ppMS     ɛpɥize     2
433001   équilibrer  ii3P   ɛkilibʁɛ     1
433914      établir  ppFS     ɛtabli     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    12
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    62
434488         être    pP       ɛtɑ̃     1
434734     éteindre  pi2P      ɛtɛɲe     1
434779     éteindre  ppMP       ɛtɛ̃     1
434839      étendre  ppMP     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     1
435062    étinceler  ii3S   ɛtɛ̃səlɛ     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
435968      étriper  pi3S      ɛtʁip     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    30
436751       évaser  ii3S      ɛvazɛ     1
437285       éviter    pP     ɛvitɑ̃     2
437301       éviter   inf      ɛvite     1
437363      évoluer  pi3S      ɛvɔly     1
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    16
437539         ôter  ppMS        ɔte     1

[1914 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.4 s, total: 1min 39s
Wall time: 30.2 s

nbChunk 293
4200
1945

            lexeme  case      phono  tir1
40           avoir  pi3S          a    79
109     abandonner  ai1S   abɑ̃dɔnɛ     1
132     abandonner   inf   abɑ̃dɔne     1
164     abandonner  ppMS   abɑ̃dɔne     1
252        abattre  pi2S        aba     1
292        abattre  fi3S     abatʁa     1
914         abolir    pP   abɔlisɑ̃     1
1175       aborder  ppMS     abɔʁde     1
1440       aboutir  pi3S      abuti     1
1673       abriter  ii3S     abʁitɛ     1
1686       abriter  pi3P      abʁit     1
1796       abrutir  ppMS     abʁyti     1
1818       abrutir  pi1S     abʁyti     1
2066      absorber  pi3S     absɔʁb     1
2337        abuser  pi3P       abyz     2
2763      accabler  ppMS     akable     1
2765      accabler  ppFP     akable     1
2964      accepter  pi1S     aksɛpt     1
2971      accepter   inf    aksɛpte     1
2973      accepter  fi1S  aksɛptəʁɛ     1
3003      accepter  ppMS    aksɛpte     1
3005      accepter  ppFS    aksɛpte     1
3438     accomplir  ppMS    akɔ̃pli     1
3443     accomplir   inf   akɔ̃pliʁ     1
3858     accoucher  ppMS      akuʃe     1
4291     accrocher  ppMS     akʁɔʃe     1
4292     accrocher  ppFS     akʁɔʃe     2
4321     accroupir  ppFS     akʁupi     1
5042      acharner  ppFS     aʃaʁne     1
5070     acheminer   inf    aʃəmine     1
...            ...   ...        ...   ...
430485    épanouir   inf    ɛpanuiʁ     1
430688      épater   inf      ɛpate     1
432160     épouser   inf      ɛpuze     1
432216  épousseter  pi3S     ɛpusɛt     1
432537    éprouver  ii3S     ɛpʁuvɛ     1
432691     épuiser  ppFS     ɛpɥize     1
433914     établir  ppFS     ɛtabli     1
434048        être  ii3P        ɛtɛ     4
434068        être  ii1S        ɛtɛ    10
434069        être  ii2S        ɛtɛ     1
434070        être  ii3S        ɛtɛ    89
434488        être    pP       ɛtɑ̃     1
434762    éteindre   inf     ɛtɛ̃dʁ     1
434782     étendre  pi3S       ɛtɑ̃     2
434789     étendre    pP    ɛtɑ̃dɑ̃     1
434831     étendre  ppMS     ɛtɑ̃dy     1
435054        être  ii2P       ɛtje     2
435172        être  ii1P      ɛtjɔ̃     2
435417     étonner  ai3S      ɛtɔna     2
435419     étonner  ii3P      ɛtɔnɛ     1
435471     étonner  ppMS      ɛtɔne     1
436203     étudier  pi3P      ɛtydi     1
436205     étudier   inf     ɛtydje     1
436316        être  ppMS        ɛte    24
436520     évaluer   inf     ɛvalye     1
437367     évoluer   inf     ɛvɔlye     1
437424     évoquer  pi1S       ɛvɔk     1
437474        être  pi2P         ɛt    14
437476        être   inf        ɛtʁ    22
437513        ôter  fi3S      ɔtəʁa     1

[1945 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.7 s, total: 1min 40s
Wall time: 30.5 s

nbChunk 294
4200
1986

             lexeme  case     phono  tir1
40            avoir  pi3S         a    88
243         abattre  pi3S       aba     1
688         abjurer  ppMS    abʒyʁe     1
865          aboyer  pi3S      abwa     1
2581         abîmer   inf     abime     1
2763       accabler  ppMS    akable     1
2887      accentuer  ii3S  aksɑ̃tyɛ     1
2904      accentuer   inf  aksɑ̃tye     1
2967       accepter  pi3S    aksɛpt     2
2971       accepter   inf   aksɛpte     2
3003       accepter  ppMS   aksɛpte     1
3385    accompagner  ii3S  akɔ̃paɲɛ     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     3
3438      accomplir  ppMS   akɔ̃pli     1
3475      accomplir  pi3P  akɔ̃plis     1
3536       accorder   inf    akɔʁde     1
3542       accorder  pc3S  akɔʁdəʁɛ     1
4090       accourir  pi3S      akuʁ     1
4095       accourir  ppMP     akuʁy     1
4230      accrocher  ai3S    akʁɔʃa     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4252      accrocher  pi1S     akʁɔʃ     1
4255      accrocher  pi3S     akʁɔʃ     1
4259      accrocher   inf    akʁɔʃe     1
4511     accueillir  ppMP     akəji     1
4720        accuser   inf     akyze     1
4758        accéder  pi3S     aksɛd     1
5146        achever  ii3P     aʃəvɛ     1
5171        achever  ppMS     aʃəve     1
...             ...   ...       ...   ...
427668     éloigner  ppMS    ɛlwaɲe     1
429337     émouvoir  ii3S     ɛmuvɛ     1
430562     épargner   inf    ɛpaʁɲe     1
432156      épouser  pi3S      ɛpuz     1
432162      épouser  fi1S   ɛpuzəʁɛ     1
432302      épouser  ppMS     ɛpuze     1
432556     éprouver   inf    ɛpʁuve     1
432640      épuiser    pP   ɛpɥizɑ̃     1
432691      épuiser  ppFS    ɛpɥize     1
433981      établir  is3S    ɛtabli     1
434048         être  ii3P       ɛtɛ     6
434068         être  ii1S       ɛtɛ    18
434070         être  ii3S       ɛtɛ    69
434768     éteindre  pi1S      ɛtɛ̃     1
434821      étendre   inf    ɛtɑ̃dʁ     1
435054         être  ii2P      ɛtje     3
435425      étonner    pP    ɛtɔnɑ̃     1
435438      étonner  pi3S      ɛtɔn     1
435444      étonner   inf     ɛtɔne     1
435450      étonner  pc3S   ɛtɔnəʁɛ     1
436205      étudier   inf    ɛtydje     1
436316         être  ppMS       ɛte    25
436707     évaporer  pi3S    ɛvapɔʁ     1
436820     éveiller  ii3S     ɛvɛjɛ     1
436835     éveiller   inf     ɛvɛje     1
437301       éviter   inf     ɛvite     1
437431      évoquer   inf     ɛvɔke     2
437474         être  pi2P        ɛt    18
437476         être   inf       ɛtʁ    20
437508         ôter  pi3S        ot     1

[1986 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.5 s, total: 1min 39s
Wall time: 30 s

nbChunk 295
4200
1952

             lexeme  case       phono  tir1
40            avoir  pi3S           a    98
109      abandonner  ai1S    abɑ̃dɔnɛ     1
145      abandonner  pi2S     abɑ̃dɔn     1
299         abattre   inf       abatʁ     1
1716        abriter  ppMS      abʁite     1
2581         abîmer   inf       abime     1
2964       accepter  pi1S      aksɛpt     1
2967       accepter  pi3S      aksɛpt     2
2971       accepter   inf     aksɛpte     1
2984       accepter  pi2S      aksɛpt     1
3003       accepter  ppMS     aksɛpte     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3408    accompagner  fi1S  akɔ̃paɲəʁɛ     1
3422    accompagner  pi2P    akɔ̃paɲe     1
3449      accomplir  pc3S   akɔ̃pliʁɛ     1
3489      accomplir  ai3S     akɔ̃pli     1
3827      accoucher   inf       akuʃe     1
4080       accourir  pc3S      akuʁʁɛ     1
4210     accoutumer  ppMS     akutyme     1
4237      accrocher  ii3S      akʁɔʃɛ     1
4252      accrocher  pi1S       akʁɔʃ     1
4292      accrocher  ppFS      akʁɔʃe     2
4464     accréditer  ppMP    akʁɛdite     1
4509     accueillir   inf      akəjiʁ     2
4634      accumuler  ii3P     akymylɛ     1
4652      accumuler  pi3S      akymyl     1
4684      accumuler  ppFS     akymyle     1
4736        accuser  pi2P       akyze     1
4748        accuser  ppMS       akyze     1
...             ...   ...         ...   ...
429713      énerver  pi2S       ɛnɛʁv     1
431615     épingler  ppMP     ɛpɛ̃gle     1
431830      éployer   inf     ɛplwaje     1
432160      épouser   inf       ɛpuze     1
432181      épouser  pi2P       ɛpuze     1
433341      érafler  pi2P      ɛʁafle     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    16
434070         être  ii3S         ɛtɛ    76
434153       étaler   inf       ɛtale     1
434734     éteindre  pi2P       ɛtɛɲe     2
434747     éteindre  ai3S       ɛtɛɲi     1
434773     éteindre  pi3S        ɛtɛ̃     1
434782      étendre  pi3S        ɛtɑ̃     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434821      étendre   inf      ɛtɑ̃dʁ     1
435172         être  ii1P       ɛtjɔ̃     1
435295       étirer  ppFP       ɛtiʁe     1
435422      étonner  ii3S       ɛtɔnɛ     1
435438      étonner  pi3S        ɛtɔn     1
435444      étonner   inf       ɛtɔne     1
435506     étouffer   inf       ɛtufe     2
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    16
436417      évacuer  pI2P      ɛvakye     1
436820     éveiller  ii3S       ɛvɛjɛ     1
437049     évertuer  ii3S     ɛvɛʁtyɛ     1
437474         être  pi2P          ɛt     5
437476         être   inf         ɛtʁ    21
437492         ôter  ai3S         ɔta     1

[1952 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.4 s, total: 1min 39s
Wall time: 30 s

nbChunk 296
4200
1950

             lexeme  case      phono  tir1
40            avoir  pi3S          a    82
243         abattre  pi3S        aba     1
299         abattre   inf      abatʁ     1
890          abolir   inf     abɔliʁ     1
2076       absorber  pc3S  absɔʁbəʁɛ     1
2124       absoudre  pi1S       absu     1
2581         abîmer   inf      abime     1
2887      accentuer  ii3S   aksɑ̃tyɛ     1
2967       accepter  pi3S     aksɛpt     1
2989       accepter  pi2P    aksɛpte     1
3317     accommoder  ai3S    akɔmɔda     1
3436    accompagner  ppMP   akɔ̃paɲe     1
3438      accomplir  ppMS    akɔ̃pli     1
3571       accorder  ppMS     akɔʁde     1
4210     accoutumer  ppMS    akutyme     1
4259      accrocher   inf     akʁɔʃe     1
4279      accrocher  pI2P     akʁɔʃe     1
4373      accroître  pi3S      akʁwa     1
4381      accroître   inf    akʁwatʁ     1
4475     accueillir    pP     akəjɑ̃     1
4686      accumuler  ppMP    akymyle     1
4720        accuser   inf      akyze     1
4748        accuser  ppMS      akyze     2
5027       acharner  pi2S      aʃaʁn     1
5119        acheter   inf      aʃəte     1
5136        acheter  ppMS      aʃəte     4
5332        achever  pi3S       aʃɛv     1
5754       acquérir  pi3S      akjɛʁ     1
5879      acquitter  ppMS      akite     1
6553        adhérer   inf      adɛʁe     1
...             ...   ...        ...   ...
429727      énerver  ppMS     ɛnɛʁve     1
430570     épargner  fi2P   ɛpaʁɲəʁe     1
430599   éparpiller  ii3S   ɛpaʁpijɛ     1
432160      épouser   inf      ɛpuze     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
432552     éprouver  pi3S      ɛpʁuv     1
432556     éprouver   inf     ɛpʁuve     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    13
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    64
434131       étaler  ii3P      ɛtalɛ     1
434135       étaler    pP     ɛtalɑ̃     1
434831      étendre  ppMS     ɛtɑ̃dy     1
434833      étendre  ppFS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     4
435172         être  ii1P      ɛtjɔ̃     6
435417      étonner  ai3S      ɛtɔna     1
435444      étonner   inf      ɛtɔne     1
435504     étouffer  pi3P       ɛtuf     1
436186      étudier  ii3S     ɛtydjɛ     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    20
436402      évacuer   inf     ɛvakye     1
436867     éveiller  ppMS      ɛvɛje     1
437407      évoluer  ppMS     ɛvɔlye     1
437414      évoquer  ii1S      ɛvɔkɛ     1
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    15
437498         ôter    pP       ɔtɑ̃     1

[1950 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 21.8 s, total: 1min 37s
Wall time: 29.1 s

nbChunk 297
4200
1897

             lexeme  case        phono  tir1
40            avoir  pi3S            a    85
132      abandonner   inf     abɑ̃dɔne     2
261         abattre  ps3S         abat     1
1388        aboutir  ppMS        abuti     1
2051       absorber  ii3S      absɔʁbɛ     1
2339         abuser   inf        abyze     1
2581         abîmer   inf        abime     1
2715       accabler  ii3S       akablɛ     1
2763       accabler  ppMS       akable     1
2884      accentuer  ii3P     aksɑ̃tyɛ     1
2971       accepter   inf      aksɛpte     1
2989       accepter  pi2P      aksɛpte     1
2990       accepter  ii2P     aksɛptje     1
3005       accepter  ppFS      aksɛpte     1
3406    accompagner   inf     akɔ̃paɲe     1
3471      accomplir  ps3S     akɔ̃plis     1
3536       accorder   inf       akɔʁde     1
4654      accumuler  pi3P       akymyl     1
5008       acharner  pi3S        aʃaʁn     1
5119        acheter   inf        aʃəte     1
5136        acheter  ppMS        aʃəte     4
5171        achever  ppMS        aʃəve     1
5329        achever  pi1S         aʃɛv     1
5807       acquérir  ppMS          aki     1
6443        adapter  ppMS       adapte     1
7284        adopter  ppFS       adɔpte     1
7309         adorer  pi1S         adɔʁ     1
7312         adorer  pi3S         adɔʁ     1
7535       adresser  pi3S        adʁɛs     1
7550       adresser  fi1P    adʁɛsəʁɔ̃     1
...             ...   ...          ...   ...
429713      énerver  pi2S        ɛnɛʁv     1
430155     épaissir  ppMS        ɛpɛsi     1
432153      épouser  pi1S         ɛpuz     1
432156      épouser  pi3S         ɛpuz     1
432160      épouser   inf        ɛpuze     1
432302      épouser  ppMS        ɛpuze     1
432549     éprouver  pi1S        ɛpʁuv     1
432552     éprouver  pi3S        ɛpʁuv     1
432556     éprouver   inf       ɛpʁuve     1
432689      épuiser  ppMS       ɛpɥize     1
434048         être  ii3P          ɛtɛ     4
434068         être  ii1S          ɛtɛ    12
434069         être  ii2S          ɛtɛ     1
434070         être  ii3S          ɛtɛ    69
434488         être    pP         ɛtɑ̃     1
434779     éteindre  ppMP         ɛtɛ̃     1
435054         être  ii2P         ɛtje     2
435172         être  ii1P        ɛtjɔ̃     1
435438      étonner  pi3S         ɛtɔn     1
435500     étouffer  pi3S         ɛtuf     1
435654     étourdir  ppMS       ɛtuʁdi     1
435760    étrangler  fi3P  ɛtʁɑ̃gləʁɔ̃     1
436316         être  ppMS          ɛte    35
436402      évacuer   inf       ɛvakye     1
436815     éveiller  ai3S        ɛvɛja     1
437285       éviter    pP       ɛvitɑ̃     1
437424      évoquer  pi1S         ɛvɔk     1
437461      évoquer  ppMP        ɛvɔke     1
437474         être  pi2P           ɛt    17
437476         être   inf          ɛtʁ    20

[1897 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.7 s, total: 1min 36s
Wall time: 29.1 s

nbChunk 298
4200
1905

             lexeme  case     phono  tir1
40            avoir  pi3S         a    90
166      abandonner  ppFS  abɑ̃dɔne     1
1468         aboyer   inf    abwaje     1
1673        abriter  ii3S    abʁitɛ     1
1934       absenter  ii3S   absɑ̃tɛ     1
2355         abuser  pi2P     abyze     1
2967       accepter  pi3S    aksɛpt     2
2971       accepter   inf   aksɛpte     2
2984       accepter  pi2S    aksɛpt     1
3003       accepter  ppMS   aksɛpte     1
3422    accompagner  pi2P  akɔ̃paɲe     1
3519       accorder  ii3S    akɔʁdɛ     1
3530       accorder  pi3S     akɔʁd     1
3821      accoucher  pi3S      akuʃ     1
4095       accourir  ppMP     akuʁy     1
4175     accoutumer  pi1S    akutym     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4322      accroupir  ppFP    akʁupi     1
4426     accréditer   inf  akʁɛdite     1
4519     accueillir  ai3S     akəji     1
4547        acculer   inf     akyle     1
4767        accéder  ai1S    aksɛdɛ     1
5119        acheter   inf     aʃəte     2
5311        acheter  pi3S      aʃɛt     1
6969        admirer  ii3S    admiʁɛ     1
7309         adorer  pi1S      adɔʁ     2
7312         adorer  pi3S      adɔʁ     1
7314         adorer  pi3P      adɔʁ     1
7399        adosser  ppFS     adɔse     1
7539       adresser   inf    adʁɛse     1
...             ...   ...       ...   ...
432532     éprouver  ai3S    ɛpʁuva     1
432535     éprouver  ii1S    ɛpʁuvɛ     1
432556     éprouver   inf    ɛpʁuve     2
432586     éprouver  ppMS    ɛpʁuve     1
433916      établir  ppFP    ɛtabli     1
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ    11
434070         être  ii3S       ɛtɛ    84
434134       étaler  ii3S     ɛtalɛ     1
434773     éteindre  pi3S      ɛtɛ̃     1
434789      étendre    pP   ɛtɑ̃dɑ̃     1
434811      étendre  ai3S    ɛtɑ̃di     3
435054         être  ii2P      ɛtje     1
435444      étonner   inf     ɛtɔne     1
435748    étrangler   inf  ɛtʁɑ̃gle     1
436205      étudier   inf    ɛtydje     1
436316         être  ppMS       ɛte    22
436402      évacuer   inf    ɛvakye     1
436430      évacuer  ppMS    ɛvakye     1
436450       évader  pi1S      ɛvad     1
436867     éveiller  ppMS     ɛvɛje     1
436889      éventer  ii3S    ɛvɑ̃tɛ     1
437301       éviter   inf     ɛvite     1
437317       éviter  pi2P     ɛvite     1
437407      évoluer  ppMS    ɛvɔlye     1
437416      évoquer  ii3S     ɛvɔkɛ     2
437431      évoquer   inf     ɛvɔke     2
437474         être  pi2P        ɛt    20
437476         être   inf       ɛtʁ    19
437512         ôter   inf       ɔte     1

[1905 rows x 4 columns]

0
CPU times: user 1min 19s, sys: 22.3 s, total: 1min 41s
Wall time: 30.3 s

nbChunk 299
4200
1963

             lexeme  case      phono  tir1
40            avoir  pi3S          a    95
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
145      abandonner  pi2S    abɑ̃dɔn     1
164      abandonner  ppMS   abɑ̃dɔne     1
170      abandonner  ppMP   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
305         abattre  ppMS      abaty     1
980         abonder  pi3S      abɔ̃d     1
1133        aborder    pP    abɔʁdɑ̃     1
1674        abriter    pP    abʁitɑ̃     1
1897        abréger  pI2P     abʁɛʒe     1
2066       absorber  pi3S     absɔʁb     1
2947       accepter  ii3P    aksɛptɛ     1
2971       accepter   inf    aksɛpte     1
3003       accepter  ppMS    aksɛpte     3
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     2
3433    accompagner  ppMS   akɔ̃paɲe     1
3434    accompagner  ppFS   akɔ̃paɲe     1
3467      accomplir  ii3S  akɔ̃plisɛ     1
3571       accorder  ppMS     akɔʁde     1
3573       accorder  ppFS     akɔʁde     1
3827      accoucher   inf      akuʃe     1
4255      accrocher  pi3S      akʁɔʃ     1
4291      accrocher  ppMS     akʁɔʃe     2
4292      accrocher  ppFS     akʁɔʃe     1
4339      accroupir  pi1S     akʁupi     1
4502     accueillir  ppMS      akəji     1
4509     accueillir   inf     akəjiʁ     2
...             ...   ...        ...   ...
429713      énerver  pi2S      ɛnɛʁv     1
430509     épanouir  ii3S   ɛpanuisɛ     1
430562     épargner   inf     ɛpaʁɲe     1
430797      épauler  pi1S       ɛpol     1
432532     éprouver  ai3S     ɛpʁuva     1
432586     éprouver  ppMS     ɛpʁuve     1
432689      épuiser  ppMS     ɛpɥize     1
433113      équiper   inf      ɛkipe     1
433912      établir  ppMS     ɛtabli     1
433954      établir  pi3P    ɛtablis     1
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ    11
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    73
434131       étaler  ii3P      ɛtalɛ     1
434134       étaler  ii3S      ɛtalɛ     1
434488         être    pP       ɛtɑ̃     1
434739     éteindre  ai3P     ɛtɛɲiʁ     1
434789      étendre    pP    ɛtɑ̃dɑ̃     1
435054         être  ii2P       ɛtje     1
435375      étoiler  pi3S      ɛtwal     1
435506     étouffer   inf      ɛtufe     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    26
437301       éviter   inf      ɛvite     3
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    16
437476         être   inf        ɛtʁ    15
437493         ôter  ai1S        ɔtɛ     1
437498         ôter    pP       ɔtɑ̃     1

[1963 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 21.9 s, total: 1min 38s
Wall time: 30.6 s

nbChunk 300
4200
1964

             lexeme  case     phono  tir1
40            avoir  pi3S         a    80
113      abandonner  ii3S  abɑ̃dɔnɛ     1
128      abandonner  pi3S   abɑ̃dɔn     1
589        abhorrer   inf     abɔʁe     1
1034        abonner   inf     abɔne     1
2335         abuser  pi3S      abyz     1
2560         abîmer  ai3S     abima     1
2763       accabler  ppMS    akable     1
2936      accentuer  ppFP  aksɑ̃tye     1
2967       accepter  pi3S    aksɛpt     1
2989       accepter  pi2P   aksɛpte     1
3399    accompagner  pI2S   akɔ̃paɲ     1
3463      accomplir  pi2S   akɔ̃pli     1
3508       accorder  ai3S    akɔʁda     1
3543       accorder  fi2S  akɔʁdəʁa     1
3913       accouder  ppMS     akude     1
4261      accrocher  fi1S  akʁɔʃəʁɛ     1
4280      accrocher  pi2P    akʁɔʃe     1
4291      accrocher  ppMS    akʁɔʃe     1
4292      accrocher  ppFS    akʁɔʃe     1
4368      accroupir  ai3S    akʁupi     1
4693        accuser  ii3S     akyzɛ     2
4720        accuser   inf     akyze     1
5112        acheter    pP    aʃətɑ̃     1
5119        acheter   inf     aʃəte     3
5136        acheter  ppMS     aʃəte     1
5171        achever  ppMS     aʃəve     1
5332        achever  pi3S      aʃɛv     1
5814       acquérir  ppFP      akiz     1
5846      acquitter  pi3S      akit     1
...             ...   ...       ...   ...
433026   équilibrer   inf  ɛkilibʁe     1
433586       ériger  pi3P      ɛʁiʒ     1
433679       éroder  ppMP     ɛʁɔde     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    18
434069         être  ii2S       ɛtɛ     2
434070         être  ii3S       ɛtɛ    65
434260    étalonner   inf   ɛtalɔne     1
434300       étaler  ppFS     ɛtale     1
434302       étaler  ppMP     ɛtale     1
434773     éteindre  pi3S      ɛtɛ̃     1
434789      étendre    pP   ɛtɑ̃dɑ̃     1
435172         être  ii1P     ɛtjɔ̃     1
435229    étiqueter  ppFS   ɛtikəte     1
435240       étirer  ii3P     ɛtiʁɛ     1
435417      étonner  ai3S     ɛtɔna     1
435422      étonner  ii3S     ɛtɔnɛ     3
435444      étonner   inf     ɛtɔne     1
435471      étonner  ppMS     ɛtɔne     2
435484     étouffer  ii3S     ɛtufɛ     1
435728    étrangler  ii3P  ɛtʁɑ̃glɛ     1
435742    étrangler  pi3S   ɛtʁɑ̃gl     1
435748    étrangler   inf  ɛtʁɑ̃gle     1
436205      étudier   inf    ɛtydje     1
436316         être  ppMS       ɛte    19
436975     éventrer  ai3S   ɛvɑ̃tʁa     1
437367      évoluer   inf    ɛvɔlye     1
437417      évoquer    pP    ɛvɔkɑ̃     1
437474         être  pi2P        ɛt    11
437476         être   inf       ɛtʁ    30

[1964 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.6 s, total: 1min 40s
Wall time: 30 s

nbChunk 301
4200
1968

             lexeme  case      phono  tir1
40            avoir  pi3S          a    81
148      abandonner  pi2P   abɑ̃dɔne     1
168      abandonner  ppFP   abɑ̃dɔne     1
259         abattre    pP     abatɑ̃     1
1867        abréger  ai3S     abʁɛʒa     1
2053       absorber    pP   absɔʁbɑ̃     1
2100       absorber  ppMS    absɔʁbe     1
2581         abîmer   inf      abime     1
2930      accentuer  ai3P  aksɑ̃tyɛʁ     1
2984       accepter  pi2S     aksɛpt     1
2988       accepter  pI2P    aksɛpte     1
3082     accidenter  ppMS  aksidɑ̃te     1
3397    accompagner  pi1S    akɔ̃paɲ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3423    accompagner  ii2P   akɔ̃paɲe     1
3475      accomplir  pi3P   akɔ̃plis     1
3536       accorder   inf     akɔʁde     1
3569       accorder  ai3P    akɔʁdɛʁ     1
3811      accoucher    pP     akuʃɑ̃     1
4461     accréditer  ppMS   akʁɛdite     1
4482     accueillir  pi3S       akœj     2
4509     accueillir   inf     akəjiʁ     2
4713        accuser  pi1S       akyz     1
4720        accuser   inf      akyze     1
4754        accuser  ppMP      akyze     1
4771        accéder  ii3S     aksɛdɛ     1
4864      accélérer  ppFS   aksɛlɛʁe     1
5008       acharner  pi3S      aʃaʁn     1
5042       acharner  ppFS     aʃaʁne     1
...             ...   ...        ...   ...
432556     éprouver   inf     ɛpʁuve     1
432586     éprouver  ppMS     ɛpʁuve     1
433062   équilibrer  ppMS   ɛkilibʁe     1
433912      établir  ppMS     ɛtabli     1
433914      établir  ppFS     ɛtabli     1
434048         être  ii3P        ɛtɛ     1
434068         être  ii1S        ɛtɛ    12
434070         être  ii3S        ɛtɛ    60
434756     éteindre  fi1S    ɛtɛ̃dʁɛ     1
434768     éteindre  pi1S       ɛtɛ̃     1
434772     éteindre  ppMS       ɛtɛ̃     1
434794      étendre  pi3P      ɛtɑ̃d     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     1
435444      étonner   inf      ɛtɔne     1
435500     étouffer  pi3S       ɛtuf     1
435540     étouffer  ppFS      ɛtufe     1
436205      étudier   inf     ɛtydje     1
436218      étudier  pi2S      ɛtydi     1
436316         être  ppMS        ɛte    30
436402      évacuer   inf     ɛvakye     1
436649     évanouir  pi1S     ɛvanui     1
436997     éventrer   inf    ɛvɑ̃tʁe     1
437301       éviter   inf      ɛvite     3
437328       éviter  ppMS      ɛvite     1
437389      évoluer  pi1P    ɛvɔlyɔ̃     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    18
437492         ôter  ai3S        ɔta     1
437498         ôter    pP       ɔtɑ̃     1

[1968 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.5 s, total: 1min 39s
Wall time: 30.4 s

nbChunk 302
4200
1978

             lexeme  case      phono  tir1
40            avoir  pi3S          a   115
45         abaisser  ai3S      abɛsa     1
52         abaisser    pP     abɛsɑ̃     1
114      abandonner    pP  abɑ̃dɔnɑ̃     1
128      abandonner  pi3S    abɑ̃dɔn     1
258         abattre  ii3S      abatɛ     1
299         abattre   inf      abatʁ     1
1388        aboutir  ppMS      abuti     1
1393        aboutir   inf     abutiʁ     1
2100       absorber  ppMS    absɔʁbe     1
2324         abuser  ii3S      abyzɛ     1
2352         abuser  pi2S       abyz     1
2730       accabler  pi3S      akabl     1
2888      accentuer    pP  aksɑ̃tyɑ̃     1
2952       accepter    pP   aksɛptɑ̃     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     4
2984       accepter  pi2S     aksɛpt     1
3400    accompagner  pi3S    akɔ̃paɲ     2
3433    accompagner  ppMS   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     2
3475      accomplir  pi3P   akɔ̃plis     1
3527       accorder  pi1S      akɔʁd     1
4091       accourir  ppMS      akuʁy     1
4255      accrocher  pi3S      akʁɔʃ     1
4259      accrocher   inf     akʁɔʃe     1
4294      accrocher  ppMP     akʁɔʃe     1
4381      accroître   inf    akʁwatʁ     1
4748        accuser  ppMS      akyze     1
5102        acheter  ai3S      aʃəta     1
...             ...   ...        ...   ...
432552     éprouver  pi3S      ɛpʁuv     2
432556     éprouver   inf     ɛpʁuve     1
433325      érafler   inf     ɛʁafle     1
433435     érailler  ppMP      ɛʁaje     1
433912      établir  ppMS     ɛtabli     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    14
434070         être  ii3S        ɛtɛ    64
434135       étaler    pP     ɛtalɑ̃     1
434302       étaler  ppMP      ɛtale     1
434488         être    pP       ɛtɑ̃     2
434768     éteindre  pi1S       ɛtɛ̃     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434833      étendre  ppFS     ɛtɑ̃dy     1
434868    éterniser   inf   ɛtɛʁnize     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     1
435244       étirer    pP     ɛtiʁɑ̃     1
435295       étirer  ppFP      ɛtiʁe     1
435420      étonner  ii1S      ɛtɔnɛ     1
435438      étonner  pi3S       ɛtɔn     1
436205      étudier   inf     ɛtydje     2
436316         être  ppMS        ɛte    20
436997     éventrer   inf    ɛvɑ̃tʁe     1
437285       éviter    pP     ɛvitɑ̃     2
437295       éviter  pi3S       ɛvit     1
437416      évoquer  ii3S      ɛvɔkɛ     2
437458      évoquer  ppMS      ɛvɔke     1
437474         être  pi2P         ɛt    10
437476         être   inf        ɛtʁ    15

[1978 rows x 4 columns]

0
CPU times: user 1min 5s, sys: 14.9 s, total: 1min 20s
Wall time: 31.9 s

nbChunk 303
4200
1930

             lexeme  case       phono  tir1
40            avoir  pi3S           a    88
109      abandonner  ai1S    abɑ̃dɔnɛ     1
132      abandonner   inf    abɑ̃dɔne     1
140      abandonner  fi2P  abɑ̃dɔnəʁe     1
164      abandonner  ppMS    abɑ̃dɔne     1
299         abattre   inf       abatʁ     1
307         abattre  ppFS       abaty     1
443        abdiquer  ppMS      abdike     1
1440        aboutir  pi3S       abuti     1
1601       abreuver  ppFS      abʁəve     1
2900      accentuer  pi3S     aksɑ̃ty     1
3003       accepter  ppMS     aksɛpte     1
3117       acclamer   inf      aklame     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3527       accorder  pi1S       akɔʁd     1
4294      accrocher  ppMP      akʁɔʃe     1
4369      accroupir  pi3S      akʁupi     1
4373      accroître  pi3S       akʁwa     1
4426     accréditer   inf    akʁɛdite     1
4509     accueillir   inf      akəjiʁ     2
4748        accuser  ppMS       akyze     1
5119        acheter   inf       aʃəte     1
5308        acheter  pi1S        aʃɛt     1
5321        acheter  fi2S     aʃɛtəʁa     1
5340        achever  pc3P     aʃɛvəʁɛ     1
6528        adhérer  pi3S        adɛʁ     1
7023        admirer  ppMS      admiʁe     1
7051     admonester  ai3S   admɔnɛsta     1
7312         adorer  pi3S        adɔʁ     2
...             ...   ...         ...   ...
432586     éprouver  ppMS      ɛpʁuve     1
432691      épuiser  ppFS      ɛpɥize     1
433912      établir  ppMS      ɛtabli     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ    12
434069         être  ii2S         ɛtɛ     1
434070         être  ii3S         ɛtɛ    58
434300       étaler  ppFS       ɛtale     1
434772     éteindre  ppMS        ɛtɛ̃     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
435172         être  ii1P       ɛtjɔ̃     2
435471      étonner  ppMS       ɛtɔne     1
435475     étouffer  ai3S       ɛtufa     1
435482     étouffer  ii1S       ɛtufɛ     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    28
436461       évader  pc1S     ɛvadəʁɛ     1
436520      évaluer   inf      ɛvalye     1
436547      évaluer  ppMS      ɛvalye     1
436873     éveiller  ppMP       ɛvɛje     1
437244    éviscérer   inf     ɛvisɛʁe     1
437301       éviter   inf       ɛvite     1
437367      évoluer   inf      ɛvɔlye     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437431      évoquer   inf       ɛvɔke     1
437458      évoquer  ppMS       ɛvɔke     1
437474         être  pi2P          ɛt     9
437476         être   inf         ɛtʁ    25
437512         ôter   inf         ɔte     1

[1930 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.3 s, total: 1min 40s
Wall time: 30.6 s

nbChunk 304
4200
1976

             lexeme  case       phono  tir1
40            avoir  pi3S           a    86
129      abandonner  ps3S     abɑ̃dɔn     1
136      abandonner  pc1S  abɑ̃dɔnəʁɛ     1
145      abandonner  pi2S     abɑ̃dɔn     1
164      abandonner  ppMS    abɑ̃dɔne     1
683         abjurer  pi1P     abʒyʁɔ̃     1
1393        aboutir   inf      abutiʁ     1
1440        aboutir  pi3S       abuti     1
1686        abriter  pi3P       abʁit     1
1851        abrutir  ai3S      abʁyti     1
1979       absenter  ppMS     absɑ̃te     1
2952       accepter    pP    aksɛptɑ̃     1
2967       accepter  pi3S      aksɛpt     2
2984       accepter  pi2S      aksɛpt     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3433    accompagner  ppMS    akɔ̃paɲe     2
3438      accomplir  ppMS     akɔ̃pli     1
3443      accomplir   inf    akɔ̃pliʁ     1
3490      accomplir  pi3S     akɔ̃pli     1
3549       accorder  pi2S       akɔʁd     1
3810      accoucher  ii3S       akuʃɛ     1
4255      accrocher  pi3S       akʁɔʃ     1
4259      accrocher   inf      akʁɔʃe     1
4502     accueillir  ppMS       akəji     1
4656      accumuler   inf     akymyle     1
4736        accuser  pi2P       akyze     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     3
5137        acheter  ppFS       aʃəte     1
...             ...   ...         ...   ...
430646   éparpiller  ppMP    ɛpaʁpije     1
431992      éponger   inf      ɛpɔ̃ʒe     1
432160      épouser   inf       ɛpuze     1
432535     éprouver  ii1S      ɛpʁuvɛ     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
433922      établir   inf     ɛtabliʁ     2
433946      établir  ii3S    ɛtablisɛ     1
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ    17
434070         être  ii3S         ɛtɛ    60
434151       étaler  pi3P        ɛtal     1
434762     éteindre   inf      ɛtɛ̃dʁ     2
434773     éteindre  pi3S        ɛtɛ̃     2
434779     éteindre  ppMP        ɛtɛ̃     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     1
435244       étirer    pP      ɛtiʁɑ̃     1
435293       étirer  ppMS       ɛtiʁe     1
435422      étonner  ii3S       ɛtɔnɛ     1
435435      étonner  pi1S        ɛtɔn     1
436316         être  ppMS         ɛte    20
436653     évanouir  ii3P    ɛvanuisɛ     1
436821     éveiller    pP      ɛvɛjɑ̃     1
436865     éveiller  ai3P      ɛvɛjɛʁ     1
436873     éveiller  ppMP       ɛvɛje     1
437301       éviter   inf       ɛvite     1
437302       éviter  fi3S     ɛvitəʁa     1
437474         être  pi2P          ɛt    23
437476         être   inf         ɛtʁ    20
437492         ôter  ai3S         ɔta     1

[1976 rows x 4 columns]

0
CPU times: user 1min 9s, sys: 20.2 s, total: 1min 29s
Wall time: 29.9 s

nbChunk 305
4200
1948

             lexeme  case       phono  tir1
40            avoir  pi3S           a    75
137      abandonner  pc2S  abɑ̃dɔnəʁɛ     1
166      abandonner  ppFS    abɑ̃dɔne     1
170      abandonner  ppMP    abɑ̃dɔne     2
299         abattre   inf       abatʁ     1
1147        aborder   inf      abɔʁde     1
2971       accepter   inf     aksɛpte     1
3003       accepter  ppMS     aksɛpte     1
3005       accepter  ppFS     aksɛpte     1
3115       acclamer  pi3P       aklam     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3435    accompagner  ppFP    akɔ̃paɲe     1
3440      accomplir  ppFS     akɔ̃pli     1
3460      accomplir  pi1S     akɔ̃pli     1
3569       accorder  ai3P     akɔʁdɛʁ     1
4502     accueillir  ppMS       akəji     3
4509     accueillir   inf      akəjiʁ     2
4626        acculer  ppMS       akyle     1
4713        accuser  pi1S        akyz     1
4783        accéder   inf      aksɛde     1
4849      accélérer  pi2P    aksɛlɛʁe     1
5119        acheter   inf       aʃəte     4
5149        achever  ii3S       aʃəvɛ     1
5311        acheter  pi3S        aʃɛt     1
5318        acheter  pc1S     aʃɛtəʁɛ     1
5329        achever  pi1S        aʃɛv     1
5807       acquérir  ppMS         aki     1
6862       admettre  pi3S        admɛ     1
6891       admettre   inf      admɛtʁ     1
...             ...   ...         ...   ...
427923       élever  pi3S        ɛlɛv     1
428401      émerger    pP     ɛmɛʁʒɑ̃     1
428419      émerger  fi3S    ɛmɛʁʒəʁa     1
428609      émettre  pi3S         ɛmɛ     1
429365     émouvoir  ppMS         ɛmy     1
429367     émouvoir  ppFS         ɛmy     1
430042     énumérer   inf     ɛnymɛʁe     1
430210     épaissir  pi3S       ɛpɛsi     1
432167      épouser  fi2S     ɛpuzəʁa     1
432556     éprouver   inf      ɛpʁuve     1
432689      épuiser  ppMS      ɛpɥize     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    15
434070         être  ii3S         ɛtɛ    76
434773     éteindre  pi3S        ɛtɛ̃     1
434782      étendre  pi3S        ɛtɑ̃     1
434821      étendre   inf      ɛtɑ̃dʁ     1
434831      étendre  ppMS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     2
435422      étonner  ii3S       ɛtɔnɛ     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435791    étreindre  ii3P      ɛtʁɛɲɛ     1
436201      étudier  pi3S       ɛtydi     2
436316         être  ppMS         ɛte    27
437301       éviter   inf       ɛvite     2
437427      évoquer  pi3S        ɛvɔk     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    21
437512         ôter   inf         ɔte     1

[1948 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.4 s, total: 1min 39s
Wall time: 30.8 s

nbChunk 306
4200
1967

             lexeme  case       phono  tir1
40            avoir  pi3S           a    93
110      abandonner  ii3P    abɑ̃dɔnɛ     1
133      abandonner  fi3S  abɑ̃dɔnəʁa     1
145      abandonner  pi2S     abɑ̃dɔn     1
164      abandonner  ppMS    abɑ̃dɔne     1
1110        abonner  ppMS       abɔne     1
1673        abriter  ii3S      abʁitɛ     1
1861        abréger  pi3P       abʁɛʒ     1
2063       absorber  pi1S      absɔʁb     1
2971       accepter   inf     aksɛpte     1
2989       accepter  pi2P     aksɛpte     1
3003       accepter  ppMS     aksɛpte     1
3005       accepter  ppFS     aksɛpte     1
3319     accommoder  ii3P     akɔmɔdɛ     1
3406    accompagner   inf    akɔ̃paɲe     1
3530       accorder  pi3S       akɔʁd     1
3571       accorder  ppMS      akɔʁde     1
3952      accoupler  ii3S      akuplɛ     1
4238      accrocher    pP     akʁɔʃɑ̃     1
4257      accrocher  pi3P       akʁɔʃ     1
4259      accrocher   inf      akʁɔʃe     1
4509     accueillir   inf      akəjiʁ     1
4720        accuser   inf       akyze     1
4750        accuser  ppFS       akyze     1
5119        acheter   inf       aʃəte     7
5137        acheter  ppFS       aʃəte     2
5149        achever  ii3S       aʃəvɛ     1
5758     acquiescer  pi3S       akjɛs     1
6414        adapter   inf      adapte     1
6528        adhérer  pi3S        adɛʁ     1
...             ...   ...         ...   ...
430579     épargner  pi2P      ɛpaʁɲe     1
432160      épouser   inf       ɛpuze     3
432532     éprouver  ai3S      ɛpʁuva     1
432535     éprouver  ii1S      ɛpʁuvɛ     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
432556     éprouver   inf      ɛpʁuve     1
432689      épuiser  ppMS      ɛpɥize     1
433922      établir   inf     ɛtabliʁ     1
433954      établir  pi3P     ɛtablis     1
434048         être  ii3P         ɛtɛ    10
434068         être  ii1S         ɛtɛ    12
434070         être  ii3S         ɛtɛ    70
434134       étaler  ii3S       ɛtalɛ     1
434301       étaler  ppFP       ɛtale     1
435172         être  ii1P       ɛtjɔ̃     2
435425      étonner    pP      ɛtɔnɑ̃     1
435438      étonner  pi3S        ɛtɔn     1
435457      étonner  pi2S        ɛtɔn     1
435471      étonner  ppMS       ɛtɔne     2
435538     étouffer  ppMS       ɛtufe     1
436218      étudier  pi2S       ɛtydi     1
436316         être  ppMS         ɛte    22
436828     éveiller  pi1S        ɛvɛj     1
436980     éventrer  ii3S     ɛvɑ̃tʁɛ     1
437301       éviter   inf       ɛvite     2
437304       éviter  pc3P     ɛvitəʁɛ     1
437329       éviter  ppFS       ɛvite     1
437417      évoquer    pP      ɛvɔkɑ̃     1
437474         être  pi2P          ɛt    20
437476         être   inf         ɛtʁ    22

[1967 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22 s, total: 1min 38s
Wall time: 30.2 s

nbChunk 307
4200
1966

             lexeme  case     phono  tir1
40            avoir  pi3S         a    74
101        abaisser  ppMS     abɛse     1
132      abandonner   inf  abɑ̃dɔne     1
616        abhorrer  ppMS     abɔʁe     1
1468         aboyer   inf    abwaje     1
1932       absenter  ii1S   absɑ̃tɛ     1
2048       absorber  ii3P   absɔʁbɛ     1
2904      accentuer   inf  aksɑ̃tye     1
2939       accepter  ai3S   aksɛpta     1
2950       accepter  ii3S   aksɛptɛ     1
2964       accepter  pi1S    aksɛpt     1
2971       accepter   inf   aksɛpte     2
2989       accepter  pi2P   aksɛpte     1
3003       accepter  ppMS   aksɛpte     1
3406    accompagner   inf  akɔ̃paɲe     1
3433    accompagner  ppMS  akɔ̃paɲe     2
3443      accomplir   inf  akɔ̃pliʁ     1
3530       accorder  pi3S     akɔʁd     2
3539       accorder  pc3P  akɔʁdəʁɛ     1
3827      accoucher   inf     akuʃe     1
4259      accrocher   inf    akʁɔʃe     1
4320      accroupir  ppMS    akʁupi     1
4690        accuser  ii3P     akyzɛ     1
4812      accélérer  pi3S   aksɛlɛʁ     1
4823      accélérer  ii3S  aksɛlɛʁɛ     1
4835      accélérer   inf  aksɛlɛʁe     1
5111        acheter  ii3S     aʃətɛ     1
5119        acheter   inf     aʃəte     3
5125        acheter  pi2P     aʃəte     2
5136        acheter  ppMS     aʃəte     1
...             ...   ...       ...   ...
432142      épouser  ii1S     ɛpuzɛ     1
432160      épouser   inf     ɛpuze     2
432537     éprouver  ii3S    ɛpʁuvɛ     1
432689      épuiser  ppMS    ɛpɥize     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ    12
434070         être  ii3S       ɛtɛ    84
434072       étaler  ai3S     ɛtala     1
434131       étaler  ii3P     ɛtalɛ     1
434153       étaler   inf     ɛtale     1
434488         être    pP      ɛtɑ̃     1
434722       étayer  ppMP     ɛtɛje     1
434747     éteindre  ai3S     ɛtɛɲi     1
434811      étendre  ai3S    ɛtɑ̃di     1
435054         être  ii2P      ɛtje     4
435172         être  ii1P     ɛtjɔ̃     2
435410      étoiler  ppFS    ɛtwale     1
435412      étoiler  ppFP    ɛtwale     1
435422      étonner  ii3S     ɛtɔnɛ     1
435463      étonner  ii1P   ɛtɔnjɔ̃     1
435538     étouffer  ppMS     ɛtufe     1
435972      étriper   inf    ɛtʁipe     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    24
436402      évacuer   inf    ɛvakye     1
437285       éviter    pP    ɛvitɑ̃     1
437294       éviter  pI2S      ɛvit     1
437301       éviter   inf     ɛvite     1
437474         être  pi2P        ɛt    13
437476         être   inf       ɛtʁ    22

[1966 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.2 s, total: 1min 39s
Wall time: 30.2 s

nbChunk 308
4200
1963

             lexeme  case     phono  tir1
40            avoir  pi3S         a    74
132      abandonner   inf  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     1
166      abandonner  ppFS  abɑ̃dɔne     1
1133        aborder    pP   abɔʁdɑ̃     1
1439        aboutir  ai3S     abuti     1
1554       abreuver  ii3S    abʁəvɛ     1
1688        abriter   inf    abʁite     2
1950       absenter   inf   absɑ̃te     1
2335         abuser  pi3S      abyz     1
2577         abîmer  pi3S      abim     1
2610         abîmer  ppMS     abime     1
2614         abîmer  ppFP     abime     1
2715       accabler  ii3S    akablɛ     1
2727       accabler  pi1S     akabl     1
2763       accabler  ppMS    akable     1
2964       accepter  pi1S    aksɛpt     1
2967       accepter  pi3S    aksɛpt     1
2971       accepter   inf   aksɛpte     1
3003       accepter  ppMS   aksɛpte     1
3385    accompagner  ii3S  akɔ̃paɲɛ     1
3400    accompagner  pi3S   akɔ̃paɲ     2
3868       accouder    pP    akudɑ̃     1
4230      accrocher  ai3S    akʁɔʃa     1
4259      accrocher   inf    akʁɔʃe     1
4403      accroître  ai3S      akʁy     1
4482     accueillir  pi3S      akœj     1
4716        accuser  pi3S      akyz     1
4748        accuser  ppMS     akyze     1
5040       acharner  ai3P   aʃaʁnɛʁ     1
...             ...   ...       ...   ...
427641     éloigner   inf    ɛlwaɲe     1
427671     éloigner  ppMP    ɛlwaɲe     1
428397      émerger  ii3P    ɛmɛʁʒɛ     1
429728      énerver  ppFS    ɛnɛʁve     1
430590     épargner  ppMS    ɛpaʁɲe     1
430688       épater   inf     ɛpate     1
432160      épouser   inf     ɛpuze     1
432303      épouser  ppFS     ɛpuze     1
433022   équilibrer  pi3S   ɛkilibʁ     1
434004       étager  pi3P      ɛtaʒ     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ    11
434070         être  ii3S       ɛtɛ    67
434488         être    pP      ɛtɑ̃     1
434755     éteindre  fi3S   ɛtɛ̃dʁa     1
434831      étendre  ppMS    ɛtɑ̃dy     1
434833      étendre  ppFS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     2
435228    étiqueter  ppMS   ɛtikəte     1
435243       étirer  ii3S     ɛtiʁɛ     1
435474      étonner  ppMP     ɛtɔne     1
435506     étouffer   inf     ɛtufe     1
435843    étreindre  ppMP     ɛtʁɛ̃     1
436205      étudier   inf    ɛtydje     1
436316         être  ppMS       ɛte    17
436835     éveiller   inf     ɛvɛje     1
437301       éviter   inf     ɛvite     1
437474         être  pi2P        ɛt    24
437476         être   inf       ɛtʁ    11

[1963 rows x 4 columns]

0
CPU times: user 1min 10s, sys: 20.4 s, total: 1min 30s
Wall time: 29.6 s

nbChunk 309
4200
1912

            lexeme  case      phono  tir1
40           avoir  pi3S          a    91
50        abaisser  ii3S      abɛsɛ     1
108     abandonner  ai3S   abɑ̃dɔna     1
128     abandonner  pi3S    abɑ̃dɔn     1
148     abandonner  pi2P   abɑ̃dɔne     1
164     abandonner  ppMS   abɑ̃dɔne     1
2100      absorber  ppMS    absɔʁbe     1
2577        abîmer  pi3S       abim     1
2763      accabler  ppMS     akable     1
2967      accepter  pi3S     aksɛpt     1
2988      accepter  pI2P    aksɛpte     1
2994      accepter  ii1P  aksɛptjɔ̃     1
3003      accepter  ppMS    aksɛpte     1
3536      accorder   inf     akɔʁde     1
3556      accorder  pi2P     akɔʁde     1
3827     accoucher   inf      akuʃe     1
3913      accouder  ppMS      akude     1
4280     accrocher  pi2P     akʁɔʃe     1
4320     accroupir  ppMS     akʁupi     1
4337     accroupir  ppMP     akʁupi     1
4686     accumuler  ppMP    akymyle     1
4688       accuser  ai3S      akyza     1
4716       accuser  pi3S       akyz     1
5014      acharner   inf     aʃaʁne     1
5119       acheter   inf      aʃəte     1
5136       acheter  ppMS      aʃəte     1
5140       achever  ai3S      aʃəva     1
5311       acheter  pi3S       aʃɛt     5
5316       acheter  fi1S    aʃɛtəʁɛ     1
5327       acheter  pi2S       aʃɛt     1
...            ...   ...        ...   ...
428844     émettre  ppMS        ɛmi     1
429365    émouvoir  ppMS        ɛmy     1
430562    épargner   inf     ɛpaʁɲe     1
430869      épeler   inf      ɛpəle     1
432160     épouser   inf      ɛpuze     3
432552    éprouver  pi3S      ɛpʁuv     1
432689     épuiser  ppMS     ɛpɥize     1
433916     établir  ppFP     ɛtabli     1
433922     établir   inf    ɛtabliʁ     2
433969     établir  pi3S     ɛtabli     1
434048        être  ii3P        ɛtɛ     2
434068        être  ii1S        ɛtɛ    16
434070        être  ii3S        ɛtɛ    65
434131      étaler  ii3P      ɛtalɛ     1
434720      étayer  ppFS      ɛtɛje     1
434747    éteindre  ai3S      ɛtɛɲi     1
435054        être  ii2P       ɛtje     6
435172        être  ii1P      ɛtjɔ̃     1
435780   étrangler  ppMS   ɛtʁɑ̃gle     1
436233     étudier  ppMS     ɛtydje     1
436316        être  ppMS        ɛte    22
436867    éveiller  ppMS      ɛvɛje     1
436997    éventrer   inf    ɛvɑ̃tʁe     1
437301      éviter   inf      ɛvite     4
437328      éviter  ppMS      ɛvite     1
437363     évoluer  pi3S      ɛvɔly     1
437431     évoquer   inf      ɛvɔke     1
437474        être  pi2P         ɛt    10
437476        être   inf        ɛtʁ    17
437497        ôter  ii3S        ɔtɛ     1

[1912 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 21.2 s, total: 1min 33s
Wall time: 29.8 s

nbChunk 310
4200
1945

             lexeme  case      phono  tir1
40            avoir  pi3S          a    75
132      abandonner   inf   abɑ̃dɔne     2
164      abandonner  ppMS   abɑ̃dɔne     1
305         abattre  ppMS      abaty     1
1393        aboutir   inf     abutiʁ     1
2610         abîmer  ppMS      abime     1
2948       accepter  ii1S    aksɛptɛ     1
2950       accepter  ii3S    aksɛptɛ     1
2964       accepter  pi1S     aksɛpt     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     3
3406    accompagner   inf   akɔ̃paɲe     2
3440      accomplir  ppFS    akɔ̃pli     1
3519       accorder  ii3S     akɔʁdɛ     1
3530       accorder  pi3S      akɔʁd     1
4252      accrocher  pi1S      akʁɔʃ     1
4519     accueillir  ai3S      akəji     1
4686      accumuler  ppMP    akymyle     1
4783        accéder   inf     aksɛde     1
5136        acheter  ppMS      aʃəte     1
5149        achever  ii3S      aʃəvɛ     1
5843      acquitter  pi1S       akit     1
7023        admirer  ppMS     admiʁe     1
7311         adorer  pI2S       adɔʁ     1
8295        affamer  ppMS      afame     1
9764       affubler  ppMS     afyble     1
9986         agacer   inf      agase     1
10010        agacer  ppMS      agase     2
10364          agir  ppMS        aʒi     1
10456          agir  ps3S       aʒis     1
...             ...   ...        ...   ...
432580     éprouver  pi1P    ɛpʁuvɔ̃     1
432584     éprouver  ai3P    ɛpʁuvɛʁ     1
432689      épuiser  ppMS     ɛpɥize     1
433169      équiper  ppMS      ɛkipe     1
433914      établir  ppFS     ɛtabli     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    16
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    65
434131       étaler  ii3P      ɛtalɛ     1
434151       étaler  pi3P       ɛtal     1
434730     éteindre  pi3P       ɛtɛɲ     1
434798      étendre  pi2P     ɛtɑ̃de     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     1
435111    étinceler  ai3P  ɛtɛ̃səlɛʁ     1
435172         être  ii1P      ɛtjɔ̃     2
435422      étonner  ii3S      ɛtɔnɛ     1
435474      étonner  ppMP      ɛtɔne     1
435828    étreindre   inf    ɛtʁɛ̃dʁ     1
436186      étudier  ii3S     ɛtydjɛ     1
436201      étudier  pi3S      ɛtydi     1
436316         être  ppMS        ɛte    24
436457       évader   inf      ɛvade     1
436820     éveiller  ii3S      ɛvɛjɛ     1
437285       éviter    pP     ɛvitɑ̃     1
437301       éviter   inf      ɛvite     2
437458      évoquer  ppMS      ɛvɔke     2
437474         être  pi2P         ɛt    13
437476         être   inf        ɛtʁ    17

[1945 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.2 s, total: 1min 38s
Wall time: 30.4 s

nbChunk 311
4200
1969

             lexeme  case      phono  tir1
40            avoir  pi3S          a    76
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
168      abandonner  ppFP   abɑ̃dɔne     1
307         abattre  ppFS      abaty     1
1174        aborder  ai3P    abɔʁdɛʁ     1
1393        aboutir   inf     abutiʁ     1
1415        aboutir  ii3S    abutisɛ     1
1485         aboyer  ppMS     abwaje     1
1950       absenter   inf    absɑ̃te     1
2070       absorber   inf    absɔʁbe     1
2715       accabler  ii3S     akablɛ     1
2950       accepter  ii3S    aksɛptɛ     1
2964       accepter  pi1S     aksɛpt     1
2971       accepter   inf    aksɛpte     2
2972       accepter  fi3S  aksɛptəʁa     1
2997       accepter  pi1P   aksɛptɔ̃     1
3005       accepter  ppFS    aksɛpte     1
3317     accommoder  ai3S    akɔmɔda     1
3343     accommoder  pi3S     akɔmɔd     1
3386    accompagner    pP  akɔ̃paɲɑ̃     1
3530       accorder  pi3S      akɔʁd     1
3536       accorder   inf     akɔʁde     2
3573       accorder  ppFS     akɔʁde     1
4259      accrocher   inf     akʁɔʃe     2
4294      accrocher  ppMP     akʁɔʃe     1
4373      accroître  pi3S      akʁwa     1
4626        acculer  ppMS      akyle     1
4748        accuser  ppMS      akyze     1
4809      accélérer  pi1S    aksɛlɛʁ     1
...             ...   ...        ...   ...
432160      épouser   inf      ɛpuze     1
432302      épouser  ppMS      ɛpuze     1
432305      épouser  ppFP      ɛpuze     1
432556     éprouver   inf     ɛpʁuve     1
433575       ériger  ii3P      ɛʁiʒɛ     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ    14
434070         être  ii3S        ɛtɛ    85
434772     éteindre  ppMS       ɛtɛ̃     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434789      étendre    pP    ɛtɑ̃dɑ̃     1
434833      étendre  ppFS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     1
435089    étinceler  pi3P    ɛtɛ̃sɛl     1
435172         être  ii1P      ɛtjɔ̃     1
435417      étonner  ai3S      ɛtɔna     2
435438      étonner  pi3S       ɛtɔn     1
435444      étonner   inf      ɛtɔne     1
435486     étouffer    pP     ɛtufɑ̃     1
435506     étouffer   inf      ɛtufe     1
436316         être  ppMS        ɛte    23
436815     éveiller  ai3S      ɛvɛja     1
436835     éveiller   inf      ɛvɛje     1
437301       éviter   inf      ɛvite     1
437328       éviter  ppMS      ɛvite     1
437367      évoluer   inf     ɛvɔlye     1
437474         être  pi2P         ɛt    14
437476         être   inf        ɛtʁ    19
437508         ôter  pi3S         ot     1

[1969 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.2 s, total: 1min 38s
Wall time: 30.2 s

nbChunk 312
4200
1983

             lexeme  case       phono  tir1
40            avoir  pi3S           a    78
108      abandonner  ai3S    abɑ̃dɔna     1
132      abandonner   inf    abɑ̃dɔne     1
170      abandonner  ppMP    abɑ̃dɔne     1
305         abattre  ppMS       abaty     1
2339         abuser   inf       abyze     1
2904      accentuer   inf    aksɑ̃tye     1
3003       accepter  ppMS     aksɛpte     1
3005       accepter  ppFS     aksɛpte     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     1
3414    accompagner  fi2P  akɔ̃paɲəʁe     1
3571       accorder  ppMS      akɔʁde     1
4090       accourir  pi3S        akuʁ     1
4238      accrocher    pP     akʁɔʃɑ̃     1
4255      accrocher  pi3S       akʁɔʃ     1
4259      accrocher   inf      akʁɔʃe     1
4473     accueillir  ii3S       akəjɛ     1
5053      acheminer  ii3S     aʃəminɛ     1
5136        acheter  ppMS       aʃəte     3
5338        achever  fi3S     aʃɛvəʁa     1
6443        adapter  ppMS      adapte     1
6891       admettre   inf      admɛtʁ     1
6969        admirer  ii3S      admiʁɛ     1
7031       admettre  ppFS       admiz     1
7283        adopter  ppMS      adɔpte     2
7295         adorer  ii1S       adɔʁɛ     1
7354        adosser  ii3S       adɔsɛ     1
7557       adresser  ii2P     adʁɛsje     1
7989      affaiblir  ii3S    afɛblisɛ     1
...             ...   ...         ...   ...
431864     éplucher  pi1S       ɛplyʃ     1
432156      épouser  pi3S        ɛpuz     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
432689      épuiser  ppMS      ɛpɥize     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ    18
434069         être  ii2S         ɛtɛ     1
434070         être  ii3S         ɛtɛ    75
434782      étendre  pi3S        ɛtɑ̃     1
435054         être  ii2P        ɛtje     2
435089    étinceler  pi3P     ɛtɛ̃sɛl     1
435172         être  ii1P       ɛtjɔ̃     1
435244       étirer    pP      ɛtiʁɑ̃     1
435450      étonner  pc3S     ɛtɔnəʁɛ     2
435463      étonner  ii1P     ɛtɔnjɔ̃     1
435486     étouffer    pP      ɛtufɑ̃     1
435506     étouffer   inf       ɛtufe     1
435660     étourdir   inf     ɛtuʁdiʁ     1
435731    étrangler  ii3S    ɛtʁɑ̃glɛ     1
436186      étudier  ii3S      ɛtydjɛ     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    18
436520      évaluer   inf      ɛvalye     1
436632     évanouir   inf     ɛvanuiʁ     1
436831     éveiller  pi3S        ɛvɛj     1
437301       éviter   inf       ɛvite     1
437329       éviter  ppFS       ɛvite     1
437474         être  pi2P          ɛt     8
437476         être   inf         ɛtʁ    18

[1983 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.7 s, total: 1min 37s
Wall time: 30.3 s

nbChunk 313
4200
1945

             lexeme  case      phono  tir1
40            avoir  pi3S          a    91
114      abandonner    pP  abɑ̃dɔnɑ̃     1
128      abandonner  pi3S    abɑ̃dɔn     1
130      abandonner  pi3P    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
305         abattre  ppMS      abaty     1
1175        aborder  ppMS     abɔʁde     1
1388        aboutir  ppMS      abuti     1
1684        abriter  pi3S      abʁit     1
1946       absenter  pi3S     absɑ̃t     1
2114       absoudre  pc3S    absudʁɛ     1
2946       accepter  ai1S    aksɛptɛ     1
2950       accepter  ii3S    aksɛptɛ     1
2969       accepter  pi3P     aksɛpt     1
2972       accepter  fi3S  aksɛptəʁa     1
2989       accepter  pi2P    aksɛpte     1
3434    accompagner  ppFS   akɔ̃paɲe     1
3519       accorder  ii3S     akɔʁdɛ     1
4293      accrocher  ppFP     akʁɔʃe     1
4321      accroupir  ppFS     akʁupi     1
4656      accumuler   inf    akymyle     1
4693        accuser  ii3S      akyzɛ     1
5136        acheter  ppMS      aʃəte     2
5137        acheter  ppFS      aʃəte     1
5140        achever  ai3S      aʃəva     1
5308        acheter  pi1S       aʃɛt     1
5311        acheter  pi3S       aʃɛt     1
5313        acheter  pi3P       aʃɛt     1
5327        acheter  pi2S       aʃɛt     1
...             ...   ...        ...   ...
429367     émouvoir  ppFS        ɛmy     1
429694      énerver  pi3S      ɛnɛʁv     1
430558     épargner  pi3S      ɛpaʁɲ     1
430594   éparpiller  ai3S   ɛpaʁpija     1
432153      épouser  pi1S       ɛpuz     2
432164      épouser  pc1S    ɛpuzəʁɛ     1
432531     éprendre  ai3S       ɛpʁi     1
432539     éprouver    pP    ɛpʁuvɑ̃     1
432552     éprouver  pi3S      ɛpʁuv     1
432689      épuiser  ppMS     ɛpɥize     2
433170      équiper  ppFS      ɛkipe     1
433238   équivaloir  pi3S      ɛkivo     1
433912      établir  ppMS     ɛtabli     1
433922      établir   inf    ɛtabliʁ     2
433987       étager  pi3S       ɛtaʒ     1
434048         être  ii3P        ɛtɛ     6
434068         être  ii1S        ɛtɛ    15
434070         être  ii3S        ɛtɛ    64
434782      étendre  pi3S       ɛtɑ̃     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     2
435294       étirer  ppFS      ɛtiʁe     1
435425      étonner    pP     ɛtɔnɑ̃     1
435438      étonner  pi3S       ɛtɔn     1
436316         être  ppMS        ɛte    24
436835     éveiller   inf      ɛvɛje     1
437284       éviter  ii3S      ɛvitɛ     1
437305       éviter  pc1S    ɛvitəʁɛ     1
437474         être  pi2P         ɛt     8
437476         être   inf        ɛtʁ    33

[1945 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.6 s, total: 1min 34s
Wall time: 29.4 s

nbChunk 314
4200
1935

             lexeme  case       phono  tir1
40            avoir  pi3S           a    86
45         abaisser  ai3S       abɛsa     1
128      abandonner  pi3S     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
134      abandonner  fi1S  abɑ̃dɔnəʁɛ     1
166      abandonner  ppFS    abɑ̃dɔne     2
177      abasourdir  ppMS    abazuʁdi     1
261         abattre  ps3S        abat     1
1571       abreuver   inf      abʁəve     1
2371         abuser  ppMS       abyze     1
2878      accentuer  ai3S    aksɑ̃tya     1
2947       accepter  ii3P     aksɛptɛ     1
2952       accepter    pP    aksɛptɑ̃     1
2964       accepter  pi1S      aksɛpt     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     2
2977       accepter  pc3S   aksɛptəʁɛ     1
3406    accompagner   inf    akɔ̃paɲe     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3443      accomplir   inf    akɔ̃pliʁ     1
3530       accorder  pi3S       akɔʁd     1
3534       accorder  pi3P       akɔʁd     1
3884       accouder   inf       akude     1
4320      accroupir  ppMS      akʁupi     1
4475     accueillir    pP      akəjɑ̃     1
4486     accueillir  fi3S     akəjəʁa     1
4693        accuser  ii3S       akyzɛ     2
4809      accélérer  pi1S     aksɛlɛʁ     1
4835      accélérer   inf    aksɛlɛʁe     1
5014       acharner   inf      aʃaʁne     1
...             ...   ...         ...   ...
432156      épouser  pi3S        ɛpuz     1
432531     éprendre  ai3S        ɛpʁi     1
432532     éprouver  ai3S      ɛpʁuva     1
432586     éprouver  ppMS      ɛpʁuve     1
433912      établir  ppMS      ɛtabli     1
433914      établir  ppFS      ɛtabli     1
433936      établir  ppMP      ɛtabli     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    14
434070         être  ii3S         ɛtɛ    63
434762     éteindre   inf      ɛtɛ̃dʁ     1
434773     éteindre  pi3S        ɛtɛ̃     2
434831      étendre  ppMS      ɛtɑ̃dy     1
435172         être  ii1P       ɛtjɔ̃     1
435438      étonner  pi3S        ɛtɔn     2
435506     étouffer   inf       ɛtufe     1
435782    étrangler  ppFS    ɛtʁɑ̃gle     1
435794    étreindre  ii3S      ɛtʁɛɲɛ     1
435828    étreindre   inf     ɛtʁɛ̃dʁ     1
436316         être  ppMS         ɛte    19
436402      évacuer   inf      ɛvakye     1
436867     éveiller  ppMS       ɛvɛje     1
436997     éventrer   inf     ɛvɑ̃tʁe     1
437049     évertuer  ii3S     ɛvɛʁtyɛ     1
437282       éviter  ii1S       ɛvitɛ     1
437284       éviter  ii3S       ɛvitɛ     1
437301       éviter   inf       ɛvite     1
437474         être  pi2P          ɛt    14
437476         être   inf         ɛtʁ    18
437508         ôter  pi3S          ot     1

[1935 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.6 s, total: 1min 36s
Wall time: 29.5 s

nbChunk 315
4200
1922

             lexeme  case       phono  tir1
40            avoir  pi3S           a    82
74         abaisser  fi3S     abɛsəʁa     1
134      abandonner  fi1S  abɑ̃dɔnəʁɛ     1
292         abattre  fi3S      abatʁa     1
1159        aborder  fi3P   abɔʁdəʁɔ̃     1
2100       absorber  ppMS     absɔʁbe     1
2226       abstenir  pi1S     abstjɛ̃     1
2952       accepter    pP    aksɛptɑ̃     1
2967       accepter  pi3S      aksɛpt     1
2979       accepter  fi2P   aksɛptəʁe     1
2989       accepter  pi2P     aksɛpte     1
3003       accepter  ppMS     aksɛpte     3
3406    accompagner   inf    akɔ̃paɲe     1
3444      accomplir  fi3S   akɔ̃pliʁa     1
3455      accomplir  fi1P  akɔ̃pliʁɔ̃     1
3467      accomplir  ii3S   akɔ̃plisɛ     1
3827      accoucher   inf       akuʃe     1
4259      accrocher   inf      akʁɔʃe     2
4473     accueillir  ii3S       akəjɛ     1
4482     accueillir  pi3S        akœj     1
4688        accuser  ai3S       akyza     1
5070      acheminer   inf     aʃəmine     1
5136        acheter  ppMS       aʃəte     1
5173        achever  ppFS       aʃəve     1
5313        acheter  pi3P        aʃɛt     1
5332        achever  pi3S        aʃɛv     1
7309         adorer  pi1S        adɔʁ     1
7312         adorer  pi3S        adɔʁ     4
7344         adorer  ppFS       adɔʁe     1
7518       adresser  ai3S      adʁɛsa     1
...             ...   ...         ...   ...
427657     éloigner  pi2P      ɛlwaɲe     1
429349     émouvoir   inf     ɛmuvwaʁ     1
429691      énerver  pi1S       ɛnɛʁv     2
429728      énerver  ppFS      ɛnɛʁve     1
430579     épargner  pi2P      ɛpaʁɲe     1
432160      épouser   inf       ɛpuze     1
432531     éprendre  ai3S        ɛpʁi     1
432535     éprouver  ii1S      ɛpʁuvɛ     1
432537     éprouver  ii3S      ɛpʁuvɛ     2
432586     éprouver  ppMS      ɛpʁuve     2
432588     éprouver  ppFS      ɛpʁuve     1
433950      établir  ps3S     ɛtablis     1
434068         être  ii1S         ɛtɛ    22
434070         être  ii3S         ɛtɛ    70
434772     éteindre  ppMS        ɛtɛ̃     1
434811      étendre  ai3S      ɛtɑ̃di     1
434923     éternuer   inf     ɛtɛʁnye     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     1
435194    étiqueter  pi2P     ɛtikəte     1
435438      étonner  pi3S        ɛtɔn     2
436316         être  ppMS         ɛte    16
436402      évacuer   inf      ɛvakye     1
436457       évader   inf       ɛvade     1
436653     évanouir  ii3P    ɛvanuisɛ     1
436867     éveiller  ppMS       ɛvɛje     1
437367      évoluer   inf      ɛvɔlye     1
437431      évoquer   inf       ɛvɔke     2
437474         être  pi2P          ɛt     7
437476         être   inf         ɛtʁ    26

[1922 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.7 s, total: 1min 36s
Wall time: 29.8 s

nbChunk 316
4200
1926

             lexeme  case        phono  tir1
40            avoir  pi3S            a    88
108      abandonner  ai3S     abɑ̃dɔna     1
132      abandonner   inf     abɑ̃dɔne     1
166      abandonner  ppFS     abɑ̃dɔne     1
1143        aborder  pi3S        abɔʁd     1
2100       absorber  ppMS      absɔʁbe     1
2774      accaparer  ii3S      akapaʁɛ     1
3380    accompagner  ai3S     akɔ̃paɲa     1
3385    accompagner  ii3S     akɔ̃paɲɛ     1
3404    accompagner  pi3P      akɔ̃paɲ     1
3418    accompagner  fi3P  akɔ̃paɲəʁɔ̃     1
3423    accompagner  ii2P     akɔ̃paɲe     1
3433    accompagner  ppMS     akɔ̃paɲe     1
3438      accomplir  ppMS      akɔ̃pli     1
3443      accomplir   inf     akɔ̃pliʁ     1
3536       accorder   inf       akɔʁde     1
4259      accrocher   inf       akʁɔʃe     1
4293      accrocher  ppFP       akʁɔʃe     1
4684      accumuler  ppFS      akymyle     1
4716        accuser  pi3S         akyz     1
4748        accuser  ppMS        akyze     1
4783        accéder   inf       aksɛde     1
5041       acharner  ppMS       aʃaʁne     1
5119        acheter   inf        aʃəte     1
5140        achever  ai3S        aʃəva     1
5150        achever    pP       aʃəvɑ̃     1
5316        acheter  fi1S      aʃɛtəʁɛ     1
6386        adapter  ii3P       adaptɛ     1
6390        adapter    pP      adaptɑ̃     1
6410        adapter  pi3S        adapt     1
...             ...   ...          ...   ...
426706      élargir  ppFS       ɛlaʁʒi     1
427639     éloigner  pi3P        ɛlwaɲ     1
428609      émettre  pi3S          ɛmɛ     1
431575     épingler   inf      ɛpɛ̃gle     1
431864     éplucher  pi1S        ɛplyʃ     1
432160      épouser   inf        ɛpuze     1
433113      équiper   inf        ɛkipe     1
434048         être  ii3P          ɛtɛ     3
434068         être  ii1S          ɛtɛ     8
434070         être  ii3S          ɛtɛ    78
434747     éteindre  ai3S        ɛtɛɲi     1
434785      étendre  ii3P       ɛtɑ̃dɛ     1
435172         être  ii1P        ɛtjɔ̃     2
435243       étirer  ii3S        ɛtiʁɛ     1
435417      étonner  ai3S        ɛtɔna     1
435438      étonner  pi3S         ɛtɔn     3
435742    étrangler  pi3S      ɛtʁɑ̃gl     1
436205      étudier   inf       ɛtydje     1
436233      étudier  ppMS       ɛtydje     1
436316         être  ppMS          ɛte    31
436484       évader  ppMS        ɛvade     1
436867     éveiller  ppMS        ɛvɛje     1
437198      évincer  ppMS       ɛvɛ̃se     1
437273       éviter  ai3S        ɛvita     1
437284       éviter  ii3S        ɛvitɛ     1
437301       éviter   inf        ɛvite     2
437431      évoquer   inf        ɛvɔke     1
437474         être  pi2P           ɛt    10
437476         être   inf          ɛtʁ    12
437512         ôter   inf          ɔte     1

[1926 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 21.4 s, total: 1min 34s
Wall time: 28.7 s

nbChunk 317
4200
1885

             lexeme  case      phono  tir1
40            avoir  pi3S          a    86
128      abandonner  pi3S    abɑ̃dɔn     1
177      abasourdir  ppMS   abazuʁdi     1
299         abattre   inf      abatʁ     1
305         abattre  ppMS      abaty     2
1147        aborder   inf     abɔʁde     1
1307        abouler  pi3S       abul     1
2343         abuser  pc1S    abyzəʁɛ     1
2371         abuser  ppMS      abyze     1
2566         abîmer    pP     abimɑ̃     1
2712       accabler  ii3P     akablɛ     1
2884      accentuer  ii3P   aksɑ̃tyɛ     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     1
2977       accepter  pc3S  aksɛptəʁɛ     1
3003       accepter  ppMS    aksɛpte     2
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3434    accompagner  ppFS   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     3
3516       accorder  ii3P     akɔʁdɛ     1
4006       accourir  ii3P      akuʁɛ     1
4235      accrocher  ii1S     akʁɔʃɛ     1
4290      accrocher  ai3P    akʁɔʃɛʁ     1
4292      accrocher  ppFS     akʁɔʃe     2
4473     accueillir  ii3S      akəjɛ     1
4532        acculer  ii3S      akylɛ     1
4748        accuser  ppMS      akyze     1
4835      accélérer   inf   aksɛlɛʁe     1
5119        acheter   inf      aʃəte     2
...             ...   ...        ...   ...
431787        épier  ai3P      ɛpjɛʁ     1
432052    épouiller  pi3S       ɛpuj     1
432160      épouser   inf      ɛpuze     2
432164      épouser  pc1S    ɛpuzəʁɛ     1
432535     éprouver  ii1S     ɛpʁuvɛ     1
432552     éprouver  pi3S      ɛpʁuv     1
432689      épuiser  ppMS     ɛpɥize     1
433912      établir  ppMS     ɛtabli     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ    10
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    71
434147       étaler  pi3S       ɛtal     1
434151       étaler  pi3P       ɛtal     1
434299       étaler  ppMS      ɛtale     1
434775     éteindre  ppFS      ɛtɛ̃t     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     2
435296       étirer  ppMP      ɛtiʁe     1
435438      étonner  pi3S       ɛtɔn     1
435506     étouffer   inf      ɛtufe     1
435780    étrangler  ppMS   ɛtʁɑ̃gle     1
436186      étudier  ii3S     ɛtydjɛ     1
436205      étudier   inf     ɛtydje     2
436316         être  ppMS        ɛte    23
436632     évanouir   inf    ɛvanuiʁ     1
437458      évoquer  ppMS      ɛvɔke     2
437474         être  pi2P         ɛt     7
437476         être   inf        ɛtʁ    11

[1885 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.9 s, total: 1min 37s
Wall time: 29.6 s

nbChunk 318
4200
1933

             lexeme  case      phono  tir1
40            avoir  pi3S          a    96
305         abattre  ppMS      abaty     1
1950       absenter   inf    absɑ̃te     1
2581         abîmer   inf      abime     1
2939       accepter  ai3S    aksɛpta     1
2948       accepter  ii1S    aksɛptɛ     1
2967       accepter  pi3S     aksɛpt     1
2969       accepter  pi3P     aksɛpt     1
2975       accepter  pc1S  aksɛptəʁɛ     1
2989       accepter  pi2P    aksɛpte     1
3003       accepter  ppMS    aksɛpte     1
3324     accommoder    pP   akɔmɔdɑ̃     1
3380    accompagner  ai3S   akɔ̃paɲa     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     2
3556       accorder  pi2P     akɔʁde     1
3569       accorder  ai3P    akɔʁdɛʁ     1
3805      accoucher  ai3S      akuʃa     1
4259      accrocher   inf     akʁɔʃe     1
4280      accrocher  pi2P     akʁɔʃe     1
4303      accroître  ii3S    akʁwasɛ     1
4321      accroupir  ppFS     akʁupi     1
4502     accueillir  ppMS      akəji     2
4683      accumuler  ppMS    akymyle     1
5119        acheter   inf      aʃəte     2
5137        acheter  ppFS      aʃəte     1
5149        achever  ii3S      aʃəvɛ     1
5171        achever  ppMS      aʃəve     1
6969        admirer  ii3S     admiʁɛ     1
...             ...   ...        ...   ...
427320       élever  ai3P     ɛləvɛʁ     1
427482     éliminer  ppMS    ɛlimine     1
427624     éloigner  ii3S     ɛlwaɲɛ     1
427937       élever  fi1P   ɛlɛvəʁɔ̃     1
428742      émigrer   inf     ɛmigʁe     1
431167        épier   inf       ɛpje     2
432160      épouser   inf      ɛpuze     1
432162      épouser  fi1S    ɛpuzəʁɛ     2
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    17
434070         être  ii3S        ɛtɛ    87
434301       étaler  ppFP      ɛtale     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     2
435438      étonner  pi3S       ɛtɔn     1
435486     étouffer    pP     ɛtufɑ̃     1
435968      étriper  pi3S      ɛtʁip     1
436188      étudier    pP    ɛtydjɑ̃     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    27
436457       évader   inf      ɛvade     1
436533      évaluer  pi2S      ɛvaly     1
436762       évaser  pi3S       ɛvaz     1
436818     éveiller  ii1S      ɛvɛjɛ     1
437046     évertuer  ii3P    ɛvɛʁtyɛ     1
437060     évertuer  pi3S     ɛvɛʁty     1
437301       éviter   inf      ɛvite     5
437474         être  pi2P         ɛt    11
437476         être   inf        ɛtʁ    24

[1933 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.4 s, total: 1min 38s
Wall time: 30.2 s

nbChunk 319
4200
1973

             lexeme  case      phono  tir1
40            avoir  pi3S          a    88
52         abaisser    pP     abɛsɑ̃     1
114      abandonner    pP  abɑ̃dɔnɑ̃     1
164      abandonner  ppMS   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
1688        abriter   inf     abʁite     1
2715       accabler  ii3S     akablɛ     1
2939       accepter  ai3S    aksɛpta     1
2964       accepter  pi1S     aksɛpt     1
2971       accepter   inf    aksɛpte     1
2975       accepter  pc1S  aksɛptəʁɛ     1
3115       acclamer  pi3P      aklam     1
3380    accompagner  ai3S   akɔ̃paɲa     1
3397    accompagner  pi1S    akɔ̃paɲ     1
3432    accompagner  ai3P  akɔ̃paɲɛʁ     1
3434    accompagner  ppFS   akɔ̃paɲe     1
4255      accrocher  pi3S      akʁɔʃ     1
4294      accrocher  ppMP     akʁɔʃe     1
4482     accueillir  pi3S       akœj     1
4693        accuser  ii3S      akyzɛ     1
4758        accéder  pi3S      aksɛd     1
5125        acheter  pi2P      aʃəte     2
5131        acheter  pi1P     aʃətɔ̃     1
5136        acheter  ppMS      aʃəte     6
5140        achever  ai3S      aʃəva     1
5149        achever  ii3S      aʃəvɛ     1
5308        acheter  pi1S       aʃɛt     1
5321        acheter  fi2S    aʃɛtəʁa     1
6530        adhérer  pi3P       adɛʁ     1
6891       admettre   inf     admɛtʁ     1
...             ...   ...        ...   ...
432052    épouiller  pi3S       ɛpuj     1
432160      épouser   inf      ɛpuze     1
432302      épouser  ppMS      ɛpuze     1
432519     éprendre  ppMS       ɛpʁi     1
432556     éprouver   inf     ɛpʁuve     1
432709       épurer  ii3S      ɛpyʁɛ     1
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ    12
434070         être  ii3S        ɛtɛ    84
434302       étaler  ppMP      ɛtale     1
434726     éteindre  ii3S      ɛtɛɲɛ     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434833      étendre  ppFS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     5
435172         être  ii1P      ɛtjɔ̃     2
435243       étirer  ii3S      ɛtiʁɛ     1
435244       étirer    pP     ɛtiʁɑ̃     1
435417      étonner  ai3S      ɛtɔna     1
435471      étonner  ppMS      ɛtɔne     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
435780    étrangler  ppMS   ɛtʁɑ̃gle     1
435838    étreindre  pi3S      ɛtʁɛ̃     1
436316         être  ppMS        ɛte    20
436549      évaluer  ppFP     ɛvalye     1
437301       éviter   inf      ɛvite     1
437411      évoquer  ai3S      ɛvɔka     1
437416      évoquer  ii3S      ɛvɔkɛ     1
437474         être  pi2P         ɛt    16
437476         être   inf        ɛtʁ    12
437539         ôter  ppMS        ɔte     1

[1973 rows x 4 columns]

0
CPU times: user 1min 11s, sys: 21 s, total: 1min 32s
Wall time: 28.6 s

nbChunk 320
4200
1878

             lexeme  case      phono  tir1
40            avoir  pi3S          a    85
125      abandonner  pi1S    abɑ̃dɔn     1
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     2
166      abandonner  ppFS   abɑ̃dɔne     1
170      abandonner  ppMP   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
2971       accepter   inf    aksɛpte     1
3386    accompagner    pP  akɔ̃paɲɑ̃     2
3467      accomplir  ii3S  akɔ̃plisɛ     1
4210     accoutumer  ppMS    akutyme     2
4255      accrocher  pi3S      akʁɔʃ     1
4473     accueillir  ii3S      akəjɛ     1
4684      accumuler  ppFS    akymyle     1
5119        acheter   inf      aʃəte     3
5136        acheter  ppMS      aʃəte     1
5311        acheter  pi3S       aʃɛt     1
5313        acheter  pi3P       aʃɛt     1
6103        activer  pi1P    aktivɔ̃     1
6443        adapter  ppMS     adapte     1
6863       admettre  pi1S       admɛ     1
6991        admirer  pi3S      admiʁ     2
6996        admirer   inf     admiʁe     2
7012        admirer  pi2P     admiʁe     1
7046       admettre  ai3S       admi     2
7312         adorer  pi3S       adɔʁ     1
7343         adorer  ppMS      adɔʁe     1
7455        adoucir  ppMS      adusi     1
8264        affamer   inf      afame     1
8554       afficher   inf      afiʃe     1
...             ...   ...        ...   ...
430013     énucléer  ppMP    ɛnyklɛe     1
430562     épargner   inf     ɛpaʁɲe     1
430568     épargner  pc3S   ɛpaʁɲəʁɛ     1
431065        épier    pP      ɛpjɑ̃     1
431609     épingler  ppMS    ɛpɛ̃gle     1
432153      épouser  pi1S       ɛpuz     1
432160      épouser   inf      ɛpuze     1
433590       ériger   inf      ɛʁiʒe     1
433922      établir   inf    ɛtabliʁ     1
433939      établir  pi1S     ɛtabli     1
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ    16
434070         être  ii3S        ɛtɛ    66
434300       étaler  ppFS      ɛtale     1
434488         être    pP       ɛtɑ̃     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     2
435438      étonner  pi3S       ɛtɔn     2
435506     étouffer   inf      ɛtufe     1
435519     étouffer  pi2S       ɛtuf     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    21
437024     éventrer  ppMS    ɛvɑ̃tʁe     1
437458      évoquer  ppMS      ɛvɔke     1
437461      évoquer  ppMP      ɛvɔke     1
437474         être  pi2P         ɛt    11
437476         être   inf        ɛtʁ    19

[1878 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.3 s, total: 1min 38s
Wall time: 30.4 s

nbChunk 321
4200
1974

             lexeme  case     phono  tir1
40            avoir  pi3S         a    86
264         abattre  pi3P      abat     1
299         abattre   inf     abatʁ     1
1440        aboutir  pi3S     abuti     1
1674        abriter    pP   abʁitɑ̃     1
1882        abréger  pI1P   abʁɛʒɔ̃     1
2715       accabler  ii3S    akablɛ     1
2939       accepter  ai3S   aksɛpta     1
2952       accepter    pP  aksɛptɑ̃     1
2971       accepter   inf   aksɛpte     3
3400    accompagner  pi3S   akɔ̃paɲ     1
3404    accompagner  pi3P   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     1
3434    accompagner  ppFS  akɔ̃paɲe     1
3492      accomplir  is3S   akɔ̃pli     1
3519       accorder  ii3S    akɔʁdɛ     1
3556       accorder  pi2P    akɔʁde     1
3821      accoucher  pi3S      akuʃ     1
3862       accouder  ai3S     akuda     1
3913       accouder  ppMS     akude     1
4291      accrocher  ppMS    akʁɔʃe     1
4654      accumuler  pi3P    akymyl     1
4688        accuser  ai3S     akyza     1
4835      accélérer   inf  aksɛlɛʁe     1
4992       acharner  ai3S    aʃaʁna     1
5119        acheter   inf     aʃəte     5
5136        acheter  ppMS     aʃəte     2
5137        acheter  ppFS     aʃəte     1
5311        acheter  pi3S      aʃɛt     1
5316        acheter  fi1S   aʃɛtəʁɛ     1
...             ...   ...       ...   ...
431065        épier    pP     ɛpjɑ̃     1
431167        épier   inf      ɛpje     1
431971      éponger  pi3S     ɛpɔ̃ʒ     1
432160      épouser   inf     ɛpuze     2
432519     éprendre  ppMS      ɛpʁi     1
432549     éprouver  pi1S     ɛpʁuv     1
432659      épuiser   inf    ɛpɥize     1
433195   équivaloir  ii3S   ɛkivalɛ     1
433433     érailler  ppFP     ɛʁaje     1
434048         être  ii3P       ɛtɛ     7
434068         être  ii1S       ɛtɛ    12
434070         être  ii3S       ɛtɛ    68
434299       étaler  ppMS     ɛtale     1
434300       étaler  ppFS     ɛtale     1
434773     éteindre  pi3S      ɛtɛ̃     1
434817      étendre  pc1S   ɛtɑ̃dʁɛ     1
435054         être  ii2P      ɛtje     1
435135      étioler   inf    ɛtjɔle     1
435172         être  ii1P     ɛtjɔ̃     5
435293       étirer  ppMS     ɛtiʁe     1
435450      étonner  pc3S   ɛtɔnəʁɛ     1
435512     étouffer  pc3S   ɛtufəʁɛ     1
436198      étudier  pi1S     ɛtydi     1
436316         être  ppMS       ɛte    23
436457       évader   inf     ɛvade     1
436520      évaluer   inf    ɛvalye     2
437301       éviter   inf     ɛvite     1
437328       éviter  ppMS     ɛvite     1
437474         être  pi2P        ɛt    19
437476         être   inf       ɛtʁ    15

[1974 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.7 s, total: 1min 36s
Wall time: 29.4 s

nbChunk 322
4200
1917

             lexeme  case      phono  tir1
40            avoir  pi3S          a    97
114      abandonner    pP  abɑ̃dɔnɑ̃     1
125      abandonner  pi1S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
258         abattre  ii3S      abatɛ     1
313         abattre  ppMP      abaty     1
616        abhorrer  ppMS      abɔʁe     1
955         abonder  ii3P     abɔ̃dɛ     1
1468         aboyer   inf     abwaje     1
2157       abstenir  ppMP    abstəny     1
2939       accepter  ai3S    aksɛpta     1
2948       accepter  ii1S    aksɛptɛ     1
2969       accepter  pi3P     aksɛpt     1
3383    accompagner  ii1S   akɔ̃paɲɛ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3517       accorder  ii1S     akɔʁdɛ     1
3519       accorder  ii3S     akɔʁdɛ     1
3534       accorder  pi3P      akɔʁd     1
4216     accoutumer  ppMP    akutyme     1
4293      accrocher  ppFP     akʁɔʃe     1
4809      accélérer  pi1S    aksɛlɛʁ     1
5042       acharner  ppFS     aʃaʁne     1
5111        acheter  ii3S      aʃətɛ     1
5119        acheter   inf      aʃəte     2
5308        acheter  pi1S       aʃɛt     1
5325        acheter  fi1P   aʃɛtəʁɔ̃     1
6444        adapter  ppFS     adapte     1
6578        adhérer  ppMS      adɛʁe     1
6891       admettre   inf     admɛtʁ     1
...             ...   ...        ...   ...
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    82
434147       étaler  pi3S       ɛtal     2
434488         être    pP       ɛtɑ̃     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434770     éteindre  pi2S       ɛtɛ̃     1
434773     éteindre  pi3S       ɛtɛ̃     1
434782      étendre  pi3S       ɛtɑ̃     2
434833      étendre  ppFS     ɛtɑ̃dy     1
435172         être  ii1P      ɛtjɔ̃     2
435232       étirer  ai3S      ɛtiʁa     1
435731    étrangler  ii3S   ɛtʁɑ̃glɛ     1
436188      étudier    pP    ɛtydjɑ̃     1
436205      étudier   inf     ɛtydje     2
436316         être  ppMS        ɛte    21
436402      évacuer   inf     ɛvakye     1
436516      évaluer  pi3S      ɛvaly     1
436632     évanouir   inf    ɛvanuiʁ     2
436807       évaser  ppFS      ɛvaze     1
437292       éviter  pi1S       ɛvit     1
437299       éviter  pi3P       ɛvit     1
437301       éviter   inf      ɛvite     1
437317       éviter  pi2P      ɛvite     1
437328       éviter  ppMS      ɛvite     1
437474         être  pi2P         ɛt     9
437476         être   inf        ɛtʁ    18
437492         ôter  ai3S        ɔta     1
437508         ôter  pi3S         ot     1
437510         ôter  pi3P         ot     1
437512         ôter   inf        ɔte     1

[1917 rows x 4 columns]

0
CPU times: user 1min 10s, sys: 20.2 s, total: 1min 30s
Wall time: 29.9 s

nbChunk 323
4200
1937

             lexeme  case       phono  tir1
40            avoir  pi3S           a   107
67         abaisser  pi3S        abɛs     1
102        abaisser  ppFS       abɛse     1
113      abandonner  ii3S    abɑ̃dɔnɛ     1
128      abandonner  pi3S     abɑ̃dɔn     2
148      abandonner  pi2P    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     1
307         abattre  ppFS       abaty     1
1393        aboutir   inf      abutiʁ     1
2143       abstenir   inf    abstəniʁ     1
2335         abuser  pi3S        abyz     1
2971       accepter   inf     aksɛpte     1
3382    accompagner  ii3P    akɔ̃paɲɛ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3433    accompagner  ppMS    akɔ̃paɲe     3
3443      accomplir   inf    akɔ̃pliʁ     1
3488      accomplir  pi1P  akɔ̃plisɔ̃     1
3527       accorder  pi1S       akɔʁd     1
3534       accorder  pi3P       akɔʁd     1
3571       accorder  ppMS      akɔʁde     3
4280      accrocher  pi2P      akʁɔʃe     1
4381      accroître   inf     akʁwatʁ     1
4684      accumuler  ppFS     akymyle     1
4686      accumuler  ppMP     akymyle     1
5102        acheter  ai3S       aʃəta     1
5111        acheter  ii3S       aʃətɛ     1
5119        acheter   inf       aʃəte     3
5136        acheter  ppMS       aʃəte     2
5149        achever  ii3S       aʃəvɛ     1
5313        acheter  pi3P        aʃɛt     1
...             ...   ...         ...   ...
432144      épouser  ii3S       ɛpuzɛ     1
432160      épouser   inf       ɛpuze     1
432537     éprouver  ii3S      ɛpʁuvɛ     3
432588     éprouver  ppFS      ɛpʁuve     1
433063   équilibrer  ppFS    ɛkilibʁe     1
433991       étager  ii3P       ɛtaʒɛ     1
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ    12
434069         être  ii2S         ɛtɛ     2
434070         être  ii3S         ɛtɛ    73
434153       étaler   inf       ɛtale     1
434950     éternuer  ppMS     ɛtɛʁnye     1
435054         être  ii2P        ɛtje     4
435062    étinceler  ii3S    ɛtɛ̃səlɛ     1
435085    étinceler  pi3S     ɛtɛ̃sɛl     1
435172         être  ii1P       ɛtjɔ̃     3
435422      étonner  ii3S       ɛtɔnɛ     1
435425      étonner    pP      ɛtɔnɑ̃     1
435438      étonner  pi3S        ɛtɔn     1
435444      étonner   inf       ɛtɔne     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    22
436484       évader  ppMS       ɛvade     1
436664     évanouir  pi3P     ɛvanuis     1
436997     éventrer   inf     ɛvɑ̃tʁe     1
437301       éviter   inf       ɛvite     2
437416      évoquer  ii3S       ɛvɔkɛ     1
437474         être  pi2P          ɛt    10
437476         être   inf         ɛtʁ    14

[1937 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.6 s, total: 1min 40s
Wall time: 31 s

nbChunk 324
4200
2009

             lexeme  case       phono  tir1
40            avoir  pi3S           a    72
132      abandonner   inf    abɑ̃dɔne     2
139      abandonner  fi2S  abɑ̃dɔnəʁa     1
164      abandonner  ppMS    abɑ̃dɔne     1
166      abandonner  ppFS    abɑ̃dɔne     1
305         abattre  ppMS       abaty     1
1143        aborder  pi3S       abɔʁd     1
1565       abreuver  pi3S       abʁœv     1
2100       absorber  ppMS     absɔʁbe     1
2710       accabler  ai3S      akabla     1
2971       accepter   inf     aksɛpte     1
3003       accepter  ppMS     aksɛpte     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3397    accompagner  pi1S     akɔ̃paɲ     2
3419    accompagner  pi2S     akɔ̃paɲ     1
3422    accompagner  pi2P    akɔ̃paɲe     2
3433    accompagner  ppMS    akɔ̃paɲe     1
3555       accorder  pI2P      akɔʁde     1
4809      accélérer  pi1S     aksɛlɛʁ     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     1
5140        achever  ai3S       aʃəva     1
5157        achever   inf       aʃəve     1
5159        achever  pi2P       aʃəve     1
5308        acheter  pi1S        aʃɛt     1
5315        acheter  fi3S     aʃɛtəʁa     1
5316        acheter  fi1S     aʃɛtəʁɛ     1
5332        achever  pi3S        aʃɛv     1
6272         acérer  ppFP       asɛʁe     1
6410        adapter  pi3S       adapt     1
...             ...   ...         ...   ...
430158     épaissir   inf      ɛpɛsiʁ     1
430210     épaissir  pi3S       ɛpɛsi     1
431791        épier  ppMP        ɛpje     1
432588     éprouver  ppFS      ɛpʁuve     1
432629      épuiser  ai3S      ɛpɥiza     1
433019   équilibrer  pi1S     ɛkilibʁ     1
433912      établir  ppMS      ɛtabli     2
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ    14
434070         être  ii3S         ɛtɛ    80
434300       étaler  ppFS       ɛtale     1
434821      étendre   inf      ɛtɑ̃dʁ     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     4
435251       étirer  pi1S        ɛtiʁ     1
435425      étonner    pP      ɛtɔnɑ̃     1
435444      étonner   inf       ɛtɔne     2
435471      étonner  ppMS       ɛtɔne     1
435472      étonner  ppFS       ɛtɔne     1
435484     étouffer  ii3S       ɛtufɛ     1
436053     étriquer  ppFS      ɛtʁike     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    24
436660     évanouir  ps3S     ɛvanuis     1
436833     éveiller  pi3P        ɛvɛj     1
437301       éviter   inf       ɛvite     2
437474         être  pi2P          ɛt    10
437476         être   inf         ɛtʁ    23
437498         ôter    pP        ɔtɑ̃     1
437508         ôter  pi3S          ot     1

[2009 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.5 s, total: 1min 39s
Wall time: 30.6 s

nbChunk 325
4200
1999

             lexeme  case       phono  tir1
40            avoir  pi3S           a    81
299         abattre   inf       abatʁ     1
1106        abonner  is3S       abɔna     1
1415        aboutir  ii3S     abutisɛ     1
1439        aboutir  ai3S       abuti     1
2335         abuser  pi3S        abyz     1
2506         abêtir   inf      abɛtiʁ     1
2887      accentuer  ii3S    aksɑ̃tyɛ     1
2934      accentuer  ppFS    aksɑ̃tye     1
2967       accepter  pi3S      aksɛpt     1
3176     acclimater   inf    aklimate     1
3314        accoler  ppFS       akɔle     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3404    accompagner  pi3P     akɔ̃paɲ     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3436    accompagner  ppMP    akɔ̃paɲe     1
3443      accomplir   inf    akɔ̃pliʁ     2
3530       accorder  pi3S       akɔʁd     1
3536       accorder   inf      akɔʁde     2
3537       accorder  fi3S    akɔʁdəʁa     1
3543       accorder  fi2S    akɔʁdəʁa     1
3862       accouder  ai3S       akuda     1
4237      accrocher  ii3S      akʁɔʃɛ     1
4293      accrocher  ppFP      akʁɔʃe     1
4479     accueillir  pi1S        akœj     1
4503     accueillir  ppFS       akəji     1
4684      accumuler  ppFS     akymyle     1
4694        accuser    pP      akyzɑ̃     1
4720        accuser   inf       akyze     1
...             ...   ...         ...   ...
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    68
434726     éteindre  ii3S       ɛtɛɲɛ     1
434740     éteindre  ai1S       ɛtɛɲi     1
434755     éteindre  fi3S     ɛtɛ̃dʁa     1
434785      étendre  ii3P      ɛtɑ̃dɛ     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     6
435438      étonner  pi3S        ɛtɔn     1
435471      étonner  ppMS       ɛtɔne     1
435484     étouffer  ii3S       ɛtufɛ     1
435500     étouffer  pi3S        ɛtuf     1
435526     étouffer  pi2P       ɛtufe     1
435754    étrangler  pc3S  ɛtʁɑ̃gləʁɛ     1
435837    étreindre  ppMS       ɛtʁɛ̃     1
436188      étudier    pP     ɛtydjɑ̃     1
436198      étudier  pi1S       ɛtydi     1
436316         être  ppMS         ɛte    13
436656     évanouir  ii3S    ɛvanuisɛ     1
436815     éveiller  ai3S       ɛvɛja     1
436816     éveiller  ai1S       ɛvɛjɛ     1
436820     éveiller  ii3S       ɛvɛjɛ     1
437301       éviter   inf       ɛvite     2
437302       éviter  fi3S     ɛvitəʁa     1
437367      évoluer   inf      ɛvɔlye     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437474         être  pi2P          ɛt     7
437476         être   inf         ɛtʁ    20

[1999 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.5 s, total: 1min 38s
Wall time: 31 s

nbChunk 326
4200
1976

             lexeme  case      phono  tir1
40            avoir  pi3S          a    90
164      abandonner  ppMS   abɑ̃dɔne     1
170      abandonner  ppMP   abɑ̃dɔne     1
299         abattre   inf      abatʁ     3
1457         aboyer  ii3P     abwajɛ     1
2100       absorber  ppMS    absɔʁbe     1
2339         abuser   inf      abyze     1
2581         abîmer   inf      abime     1
2977       accepter  pc3S  aksɛptəʁɛ     1
3322     accommoder  ii3S    akɔmɔdɛ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     2
3443      accomplir   inf   akɔ̃pliʁ     1
3519       accorder  ii3S     akɔʁdɛ     1
3542       accorder  pc3S   akɔʁdəʁɛ     1
4093       accourir  ppFP      akuʁy     1
4234      accrocher  ii3P     akʁɔʃɛ     1
4320      accroupir  ppMS     akʁupi     1
4503     accueillir  ppFS      akəji     1
4693        accuser  ii3S      akyzɛ     1
4694        accuser    pP     akyzɑ̃     1
4716        accuser  pi3S       akyz     2
4748        accuser  ppMS      akyze     1
4783        accéder   inf     aksɛde     1
4824      accélérer    pP  aksɛlɛʁɑ̃     1
5102        acheter  ai3S      aʃəta     1
5136        acheter  ppMS      aʃəte     2
5315        acheter  fi3S    aʃɛtəʁa     1
6067        activer  pi3S      aktiv     1
6109        activer  ppFS     aktive     1
...             ...   ...        ...   ...
428995   émotionner  ppMS   ɛmɔsjɔne     1
429334     émouvoir  ii3P      ɛmuvɛ     1
429367     émouvoir  ppFS        ɛmy     1
430558     épargner  pi3S      ɛpaʁɲ     1
430562     épargner   inf     ɛpaʁɲe     1
430573     épargner  fi1P  ɛpaʁɲəʁɔ̃     1
432156      épouser  pi3S       ɛpuz     1
432160      épouser   inf      ɛpuze     1
432164      épouser  pc1S    ɛpuzəʁɛ     1
432302      épouser  ppMS      ɛpuze     1
432739       épurer   inf      ɛpyʁe     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    14
434070         être  ii3S        ɛtɛ    68
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     4
435435      étonner  pi1S       ɛtɔn     1
435506     étouffer   inf      ɛtufe     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
435807    étreindre  ai3P    ɛtʁɛɲiʁ     1
436216      étudier  fi1P   ɛtydiʁɔ̃     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    28
436402      évacuer   inf     ɛvakye     1
436820     éveiller  ii3S      ɛvɛjɛ     1
436980     éventrer  ii3S    ɛvɑ̃tʁɛ     1
437299       éviter  pi3P       ɛvit     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    17
437512         ôter   inf        ɔte     1

[1976 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.6 s, total: 1min 36s
Wall time: 29.6 s

nbChunk 327
4200
1919

             lexeme  case      phono  tir1
40            avoir  pi3S          a    79
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
1684        abriter  pi3S      abʁit     1
2030       absoudre  ps3S     absɔlv     1
2100       absorber  ppMS    absɔʁbe     1
3406    accompagner   inf   akɔ̃paɲe     1
3438      accomplir  ppMS    akɔ̃pli     1
3467      accomplir  ii3S  akɔ̃plisɛ     1
3523       accorder  is3P    akɔʁdas     1
3530       accorder  pi3S      akɔʁd     1
3536       accorder   inf     akɔʁde     1
4259      accrocher   inf     akʁɔʃe     1
4292      accrocher  ppFS     akʁɔʃe     1
4482     accueillir  pi3S       akœj     1
4511     accueillir  ppMP      akəji     1
4736        accuser  pi2P      akyze     1
4754        accuser  ppMP      akyze     1
4864      accélérer  ppFS   aksɛlɛʁe     1
5119        acheter   inf      aʃəte     3
5125        acheter  pi2P      aʃəte     1
5136        acheter  ppMS      aʃəte     1
5140        achever  ai3S      aʃəva     1
5157        achever   inf      aʃəve     2
5308        acheter  pi1S       aʃɛt     1
7026        admirer  ppMP     admiʁe     1
7028       admettre  ppMS       admi     1
7309         adorer  pi1S       adɔʁ     1
7312         adorer  pi3S       adɔʁ     1
...             ...   ...        ...   ...
431981      éponger    pP    ɛpɔ̃ʒɑ̃     1
432160      épouser   inf      ɛpuze     1
432302      épouser  ppMS      ɛpuze     1
432491     éprendre   inf    ɛpʁɑ̃dʁ     1
432535     éprouver  ii1S     ɛpʁuvɛ     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
432665      épuiser  pc3S   ɛpɥizəʁɛ     1
434048         être  ii3P        ɛtɛ     6
434068         être  ii1S        ɛtɛ    10
434070         être  ii3S        ɛtɛ    77
434488         être    pP       ɛtɑ̃     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434773     éteindre  pi3S       ɛtɛ̃     2
434821      étendre   inf     ɛtɑ̃dʁ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     3
435782    étrangler  ppFS   ɛtʁɑ̃gle     1
435920     étriller   inf     ɛtʁije     1
436201      étudier  pi3S      ɛtydi     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    28
436550      évaluer  ppMP     ɛvalye     1
436835     éveiller   inf      ɛvɛje     1
437050     évertuer    pP   ɛvɛʁtyɑ̃     1
437284       éviter  ii3S      ɛvitɛ     1
437301       éviter   inf      ɛvite     1
437327       éviter  ai3P     ɛvitɛʁ     1
437474         être  pi2P         ɛt     8
437476         être   inf        ɛtʁ    20

[1919 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 22.3 s, total: 1min 35s
Wall time: 29.9 s

nbChunk 328
4200
1957

             lexeme  case      phono  tir1
40            avoir  pi3S          a    97
125      abandonner  pi1S    abɑ̃dɔn     1
164      abandonner  ppMS   abɑ̃dɔne     1
243         abattre  pi3S        aba     1
305         abattre  ppMS      abaty     1
1145        aborder  pi3P      abɔʁd     1
1601       abreuver  ppFS     abʁəve     1
1673        abriter  ii3S     abʁitɛ     2
1789        abroger  ppMP     abʁɔʒe     1
2581         abîmer   inf      abime     1
2971       accepter   inf    aksɛpte     2
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
3465      accomplir  ii1S  akɔ̃plisɛ     1
3516       accorder  ii3P     akɔʁdɛ     1
3530       accorder  pi3S      akɔʁd     1
3536       accorder   inf     akɔʁde     1
4235      accrocher  ii1S     akʁɔʃɛ     1
4255      accrocher  pi3S      akʁɔʃ     2
4294      accrocher  ppMP     akʁɔʃe     1
4502     accueillir  ppMS      akəji     1
5119        acheter   inf      aʃəte     5
5136        acheter  ppMS      aʃəte     1
5149        achever  ii3S      aʃəvɛ     1
5173        achever  ppFS      aʃəve     1
5311        acheter  pi3S       aʃɛt     1
5879      acquitter  ppMS      akite     1
6991        admirer  pi3S      admiʁ     1
7027       admettre  ppMP       admi     1
...             ...   ...        ...   ...
428650     émouvoir  pi3S        ɛmø     1
429349     émouvoir   inf    ɛmuvwaʁ     1
429713      énerver  pi2S      ɛnɛʁv     1
430042     énumérer   inf    ɛnymɛʁe     1
430482     épanouir  ppFS     ɛpanui     1
430837      épauler  ppMS      ɛpɔle     1
432153      épouser  pi1S       ɛpuz     1
432160      épouser   inf      ɛpuze     2
432537     éprouver  ii3S     ɛpʁuvɛ     1
432552     éprouver  pi3S      ɛpʁuv     1
432586     éprouver  ppMS     ɛpʁuve     1
432689      épuiser  ppMS     ɛpɥize     3
434048         être  ii3P        ɛtɛ     1
434068         être  ii1S        ɛtɛ    11
434070         être  ii3S        ɛtɛ    68
434488         être    pP       ɛtɑ̃     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434901     éternuer  ai3S    ɛtɛʁnya     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     4
435232       étirer  ai3S      ɛtiʁa     1
435438      étonner  pi3S       ɛtɔn     1
435746    étrangler  pi3P    ɛtʁɑ̃gl     1
436316         être  ppMS        ɛte    20
436457       évader   inf      ɛvade     1
437301       éviter   inf      ɛvite     3
437414      évoquer  ii1S      ɛvɔkɛ     1
437461      évoquer  ppMP      ɛvɔke     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    24

[1957 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.4 s, total: 1min 38s
Wall time: 30.4 s

nbChunk 329
4200
1966

             lexeme  case       phono  tir1
40            avoir  pi3S           a    75
125      abandonner  pi1S     abɑ̃dɔn     1
134      abandonner  fi1S  abɑ̃dɔnəʁɛ     1
164      abandonner  ppMS    abɑ̃dɔne     1
166      abandonner  ppFS    abɑ̃dɔne     2
250         abattre  pi1S         aba     1
287         abattre  ai3S       abati     1
416        abdiquer   inf      abdike     1
2124       absoudre  pi1S        absu     1
2967       accepter  pi3S      aksɛpt     1
3343     accommoder  pi3S      akɔmɔd     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
3443      accomplir   inf    akɔ̃pliʁ     1
3530       accorder  pi3S       akɔʁd     1
3555       accorder  pI2P      akɔʁde     1
3567       accorder  is3S      akɔʁda     1
4237      accrocher  ii3S      akʁɔʃɛ     1
4259      accrocher   inf      akʁɔʃe     1
4369      accroupir  pi3S      akʁupi     1
4716        accuser  pi3S        akyz     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     5
5157        achever   inf       aʃəve     1
5173        achever  ppFS       aʃəve     1
5336        achever  pi3P        aʃɛv     1
5758     acquiescer  pi3S       akjɛs     1
5905       acquérir   inf      akɛʁiʁ     1
6863       admettre  pi1S        admɛ     1
...             ...   ...         ...   ...
429365     émouvoir  ppMS         ɛmy     1
431160        épier  pi1S         ɛpi     1
432188   épousseter  ai3S     ɛpusəta     1
432532     éprouver  ai3S      ɛpʁuva     1
432533     éprouver  ai1S      ɛpʁuvɛ     1
432556     éprouver   inf      ɛpʁuve     1
433946      établir  ii3S    ɛtablisɛ     1
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ    12
434070         être  ii3S         ɛtɛ    70
434144       étaler  pi1S        ɛtal     1
434719       étayer  ppMS       ɛtɛje     1
434794      étendre  pi3P       ɛtɑ̃d     1
435054         être  ii2P        ɛtje     4
435172         être  ii1P       ɛtjɔ̃     1
435435      étonner  pi1S        ɛtɔn     1
435472      étonner  ppFS       ɛtɔne     1
435500     étouffer  pi3S        ɛtuf     1
435512     étouffer  pc3S     ɛtufəʁɛ     1
436205      étudier   inf      ɛtydje     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    15
437284       éviter  ii3S       ɛvitɛ     1
437299       éviter  pi3P        ɛvit     1
437301       éviter   inf       ɛvite     3
437431      évoquer   inf       ɛvɔke     1
437453      évoquer  pi1P      ɛvɔkɔ̃     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    14
437492         ôter  ai3S         ɔta     1

[1966 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.5 s, total: 1min 35s
Wall time: 29.8 s

nbChunk 330
4200
1954

             lexeme  case     phono  tir1
40            avoir  pi3S         a    77
132      abandonner   inf  abɑ̃dɔne     1
147      abandonner  pI2P  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     2
297         abattre  pc3S    abatʁɛ     1
299         abattre   inf     abatʁ     2
1673        abriter  ii3S    abʁitɛ     1
1946       absenter  pi3S    absɑ̃t     1
2031       absoudre  pi3P    absɔlv     1
2339         abuser   inf     abyze     1
2577         abîmer  pi3S      abim     1
2952       accepter    pP  aksɛptɑ̃     1
2971       accepter   inf   aksɛpte     1
3003       accepter  ppMS   aksɛpte     1
3385    accompagner  ii3S  akɔ̃paɲɛ     1
3406    accompagner   inf  akɔ̃paɲe     1
3519       accorder  ii3S    akɔʁdɛ     1
3571       accorder  ppMS    akɔʁde     2
3914       accouder  ppFS     akude     1
4626        acculer  ppMS     akyle     1
4748        accuser  ppMS     akyze     1
5119        acheter   inf     aʃəte     1
5125        acheter  pi2P     aʃəte     1
5149        achever  ii3S     aʃəvɛ     2
5311        acheter  pi3S      aʃɛt     1
5313        acheter  pi3P      aʃɛt     1
5332        achever  pi3S      aʃɛv     1
6412        adapter  pi3P     adapt     1
6530        adhérer  pi3P      adɛʁ     1
6863       admettre  pi1S      admɛ     1
...             ...   ...       ...   ...
433105      équiper  pi3S      ɛkip     1
433170      équiper  ppFS     ɛkipe     1
433914      établir  ppFS    ɛtabli     1
433936      établir  ppMP    ɛtabli     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    10
434070         être  ii3S       ɛtɛ    70
434072       étaler  ai3S     ɛtala     2
434302       étaler  ppMP     ɛtale     2
434488         être    pP      ɛtɑ̃     1
434760     éteindre  pc3S   ɛtɛ̃dʁɛ     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
434773     éteindre  pi3S      ɛtɛ̃     1
434821      étendre   inf    ɛtɑ̃dʁ     1
435059    étinceler  ii3P  ɛtɛ̃səlɛ     1
435172         être  ii1P     ɛtjɔ̃     3
435422      étonner  ii3S     ɛtɔnɛ     1
435435      étonner  pi1S      ɛtɔn     1
435438      étonner  pi3S      ɛtɔn     1
435472      étonner  ppFS     ɛtɔne     2
435500     étouffer  pi3S      ɛtuf     1
435506     étouffer   inf     ɛtufe     1
435780    étrangler  ppMS  ɛtʁɑ̃gle     1
436316         être  ppMS       ɛte    23
436520      évaluer   inf    ɛvalye     1
437285       éviter    pP    ɛvitɑ̃     1
437316       éviter  pI2P     ɛvite     1
437416      évoquer  ii3S     ɛvɔkɛ     1
437474         être  pi2P        ɛt    10
437476         être   inf       ɛtʁ    16

[1954 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.5 s, total: 1min 35s
Wall time: 29.4 s

nbChunk 331
4200
1909

              lexeme  case       phono  tir1
40             avoir  pi3S           a    74
128       abandonner  pi3S     abɑ̃dɔn     1
134       abandonner  fi1S  abɑ̃dɔnəʁɛ     1
148       abandonner  pi2P    abɑ̃dɔne     1
166       abandonner  ppFS    abɑ̃dɔne     2
299          abattre   inf       abatʁ     1
1133         aborder    pP     abɔʁdɑ̃     1
1147         aborder   inf      abɔʁde     1
1979        absenter  ppMS     absɑ̃te     1
2051        absorber  ii3S     absɔʁbɛ     1
2143        abstenir   inf    abstəniʁ     1
2244        abstenir  ai3S      abstɛ̃     1
2332          abuser  pi1S        abyz     1
2581          abîmer   inf       abime     1
2736        accabler   inf      akable     1
2948        accepter  ii1S     aksɛptɛ     1
2971        accepter   inf     aksɛpte     1
2994        accepter  ii1P   aksɛptjɔ̃     1
2997        accepter  pi1P    aksɛptɔ̃     1
3003        accepter  ppMS     aksɛpte     3
3007        accepter  ppFP     aksɛpte     1
3400     accompagner  pi3S     akɔ̃paɲ     1
3406     accompagner   inf    akɔ̃paɲe     1
3534        accorder  pi3P       akɔʁd     1
4291       accrocher  ppMS      akʁɔʃe     1
4369       accroupir  pi3S      akʁupi     1
4835       accélérer   inf    aksɛlɛʁe     1
5119         acheter   inf       aʃəte     4
5308         acheter  pi1S        aʃɛt     1
6009       actionner  pI2S      aksjɔn     1
...              ...   ...         ...   ...
432160       épouser   inf       ɛpuze     2
432267  époustoufler   inf   ɛpustufle     1
432303       épouser  ppFS       ɛpuze     1
433618        ériger  ppFS       ɛʁiʒe     1
433946       établir  ii3S    ɛtablisɛ     1
433987        étager  pi3S        ɛtaʒ     1
434048          être  ii3P         ɛtɛ     2
434068          être  ii1S         ɛtɛ    12
434069          être  ii2S         ɛtɛ     1
434070          être  ii3S         ɛtɛ    77
434134        étaler  ii3S       ɛtalɛ     1
434153        étaler   inf       ɛtale     1
434726      éteindre  ii3S       ɛtɛɲɛ     1
434747      éteindre  ai3S       ɛtɛɲi     1
434762      éteindre   inf      ɛtɛ̃dʁ     1
434779      éteindre  ppMP        ɛtɛ̃     1
434831       étendre  ppMS      ɛtɑ̃dy     1
435172          être  ii1P       ɛtjɔ̃     1
435422       étonner  ii3S       ɛtɔnɛ     1
435439       étonner  ps3S        ɛtɔn     1
436198       étudier  pi1S       ɛtydi     1
436316          être  ppMS         ɛte    21
436402       évacuer   inf      ɛvakye     2
436484        évader  ppMS       ɛvade     1
436627      évanouir  ppMS      ɛvanui     1
437273        éviter  ai3S       ɛvita     1
437285        éviter    pP      ɛvitɑ̃     1
437301        éviter   inf       ɛvite     1
437474          être  pi2P          ɛt    13
437476          être   inf         ɛtʁ    22

[1909 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22 s, total: 1min 37s
Wall time: 30 s

nbChunk 332
4200
1952

             lexeme  case     phono  tir1
40            avoir  pi3S         a    73
128      abandonner  pi3S   abɑ̃dɔn     1
132      abandonner   inf  abɑ̃dɔne     1
145      abandonner  pi2S   abɑ̃dɔn     1
255         abattre  ii3P     abatɛ     1
299         abattre   inf     abatʁ     1
862          aboyer  pi1S      abwa     1
1571       abreuver   inf    abʁəve     1
1861        abréger  pi3P     abʁɛʒ     1
2339         abuser   inf     abyze     1
2610         abîmer  ppMS     abime     1
2971       accepter   inf   aksɛpte     1
3003       accepter  ppMS   aksɛpte     1
3406    accompagner   inf  akɔ̃paɲe     1
3443      accomplir   inf  akɔ̃pliʁ     2
3471      accomplir  ps3S  akɔ̃plis     1
3827      accoucher   inf     akuʃe     1
4259      accrocher   inf    akʁɔʃe     1
4292      accrocher  ppFS    akʁɔʃe     1
4320      accroupir  ppMS    akʁupi     1
4720        accuser   inf     akyze     1
5119        acheter   inf     aʃəte     4
5136        acheter  ppMS     aʃəte     1
5137        acheter  ppFS     aʃəte     2
5157        achever   inf     aʃəve     1
5316        acheter  fi1S   aʃɛtəʁɛ     1
5327        acheter  pi2S      aʃɛt     1
5332        achever  pi3S      aʃɛv     1
6414        adapter   inf    adapte     1
6891       admettre   inf    admɛtʁ     1
...             ...   ...       ...   ...
432160      épouser   inf     ɛpuze     2
432481     éprendre  ii3S    ɛpʁənɛ     1
432659      épuiser   inf    ɛpɥize     1
432695      épuiser  ppMP    ɛpɥize     1
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ    14
434070         être  ii3S       ɛtɛ    70
434147       étaler  pi3S      ɛtal     1
434301       étaler  ppFP     ɛtale     1
434740     éteindre  ai1S     ɛtɛɲi     1
434762     éteindre   inf    ɛtɛ̃dʁ     1
434770     éteindre  pi2S      ɛtɛ̃     1
435054         être  ii2P      ɛtje     1
435089    étinceler  pi3P   ɛtɛ̃sɛl     1
435172         être  ii1P     ɛtjɔ̃     3
435254       étirer  pi3S      ɛtiʁ     1
435258       étirer  pi3P      ɛtiʁ     1
435375      étoiler  pi3S     ɛtwal     1
435417      étonner  ai3S     ɛtɔna     1
435518     étouffer  fi3P  ɛtufəʁɔ̃     1
435968      étriper  pi3S     ɛtʁip     1
436205      étudier   inf    ɛtydje     2
436316         être  ppMS       ɛte    21
436457       évader   inf     ɛvade     1
436532      évaluer  fi3P  ɛvalyʁɔ̃     1
437301       éviter   inf     ɛvite     1
437414      évoquer  ii1S     ɛvɔkɛ     1
437474         être  pi2P        ɛt    18
437476         être   inf       ɛtʁ    20
437508         ôter  pi3S        ot     1

[1952 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 21.1 s, total: 1min 34s
Wall time: 30.1 s

nbChunk 333
4200
1965

             lexeme  case     phono  tir1
40            avoir  pi3S         a    84
2339         abuser   inf     abyze     1
2769      accaparer  ai3S   akapaʁa     1
3343     accommoder  pi3S    akɔmɔd     1
3349     accommoder   inf   akɔmɔde     1
3397    accompagner  pi1S   akɔ̃paɲ     1
3443      accomplir   inf  akɔ̃pliʁ     2
3489      accomplir  ai3S   akɔ̃pli     1
3516       accorder  ii3P    akɔʁdɛ     1
3827      accoucher   inf     akuʃe     1
3913       accouder  ppMS     akude     1
4259      accrocher   inf    akʁɔʃe     1
4291      accrocher  ppMS    akʁɔʃe     1
4502     accueillir  ppMS     akəji     1
4547        acculer   inf     akyle     1
4688        accuser  ai3S     akyza     1
5119        acheter   inf     aʃəte     1
5136        acheter  ppMS     aʃəte     2
5137        acheter  ppFS     aʃəte     1
5149        achever  ii3S     aʃəvɛ     1
5308        acheter  pi1S      aʃɛt     1
5806       acquérir  ppMP       aki     1
5807       acquérir  ppMS       aki     1
5905       acquérir   inf    akɛʁiʁ     1
6967        admirer  ii1S    admiʁɛ     1
6996        admirer   inf    admiʁe     1
7222        adopter  ai3S    adɔpta     1
7297         adorer  ii3S     adɔʁɛ     1
7309         adorer  pi1S      adɔʁ     1
7312         adorer  pi3S      adɔʁ     2
...             ...   ...       ...   ...
432537     éprouver  ii3S    ɛpʁuvɛ     1
432689      épuiser  ppMS    ɛpɥize     2
433912      établir  ppMS    ɛtabli     2
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ    10
434070         être  ii3S       ɛtɛ    71
434144       étaler  pi1S      ɛtal     1
434147       étaler  pi3S      ɛtal     1
434151       étaler  pi3P      ɛtal     1
434726     éteindre  ii3S     ɛtɛɲɛ     1
434747     éteindre  ai3S     ɛtɛɲi     1
434821      étendre   inf    ɛtɑ̃dʁ     1
434831      étendre  ppMS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     1
435231    étiqueter  ppMP   ɛtikəte     1
435438      étonner  pi3S      ɛtɔn     1
435471      étonner  ppMS     ɛtɔne     2
435484     étouffer  ii3S     ɛtufɛ     2
435519     étouffer  pi2S      ɛtuf     1
435701     étourdir  pi2P  ɛtuʁdise     1
435726    étrangler  ai3S  ɛtʁɑ̃gla     1
435739    étrangler  pi1S   ɛtʁɑ̃gl     1
435748    étrangler   inf  ɛtʁɑ̃gle     1
436213      étudier  fi2P   ɛtydiʁe     1
436316         être  ppMS       ɛte    21
436453       évader  pi3S      ɛvad     1
436835     éveiller   inf     ɛvɛje     1
437411      évoquer  ai3S     ɛvɔka     1
437474         être  pi2P        ɛt    18
437476         être   inf       ɛtʁ    19

[1965 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 22.1 s, total: 1min 36s
Wall time: 29.8 s

nbChunk 334
4200
1947

             lexeme  case       phono  tir1
40            avoir  pi3S           a    80
71         abaisser  pi3P        abɛs     1
125      abandonner  pi1S     abɑ̃dɔn     1
128      abandonner  pi3S     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     1
264         abattre  pi3P        abat     1
299         abattre   inf       abatʁ     1
869          aboyer  pi3P        abwa     1
2102       absorber  ppFS     absɔʁbe     1
2371         abuser  ppMS       abyze     1
2764       accabler  ppFS      akable     1
2969       accepter  pi3P      aksɛpt     1
2971       accepter   inf     aksɛpte     2
2974       accepter  pc3P   aksɛptəʁɛ     1
2976       accepter  pc2S   aksɛptəʁɛ     1
3386    accompagner    pP   akɔ̃paɲɑ̃     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3408    accompagner  fi1S  akɔ̃paɲəʁɛ     1
3443      accomplir   inf    akɔ̃pliʁ     1
3545       accorder  pc2P   akɔʁdəʁje     1
3821      accoucher  pi3S        akuʃ     1
4259      accrocher   inf      akʁɔʃe     2
4502     accueillir  ppMS       akəji     1
4688        accuser  ai3S       akyza     1
5111        acheter  ii3S       aʃətɛ     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     2
5140        achever  ai3S       aʃəva     1
5149        achever  ii3S       aʃəvɛ     1
...             ...   ...         ...   ...
432535     éprouver  ii1S      ɛpʁuvɛ     1
432586     éprouver  ppMS      ɛpʁuve     1
432650      épuiser  pi1S       ɛpɥiz     1
433912      établir  ppMS      ɛtabli     1
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ    12
434070         être  ii3S         ɛtɛ    70
434134       étaler  ii3S       ɛtalɛ     1
434723     éteindre  ii3P       ɛtɛɲɛ     1
434923     éternuer   inf     ɛtɛʁnye     1
435054         être  ii2P        ɛtje     3
435172         être  ii1P       ɛtjɔ̃     2
435438      étonner  pi3S        ɛtɔn     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435475     étouffer  ai3S       ɛtufa     1
435540     étouffer  ppFS       ɛtufe     1
435654     étourdir  ppMS      ɛtuʁdi     1
435893     étrenner  ppMS      ɛtʁɛne     1
436316         être  ppMS         ɛte    28
436402      évacuer   inf      ɛvakye     1
436457       évader   inf       ɛvade     1
436627     évanouir  ppMS      ɛvanui     1
436833     éveiller  pi3P        ɛvɛj     1
437284       éviter  ii3S       ɛvitɛ     1
437360      évoluer  pi1S       ɛvɔly     1
437417      évoquer    pP      ɛvɔkɑ̃     1
437474         être  pi2P          ɛt    15
437476         être   inf         ɛtʁ    17
437508         ôter  pi3S          ot     1
437512         ôter   inf         ɔte     1

[1947 rows x 4 columns]

0
CPU times: user 1min 11s, sys: 21.4 s, total: 1min 33s
Wall time: 29.9 s

nbChunk 335
4200
1935

             lexeme  case        phono  tir1
40            avoir  pi3S            a    84
277         abattre  ai3P       abatiʁ     1
287         abattre  ai3S        abati     1
299         abattre   inf        abatʁ     1
1147        aborder   inf       abɔʁde     1
1673        abriter  ii3S       abʁitɛ     1
2123       absoudre  ppMS         absu     1
2339         abuser   inf        abyze     1
2343         abuser  pc1S      abyzəʁɛ     1
2710       accabler  ai3S       akabla     1
2967       accepter  pi3S       aksɛpt     1
3003       accepter  ppMS      aksɛpte     3
3091       acclamer  ai3S       aklama     1
3400    accompagner  pi3S      akɔ̃paɲ     1
3406    accompagner   inf     akɔ̃paɲe     1
3418    accompagner  fi3P  akɔ̃paɲəʁɔ̃     1
3434    accompagner  ppFS     akɔ̃paɲe     1
3455      accomplir  fi1P   akɔ̃pliʁɔ̃     1
3530       accorder  pi3S        akɔʁd     1
3571       accorder  ppMS       akɔʁde     1
4255      accrocher  pi3S        akʁɔʃ     2
4283      accrocher  ii1P     akʁɔʃjɔ̃     1
4292      accrocher  ppFS       akʁɔʃe     1
4502     accueillir  ppMS        akəji     1
4748        accuser  ppMS        akyze     1
4750        accuser  ppFS        akyze     1
4809      accélérer  pi1S      aksɛlɛʁ     1
5119        acheter   inf        aʃəte     3
5136        acheter  ppMS        aʃəte     2
5308        acheter  pi1S         aʃɛt     1
...             ...   ...          ...   ...
432586     éprouver  ppMS       ɛpʁuve     1
432689      épuiser  ppMS       ɛpɥize     2
433914      établir  ppFS       ɛtabli     1
433922      établir   inf      ɛtabliʁ     1
433987       étager  pi3S         ɛtaʒ     1
434048         être  ii3P          ɛtɛ     5
434068         être  ii1S          ɛtɛ     9
434070         être  ii3S          ɛtɛ    48
434072       étaler  ai3S        ɛtala     1
434147       étaler  pi3S         ɛtal     1
434782      étendre  pi3S         ɛtɑ̃     1
434831      étendre  ppMS       ɛtɑ̃dy     1
435054         être  ii2P         ɛtje     2
435059    étinceler  ii3P     ɛtɛ̃səlɛ     1
435062    étinceler  ii3S     ɛtɛ̃səlɛ     1
435172         être  ii1P        ɛtjɔ̃     2
435450      étonner  pc3S      ɛtɔnəʁɛ     1
435460      étonner  pi2P        ɛtɔne     1
436233      étudier  ppMS       ɛtydje     1
436237      étudier  ppFP       ɛtydje     1
436316         être  ppMS          ɛte    20
436821     éveiller    pP       ɛvɛjɑ̃     1
436835     éveiller   inf        ɛvɛje     1
437281       éviter  ii3P        ɛvitɛ     1
437285       éviter    pP       ɛvitɑ̃     1
437301       éviter   inf        ɛvite     3
437417      évoquer    pP       ɛvɔkɑ̃     1
437474         être  pi2P           ɛt    13
437476         être   inf          ɛtʁ    24
437512         ôter   inf          ɔte     1

[1935 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.9 s, total: 1min 36s
Wall time: 30.1 s

nbChunk 336
4200
1946

             lexeme  case     phono  tir1
40            avoir  pi3S         a    92
111      abandonner  ii1S  abɑ̃dɔnɛ     1
113      abandonner  ii3S  abɑ̃dɔnɛ     1
166      abandonner  ppFS  abɑ̃dɔne     1
869          aboyer  pi3P      abwa     1
890          abolir   inf    abɔliʁ     1
1393        aboutir   inf    abutiʁ     1
1684        abriter  pi3S     abʁit     1
1934       absenter  ii3S   absɑ̃tɛ     1
2070       absorber   inf   absɔʁbe     1
2964       accepter  pi1S    aksɛpt     1
2971       accepter   inf   aksɛpte     1
2989       accepter  pi2P   aksɛpte     1
3380    accompagner  ai3S  akɔ̃paɲa     1
3382    accompagner  ii3P  akɔ̃paɲɛ     1
3397    accompagner  pi1S   akɔ̃paɲ     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3438      accomplir  ppMS   akɔ̃pli     1
3440      accomplir  ppFS   akɔ̃pli     1
3508       accorder  ai3S    akɔʁda     1
3536       accorder   inf    akɔʁde     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4369      accroupir  pi3S    akʁupi     1
4509     accueillir   inf    akəjiʁ     1
4688        accuser  ai3S     akyza     1
4693        accuser  ii3S     akyzɛ     1
5119        acheter   inf     aʃəte     2
5125        acheter  pi2P     aʃəte     1
...             ...   ...       ...   ...
434068         être  ii1S       ɛtɛ    11
434070         être  ii3S       ɛtɛ    73
434072       étaler  ai3S     ɛtala     1
434134       étaler  ii3S     ɛtalɛ     1
434153       étaler   inf     ɛtale     1
434300       étaler  ppFS     ɛtale     1
434451     étancher   inf    ɛtɑ̃ʃe     1
434734     éteindre  pi2P     ɛtɛɲe     1
434789      étendre    pP   ɛtɑ̃dɑ̃     1
434833      étendre  ppFS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     1
435254       étirer  pi3S      ɛtiʁ     1
435417      étonner  ai3S     ɛtɔna     1
435425      étonner    pP    ɛtɔnɑ̃     2
435435      étonner  pi1S      ɛtɔn     1
435438      étonner  pi3S      ɛtɔn     1
435500     étouffer  pi3S      ɛtuf     1
435654     étourdir  ppMS    ɛtuʁdi     1
436205      étudier   inf    ɛtydje     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    16
436402      évacuer   inf    ɛvakye     1
436627     évanouir  ppMS    ɛvanui     1
436629     évanouir  ppFS    ɛvanui     1
436632     évanouir   inf   ɛvanuiʁ     1
436869     éveiller  ppFS     ɛvɛje     1
437301       éviter   inf     ɛvite     1
437474         être  pi2P        ɛt    14
437476         être   inf       ɛtʁ    16

[1946 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.9 s, total: 1min 36s
Wall time: 29.6 s

nbChunk 337
4200
1945

             lexeme  case      phono  tir1
40            avoir  pi3S          a    90
101        abaisser  ppMS      abɛse     1
114      abandonner    pP  abɑ̃dɔnɑ̃     1
164      abandonner  ppMS   abɑ̃dɔne     1
258         abattre  ii3S      abatɛ     1
299         abattre   inf      abatʁ     1
1600       abreuver  ppMS     abʁəve     1
2335         abuser  pi3S       abyz     1
2574         abîmer  pi1S       abim     1
2581         abîmer   inf      abime     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     1
3003       accepter  ppMS    aksɛpte     2
3005       accepter  ppFS    aksɛpte     1
3385    accompagner  ii3S   akɔ̃paɲɛ     2
3397    accompagner  pi1S    akɔ̃paɲ     1
4255      accrocher  pi3S      akʁɔʃ     2
4259      accrocher   inf     akʁɔʃe     1
4291      accrocher  ppMS     akʁɔʃe     2
4320      accroupir  ppMS     akʁupi     2
4475     accueillir    pP     akəjɑ̃     1
4502     accueillir  ppMS      akəji     1
4519     accueillir  ai3S      akəji     1
4690        accuser  ii3P      akyzɛ     1
4720        accuser   inf      akyze     1
5119        acheter   inf      aʃəte     2
5136        acheter  ppMS      aʃəte     1
5149        achever  ii3S      aʃəvɛ     1
5157        achever   inf      aʃəve     1
5764     acquiescer   inf     akjɛse     1
...             ...   ...        ...   ...
429694      énerver  pi3S      ɛnɛʁv     1
430158     épaissir   inf     ɛpɛsiʁ     1
431867     éplucher  pi3S      ɛplyʃ     1
432145      épouser    pP     ɛpuzɑ̃     1
432156      épouser  pi3S       ɛpuz     1
432659      épuiser   inf     ɛpɥize     1
433169      équiper  ppMS      ɛkipe     1
433924      établir  fi1S   ɛtabliʁɛ     1
433950      établir  ps3S    ɛtablis     1
434068         être  ii1S        ɛtɛ    16
434070         être  ii3S        ɛtɛ    64
434147       étaler  pi3S       ɛtal     1
434747     éteindre  ai3S      ɛtɛɲi     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434772     éteindre  ppMS       ɛtɛ̃     1
434827      étendre  pi1S       ɛtɑ̃     1
434833      étendre  ppFS     ɛtɑ̃dy     1
435085    étinceler  pi3S    ɛtɛ̃sɛl     1
435172         être  ii1P      ɛtjɔ̃     3
435435      étonner  pi1S       ɛtɔn     1
435444      étonner   inf      ɛtɔne     1
435506     étouffer   inf      ɛtufe     1
435792    étreindre  ii1S     ɛtʁɛɲɛ     1
436203      étudier  pi3P      ɛtydi     1
436316         être  ppMS        ɛte    20
436815     éveiller  ai3S      ɛvɛja     1
437301       éviter   inf      ɛvite     3
437317       éviter  pi2P      ɛvite     1
437474         être  pi2P         ɛt     5
437476         être   inf        ɛtʁ    22

[1945 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.5 s, total: 1min 35s
Wall time: 29.4 s

nbChunk 338
4200
1921

             lexeme  case     phono  tir1
40            avoir  pi3S         a    94
108      abandonner  ai3S  abɑ̃dɔna     1
109      abandonner  ai1S  abɑ̃dɔnɛ     1
128      abandonner  pi3S   abɑ̃dɔn     1
132      abandonner   inf  abɑ̃dɔne     2
168      abandonner  ppFP  abɑ̃dɔne     1
1946       absenter  pi3S    absɑ̃t     1
2143       abstenir   inf  abstəniʁ     1
2339         abuser   inf     abyze     1
2971       accepter   inf   aksɛpte     1
3003       accepter  ppMS   aksɛpte     1
3382    accompagner  ii3P  akɔ̃paɲɛ     1
3400    accompagner  pi3S   akɔ̃paɲ     2
3438      accomplir  ppMS   akɔ̃pli     2
4230      accrocher  ai3S    akʁɔʃa     1
4291      accrocher  ppMS    akʁɔʃe     1
4294      accrocher  ppMP    akʁɔʃe     1
4331      accroupir  ai3P   akʁupiʁ     1
4716        accuser  pi3S      akyz     1
4748        accuser  ppMS     akyze     1
5041       acharner  ppMS    aʃaʁne     1
5111        acheter  ii3S     aʃətɛ     1
5119        acheter   inf     aʃəte     3
5125        acheter  pi2P     aʃəte     1
5136        acheter  ppMS     aʃəte     2
5149        achever  ii3S     aʃəvɛ     1
5157        achever   inf     aʃəve     1
5316        acheter  fi1S   aʃɛtəʁɛ     1
5764     acquiescer   inf    akjɛse     1
6709      adjoindre  ai3S   adʒwaɲi     1
...             ...   ...       ...   ...
429349     émouvoir   inf   ɛmuvwaʁ     1
432160      épouser   inf     ɛpuze     3
432689      épuiser  ppMS    ɛpɥize     1
432695      épuiser  ppMP    ɛpɥize     1
433916      établir  ppFP    ɛtabli     1
434048         être  ii3P       ɛtɛ     1
434068         être  ii1S       ɛtɛ    12
434069         être  ii2S       ɛtɛ     1
434070         être  ii3S       ɛtɛ    79
434729     éteindre  ps3S      ɛtɛɲ     1
434821      étendre   inf    ɛtɑ̃dʁ     2
435054         être  ii2P      ɛtje     2
435435      étonner  pi1S      ɛtɔn     1
435444      étonner   inf     ɛtɔne     1
435471      étonner  ppMS     ɛtɔne     1
435472      étonner  ppFS     ɛtɔne     1
435780    étrangler  ppMS  ɛtʁɑ̃gle     1
436316         être  ppMS       ɛte    27
436402      évacuer   inf    ɛvakye     1
436436      évacuer  ppMP    ɛvakye     1
436453       évader  pi3S      ɛvad     1
436484       évader  ppMS     ɛvade     1
437284       éviter  ii3S     ɛvitɛ     1
437285       éviter    pP    ɛvitɑ̃     1
437295       éviter  pi3S      ɛvit     1
437301       éviter   inf     ɛvite     2
437307       éviter  pc3S   ɛvitəʁɛ     1
437416      évoquer  ii3S     ɛvɔkɛ     1
437474         être  pi2P        ɛt    11
437476         être   inf       ɛtʁ    21

[1921 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.9 s, total: 1min 37s
Wall time: 30 s

nbChunk 339
4200
1954

            lexeme  case       phono  tir1
40           avoir  pi3S           a    89
130     abandonner  pi3P     abɑ̃dɔn     1
307        abattre  ppFS       abaty     1
1121       aborder  ai3S      abɔʁda     1
2339        abuser   inf       abyze     1
2503        abêtir  ppMS       abɛti     1
2939      accepter  ai3S     aksɛpta     1
2946      accepter  ai1S     aksɛptɛ     1
2980      accepter  pc2P  aksɛptəʁje     1
2984      accepter  pi2S      aksɛpt     1
3009      accepter  ppMP     aksɛpte     1
4210    accoutumer  ppMS     akutyme     1
4237     accrocher  ii3S      akʁɔʃɛ     1
4255     accrocher  pi3S       akʁɔʃ     1
5041      acharner  ppMS      aʃaʁne     1
5119       acheter   inf       aʃəte     3
5125       acheter  pi2P       aʃəte     1
5136       acheter  ppMS       aʃəte     1
5310       acheter  pI2S        aʃɛt     1
5311       acheter  pi3S        aʃɛt     1
5316       acheter  fi1S     aʃɛtəʁɛ     1
5329       achever  pi1S        aʃɛv     1
5787    acquiescer  ai3S      akjɛsa     1
5806      acquérir  ppMP         aki     1
5879     acquitter  ppMS       akite     1
6067       activer  pi3S       aktiv     1
6870      admettre    pP     admɛtɑ̃     1
6883      admettre  pi1P     admɛtɔ̃     1
6996       admirer   inf      admiʁe     1
7012       admirer  pi2P      admiʁe     1
...            ...   ...         ...   ...
430338    épancher  pi3P       ɛpɑ̃ʃ     1
430506    épanouir  ii3P    ɛpanuisɛ     1
430555    épargner  pi1S       ɛpaʁɲ     1
431356      épiler  ppMS       ɛpile     1
432138     épouser  ai3S       ɛpuza     1
432160     épouser   inf       ɛpuze     1
432638     épuiser  ii3S      ɛpɥizɛ     1
432689     épuiser  ppMS      ɛpɥize     1
433170     équiper  ppFS       ɛkipe     1
434048        être  ii3P         ɛtɛ     3
434068        être  ii1S         ɛtɛ    10
434070        être  ii3S         ɛtɛ    76
434747    éteindre  ai3S       ɛtɛɲi     1
434831     étendre  ppMS      ɛtɑ̃dy     1
435054        être  ii2P        ɛtje     1
435258      étirer  pi3P        ɛtiʁ     1
435450     étonner  pc3S     ɛtɔnəʁɛ     1
435741   étrangler  pI2S     ɛtʁɑ̃gl     1
435748   étrangler   inf    ɛtʁɑ̃gle     1
435828   étreindre   inf     ɛtʁɛ̃dʁ     1
436201     étudier  pi3S       ɛtydi     1
436205     étudier   inf      ɛtydje     1
436237     étudier  ppFP      ɛtydje     1
436316        être  ppMS         ɛte    19
436520     évaluer   inf      ɛvalye     1
437285      éviter    pP      ɛvitɑ̃     1
437301      éviter   inf       ɛvite     1
437317      éviter  pi2P       ɛvite     1
437474        être  pi2P          ɛt    14
437476        être   inf         ɛtʁ    13

[1954 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 22.1 s, total: 1min 36s
Wall time: 30.4 s

nbChunk 340
4200
1952

             lexeme  case      phono  tir1
40            avoir  pi3S          a    84
114      abandonner    pP  abɑ̃dɔnɑ̃     1
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     2
1175        aborder  ppMS     abɔʁde     1
2581         abîmer   inf      abime     1
2952       accepter    pP   aksɛptɑ̃     1
2967       accepter  pi3S     aksɛpt     1
2972       accepter  fi3S  aksɛptəʁa     1
2975       accepter  pc1S  aksɛptəʁɛ     1
3003       accepter  ppMS    aksɛpte     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3463      accomplir  pi2S    akɔ̃pli     1
3536       accorder   inf     akɔʁde     1
3827      accoucher   inf      akuʃe     1
3968      accoupler  pi3P      akupl     1
4103       accourir  ai3S      akuʁy     1
4238      accrocher    pP    akʁɔʃɑ̃     1
4652      accumuler  pi3S     akymyl     1
4720        accuser   inf      akyze     1
4733        accuser  pi2S       akyz     1
4835      accélérer   inf   aksɛlɛʁe     1
5137        acheter  ppFS      aʃəte     1
5884       acquérir  ps3S      akjɛʁ     1
5905       acquérir   inf     akɛʁiʁ     1
6414        adapter   inf     adapte     1
6801        adjuger  ppMS     adʒyʒe     1
...             ...   ...        ...   ...
432533     éprouver  ai1S     ɛpʁuvɛ     1
432535     éprouver  ii1S     ɛpʁuvɛ     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
433431     érailler  ppFS      ɛʁaje     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ    19
434070         être  ii3S        ɛtɛ    65
434723     éteindre  ii3P      ɛtɛɲɛ     1
434730     éteindre  pi3P       ɛtɛɲ     1
434803      étendre  ai3P    ɛtɑ̃diʁ     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     5
435243       étirer  ii3S      ɛtiʁɛ     1
435417      étonner  ai3S      ɛtɔna     1
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435457      étonner  pi2S       ɛtɔn     1
435538     étouffer  ppMS      ɛtufe     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
436188      étudier    pP    ɛtydjɑ̃     1
436316         être  ppMS        ɛte    25
436398      évacuer  pi3S      ɛvaky     1
436520      évaluer   inf     ɛvalye     1
436649     évanouir  pi1S     ɛvanui     1
437301       éviter   inf      ɛvite     1
437365      évoluer  pi3P      ɛvɔly     1
437413      évoquer  ii3P      ɛvɔkɛ     1
437474         être  pi2P         ɛt    20
437476         être   inf        ɛtʁ    21

[1952 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 23 s, total: 1min 38s
Wall time: 30.8 s

nbChunk 341
4200
1993

            lexeme  case     phono  tir1
40           avoir  pi3S         a    72
128     abandonner  pi3S   abɑ̃dɔn     1
164     abandonner  ppMS  abɑ̃dɔne     2
166     abandonner  ppFS  abɑ̃dɔne     1
168     abandonner  ppFP  abɑ̃dɔne     1
170     abandonner  ppMP  abɑ̃dɔne     1
1406       aboutir  fi3P  abutiʁɔ̃     1
2143      abstenir   inf  abstəniʁ     1
2154      abstenir  ppMS   abstəny     1
2989      accepter  pi2P   aksɛpte     1
3536      accorder   inf    akɔʁde     2
4292     accrocher  ppFS    akʁɔʃe     1
4736       accuser  pi2P     akyze     1
4755       accéder  pi1S     aksɛd     1
5041      acharner  ppMS    aʃaʁne     1
5102       acheter  ai3S     aʃəta     1
5111       acheter  ii3S     aʃətɛ     1
5119       acheter   inf     aʃəte     1
5133       acheter  is3S     aʃəta     1
5136       acheter  ppMS     aʃəte     1
5139       acheter  ppMP     aʃəte     1
5311       acheter  pi3S      aʃɛt     1
5332       achever  pi3S      aʃɛv     1
5692     acoquiner   inf   akɔkine     1
6067       activer  pi3S     aktiv     1
6862      admettre  pi3S      admɛ     1
6991       admirer  pi3S     admiʁ     1
6996       admirer   inf    admiʁe     1
7294        adorer  ii3P     adɔʁɛ     1
7312        adorer  pi3S      adɔʁ     1
...            ...   ...       ...   ...
432691     épuiser  ppFS    ɛpɥize     1
432695     épuiser  ppMP    ɛpɥize     1
432739      épurer   inf     ɛpyʁe     1
434068        être  ii1S       ɛtɛ     8
434070        être  ii3S       ɛtɛ    68
434134      étaler  ii3S     ɛtalɛ     1
434772    éteindre  ppMS      ɛtɛ̃     1
434775    éteindre  ppFS     ɛtɛ̃t     1
434788     étendre  ii3S    ɛtɑ̃dɛ     1
434794     étendre  pi3P     ɛtɑ̃d     1
434821     étendre   inf    ɛtɑ̃dʁ     1
434939    éternuer  pi2P   ɛtɛʁnye     1
435172        être  ii1P     ɛtjɔ̃     2
435260      étirer   inf     ɛtiʁe     2
435417     étonner  ai3S     ɛtɔna     1
435444     étonner   inf     ɛtɔne     1
435473     étonner  ppFP     ɛtɔne     1
435656    étourdir  ppFS    ɛtuʁdi     1
435815   étreindre  ai3S    ɛtʁɛɲi     1
436316        être  ppMS       ɛte    30
436402     évacuer   inf    ɛvakye     2
436417     évacuer  pI2P    ɛvakye     1
436520     évaluer   inf    ɛvalye     1
436536     évaluer  pi2P    ɛvalye     1
436649    évanouir  pi1S    ɛvanui     1
436828    éveiller  pi1S      ɛvɛj     1
437301      éviter   inf     ɛvite     1
437327      éviter  ai3P    ɛvitɛʁ     1
437474        être  pi2P        ɛt     9
437476        être   inf       ɛtʁ    25

[1993 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.2 s, total: 1min 38s
Wall time: 30.3 s

nbChunk 342
4200
1969

             lexeme  case        phono  tir1
40            avoir  pi3S            a    66
45         abaisser  ai3S        abɛsa     1
113      abandonner  ii3S     abɑ̃dɔnɛ     1
130      abandonner  pi3P      abɑ̃dɔn     1
132      abandonner   inf     abɑ̃dɔne     1
170      abandonner  ppMP     abɑ̃dɔne     1
305         abattre  ppMS        abaty     1
982         abonder  pi3P        abɔ̃d     1
1307        abouler  pi3S         abul     1
1684        abriter  pi3S        abʁit     1
1761        abroger   inf       abʁɔʒe     1
2577         abîmer  pi3S         abim     1
2727       accabler  pi1S        akabl     1
2967       accepter  pi3S       aksɛpt     1
2971       accepter   inf      aksɛpte     1
2984       accepter  pi2S       aksɛpt     1
3379     accommoder  ppMP      akɔmɔde     1
3406    accompagner   inf     akɔ̃paɲe     1
3418    accompagner  fi3P  akɔ̃paɲəʁɔ̃     1
3435    accompagner  ppFP     akɔ̃paɲe     1
3859      accoucher  ppFS        akuʃe     1
4182     accoutumer   inf      akutyme     1
4257      accrocher  pi3P        akʁɔʃ     1
4290      accrocher  ai3P      akʁɔʃɛʁ     1
4373      accroître  pi3S        akʁwa     1
4482     accueillir  pi3S         akœj     1
4654      accumuler  pi3P       akymyl     1
4693        accuser  ii3S        akyzɛ     1
4812      accélérer  pi3S      aksɛlɛʁ     1
4835      accélérer   inf     aksɛlɛʁe     1
...             ...   ...          ...   ...
432302      épouser  ppMS        ɛpuze     1
432586     éprouver  ppMS       ɛpʁuve     2
433379     érailler  ai3S        ɛʁaja     1
433912      établir  ppMS       ɛtabli     1
433939      établir  pi1S       ɛtabli     1
434048         être  ii3P          ɛtɛ     6
434068         être  ii1S          ɛtɛ    12
434070         être  ii3S          ɛtɛ    81
434147       étaler  pi3S         ɛtal     1
434451     étancher   inf       ɛtɑ̃ʃe     1
434788      étendre  ii3S       ɛtɑ̃dɛ     1
435054         être  ii2P         ɛtje     1
435172         être  ii1P        ɛtjɔ̃     2
435417      étonner  ai3S        ɛtɔna     1
435419      étonner  ii3P        ɛtɔnɛ     1
435471      étonner  ppMS        ɛtɔne     1
435472      étonner  ppFS        ɛtɔne     1
435544     étouffer  ppMP        ɛtufe     1
436316         être  ppMS          ɛte    22
436629     évanouir  ppFS       ɛvanui     1
436835     éveiller   inf        ɛvɛje     1
436867     éveiller  ppMS        ɛvɛje     2
437285       éviter    pP       ɛvitɑ̃     1
437301       éviter   inf        ɛvite     2
437307       éviter  pc3S      ɛvitəʁɛ     1
437309       éviter  fi2P      ɛvitəʁe     1
437416      évoquer  ii3S        ɛvɔkɛ     1
437424      évoquer  pi1S         ɛvɔk     2
437474         être  pi2P           ɛt    17
437476         être   inf          ɛtʁ    23

[1969 rows x 4 columns]

0
CPU times: user 1min 8s, sys: 20.2 s, total: 1min 28s
Wall time: 29.6 s

nbChunk 343
4200
1898

            lexeme  case     phono  tir1
40           avoir  pi3S         a    90
125     abandonner  pi1S   abɑ̃dɔn     1
164     abandonner  ppMS  abɑ̃dɔne     1
166     abandonner  ppFS  abɑ̃dɔne     1
256        abattre  ii1S     abatɛ     1
299        abattre   inf     abatʁ     1
2355        abuser  pi2P     abyze     1
2936     accentuer  ppFP  aksɑ̃tye     1
2948      accepter  ii1S   aksɛptɛ     1
2967      accepter  pi3S    aksɛpt     1
2968      accepter  ps3S    aksɛpt     1
3003      accepter  ppMS   aksɛpte     1
3170    acclimater  pi3S   aklimat     1
3534      accorder  pi3P     akɔʁd     1
3702       accoter  pi3S      akɔt     1
3827     accoucher   inf     akuʃe     1
3862      accouder  ai3S     akuda     1
4090      accourir  pi3S      akuʁ     1
4293     accrocher  ppFP    akʁɔʃe     1
4519    accueillir  ai3S     akəji     1
5064     acheminer  pi3S    aʃəmin     1
5119       acheter   inf     aʃəte     1
5157       achever   inf     aʃəve     1
5171       achever  ppMS     aʃəve     2
5313       acheter  pi3P      aʃɛt     1
5316       acheter  fi1S   aʃɛtəʁɛ     1
5692     acoquiner   inf   akɔkine     1
5905      acquérir   inf    akɛʁiʁ     2
6089       activer  pi2P    aktive     1
6865      admettre  pi2S      admɛ     1
...            ...   ...       ...   ...
428864     émettre  ai3S       ɛmi     1
429367    émouvoir  ppFS       ɛmy     1
431613    épingler  ppFP   ɛpɛ̃gle     1
432156     épouser  pi3S      ɛpuz     1
432160     épouser   inf     ɛpuze     1
432556    éprouver   inf    ɛpʁuve     2
433590      ériger   inf     ɛʁiʒe     1
433912     établir  ppMS    ɛtabli     1
433922     établir   inf   ɛtabliʁ     2
433991      étager  ii3P     ɛtaʒɛ     1
434048        être  ii3P       ɛtɛ     2
434068        être  ii1S       ɛtɛ    19
434070        être  ii3S       ɛtɛ    68
434782     étendre  pi3S      ɛtɑ̃     2
434788     étendre  ii3S    ɛtɑ̃dɛ     1
435054        être  ii2P      ɛtje     3
435172        être  ii1P     ɛtjɔ̃     2
435417     étonner  ai3S     ɛtɔna     1
435486    étouffer    pP    ɛtufɑ̃     1
435500    étouffer  pi3S      ɛtuf     1
436316        être  ppMS       ɛte    23
436520     évaluer   inf    ɛvalye     1
436632    évanouir   inf   ɛvanuiʁ     1
437285      éviter    pP    ɛvitɑ̃     1
437301      éviter   inf     ɛvite     2
437414     évoquer  ii1S     ɛvɔkɛ     1
437458     évoquer  ppMS     ɛvɔke     1
437474        être  pi2P        ɛt    15
437476        être   inf       ɛtʁ    24
437512        ôter   inf       ɔte     2

[1898 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.8 s, total: 1min 36s
Wall time: 30.2 s

nbChunk 344
4200
1940

             lexeme  case        phono  tir1
40            avoir  pi3S            a   101
73         abaisser   inf        abɛse     1
109      abandonner  ai1S     abɑ̃dɔnɛ     1
130      abandonner  pi3P      abɑ̃dɔn     1
143      abandonner  fi1P  abɑ̃dɔnəʁɔ̃     1
889          abolir  ppFP        abɔli     1
1143        aborder  pi3S        abɔʁd     1
1716        abriter  ppMS       abʁite     1
1722        abriter  ppMP       abʁite     1
1796        abrutir  ppMS       abʁyti     1
2581         abîmer   inf        abime     1
2755       accabler  ii1P     akabljɔ̃     1
2984       accepter  pi2S       aksɛpt     1
3003       accepter  ppMS      aksɛpte     1
3400    accompagner  pi3S      akɔ̃paɲ     1
3419    accompagner  pi2S      akɔ̃paɲ     1
3433    accompagner  ppMS     akɔ̃paɲe     1
3443      accomplir   inf     akɔ̃pliʁ     1
3492      accomplir  is3S      akɔ̃pli     1
3536       accorder   inf       akɔʁde     1
3573       accorder  ppFS       akɔʁde     1
3878       accouder  pi3S         akud     1
4090       accourir  pi3S         akuʁ     1
4096       accourir  ai1S        akuʁy     1
4293      accrocher  ppFP       akʁɔʃe     1
5008       acharner  pi3S        aʃaʁn     1
5119        acheter   inf        aʃəte     5
5136        acheter  ppMS        aʃəte     2
5145        achever  ai1S        aʃəvɛ     1
6044      actionner  ppFS      aksjɔne     1
...             ...   ...          ...   ...
432160      épouser   inf        ɛpuze     3
432303      épouser  ppFS        ɛpuze     1
432549     éprouver  pi1S        ɛpʁuv     1
432586     éprouver  ppMS       ɛpʁuve     1
432689      épuiser  ppMS       ɛpɥize     1
433354      érafler  ppMS       ɛʁafle     1
433914      établir  ppFS       ɛtabli     1
433922      établir   inf      ɛtabliʁ     2
434048         être  ii3P          ɛtɛ     3
434068         être  ii1S          ɛtɛ    16
434070         être  ii3S          ɛtɛ    55
434299       étaler  ppMS        ɛtale     1
434772     éteindre  ppMS         ɛtɛ̃     2
434773     éteindre  pi3S         ɛtɛ̃     1
435054         être  ii2P         ɛtje     2
435172         être  ii1P        ɛtjɔ̃     1
435450      étonner  pc3S      ɛtɔnəʁɛ     1
435481     étouffer  ii3P        ɛtufɛ     1
435499     étouffer  pI2S         ɛtuf     1
435782    étrangler  ppFS     ɛtʁɑ̃gle     1
436233      étudier  ppMS       ɛtydje     3
436316         être  ppMS          ɛte    22
436395      évacuer  pi1S        ɛvaky     1
436520      évaluer   inf       ɛvalye     1
437273       éviter  ai3S        ɛvita     1
437301       éviter   inf        ɛvite     1
437367      évoluer   inf       ɛvɔlye     1
437458      évoquer  ppMS        ɛvɔke     1
437474         être  pi2P           ɛt    21
437476         être   inf          ɛtʁ    13

[1940 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 22 s, total: 1min 35s
Wall time: 29.9 s

nbChunk 345
4200
1941

            lexeme  case      phono  tir1
40           avoir  pi3S          a    81
73        abaisser   inf      abɛse     1
1688       abriter   inf     abʁite     1
2371        abuser  ppMS      abyze     1
2939      accepter  ai3S    aksɛpta     1
2952      accepter    pP   aksɛptɑ̃     1
2971      accepter   inf    aksɛpte     1
2989      accepter  pi2P    aksɛpte     1
3003      accepter  ppMS    aksɛpte     1
3542      accorder  pc3S   akɔʁdəʁɛ     1
4234     accrocher  ii3P     akʁɔʃɛ     1
4237     accrocher  ii3S     akʁɔʃɛ     2
4255     accrocher  pi3S      akʁɔʃ     1
4280     accrocher  pi2P     akʁɔʃe     1
4291     accrocher  ppMS     akʁɔʃe     1
4292     accrocher  ppFS     akʁɔʃe     1
4293     accrocher  ppFP     akʁɔʃe     1
4479    accueillir  pi1S       akœj     1
4720       accuser   inf      akyze     1
5119       acheter   inf      aʃəte     2
5136       acheter  ppMS      aʃəte     2
5140       achever  ai3S      aʃəva     1
5171       achever  ppMS      aʃəve     1
5311       acheter  pi3S       aʃɛt     1
6969       admirer  ii3S     admiʁɛ     1
7023       admirer  ppMS     admiʁe     1
7309        adorer  pi1S       adɔʁ     1
7312        adorer  pi3S       adɔʁ     2
7320        adorer  pc1S    adɔʁəʁɛ     1
7338        adorer  pi1P     adɔʁɔ̃     1
...            ...   ...        ...   ...
432041   épouiller  ii3S      ɛpujɛ     1
432153     épouser  pi1S       ɛpuz     1
432160     épouser   inf      ɛpuze     1
432552    éprouver  pi3S      ɛpʁuv     1
432586    éprouver  ppMS     ɛpʁuve     1
433916     établir  ppFP     ɛtabli     1
434048        être  ii3P        ɛtɛ     1
434068        être  ii1S        ɛtɛ    13
434070        être  ii3S        ɛtɛ    74
434734    éteindre  pi2P      ɛtɛɲe     1
434747    éteindre  ai3S      ɛtɛɲi     1
434811     étendre  ai3S     ɛtɑ̃di     1
434821     étendre   inf     ɛtɑ̃dʁ     1
434831     étendre  ppMS     ɛtɑ̃dy     1
435172        être  ii1P      ɛtjɔ̃     2
435544    étouffer  ppMP      ɛtufe     1
435677    étourdir  pi1S     ɛtuʁdi     1
436181     étudier  ai3S     ɛtydja     1
436316        être  ppMS        ɛte    24
436436     évacuer  ppMP     ɛvakye     1
436547     évaluer  ppMS     ɛvalye     1
436627    évanouir  ppMS     ɛvanui     1
436657    évanouir    pP  ɛvanuisɑ̃     1
436828    éveiller  pi1S       ɛvɛj     1
437301      éviter   inf      ɛvite     2
437363     évoluer  pi3S      ɛvɔly     1
437417     évoquer    pP     ɛvɔkɑ̃     1
437431     évoquer   inf      ɛvɔke     1
437474        être  pi2P         ɛt    12
437476        être   inf        ɛtʁ    18

[1941 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22 s, total: 1min 37s
Wall time: 30.3 s

nbChunk 346
4200
1957

             lexeme  case      phono  tir1
40            avoir  pi3S          a    80
114      abandonner    pP  abɑ̃dɔnɑ̃     1
125      abandonner  pi1S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     2
164      abandonner  ppMS   abɑ̃dɔne     2
287         abattre  ai3S      abati     1
1147        aborder   inf     abɔʁde     1
1393        aboutir   inf     abutiʁ     1
1394        aboutir  fi3S    abutiʁa     1
1716        abriter  ppMS     abʁite     1
2971       accepter   inf    aksɛpte     2
2994       accepter  ii1P  aksɛptjɔ̃     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3386    accompagner    pP  akɔ̃paɲɑ̃     1
3530       accorder  pi3S      akɔʁd     1
3556       accorder  pi2P     akɔʁde     1
4255      accrocher  pi3S      akʁɔʃ     1
4292      accrocher  ppFS     akʁɔʃe     1
4347      accroupir    pP  akʁupisɑ̃     1
4509     accueillir   inf     akəjiʁ     1
4635      accumuler  ii1S    akymylɛ     1
4693        accuser  ii3S      akyzɛ     1
5119        acheter   inf      aʃəte     1
5137        acheter  ppFS      aʃəte     1
5171        achever  ppMS      aʃəve     1
5173        achever  ppFS      aʃəve     1
5318        acheter  pc1S    aʃɛtəʁɛ     1
6991        admirer  pi3S      admiʁ     1
7046       admettre  ai3S       admi     2
7309         adorer  pi1S       adɔʁ     1
...             ...   ...        ...   ...
427624     éloigner  ii3S     ɛlwaɲɛ     1
427635     éloigner  pi3S      ɛlwaɲ     1
427734     élucider  ai3S    ɛlysida     1
430156     épaissir  ppFS      ɛpɛsi     1
430562     épargner   inf     ɛpaʁɲe     1
432156      épouser  pi3S       ɛpuz     1
432160      épouser   inf      ɛpuze     3
433169      équiper  ppMS      ɛkipe     1
434048         être  ii3P        ɛtɛ     6
434068         être  ii1S        ɛtɛ    19
434070         être  ii3S        ɛtɛ    71
434773     éteindre  pi3S       ɛtɛ̃     1
434775     éteindre  ppFS      ɛtɛ̃t     1
434811      étendre  ai3S     ɛtɑ̃di     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     5
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435471      étonner  ppMS      ɛtɔne     1
435484     étouffer  ii3S      ɛtufɛ     1
435731    étrangler  ii3S   ɛtʁɑ̃glɛ     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    23
436395      évacuer  pi1S      ɛvaky     1
436457       évader   inf      ɛvade     1
436831     éveiller  pi3S       ɛvɛj     1
437301       éviter   inf      ɛvite     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    23
437492         ôter  ai3S        ɔta     1

[1957 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.8 s, total: 1min 39s
Wall time: 30.8 s

nbChunk 347
4200
1996

             lexeme  case      phono  tir1
40            avoir  pi3S          a    87
177      abasourdir  ppMS   abazuʁdi     1
261         abattre  ps3S       abat     1
1169        aborder  pi1P    abɔʁdɔ̃     1
1670        abriter  ii3P     abʁitɛ     1
1884        abréger   inf     abʁɛʒe     1
2581         abîmer   inf      abime     1
2715       accabler  ii3S     akablɛ     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     2
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3422    accompagner  pi2P   akɔ̃paɲe     1
3434    accompagner  ppFS   akɔ̃paɲe     1
3530       accorder  pi3S      akɔʁd     1
3571       accorder  ppMS     akɔʁde     1
4291      accrocher  ppMS     akʁɔʃe     1
5119        acheter   inf      aʃəte     1
5136        acheter  ppMS      aʃəte     1
5171        achever  ppMS      aʃəve     1
5311        acheter  pi3S       aʃɛt     1
5329        achever  pi1S       aʃɛv     1
5349        achever  fi3P   aʃɛvəʁɔ̃     1
6863       admettre  pi1S       admɛ     1
6926    administrer  pi3P  administʁ     1
6991        admirer  pi3S      admiʁ     1
7309         adorer  pi1S       adɔʁ     1
7312         adorer  pi3S       adɔʁ     1
7485        adoucir    pP   adusisɑ̃     1
7518       adresser  ai3S     adʁɛsa     1
7524       adresser    pP    adʁɛsɑ̃     1
...             ...   ...        ...   ...
432691      épuiser  ppFS     ɛpɥize     1
433912      établir  ppMS     ɛtabli     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    12
434070         être  ii3S        ɛtɛ    78
434300       étaler  ppFS      ɛtale     1
434747     éteindre  ai3S      ɛtɛɲi     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434768     éteindre  pi1S       ɛtɛ̃     1
434772     éteindre  ppMS       ɛtɛ̃     1
434773     éteindre  pi3S       ɛtɛ̃     1
434811      étendre  ai3S     ɛtɑ̃di     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434829      étendre  pi2S       ɛtɑ̃     1
434917     éternuer  pi3S     ɛtɛʁny     1
435054         être  ii2P       ɛtje     2
435089    étinceler  pi3P    ɛtɛ̃sɛl     1
435172         être  ii1P      ɛtjɔ̃     2
435438      étonner  pi3S       ɛtɔn     1
435544     étouffer  ppMP      ɛtufe     1
435654     étourdir  ppMS     ɛtuʁdi     1
435761    étrangler  pi2S    ɛtʁɑ̃gl     1
435780    étrangler  ppMS   ɛtʁɑ̃gle     1
436316         être  ppMS        ɛte    25
436656     évanouir  ii3S   ɛvanuisɛ     1
436867     éveiller  ppMS      ɛvɛje     1
437301       éviter   inf      ɛvite     3
437416      évoquer  ii3S      ɛvɔkɛ     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    28

[1996 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.1 s, total: 1min 37s
Wall time: 30.2 s

nbChunk 348
4200
1968

           lexeme  case       phono  tir1
40          avoir  pi3S           a    96
64       abaisser  pi1S        abɛs     1
243       abattre  pi3S         aba     1
305       abattre  ppMS       abaty     1
1121      aborder  ai3S      abɔʁda     1
1153      aborder  pc3S    abɔʁdəʁɛ     1
1818      abrutir  pi1S      abʁyti     1
2157     abstenir  ppMP     abstəny     1
2337       abuser  pi3P        abyz     1
2888    accentuer    pP   aksɑ̃tyɑ̃     2
2950     accepter  ii3S     aksɛptɛ     1
2971     accepter   inf     aksɛpte     1
3003     accepter  ppMS     aksɛpte     1
3913     accouder  ppMS       akude     1
4279    accrocher  pI2P      akʁɔʃe     1
4322    accroupir  ppFP      akʁupi     1
4403    accroître  ai3S        akʁy     1
4835    accélérer   inf    aksɛlɛʁe     1
5107      acheter  ai1S       aʃətɛ     1
5119      acheter   inf       aʃəte     5
5136      acheter  ppMS       aʃəte     5
5149      achever  ii3S       aʃəvɛ     1
5311      acheter  pi3S        aʃɛt     1
5327      acheter  pi2S        aʃɛt     1
5807     acquérir  ppMS         aki     1
6028    actionner  fi3P  aksjɔnəʁɔ̃     1
6891     admettre   inf      admɛtʁ     1
6996      admirer   inf      admiʁe     1
7309       adorer  pi1S        adɔʁ     1
7312       adorer  pi3S        adɔʁ     1
...           ...   ...         ...   ...
432537   éprouver  ii3S      ɛpʁuvɛ     1
432549   éprouver  pi1S       ɛpʁuv     1
433922    établir   inf     ɛtabliʁ     1
434048       être  ii3P         ɛtɛ     3
434068       être  ii1S         ɛtɛ    14
434070       être  ii3S         ɛtɛ    88
434135     étaler    pP      ɛtalɑ̃     1
434260  étalonner   inf     ɛtalɔne     1
434768   éteindre  pi1S        ɛtɛ̃     1
434770   éteindre  pi2S        ɛtɛ̃     1
434811    étendre  ai3S      ɛtɑ̃di     1
435054       être  ii2P        ɛtje     2
435172       être  ii1P       ɛtjɔ̃     5
435377    étoiler  pi3P       ɛtwal     1
435438    étonner  pi3S        ɛtɔn     1
435445    étonner  fi3S     ɛtɔnəʁa     1
435448    étonner  pc1S     ɛtɔnəʁɛ     1
435795  étreindre    pP     ɛtʁɛɲɑ̃     1
436227    étudier  pi1P     ɛtydjɔ̃     1
436233    étudier  ppMS      ɛtydje     1
436316       être  ppMS         ɛte    25
436405    évacuer  pc3P     ɛvakyʁɛ     1
436436    évacuer  ppMP      ɛvakye     1
436450     évader  pi1S        ɛvad     1
436831   éveiller  pi3S        ɛvɛj     1
436836   éveiller  fi3S     ɛvɛjəʁa     1
437301     éviter   inf       ɛvite     3
437474       être  pi2P          ɛt    20
437476       être   inf         ɛtʁ    20
437539       ôter  ppMS         ɔte     1

[1968 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.3 s, total: 1min 38s
Wall time: 30.3 s

nbChunk 349
4200
1978

             lexeme  case       phono  tir1
40            avoir  pi3S           a    99
52         abaisser    pP      abɛsɑ̃     1
164      abandonner  ppMS    abɑ̃dɔne     3
166      abandonner  ppFS    abɑ̃dɔne     1
177      abasourdir  ppMS    abazuʁdi     1
299         abattre   inf       abatʁ     1
661         abjurer   inf      abʒyʁe     1
977         abonder  pi1S       abɔ̃d     1
1393        aboutir   inf      abutiʁ     1
1796        abrutir  ppMS      abʁyti     1
2070       absorber   inf     absɔʁbe     1
2226       abstenir  pi1S     abstjɛ̃     1
2371         abuser  ppMS       abyze     1
2967       accepter  pi3S      aksɛpt     1
2968       accepter  ps3S      aksɛpt     1
2971       accepter   inf     aksɛpte     1
3361     accommoder  fi3P  akɔmɔdəʁɔ̃     1
3386    accompagner    pP   akɔ̃paɲɑ̃     1
3406    accompagner   inf    akɔ̃paɲe     2
3419    accompagner  pi2S     akɔ̃paɲ     1
3433    accompagner  ppMS    akɔ̃paɲe     3
3530       accorder  pi3S       akɔʁd     1
4473     accueillir  ii3S       akəjɛ     1
4509     accueillir   inf      akəjiʁ     1
4748        accuser  ppMS       akyze     2
4783        accéder   inf      aksɛde     1
4809      accélérer  pi1S     aksɛlɛʁ     1
4835      accélérer   inf    aksɛlɛʁe     1
5030       acharner  pi2P      aʃaʁne     1
5041       acharner  ppMS      aʃaʁne     1
...             ...   ...         ...   ...
432302      épouser  ppMS       ɛpuze     1
432535     éprouver  ii1S      ɛpʁuvɛ     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    13
434069         être  ii2S         ɛtɛ     1
434070         être  ii3S         ɛtɛ    63
434144       étaler  pi1S        ɛtal     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434775     éteindre  ppFS       ɛtɛ̃t     1
434788      étendre  ii3S      ɛtɑ̃dɛ     2
434811      étendre  ai3S      ɛtɑ̃di     2
434827      étendre  pi1S        ɛtɑ̃     1
435172         être  ii1P       ɛtjɔ̃     1
435240       étirer  ii3P       ɛtiʁɛ     1
435260       étirer   inf       ɛtiʁe     1
435442      étonner  pi3P        ɛtɔn     1
435711     étourdir  pi3S      ɛtuʁdi     1
436316         être  ppMS         ɛte    16
436500      évaluer    pP     ɛvalyɑ̃     1
436664     évanouir  pi3P     ɛvanuis     1
436821     éveiller    pP      ɛvɛjɑ̃     1
436835     éveiller   inf       ɛvɛje     1
437244    éviscérer   inf     ɛvisɛʁe     1
437285       éviter    pP      ɛvitɑ̃     2
437301       éviter   inf       ɛvite     3
437317       éviter  pi2P       ɛvite     1
437328       éviter  ppMS       ɛvite     1
437474         être  pi2P          ɛt    11
437476         être   inf         ɛtʁ    17
437508         ôter  pi3S          ot     1

[1978 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 20.7 s, total: 1min 32s
Wall time: 29.4 s

nbChunk 350
4200
1908

             lexeme  case      phono  tir1
40            avoir  pi3S          a    86
125      abandonner  pi1S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
170      abandonner  ppMP   abɑ̃dɔne     1
305         abattre  ppMS      abaty     1
1169        aborder  pi1P    abɔʁdɔ̃     1
1979       absenter  ppMS    absɑ̃te     1
2102       absorber  ppFS    absɔʁbe     1
2581         abîmer   inf      abime     1
2950       accepter  ii3S    aksɛptɛ     1
3406    accompagner   inf   akɔ̃paɲe     1
3449      accomplir  pc3S  akɔ̃pliʁɛ     1
3571       accorder  ppMS     akɔʁde     1
3827      accoucher   inf      akuʃe     1
4255      accrocher  pi3S      akʁɔʃ     1
4291      accrocher  ppMS     akʁɔʃe     1
4373      accroître  pi3S      akʁwa     1
4470     accueillir  ii3P      akəjɛ     1
4509     accueillir   inf     akəjiʁ     1
4720        accuser   inf      akyze     1
4783        accéder   inf     aksɛde     1
5111        acheter  ii3S      aʃətɛ     1
5119        acheter   inf      aʃəte     1
5149        achever  ii3S      aʃəvɛ     1
5308        acheter  pi1S       aʃɛt     1
5311        acheter  pi3S       aʃɛt     1
6050        activer  ii3P     aktivɛ     1
6967        admirer  ii1S     admiʁɛ     1
6969        admirer  ii3S     admiʁɛ     1
7018        admirer  pi1P    admiʁɔ̃     1
...             ...   ...        ...   ...
428248       émaner  pi3S       ɛman     1
428397      émerger  ii3P     ɛmɛʁʒɛ     2
430021     énumérer  pi2S     ɛnymɛʁ     1
430579     épargner  pi2P     ɛpaʁɲe     1
431167        épier   inf       ɛpje     1
432153      épouser  pi1S       ɛpuz     1
432302      épouser  ppMS      ɛpuze     1
432383   épouvanter  pi1S    ɛpuvɑ̃t     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
432689      épuiser  ppMS     ɛpɥize     1
433238   équivaloir  pi3S      ɛkivo     1
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ    22
434070         être  ii3S        ɛtɛ    63
434762     éteindre   inf     ɛtɛ̃dʁ     1
435172         être  ii1P      ɛtjɔ̃     2
435244       étirer    pP     ɛtiʁɑ̃     1
435418      étonner  ai1S      ɛtɔnɛ     1
435506     étouffer   inf      ɛtufe     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
436316         être  ppMS        ɛte    18
436815     éveiller  ai3S      ɛvɛja     1
437273       éviter  ai3S      ɛvita     1
437285       éviter    pP     ɛvitɑ̃     2
437301       éviter   inf      ɛvite     2
437416      évoquer  ii3S      ɛvɔkɛ     1
437417      évoquer    pP     ɛvɔkɑ̃     1
437461      évoquer  ppMP      ɛvɔke     1
437474         être  pi2P         ɛt    13
437476         être   inf        ɛtʁ    15

[1908 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.9 s, total: 1min 37s
Wall time: 30 s

nbChunk 351
4200
1939

             lexeme  case     phono  tir1
40            avoir  pi3S         a    83
101        abaisser  ppMS     abɛse     1
132      abandonner   inf  abɑ̃dɔne     1
148      abandonner  pi2P  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     1
297         abattre  pc3S    abatʁɛ     1
305         abattre  ppMS     abaty     1
1175        aborder  ppMS    abɔʁde     1
1455         aboyer  ai3S    abwaja     1
1935       absenter    pP  absɑ̃tɑ̃     1
2324         abuser  ii3S     abyzɛ     1
2339         abuser   inf     abyze     1
2581         abîmer   inf     abime     1
2964       accepter  pi1S    aksɛpt     1
2971       accepter   inf   aksɛpte     1
3003       accepter  ppMS   aksɛpte     1
3144       acclamer  ppMS    aklame     1
3404    accompagner  pi3P   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3508       accorder  ai3S    akɔʁda     1
3530       accorder  pi3S     akɔʁd     2
3556       accorder  pi2P    akɔʁde     1
3915       accouder  ppFP     akude     1
4758        accéder  pi3S     aksɛd     1
5111        acheter  ii3S     aʃətɛ     1
5119        acheter   inf     aʃəte     1
5140        achever  ai3S     aʃəva     1
5157        achever   inf     aʃəve     2
5171        achever  ppMS     aʃəve     1
...             ...   ...       ...   ...
428609      émettre  pi3S       ɛmɛ     1
429337     émouvoir  ii3S     ɛmuvɛ     1
429365     émouvoir  ppMS       ɛmy     1
430042     énumérer   inf   ɛnymɛʁe     1
430482     épanouir  ppFS    ɛpanui     1
430517     épanouir  pi3P   ɛpanuis     1
430682       épater  pi3S      ɛpat     1
431871     éplucher   inf    ɛplyʃe     1
432160      épouser   inf     ɛpuze     2
434048         être  ii3P       ɛtɛ     5
434068         être  ii1S       ɛtɛ    19
434069         être  ii2S       ɛtɛ     1
434070         être  ii3S       ɛtɛ    84
434782      étendre  pi3S      ɛtɑ̃     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     2
435417      étonner  ai3S     ɛtɔna     1
435418      étonner  ai1S     ɛtɔnɛ     1
435471      étonner  ppMS     ɛtɔne     1
435526     étouffer  pi2P     ɛtufe     1
436316         être  ppMS       ɛte    23
436632     évanouir   inf   ɛvanuiʁ     2
436649     évanouir  pi1S    ɛvanui     1
436820     éveiller  ii3S     ɛvɛjɛ     1
437292       éviter  pi1S      ɛvit     1
437301       éviter   inf     ɛvite     2
437416      évoquer  ii3S     ɛvɔkɛ     1
437431      évoquer   inf     ɛvɔke     1
437474         être  pi2P        ɛt    11
437476         être   inf       ɛtʁ    22

[1939 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.7 s, total: 1min 36s
Wall time: 30.4 s

nbChunk 352
4200
1950

             lexeme  case      phono  tir1
40            avoir  pi3S          a    91
164      abandonner  ppMS   abɑ̃dɔne     1
255         abattre  ii3P      abatɛ     1
2066       absorber  pi3S     absɔʁb     1
2102       absorber  ppFS    absɔʁbe     1
2948       accepter  ii1S    aksɛptɛ     1
2950       accepter  ii3S    aksɛptɛ     1
2967       accepter  pi3S     aksɛpt     1
2968       accepter  ps3S     aksɛpt     1
2971       accepter   inf    aksɛpte     1
2979       accepter  fi2P  aksɛptəʁe     1
3003       accepter  ppMS    aksɛpte     1
3399    accompagner  pI2S    akɔ̃paɲ     1
3432    accompagner  ai3P  akɔ̃paɲɛʁ     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3489      accomplir  ai3S    akɔ̃pli     1
3534       accorder  pi3P      akɔʁd     1
3571       accorder  ppMS     akɔʁde     1
3916       accouder  ppMP      akude     1
4210     accoutumer  ppMS    akutyme     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4272      accrocher  pi2S      akʁɔʃ     1
4290      accrocher  ai3P    akʁɔʃɛʁ     1
4509     accueillir   inf     akəjiʁ     1
4694        accuser    pP     akyzɑ̃     1
4713        accuser  pi1S       akyz     1
4736        accuser  pi2P      akyze     1
4809      accélérer  pi1S    aksɛlɛʁ     1
4835      accélérer   inf   aksɛlɛʁe     1
5008       acharner  pi3S      aʃaʁn     1
...             ...   ...        ...   ...
432569     éprouver  pi2S      ɛpʁuv     1
433944      établir  ii1S   ɛtablisɛ     1
433968      établir  ai3S     ɛtabli     1
433969      établir  pi3S     ɛtabli     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    16
434070         être  ii3S        ɛtɛ    72
434762     éteindre   inf     ɛtɛ̃dʁ     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
434833      étendre  ppFS     ɛtɑ̃dy     1
434866    éterniser  pi3P    ɛtɛʁniz     1
435054         être  ii2P       ɛtje     1
435074    étinceler   inf   ɛtɛ̃səle     1
435172         être  ii1P      ɛtjɔ̃     3
435435      étonner  pi1S       ɛtɔn     3
435506     étouffer   inf      ɛtufe     1
436186      étudier  ii3S     ɛtydjɛ     1
436316         être  ppMS        ɛte    24
436457       évader   inf      ɛvade     1
436821     éveiller    pP     ɛvɛjɑ̃     1
437273       éviter  ai3S      ɛvita     1
437299       éviter  pi3P       ɛvit     1
437301       éviter   inf      ɛvite     2
437307       éviter  pc3S    ɛvitəʁɛ     1
437367      évoluer   inf     ɛvɔlye     1
437414      évoquer  ii1S      ɛvɔkɛ     1
437474         être  pi2P         ɛt    16
437476         être   inf        ɛtʁ    19
437512         ôter   inf        ɔte     1

[1950 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 22.2 s, total: 1min 36s
Wall time: 30.1 s

nbChunk 353
4200
1938

             lexeme  case       phono  tir1
40            avoir  pi3S           a    83
113      abandonner  ii3S    abɑ̃dɔnɛ     1
128      abandonner  pi3S     abɑ̃dɔn     2
132      abandonner   inf    abɑ̃dɔne     1
133      abandonner  fi3S  abɑ̃dɔnəʁa     1
261         abattre  ps3S        abat     1
299         abattre   inf       abatʁ     1
906          abolir  pi1S       abɔli     1
1455         aboyer  ai3S      abwaja     1
1601       abreuver  ppFS      abʁəve     1
2070       absorber   inf     absɔʁbe     2
2283      abstraire  ppFP     abstʁɛt     1
2979       accepter  fi2P   aksɛptəʁe     1
2997       accepter  pi1P    aksɛptɔ̃     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
3862       accouder  ai3S       akuda     1
4230      accrocher  ai3S      akʁɔʃa     1
4255      accrocher  pi3S       akʁɔʃ     1
4291      accrocher  ppMS      akʁɔʃe     1
4685      accumuler  ppFP     akymyle     1
4686      accumuler  ppMP     akymyle     1
5102        acheter  ai3S       aʃəta     1
5119        acheter   inf       aʃəte     3
5136        acheter  ppMS       aʃəte     1
5137        acheter  ppFS       aʃəte     1
5332        achever  pi3S        aʃɛv     1
6553        adhérer   inf       adɛʁe     1
6891       admettre   inf      admɛtʁ     1
7314         adorer  pi3P        adɔʁ     1
...             ...   ...         ...   ...
432162      épouser  fi1S     ɛpuzəʁɛ     1
432552     éprouver  pi3S       ɛpʁuv     1
432556     éprouver   inf      ɛpʁuve     3
432569     éprouver  pi2S       ɛpʁuv     1
433431     érailler  ppFS       ɛʁaje     1
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ    11
434070         être  ii3S         ɛtɛ    78
434151       étaler  pi3P        ɛtal     1
434153       étaler   inf       ɛtale     1
434302       étaler  ppMP       ɛtale     1
434747     éteindre  ai3S       ɛtɛɲi     1
434831      étendre  ppMS      ɛtɑ̃dy     1
434836      étendre  ppFP      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     2
435422      étonner  ii3S       ɛtɔnɛ     1
435484     étouffer  ii3S       ɛtufɛ     1
435780    étrangler  ppMS    ɛtʁɑ̃gle     1
436316         être  ppMS         ɛte    25
436656     évanouir  ii3S    ɛvanuisɛ     1
436820     éveiller  ii3S       ɛvɛjɛ     1
436873     éveiller  ppMP       ɛvɛje     1
437301       éviter   inf       ɛvite     2
437312       éviter  fi1P    ɛvitəʁɔ̃     1
437328       éviter  ppMS       ɛvite     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437458      évoquer  ppMS       ɛvɔke     1
437474         être  pi2P          ɛt    14
437476         être   inf         ɛtʁ    18

[1938 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.8 s, total: 1min 35s
Wall time: 29.7 s

nbChunk 354
4200
1934

             lexeme  case     phono  tir1
40            avoir  pi3S         a    78
50         abaisser  ii3S     abɛsɛ     1
264         abattre  pi3P      abat     1
299         abattre   inf     abatʁ     1
865          aboyer  pi3S      abwa     1
1133        aborder    pP   abɔʁdɑ̃     1
1710        abriter  pi1P   abʁitɔ̃     1
2577         abîmer  pi3S      abim     1
2938      accentuer  ppMP  aksɑ̃tye     1
2964       accepter  pi1S    aksɛpt     1
2967       accepter  pi3S    aksɛpt     1
2997       accepter  pi1P  aksɛptɔ̃     1
3003       accepter  ppMS   aksɛpte     2
3383    accompagner  ii1S  akɔ̃paɲɛ     1
3406    accompagner   inf  akɔ̃paɲe     1
3436    accompagner  ppMP  akɔ̃paɲe     1
3508       accorder  ai3S    akɔʁda     1
3519       accorder  ii3S    akɔʁdɛ     1
3573       accorder  ppFS    akɔʁde     1
3629       accoster  ai3S    akɔsta     1
4005      accoupler  ppMP    akuple     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4255      accrocher  pi3S     akʁɔʃ     1
4259      accrocher   inf    akʁɔʃe     1
4290      accrocher  ai3P   akʁɔʃɛʁ     1
4291      accrocher  ppMS    akʁɔʃe     2
4320      accroupir  ppMS    akʁupi     2
4509     accueillir   inf    akəjiʁ     2
4626        acculer  ppMS     akyle     1
4683      accumuler  ppMS   akymyle     1
...             ...   ...       ...   ...
429700      énerver   inf    ɛnɛʁve     1
430485     épanouir   inf   ɛpanuiʁ     1
432420   épouvanter  ppMS  ɛpuvɑ̃te     1
432534     éprouver  ii3P    ɛpʁuvɛ     1
432586     éprouver  ppMS    ɛpʁuve     1
433914      établir  ppFS    ɛtabli     2
433922      établir   inf   ɛtabliʁ     2
433930      établir  ai3P   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ    10
434070         être  ii3S       ɛtɛ    80
434788      étendre  ii3S    ɛtɑ̃dɛ     1
434804      étendre  ai1S    ɛtɑ̃di     1
434833      étendre  ppFS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     1
435260       étirer   inf     ɛtiʁe     1
435422      étonner  ii3S     ɛtɔnɛ     1
435438      étonner  pi3S      ɛtɔn     1
435506     étouffer   inf     ɛtufe     1
435969      étriper  ps3S     ɛtʁip     1
436316         être  ppMS       ɛte    16
436627     évanouir  ppMS    ɛvanui     1
436835     éveiller   inf     ɛvɛje     1
436867     éveiller  ppMS     ɛvɛje     1
437301       éviter   inf     ɛvite     2
437328       éviter  ppMS     ɛvite     1
437416      évoquer  ii3S     ɛvɔkɛ     1
437474         être  pi2P        ɛt    14
437476         être   inf       ɛtʁ    20

[1934 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.7 s, total: 1min 34s
Wall time: 29.6 s

nbChunk 355
4200
1920

             lexeme  case      phono  tir1
40            avoir  pi3S          a    89
67         abaisser  pi3S       abɛs     1
108      abandonner  ai3S   abɑ̃dɔna     1
113      abandonner  ii3S   abɑ̃dɔnɛ     1
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     3
147      abandonner  pI2P   abɑ̃dɔne     1
287         abattre  ai3S      abati     2
292         abattre  fi3S     abatʁa     1
305         abattre  ppMS      abaty     1
1673        abriter  ii3S     abʁitɛ     1
2371         abuser  ppMS      abyze     1
2967       accepter  pi3S     aksɛpt     2
2971       accepter   inf    aksɛpte     2
2972       accepter  fi3S  aksɛptəʁa     1
3382    accompagner  ii3P   akɔ̃paɲɛ     1
3400    accompagner  pi3S    akɔ̃paɲ     2
3406    accompagner   inf   akɔ̃paɲe     2
3433    accompagner  ppMS   akɔ̃paɲe     2
3436    accompagner  ppMP   akɔ̃paɲe     1
3438      accomplir  ppMS    akɔ̃pli     1
3571       accorder  ppMS     akɔʁde     1
4259      accrocher   inf     akʁɔʃe     1
4462     accréditer  ppFS   akʁɛdite     1
4482     accueillir  pi3S       akœj     1
4509     accueillir   inf     akəjiʁ     1
4638      accumuler    pP   akymylɑ̃     1
4715        accuser  pI2S       akyz     1
4736        accuser  pi2P      akyze     1
4750        accuser  ppFS      akyze     1
...             ...   ...        ...   ...
429694      énerver  pi3S      ɛnɛʁv     1
429700      énerver   inf     ɛnɛʁve     1
430590     épargner  ppMS     ɛpaʁɲe     1
430799      épauler  pI2S       ɛpol     1
431271       épiler   inf      ɛpile     1
432156      épouser  pi3S       ɛpuz     1
432586     éprouver  ppMS     ɛpʁuve     2
433105      équiper  pi3S       ɛkip     1
433169      équiper  ppMS      ɛkipe     1
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ     7
434070         être  ii3S        ɛtɛ    88
434131       étaler  ii3P      ɛtalɛ     1
434775     éteindre  ppFS      ɛtɛ̃t     1
434917     éternuer  pi3S     ɛtɛʁny     1
435059    étinceler  ii3P   ɛtɛ̃səlɛ     1
435172         être  ii1P      ɛtjɔ̃     3
435240       étirer  ii3P      ɛtiʁɛ     1
436002      étriper  ppMP     ɛtʁipe     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    28
436443       évader    pP     ɛvadɑ̃     1
436831     éveiller  pi3S       ɛvɛj     1
436835     éveiller   inf      ɛvɛje     1
436902      éventer  pi3P      ɛvɑ̃t     1
437301       éviter   inf      ɛvite     1
437304       éviter  pc3P    ɛvitəʁɛ     1
437413      évoquer  ii3P      ɛvɔkɛ     1
437474         être  pi2P         ɛt    11
437476         être   inf        ɛtʁ    26

[1920 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.7 s, total: 1min 35s
Wall time: 29.9 s

nbChunk 356
4200
1940

             lexeme  case     phono  tir1
40            avoir  pi3S         a    88
45         abaisser  ai3S     abɛsa     1
90         abaisser  pi2P     abɛse     1
166      abandonner  ppFS  abɑ̃dɔne     1
1147        aborder   inf    abɔʁde     1
1884        abréger   inf    abʁɛʒe     1
2070       absorber   inf   absɔʁbe     1
2581         abîmer   inf     abime     1
2717       accabler    pP   akablɑ̃     1
2819      accaparer  ppFS   akapaʁe     1
2971       accepter   inf   aksɛpte     1
2989       accepter  pi2P   aksɛpte     1
3003       accepter  ppMS   aksɛpte     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3460      accomplir  pi1S   akɔ̃pli     1
3530       accorder  pi3S     akɔʁd     1
3571       accorder  ppMS    akɔʁde     1
4255      accrocher  pi3S     akʁɔʃ     1
4291      accrocher  ppMS    akʁɔʃe     1
4292      accrocher  ppFS    akʁɔʃe     1
4294      accrocher  ppMP    akʁɔʃe     1
4320      accroupir  ppMS    akʁupi     1
4321      accroupir  ppFS    akʁupi     1
4521     accueillir  pi1P    akəjɔ̃     2
4654      accumuler  pi3P    akymyl     1
5008       acharner  pi3S     aʃaʁn     1
5042       acharner  ppFS    aʃaʁne     1
5119        acheter   inf     aʃəte     2
5136        acheter  ppMS     aʃəte     1
5327        acheter  pi2S      aʃɛt     1
...             ...   ...       ...   ...
433928      établir  pc3S  ɛtabliʁɛ     1
433994       étager  ii3S     ɛtaʒɛ     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ    18
434070         être  ii3S       ɛtɛ    70
434072       étaler  ai3S     ɛtala     1
434134       étaler  ii3S     ɛtalɛ     1
434302       étaler  ppMP     ɛtale     1
434726     éteindre  ii3S     ɛtɛɲɛ     1
434730     éteindre  pi3P      ɛtɛɲ     1
434775     éteindre  ppFS     ɛtɛ̃t     1
434868    éterniser   inf  ɛtɛʁnize     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     1
435731    étrangler  ii3S  ɛtʁɑ̃glɛ     1
435742    étrangler  pi3S   ɛtʁɑ̃gl     1
435746    étrangler  pi3P   ɛtʁɑ̃gl     1
435968      étriper  pi3S     ɛtʁip     1
436201      étudier  pi3S     ɛtydi     1
436316         être  ppMS       ɛte    29
436667     évanouir  ps2S   ɛvanuis     1
436835     éveiller   inf     ɛvɛje     2
437176      évincer   inf    ɛvɛ̃se     1
437325       éviter  is3S     ɛvita     1
437367      évoluer   inf    ɛvɔlye     1
437416      évoquer  ii3S     ɛvɔkɛ     1
437427      évoquer  pi3S      ɛvɔk     2
437429      évoquer  pi3P      ɛvɔk     1
437474         être  pi2P        ɛt    15
437476         être   inf       ɛtʁ    14

[1940 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.5 s, total: 1min 35s
Wall time: 29.3 s

nbChunk 357
4200
1915

             lexeme  case       phono  tir1
40            avoir  pi3S           a    77
129      abandonner  ps3S     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     3
1307        abouler  pi3S        abul     1
1722        abriter  ppMP      abʁite     1
1946       absenter  pi3S      absɑ̃t     1
2900      accentuer  pi3S     aksɑ̃ty     1
2939       accepter  ai3S     aksɛpta     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     2
3400    accompagner  pi3S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     2
3414    accompagner  fi2P  akɔ̃paɲəʁe     1
3519       accorder  ii3S      akɔʁdɛ     1
4233      accrocher  ai1S      akʁɔʃɛ     1
4339      accroupir  pi1S      akʁupi     1
4713        accuser  pi1S        akyz     1
5119        acheter   inf       aʃəte     2
5124        acheter  pI2P       aʃəte     1
5136        acheter  ppMS       aʃəte     1
5171        achever  ppMS       aʃəve     1
6536        adhérer  ii3P       adɛʁɛ     1
6864       admettre  pI2S        admɛ     1
6869       admettre  ii3S      admɛtɛ     1
6969        admirer  ii3S      admiʁɛ     1
6988        admirer  pi1S       admiʁ     1
7312         adorer  pi3S        adɔʁ     1
7313         adorer  ps3S        adɔʁ     1
7524       adresser    pP     adʁɛsɑ̃     1
7803        advenir  ps3S      advjɛn     1
...             ...   ...         ...   ...
428418      émerger   inf      ɛmɛʁʒe     1
429367     émouvoir  ppFS         ɛmy     1
429498     émouvoir  ppMP         ɛmy     1
429716      énerver  pi2P      ɛnɛʁve     1
430593     épargner  ppMP      ɛpaʁɲe     1
432144      épouser  ii3S       ɛpuzɛ     1
432554     éprouver  pi3P       ɛpʁuv     1
433914      établir  ppFS      ɛtabli     1
433916      établir  ppFP      ɛtabli     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ    12
434070         être  ii3S         ɛtɛ    82
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434793      étendre  ps3S       ɛtɑ̃d     1
434831      étendre  ppMS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     3
435172         être  ii1P       ɛtjɔ̃     3
435258       étirer  pi3P        ɛtiʁ     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436198      étudier  pi1S       ɛtydi     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    17
436836     éveiller  fi3S     ɛvɛjəʁa     1
436871     éveiller  ppFP       ɛvɛje     1
437301       éviter   inf       ɛvite     2
437416      évoquer  ii3S       ɛvɔkɛ     1
437427      évoquer  pi3S        ɛvɔk     1
437474         être  pi2P          ɛt    16
437476         être   inf         ɛtʁ    17

[1915 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 22 s, total: 1min 36s
Wall time: 30.1 s

nbChunk 358
4200
1962

             lexeme  case      phono  tir1
40            avoir  pi3S          a    88
114      abandonner    pP  abɑ̃dɔnɑ̃     1
125      abandonner  pi1S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     2
1110        abonner  ppMS      abɔne     1
1668        abriter  ai3S     abʁita     1
2049       absorber  ii1S    absɔʁbɛ     1
2100       absorber  ppMS    absɔʁbe     1
2766       accabler  ppMP     akable     1
2964       accepter  pi1S     aksɛpt     1
2967       accepter  pi3S     aksɛpt     2
2971       accepter   inf    aksɛpte     1
2984       accepter  pi2S     aksɛpt     1
3003       accepter  ppMS    aksɛpte     2
3005       accepter  ppFS    aksɛpte     1
3380    accompagner  ai3S   akɔ̃paɲa     1
3438      accomplir  ppMS    akɔ̃pli     1
3490      accomplir  pi3S    akɔ̃pli     1
3653       accoster  pi3P      akɔst     1
3827      accoucher   inf      akuʃe     1
3970      accoupler   inf     akuple     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4255      accrocher  pi3S      akʁɔʃ     1
4280      accrocher  pi2P     akʁɔʃe     1
4482     accueillir  pi3S       akœj     1
4509     accueillir   inf     akəjiʁ     2
4694        accuser    pP     akyzɑ̃     1
4818      accélérer  ai3S   aksɛlɛʁa     1
5014       acharner   inf     aʃaʁne     1
5136        acheter  ppMS      aʃəte     3
...             ...   ...        ...   ...
432160      épouser   inf      ɛpuze     2
432303      épouser  ppFS      ɛpuze     1
432532     éprouver  ai3S     ɛpʁuva     1
432689      épuiser  ppMS     ɛpɥize     1
433922      établir   inf    ɛtabliʁ     3
433991       étager  ii3P      ɛtaʒɛ     1
434068         être  ii1S        ɛtɛ    15
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    76
434072       étaler  ai3S      ɛtala     1
434488         être    pP       ɛtɑ̃     2
434773     éteindre  pi3S       ɛtɛ̃     1
434779     éteindre  ppMP       ɛtɛ̃     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434827      étendre  pi1S       ɛtɑ̃     1
435172         être  ii1P      ɛtjɔ̃     2
435422      étonner  ii3S      ɛtɔnɛ     1
435438      étonner  pi3S       ɛtɔn     1
435474      étonner  ppMP      ɛtɔne     1
436201      étudier  pi3S      ɛtydi     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    19
436402      évacuer   inf     ɛvakye     1
436835     éveiller   inf      ɛvɛje     1
437301       éviter   inf      ɛvite     3
437411      évoquer  ai3S      ɛvɔka     1
437458      évoquer  ppMS      ɛvɔke     1
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    22
437528         ôter  pi2P        ɔte     1

[1962 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.8 s, total: 1min 36s
Wall time: 30.2 s

nbChunk 359
4200
1960

             lexeme  case      phono  tir1
40            avoir  pi3S          a    68
46         abaisser  ai1S      abɛsɛ     1
50         abaisser  ii3S      abɛsɛ     1
132      abandonner   inf   abɑ̃dɔne     2
164      abandonner  ppMS   abɑ̃dɔne     1
168      abandonner  ppFP   abɑ̃dɔne     1
243         abattre  pi3S        aba     1
890          abolir   inf     abɔliʁ     1
1827        abrutir    pP  abʁytisɑ̃     1
2928      accentuer  is3S   aksɑ̃tya     1
2964       accepter  pi1S     aksɛpt     1
2967       accepter  pi3S     aksɛpt     1
2971       accepter   inf    aksɛpte     2
2972       accepter  fi3S  aksɛptəʁa     1
2989       accepter  pi2P    aksɛpte     1
3003       accepter  ppMS    aksɛpte     1
3113       acclamer  pi3S      aklam     1
3397    accompagner  pi1S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3422    accompagner  pi2P   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3490      accomplir  pi3S    akɔ̃pli     1
3571       accorder  ppMS     akɔʁde     2
3573       accorder  ppFS     akɔʁde     1
3827      accoucher   inf      akuʃe     1
4320      accroupir  ppMS     akʁupi     1
4783        accéder   inf     aksɛde     1
4995       acharner  ii1S     aʃaʁnɛ     1
5119        acheter   inf      aʃəte     1
5136        acheter  ppMS      aʃəte     2
...             ...   ...        ...   ...
427668     éloigner  ppMS     ɛlwaɲe     1
429331  émoustiller  ppFS   ɛmustije     1
429365     émouvoir  ppMS        ɛmy     1
432160      épouser   inf      ɛpuze     1
432535     éprouver  ii1S     ɛpʁuvɛ     2
432556     éprouver   inf     ɛpʁuve     2
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     8
434068         être  ii1S        ɛtɛ    14
434070         être  ii3S        ɛtɛ    68
434134       étaler  ii3S      ɛtalɛ     1
434720       étayer  ppFS      ɛtɛje     1
434756     éteindre  fi1S    ɛtɛ̃dʁɛ     1
434773     éteindre  pi3S       ɛtɛ̃     1
434833      étendre  ppFS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     1
435435      étonner  pi1S       ɛtɔn     1
435444      étonner   inf      ɛtɔne     1
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435542     étouffer  ppFP      ɛtufe     1
436205      étudier   inf     ɛtydje     2
436316         être  ppMS        ɛte    24
436499      évaluer  ii3S     ɛvalyɛ     1
436629     évanouir  ppFS     ɛvanui     1
437301       éviter   inf      ɛvite     2
437417      évoquer    pP     ɛvɔkɑ̃     1
437474         être  pi2P         ɛt    13
437476         être   inf        ɛtʁ    12
437492         ôter  ai3S        ɔta     1

[1960 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21 s, total: 1min 35s
Wall time: 31.1 s

nbChunk 360
4200
1940

             lexeme  case     phono  tir1
40            avoir  pi3S         a    88
113      abandonner  ii3S  abɑ̃dɔnɛ     1
164      abandonner  ppMS  abɑ̃dɔne     1
287         abattre  ai3S     abati     1
305         abattre  ppMS     abaty     1
2143       abstenir   inf  abstəniʁ     1
2950       accepter  ii3S   aksɛptɛ     1
2988       accepter  pI2P   aksɛpte     1
3400    accompagner  pi3S   akɔ̃paɲ     2
3534       accorder  pi3P     akɔʁd     1
3536       accorder   inf    akɔʁde     1
3544       accorder  fi2P  akɔʁdəʁe     1
4230      accrocher  ai3S    akʁɔʃa     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4255      accrocher  pi3S     akʁɔʃ     2
4262      accrocher  pc3P  akʁɔʃəʁɛ     1
4313      accroître  pi2P   akʁwase     1
4473     accueillir  ii3S     akəjɛ     2
4482     accueillir  pi3S      akœj     1
4509     accueillir   inf    akəjiʁ     1
4690        accuser  ii3P     akyzɛ     1
4748        accuser  ppMS     akyze     1
5041       acharner  ppMS    aʃaʁne     1
5119        acheter   inf     aʃəte     3
5136        acheter  ppMS     aʃəte     6
5139        acheter  ppMP     aʃəte     1
5149        achever  ii3S     aʃəvɛ     1
5157        achever   inf     aʃəve     1
5311        acheter  pi3S      aʃɛt     1
5315        acheter  fi3S   aʃɛtəʁa     1
...             ...   ...       ...   ...
430555     épargner  pi1S     ɛpaʁɲ     1
431167        épier   inf      ɛpje     1
432160      épouser   inf     ɛpuze     1
432532     éprouver  ai3S    ɛpʁuva     1
432552     éprouver  pi3S     ɛpʁuv     1
432556     éprouver   inf    ɛpʁuve     1
432691      épuiser  ppFS    ɛpɥize     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ    11
434070         être  ii3S       ɛtɛ    73
434134       étaler  ii3S     ɛtalɛ     1
434299       étaler  ppMS     ɛtale     1
434773     éteindre  pi3S      ɛtɛ̃     1
434788      étendre  ii3S    ɛtɑ̃dɛ     1
434833      étendre  ppFS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     1
435417      étonner  ai3S     ɛtɔna     2
435425      étonner    pP    ɛtɔnɑ̃     1
435474      étonner  ppMP     ɛtɔne     1
435748    étrangler   inf  ɛtʁɑ̃gle     1
436201      étudier  pi3S     ɛtydi     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    28
436835     éveiller   inf     ɛvɛje     1
437285       éviter    pP    ɛvitɑ̃     1
437301       éviter   inf     ɛvite     3
437474         être  pi2P        ɛt     8
437476         être   inf       ɛtʁ    22
437539         ôter  ppMS       ɔte     1

[1940 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.6 s, total: 1min 35s
Wall time: 29.5 s

nbChunk 361
4200
1937

             lexeme  case     phono  tir1
40            avoir  pi3S         a    86
108      abandonner  ai3S  abɑ̃dɔna     1
166      abandonner  ppFS  abɑ̃dɔne     1
1178        aborder  ppMP    abɔʁde     1
2143       abstenir   inf  abstəniʁ     1
2267      abstraire   inf   abstʁɛʁ     1
2971       accepter   inf   aksɛpte     2
2984       accepter  pi2S    aksɛpt     1
3434    accompagner  ppFS  akɔ̃paɲe     1
3858      accoucher  ppMS     akuʃe     1
3914       accouder  ppFS     akude     1
4272      accrocher  pi2S     akʁɔʃ     1
4502     accueillir  ppMS     akəji     1
4637      accumuler  ii3S   akymylɛ     1
5119        acheter   inf     aʃəte     3
5136        acheter  ppMS     aʃəte     2
5157        achever   inf     aʃəve     1
5171        achever  ppMS     aʃəve     1
5311        acheter  pi3S      aʃɛt     1
5327        acheter  pi2S      aʃɛt     1
5329        achever  pi1S      aʃɛv     1
6891       admettre   inf    admɛtʁ     1
7173        adonner  ii3P     adɔnɛ     1
7312         adorer  pi3S      adɔʁ     1
7400        adosser  ppFP     adɔse     1
7401        adosser  ppMP     adɔse     1
7964      affaiblir  ppFS    afɛbli     1
9575      affronter   inf   afʁɔ̃te     1
10156   agenouiller  ppMS   aʒənuje     1
10157   agenouiller  ppFS   aʒənuje     1
...             ...   ...       ...   ...
433026   équilibrer   inf  ɛkilibʁe     1
433170      équiper  ppFS     ɛkipe     1
433790      éructer  pi3S     ɛʁykt     1
433922      établir   inf   ɛtabliʁ     1
433942      établir  pi2S    ɛtabli     1
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ    10
434070         être  ii3S       ɛtɛ    71
434726     éteindre  ii3S     ɛtɛɲɛ     1
434747     éteindre  ai3S     ɛtɛɲi     1
434775     éteindre  ppFS     ɛtɛ̃t     1
434798      étendre  pi2P    ɛtɑ̃de     1
434917     éternuer  pi3S    ɛtɛʁny     1
435054         être  ii2P      ɛtje     1
435059    étinceler  ii3P  ɛtɛ̃səlɛ     1
435172         être  ii1P     ɛtjɔ̃     1
435232       étirer  ai3S     ɛtiʁa     1
435254       étirer  pi3S      ɛtiʁ     1
435419      étonner  ii3P     ɛtɔnɛ     1
435438      étonner  pi3S      ɛtɔn     1
435500     étouffer  pi3S      ɛtuf     1
435529     étouffer  ii1P   ɛtufjɔ̃     1
436205      étudier   inf    ɛtydje     2
436316         être  ppMS       ɛte    22
436430      évacuer  ppMS    ɛvakye     1
436867     éveiller  ppMS     ɛvɛje     1
437301       éviter   inf     ɛvite     1
437328       éviter  ppMS     ɛvite     1
437474         être  pi2P        ɛt     6
437476         être   inf       ɛtʁ    11

[1937 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 18 s, total: 1min 33s
Wall time: 43.7 s

nbChunk 362
4200
1946

             lexeme  case        phono  tir1
40            avoir  pi3S            a    92
113      abandonner  ii3S     abɑ̃dɔnɛ     1
128      abandonner  pi3S      abɑ̃dɔn     1
132      abandonner   inf     abɑ̃dɔne     1
164      abandonner  ppMS     abɑ̃dɔne     1
170      abandonner  ppMP     abɑ̃dɔne     1
890          abolir   inf       abɔliʁ     1
2070       absorber   inf      absɔʁbe     1
2339         abuser   inf        abyze     1
2577         abîmer  pi3S         abim     1
2610         abîmer  ppMS        abime     1
2950       accepter  ii3S      aksɛptɛ     1
2984       accepter  pi2S       aksɛpt     1
3003       accepter  ppMS      aksɛpte     1
3380    accompagner  ai3S     akɔ̃paɲa     1
3400    accompagner  pi3S      akɔ̃paɲ     1
3406    accompagner   inf     akɔ̃paɲe     1
3484      accomplir  ii1P  akɔ̃plisjɔ̃     1
3508       accorder  ai3S       akɔʁda     1
3519       accorder  ii3S       akɔʁdɛ     1
4237      accrocher  ii3S       akʁɔʃɛ     1
4369      accroupir  pi3S       akʁupi     1
4509     accueillir   inf       akəjiʁ     1
4511     accueillir  ppMP        akəji     1
4992       acharner  ai3S       aʃaʁna     1
5053      acheminer  ii3S      aʃəminɛ     1
5119        acheter   inf        aʃəte     2
5136        acheter  ppMS        aʃəte     1
5137        acheter  ppFS        aʃəte     1
5316        acheter  fi1S      aʃɛtəʁɛ     1
...             ...   ...          ...   ...
433914      établir  ppFS       ɛtabli     2
434048         être  ii3P          ɛtɛ     4
434068         être  ii1S          ɛtɛ    14
434070         être  ii3S          ɛtɛ    67
434260    étalonner   inf      ɛtalɔne     1
434488         être    pP         ɛtɑ̃     1
434772     éteindre  ppMS         ɛtɛ̃     1
434785      étendre  ii3P       ɛtɑ̃dɛ     1
434833      étendre  ppFS       ɛtɑ̃dy     1
434839      étendre  ppMP       ɛtɑ̃dy     1
435054         être  ii2P         ɛtje     3
435055    étinceler  ai3S     ɛtɛ̃səla     1
435172         être  ii1P        ɛtjɔ̃     3
435438      étonner  pi3S         ɛtɔn     1
435500     étouffer  pi3S         ɛtuf     1
436201      étudier  pi3S        ɛtydi     1
436316         être  ppMS          ɛte    26
436516      évaluer  pi3S        ɛvaly     1
436653     évanouir  ii3P     ɛvanuisɛ     1
436818     éveiller  ii1S        ɛvɛjɛ     1
436821     éveiller    pP       ɛvɛjɑ̃     1
436831     éveiller  pi3S         ɛvɛj     1
436835     éveiller   inf        ɛvɛje     2
437285       éviter    pP       ɛvitɑ̃     1
437295       éviter  pi3S         ɛvit     1
437301       éviter   inf        ɛvite     2
437411      évoquer  ai3S        ɛvɔka     1
437474         être  pi2P           ɛt     8
437476         être   inf          ɛtʁ    19
437505         ôter  pi1S           ot     1

[1946 rows x 4 columns]

0
CPU times: user 1min 6s, sys: 18.7 s, total: 1min 25s
Wall time: 30 s

nbChunk 363
4200
1929

             lexeme  case       phono  tir1
40            avoir  pi3S           a    88
128      abandonner  pi3S     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
243         abattre  pi3S         aba     1
287         abattre  ai3S       abati     1
1160        aborder  pi2S       abɔʁd     1
1169        aborder  pi1P     abɔʁdɔ̃     1
1718        abriter  ppFS      abʁite     1
2371         abuser  ppMS       abyze     1
2612         abîmer  ppFS       abime     1
2950       accepter  ii3S     aksɛptɛ     1
2952       accepter    pP    aksɛptɑ̃     1
2980       accepter  pc2P  aksɛptəʁje     1
3003       accepter  ppMS     aksɛpte     3
3406    accompagner   inf    akɔ̃paɲe     2
3422    accompagner  pi2P    akɔ̃paɲe     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3912       accouder  ai3P      akudɛʁ     1
4005      accoupler  ppMP      akuple     1
4259      accrocher   inf      akʁɔʃe     1
4291      accrocher  ppMS      akʁɔʃe     1
4812      accélérer  pi3S     aksɛlɛʁ     1
5119        acheter   inf       aʃəte     2
5125        acheter  pi2P       aʃəte     1
5131        acheter  pi1P      aʃətɔ̃     1
5137        acheter  ppFS       aʃəte     1
5149        achever  ii3S       aʃəvɛ     1
6969        admirer  ii3S      admiʁɛ     1
6996        admirer   inf      admiʁe     1
7285        adopter  ppFP      adɔpte     1
...             ...   ...         ...   ...
431973      éponger  ai3S      ɛpɔ̃ʒa     1
432153      épouser  pi1S        ɛpuz     1
432160      épouser   inf       ɛpuze     1
432638      épuiser  ii3S      ɛpɥizɛ     1
432659      épuiser   inf      ɛpɥize     1
433928      établir  pc3S    ɛtabliʁɛ     1
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ     9
434070         être  ii3S         ɛtɛ    76
434147       étaler  pi3S        ɛtal     1
434719       étayer  ppMS       ɛtɛje     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434836      étendre  ppFP      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     4
435064    étinceler    pP   ɛtɛ̃səlɑ̃     1
435422      étonner  ii3S       ɛtɔnɛ     1
435484     étouffer  ii3S       ɛtufɛ     1
435742    étrangler  pi3S     ɛtʁɑ̃gl     1
436198      étudier  pi1S       ɛtydi     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    31
436678     évanouir  ai3S      ɛvanui     1
436679     évanouir  pi3S      ɛvanui     1
436904      éventer   inf      ɛvɑ̃te     1
437301       éviter   inf       ɛvite     4
437365      évoluer  pi3P       ɛvɔly     1
437427      évoquer  pi3S        ɛvɔk     1
437458      évoquer  ppMS       ɛvɔke     1
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    24

[1929 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 21 s, total: 1min 33s
Wall time: 29.3 s

nbChunk 364
4200
1894

             lexeme  case     phono  tir1
40            avoir  pi3S         a    84
130      abandonner  pi3P   abɑ̃dɔn     1
145      abandonner  pi2S   abɑ̃dɔn     1
299         abattre   inf     abatʁ     1
307         abattre  ppFS     abaty     1
409        abdiquer  pi1S     abdik     1
1034        abonner   inf     abɔne     1
2228       abstenir  pi2S   abstjɛ̃     1
2339         abuser   inf     abyze     1
2581         abîmer   inf     abime     1
2610         abîmer  ppMS     abime     1
2612         abîmer  ppFS     abime     1
2967       accepter  pi3S    aksɛpt     1
2971       accepter   inf   aksɛpte     2
2997       accepter  pi1P  aksɛptɔ̃     1
3003       accepter  ppMS   aksɛpte     1
3434    accompagner  ppFS  akɔ̃paɲe     1
3530       accorder  pi3S     akɔʁd     1
3805      accoucher  ai3S     akuʃa     1
4237      accrocher  ii3S    akʁɔʃɛ     2
4255      accrocher  pi3S     akʁɔʃ     1
4279      accrocher  pI2P    akʁɔʃe     1
4291      accrocher  ppMS    akʁɔʃe     1
4294      accrocher  ppMP    akʁɔʃe     1
4331      accroupir  ai3P   akʁupiʁ     1
4509     accueillir   inf    akəjiʁ     1
4748        accuser  ppMS     akyze     1
5119        acheter   inf     aʃəte     3
5311        acheter  pi3S      aʃɛt     1
6444        adapter  ppFS    adapte     1
...             ...   ...       ...   ...
429727      énerver  ppMS    ɛnɛʁve     1
430374      épandre  ii3P    ɛpɑ̃dɛ     1
431896     éplucher  ii1P  ɛplyʃjɔ̃     1
431973      éponger  ai3S    ɛpɔ̃ʒa     1
432160      épouser   inf     ɛpuze     2
432552     éprouver  pi3S     ɛpʁuv     1
432586     éprouver  ppMS    ɛpʁuve     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    11
434070         être  ii3S       ɛtɛ    75
434762     éteindre   inf    ɛtɛ̃dʁ     1
434895    éterniser  ppMS  ɛtɛʁnize     1
435054         être  ii2P      ɛtje     3
435172         être  ii1P     ɛtjɔ̃     1
435240       étirer  ii3P     ɛtiʁɛ     1
435444      étonner   inf     ɛtɔne     1
435475     étouffer  ai3S     ɛtufa     1
435506     étouffer   inf     ɛtufe     1
436201      étudier  pi3S     ɛtydi     1
436316         être  ppMS       ɛte    31
436432      évacuer  ppFS    ɛvakye     1
437284       éviter  ii3S     ɛvitɛ     1
437285       éviter    pP    ɛvitɑ̃     1
437301       éviter   inf     ɛvite     2
437407      évoluer  ppMS    ɛvɔlye     1
437427      évoquer  pi3S      ɛvɔk     1
437431      évoquer   inf     ɛvɔke     1
437474         être  pi2P        ɛt    13
437476         être   inf       ɛtʁ    17

[1894 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22.3 s, total: 1min 39s
Wall time: 30.6 s

nbChunk 365
4200
1992

             lexeme  case     phono  tir1
40            avoir  pi3S         a    89
164      abandonner  ppMS  abɑ̃dɔne     1
264         abattre  pi3P      abat     1
955         abonder  ii3P    abɔ̃dɛ     1
1147        aborder   inf    abɔʁde     1
1468         aboyer   inf    abwaje     1
1704        abriter  pi2P    abʁite     1
1950       absenter   inf   absɑ̃te     1
2116       absoudre   inf    absudʁ     1
2339         abuser   inf     abyze     2
2939       accepter  ai3S   aksɛpta     1
3003       accepter  ppMS   aksɛpte     1
3349     accommoder   inf   akɔmɔde     1
3380    accompagner  ai3S  akɔ̃paɲa     1
3406    accompagner   inf  akɔ̃paɲe     2
3519       accorder  ii3S    akɔʁdɛ     1
4238      accrocher    pP   akʁɔʃɑ̃     1
4291      accrocher  ppMS    akʁɔʃe     1
4748        accuser  ppMS     akyze     1
4994       acharner  ii3P    aʃaʁnɛ     1
5008       acharner  pi3S     aʃaʁn     1
5119        acheter   inf     aʃəte     5
5136        acheter  ppMS     aʃəte     1
5149        achever  ii3S     aʃəvɛ     1
5157        achever   inf     aʃəve     1
5171        achever  ppMS     aʃəve     1
5814       acquérir  ppFP      akiz     1
6862       admettre  pi3S      admɛ     1
6863       admettre  pi1S      admɛ     1
6967        admirer  ii1S    admiʁɛ     1
...             ...   ...       ...   ...
432693      épuiser  ppFP    ɛpɥize     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ    10
434069         être  ii2S       ɛtɛ     1
434070         être  ii3S       ɛtɛ    65
434730     éteindre  pi3P      ɛtɛɲ     1
434788      étendre  ii3S    ɛtɑ̃dɛ     1
434789      étendre    pP   ɛtɑ̃dɑ̃     1
434803      étendre  ai3P   ɛtɑ̃diʁ     1
434831      étendre  ppMS    ɛtɑ̃dy     1
434833      étendre  ppFS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     2
435243       étirer  ii3S     ɛtiʁɛ     1
435417      étonner  ai3S     ɛtɔna     1
435422      étonner  ii3S     ɛtɔnɛ     1
435500     étouffer  pi3S      ɛtuf     1
435506     étouffer   inf     ɛtufe     1
435742    étrangler  pi3S   ɛtʁɑ̃gl     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    21
436457       évader   inf     ɛvade     1
436867     éveiller  ppMS     ɛvɛje     2
437301       éviter   inf     ɛvite     1
437328       éviter  ppMS     ɛvite     1
437416      évoquer  ii3S     ɛvɔkɛ     1
437474         être  pi2P        ɛt    18
437476         être   inf       ɛtʁ    16
437539         ôter  ppMS       ɔte     1

[1992 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.7 s, total: 1min 36s
Wall time: 29 s

nbChunk 366
4200
1889

             lexeme  case      phono  tir1
40            avoir  pi3S          a    79
113      abandonner  ii3S   abɑ̃dɔnɛ     1
114      abandonner    pP  abɑ̃dɔnɑ̃     1
132      abandonner   inf   abɑ̃dɔne     1
299         abattre   inf      abatʁ     2
1388        aboutir  ppMS      abuti     1
1716        abriter  ppMS     abʁite     1
2070       absorber   inf    absɔʁbe     1
2736       accabler   inf     akable     1
2771      accaparer  ii3P    akapaʁɛ     1
2888      accentuer    pP  aksɑ̃tyɑ̃     1
2950       accepter  ii3S    aksɛptɛ     1
3375     accommoder  ai3P   akɔmɔdɛʁ     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3434    accompagner  ppFS   akɔ̃paɲe     1
3464      accomplir  ii3P  akɔ̃plisɛ     1
3641       accoster    pP    akɔstɑ̃     1
3913       accouder  ppMS      akude     1
4320      accroupir  ppMS     akʁupi     1
4502     accueillir  ppMS      akəji     1
4519     accueillir  ai3S      akəji     1
4654      accumuler  pi3P     akymyl     1
4736        accuser  pi2P      akyze     1
4997       acharner  ii3S     aʃaʁnɛ     1
5005       acharner  pi1S      aʃaʁn     1
5109        acheter  ii1S      aʃətɛ     1
5135        acheter  ai3P     aʃətɛʁ     1
5136        acheter  ppMS      aʃəte     1
...             ...   ...        ...   ...
432537     éprouver  ii3S     ɛpʁuvɛ     1
432556     éprouver   inf     ɛpʁuve     1
433170      équiper  ppFS      ɛkipe     1
433922      établir   inf    ɛtabliʁ     1
433930      établir  ai3P    ɛtabliʁ     1
433946      établir  ii3S   ɛtablisɛ     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ    14
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    88
434772     éteindre  ppMS       ɛtɛ̃     1
434773     éteindre  pi3S       ɛtɛ̃     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
435054         être  ii2P       ɛtje     4
435172         être  ii1P      ɛtjɔ̃     2
435417      étonner  ai3S      ɛtɔna     1
435422      étonner  ii3S      ɛtɔnɛ     1
435444      étonner   inf      ɛtɔne     1
435486     étouffer    pP     ɛtufɑ̃     1
435500     étouffer  pi3S       ɛtuf     1
435731    étrangler  ii3S   ɛtʁɑ̃glɛ     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    22
436520      évaluer   inf     ɛvalye     1
437282       éviter  ii1S      ɛvitɛ     1
437301       éviter   inf      ɛvite     3
437429      évoquer  pi3P       ɛvɔk     1
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    17
437539         ôter  ppMS        ɔte     1

[1889 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.1 s, total: 1min 37s
Wall time: 30.2 s

nbChunk 367
4200
1956

             lexeme  case       phono  tir1
40            avoir  pi3S           a    94
114      abandonner    pP   abɑ̃dɔnɑ̃     1
128      abandonner  pi3S     abɑ̃dɔn     1
130      abandonner  pi3P     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     3
138      abandonner  pc3S  abɑ̃dɔnəʁɛ     1
164      abandonner  ppMS    abɑ̃dɔne     1
299         abattre   inf       abatʁ     1
955         abonder  ii3P      abɔ̃dɛ     1
1143        aborder  pi3S       abɔʁd     1
1393        aboutir   inf      abutiʁ     1
2031       absoudre  pi3P      absɔlv     1
2143       abstenir   inf    abstəniʁ     1
2610         abîmer  ppMS       abime     1
2715       accabler  ii3S      akablɛ     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     1
3406    accompagner   inf    akɔ̃paɲe     1
3414    accompagner  fi2P  akɔ̃paɲəʁe     1
3433    accompagner  ppMS    akɔ̃paɲe     2
3436    accompagner  ppMP    akɔ̃paɲe     1
4259      accrocher   inf      akʁɔʃe     1
4393      accroître  ai3P       akʁyʁ     1
4750        accuser  ppFS       akyze     1
4835      accélérer   inf    aksɛlɛʁe     1
4862      accélérer  ppMS    aksɛlɛʁe     1
5119        acheter   inf       aʃəte     3
5149        achever  ii3S       aʃəvɛ     1
5150        achever    pP      aʃəvɑ̃     1
5311        acheter  pi3S        aʃɛt     1
...             ...   ...         ...   ...
430614   éparpiller  pi3P     ɛpaʁpij     1
430694       épater  pc3S     ɛpatəʁɛ     1
432167      épouser  fi2S     ɛpuzəʁa     1
432556     éprouver   inf      ɛpʁuve     1
432657      épuiser  pi3P       ɛpɥiz     1
433130      équiper  pi2P       ɛkipe     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    79
434762     éteindre   inf      ɛtɛ̃dʁ     1
434773     éteindre  pi3S        ɛtɛ̃     3
434782      étendre  pi3S        ɛtɑ̃     1
434789      étendre    pP     ɛtɑ̃dɑ̃     1
434831      étendre  ppMS      ɛtɑ̃dy     2
435172         être  ii1P       ɛtjɔ̃     2
435254       étirer  pi3S        ɛtiʁ     1
435425      étonner    pP      ɛtɔnɑ̃     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435484     étouffer  ii3S       ɛtufɛ     1
435500     étouffer  pi3S        ɛtuf     1
435540     étouffer  ppFS       ɛtufe     1
436316         être  ppMS         ɛte    26
436436      évacuer  ppMP      ɛvakye     1
436457       évader   inf       ɛvade     1
436867     éveiller  ppMS       ɛvɛje     1
437301       éviter   inf       ɛvite     4
437458      évoquer  ppMS       ɛvɔke     1
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    18
437539         ôter  ppMS         ɔte     1

[1956 rows x 4 columns]

0
CPU times: user 1min 5s, sys: 17.9 s, total: 1min 23s
Wall time: 30 s

nbChunk 368
4200
1942

             lexeme  case      phono  tir1
40            avoir  pi3S          a   104
50         abaisser  ii3S      abɛsɛ     1
128      abandonner  pi3S    abɑ̃dɔn     1
145      abandonner  pi2S    abɑ̃dɔn     1
293         abattre  fi1S     abatʁɛ     1
313         abattre  ppMP      abaty     1
1246       aboucher    pP     abuʃɑ̃     1
1796        abrutir  ppMS     abʁyti     1
2984       accepter  pi2S     aksɛpt     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3386    accompagner    pP  akɔ̃paɲɑ̃     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
3446      accomplir  pc3P  akɔ̃pliʁɛ     1
3508       accorder  ai3S     akɔʁda     1
3517       accorder  ii1S     akɔʁdɛ     1
3536       accorder   inf     akɔʁde     1
3862       accouder  ai3S      akuda     1
3912       accouder  ai3P     akudɛʁ     1
4254      accrocher  pI2S      akʁɔʃ     1
4255      accrocher  pi3S      akʁɔʃ     1
4482     accueillir  pi3S       akœj     2
4502     accueillir  ppMS      akəji     1
4718        accuser  pi3P       akyz     1
4750        accuser  ppFS      akyze     2
4864      accélérer  ppFS   aksɛlɛʁe     1
5119        acheter   inf      aʃəte     1
5173        achever  ppFS      aʃəve     1
5905       acquérir   inf     akɛʁiʁ     1
...             ...   ...        ...   ...
432160      épouser   inf      ɛpuze     2
432164      épouser  pc1S    ɛpuzəʁɛ     1
432302      épouser  ppMS      ɛpuze     1
433395     érailler  pi3S       ɛʁaj     1
433912      établir  ppMS     ɛtabli     1
433954      établir  pi3P    ɛtablis     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    14
434070         être  ii3S        ɛtɛ    76
434134       étaler  ii3S      ɛtalɛ     1
434727     éteindre    pP     ɛtɛɲɑ̃     1
434829      étendre  pi2S       ɛtɑ̃     1
434831      étendre  ppMS     ɛtɑ̃dy     2
435054         être  ii2P       ɛtje     4
435062    étinceler  ii3S   ɛtɛ̃səlɛ     1
435172         être  ii1P      ɛtjɔ̃     4
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435500     étouffer  pi3S       ɛtuf     1
435542     étouffer  ppFP      ɛtufe     1
436316         être  ppMS        ɛte    19
436652     évanouir  pi2S     ɛvanui     1
436821     éveiller    pP     ɛvɛjɑ̃     1
437064     évertuer   inf    ɛvɛʁtye     1
437301       éviter   inf      ɛvite     1
437318       éviter  ii2P     ɛvitje     1
437329       éviter  ppFS      ɛvite     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    11
437540         ôter  ppFS        ɔte     1

[1942 rows x 4 columns]

0
CPU times: user 1min 6s, sys: 18.3 s, total: 1min 25s
Wall time: 30.6 s

nbChunk 369
4200
1939

             lexeme  case      phono  tir1
40            avoir  pi3S          a    99
128      abandonner  pi3S    abɑ̃dɔn     1
164      abandonner  ppMS   abɑ̃dɔne     2
305         abattre  ppMS      abaty     1
1112        abonner  ppFS      abɔne     1
1147        aborder   inf     abɔʁde     2
1415        aboutir  ii3S    abutisɛ     1
1788        abroger  ppFP     abʁɔʒe     1
1796        abrutir  ppMS     abʁyti     1
2143       abstenir   inf   abstəniʁ     1
2335         abuser  pi3S       abyz     1
2952       accepter    pP   aksɛptɑ̃     1
2971       accepter   inf    aksɛpte     1
3003       accepter  ppMS    aksɛpte     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3436    accompagner  ppMP   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
3467      accomplir  ii3S  akɔ̃plisɛ     1
3490      accomplir  pi3S    akɔ̃pli     1
3534       accorder  pi3P      akɔʁd     1
3571       accorder  ppMS     akɔʁde     1
4091       accourir  ppMS      akuʁy     1
4259      accrocher   inf     akʁɔʃe     1
4291      accrocher  ppMS     akʁɔʃe     1
4294      accrocher  ppMP     akʁɔʃe     1
4473     accueillir  ii3S      akəjɛ     1
4862      accélérer  ppMS   aksɛlɛʁe     1
4864      accélérer  ppFS   aksɛlɛʁe     1
5048      acheminer  ai3S    aʃəmina     1
...             ...   ...        ...   ...
428650     émouvoir  pi3S        ɛmø     2
429716      énerver  pi2P     ɛnɛʁve     1
430905       épeler  ppMS      ɛpəle     1
432160      épouser   inf      ɛpuze     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
432638      épuiser  ii3S     ɛpɥizɛ     1
433091      équiper  ii3S      ɛkipɛ     1
433111      équiper  pi3P       ɛkip     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    16
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    78
434072       étaler  ai3S      ɛtala     1
434733     éteindre  pI2P      ɛtɛɲe     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     2
435506     étouffer   inf      ɛtufe     1
436316         être  ppMS        ɛte    21
436516      évaluer  pi3S      ɛvaly     1
437024     éventrer  ppMS    ɛvɑ̃tʁe     1
437282       éviter  ii1S      ɛvitɛ     1
437284       éviter  ii3S      ɛvitɛ     1
437301       éviter   inf      ɛvite     2
437407      évoluer  ppMS     ɛvɔlye     1
437411      évoquer  ai3S      ɛvɔka     1
437474         être  pi2P         ɛt    15
437476         être   inf        ɛtʁ    20
437512         ôter   inf        ɔte     1

[1939 rows x 4 columns]

0
CPU times: user 1min 7s, sys: 18.5 s, total: 1min 25s
Wall time: 30.7 s

nbChunk 370
4200
1925

             lexeme  case      phono  tir1
40            avoir  pi3S          a    98
114      abandonner    pP  abɑ̃dɔnɑ̃     1
1143        aborder  pi3S      abɔʁd     1
1147        aborder   inf     abɔʁde     1
1673        abriter  ii3S     abʁitɛ     1
1884        abréger   inf     abʁɛʒe     1
2066       absorber  pi3S     absɔʁb     1
2070       absorber   inf    absɔʁbe     1
2116       absoudre   inf     absudʁ     1
2143       abstenir   inf   abstəniʁ     1
2339         abuser   inf      abyze     1
2371         abuser  ppMS      abyze     1
2612         abîmer  ppFS      abime     1
2904      accentuer   inf   aksɑ̃tye     1
2939       accepter  ai3S    aksɛpta     1
2971       accepter   inf    aksɛpte     2
3385    accompagner  ii3S   akɔ̃paɲɛ     2
3400    accompagner  pi3S    akɔ̃paɲ     1
3434    accompagner  ppFS   akɔ̃paɲe     2
3436    accompagner  ppMP   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
3530       accorder  pi3S      akɔʁd     1
4233      accrocher  ai1S     akʁɔʃɛ     1
4234      accrocher  ii3P     akʁɔʃɛ     1
4259      accrocher   inf     akʁɔʃe     1
4291      accrocher  ppMS     akʁɔʃe     1
4690        accuser  ii3P      akyzɛ     1
4748        accuser  ppMS      akyze     1
4771        accéder  ii3S     aksɛdɛ     1
5119        acheter   inf      aʃəte     3
...             ...   ...        ...   ...
434762     éteindre   inf     ɛtɛ̃dʁ     2
434782      étendre  pi3S       ɛtɑ̃     1
434821      étendre   inf     ɛtɑ̃dʁ     2
435054         être  ii2P       ɛtje     4
435135      étioler   inf     ɛtjɔle     1
435172         être  ii1P      ɛtjɔ̃     2
435231    étiqueter  ppMP    ɛtikəte     1
435243       étirer  ii3S      ɛtiʁɛ     1
435254       étirer  pi3S       ɛtiʁ     1
435438      étonner  pi3S       ɛtɔn     1
435471      étonner  ppMS      ɛtɔne     1
435484     étouffer  ii3S      ɛtufɛ     1
435492     étouffer  is3P     ɛtufas     1
435497     étouffer  pi1S       ɛtuf     1
435506     étouffer   inf      ɛtufe     1
435544     étouffer  ppMP      ɛtufe     1
435654     étourdir  ppMS     ɛtuʁdi     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    19
436436      évacuer  ppMP     ɛvakye     1
436805       évaser  ppMS      ɛvaze     1
436835     éveiller   inf      ɛvɛje     1
437281       éviter  ii3P      ɛvitɛ     1
437295       éviter  pi3S       ɛvit     1
437301       éviter   inf      ɛvite     2
437458      évoquer  ppMS      ɛvɔke     1
437474         être  pi2P         ɛt    12
437476         être   inf        ɛtʁ    15
437539         ôter  ppMS        ɔte     1

[1925 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.5 s, total: 1min 39s
Wall time: 30.7 s

nbChunk 371
4200
1985

             lexeme  case      phono  tir1
40            avoir  pi3S          a    85
130      abandonner  pi3P    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
145      abandonner  pi2S    abɑ̃dɔn     1
243         abattre  pi3S        aba     1
307         abattre  ppFS      abaty     1
980         abonder  pi3S      abɔ̃d     1
1684        abriter  pi3S      abʁit     1
2143       abstenir   inf   abstəniʁ     1
2335         abuser  pi3S       abyz     1
2610         abîmer  ppMS      abime     2
2977       accepter  pc3S  aksɛptəʁɛ     1
3003       accepter  ppMS    aksɛpte     1
3397    accompagner  pi1S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     2
3422    accompagner  pi2P   akɔ̃paɲe     1
3519       accorder  ii3S     akɔʁdɛ     3
4007       accourir  ii1S      akuʁɛ     1
4320      accroupir  ppMS     akʁupi     1
4484     accueillir  pi3P       akœj     1
4783        accéder   inf     aksɛde     1
4814      accélérer  pi3P    aksɛlɛʁ     1
5119        acheter   inf      aʃəte     1
5125        acheter  pi2P      aʃəte     1
5139        acheter  ppMP      aʃəte     1
5313        acheter  pi3P       aʃɛt     1
5764     acquiescer   inf     akjɛse     1
6883       admettre  pi1P    admɛtɔ̃     1
6996        admirer   inf     admiʁe     1
7173        adonner  ii3P      adɔnɛ     1
...             ...   ...        ...   ...
432156      épouser  pi3S       ɛpuz     1
432160      épouser   inf      ɛpuze     3
432302      épouser  ppMS      ɛpuze     1
432533     éprouver  ai1S     ɛpʁuvɛ     1
433113      équiper   inf      ɛkipe     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ    24
434070         être  ii3S        ɛtɛ    88
434134       étaler  ii3S      ɛtalɛ     1
434147       étaler  pi3S       ɛtal     2
434299       étaler  ppMS      ɛtale     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
434853    éterniser  ii3S   ɛtɛʁnizɛ     1
435231    étiqueter  ppMP    ɛtikəte     1
435420      étonner  ii1S      ɛtɔnɛ     1
435425      étonner    pP     ɛtɔnɑ̃     1
435450      étonner  pc3S    ɛtɔnəʁɛ     1
435471      étonner  ppMS      ɛtɔne     1
435506     étouffer   inf      ɛtufe     1
435666     étourdir  pc3S   ɛtuʁdiʁɛ     1
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    22
436520      évaluer   inf     ɛvalye     1
436627     évanouir  ppMS     ɛvanui     1
437417      évoquer    pP     ɛvɔkɑ̃     1
437474         être  pi2P         ɛt    16
437476         être   inf        ɛtʁ    17

[1985 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.5 s, total: 1min 39s
Wall time: 30.7 s

nbChunk 372
4200
1999

             lexeme  case       phono  tir1
40            avoir  pi3S           a    73
132      abandonner   inf    abɑ̃dɔne     2
145      abandonner  pi2S     abɑ̃dɔn     1
255         abattre  ii3P       abatɛ     1
299         abattre   inf       abatʁ     1
1388        aboutir  ppMS       abuti     1
1816        abrutir  ppMP      abʁyti     1
2612         abîmer  ppFS       abime     1
2946       accepter  ai1S     aksɛptɛ     1
2967       accepter  pi3S      aksɛpt     1
3406    accompagner   inf    akɔ̃paɲe     2
3433    accompagner  ppMS    akɔ̃paɲe     1
3527       accorder  pi1S       akɔʁd     1
3536       accorder   inf      akɔʁde     1
3840      accoucher  pi2S        akuʃ     1
3916       accouder  ppMP       akude     1
4255      accrocher  pi3S       akʁɔʃ     1
4259      accrocher   inf      akʁɔʃe     1
4484     accueillir  pi3P        akœj     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     2
5308        acheter  pi1S        aʃɛt     1
5315        acheter  fi3S     aʃɛtəʁa     1
5329        achever  pi1S        aʃɛv     1
5846      acquitter  pi3S        akit     1
6865       admettre  pi2S        admɛ     1
6970        admirer    pP     admiʁɑ̃     1
7027       admettre  ppMP        admi     1
7283        adopter  ppMS      adɔpte     1
7297         adorer  ii3S       adɔʁɛ     1
...             ...   ...         ...   ...
434068         être  ii1S         ɛtɛ    13
434069         être  ii2S         ɛtɛ     1
434070         être  ii3S         ɛtɛ    69
434135       étaler    pP      ɛtalɑ̃     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434768     éteindre  pi1S        ɛtɛ̃     1
434775     éteindre  ppFS       ɛtɛ̃t     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434821      étendre   inf      ɛtɑ̃dʁ     1
434831      étendre  ppMS      ɛtɑ̃dy     1
434833      étendre  ppFS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     2
435254       étirer  pi3S        ɛtiʁ     2
435292       étirer  ai3P      ɛtiʁɛʁ     1
435363      étoiler  ii3S      ɛtwalɛ     1
435444      étonner   inf       ɛtɔne     1
435472      étonner  ppFS       ɛtɔne     1
435497     étouffer  pi1S        ɛtuf     1
435506     étouffer   inf       ɛtufe     1
435749    étrangler  fi3S  ɛtʁɑ̃gləʁa     1
436205      étudier   inf      ɛtydje     2
436316         être  ppMS         ɛte    18
436657     évanouir    pP   ɛvanuisɑ̃     1
436835     éveiller   inf       ɛvɛje     1
437299       éviter  pi3P        ɛvit     1
437414      évoquer  ii1S       ɛvɔkɛ     1
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    20
437539         ôter  ppMS         ɔte     1

[1999 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.4 s, total: 1min 34s
Wall time: 30 s

nbChunk 373
4200
1957

             lexeme  case      phono  tir1
40            avoir  pi3S          a    89
125      abandonner  pi1S    abɑ̃dɔn     1
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     2
264         abattre  pi3P       abat     1
1132        aborder  ii3S     abɔʁdɛ     1
1133        aborder    pP    abɔʁdɑ̃     1
2068       absorber  pi3P     absɔʁb     1
2734       accabler  pi3P      akabl     1
2971       accepter   inf    aksɛpte     3
3003       accepter  ppMS    aksɛpte     2
3386    accompagner    pP  akɔ̃paɲɑ̃     1
3404    accompagner  pi3P    akɔ̃paɲ     1
3443      accomplir   inf   akɔ̃pliʁ     1
3471      accomplir  ps3S   akɔ̃plis     1
3536       accorder   inf     akɔʁde     1
3682       accoster  ppMS     akɔste     1
3858      accoucher  ppMS      akuʃe     1
4294      accrocher  ppMP     akʁɔʃe     1
4718        accuser  pi3P       akyz     1
4748        accuser  ppMS      akyze     1
4783        accéder   inf     aksɛde     1
4824      accélérer    pP  aksɛlɛʁɑ̃     1
5102        acheter  ai3S      aʃəta     1
5119        acheter   inf      aʃəte     1
5136        acheter  ppMS      aʃəte     1
5140        achever  ai3S      aʃəva     1
5171        achever  ppMS      aʃəve     1
5740       acquérir  fi1S     akɛʁʁɛ     1
...             ...   ...        ...   ...
432539     éprouver    pP    ɛpʁuvɑ̃     1
432556     éprouver   inf     ɛpʁuve     2
433105      équiper  pi3S       ɛkip     1
433618       ériger  ppFS      ɛʁiʒe     1
433922      établir   inf    ɛtabliʁ     1
433946      établir  ii3S   ɛtablisɛ     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    16
434070         être  ii3S        ɛtɛ    88
434488         être    pP       ɛtɑ̃     1
434782      étendre  pi3S       ɛtɑ̃     1
434786      étendre  ii1S     ɛtɑ̃dɛ     1
435054         être  ii2P       ɛtje     2
435243       étirer  ii3S      ɛtiʁɛ     1
435481     étouffer  ii3P      ɛtufɛ     1
435486     étouffer    pP     ɛtufɑ̃     1
435534     étouffer  is3S      ɛtufa     1
436181      étudier  ai3S     ɛtydja     1
436198      étudier  pi1S      ɛtydi     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    18
436484       évader  ppMS      ɛvade     1
436820     éveiller  ii3S      ɛvɛjɛ     1
436835     éveiller   inf      ɛvɛje     1
437301       éviter   inf      ɛvite     2
437328       éviter  ppMS      ɛvite     1
437367      évoluer   inf     ɛvɔlye     1
437429      évoquer  pi3P       ɛvɔk     1
437474         être  pi2P         ɛt    11
437476         être   inf        ɛtʁ    27

[1957 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22 s, total: 1min 37s
Wall time: 30.5 s

nbChunk 374
4200
1962

             lexeme  case     phono  tir1
40            avoir  pi3S         a    93
101        abaisser  ppMS     abɛse     1
108      abandonner  ai3S  abɑ̃dɔna     1
164      abandonner  ppMS  abɑ̃dɔne     1
166      abandonner  ppFS  abɑ̃dɔne     1
1306        abouler  pI2S      abul     1
3383    accompagner  ii1S  akɔ̃paɲɛ     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3443      accomplir   inf  akɔ̃pliʁ     1
3534       accorder  pi3P     akɔʁd     1
4259      accrocher   inf    akʁɔʃe     1
4291      accrocher  ppMS    akʁɔʃe     2
4293      accrocher  ppFP    akʁɔʃe     1
4294      accrocher  ppMP    akʁɔʃe     1
4481     accueillir  pI2S      akœj     1
4502     accueillir  ppMS     akəji     1
4718        accuser  pi3P      akyz     1
5109        acheter  ii1S     aʃətɛ     1
5119        acheter   inf     aʃəte     2
5136        acheter  ppMS     aʃəte     2
5157        achever   inf     aʃəve     1
5162        achever  ii1P   aʃəvjɔ̃     1
5812       acquérir  ppFS      akiz     1
6067        activer  pi3S     aktiv     2
7312         adorer  pi3S      adɔʁ     3
7523       adresser  ii3S    adʁɛsɛ     1
7568       adresser  ppFS    adʁɛse     1
8305       affecter  ii3S    afɛktɛ     1
8322       affecter   inf    afɛkte     1
8772       affirmer  ai3S    afiʁma     1
...             ...   ...       ...   ...
432584     éprouver  ai3P   ɛpʁuvɛʁ     1
432586     éprouver  ppMS    ɛpʁuve     1
432771       épurer  ppFP     ɛpyʁe     1
433062   équilibrer  ppMS  ɛkilibʁe     1
433969      établir  pi3S    ɛtabli     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ     8
434070         être  ii3S       ɛtɛ    79
434147       étaler  pi3S      ɛtal     1
434307       étamer  ii3P     ɛtamɛ     1
434773     éteindre  pi3S      ɛtɛ̃     1
434811      étendre  ai3S    ɛtɑ̃di     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     2
435260       étirer   inf     ɛtiʁe     2
435420      étonner  ii1S     ɛtɔnɛ     1
435422      étonner  ii3S     ɛtɔnɛ     2
435472      étonner  ppFS     ɛtɔne     1
435475     étouffer  ai3S     ɛtufa     1
435482     étouffer  ii1S     ɛtufɛ     1
435794    étreindre  ii3S    ɛtʁɛɲɛ     1
436316         être  ppMS       ɛte    20
436520      évaluer   inf    ɛvalye     1
436627     évanouir  ppMS    ɛvanui     1
437285       éviter    pP    ɛvitɑ̃     1
437301       éviter   inf     ɛvite     1
437413      évoquer  ii3P     ɛvɔkɛ     1
437431      évoquer   inf     ɛvɔke     1
437474         être  pi2P        ɛt    10
437476         être   inf       ɛtʁ    12

[1962 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.2 s, total: 1min 38s
Wall time: 30.7 s

nbChunk 375
4200
1987

             lexeme  case       phono  tir1
40            avoir  pi3S           a    84
125      abandonner  pi1S     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     1
271         abattre  pI2P       abate     1
299         abattre   inf       abatʁ     1
1147        aborder   inf      abɔʁde     1
1688        abriter   inf      abʁite     1
2950       accepter  ii3S     aksɛptɛ     1
2971       accepter   inf     aksɛpte     1
3093       acclamer  ii3P      aklamɛ     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3400    accompagner  pi3S     akɔ̃paɲ     3
3408    accompagner  fi1S  akɔ̃paɲəʁɛ     1
3443      accomplir   inf    akɔ̃pliʁ     1
3527       accorder  pi1S       akɔʁd     1
3571       accorder  ppMS      akɔʁde     1
3970      accoupler   inf      akuple     1
4238      accrocher    pP     akʁɔʃɑ̃     1
4255      accrocher  pi3S       akʁɔʃ     1
4292      accrocher  ppFS      akʁɔʃe     1
4387      accroître  ppMS        akʁy     1
4503     accueillir  ppFS       akəji     1
4627        acculer  ppFS       akyle     1
4713        accuser  pi1S        akyz     1
5111        acheter  ii3S       aʃətɛ     1
5119        acheter   inf       aʃəte     5
5136        acheter  ppMS       aʃəte     1
5149        achever  ii3S       aʃəvɛ     1
5157        achever   inf       aʃəve     1
...             ...   ...         ...   ...
427641     éloigner   inf      ɛlwaɲe     1
427669     éloigner  ppFS      ɛlwaɲe     1
427897        élire  ppMP         ɛly     1
427923       élever  pi3S        ɛlɛv     1
428400      émerger  ii3S      ɛmɛʁʒɛ     1
428609      émettre  pi3S         ɛmɛ     1
428864      émettre  ai3S         ɛmi     1
429337     émouvoir  ii3S       ɛmuvɛ     1
429498     émouvoir  ppMP         ɛmy     1
432160      épouser   inf       ɛpuze     2
432168      épouser  fi2P     ɛpuzəʁe     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    75
434299       étaler  ppMS       ɛtale     1
435054         être  ii2P        ɛtje     3
435172         être  ii1P       ɛtjɔ̃     1
435260       étirer   inf       ɛtiʁe     1
435484     étouffer  ii3S       ɛtufɛ     1
435486     étouffer    pP      ɛtufɑ̃     1
436316         être  ppMS         ɛte    21
436457       évader   inf       ɛvade     1
436831     éveiller  pi3S        ɛvɛj     1
436867     éveiller  ppMS       ɛvɛje     1
437281       éviter  ii3P       ɛvitɛ     1
437301       éviter   inf       ɛvite     2
437407      évoluer  ppMS      ɛvɔlye     1
437474         être  pi2P          ɛt    10
437476         être   inf         ɛtʁ    20

[1987 rows x 4 columns]

0
CPU times: user 1min 9s, sys: 20 s, total: 1min 29s
Wall time: 30.8 s

nbChunk 376
4200
1961

             lexeme  case     phono  tir1
40            avoir  pi3S         a    83
125      abandonner  pi1S   abɑ̃dɔn     2
132      abandonner   inf  abɑ̃dɔne     2
164      abandonner  ppMS  abɑ̃dɔne     1
264         abattre  pi3P      abat     1
865          aboyer  pi3S      abwa     1
2100       absorber  ppMS   absɔʁbe     1
2339         abuser   inf     abyze     1
2736       accabler   inf    akable     1
2968       accepter  ps3S    aksɛpt     1
2971       accepter   inf   aksɛpte     1
2997       accepter  pi1P  aksɛptɔ̃     1
3003       accepter  ppMS   aksɛpte     1
3433    accompagner  ppMS  akɔ̃paɲe     3
3443      accomplir   inf  akɔ̃pliʁ     2
3490      accomplir  pi3S   akɔ̃pli     1
3530       accorder  pi3S     akɔʁd     1
3556       accorder  pi2P    akɔʁde     1
3805      accoucher  ai3S     akuʃa     1
3914       accouder  ppFS     akude     1
4255      accrocher  pi3S     akʁɔʃ     1
4257      accrocher  pi3P     akʁɔʃ     1
4280      accrocher  pi2P    akʁɔʃe     1
4294      accrocher  ppMP    akʁɔʃe     1
4391      accroître  ppFP      akʁy     1
4502     accueillir  ppMS     akəji     1
4783        accéder   inf    aksɛde     1
4818      accélérer  ai3S  aksɛlɛʁa     1
4997       acharner  ii3S    aʃaʁnɛ     1
5005       acharner  pi1S     aʃaʁn     1
...             ...   ...       ...   ...
427733        élire  ppMS       ɛly     2
427897        élire  ppMP       ɛly     1
427923       élever  pi3S      ɛlɛv     1
429349     émouvoir   inf   ɛmuvwaʁ     1
429365     émouvoir  ppMS       ɛmy     2
430210     épaissir  pi3S     ɛpɛsi     1
430502     épanouir  pi1S    ɛpanui     1
431065        épier    pP     ɛpjɑ̃     1
432421   épouvanter  ppFS  ɛpuvɑ̃te     1
433590       ériger   inf     ɛʁiʒe     1
433912      établir  ppMS    ɛtabli     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ     5
434070         être  ii3S       ɛtɛ    63
434762     éteindre   inf    ɛtɛ̃dʁ     1
434782      étendre  pi3S      ɛtɑ̃     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     1
435471      étonner  ppMS     ɛtɔne     1
435500     étouffer  pi3S      ɛtuf     1
435742    étrangler  pi3S   ɛtʁɑ̃gl     1
436316         être  ppMS       ɛte    22
436869     éveiller  ppFS     ɛvɛje     1
437301       éviter   inf     ɛvite     3
437328       éviter  ppMS     ɛvite     1
437352      évoluer  ii3S    ɛvɔlyɛ     1
437431      évoquer   inf     ɛvɔke     1
437474         être  pi2P        ɛt    17
437476         être   inf       ɛtʁ    25
437508         ôter  pi3S        ot     1

[1961 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.2 s, total: 1min 34s
Wall time: 29.7 s

nbChunk 377
4200
1939

             lexeme  case      phono  tir1
40            avoir  pi3S          a    71
1245       aboucher  ii3S      abuʃɛ     1
1393        aboutir   inf     abutiʁ     1
2332         abuser  pi1S       abyz     1
2610         abîmer  ppMS      abime     1
2939       accepter  ai3S    aksɛpta     1
2971       accepter   inf    aksɛpte     1
2972       accepter  fi3S  aksɛptəʁa     1
3003       accepter  ppMS    aksɛpte     1
3400    accompagner  pi3S    akɔ̃paɲ     2
3438      accomplir  ppMS    akɔ̃pli     1
3443      accomplir   inf   akɔ̃pliʁ     1
3573       accorder  ppFS     akɔʁde     1
3914       accouder  ppFS      akude     1
4063       accourir  pi3P       akuʁ     1
4072       accourir   inf     akuʁiʁ     1
4320      accroupir  ppMS     akʁupi     1
4484     accueillir  pi3P       akœj     1
4509     accueillir   inf     akəjiʁ     1
5102        acheter  ai3S      aʃəta     2
5119        acheter   inf      aʃəte     2
5146        achever  ii3P      aʃəvɛ     2
5332        achever  pi3S       aʃɛv     2
5832      acquitter  ii3P      akitɛ     1
6043      actionner  ppMS    aksjɔne     1
6048        activer  ai3S     aktiva     1
6410        adapter  pi3S      adapt     1
6765        adjuger    pP    adʒyʒɑ̃     1
6870       admettre    pP    admɛtɑ̃     1
7246        adopter  pi3S      adɔpt     1
...             ...   ...        ...   ...
432580     éprouver  pi1P    ɛpʁuvɔ̃     1
432689      épuiser  ppMS     ɛpɥize     1
433172      équiper  ppFP      ɛkipe     1
433968      établir  ai3S     ɛtabli     1
434048         être  ii3P        ɛtɛ     4
434068         être  ii1S        ɛtɛ    12
434070         être  ii3S        ɛtɛ    75
434151       étaler  pi3P       ɛtal     1
434300       étaler  ppFS      ɛtale     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434772     éteindre  ppMS       ɛtɛ̃     1
434779     éteindre  ppMP       ɛtɛ̃     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434789      étendre    pP    ɛtɑ̃dɑ̃     1
435054         être  ii2P       ɛtje     2
435472      étonner  ppFS      ɛtɔne     1
435475     étouffer  ai3S      ɛtufa     1
435748    étrangler   inf   ɛtʁɑ̃gle     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    26
436520      évaluer   inf     ɛvalye     1
437273       éviter  ai3S      ɛvita     1
437301       éviter   inf      ɛvite     1
437363      évoluer  pi3S      ɛvɔly     1
437411      évoquer  ai3S      ɛvɔka     1
437416      évoquer  ii3S      ɛvɔkɛ     1
437427      évoquer  pi3S       ɛvɔk     1
437458      évoquer  ppMS      ɛvɔke     1
437474         être  pi2P         ɛt    18
437476         être   inf        ɛtʁ    20

[1939 rows x 4 columns]

0
CPU times: user 1min 9s, sys: 19.6 s, total: 1min 29s
Wall time: 31.4 s

nbChunk 378
4200
1996

             lexeme  case       phono  tir1
40            avoir  pi3S           a    89
108      abandonner  ai3S    abɑ̃dɔna     1
111      abandonner  ii1S    abɑ̃dɔnɛ     1
113      abandonner  ii3S    abɑ̃dɔnɛ     1
151      abandonner  ii1P  abɑ̃dɔnjɔ̃     1
164      abandonner  ppMS    abɑ̃dɔne     1
166      abandonner  ppFS    abɑ̃dɔne     1
170      abandonner  ppMP    abɑ̃dɔne     1
1468         aboyer   inf      abwaje     1
1670        abriter  ii3P      abʁitɛ     1
2100       absorber  ppMS     absɔʁbe     1
2223       abstenir  pi3P     abstjɛn     1
2971       accepter   inf     aksɛpte     1
3003       accepter  ppMS     aksɛpte     1
3009       accepter  ppMP     aksɛpte     1
3386    accompagner    pP   akɔ̃paɲɑ̃     1
3458      accomplir  ppMP     akɔ̃pli     1
3475      accomplir  pi3P    akɔ̃plis     1
3536       accorder   inf      akɔʁde     1
3583       accorder  ppMP      akɔʁde     1
4216     accoutumer  ppMP     akutyme     1
4252      accrocher  pi1S       akʁɔʃ     1
4255      accrocher  pi3S       akʁɔʃ     1
4510     accueillir  ai3P      akəjiʁ     1
4992       acharner  ai3S      aʃaʁna     1
5005       acharner  pi1S       aʃaʁn     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     1
5140        achever  ai3S       aʃəva     1
5171        achever  ppMS       aʃəve     1
...             ...   ...         ...   ...
430517     épanouir  pi3P     ɛpanuis     1
430616   éparpiller   inf    ɛpaʁpije     1
430721       épater  ppMS       ɛpate     1
430727       épater  ppMP       ɛpate     1
432144      épouser  ii3S       ɛpuzɛ     1
432145      épouser    pP      ɛpuzɑ̃     1
432160      épouser   inf       ɛpuze     1
432162      épouser  fi1S     ɛpuzəʁɛ     1
432535     éprouver  ii1S      ɛpʁuvɛ     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    17
434070         être  ii3S         ɛtɛ    73
434727     éteindre    pP      ɛtɛɲɑ̃     1
434730     éteindre  pi3P        ɛtɛɲ     1
434782      étendre  pi3S        ɛtɑ̃     1
434789      étendre    pP     ɛtɑ̃dɑ̃     1
434804      étendre  ai1S      ɛtɑ̃di     1
435172         être  ii1P       ɛtjɔ̃     1
435417      étonner  ai3S       ɛtɔna     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    21
436402      évacuer   inf      ɛvakye     1
436815     éveiller  ai3S       ɛvɛja     1
437284       éviter  ii3S       ɛvitɛ     1
437301       éviter   inf       ɛvite     2
437352      évoluer  ii3S      ɛvɔlyɛ     1
437360      évoluer  pi1S       ɛvɔly     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    23
437508         ôter  pi3S          ot     1

[1996 rows x 4 columns]

0
CPU times: user 1min 12s, sys: 21.1 s, total: 1min 33s
Wall time: 30.5 s

nbChunk 379
4200
1967

             lexeme  case      phono  tir1
40            avoir  pi3S          a    81
113      abandonner  ii3S   abɑ̃dɔnɛ     1
177      abasourdir  ppMS   abazuʁdi     1
264         abattre  pi3P       abat     1
443        abdiquer  ppMS     abdike     1
2371         abuser  ppMS      abyze     1
2771      accaparer  ii3P    akapaʁɛ     1
2971       accepter   inf    aksɛpte     3
3003       accepter  ppMS    aksɛpte     1
3005       accepter  ppFS    aksɛpte     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3406    accompagner   inf   akɔ̃paɲe     1
3434    accompagner  ppFS   akɔ̃paɲe     1
3556       accorder  pi2P     akɔʁde     1
3970      accoupler   inf     akuple     1
4006       accourir  ii3P      akuʁɛ     1
4259      accrocher   inf     akʁɔʃe     1
4292      accrocher  ppFS     akʁɔʃe     1
4296       accroire   inf     akʁwaʁ     1
4321      accroupir  ppFS     akʁupi     1
4347      accroupir    pP  akʁupisɑ̃     1
4685      accumuler  ppFP    akymyle     1
4693        accuser  ii3S      akyzɛ     1
4716        accuser  pi3S       akyz     1
4748        accuser  ppMS      akyze     1
4835      accélérer   inf   aksɛlɛʁe     1
5107        acheter  ai1S      aʃətɛ     1
5119        acheter   inf      aʃəte     3
5157        achever   inf      aʃəve     1
5807       acquérir  ppMS        aki     1
...             ...   ...        ...   ...
433922      établir   inf    ɛtabliʁ     1
433968      établir  ai3S     ɛtabli     1
434048         être  ii3P        ɛtɛ     3
434068         être  ii1S        ɛtɛ    14
434070         être  ii3S        ɛtɛ    56
434298       étaler  ai3P     ɛtalɛʁ     1
434727     éteindre    pP     ɛtɛɲɑ̃     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434775     éteindre  ppFS      ɛtɛ̃t     1
434785      étendre  ii3P     ɛtɑ̃dɛ     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434831      étendre  ppMS     ɛtɑ̃dy     2
434864    éterniser  pi3S    ɛtɛʁniz     1
435054         être  ii2P       ɛtje     2
435172         être  ii1P      ɛtjɔ̃     1
435417      étonner  ai3S      ɛtɔna     1
435438      étonner  pi3S       ɛtɔn     1
435920     étriller   inf     ɛtʁije     1
435968      étriper  pi3S      ɛtʁip     1
436186      étudier  ii3S     ɛtydjɛ     1
436205      étudier   inf     ɛtydje     2
436316         être  ppMS        ɛte    16
436547      évaluer  ppMS     ɛvalye     1
436632     évanouir   inf    ɛvanuiʁ     1
436653     évanouir  ii3P   ɛvanuisɛ     1
437301       éviter   inf      ɛvite     1
437329       éviter  ppFS      ɛvite     1
437459      évoquer  ppFS      ɛvɔke     1
437474         être  pi2P         ɛt    14
437476         être   inf        ɛtʁ    16

[1967 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.3 s, total: 1min 34s
Wall time: 29.5 s

nbChunk 380
4200
1913

             lexeme  case       phono  tir1
40            avoir  pi3S           a   114
108      abandonner  ai3S    abɑ̃dɔna     1
128      abandonner  pi3S     abɑ̃dɔn     1
130      abandonner  pi3P     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
134      abandonner  fi1S  abɑ̃dɔnəʁɛ     1
164      abandonner  ppMS    abɑ̃dɔne     1
287         abattre  ai3S       abati     1
654         abjurer  pi1S       abʒyʁ     1
887          abolir  ppMS       abɔli     1
2325         abuser    pP      abyzɑ̃     1
2355         abuser  pi2P       abyze     1
2577         abîmer  pi3S        abim     2
2971       accepter   inf     aksɛpte     2
2999       accepter  is3S     aksɛpta     1
3003       accepter  ppMS     aksɛpte     3
3400    accompagner  pi3S     akɔ̃paɲ     3
3444      accomplir  fi3S   akɔ̃pliʁa     1
3460      accomplir  pi1S     akɔ̃pli     1
3530       accorder  pi3S       akɔʁd     2
4237      accrocher  ii3S      akʁɔʃɛ     1
4292      accrocher  ppFS      akʁɔʃe     1
4381      accroître   inf     akʁwatʁ     1
4502     accueillir  ppMS       akəji     1
4547        acculer   inf       akyle     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     2
5311        acheter  pi3S        aʃɛt     1
5332        achever  pi3S        aʃɛv     1
5338        achever  fi3S     aʃɛvəʁa     1
...             ...   ...         ...   ...
432537     éprouver  ii3S      ɛpʁuvɛ     1
432552     éprouver  pi3S       ɛpʁuv     1
432650      épuiser  pi1S       ɛpɥiz     1
432695      épuiser  ppMP      ɛpɥize     1
433823      éructer  ppFP      ɛʁykte     1
433912      établir  ppMS      ɛtabli     1
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ    13
434070         être  ii3S         ɛtɛ    71
434747     éteindre  ai3S       ɛtɛɲi     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
435059    étinceler  ii3P    ɛtɛ̃səlɛ     1
435172         être  ii1P       ɛtjɔ̃     1
435254       étirer  pi3S        ɛtiʁ     1
435293       étirer  ppMS       ɛtiʁe     1
435438      étonner  pi3S        ɛtɔn     1
435471      étonner  ppMS       ɛtɔne     1
435506     étouffer   inf       ɛtufe     1
435540     étouffer  ppFS       ɛtufe     1
435668     étourdir  ai3P     ɛtuʁdiʁ     1
435780    étrangler  ppMS    ɛtʁɑ̃gle     1
436316         être  ppMS         ɛte    24
436547      évaluer  ppMS      ɛvalye     1
436762       évaser  pi3S        ɛvaz     1
437285       éviter    pP      ɛvitɑ̃     1
437301       éviter   inf       ɛvite     2
437352      évoluer  ii3S      ɛvɔlyɛ     1
437431      évoquer   inf       ɛvɔke     1
437474         être  pi2P          ɛt    14
437476         être   inf         ɛtʁ    15

[1913 rows x 4 columns]

0
CPU times: user 1min 11s, sys: 21 s, total: 1min 32s
Wall time: 30 s

nbChunk 381
4200
1934

             lexeme  case       phono  tir1
40            avoir  pi3S           a    73
114      abandonner    pP   abɑ̃dɔnɑ̃     1
128      abandonner  pi3S     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
166      abandonner  ppFS    abɑ̃dɔne     1
258         abattre  ii3S       abatɛ     1
313         abattre  ppMP       abaty     2
890          abolir   inf      abɔliʁ     1
1143        aborder  pi3S       abɔʁd     1
1147        aborder   inf      abɔʁde     1
1440        aboutir  pi3S       abuti     1
1681        abriter  pi1S       abʁit     1
2610         abîmer  ppMS       abime     1
2763       accabler  ppMS      akable     1
2764       accabler  ppFS      akable     1
2971       accepter   inf     aksɛpte     1
3003       accepter  ppMS     aksɛpte     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3406    accompagner   inf    akɔ̃paɲe     1
3407    accompagner  fi3S  akɔ̃paɲəʁa     1
3432    accompagner  ai3P   akɔ̃paɲɛʁ     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     1
3443      accomplir   inf    akɔ̃pliʁ     1
3640       accoster  ii3S      akɔstɛ     1
4237      accrocher  ii3S      akʁɔʃɛ     1
4255      accrocher  pi3S       akʁɔʃ     2
4293      accrocher  ppFP      akʁɔʃe     1
4294      accrocher  ppMP      akʁɔʃe     1
4320      accroupir  ppMS      akʁupi     1
...             ...   ...         ...   ...
432390   épouvanter  pi3P     ɛpuvɑ̃t     1
432535     éprouver  ii1S      ɛpʁuvɛ     2
432549     éprouver  pi1S       ɛpʁuv     1
432695      épuiser  ppMP      ɛpɥize     1
433238   équivaloir  pi3S       ɛkivo     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ    19
434069         être  ii2S         ɛtɛ     1
434070         être  ii3S         ɛtɛ    66
434821      étendre   inf      ɛtɑ̃dʁ     1
434829      étendre  pi2S        ɛtɑ̃     1
434833      étendre  ppFS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     1
435444      étonner   inf       ɛtɔne     1
435500     étouffer  pi3S        ɛtuf     1
435749    étrangler  fi3S  ɛtʁɑ̃gləʁa     1
436201      étudier  pi3S       ɛtydi     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    28
436711     évaporer   inf     ɛvapɔʁe     1
437024     éventrer  ppMS     ɛvɑ̃tʁe     1
437285       éviter    pP      ɛvitɑ̃     1
437292       éviter  pi1S        ɛvit     1
437301       éviter   inf       ɛvite     2
437413      évoquer  ii3P       ɛvɔkɛ     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    14
437498         ôter    pP        ɔtɑ̃     1

[1934 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.1 s, total: 1min 37s
Wall time: 30.5 s

nbChunk 382
4200
1982

             lexeme  case       phono  tir1
40            avoir  pi3S           a    89
101        abaisser  ppMS       abɛse     1
132      abandonner   inf    abɑ̃dɔne     1
1116        abonner  ppMP       abɔne     1
1129        aborder  ii3P      abɔʁdɛ     1
1401        aboutir  ai3P      abutiʁ     1
1461         aboyer    pP     abwajɑ̃     1
2116       absoudre   inf      absudʁ     1
2818      accaparer  ppMS     akapaʁe     1
2964       accepter  pi1S      aksɛpt     2
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     2
3003       accepter  ppMS     aksɛpte     1
3144       acclamer  ppMS      aklame     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     2
3433    accompagner  ppMS    akɔ̃paɲe     1
3468      accomplir    pP  akɔ̃plisɑ̃     1
3530       accorder  pi3S       akɔʁd     1
3571       accorder  ppMS      akɔʁde     1
4159      accoutrer  ppMP      akutʁe     1
4255      accrocher  pi3S       akʁɔʃ     1
4257      accrocher  pi3P       akʁɔʃ     1
4293      accrocher  ppFP      akʁɔʃe     1
4322      accroupir  ppFP      akʁupi     1
4509     accueillir   inf      akəjiʁ     1
4750        accuser  ppFS       akyze     1
4823      accélérer  ii3S    aksɛlɛʁɛ     1
5119        acheter   inf       aʃəte     2
...             ...   ...         ...   ...
432160      épouser   inf       ɛpuze     1
432535     éprouver  ii1S      ɛpʁuvɛ     1
432586     éprouver  ppMS      ɛpʁuve     1
432689      épuiser  ppMS      ɛpɥize     1
432695      épuiser  ppMP      ɛpɥize     1
434048         être  ii3P         ɛtɛ     6
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    79
434730     éteindre  pi3P        ɛtɛɲ     1
434817      étendre  pc1S     ɛtɑ̃dʁɛ     1
434831      étendre  ppMS      ɛtɑ̃dy     1
434868    éterniser   inf    ɛtɛʁnize     1
435054         être  ii2P        ɛtje     2
435232       étirer  ai3S       ɛtiʁa     1
435282       étirer  pi2P       ɛtiʁe     1
435504     étouffer  pi3P        ɛtuf     1
435782    étrangler  ppFS    ɛtʁɑ̃gle     1
436316         être  ppMS         ɛte    28
436484       évader  ppMS       ɛvade     1
436513      évaluer  pi1S       ɛvaly     1
436649     évanouir  pi1S      ɛvanui     1
436867     éveiller  ppMS       ɛvɛje     1
437285       éviter    pP      ɛvitɑ̃     1
437295       éviter  pi3S        ɛvit     1
437299       éviter  pi3P        ɛvit     1
437328       éviter  ppMS       ɛvite     1
437431      évoquer   inf       ɛvɔke     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    21
437508         ôter  pi3S          ot     1

[1982 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.6 s, total: 1min 35s
Wall time: 30.2 s

nbChunk 383
4200
1956

             lexeme  case     phono  tir1
40            avoir  pi3S         a    86
128      abandonner  pi3S   abɑ̃dɔn     1
164      abandonner  ppMS  abɑ̃dɔne     1
2734       accabler  pi3P     akabl     1
2950       accepter  ii3S   aksɛptɛ     2
2967       accepter  pi3S    aksɛpt     1
2971       accepter   inf   aksɛpte     1
2984       accepter  pi2S    aksɛpt     1
3009       accepter  ppMP   aksɛpte     1
3132       acclamer  pI2P    aklame     1
3269        accoler  ii3S     akɔlɛ     1
3385    accompagner  ii3S  akɔ̃paɲɛ     2
3400    accompagner  pi3S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     1
3438      accomplir  ppMS   akɔ̃pli     1
4323      accroupir   inf   akʁupiʁ     2
4519     accueillir  ai3S     akəji     1
5043       acharner  ppFP    aʃaʁne     1
5119        acheter   inf     aʃəte     2
5136        acheter  ppMS     aʃəte     2
6540        adhérer    pP    adɛʁɑ̃     1
7191        adonner   inf     adɔne     1
7266        adopter  pi2P    adɔpte     1
7295         adorer  ii1S     adɔʁɛ     1
7298         adorer    pP    adɔʁɑ̃     1
7309         adorer  pi1S      adɔʁ     1
7316         adorer   inf     adɔʁe     1
7518       adresser  ai3S    adʁɛsa     1
7520       adresser  ii3P    adʁɛsɛ     1
8193        affaler  ai3S     afala     1
...             ...   ...       ...   ...
431795      éployer  pi3S     ɛplwa     1
432041    épouiller  ii3S     ɛpujɛ     1
432302      épouser  ppMS     ɛpuze     1
432537     éprouver  ii3S    ɛpʁuvɛ     1
432552     éprouver  pi3S     ɛpʁuv     1
432588     éprouver  ppFS    ɛpʁuve     1
433790      éructer  pi3S     ɛʁykt     1
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ    15
434070         être  ii3S       ɛtɛ    65
434821      étendre   inf    ɛtɑ̃dʁ     1
434831      étendre  ppMS    ɛtɑ̃dy     2
435135      étioler   inf    ɛtjɔle     1
435251       étirer  pi1S      ɛtiʁ     1
435294       étirer  ppFS     ɛtiʁe     1
435444      étonner   inf     ɛtɔne     1
435500     étouffer  pi3S      ɛtuf     1
435506     étouffer   inf     ɛtufe     1
435742    étrangler  pi3S   ɛtʁɑ̃gl     1
435794    étreindre  ii3S    ɛtʁɛɲɛ     1
436201      étudier  pi3S     ɛtydi     2
436316         être  ppMS       ɛte    21
436629     évanouir  ppFS    ɛvanui     1
436820     éveiller  ii3S     ɛvɛjɛ     2
437301       éviter   inf     ɛvite     4
437416      évoquer  ii3S     ɛvɔkɛ     1
437427      évoquer  pi3S      ɛvɔk     1
437474         être  pi2P        ɛt     7
437476         être   inf       ɛtʁ    19
437498         ôter    pP      ɔtɑ̃     1

[1956 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.3 s, total: 1min 34s
Wall time: 30.2 s

nbChunk 384
4200
1964

             lexeme  case       phono  tir1
40            avoir  pi3S           a    87
132      abandonner   inf    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     2
243         abattre  pi3S         aba     1
305         abattre  ppMS       abaty     1
982         abonder  pi3P       abɔ̃d     1
1684        abriter  pi3S       abʁit     1
1686        abriter  pi3P       abʁit     1
1796        abrutir  ppMS      abʁyti     1
2339         abuser   inf       abyze     1
2581         abîmer   inf       abime     1
2939       accepter  ai3S     aksɛpta     1
2971       accepter   inf     aksɛpte     2
3382    accompagner  ii3P    akɔ̃paɲɛ     1
3413    accompagner  fi2S  akɔ̃paɲəʁa     1
3655       accoster   inf      akɔste     1
3913       accouder  ppMS       akude     1
4291      accrocher  ppMS      akʁɔʃe     1
4373      accroître  pi3S       akʁwa     1
4509     accueillir   inf      akəjiʁ     1
4688        accuser  ai3S       akyza     1
4713        accuser  pi1S        akyz     1
4812      accélérer  pi3S     aksɛlɛʁ     1
4835      accélérer   inf    aksɛlɛʁe     1
5042       acharner  ppFS      aʃaʁne     1
5136        acheter  ppMS       aʃəte     1
5139        acheter  ppMP       aʃəte     1
5311        acheter  pi3S        aʃɛt     1
6443        adapter  ppMS      adapte     1
6991        admirer  pi3S       admiʁ     1
...             ...   ...         ...   ...
433922      établir   inf     ɛtabliʁ     2
433930      établir  ai3P     ɛtabliʁ     1
433959      établir  pi2P    ɛtablise     1
434048         être  ii3P         ɛtɛ     5
434068         être  ii1S         ɛtɛ    21
434070         être  ii3S         ɛtɛ    59
434451     étancher   inf      ɛtɑ̃ʃe     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434768     éteindre  pi1S        ɛtɛ̃     1
434773     éteindre  pi3S        ɛtɛ̃     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434811      étendre  ai3S      ɛtɑ̃di     1
434831      étendre  ppMS      ɛtɑ̃dy     1
434853    éterniser  ii3S    ɛtɛʁnizɛ     1
434898    éterniser  ppMP    ɛtɛʁnize     1
435054         être  ii2P        ɛtje     1
435074    étinceler   inf    ɛtɛ̃səle     1
435172         être  ii1P       ɛtjɔ̃     1
435444      étonner   inf       ɛtɔne     1
435471      étonner  ppMS       ɛtɔne     1
435472      étonner  ppFS       ɛtɔne     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    24
436835     éveiller   inf       ɛvɛje     1
437301       éviter   inf       ɛvite     1
437305       éviter  pc1S     ɛvitəʁɛ     1
437367      évoluer   inf      ɛvɔlye     1
437474         être  pi2P          ɛt    11
437476         être   inf         ɛtʁ    18

[1964 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.9 s, total: 1min 35s
Wall time: 29.9 s

nbChunk 385
4200
1944

             lexeme  case      phono  tir1
40            avoir  pi3S          a    81
108      abandonner  ai3S   abɑ̃dɔna     1
114      abandonner    pP  abɑ̃dɔnɑ̃     1
148      abandonner  pi2P   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     1
258         abattre  ii3S      abatɛ     1
299         abattre   inf      abatʁ     1
305         abattre  ppMS      abaty     1
396        abdiquer  ai3S     abdika     1
890          abolir   inf     abɔliʁ     1
1884        abréger   inf     abʁɛʒe     1
2878      accentuer  ai3S   aksɑ̃tya     1
2887      accentuer  ii3S   aksɑ̃tyɛ     1
2964       accepter  pi1S     aksɛpt     1
2971       accepter   inf    aksɛpte     1
2977       accepter  pc3S  aksɛptəʁɛ     1
3003       accepter  ppMS    aksɛpte     1
3082     accidenter  ppMS  aksidɑ̃te     1
3404    accompagner  pi3P    akɔ̃paɲ     1
3438      accomplir  ppMS    akɔ̃pli     1
3536       accorder   inf     akɔʁde     1
3583       accorder  ppMP     akɔʁde     1
4294      accrocher  ppMP     akʁɔʃe     1
4652      accumuler  pi3S     akymyl     1
4716        accuser  pi3S       akyz     1
4812      accélérer  pi3S    aksɛlɛʁ     1
5054      acheminer    pP   aʃəminɑ̃     1
5111        acheter  ii3S      aʃətɛ     1
5119        acheter   inf      aʃəte     2
5165        achever  pi1P     aʃəvɔ̃     1
...             ...   ...        ...   ...
433922      établir   inf    ɛtabliʁ     2
433969      établir  pi3S     ɛtabli     1
434048         être  ii3P        ɛtɛ     1
434068         être  ii1S        ɛtɛ     7
434070         être  ii3S        ɛtɛ    78
434727     éteindre    pP     ɛtɛɲɑ̃     1
434773     éteindre  pi3S       ɛtɛ̃     1
434775     éteindre  ppFS      ɛtɛ̃t     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434811      étendre  ai3S     ɛtɑ̃di     1
434821      étendre   inf     ɛtɑ̃dʁ     2
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     2
435422      étonner  ii3S      ɛtɔnɛ     1
435484     étouffer  ii3S      ɛtufɛ     1
435684     étourdir  ii3S   ɛtuʁdisɛ     1
435780    étrangler  ppMS   ɛtʁɑ̃gle     1
436201      étudier  pi3S      ɛtydi     2
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    20
436520      évaluer   inf     ɛvalye     1
436660     évanouir  ps3S    ɛvanuis     1
437281       éviter  ii3P      ɛvitɛ     1
437282       éviter  ii1S      ɛvitɛ     1
437295       éviter  pi3S       ɛvit     1
437301       éviter   inf      ɛvite     2
437447      évoquer  pi2P      ɛvɔke     1
437474         être  pi2P         ɛt    14
437476         être   inf        ɛtʁ    16
437508         ôter  pi3S         ot     1

[1944 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.8 s, total: 1min 36s
Wall time: 29.8 s

nbChunk 386
4200
1957

             lexeme  case      phono  tir1
40            avoir  pi3S          a    94
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
313         abattre  ppMP      abaty     1
869          aboyer  pi3P       abwa     1
955         abonder  ii3P     abɔ̃dɛ     1
1147        aborder   inf     abɔʁde     2
1178        aborder  ppMP     abɔʁde     1
1468         aboyer   inf     abwaje     1
2100       absorber  ppMS    absɔʁbe     1
2104       absorber  ppFP    absɔʁbe     1
2355         abuser  pi2P      abyze     1
2952       accepter    pP   aksɛptɑ̃     1
2971       accepter   inf    aksɛpte     1
2975       accepter  pc1S  aksɛptəʁɛ     1
2997       accepter  pi1P   aksɛptɔ̃     3
3003       accepter  ppMS    aksɛpte     1
3397    accompagner  pi1S    akɔ̃paɲ     1
3400    accompagner  pi3S    akɔ̃paɲ     2
3433    accompagner  ppMS   akɔ̃paɲe     1
3434    accompagner  ppFS   akɔ̃paɲe     1
3443      accomplir   inf   akɔ̃pliʁ     1
3475      accomplir  pi3P   akɔ̃plis     1
3490      accomplir  pi3S    akɔ̃pli     1
3536       accorder   inf     akɔʁde     2
3549       accorder  pi2S      akɔʁd     1
4234      accrocher  ii3P     akʁɔʃɛ     1
4291      accrocher  ppMS     akʁɔʃe     1
4293      accrocher  ppFP     akʁɔʃe     1
4294      accrocher  ppMP     akʁɔʃe     1
...             ...   ...        ...   ...
432181      épouser  pi2P      ɛpuze     1
432533     éprouver  ai1S     ɛpʁuvɛ     1
432552     éprouver  pi3S      ɛpʁuv     1
432586     éprouver  ppMS     ɛpʁuve     1
433926      établir  pc1S   ɛtabliʁɛ     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ    13
434070         être  ii3S        ɛtɛ    79
434072       étaler  ai3S      ɛtala     1
434488         être    pP       ɛtɑ̃     1
434773     éteindre  pi3S       ɛtɛ̃     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
434821      étendre   inf     ɛtɑ̃dʁ     1
434831      étendre  ppMS     ɛtɑ̃dy     1
434833      étendre  ppFS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     1
435240       étirer  ii3P      ɛtiʁɛ     1
435438      étonner  pi3S       ɛtɔn     1
435471      étonner  ppMS      ɛtɔne     1
435742    étrangler  pi3S    ɛtʁɑ̃gl     1
436201      étudier  pi3S      ɛtydi     1
436205      étudier   inf     ɛtydje     1
436316         être  ppMS        ɛte    31
436627     évanouir  ppMS     ɛvanui     1
436835     éveiller   inf      ɛvɛje     1
437301       éviter   inf      ɛvite     2
437458      évoquer  ppMS      ɛvɔke     1
437474         être  pi2P         ɛt     8
437476         être   inf        ɛtʁ    19

[1957 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.3 s, total: 1min 39s
Wall time: 30.1 s

nbChunk 387
4200
1951

            lexeme  case     phono  tir1
40           avoir  pi3S         a    86
132     abandonner   inf  abɑ̃dɔne     1
148     abandonner  pi2P  abɑ̃dɔne     1
891         abolir  fi3S   abɔliʁa     1
1425       aboutir  pi3P    abutis     1
1440       aboutir  pi3S     abuti     1
1796       abrutir  ppMS    abʁyti     1
1859       abréger  pi3S     abʁɛʒ     1
2066      absorber  pi3S    absɔʁb     1
2339        abuser   inf     abyze     1
2574        abîmer  pi1S      abim     1
2887     accentuer  ii3S  aksɑ̃tyɛ     1
2946      accepter  ai1S   aksɛptɛ     1
2967      accepter  pi3S    aksɛpt     1
2971      accepter   inf   aksɛpte     1
3376    accommoder  ppMS   akɔmɔde     1
3438     accomplir  ppMS   akɔ̃pli     1
3440     accomplir  ppFS   akɔ̃pli     1
3527      accorder  pi1S     akɔʁd     2
3530      accorder  pi3S     akɔʁd     1
3536      accorder   inf    akɔʁde     1
3573      accorder  ppFS    akɔʁde     1
3821     accoucher  pi3S      akuʃ     1
3847     accoucher  pi2P     akuʃe     1
4259     accrocher   inf    akʁɔʃe     1
4323     accroupir   inf   akʁupiʁ     1
4519    accueillir  ai3S     akəji     1
4548       acculer  fi3S   akyləʁa     1
4684     accumuler  ppFS   akymyle     1
4997      acharner  ii3S    aʃaʁnɛ     1
...            ...   ...       ...   ...
427624    éloigner  ii3S    ɛlwaɲɛ     1
427641    éloigner   inf    ɛlwaɲe     1
427669    éloigner  ppFS    ɛlwaɲe     1
429367    émouvoir  ppFS       ɛmy     1
429691     énerver  pi1S     ɛnɛʁv     1
431065       épier    pP     ɛpjɑ̃     1
432160     épouser   inf     ɛpuze     2
432562    éprouver  pc3S  ɛpʁuvəʁɛ     1
432588    éprouver  ppFS    ɛpʁuve     1
432689     épuiser  ppMS    ɛpɥize     1
433912     établir  ppMS    ɛtabli     3
434048        être  ii3P       ɛtɛ     2
434068        être  ii1S       ɛtɛ     9
434070        être  ii3S       ɛtɛ    64
434301      étaler  ppFP     ɛtale     1
434811     étendre  ai3S    ɛtɑ̃di     1
434821     étendre   inf    ɛtɑ̃dʁ     1
434831     étendre  ppMS    ɛtɑ̃dy     1
434833     étendre  ppFS    ɛtɑ̃dy     1
435054        être  ii2P      ɛtje     1
435172        être  ii1P     ɛtjɔ̃     3
436233     étudier  ppMS    ɛtydje     1
436235     étudier  ppFS    ɛtydje     1
436316        être  ppMS       ɛte    30
436679    évanouir  pi3S    ɛvanui     1
436890     éventer    pP   ɛvɑ̃tɑ̃     1
437024    éventrer  ppMS   ɛvɑ̃tʁe     1
437474        être  pi2P        ɛt    11
437476        être   inf       ɛtʁ    23
437539        ôter  ppMS       ɔte     1

[1951 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.4 s, total: 1min 40s
Wall time: 30.3 s

nbChunk 388
4200
1960

             lexeme  case       phono  tir1
40            avoir  pi3S           a    79
108      abandonner  ai3S    abɑ̃dɔna     1
128      abandonner  pi3S     abɑ̃dɔn     1
890          abolir   inf      abɔliʁ     1
1164        aborder  ii2P     abɔʁdje     1
2133       abstenir  ii1S     abstənɛ     1
2324         abuser  ii3S       abyzɛ     1
2332         abuser  pi1S        abyz     1
2335         abuser  pi3S        abyz     1
2971       accepter   inf     aksɛpte     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3406    accompagner   inf    akɔ̃paɲe     1
3408    accompagner  fi1S  akɔ̃paɲəʁɛ     1
3433    accompagner  ppMS    akɔ̃paɲe     2
3530       accorder  pi3S       akɔʁd     1
3536       accorder   inf      akɔʁde     1
3538       accorder  fi1S    akɔʁdəʁɛ     1
3549       accorder  pi2S       akɔʁd     1
3655       accoster   inf      akɔste     1
4090       accourir  pi3S        akuʁ     1
4257      accrocher  pi3P       akʁɔʃ     1
4656      accumuler   inf     akymyle     1
4748        accuser  ppMS       akyze     1
4750        accuser  ppFS       akyze     1
5102        acheter  ai3S       aʃəta     1
5119        acheter   inf       aʃəte     2
5137        acheter  ppFS       aʃəte     1
5147        achever  ii1S       aʃəvɛ     1
5311        acheter  pi3S        aʃɛt     1
6054        activer    pP     aktivɑ̃     1
...             ...   ...         ...   ...
432160      épouser   inf       ɛpuze     3
432554     éprouver  pi3P       ɛpʁuv     1
433969      établir  pi3S      ɛtabli     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    15
434070         être  ii3S         ɛtɛ    86
434072       étaler  ai3S       ɛtala     1
434134       étaler  ii3S       ɛtalɛ     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434811      étendre  ai3S      ɛtɑ̃di     1
434821      étendre   inf      ɛtɑ̃dʁ     3
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     3
435295       étirer  ppFP       ɛtiʁe     1
435438      étonner  pi3S        ɛtɔn     1
435445      étonner  fi3S     ɛtɔnəʁa     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435481     étouffer  ii3P       ɛtufɛ     1
436205      étudier   inf      ɛtydje     2
436218      étudier  pi2S       ɛtydi     1
436221      étudier  pi2P      ɛtydje     1
436233      étudier  ppMS      ɛtydje     2
436316         être  ppMS         ɛte    18
437292       éviter  pi1S        ɛvit     1
437416      évoquer  ii3S       ɛvɔkɛ     3
437427      évoquer  pi3S        ɛvɔk     2
437431      évoquer   inf       ɛvɔke     1
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    18
437539         ôter  ppMS         ɔte     1

[1960 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 22.1 s, total: 1min 37s
Wall time: 30.3 s

nbChunk 389
4200
1968

             lexeme  case      phono  tir1
40            avoir  pi3S          a    71
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     1
1393        aboutir   inf     abutiʁ     1
1684        abriter  pi3S      abʁit     1
2143       abstenir   inf   abstəniʁ     1
2730       accabler  pi3S      akabl     1
2878      accentuer  ai3S   aksɑ̃tya     1
2978       accepter  fi2S  aksɛptəʁa     1
3003       accepter  ppMS    aksɛpte     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     1
4279      accrocher  pI2P     akʁɔʃe     1
4291      accrocher  ppMS     akʁɔʃe     1
4509     accueillir   inf     akəjiʁ     2
4684      accumuler  ppFS    akymyle     1
4716        accuser  pi3S       akyz     1
4754        accuser  ppMP      akyze     1
5119        acheter   inf      aʃəte     1
5125        acheter  pi2P      aʃəte     1
5136        acheter  ppMS      aʃəte     2
5311        acheter  pi3S       aʃɛt     1
5316        acheter  fi1S    aʃɛtəʁɛ     1
5332        achever  pi3S       aʃɛv     1
5997      actionner  ii3S    aksjɔnɛ     1
6801        adjuger  ppMS     adʒyʒe     1
6863       admettre  pi1S       admɛ     1
6891       admettre   inf     admɛtʁ     1
6996        admirer   inf     admiʁe     1
7250        adopter   inf     adɔpte     1
...             ...   ...        ...   ...
431261       épiler  pi3S       ɛpil     1
431871     éplucher   inf     ɛplyʃe     1
432182      épouser  ii2P     ɛpuzje     1
432421   épouvanter  ppFS   ɛpuvɑ̃te     1
432535     éprouver  ii1S     ɛpʁuvɛ     1
432556     éprouver   inf     ɛpʁuve     2
432586     éprouver  ppMS     ɛpʁuve     1
432689      épuiser  ppMS     ɛpɥize     1
432693      épuiser  ppFP     ɛpɥize     1
434048         être  ii3P        ɛtɛ     1
434068         être  ii1S        ɛtɛ    14
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    74
434762     éteindre   inf     ɛtɛ̃dʁ     1
434821      étendre   inf     ɛtɑ̃dʁ     1
435054         être  ii2P       ɛtje     1
435172         être  ii1P      ɛtjɔ̃     5
435232       étirer  ai3S      ɛtiʁa     1
435295       étirer  ppFP      ɛtiʁe     1
435417      étonner  ai3S      ɛtɔna     1
435422      étonner  ii3S      ɛtɔnɛ     1
435425      étonner    pP     ɛtɔnɑ̃     1
435437      étonner  pI2S       ɛtɔn     1
435500     étouffer  pi3S       ɛtuf     1
436316         être  ppMS        ɛte    27
436627     évanouir  ppMS     ɛvanui     1
436629     évanouir  ppFS     ɛvanui     1
437282       éviter  ii1S      ɛvitɛ     1
437474         être  pi2P         ɛt    11
437476         être   inf        ɛtʁ    20

[1968 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22 s, total: 1min 39s
Wall time: 29.9 s

nbChunk 390
4200
1950

             lexeme  case       phono  tir1
40            avoir  pi3S           a    72
109      abandonner  ai1S    abɑ̃dɔnɛ     1
113      abandonner  ii3S    abɑ̃dɔnɛ     2
132      abandonner   inf    abɑ̃dɔne     1
585        abhorrer  pi3S        abɔʁ     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     1
3380    accompagner  ai3S    akɔ̃paɲa     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3443      accomplir   inf    akɔ̃pliʁ     2
3530       accorder  pi3S       akɔʁd     1
3878       accouder  pi3S        akud     1
4238      accrocher    pP     akʁɔʃɑ̃     1
4255      accrocher  pi3S       akʁɔʃ     1
4259      accrocher   inf      akʁɔʃe     1
4510     accueillir  ai3P      akəjiʁ     1
4683      accumuler  ppMS     akymyle     1
4783        accéder   inf      aksɛde     1
5102        acheter  ai3S       aʃəta     1
5136        acheter  ppMS       aʃəte     2
5146        achever  ii3P       aʃəvɛ     1
5234       achopper  ppFS       aʃɔpe     1
5754       acquérir  pi3S       akjɛʁ     1
5905       acquérir   inf      akɛʁiʁ     1
6883       admettre  pi1P     admɛtɔ̃     1
6928    administrer   inf  administʁe     1
6969        admirer  ii3S      admiʁɛ     1
6996        admirer   inf      admiʁe     2
7046       admettre  ai3S        admi     1
...             ...   ...         ...   ...
432537     éprouver  ii3S      ɛpʁuvɛ     1
432556     éprouver   inf      ɛpʁuve     2
433922      établir   inf     ɛtabliʁ     1
434039       étager  ppMP       ɛtaʒe     1
434048         être  ii3P         ɛtɛ     2
434068         être  ii1S         ɛtɛ     9
434070         être  ii3S         ɛtɛ    74
434135       étaler    pP      ɛtalɑ̃     1
434147       étaler  pi3S        ɛtal     1
434151       étaler  pi3P        ɛtal     1
434488         être    pP        ɛtɑ̃     1
434785      étendre  ii3P      ɛtɑ̃dɛ     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434831      étendre  ppMS      ɛtɑ̃dy     1
434836      étendre  ppFP      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     1
435422      étonner  ii3S       ɛtɔnɛ     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435838    étreindre  pi3S       ɛtʁɛ̃     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    23
436405      évacuer  pc3P     ɛvakyʁɛ     1
436632     évanouir   inf     ɛvanuiʁ     1
436865     éveiller  ai3P      ɛvɛjɛʁ     1
437301       éviter   inf       ɛvite     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437474         être  pi2P          ɛt     9
437476         être   inf         ɛtʁ    14
437497         ôter  ii3S         ɔtɛ     1

[1950 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.8 s, total: 1min 35s
Wall time: 29.2 s

nbChunk 391
4200
1913

             lexeme  case     phono  tir1
40            avoir  pi3S         a    90
164      abandonner  ppMS  abɑ̃dɔne     3
166      abandonner  ppFS  abɑ̃dɔne     1
1147        aborder   inf    abɔʁde     1
1393        aboutir   inf    abutiʁ     1
1440        aboutir  pi3S     abuti     1
1674        abriter    pP   abʁitɑ̃     1
2102       absorber  ppFS   absɔʁbe     1
2506         abêtir   inf    abɛtiʁ     1
2715       accabler  ii3S    akablɛ     1
2902      accentuer  pi3P   aksɑ̃ty     1
3382    accompagner  ii3P  akɔ̃paɲɛ     1
3406    accompagner   inf  akɔ̃paɲe     1
3490      accomplir  pi3S   akɔ̃pli     1
3655       accoster   inf    akɔste     1
4255      accrocher  pi3S     akʁɔʃ     1
4259      accrocher   inf    akʁɔʃe     2
4369      accroupir  pi3S    akʁupi     2
4509     accueillir   inf    akəjiʁ     1
4521     accueillir  pi1P    akəjɔ̃     1
4750        accuser  ppFS     akyze     1
4783        accéder   inf    aksɛde     1
4812      accélérer  pi3S   aksɛlɛʁ     1
5119        acheter   inf     aʃəte     3
5136        acheter  ppMS     aʃəte     1
5157        achever   inf     aʃəve     1
5311        acheter  pi3S      aʃɛt     1
6891       admettre   inf    admɛtʁ     2
6959        admirer  ai3S    admiʁa     1
6991        admirer  pi3S     admiʁ     1
...             ...   ...       ...   ...
432160      épouser   inf     ɛpuze     1
432638      épuiser  ii3S    ɛpɥizɛ     1
432653      épuiser  pi3S     ɛpɥiz     1
432691      épuiser  ppFS    ɛpɥize     1
433308      érafler  ii3S    ɛʁaflɛ     1
433617       ériger  ppMS     ɛʁiʒe     1
433912      établir  ppMS    ɛtabli     2
433914      établir  ppFS    ɛtabli     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     5
434068         être  ii1S       ɛtɛ    10
434070         être  ii3S       ɛtɛ    79
434768     éteindre  pi1S      ɛtɛ̃     1
434782      étendre  pi3S      ɛtɑ̃     1
434811      étendre  ai3S    ɛtɑ̃di     1
435054         être  ii2P      ɛtje     1
435417      étonner  ai3S     ɛtɔna     1
435540     étouffer  ppFS     ɛtufe     1
435654     étourdir  ppMS    ɛtuʁdi     1
435711     étourdir  pi3S    ɛtuʁdi     1
436198      étudier  pi1S     ɛtydi     2
436227      étudier  pi1P   ɛtydjɔ̃     1
436316         être  ppMS       ɛte    24
436815     éveiller  ai3S     ɛvɛja     1
436867     éveiller  ppMS     ɛvɛje     1
437301       éviter   inf     ɛvite     2
437407      évoluer  ppMS    ɛvɔlye     1
437427      évoquer  pi3S      ɛvɔk     1
437474         être  pi2P        ɛt    14
437476         être   inf       ɛtʁ    12

[1913 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.3 s, total: 1min 39s
Wall time: 30.1 s

nbChunk 392
4200
1940

             lexeme  case     phono  tir1
40            avoir  pi3S         a    90
132      abandonner   inf  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     1
166      abandonner  ppFS  abɑ̃dɔne     1
305         abattre  ppMS     abaty     1
1143        aborder  pi3S     abɔʁd     1
1703        abriter  pI2P    abʁite     1
2051       absorber  ii3S   absɔʁbɛ     1
2337         abuser  pi3P      abyz     1
2939       accepter  ai3S   aksɛpta     1
2947       accepter  ii3P   aksɛptɛ     1
2967       accepter  pi3S    aksɛpt     2
2971       accepter   inf   aksɛpte     1
3003       accepter  ppMS   aksɛpte     1
3144       acclamer  ppMS    aklame     1
3382    accompagner  ii3P  akɔ̃paɲɛ     1
3385    accompagner  ii3S  akɔ̃paɲɛ     1
3397    accompagner  pi1S   akɔ̃paɲ     1
3422    accompagner  pi2P  akɔ̃paɲe     1
3433    accompagner  ppMS  akɔ̃paɲe     1
3443      accomplir   inf  akɔ̃pliʁ     1
4255      accrocher  pi3S     akʁɔʃ     1
4280      accrocher  pi2P    akʁɔʃe     1
4292      accrocher  ppFS    akʁɔʃe     1
4321      accroupir  ppFS    akʁupi     1
4368      accroupir  ai3S    akʁupi     1
4369      accroupir  pi3S    akʁupi     1
4491     accueillir  pc3S   akəjəʁɛ     1
4748        accuser  ppMS     akyze     1
4835      accélérer   inf  aksɛlɛʁe     1
...             ...   ...       ...   ...
427920       élever  pi1S      ɛlɛv     1
428214    émanciper   inf  ɛmɑ̃sipe     1
428390      émerger  pi1S     ɛmɛʁʒ     1
428609      émettre  pi3S       ɛmɛ     1
429277     émousser  ppFP     ɛmuse     1
429728      énerver  ppFS    ɛnɛʁve     1
430183     épaissir    pP  ɛpɛsisɑ̃     1
432160      épouser   inf     ɛpuze     1
432302      épouser  ppMS     ɛpuze     1
432552     éprouver  pi3S     ɛpʁuv     1
434048         être  ii3P       ɛtɛ     2
434068         être  ii1S       ɛtɛ    10
434070         être  ii3S       ɛtɛ    89
434726     éteindre  ii3S     ɛtɛɲɛ     1
434785      étendre  ii3P    ɛtɑ̃dɛ     1
434788      étendre  ii3S    ɛtɑ̃dɛ     1
434804      étendre  ai1S    ɛtɑ̃di     1
434831      étendre  ppMS    ɛtɑ̃dy     1
435172         être  ii1P     ɛtjɔ̃     3
435244       étirer    pP    ɛtiʁɑ̃     1
435729    étrangler  ii1S  ɛtʁɑ̃glɛ     1
436205      étudier   inf    ɛtydje     2
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    21
436627     évanouir  ppMS    ɛvanui     1
437273       éviter  ai3S     ɛvita     1
437301       éviter   inf     ɛvite     1
437416      évoquer  ii3S     ɛvɔkɛ     1
437474         être  pi2P        ɛt    18
437476         être   inf       ɛtʁ    21

[1940 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.2 s, total: 1min 39s
Wall time: 30.4 s

nbChunk 393
4200
1968

             lexeme  case       phono  tir1
40            avoir  pi3S           a    83
67         abaisser  pi3S        abɛs     1
128      abandonner  pi3S     abɑ̃dɔn     1
133      abandonner  fi3S  abɑ̃dɔnəʁa     1
147      abandonner  pI2P    abɑ̃dɔne     1
164      abandonner  ppMS    abɑ̃dɔne     1
307         abattre  ppFS       abaty     1
1160        aborder  pi2S       abɔʁd     1
2612         abîmer  ppFS       abime     1
2712       accabler  ii3P      akablɛ     1
2766       accabler  ppMP      akable     1
2967       accepter  pi3S      aksɛpt     1
2972       accepter  fi3S   aksɛptəʁa     1
3380    accompagner  ai3S    akɔ̃paɲa     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3443      accomplir   inf    akɔ̃pliʁ     1
3536       accorder   inf      akɔʁde     1
3571       accorder  ppMS      akɔʁde     1
4234      accrocher  ii3P      akʁɔʃɛ     1
4255      accrocher  pi3S       akʁɔʃ     1
4259      accrocher   inf      akʁɔʃe     1
4292      accrocher  ppFS      akʁɔʃe     1
4509     accueillir   inf      akəjiʁ     1
4684      accumuler  ppFS     akymyle     1
5054      acheminer    pP    aʃəminɑ̃     1
5119        acheter   inf       aʃəte     3
5136        acheter  ppMS       aʃəte     2
5171        achever  ppMS       aʃəve     1
5308        acheter  pi1S        aʃɛt     1
...             ...   ...         ...   ...
432535     éprouver  ii1S      ɛpʁuvɛ     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
432549     éprouver  pi1S       ɛpʁuv     1
433174      équiper  ppMP       ɛkipe     1
434004       étager  pi3P        ɛtaʒ     1
434048         être  ii3P         ɛtɛ     1
434068         être  ii1S         ɛtɛ    10
434070         être  ii3S         ɛtɛ    87
434727     éteindre    pP      ɛtɛɲɑ̃     1
434770     éteindre  pi2S        ɛtɛ̃     1
434782      étendre  pi3S        ɛtɑ̃     1
435054         être  ii2P        ɛtje     2
435172         être  ii1P       ɛtjɔ̃     1
435251       étirer  pi1S        ɛtiʁ     1
435417      étonner  ai3S       ɛtɔna     1
435438      étonner  pi3S        ɛtɔn     1
435482     étouffer  ii1S       ɛtufɛ     1
435497     étouffer  pi1S        ɛtuf     1
435507     étouffer  fi3S     ɛtufəʁa     1
436188      étudier    pP     ɛtydjɑ̃     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    23
436980     éventrer  ii3S     ɛvɑ̃tʁɛ     1
437285       éviter    pP      ɛvitɑ̃     1
437301       éviter   inf       ɛvite     1
437328       éviter  ppMS       ɛvite     1
437427      évoquer  pi3S        ɛvɔk     1
437474         être  pi2P          ɛt    16
437476         être   inf         ɛtʁ    23
437540         ôter  ppFS         ɔte     1

[1968 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.5 s, total: 1min 36s
Wall time: 28.9 s

nbChunk 394
4200
1882

             lexeme  case       phono  tir1
40            avoir  pi3S           a    90
108      abandonner  ai3S    abɑ̃dɔna     1
128      abandonner  pi3S     abɑ̃dɔn     1
145      abandonner  pi2S     abɑ̃dɔn     1
264         abattre  pi3P        abat     1
933          abolir  ai3S       abɔli     1
1143        aborder  pi3S       abɔʁd     1
1417        aboutir    pP    abutisɑ̃     1
1673        abriter  ii3S      abʁitɛ     1
1688        abriter   inf      abʁite     1
1716        abriter  ppMS      abʁite     1
2070       absorber   inf     absɔʁbe     1
2610         abîmer  ppMS       abime     1
2766       accabler  ppMP      akable     1
2939       accepter  ai3S     aksɛpta     1
2967       accepter  pi3S      aksɛpt     1
2971       accepter   inf     aksɛpte     2
2980       accepter  pc2P  aksɛptəʁje     1
2997       accepter  pi1P    aksɛptɔ̃     1
3003       accepter  ppMS     aksɛpte     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3397    accompagner  pi1S     akɔ̃paɲ     1
3400    accompagner  pi3S     akɔ̃paɲ     2
3433    accompagner  ppMS    akɔ̃paɲe     1
3443      accomplir   inf    akɔ̃pliʁ     1
3531       accorder  ps3S       akɔʁd     1
4230      accrocher  ai3S      akʁɔʃa     1
4547        acculer   inf       akyle     1
4720        accuser   inf       akyze     1
5012       acharner  pi3P       aʃaʁn     1
...             ...   ...         ...   ...
429800      énoncer   inf      ɛnɔ̃se     1
430340     épancher   inf      ɛpɑ̃ʃe     1
430485     épanouir   inf     ɛpanuiʁ     1
431575     épingler   inf     ɛpɛ̃gle     1
432160      épouser   inf       ɛpuze     2
432537     éprouver  ii3S      ɛpʁuvɛ     1
432553     éprouver  ps3S       ɛpʁuv     1
432556     éprouver   inf      ɛpʁuve     1
432635      épuiser  ii3P      ɛpɥizɛ     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    14
434069         être  ii2S         ɛtɛ     1
434070         être  ii3S         ɛtɛ    82
434770     éteindre  pi2S        ɛtɛ̃     1
434773     éteindre  pi3S        ɛtɛ̃     1
434782      étendre  pi3S        ɛtɑ̃     1
434788      étendre  ii3S      ɛtɑ̃dɛ     1
434833      étendre  ppFS      ɛtɑ̃dy     1
435172         être  ii1P       ɛtjɔ̃     1
435306      étoffer  ii3S       ɛtɔfɛ     1
435536     étouffer  ai3P      ɛtufɛʁ     1
435837    étreindre  ppMS       ɛtʁɛ̃     1
436181      étudier  ai3S      ɛtydja     1
436233      étudier  ppMS      ɛtydje     1
436316         être  ppMS         ɛte    23
436867     éveiller  ppMS       ɛvɛje     1
437301       éviter   inf       ɛvite     3
437474         être  pi2P          ɛt    13
437476         être   inf         ɛtʁ    19

[1882 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.4 s, total: 1min 39s
Wall time: 30.1 s

nbChunk 395
4200
1956

             lexeme  case     phono  tir1
40            avoir  pi3S         a    96
113      abandonner  ii3S  abɑ̃dɔnɛ     1
145      abandonner  pi2S   abɑ̃dɔn     1
177      abasourdir  ppMS  abazuʁdi     1
272         abattre  pi2P     abate     1
1129        aborder  ii3P    abɔʁdɛ     1
1571       abreuver   inf    abʁəve     1
2070       absorber   inf   absɔʁbe     1
2335         abuser  pi3S      abyz     1
2371         abuser  ppMS     abyze     1
2971       accepter   inf   aksɛpte     2
3343     accommoder  pi3S    akɔmɔd     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3443      accomplir   inf  akɔ̃pliʁ     1
3534       accorder  pi3P     akɔʁd     1
3571       accorder  ppMS    akɔʁde     1
3737        accoter  ppMS     akɔte     1
4255      accrocher  pi3S     akʁɔʃ     1
4291      accrocher  ppMS    akʁɔʃe     1
4293      accrocher  ppFP    akʁɔʃe     1
4320      accroupir  ppMS    akʁupi     1
4720        accuser   inf     akyze     1
4835      accélérer   inf  aksɛlɛʁe     1
5119        acheter   inf     aʃəte     1
5136        acheter  ppMS     aʃəte     1
5171        achever  ppMS     aʃəve     1
5311        acheter  pi3S      aʃɛt     1
5316        acheter  fi1S   aʃɛtəʁɛ     1
6801        adjuger  ppMS    adʒyʒe     1
6882       admettre  pI1P   admɛtɔ̃     1
...             ...   ...       ...   ...
433238   équivaloir  pi3S     ɛkivo     1
433645       éroder  pi3S      ɛʁɔd     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ    15
434070         être  ii3S       ɛtɛ    81
434729     éteindre  ps3S      ɛtɛɲ     1
434747     éteindre  ai3S     ɛtɛɲi     1
434773     éteindre  pi3S      ɛtɛ̃     1
434836      étendre  ppFP    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     1
435232       étirer  ai3S     ɛtiʁa     1
435244       étirer    pP    ɛtiʁɑ̃     1
435438      étonner  pi3S      ɛtɔn     2
435506     étouffer   inf     ɛtufe     2
435538     étouffer  ppMS     ɛtufe     1
436205      étudier   inf    ɛtydje     1
436233      étudier  ppMS    ɛtydje     1
436316         être  ppMS       ɛte    25
436402      évacuer   inf    ɛvakye     1
436454       évader  ps3S      ɛvad     1
436547      évaluer  ppMS    ɛvalye     1
436629     évanouir  ppFS    ɛvanui     1
436833     éveiller  pi3P      ɛvɛj     1
437295       éviter  pi3S      ɛvit     1
437301       éviter   inf     ɛvite     2
437474         être  pi2P        ɛt    12
437476         être   inf       ɛtʁ    20
437497         ôter  ii3S       ɔtɛ     1

[1956 rows x 4 columns]

0
CPU times: user 1min 18s, sys: 22.5 s, total: 1min 40s
Wall time: 30.1 s

nbChunk 396
4200
1964

             lexeme  case     phono  tir1
40            avoir  pi3S         a    85
164      abandonner  ppMS  abɑ̃dɔne     2
299         abattre   inf     abatʁ     1
1175        aborder  ppMS    abɔʁde     1
1934       absenter  ii3S   absɑ̃tɛ     1
2579         abîmer  pi3P      abim     1
2971       accepter   inf   aksɛpte     2
2997       accepter  pi1P  aksɛptɔ̃     1
3003       accepter  ppMS   aksɛpte     2
3170     acclimater  pi3S   aklimat     1
3382    accompagner  ii3P  akɔ̃paɲɛ     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3490      accomplir  pi3S   akɔ̃pli     1
3519       accorder  ii3S    akɔʁdɛ     1
3530       accorder  pi3S     akɔʁd     1
3583       accorder  ppMP    akɔʁde     1
3827      accoucher   inf     akuʃe     1
4259      accrocher   inf    akʁɔʃe     1
4293      accrocher  ppFP    akʁɔʃe     1
4693        accuser  ii3S     akyzɛ     2
4808        accéder  ppMS    aksɛde     1
4812      accélérer  pi3S   aksɛlɛʁ     1
5111        acheter  ii3S     aʃətɛ     1
5119        acheter   inf     aʃəte     5
5157        achever   inf     aʃəve     1
5171        achever  ppMS     aʃəve     1
5173        achever  ppFS     aʃəve     1
5311        acheter  pi3S      aʃɛt     1
5313        acheter  pi3P      aʃɛt     1
6072        activer   inf    aktive     1
...             ...   ...       ...   ...
432144      épouser  ii3S     ɛpuzɛ     1
432160      épouser   inf     ɛpuze     1
432166      épouser  pc3S   ɛpuzəʁɛ     1
432302      épouser  ppMS     ɛpuze     1
433912      établir  ppMS    ɛtabli     1
433922      établir   inf   ɛtabliʁ     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ     3
434070         être  ii3S       ɛtɛ    74
434072       étaler  ai3S     ɛtala     1
434147       étaler  pi3S      ɛtal     1
434488         être    pP      ɛtɑ̃     1
434772     éteindre  ppMS      ɛtɛ̃     1
434773     éteindre  pi3S      ɛtɛ̃     1
434775     éteindre  ppFS     ɛtɛ̃t     1
434827      étendre  pi1S      ɛtɑ̃     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     2
435512     étouffer  pc3S   ɛtufəʁɛ     1
436188      étudier    pP   ɛtydjɑ̃     1
436316         être  ppMS       ɛte    18
436402      évacuer   inf    ɛvakye     1
437301       éviter   inf     ɛvite     2
437427      évoquer  pi3S      ɛvɔk     1
437431      évoquer   inf     ɛvɔke     1
437458      évoquer  ppMS     ɛvɔke     1
437474         être  pi2P        ɛt    16
437476         être   inf       ɛtʁ    21
437512         ôter   inf       ɔte     1
437542         ôter  ppMP       ɔte     1

[1964 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.9 s, total: 1min 37s
Wall time: 29.7 s

nbChunk 397
4200
1947

             lexeme  case       phono  tir1
40            avoir  pi3S           a    88
64         abaisser  pi1S        abɛs     1
132      abandonner   inf    abɑ̃dɔne     2
138      abandonner  pc3S  abɑ̃dɔnəʁɛ     1
148      abandonner  pi2P    abɑ̃dɔne     1
299         abattre   inf       abatʁ     1
1132        aborder  ii3S      abɔʁdɛ     1
1143        aborder  pi3S       abɔʁd     1
1307        abouler  pi3S        abul     1
2939       accepter  ai3S     aksɛpta     1
2967       accepter  pi3S      aksɛpt     1
3003       accepter  ppMS     aksɛpte     1
3093       acclamer  ii3P      aklamɛ     1
3315        accoler  ppFP       akɔle     1
3371     accommoder  pi1P    akɔmɔdɔ̃     1
3382    accompagner  ii3P    akɔ̃paɲɛ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3443      accomplir   inf    akɔ̃pliʁ     1
3475      accomplir  pi3P    akɔ̃plis     1
4237      accrocher  ii3S      akʁɔʃɛ     1
4690        accuser  ii3P       akyzɛ     1
4720        accuser   inf       akyze     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     2
5171        achever  ppMS       aʃəve     1
5807       acquérir  ppMS         aki     1
6873       admettre  pi3P       admɛt     1
7309         adorer  pi1S        adɔʁ     1
7317         adorer  fi3S     adɔʁəʁa     1
7344         adorer  ppFS       adɔʁe     1
...             ...   ...         ...   ...
430563     épargner  fi3S    ɛpaʁɲəʁa     1
432160      épouser   inf       ɛpuze     1
432549     éprouver  pi1S       ɛpʁuv     1
432657      épuiser  pi3P       ɛpɥiz     1
433238   équivaloir  pi3S       ɛkivo     1
433431     érailler  ppFS       ɛʁaje     1
433914      établir  ppFS      ɛtabli     1
434048         être  ii3P         ɛtɛ     6
434068         être  ii1S         ɛtɛ    15
434069         être  ii2S         ɛtɛ     1
434070         être  ii3S         ɛtɛ    75
434144       étaler  pi1S        ɛtal     1
434153       étaler   inf       ɛtale     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434770     éteindre  pi2S        ɛtɛ̃     1
435054         être  ii2P        ɛtje     4
435172         être  ii1P       ɛtjɔ̃     2
435444      étonner   inf       ɛtɔne     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
435968      étriper  pi3S       ɛtʁip     1
436181      étudier  ai3S      ɛtydja     1
436205      étudier   inf      ɛtydje     2
436316         être  ppMS         ɛte    16
436869     éveiller  ppFS       ɛvɛje     1
437328       éviter  ppMS       ɛvite     1
437365      évoluer  pi3P       ɛvɔly     1
437474         être  pi2P          ɛt     9
437476         être   inf         ɛtʁ    20
437512         ôter   inf         ɔte     1

[1947 rows x 4 columns]

0
CPU times: user 1min 6s, sys: 19.3 s, total: 1min 25s
Wall time: 29.3 s

nbChunk 398
4200
1897

             lexeme  case     phono  tir1
40            avoir  pi3S         a    79
73         abaisser   inf     abɛse     1
109      abandonner  ai1S  abɑ̃dɔnɛ     1
132      abandonner   inf  abɑ̃dɔne     2
252         abattre  pi2S       aba     1
865          aboyer  pi3S      abwa     1
1668        abriter  ai3S    abʁita     1
2042       absorber  ai3S   absɔʁba     1
2967       accepter  pi3S    aksɛpt     1
2968       accepter  ps3S    aksɛpt     1
2971       accepter   inf   aksɛpte     5
3144       acclamer  ppMS    aklame     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3443      accomplir   inf  akɔ̃pliʁ     1
3530       accorder  pi3S     akɔʁd     1
4238      accrocher    pP   akʁɔʃɑ̃     1
4252      accrocher  pi1S     akʁɔʃ     1
4255      accrocher  pi3S     akʁɔʃ     2
4475     accueillir    pP    akəjɑ̃     1
5092      acheminer  pi1P  aʃəminɔ̃     1
5173        achever  ppFS     aʃəve     1
5316        acheter  fi1S   aʃɛtəʁɛ     1
6959        admirer  ai3S    admiʁa     1
6996        admirer   inf    admiʁe     1
7312         adorer  pi3S      adɔʁ     1
7401        adosser  ppMP     adɔse     1
7523       adresser  ii3S    adʁɛsɛ     1
7532       adresser  pi1S     adʁɛs     1
7535       adresser  pi3S     adʁɛs     1
7806        advenir  pi3S    advjɛ̃     1
...             ...   ...       ...   ...
430668       épater    pP    ɛpatɑ̃     1
431611     épingler  ppFS   ɛpɛ̃gle     1
431867     éplucher  pi3S     ɛplyʃ     1
432156      épouser  pi3S      ɛpuz     2
432160      épouser   inf     ɛpuze     2
432534     éprouver  ii3P    ɛpʁuvɛ     1
432689      épuiser  ppMS    ɛpɥize     1
433113      équiper   inf     ɛkipe     1
433226   équivaloir  fi3S  ɛkivɔdʁa     1
433777      éructer  ii3S    ɛʁyktɛ     1
433912      établir  ppMS    ɛtabli     1
433981      établir  is3S    ɛtabli     1
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ    15
434070         être  ii3S       ɛtɛ    56
434821      étendre   inf    ɛtɑ̃dʁ     1
435054         être  ii2P      ɛtje     2
435481     étouffer  ii3P     ɛtufɛ     1
436235      étudier  ppFS    ɛtydje     1
436316         être  ppMS       ɛte    22
436402      évacuer   inf    ɛvakye     1
436430      évacuer  ppMS    ɛvakye     1
436457       évader   inf     ɛvade     1
436629     évanouir  ppFS    ɛvanui     1
437301       éviter   inf     ɛvite     1
437307       éviter  pc3S   ɛvitəʁɛ     1
437431      évoquer   inf     ɛvɔke     1
437474         être  pi2P        ɛt    15
437476         être   inf       ɛtʁ    23
437492         ôter  ai3S       ɔta     1

[1897 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.8 s, total: 1min 36s
Wall time: 28.8 s

nbChunk 399
4200
1907

             lexeme  case      phono  tir1
40            avoir  pi3S          a    87
132      abandonner   inf   abɑ̃dɔne     1
299         abattre   inf      abatʁ     1
928          abolir  ii1P  abɔlisjɔ̃     1
1121        aborder  ai3S     abɔʁda     1
1148        aborder  fi3S   abɔʁdəʁa     1
2051       absorber  ii3S    absɔʁbɛ     1
2070       absorber   inf    absɔʁbe     1
2371         abuser  ppMS      abyze     1
2577         abîmer  pi3S       abim     1
2612         abîmer  ppFS      abime     1
2946       accepter  ai1S    aksɛptɛ     2
2969       accepter  pi3P     aksɛpt     1
2972       accepter  fi3S  aksɛptəʁa     1
3385    accompagner  ii3S   akɔ̃paɲɛ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3519       accorder  ii3S     akɔʁdɛ     1
3536       accorder   inf     akɔʁde     1
4252      accrocher  pi1S      akʁɔʃ     1
4255      accrocher  pi3S      akʁɔʃ     1
4259      accrocher   inf     akʁɔʃe     1
4368      accroupir  ai3S     akʁupi     1
4509     accueillir   inf     akəjiʁ     1
4519     accueillir  ai3S      akəji     1
4626        acculer  ppMS      akyle     1
4716        accuser  pi3S       akyz     1
4720        accuser   inf      akyze     1
4812      accélérer  pi3S    aksɛlɛʁ     1
5108        acheter  ii3P      aʃətɛ     1
...             ...   ...        ...   ...
427641     éloigner   inf     ɛlwaɲe     1
428248       émaner  pi3S       ɛman     1
428608  émerveiller  ppMP   ɛmɛʁvɛje     1
430590     épargner  ppMS     ɛpaʁɲe     1
432156      épouser  pi3S       ɛpuz     1
432160      épouser   inf      ɛpuze     3
432533     éprouver  ai1S     ɛpʁuvɛ     1
432569     éprouver  pi2S      ɛpʁuv     1
432592     éprouver  ppMP     ɛpʁuve     1
432695      épuiser  ppMP     ɛpɥize     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ     9
434070         être  ii3S        ɛtɛ    73
434773     éteindre  pi3S       ɛtɛ̃     2
434789      étendre    pP    ɛtɑ̃dɑ̃     1
434831      étendre  ppMS     ɛtɑ̃dy     1
435054         être  ii2P       ɛtje     1
435062    étinceler  ii3S   ɛtɛ̃səlɛ     1
435232       étirer  ai3S      ɛtiʁa     1
435484     étouffer  ii3S      ɛtufɛ     1
435506     étouffer   inf      ɛtufe     1
435538     étouffer  ppMS      ɛtufe     1
436316         être  ppMS        ɛte    19
436457       évader   inf      ɛvade     1
436821     éveiller    pP     ɛvɛjɑ̃     1
437285       éviter    pP     ɛvitɑ̃     1
437301       éviter   inf      ɛvite     2
437427      évoquer  pi3S       ɛvɔk     1
437474         être  pi2P         ɛt    19
437476         être   inf        ɛtʁ    18

[1907 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22 s, total: 1min 38s
Wall time: 30.2 s

nbChunk 400
4200
1967

             lexeme  case      phono  tir1
40            avoir  pi3S          a    74
114      abandonner    pP  abɑ̃dɔnɑ̃     1
132      abandonner   inf   abɑ̃dɔne     1
147      abandonner  pI2P   abɑ̃dɔne     1
148      abandonner  pi2P   abɑ̃dɔne     1
170      abandonner  ppMP   abɑ̃dɔne     1
862          aboyer  pi1S       abwa     1
1147        aborder   inf     abɔʁde     3
1674        abriter    pP    abʁitɑ̃     1
1859        abréger  pi3S      abʁɛʒ     1
2051       absorber  ii3S    absɔʁbɛ     1
2070       absorber   inf    absɔʁbe     1
2100       absorber  ppMS    absɔʁbe     1
2324         abuser  ii3S      abyzɛ     1
2371         abuser  ppMS      abyze     1
2897      accentuer  pi1S    aksɑ̃ty     1
2971       accepter   inf    aksɛpte     1
3003       accepter  ppMS    aksɛpte     2
3091       acclamer  ai3S     aklama     1
3382    accompagner  ii3P   akɔ̃paɲɛ     1
3400    accompagner  pi3S    akɔ̃paɲ     1
3404    accompagner  pi3P    akɔ̃paɲ     1
3434    accompagner  ppFS   akɔ̃paɲe     1
3508       accorder  ai3S     akɔʁda     1
3516       accorder  ii3P     akɔʁdɛ     1
3519       accorder  ii3S     akɔʁdɛ     1
3821      accoucher  pi3S       akuʃ     1
3827      accoucher   inf      akuʃe     1
4259      accrocher   inf     akʁɔʃe     1
4291      accrocher  ppMS     akʁɔʃe     1
...             ...   ...        ...   ...
430558     épargner  pi3S      ɛpaʁɲ     1
430688       épater   inf      ɛpate     1
432160      épouser   inf      ɛpuze     1
432537     éprouver  ii3S     ɛpʁuvɛ     1
433912      établir  ppMS     ɛtabli     1
433922      établir   inf    ɛtabliʁ     1
434068         être  ii1S        ɛtɛ    14
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    83
434747     éteindre  ai3S      ɛtɛɲi     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434773     éteindre  pi3S       ɛtɛ̃     2
434821      étendre   inf     ɛtɑ̃dʁ     1
434828      étendre  pI2S       ɛtɑ̃     1
435054         être  ii2P       ɛtje     2
435244       étirer    pP     ɛtiʁɑ̃     1
435294       étirer  ppFS      ɛtiʁe     1
435471      étonner  ppMS      ɛtɔne     1
436212      étudier  fi2S    ɛtydiʁa     1
436316         être  ppMS        ɛte    20
436436      évacuer  ppMP     ɛvakye     1
436627     évanouir  ppMS     ɛvanui     1
436867     éveiller  ppMS      ɛvɛje     1
437301       éviter   inf      ɛvite     1
437417      évoquer    pP     ɛvɔkɑ̃     1
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt     7
437476         être   inf        ɛtʁ    15
437497         ôter  ii3S        ɔtɛ     1
437512         ôter   inf        ɔte     2

[1967 rows x 4 columns]

0
CPU times: user 1min 10s, sys: 20.6 s, total: 1min 31s
Wall time: 30 s

nbChunk 401
4200
1925

             lexeme  case      phono  tir1
40            avoir  pi3S          a    95
108      abandonner  ai3S   abɑ̃dɔna     1
128      abandonner  pi3S    abɑ̃dɔn     1
132      abandonner   inf   abɑ̃dɔne     1
166      abandonner  ppFS   abɑ̃dɔne     1
1673        abriter  ii3S     abʁitɛ     1
1979       absenter  ppMS    absɑ̃te     1
2581         abîmer   inf      abime     1
2948       accepter  ii1S    aksɛptɛ     2
2967       accepter  pi3S     aksɛpt     1
2989       accepter  pi2P    aksɛpte     1
3003       accepter  ppMS    aksɛpte     3
3383    accompagner  ii1S   akɔ̃paɲɛ     1
3490      accomplir  pi3S    akɔ̃pli     1
3519       accorder  ii3S     akɔʁdɛ     1
3583       accorder  ppMP     akɔʁde     1
3686        accoter  ai3S      akɔta     1
3858      accoucher  ppMS      akuʃe     1
4237      accrocher  ii3S     akʁɔʃɛ     1
4320      accroupir  ppMS     akʁupi     1
4509     accueillir   inf     akəjiʁ     1
4512     accueillir  ai1S      akəji     1
4682      accumuler  ai3P   akymylɛʁ     1
4720        accuser   inf      akyze     1
4864      accélérer  ppFS   aksɛlɛʁe     1
5119        acheter   inf      aʃəte     1
5125        acheter  pi2P      aʃəte     1
5136        acheter  ppMS      aʃəte     2
5139        acheter  ppMP      aʃəte     1
6432        adapter  pi2P     adapte     1
...             ...   ...        ...   ...
432691      épuiser  ppFS     ɛpɥize     1
433433     érailler  ppFP      ɛʁaje     1
433922      établir   inf    ɛtabliʁ     1
434048         être  ii3P        ɛtɛ     5
434068         être  ii1S        ɛtɛ     9
434069         être  ii2S        ɛtɛ     2
434070         être  ii3S        ɛtɛ    81
434301       étaler  ppFP      ɛtale     1
434488         être    pP       ɛtɑ̃     1
434762     éteindre   inf     ɛtɛ̃dʁ     1
434768     éteindre  pi1S       ɛtɛ̃     1
434773     éteindre  pi3S       ɛtɛ̃     1
434775     éteindre  ppFS      ɛtɛ̃t     1
434788      étendre  ii3S     ɛtɑ̃dɛ     1
435064    étinceler    pP  ɛtɛ̃səlɑ̃     1
435172         être  ii1P      ɛtjɔ̃     2
435241       étirer  ii1S      ɛtiʁɛ     1
435418      étonner  ai1S      ɛtɔnɛ     1
435438      étonner  pi3S       ɛtɔn     1
435444      étonner   inf      ɛtɔne     1
435471      étonner  ppMS      ɛtɔne     1
435500     étouffer  pi3S       ɛtuf     1
435506     étouffer   inf      ɛtufe     1
436316         être  ppMS        ɛte    25
436632     évanouir   inf    ɛvanuiʁ     1
437301       éviter   inf      ɛvite     3
437431      évoquer   inf      ɛvɔke     1
437474         être  pi2P         ɛt    13
437476         être   inf        ɛtʁ    23
437512         ôter   inf        ɔte     1

[1925 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.4 s, total: 1min 39s
Wall time: 30.2 s

nbChunk 402
4200
1962

             lexeme  case     phono  tir1
40            avoir  pi3S         a    77
132      abandonner   inf  abɑ̃dɔne     1
164      abandonner  ppMS  abɑ̃dɔne     1
297         abattre  pc3S    abatʁɛ     1
305         abattre  ppMS     abaty     1
869          aboyer  pi3P      abwa     1
887          abolir  ppMS     abɔli     1
982         abonder  pi3P     abɔ̃d     1
1147        aborder   inf    abɔʁde     1
1884        abréger   inf    abʁɛʒe     1
2070       absorber   inf   absɔʁbe     2
2715       accabler  ii3S    akablɛ     1
2939       accepter  ai3S   aksɛpta     1
2964       accepter  pi1S    aksɛpt     1
2967       accepter  pi3S    aksɛpt     1
2989       accepter  pi2P   aksɛpte     1
3003       accepter  ppMS   aksɛpte     2
3380    accompagner  ai3S  akɔ̃paɲa     1
3406    accompagner   inf  akɔ̃paɲe     3
3433    accompagner  ppMS  akɔ̃paɲe     1
3571       accorder  ppMS    akɔʁde     1
3913       accouder  ppMS     akude     1
4087       accourir  pi1S      akuʁ     1
4238      accrocher    pP   akʁɔʃɑ̃     1
4255      accrocher  pi3S     akʁɔʃ     1
4291      accrocher  ppMS    akʁɔʃe     2
4502     accueillir  ppMS     akəji     1
4716        accuser  pi3S      akyz     1
4748        accuser  ppMS     akyze     3
4835      accélérer   inf  aksɛlɛʁe     1
...             ...   ...       ...   ...
429365     émouvoir  ppMS       ɛmy     1
429700      énerver   inf    ɛnɛʁve     1
430590     épargner  ppMS    ɛpaʁɲe     1
432160      épouser   inf     ɛpuze     1
432302      épouser  ppMS     ɛpuze     1
432374   épouvanter  ii3S  ɛpuvɑ̃tɛ     1
433946      établir  ii3S  ɛtablisɛ     1
434048         être  ii3P       ɛtɛ     6
434068         être  ii1S       ɛtɛ    11
434070         être  ii3S       ɛtɛ    77
434727     éteindre    pP    ɛtɛɲɑ̃     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     2
435422      étonner  ii3S     ɛtɔnɛ     1
435497     étouffer  pi1S      ɛtuf     1
435500     étouffer  pi3S      ɛtuf     1
435506     étouffer   inf     ɛtufe     1
436205      étudier   inf    ɛtydje     1
436316         être  ppMS       ɛte    22
436414      évacuer  fi3P  ɛvakyʁɔ̃     1
437049     évertuer  ii3S   ɛvɛʁtyɛ     1
437301       éviter   inf     ɛvite     1
437317       éviter  pi2P     ɛvite     1
437328       éviter  ppMS     ɛvite     1
437416      évoquer  ii3S     ɛvɔkɛ     1
437453      évoquer  pi1P    ɛvɔkɔ̃     1
437457      évoquer  ai3P    ɛvɔkɛʁ     1
437458      évoquer  ppMS     ɛvɔke     1
437474         être  pi2P        ɛt    14
437476         être   inf       ɛtʁ    17

[1962 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.2 s, total: 1min 34s
Wall time: 29.6 s

nbChunk 403
4200
1929

             lexeme  case       phono  tir1
40            avoir  pi3S           a    89
108      abandonner  ai3S    abɑ̃dɔna     1
164      abandonner  ppMS    abɑ̃dɔne     2
177      abasourdir  ppMS    abazuʁdi     1
299         abattre   inf       abatʁ     1
645         abjurer    pP     abʒyʁɑ̃     1
865          aboyer  pi3S        abwa     1
1163        aborder  pi2P      abɔʁde     1
1788        abroger  ppFP      abʁɔʒe     1
2102       absorber  ppFS     absɔʁbe     1
2337         abuser  pi3P        abyz     1
2339         abuser   inf       abyze     1
2950       accepter  ii3S     aksɛptɛ     1
2952       accepter    pP    aksɛptɑ̃     1
3386    accompagner    pP   akɔ̃paɲɑ̃     1
3480      accomplir  pi2P   akɔ̃plise     1
3527       accorder  pi1S       akɔʁd     1
3536       accorder   inf      akɔʁde     1
4255      accrocher  pi3S       akʁɔʃ     1
4484     accueillir  pi3P        akœj     1
4835      accélérer   inf    aksɛlɛʁe     1
5008       acharner  pi3S       aʃaʁn     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     3
5157        achever   inf       aʃəve     1
6988        admirer  pi1S       admiʁ     1
6996        admirer   inf      admiʁe     1
7320         adorer  pc1S     adɔʁəʁɛ     1
7569       adresser  ppFP      adʁɛse     1
9059        affoler  ai3S       afɔla     1
...             ...   ...         ...   ...
432145      épouser    pP      ɛpuzɑ̃     1
432160      épouser   inf       ɛpuze     2
432532     éprouver  ai3S      ɛpʁuva     1
432556     éprouver   inf      ɛpʁuve     1
432659      épuiser   inf      ɛpɥize     1
432770       épurer  ppFS       ɛpyʁe     1
433026   équilibrer   inf    ɛkilibʁe     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    19
434069         être  ii2S         ɛtɛ     1
434070         être  ii3S         ɛtɛ    71
434811      étendre  ai3S      ɛtɑ̃di     1
434831      étendre  ppMS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     2
435228    étiqueter  ppMS     ɛtikəte     1
435450      étonner  pc3S     ɛtɔnəʁɛ     2
435457      étonner  pi2S        ɛtɔn     1
435471      étonner  ppMS       ɛtɔne     1
435794    étreindre  ii3S      ɛtʁɛɲɛ     1
436181      étudier  ai3S      ɛtydja     1
436316         être  ppMS         ɛte    23
436591  évangéliser   inf  ɛvɑ̃ʒɛlize     1
437301       éviter   inf       ɛvite     3
437427      évoquer  pi3S        ɛvɔk     1
437474         être  pi2P          ɛt    11
437476         être   inf         ɛtʁ    23
437512         ôter   inf         ɔte     1
437539         ôter  ppMS         ɔte     1

[1929 rows x 4 columns]

0
CPU times: user 1min 11s, sys: 20.8 s, total: 1min 32s
Wall time: 29.8 s

nbChunk 404
4200
1942

             lexeme  case       phono  tir1
40            avoir  pi3S           a    96
108      abandonner  ai3S    abɑ̃dɔna     1
114      abandonner    pP   abɑ̃dɔnɑ̃     1
125      abandonner  pi1S     abɑ̃dɔn     1
128      abandonner  pi3S     abɑ̃dɔn     1
129      abandonner  ps3S     abɑ̃dɔn     1
130      abandonner  pi3P     abɑ̃dɔn     1
132      abandonner   inf    abɑ̃dɔne     1
138      abandonner  pc3S  abɑ̃dɔnəʁɛ     1
287         abattre  ai3S       abati     1
299         abattre   inf       abatʁ     1
2066       absorber  pi3S      absɔʁb     1
2143       abstenir   inf    abstəniʁ     1
2321         abuser  ii3P       abyzɛ     1
2335         abuser  pi3S        abyz     1
2593         abîmer  fi3P    abiməʁɔ̃     1
2782      accaparer  pi1S      akapaʁ     1
2969       accepter  pi3P      aksɛpt     1
3113       acclamer  pi3S       aklam     1
3351     accommoder  fi1S   akɔmɔdəʁɛ     1
3406    accompagner   inf    akɔ̃paɲe     1
3422    accompagner  pi2P    akɔ̃paɲe     1
3443      accomplir   inf    akɔ̃pliʁ     1
3519       accorder  ii3S      akɔʁdɛ     1
3530       accorder  pi3S       akɔʁd     1
3536       accorder   inf      akɔʁde     1
4210     accoutumer  ppMS     akutyme     1
4252      accrocher  pi1S       akʁɔʃ     1
4255      accrocher  pi3S       akʁɔʃ     2
4291      accrocher  ppMS      akʁɔʃe     1
...             ...   ...         ...   ...
431909     éplucher  ppMP      ɛplyʃe     1
432160      épouser   inf       ɛpuze     1
432303      épouser  ppFS       ɛpuze     1
432535     éprouver  ii1S      ɛpʁuvɛ     1
432552     éprouver  pi3S       ɛpʁuv     1
432556     éprouver   inf      ɛpʁuve     1
432582     éprouver  is3S      ɛpʁuva     1
432659      épuiser   inf      ɛpɥize     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ    14
434069         être  ii2S         ɛtɛ     1
434070         être  ii3S         ɛtɛ    71
434302       étaler  ppMP       ɛtale     1
434488         être    pP        ɛtɑ̃     2
434762     éteindre   inf      ɛtɛ̃dʁ     1
435054         être  ii2P        ɛtje     3
435172         être  ii1P       ɛtjɔ̃     2
435481     étouffer  ii3P       ɛtufɛ     1
435506     étouffer   inf       ɛtufe     2
436316         être  ppMS         ɛte    20
436457       évader   inf       ɛvade     1
436632     évanouir   inf     ɛvanuiʁ     1
436980     éventrer  ii3S     ɛvɑ̃tʁɛ     1
437130       évider   inf       ɛvide     1
437295       éviter  pi3S        ɛvit     1
437301       éviter   inf       ɛvite     2
437328       éviter  ppMS       ɛvite     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    17

[1942 rows x 4 columns]

0
CPU times: user 1min 9s, sys: 20.2 s, total: 1min 29s
Wall time: 29.9 s

nbChunk 405
4200
1943

             lexeme  case      phono  tir1
40            avoir  pi3S          a    79
114      abandonner    pP  abɑ̃dɔnɑ̃     1
132      abandonner   inf   abɑ̃dɔne     1
164      abandonner  ppMS   abɑ̃dɔne     3
982         abonder  pi3P      abɔ̃d     1
1121        aborder  ai3S     abɔʁda     1
1132        aborder  ii3S     abɔʁdɛ     1
1147        aborder   inf     abɔʁde     1
1688        abriter   inf     abʁite     1
2066       absorber  pi3S     absɔʁb     1
2106       absorber  ppMP    absɔʁbe     1
2325         abuser    pP     abyzɑ̃     1
2751       accabler  pI2P     akable     1
2971       accepter   inf    aksɛpte     2
2997       accepter  pi1P   aksɛptɔ̃     1
3005       accepter  ppFS    aksɛpte     1
3406    accompagner   inf   akɔ̃paɲe     1
3433    accompagner  ppMS   akɔ̃paɲe     1
3440      accomplir  ppFS    akɔ̃pli     1
3536       accorder   inf     akɔʁde     1
3571       accorder  ppMS     akɔʁde     1
4280      accrocher  pi2P     akʁɔʃe     1
4368      accroupir  ai3S     akʁupi     1
4504     accueillir  ppFP      akəji     1
5119        acheter   inf      aʃəte     3
5136        acheter  ppMS      aʃəte     1
5137        acheter  ppFS      aʃəte     1
5140        achever  ai3S      aʃəva     1
5149        achever  ii3S      aʃəvɛ     1
5311        acheter  pi3S       aʃɛt     2
...             ...   ...        ...   ...
430593     épargner  ppMP     ɛpaʁɲe     1
431163        épier  pi3S        ɛpi     1
432144      épouser  ii3S      ɛpuzɛ     1
432160      épouser   inf      ɛpuze     1
432369   épouvanter  ii3P   ɛpuvɑ̃tɛ     1
432535     éprouver  ii1S     ɛpʁuvɛ     1
432586     éprouver  ppMS     ɛpʁuve     1
433946      établir  ii3S   ɛtablisɛ     1
434048         être  ii3P        ɛtɛ     2
434068         être  ii1S        ɛtɛ    11
434069         être  ii2S        ɛtɛ     1
434070         être  ii3S        ɛtɛ    75
434147       étaler  pi3S       ɛtal     1
434156       étaler  pc3P    ɛtaləʁɛ     1
434488         être    pP       ɛtɑ̃     1
434821      étendre   inf     ɛtɑ̃dʁ     2
435054         être  ii2P       ɛtje     1
435062    étinceler  ii3S   ɛtɛ̃səlɛ     1
435244       étirer    pP     ɛtiʁɑ̃     1
435417      étonner  ai3S      ɛtɔna     2
436233      étudier  ppMS     ɛtydje     1
436316         être  ppMS        ɛte    24
436867     éveiller  ppMS      ɛvɛje     1
437295       éviter  pi3S       ɛvit     1
437301       éviter   inf      ɛvite     5
437328       éviter  ppMS      ɛvite     1
437416      évoquer  ii3S      ɛvɔkɛ     2
437427      évoquer  pi3S       ɛvɔk     1
437474         être  pi2P         ɛt     9
437476         être   inf        ɛtʁ    18

[1943 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.7 s, total: 1min 35s
Wall time: 30.3 s

nbChunk 406
4200
1986

             lexeme  case        phono  tir1
40            avoir  pi3S            a    86
73         abaisser   inf        abɛse     1
128      abandonner  pi3S      abɑ̃dɔn     1
132      abandonner   inf     abɑ̃dɔne     1
143      abandonner  fi1P  abɑ̃dɔnəʁɔ̃     1
147      abandonner  pI2P     abɑ̃dɔne     1
149      abandonner  ii2P    abɑ̃dɔnje     1
305         abattre  ppMS        abaty     1
1440        aboutir  pi3S        abuti     1
1684        abriter  pi3S        abʁit     1
1884        abréger   inf       abʁɛʒe     1
2100       absorber  ppMS      absɔʁbe     1
2736       accabler   inf       akable     1
2971       accepter   inf      aksɛpte     1
3349     accommoder   inf      akɔmɔde     1
3413    accompagner  fi2S   akɔ̃paɲəʁa     1
3433    accompagner  ppMS     akɔ̃paɲe     1
3443      accomplir   inf     akɔ̃pliʁ     1
3536       accorder   inf       akɔʁde     1
3556       accorder  pi2P       akɔʁde     1
4259      accrocher   inf       akʁɔʃe     1
4783        accéder   inf       aksɛde     1
5043       acharner  ppFP       aʃaʁne     1
5119        acheter   inf        aʃəte     2
5125        acheter  pi2P        aʃəte     1
5136        acheter  ppMS        aʃəte     1
5137        acheter  ppFS        aʃəte     1
5146        achever  ii3P        aʃəvɛ     1
5311        acheter  pi3S         aʃɛt     1
5315        acheter  fi3S      aʃɛtəʁa     1
...             ...   ...          ...   ...
434048         être  ii3P          ɛtɛ     1
434068         être  ii1S          ɛtɛ    12
434069         être  ii2S          ɛtɛ     2
434070         être  ii3S          ɛtɛ    82
434131       étaler  ii3P        ɛtalɛ     1
434153       étaler   inf        ɛtale     2
434488         être    pP         ɛtɑ̃     2
434762     éteindre   inf       ɛtɛ̃dʁ     1
434768     éteindre  pi1S         ɛtɛ̃     1
434788      étendre  ii3S       ɛtɑ̃dɛ     1
434833      étendre  ppFS       ɛtɑ̃dy     1
435054         être  ii2P         ɛtje     1
435172         être  ii1P        ɛtjɔ̃     3
435435      étonner  pi1S         ɛtɔn     1
435438      étonner  pi3S         ɛtɔn     1
435475     étouffer  ai3S        ɛtufa     1
435484     étouffer  ii3S        ɛtufɛ     1
435519     étouffer  pi2S         ɛtuf     1
435538     étouffer  ppMS        ɛtufe     1
436205      étudier   inf       ɛtydje     1
436206      étudier  fi3S      ɛtydiʁa     1
436218      étudier  pi2S        ɛtydi     1
436233      étudier  ppMS       ɛtydje     2
436316         être  ppMS          ɛte    24
437176      évincer   inf       ɛvɛ̃se     1
437273       éviter  ai3S        ɛvita     1
437301       éviter   inf        ɛvite     3
437474         être  pi2P           ɛt    10
437476         être   inf          ɛtʁ    22
437510         ôter  pi3P           ot     1

[1986 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.4 s, total: 1min 35s
Wall time: 30.9 s

nbChunk 407
4200
1980

             lexeme  case       phono  tir1
40            avoir  pi3S           a    84
45         abaisser  ai3S       abɛsa     1
108      abandonner  ai3S    abɑ̃dɔna     1
134      abandonner  fi1S  abɑ̃dɔnəʁɛ     1
148      abandonner  pi2P    abɑ̃dɔne     1
162      abandonner  ai3P   abɑ̃dɔnɛʁ     1
164      abandonner  ppMS    abɑ̃dɔne     1
264         abattre  pi3P        abat     1
305         abattre  ppMS       abaty     1
616        abhorrer  ppMS       abɔʁe     1
890          abolir   inf      abɔliʁ     1
1468         aboyer   inf      abwaje     1
1856        abréger  pi1S       abʁɛʒ     1
1980       absenter  ppFS     absɑ̃te     1
2106       absorber  ppMP     absɔʁbe     1
2374         abuser  ppMP       abyze     1
2616         abîmer  ppMP       abime     1
2900      accentuer  pi3S     aksɑ̃ty     1
2950       accepter  ii3S     aksɛptɛ     1
2971       accepter   inf     aksɛpte     1
3003       accepter  ppMS     aksɛpte     2
3368     accommoder  ii1P   akɔmɔdjɔ̃     1
3385    accompagner  ii3S    akɔ̃paɲɛ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3406    accompagner   inf    akɔ̃paɲe     1
3419    accompagner  pi2S     akɔ̃paɲ     1
3433    accompagner  ppMS    akɔ̃paɲe     2
3436    accompagner  ppMP    akɔ̃paɲe     1
3490      accomplir  pi3S     akɔ̃pli     1
4006       accourir  ii3P       akuʁɛ     1
...             ...   ...         ...   ...
428650     émouvoir  pi3S         ɛmø     1
429694      énerver  pi3S       ɛnɛʁv     1
430590     épargner  ppMS      ɛpaʁɲe     1
430721       épater  ppMS       ɛpate     2
432144      épouser  ii3S       ɛpuzɛ     1
432156      épouser  pi3S        ɛpuz     1
432160      épouser   inf       ɛpuze     1
432586     éprouver  ppMS      ɛpʁuve     1
432689      épuiser  ppMS      ɛpɥize     1
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ    11
434070         être  ii3S         ɛtɛ    60
434302       étaler  ppMP       ɛtale     1
434692       étayer   inf       ɛtɛje     1
434726     éteindre  ii3S       ɛtɛɲɛ     1
434747     éteindre  ai3S       ɛtɛɲi     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434816      étendre  pc3P     ɛtɑ̃dʁɛ     1
435054         être  ii2P        ɛtje     1
435438      étonner  pi3S        ɛtɔn     1
435471      étonner  ppMS       ɛtɔne     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
436316         être  ppMS         ɛte    24
436457       évader   inf       ɛvade     1
436821     éveiller    pP      ɛvɛjɑ̃     1
437295       éviter  pi3S        ɛvit     1
437301       éviter   inf       ɛvite     1
437427      évoquer  pi3S        ɛvɔk     1
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    18

[1980 rows x 4 columns]

0
CPU times: user 1min 5s, sys: 19 s, total: 1min 24s
Wall time: 30.2 s

nbChunk 408
4200
1948

             lexeme  case       phono  tir1
40            avoir  pi3S           a   103
132      abandonner   inf    abɑ̃dɔne     1
145      abandonner  pi2S     abɑ̃dɔn     1
151      abandonner  ii1P  abɑ̃dɔnjɔ̃     1
170      abandonner  ppMP    abɑ̃dɔne     1
1129        aborder  ii3P      abɔʁdɛ     1
1143        aborder  pi3S       abɔʁd     1
1979       absenter  ppMS     absɑ̃te     1
2947       accepter  ii3P     aksɛptɛ     1
2971       accepter   inf     aksɛpte     2
2977       accepter  pc3S   aksɛptəʁɛ     1
3003       accepter  ppMS     aksɛpte     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3434    accompagner  ppFS    akɔ̃paɲe     1
3435    accompagner  ppFP    akɔ̃paɲe     1
3460      accomplir  pi1S     akɔ̃pli     1
3508       accorder  ai3S      akɔʁda     1
3536       accorder   inf      akɔʁde     1
3827      accoucher   inf       akuʃe     1
3914       accouder  ppFS       akude     1
4259      accrocher   inf      akʁɔʃe     1
4260      accrocher  fi3S    akʁɔʃəʁa     1
4688        accuser  ai3S       akyza     1
4994       acharner  ii3P      aʃaʁnɛ     1
5119        acheter   inf       aʃəte     2
5136        acheter  ppMS       aʃəte     1
5157        achever   inf       aʃəve     1
6739      adjoindre  ppMP      adʒwɛ̃     1
6863       admettre  pi1S        admɛ     1
6891       admettre   inf      admɛtʁ     1
...             ...   ...         ...   ...
434069         être  ii2S         ɛtɛ     1
434070         être  ii3S         ɛtɛ    85
434773     éteindre  pi3S        ɛtɛ̃     1
434782      étendre  pi3S        ɛtɑ̃     2
434786      étendre  ii1S      ɛtɑ̃dɛ     1
434811      étendre  ai3S      ɛtɑ̃di     2
435054         être  ii2P        ɛtje     2
435133      étioler  pi3P       ɛtjɔl     1
435172         être  ii1P       ɛtjɔ̃     1
435232       étirer  ai3S       ɛtiʁa     1
435425      étonner    pP      ɛtɔnɑ̃     1
435450      étonner  pc3S     ɛtɔnəʁɛ     1
435482     étouffer  ii1S       ɛtufɛ     1
435497     étouffer  pi1S        ɛtuf     1
435506     étouffer   inf       ɛtufe     1
435654     étourdir  ppMS      ɛtuʁdi     1
435748    étrangler   inf    ɛtʁɑ̃gle     1
435794    étreindre  ii3S      ɛtʁɛɲɛ     1
436205      étudier   inf      ɛtydje     1
436316         être  ppMS         ɛte    37
436400      évacuer  pi3P       ɛvaky     1
436835     éveiller   inf       ɛvɛje     1
437285       éviter    pP      ɛvitɑ̃     1
437295       éviter  pi3S        ɛvit     1
437301       éviter   inf       ɛvite     1
437416      évoquer  ii3S       ɛvɔkɛ     1
437458      évoquer  ppMS       ɛvɔke     2
437474         être  pi2P          ɛt    11
437476         être   inf         ɛtʁ    14
437512         ôter   inf         ɔte     1

[1948 rows x 4 columns]

0
CPU times: user 1min 9s, sys: 20 s, total: 1min 29s
Wall time: 30.8 s

nbChunk 409
4200
1975

             lexeme  case     phono  tir1
40            avoir  pi3S         a    84
128      abandonner  pi3S   abɑ̃dɔn     1
132      abandonner   inf  abɑ̃dɔne     1
259         abattre    pP    abatɑ̃     1
305         abattre  ppMS     abaty     1
1147        aborder   inf    abɔʁde     1
1393        aboutir   inf    abutiʁ     1
1461         aboyer    pP   abwajɑ̃     1
2285      abstraire  ppMP    abstʁɛ     1
2371         abuser  ppMS     abyze     1
2763       accabler  ppMS    akable     1
2884      accentuer  ii3P  aksɑ̃tyɛ     1
3322     accommoder  ii3S   akɔmɔdɛ     1
3400    accompagner  pi3S   akɔ̃paɲ     1
3406    accompagner   inf  akɔ̃paɲe     1
3434    accompagner  ppFS  akɔ̃paɲe     1
3436    accompagner  ppMP  akɔ̃paɲe     1
4280      accrocher  pi2P    akʁɔʃe     1
4320      accroupir  ppMS    akʁupi     2
4321      accroupir  ppFS    akʁupi     1
4354      accroupir  pi3P   akʁupis     1
4835      accélérer   inf  aksɛlɛʁe     1
5119        acheter   inf     aʃəte     4
5149        achever  ii3S     aʃəvɛ     1
5173        achever  ppFS     aʃəve     1
5308        acheter  pi1S      aʃɛt     1
6072        activer   inf    aktive     1
6883       admettre  pi1P   admɛtɔ̃     1
6996        admirer   inf    admiʁe     2
7022        admirer  ai3P   admiʁɛʁ     1
...             ...   ...       ...   ...
432691      épuiser  ppFS    ɛpɥize     1
432695      épuiser  ppMP    ɛpɥize     1
433912      établir  ppMS    ɛtabli     1
433922      établir   inf   ɛtabliʁ     1
433969      établir  pi3S    ɛtabli     1
434048         être  ii3P       ɛtɛ     4
434068         être  ii1S       ɛtɛ     7
434069         être  ii2S       ɛtɛ     1
434070         être  ii3S       ɛtɛ    71
434147       étaler  pi3S      ɛtal     1
434153       étaler   inf     ɛtale     1
434488         être    pP      ɛtɑ̃     1
434773     éteindre  pi3S      ɛtɛ̃     1
434788      étendre  ii3S    ɛtɑ̃dɛ     1
435054         être  ii2P      ɛtje     2
435172         être  ii1P     ɛtjɔ̃     3
435422      étonner  ii3S     ɛtɔnɛ     1
435425      étonner    pP    ɛtɔnɑ̃     1
435450      étonner  pc3S   ɛtɔnəʁɛ     1
435475     étouffer  ai3S     ɛtufa     1
435506     étouffer   inf     ɛtufe     1
435538     étouffer  ppMS     ɛtufe     1
435540     étouffer  ppFS     ɛtufe     2
436316         être  ppMS       ɛte    26
436831     éveiller  pi3S      ɛvɛj     1
437024     éventrer  ppMS   ɛvɑ̃tʁe     1
437295       éviter  pi3S      ɛvit     1
437301       éviter   inf     ɛvite     4
437474         être  pi2P        ɛt    16
437476         être   inf       ɛtʁ    17

[1975 rows x 4 columns]

0
CPU times: user 1min 15s, sys: 21.9 s, total: 1min 37s
Wall time: 30.5 s

nbChunk 410
4200
1980

            lexeme  case       phono  tir1
40           avoir  pi3S           a    89
108     abandonner  ai3S    abɑ̃dɔna     1
128     abandonner  pi3S     abɑ̃dɔn     3
166     abandonner  ppFS    abɑ̃dɔne     1
243        abattre  pi3S         aba     1
252        abattre  pi2S         aba     1
1175       aborder  ppMS      abɔʁde     1
1468        aboyer   inf      abwaje     1
1716       abriter  ppMS      abʁite     1
2102      absorber  ppFS     absɔʁbe     1
2967      accepter  pi3S      aksɛpt     1
2980      accepter  pc2P  aksɛptəʁje     1
3003      accepter  ppMS     aksɛpte     2
3536      accorder   inf      akɔʁde     1
3913      accouder  ppMS       akude     1
3916      accouder  ppMP       akude     1
4090      accourir  pi3S        akuʁ     1
4238     accrocher    pP     akʁɔʃɑ̃     1
4291     accrocher  ppMS      akʁɔʃe     1
4293     accrocher  ppFP      akʁɔʃe     1
4498    accueillir  pi2S        akœj     1
4511    accueillir  ppMP       akəji     1
5119       acheter   inf       aʃəte     2
5139       acheter  ppMP       aʃəte     2
5171       achever  ppMS       aʃəve     1
5311       acheter  pi3S        aʃɛt     2
5329       achever  pi1S        aʃɛv     1
5332       achever  pi3S        aʃɛv     1
6862      admettre  pi3S        admɛ     1
6891      admettre   inf      admɛtʁ     1
...            ...   ...         ...   ...
432691     épuiser  ppFS      ɛpɥize     1
433272   éradiquer   inf     ɛʁadike     1
433912     établir  ppMS      ɛtabli     1
433922     établir   inf     ɛtabliʁ     1
434048        être  ii3P         ɛtɛ     4
434068        être  ii1S         ɛtɛ     8
434070        être  ii3S         ɛtɛ    75
434726    éteindre  ii3S       ɛtɛɲɛ     1
434747    éteindre  ai3S       ɛtɛɲi     1
434777    éteindre  ppFP       ɛtɛ̃t     1
434788     étendre  ii3S      ɛtɑ̃dɛ     1
434794     étendre  pi3P       ɛtɑ̃d     1
434798     étendre  pi2P      ɛtɑ̃de     1
434821     étendre   inf      ɛtɑ̃dʁ     1
434833     étendre  ppFS      ɛtɑ̃dy     1
435054        être  ii2P        ɛtje     4
435172        être  ii1P       ɛtjɔ̃     3
435254      étirer  pi3S        ɛtiʁ     1
435422     étonner  ii3S       ɛtɔnɛ     1
435438     étonner  pi3S        ɛtɔn     1
435450     étonner  pc3S     ɛtɔnəʁɛ     1
435500    étouffer  pi3S        ɛtuf     1
435542    étouffer  ppFP       ɛtufe     1
436205     étudier   inf      ɛtydje     1
436316        être  ppMS         ɛte    27
436828    éveiller  pi1S        ɛvɛj     1
437328      éviter  ppMS       ɛvite     1
437474        être  pi2P          ɛt    11
437476        être   inf         ɛtʁ    18
437512        ôter   inf         ɔte     1

[1980 rows x 4 columns]

0
CPU times: user 1min 13s, sys: 21.4 s, total: 1min 34s
Wall time: 30.2 s

nbChunk 411
4200
1959

             lexeme  case       phono  tir1
40            avoir  pi3S           a    87
179      abasourdir  ppFS    abazuʁdi     1
1388        aboutir  ppMS       abuti     1
1674        abriter    pP     abʁitɑ̃     1
1688        abriter   inf      abʁite     1
1897        abréger  pI2P      abʁɛʒe     1
2685     acagnarder  ppFS    akaɲaʁde     1
2730       accabler  pi3S       akabl     1
2819      accaparer  ppFS     akapaʁe     1
2939       accepter  ai3S     aksɛpta     1
2971       accepter   inf     aksɛpte     1
2977       accepter  pc3S   aksɛptəʁɛ     1
3003       accepter  ppMS     aksɛpte     1
3419    accompagner  pi2S     akɔ̃paɲ     1
3655       accoster   inf      akɔste     1
4252      accrocher  pi1S       akʁɔʃ     1
4272      accrocher  pi2S       akʁɔʃ     1
4280      accrocher  pi2P      akʁɔʃe     1
4519     accueillir  ai3S       akəji     1
4652      accumuler  pi3S      akymyl     1
5119        acheter   inf       aʃəte     1
5136        acheter  ppMS       aʃəte     1
5139        acheter  ppMP       aʃəte     1
5140        achever  ai3S       aʃəva     1
5173        achever  ppFS       aʃəve     1
5315        acheter  fi3S     aʃɛtəʁa     1
5327        acheter  pi2S        aʃɛt     1
5332        achever  pi3S        aʃɛv     1
6443        adapter  ppMS      adapte     1
6481    additionner  pc3S  adisjɔnəʁɛ     1
...             ...   ...         ...   ...
432302      épouser  ppMS       ɛpuze     1
432537     éprouver  ii3S      ɛpʁuvɛ     2
432770       épurer  ppFS       ɛpyʁe     1
433061   équilibrer  ai3P   ɛkilibʁɛʁ     1
433914      établir  ppFS      ɛtabli     1
434048         être  ii3P         ɛtɛ     4
434068         être  ii1S         ɛtɛ    13
434070         être  ii3S         ɛtɛ    85
434740     éteindre  ai1S       ɛtɛɲi     1
434772     éteindre  ppMS        ɛtɛ̃     1
434773     éteindre  pi3S        ɛtɛ̃     1
434831      étendre  ppMS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     3
435172         être  ii1P       ɛtjɔ̃     4
435232       étirer  ai3S       ɛtiʁa     1
435243       étirer  ii3S       ɛtiʁɛ     1
435377      étoiler  pi3P       ɛtwal     1
435417      étonner  ai3S       ɛtɔna     1
435418      étonner  ai1S       ɛtɔnɛ     1
435422      étonner  ii3S       ɛtɔnɛ     1
435506     étouffer   inf       ɛtufe     1
435538     étouffer  ppMS       ɛtufe     1
436186      étudier  ii3S      ɛtydjɛ     1
436316         être  ppMS         ɛte    16
436547      évaluer  ppMS      ɛvalye     1
436835     éveiller   inf       ɛvɛje     2
436997     éventrer   inf     ɛvɑ̃tʁe     1
437024     éventrer  ppMS     ɛvɑ̃tʁe     1
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    15

[1959 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.8 s, total: 1min 36s
Wall time: 30.1 s

nbChunk 412
4200
1962

             lexeme  case       phono  tir1
40            avoir  pi3S           a    98
128      abandonner  pi3S     abɑ̃dɔn     2
166      abandonner  ppFS    abɑ̃dɔne     1
305         abattre  ppMS       abaty     1
1406        aboutir  fi3P    abutiʁɔ̃     1
2964       accepter  pi1S      aksɛpt     1
2971       accepter   inf     aksɛpte     4
2984       accepter  pi2S      aksɛpt     1
3003       accepter  ppMS     aksɛpte     1
3399    accompagner  pI2S     akɔ̃paɲ     1
3400    accompagner  pi3S     akɔ̃paɲ     1
3408    accompagner  fi1S  akɔ̃paɲəʁɛ     1
3422    accompagner  pi2P    akɔ̃paɲe     1
3433    accompagner  ppMS    akɔ̃paɲe     1
3436    accompagner  ppMP    akɔ̃paɲe     1
3438      accomplir  ppMS     akɔ̃pli     2
3519       accorder  ii3S      akɔʁdɛ     1
3527       accorder  pi1S       akɔʁd     1
3530       accorder  pi3S       akɔʁd     1
3536       accorder   inf      akɔʁde     1
4519     accueillir  ai3S       akəji     1
4627        acculer  ppFS       akyle     1
4716        accuser  pi3S        akyz     1
4726        accuser  pc3S     akyzəʁɛ     1
5119        acheter   inf       aʃəte     4
5136        acheter  ppMS       aʃəte     1
5137        acheter  ppFS       aʃəte     1
5157        achever   inf       aʃəve     1
5311        acheter  pi3S        aʃɛt     1
5807       acquérir  ppMS         aki     1
...             ...   ...         ...   ...
432519     éprendre  ppMS        ɛpʁi     1
432537     éprouver  ii3S      ɛpʁuvɛ     1
432657      épuiser  pi3P       ɛpɥiz     1
433238   équivaloir  pi3S       ɛkivo     1
433922      établir   inf     ɛtabliʁ     1
434048         être  ii3P         ɛtɛ     6
434068         être  ii1S         ɛtɛ    12
434070         être  ii3S         ɛtɛ    65
434072       étaler  ai3S       ɛtala     1
434734     éteindre  pi2P       ɛtɛɲe     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434768     éteindre  pi1S        ɛtɛ̃     1
434789      étendre    pP     ɛtɑ̃dɑ̃     1
434811      étendre  ai3S      ɛtɑ̃di     1
435172         être  ii1P       ɛtjɔ̃     2
435457      étonner  pi2S        ɛtɔn     1
435484     étouffer  ii3S       ɛtufɛ     1
435794    étreindre  ii3S      ɛtʁɛɲɛ     1
435795    étreindre    pP     ɛtʁɛɲɑ̃     1
435920     étriller   inf      ɛtʁije     1
436316         être  ppMS         ɛte    28
436484       évader  ppMS       ɛvade     1
436631     évanouir  ppFP      ɛvanui     1
436997     éventrer   inf     ɛvɑ̃tʁe     1
437301       éviter   inf       ɛvite     3
437407      évoluer  ppMS      ɛvɔlye     1
437458      évoquer  ppMS       ɛvɔke     1
437474         être  pi2P          ɛt    15
437476         être   inf         ɛtʁ    22
437539         ôter  ppMS         ɔte     1

[1962 rows x 4 columns]

0
CPU times: user 1min 14s, sys: 21.8 s, total: 1min 36s
Wall time: 29.4 s

nbChunk 413
4200
1938

             lexeme  case        phono  tir1
40            avoir  pi3S            a    78
102        abaisser  ppFS        abɛse     1
130      abandonner  pi3P      abɑ̃dɔn     1
132      abandonner   inf     abɑ̃dɔne     1
145      abandonner  pi2S      abɑ̃dɔn     1
272         abattre  pi2P        abate     1
2334         abuser  pI2S         abyz     1
2712       accabler  ii3P       akablɛ     1
2950       accepter  ii3S      aksɛptɛ     3
2967       accepter  pi3S       aksɛpt     1
2969       accepter  pi3P       aksɛpt     1
2971       accepter   inf      aksɛpte     2
2981       accepter  pc1P  aksɛptəʁjɔ̃     1
3005       accepter  ppFS      aksɛpte     1
3406    accompagner   inf     akɔ̃paɲe     1
3422    accompagner  pi2P     akɔ̃paɲe     1
3443      accomplir   inf     akɔ̃pliʁ     2
3464      accomplir  ii3P    akɔ̃plisɛ     1
3571       accorder  ppMS       akɔʁde     1
4259      accrocher   inf       akʁɔʃe     3
4387      accroître  ppMS         akʁy     1
4502     accueillir  ppMS        akəji     1
5119        acheter   inf        aʃəte     2
5136        acheter  ppMS        aʃəte     3
5137        acheter  ppFS        aʃəte     1
5140        achever  ai3S        aʃəva     1
5145        achever  ai1S        aʃəvɛ     1
5149        achever  ii3S        aʃəvɛ     1
5157        achever   inf        aʃəve     1
5171        achever  ppMS        aʃəve     1
...             ...   ...          ...   ...
429728      énerver  ppFS       ɛnɛʁve     1
430423      épandre  ppFP       ɛpɑ̃dy     1
431167        épier   inf         ɛpje     1
432160      épouser   inf        ɛpuze     5
432640      épuiser    pP      ɛpɥizɑ̃     1
433062   équilibrer  ppMS     ɛkilibʁe     1
433912      établir  ppMS       ɛtabli     1
434048         être  ii3P          ɛtɛ     4
434068         être  ii1S          ɛtɛ    12
434070         être  ii3S          ɛtɛ    60
434782      étendre  pi3S         ɛtɑ̃     1
434831      étendre  ppMS       ɛtɑ̃dy     1
435054         être  ii2P         ɛtje     1
435172         être  ii1P        ɛtjɔ̃     1
435417      étonner  ai3S        ɛtɔna     1
435450      étonner  pc3S      ɛtɔnəʁɛ     1
435472      étonner  ppFS        ɛtɔne     1
435794    étreindre  ii3S       ɛtʁɛɲɛ     1
435798    étreindre  pi3P        ɛtʁɛɲ     1
435968      étriper  pi3S        ɛtʁip     1
436233      étudier  ppMS       ɛtydje     2
436316         être  ppMS          ɛte    22
436453       évader  pi3S         ɛvad     1
436457       évader   inf        ɛvade     1
437273       éviter  ai3S        ɛvita     1
437285       éviter    pP       ɛvitɑ̃     1
437301       éviter   inf        ɛvite     6
437431      évoquer   inf        ɛvɔke     1
437474         être  pi2P           ɛt    19
437476         être   inf          ɛtʁ    22

[1938 rows x 4 columns]

0
CPU times: user 1min 17s, sys: 22.5 s, total: 1min 39s
Wall time: 30.2 s

nbChunk 414
4200
1967

             lexeme  case       phono  tir1
40            avoir  pi3S           a    87
164      abandonner  ppMS    abɑ̃dɔne     1
256         abattre  ii1S       abatɛ     1
305         abattre  ppMS       abaty     1
1121        aborder  ai3S      abɔʁda     1
1434        aboutir  ii1P   abutisjɔ̃     1
1468         aboyer   inf      abwaje     1
1673        abriter  ii3S      abʁitɛ     1
2100       absorber  ppMS     absɔʁbe     1
2339         abuser   inf       abyze     1
2971       accepter   inf     aksɛpte     1
2980       accepter  pc2P  aksɛptəʁje     1
2994       accepter  ii1P   aksɛptjɔ̃     1
3003       accepter  ppMS     aksɛpte     2
3433    accompagner  ppMS    akɔ̃paɲe     1
3520       accorder    pP     akɔʁdɑ̃     1
3536       accorder   inf      akɔʁde     1
3573       accorder  ppFS      akɔʁde     1
4062       accourir  ps3S        akuʁ     1
4090       accourir  pi3S        akuʁ     1
4210     accoutumer  ppMS     akutyme     1
4255      accrocher  pi3S       akʁɔʃ     1
4720        accuser   inf       akyze     1
5041       acharner  ppMS      aʃaʁne     1
5119        acheter   inf       aʃəte     3
5136        acheter  ppMS       aʃəte     2
5157        achever   inf       aʃəve     1
5311        acheter  pi3S        aʃɛt     1
5313        acheter  pi3P        aʃɛt     1
5316        acheter  fi1S     aʃɛtəʁɛ     1
...             ...   ...         ...   ...
432302      épouser  ppMS       ɛpuze     1
432519     éprendre  ppMS        ɛpʁi     1
432554     éprouver  pi3P       ɛpʁuv     1
432556     éprouver   inf      ɛpʁuve     1
434048         être  ii3P         ɛtɛ     3
434068         être  ii1S         ɛtɛ     8
434070         être  ii3S         ɛtɛ    87
434134       étaler  ii3S       ɛtalɛ     1
434302       étaler  ppMP       ɛtale     1
434762     éteindre   inf      ɛtɛ̃dʁ     1
434777     éteindre  ppFP       ɛtɛ̃t     1
434833      étendre  ppFS      ɛtɑ̃dy     1
435054         être  ii2P        ɛtje     1
435172         être  ii1P       ɛtjɔ̃     1
435444      étonner   inf       ɛtɔne     2
435472      étonner  ppFS       ɛtɔne     1
435484     étouffer  ii3S       ɛtufɛ     1
435504     étouffer  pi3P        ɛtuf     1
435894     étrenner  ppFS      ɛtʁɛne     1
436186      étudier  ii3S      ɛtydjɛ     1
436237      étudier  ppFP      ɛtydje     1
436316         être  ppMS         ɛte    20
436632     évanouir   inf     ɛvanuiʁ     1
436656     évanouir  ii3S    ɛvanuisɛ     1
436997     éventrer   inf     ɛvɑ̃tʁe     1
437301       éviter   inf       ɛvite     1
437431      évoquer   inf       ɛvɔke     1
437474         être  pi2P          ɛt    12
437476         être   inf         ɛtʁ    21
437512         ôter   inf         ɔte     1

[1967 rows x 4 columns]

0
CPU times: user 1min 16s, sys: 22 s, total: 1min 38s
Wall time: 29.8 s

nbChunk 415
4200
1925

             lexeme  case     phono  tir1
40            avoir  pi3S         a    89
113      abandonner  ii3S  abɑ̃dɔnɛ     1
166      abandonner  ppFS  abɑ̃dɔne     1
310         abattre  ppFP     abaty     1
1147        aborder   inf    abɔʁde     1
1468         aboyer   inf    abwaje     1
1668        abriter  ai3S    abʁita     1
2138       abstenir  pi2P   abstəne     1
2155       abstenir  ppFS   abstəny     1
2332         abuser  pi1S      abyz     1
2971       accepter   inf   aksɛpte     1
3313        accoler  ppMS     akɔle     1
3380    accompagner  ai3S  akɔ̃paɲa     2
3400    accompagner  pi3S   akɔ̃paɲ     1
3404    accompagner  pi3P   akɔ̃paɲ     1
3434    accompagner  ppFS  akɔ̃paɲe     1
3458      accomplir  ppMP   akɔ̃pli     1
3519       accorder  ii3S    akɔʁdɛ     1
4237      accrocher  ii3S    akʁɔʃɛ     1
4292      accrocher  ppFS    akʁɔʃe     1
4321      accroupir  ppFS    akʁupi     1
4498     accueillir  pi2S      akœj     1
4748        accuser  ppMS     akyze     1
4809      accélérer  pi1S   aksɛlɛʁ     1
5107        acheter  ai1S     aʃətɛ     1
5111        acheter  ii3S     aʃətɛ     1
5119        acheter   inf     aʃəte     3
5136        acheter  ppMS     aʃəte     1
5311        acheter  pi3S      aʃɛt     1
5832      acquitter  ii3P     akitɛ     1
...             ...   ...       ...   ...
430158     épaissir   inf    ɛpɛsiʁ     1
432160      épouser   inf     ɛpuze     1
432657      épuiser  pi3P     ɛpɥiz     1
432691      épuiser  ppFS    ɛpɥize     1
433433     érailler  ppFP     ɛʁaje     1
433912      établir  ppMS    ɛtabli     2
434048         être  ii3P       ɛtɛ     3
434068         être  ii1S       ɛtɛ    13
434070         être  ii3S       ɛtɛ    66
434773     éteindre  pi3S      ɛtɛ̃     1
434794      étendre  pi3P     ɛtɑ̃d     1
434821      étendre   inf    ɛtɑ̃dʁ     1
434827      étendre  pi1S      ɛtɑ̃     1
434831      étendre  ppMS    ɛtɑ̃dy     1
435054         être  ii2P      ɛtje     1
435172         être  ii1P     ɛtjɔ̃     3
435244       étirer    pP    ɛtiʁɑ̃     1
435294       étirer  ppFS     ɛtiʁe     1
435417      étonner  ai3S     ɛtɔna     1
435748    étrangler   inf  ɛtʁɑ̃gle     1
436205      étudier   inf    ɛtydje     1
436316         être  ppMS       ɛte    24
436402      évacuer   inf    ɛvakye     1
436835     éveiller   inf     ɛvɛje     1
437284       éviter  ii3S     ɛvitɛ     1
437301       éviter   inf     ɛvite     2
437309       éviter  fi2P   ɛvitəʁe     1
437413      évoquer  ii3P     ɛvɔkɛ     1
437474         être  pi2P        ɛt     7
437476         être   inf       ɛtʁ    21

[1925 rows x 4 columns]

# Longitudinales avec désintégration
- Pour chaque échantillon *i*, on propage les tirages à *i+1* en les divisant par *pDivision* (par exemple 2) pour tenir compte de la désintégration.
- La désintégration est complète quand un tirage devient inférieur au seuil *vDesintegration*. La forme en question disparaît de l'échantillon.  
Le seuil est : $${vDesintegration}=\frac{1}{{pDivision}^{cDesintegration}}$$

Autrement dit pour un élément tiré une fois dans un échantillon et plus par la suite, sa trace disparaît après *cDesintegration* tirages.

In [108]:
pDivision=2
cDesintegration=7
vDesintegration=float(1)/pDivision**cDesintegration
vDesintegration

0.0078125

In [5]:
lSamples=glob.glob(repDesintegrationSamples+"*.csv")
repDesintegrationLongitudinales='/Users/gilles/sDrive/Recherche/Boye/HDR/Data/Desintegration/Desintegration-Longitudinales/'

In [110]:
df0=pd.read_csv(lSamples[0],sep="\t",encoding="utf8",index_col=[0,1,2,3])
df0["tir2"]=(df0["tir1"]/pDivision).astype(float)
df0.to_csv(path_or_buf=repDesintegrationLongitudinales+"DSL-%03d-%d-%d-%d.csv"%(0,chunk,pDivision,cDesintegration),sep="\t",encoding="utf8")
df0=df0.rename(columns={"tir1":"tir0", "tir2":"tir1"})
df0.head()

                               tir0  tir1
     lexeme     case phono
40   avoir      pi3S a           95  47.5
132  abandonner inf  abɑ̃dɔne     2   1.0
164  abandonner ppMS abɑ̃dɔne     1   0.5
243  abattre    pi3S aba          1   0.5
1441 abouter    pI1P abutɔ̃       1   0.5

df1=pd.read_csv(lSamples[1],sep="\t",encoding="utf8",index_col=[0,1,2,3])
df1["tir2"]=df1["tir1"]
df1=df1.add(df0,fill_value=0)
df2=df1[df1.tir1>=0.5][["tir1","tir2"]]
df2["tir2"]=df2["tir1"]/2
df2

In [111]:
for i in range(1,len(lSamples[:])):
    df1=pd.read_csv(lSamples[i],sep="\t",encoding="utf8",index_col=[0,1,2,3])
    df1["tir2"]=df1["tir1"]
    df1=df1.add(df0,fill_value=0)
    # display(df1.head())
    df2=df1[df1.tir1>=vDesintegration][["tir1","tir2"]]
    df2["tir2"]=df2["tir1"]/pDivision
    display(df2.head())
    df2.to_csv(path_or_buf=repDesintegrationLongitudinales+"DSL-%03d-%d-%d-%d.csv"%(i,chunk,pDivision,cDesintegration),sep="\t",encoding="utf8")
    df0=df2
    df0=df0.rename(columns={"tir1":"tir0", "tir2":"tir1"})

                               tir1   tir2
    lexeme     case phono
40  avoir      pi3S a         148.5  74.25
132 abandonner inf  abɑ̃dɔne    1.0   0.50
145 abandonner pi2S abɑ̃dɔn     1.0   0.50
164 abandonner ppMS abɑ̃dɔne    1.5   0.75
243 abattre    pi3S aba         0.5   0.25

                                tir1    tir2
    lexeme     case phono
40  avoir      pi3S a         156.25  78.125
128 abandonner pi3S abɑ̃dɔn     2.00   1.000
132 abandonner inf  abɑ̃dɔne    2.50   1.250
145 abandonner pi2S abɑ̃dɔn     0.50   0.250
164 abandonner ppMS abɑ̃dɔne    0.75   0.375

                                 tir1     tir2
    lexeme     case phono
40  avoir      pi3S a         152.125  76.0625
73  abaisser   inf  abɛse       1.000   0.5000
128 abandonner pi3S abɑ̃dɔn     1.000   0.5000
132 abandonner inf  abɑ̃dɔne    3.250   1.6250
145 abandonner pi2S abɑ̃dɔn     0.250   0.1250

                                    tir1      tir2
    lexeme     case phono
40  avoir      pi3S a           160.0625  80.03125
73  abaisser   inf  abɛse         0.5000   0.25000
128 abandonner pi3S abɑ̃dɔn       1.5000   0.75000
132 abandonner inf  abɑ̃dɔne      4.6250   2.31250
133 abandonner fi3S abɑ̃dɔnəʁa    1.0000   0.50000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a           175.03125  87.515625
73  abaisser   inf  abɛse         0.25000   0.125000
128 abandonner pi3S abɑ̃dɔn       0.75000   0.375000
132 abandonner inf  abɑ̃dɔne      3.31250   1.656250
133 abandonner fi3S abɑ̃dɔnəʁa    0.50000   0.250000

                                      tir1       tir2
    lexeme     case phono
40  avoir      pi3S a           181.515625  90.757812
73  abaisser   inf  abɛse         0.125000   0.062500
128 abandonner pi3S abɑ̃dɔn       0.375000   0.187500
132 abandonner inf  abɑ̃dɔne      2.656250   1.328125
133 abandonner fi3S abɑ̃dɔnəʁa    0.250000   0.125000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         186.757812  93.378906
73  abaisser   inf  abɛse       0.062500   0.031250
125 abandonner pi1S abɑ̃dɔn     1.000000   0.500000
128 abandonner pi3S abɑ̃dɔn     1.187500   0.593750
132 abandonner inf  abɑ̃dɔne    2.328125   1.164062

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         164.378906  82.189453
73  abaisser   inf  abɛse       0.031250   0.015625
125 abandonner pi1S abɑ̃dɔn     1.500000   0.750000
128 abandonner pi3S abɑ̃dɔn     1.593750   0.796875
132 abandonner inf  abɑ̃dɔne    1.164062   0.582031

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         176.189453  88.094727
73  abaisser   inf  abɛse       0.015625   0.007812
125 abandonner pi1S abɑ̃dɔn     0.750000   0.375000
128 abandonner pi3S abɑ̃dɔn     0.796875   0.398438
132 abandonner inf  abɑ̃dɔne    1.582031   0.791016

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         161.094727  80.547363
73  abaisser   inf  abɛse       0.007812   0.003906
113 abandonner ii3S abɑ̃dɔnɛ    1.000000   0.500000
125 abandonner pi1S abɑ̃dɔn     0.375000   0.187500
128 abandonner pi3S abɑ̃dɔn     0.398438   0.199219

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         161.547363  80.773682
113 abandonner ii3S abɑ̃dɔnɛ    0.500000   0.250000
125 abandonner pi1S abɑ̃dɔn     0.187500   0.093750
128 abandonner pi3S abɑ̃dɔn     1.199219   0.599609
132 abandonner inf  abɑ̃dɔne    0.895508   0.447754

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         150.773682  75.386841
111 abandonner ii1S abɑ̃dɔnɛ    1.000000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ    0.250000   0.125000
125 abandonner pi1S abɑ̃dɔn     0.093750   0.046875
128 abandonner pi3S abɑ̃dɔn     0.599609   0.299805

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         159.386841  79.693420
111 abandonner ii1S abɑ̃dɔnɛ    0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ    0.125000   0.062500
125 abandonner pi1S abɑ̃dɔn     0.046875   0.023438
128 abandonner pi3S abɑ̃dɔn     1.299805   0.649902

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         168.693420  84.346710
111 abandonner ii1S abɑ̃dɔnɛ    0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ    0.062500   0.031250
125 abandonner pi1S abɑ̃dɔn     0.023438   0.011719
128 abandonner pi3S abɑ̃dɔn     0.649902   0.324951

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         182.346710  91.173355
111 abandonner ii1S abɑ̃dɔnɛ    0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ    0.031250   0.015625
125 abandonner pi1S abɑ̃dɔn     0.011719   0.005859
128 abandonner pi3S abɑ̃dɔn     0.324951   0.162476

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         179.173355  89.586678
111 abandonner ii1S abɑ̃dɔnɛ    0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ    0.015625   0.007812
128 abandonner pi3S abɑ̃dɔn     0.162476   0.081238
130 abandonner pi3P abɑ̃dɔn     0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         168.586678  84.293339
111 abandonner ii1S abɑ̃dɔnɛ    0.031250   0.015625
113 abandonner ii3S abɑ̃dɔnɛ    0.007812   0.003906
128 abandonner pi3S abɑ̃dɔn     1.081238   0.540619
130 abandonner pi3P abɑ̃dɔn     0.250000   0.125000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         175.293339  87.646669
101 abaisser   ppMS abɛse       1.000000   0.500000
111 abandonner ii1S abɑ̃dɔnɛ    0.015625   0.007812
128 abandonner pi3S abɑ̃dɔn     0.540619   0.270309
130 abandonner pi3P abɑ̃dɔn     0.125000   0.062500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         179.646669  89.823335
101 abaisser   ppMS abɛse       0.500000   0.250000
111 abandonner ii1S abɑ̃dɔnɛ    0.007812   0.003906
128 abandonner pi3S abɑ̃dɔn     0.270309   0.135155
130 abandonner pi3P abɑ̃dɔn     1.062500   0.531250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         163.823335  81.911667
101 abaisser   ppMS abɛse       0.250000   0.125000
128 abandonner pi3S abɑ̃dɔn     0.135155   0.067577
130 abandonner pi3P abɑ̃dɔn     0.531250   0.265625
132 abandonner inf  abɑ̃dɔne    2.072062   1.036031

                                   tir1       tir2
    lexeme     case phono
40  avoir      pi3S a        168.911667  84.455834
73  abaisser   inf  abɛse      1.000000   0.500000
101 abaisser   ppMS abɛse      0.125000   0.062500
128 abandonner pi3S abɑ̃dɔn    0.067577   0.033789
130 abandonner pi3P abɑ̃dɔn    0.265625   0.132812

                                   tir1       tir2
    lexeme     case phono
40  avoir      pi3S a        156.455834  78.227917
73  abaisser   inf  abɛse      0.500000   0.250000
101 abaisser   ppMS abɛse      0.062500   0.031250
128 abandonner pi3S abɑ̃dɔn    0.033789   0.016894
130 abandonner pi3P abɑ̃dɔn    0.132812   0.066406

                                   tir1       tir2
    lexeme     case phono
40  avoir      pi3S a        163.227917  81.613958
73  abaisser   inf  abɛse      0.250000   0.125000
101 abaisser   ppMS abɛse      0.031250   0.015625
128 abandonner pi3S abɑ̃dɔn    0.016894   0.008447
130 abandonner pi3P abɑ̃dɔn    0.066406   0.033203

                                   tir1       tir2
    lexeme     case phono
40  avoir      pi3S a        181.613958  90.806979
73  abaisser   inf  abɛse      0.125000   0.062500
101 abaisser   ppMS abɛse      0.015625   0.007812
128 abandonner pi3S abɑ̃dɔn    0.008447   0.004224
130 abandonner pi3P abɑ̃dɔn    0.033203   0.016602

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         166.806979  83.403490
73  abaisser   inf  abɛse       0.062500   0.031250
101 abaisser   ppMS abɛse       0.007812   0.003906
130 abandonner pi3P abɑ̃dɔn     0.016602   0.008301
132 abandonner inf  abɑ̃dɔne    1.814752   0.907376

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         171.403490  85.701745
73  abaisser   inf  abɛse       0.031250   0.015625
108 abandonner ai3S abɑ̃dɔna    1.000000   0.500000
128 abandonner pi3S abɑ̃dɔn     1.000000   0.500000
130 abandonner pi3P abɑ̃dɔn     0.008301   0.004150

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         197.701745  98.850872
73  abaisser   inf  abɛse       0.015625   0.007812
108 abandonner ai3S abɑ̃dɔna    0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ    1.000000   0.500000
128 abandonner pi3S abɑ̃dɔn     0.500000   0.250000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          186.850872  93.425436
73  abaisser   inf  abɛse        0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna     0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ     0.500000   0.250000
114 abandonner pP   abɑ̃dɔnɑ̃    1.000000   0.500000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          198.425436  99.212718
108 abandonner ai3S abɑ̃dɔna     0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ     0.250000   0.125000
114 abandonner pP   abɑ̃dɔnɑ̃    0.500000   0.250000
125 abandonner pi1S abɑ̃dɔn      1.000000   0.500000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          187.212718  93.606359
108 abandonner ai3S abɑ̃dɔna     0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ     0.125000   0.062500
114 abandonner pP   abɑ̃dɔnɑ̃    0.250000   0.125000
125 abandonner pi1S abɑ̃dɔn      0.500000   0.250000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          197.606359  98.803180
108 abandonner ai3S abɑ̃dɔna     0.031250   0.015625
113 abandonner ii3S abɑ̃dɔnɛ     0.062500   0.031250
114 abandonner pP   abɑ̃dɔnɑ̃    0.125000   0.062500
125 abandonner pi1S abɑ̃dɔn      0.250000   0.125000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          188.803180  94.401590
108 abandonner ai3S abɑ̃dɔna     0.015625   0.007812
113 abandonner ii3S abɑ̃dɔnɛ     1.031250   0.515625
114 abandonner pP   abɑ̃dɔnɑ̃    0.062500   0.031250
125 abandonner pi1S abɑ̃dɔn      0.125000   0.062500

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          195.401590  97.700795
45  abaisser   ai3S abɛsa        1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna     0.007812   0.003906
113 abandonner ii3S abɑ̃dɔnɛ     0.515625   0.257812
114 abandonner pP   abɑ̃dɔnɑ̃    0.031250   0.015625

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          184.700795  92.350397
45  abaisser   ai3S abɛsa        0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ     0.257812   0.128906
114 abandonner pP   abɑ̃dɔnɑ̃    0.015625   0.007812
125 abandonner pi1S abɑ̃dɔn      0.031250   0.015625

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          194.350397  97.175199
45  abaisser   ai3S abɛsa        0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ     0.128906   0.064453
114 abandonner pP   abɑ̃dɔnɑ̃    0.007812   0.003906
125 abandonner pi1S abɑ̃dɔn      0.015625   0.007812

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         179.175199  89.587599
45  abaisser   ai3S abɛsa       0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ    0.064453   0.032227
125 abandonner pi1S abɑ̃dɔn     0.007812   0.003906
128 abandonner pi3S abɑ̃dɔn     0.625977   0.312988

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         179.587599  89.793800
45  abaisser   ai3S abɛsa       0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ    0.032227   0.016113
128 abandonner pi3S abɑ̃dɔn     1.312988   0.656494
132 abandonner inf  abɑ̃dɔne    0.123490   0.061745

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         178.793800  89.396900
45  abaisser   ai3S abɛsa       0.031250   0.015625
113 abandonner ii3S abɑ̃dɔnɛ    0.016113   0.008057
128 abandonner pi3S abɑ̃dɔn     0.656494   0.328247
132 abandonner inf  abɑ̃dɔne    0.061745   0.030872

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         175.396900  87.698450
45  abaisser   ai3S abɛsa       0.015625   0.007812
100 abaisser   ai3P abɛsɛʁ      1.000000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ    0.008057   0.004028
128 abandonner pi3S abɑ̃dɔn     0.328247   0.164124

                                   tir1       tir2
    lexeme     case phono
40  avoir      pi3S a        175.698450  87.849225
45  abaisser   ai3S abɛsa      0.007812   0.003906
100 abaisser   ai3P abɛsɛʁ     0.500000   0.250000
128 abandonner pi3S abɑ̃dɔn    0.164124   0.082062
129 abandonner ps3S abɑ̃dɔn    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         183.849225  91.924612
67  abaisser   pi3S abɛs        1.000000   0.500000
100 abaisser   ai3P abɛsɛʁ      0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ    1.000000   0.500000
128 abandonner pi3S abɑ̃dɔn     2.082062   1.041031

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         185.924612  92.962306
67  abaisser   pi3S abɛs        0.500000   0.250000
100 abaisser   ai3P abɛsɛʁ      0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ    1.500000   0.750000
128 abandonner pi3S abɑ̃dɔn     2.041031   1.020515

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         163.962306  81.981153
52  abaisser   pP   abɛsɑ̃      1.000000   0.500000
67  abaisser   pi3S abɛs        0.250000   0.125000
100 abaisser   ai3P abɛsɛʁ      0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ    0.750000   0.375000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         157.981153  78.990577
52  abaisser   pP   abɛsɑ̃      0.500000   0.250000
67  abaisser   pi3S abɛs        1.125000   0.562500
100 abaisser   ai3P abɛsɛʁ      0.031250   0.015625
113 abandonner ii3S abɑ̃dɔnɛ    0.375000   0.187500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         162.990577  81.495288
52  abaisser   pP   abɛsɑ̃      0.250000   0.125000
67  abaisser   pi3S abɛs        0.562500   0.281250
100 abaisser   ai3P abɛsɛʁ      0.015625   0.007812
113 abandonner ii3S abɑ̃dɔnɛ    1.187500   0.593750

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         156.495288  78.247644
52  abaisser   pP   abɛsɑ̃      0.125000   0.062500
67  abaisser   pi3S abɛs        0.281250   0.140625
100 abaisser   ai3P abɛsɛʁ      0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna    1.000000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         149.247644  74.623822
52  abaisser   pP   abɛsɑ̃      1.062500   0.531250
67  abaisser   pi3S abɛs        0.140625   0.070312
108 abandonner ai3S abɑ̃dɔna    0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ    0.296875   0.148438

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         154.623822  77.311911
52  abaisser   pP   abɛsɑ̃      0.531250   0.265625
67  abaisser   pi3S abɛs        0.070312   0.035156
108 abandonner ai3S abɑ̃dɔna    0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ    0.148438   0.074219

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         159.311911  79.655956
52  abaisser   pP   abɛsɑ̃      0.265625   0.132812
67  abaisser   pi3S abɛs        0.035156   0.017578
108 abandonner ai3S abɑ̃dɔna    0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ    0.074219   0.037109

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         158.655956  79.327978
52  abaisser   pP   abɛsɑ̃      0.132812   0.066406
67  abaisser   pi3S abɛs        0.017578   0.008789
108 abandonner ai3S abɑ̃dɔna    0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ    0.037109   0.018555

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         168.327978  84.163989
52  abaisser   pP   abɛsɑ̃      0.066406   0.033203
67  abaisser   pi3S abɛs        0.008789   0.004395
108 abandonner ai3S abɑ̃dɔna    0.031250   0.015625
111 abandonner ii1S abɑ̃dɔnɛ    1.000000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         154.163989  77.081994
52  abaisser   pP   abɛsɑ̃      0.033203   0.016602
108 abandonner ai3S abɑ̃dɔna    0.015625   0.007812
109 abandonner ai1S abɑ̃dɔnɛ    1.000000   0.500000
111 abandonner ii1S abɑ̃dɔnɛ    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         186.081994  93.040997
52  abaisser   pP   abɛsɑ̃      0.016602   0.008301
67  abaisser   pi3S abɛs        1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna    0.007812   0.003906
109 abandonner ai1S abɑ̃dɔnɛ    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         179.040997  89.520499
52  abaisser   pP   abɛsɑ̃      0.008301   0.004150
67  abaisser   pi3S abɛs        0.500000   0.250000
109 abandonner ai1S abɑ̃dɔnɛ    0.250000   0.125000
111 abandonner ii1S abɑ̃dɔnɛ    0.125000   0.062500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         175.520499  87.760249
67  abaisser   pi3S abɛs        0.250000   0.125000
109 abandonner ai1S abɑ̃dɔnɛ    0.125000   0.062500
111 abandonner ii1S abɑ̃dɔnɛ    0.062500   0.031250
128 abandonner pi3S abɑ̃dɔn     0.579839   0.289919

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         174.760249  87.380125
67  abaisser   pi3S abɛs        1.125000   0.562500
109 abandonner ai1S abɑ̃dɔnɛ    0.062500   0.031250
111 abandonner ii1S abɑ̃dɔnɛ    1.031250   0.515625
125 abandonner pi1S abɑ̃dɔn     1.000000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         167.380125  83.690062
67  abaisser   pi3S abɛs        0.562500   0.281250
109 abandonner ai1S abɑ̃dɔnɛ    0.031250   0.015625
111 abandonner ii1S abɑ̃dɔnɛ    0.515625   0.257812
113 abandonner ii3S abɑ̃dɔnɛ    1.000000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         168.690062  84.345031
67  abaisser   pi3S abɛs        0.281250   0.140625
109 abandonner ai1S abɑ̃dɔnɛ    0.015625   0.007812
111 abandonner ii1S abɑ̃dɔnɛ    0.257812   0.128906
113 abandonner ii3S abɑ̃dɔnɛ    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         176.345031  88.172516
67  abaisser   pi3S abɛs        0.140625   0.070312
109 abandonner ai1S abɑ̃dɔnɛ    0.007812   0.003906
111 abandonner ii1S abɑ̃dɔnɛ    0.128906   0.064453
113 abandonner ii3S abɑ̃dɔnɛ    0.250000   0.125000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          189.172516  94.586258
67  abaisser   pi3S abɛs         0.070312   0.035156
111 abandonner ii1S abɑ̃dɔnɛ     0.064453   0.032227
113 abandonner ii3S abɑ̃dɔnɛ     0.125000   0.062500
114 abandonner pP   abɑ̃dɔnɑ̃    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         181.586258  90.793129
67  abaisser   pi3S abɛs        0.035156   0.017578
73  abaisser   inf  abɛse       1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna    1.000000   0.500000
111 abandonner ii1S abɑ̃dɔnɛ    0.032227   0.016113

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         182.793129  91.396564
67  abaisser   pi3S abɛs        0.017578   0.008789
73  abaisser   inf  abɛse       0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna    0.500000   0.250000
111 abandonner ii1S abɑ̃dɔnɛ    0.016113   0.008057

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         179.396564  89.698282
67  abaisser   pi3S abɛs        0.008789   0.004395
73  abaisser   inf  abɛse       0.250000   0.125000
108 abandonner ai3S abɑ̃dɔna    1.250000   0.625000
111 abandonner ii1S abɑ̃dɔnɛ    0.008057   0.004028

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         175.698282  87.849141
73  abaisser   inf  abɛse       0.125000   0.062500
108 abandonner ai3S abɑ̃dɔna    1.625000   0.812500
109 abandonner ai1S abɑ̃dɔnɛ    1.000000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ    0.007812   0.003906

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          148.849141  74.424571
73  abaisser   inf  abɛse        0.062500   0.031250
108 abandonner ai3S abɑ̃dɔna     2.812500   1.406250
109 abandonner ai1S abɑ̃dɔnɛ     0.500000   0.250000
114 abandonner pP   abɑ̃dɔnɑ̃    0.265625   0.132812

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         169.424571  84.712285
50  abaisser   ii3S abɛsɛ       1.000000   0.500000
73  abaisser   inf  abɛse       0.031250   0.015625
101 abaisser   ppMS abɛse       1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna    1.406250   0.703125

                                tir1       tir2
    lexeme   case phono
40  avoir    pi3S a       173.712285  86.856143
50  abaisser ii3S abɛsɛ     0.500000   0.250000
52  abaisser pP   abɛsɑ̃    1.000000   0.500000
73  abaisser inf  abɛse     0.015625   0.007812
101 abaisser ppMS abɛse     0.500000   0.250000

                                tir1       tir2
   lexeme   case phono
40 avoir    pi3S a        175.856143  87.928071
50 abaisser ii3S abɛsɛ      2.250000   1.125000
52 abaisser pP   abɛsɑ̃     0.500000   0.250000
73 abaisser inf  abɛse      0.007812   0.003906
78 abaisser pc2S abɛsəʁɛ    1.000000   0.500000

                                 tir1       tir2
    lexeme   case phono
40  avoir    pi3S a        159.928071  79.964036
50  abaisser ii3S abɛsɛ      1.125000   0.562500
52  abaisser pP   abɛsɑ̃     0.250000   0.125000
78  abaisser pc2S abɛsəʁɛ    0.500000   0.250000
101 abaisser ppMS abɛse      0.125000   0.062500

                                 tir1       tir2
    lexeme   case phono
40  avoir    pi3S a        174.964036  87.482018
50  abaisser ii3S abɛsɛ      0.562500   0.281250
52  abaisser pP   abɛsɑ̃     0.125000   0.062500
78  abaisser pc2S abɛsəʁɛ    0.250000   0.125000
101 abaisser ppMS abɛse      0.062500   0.031250

                                tir1       tir2
   lexeme   case phono
40 avoir    pi3S a        187.482018  93.741009
50 abaisser ii3S abɛsɛ      0.281250   0.140625
52 abaisser pP   abɛsɑ̃     0.062500   0.031250
71 abaisser pi3P abɛs       1.000000   0.500000
78 abaisser pc2S abɛsəʁɛ    0.125000   0.062500

                                tir1       tir2
   lexeme   case phono
40 avoir    pi3S a        157.741009  78.870504
50 abaisser ii3S abɛsɛ      1.140625   0.570312
52 abaisser pP   abɛsɑ̃     0.031250   0.015625
71 abaisser pi3P abɛs       0.500000   0.250000
78 abaisser pc2S abɛsəʁɛ    0.062500   0.031250

                                tir1       tir2
   lexeme   case phono
40 avoir    pi3S a        158.870504  79.435252
50 abaisser ii3S abɛsɛ      0.570312   0.285156
52 abaisser pP   abɛsɑ̃     0.015625   0.007812
71 abaisser pi3P abɛs       0.250000   0.125000
78 abaisser pc2S abɛsəʁɛ    0.031250   0.015625

                               tir1       tir2
   lexeme   case phono
40 avoir    pi3S a       195.435252  97.717626
50 abaisser ii3S abɛsɛ     0.285156   0.142578
52 abaisser pP   abɛsɑ̃    0.007812   0.003906
67 abaisser pi3S abɛs      1.000000   0.500000
71 abaisser pi3P abɛs      0.125000   0.062500

                              tir1       tir2
   lexeme   case phono
40 avoir    pi3S a      191.717626  95.858813
50 abaisser ii3S abɛsɛ    0.142578   0.071289
67 abaisser pi3S abɛs     0.500000   0.250000
71 abaisser pi3P abɛs     0.062500   0.031250
73 abaisser inf  abɛse    1.000000   0.500000

                              tir1       tir2
   lexeme   case phono
40 avoir    pi3S a      195.858813  97.929407
50 abaisser ii3S abɛsɛ    0.071289   0.035645
67 abaisser pi3S abɛs     0.250000   0.125000
71 abaisser pi3P abɛs     0.031250   0.015625
73 abaisser inf  abɛse    0.500000   0.250000

                              tir1       tir2
   lexeme   case phono
40 avoir    pi3S a      189.929407  94.964703
50 abaisser ii3S abɛsɛ    0.035645   0.017822
67 abaisser pi3S abɛs     0.125000   0.062500
71 abaisser pi3P abɛs     0.015625   0.007812
73 abaisser inf  abɛse    0.250000   0.125000

                              tir1       tir2
   lexeme   case phono
40 avoir    pi3S a      199.964703  99.982352
50 abaisser ii3S abɛsɛ    0.017822   0.008911
67 abaisser pi3S abɛs     0.062500   0.031250
71 abaisser pi3P abɛs     0.007812   0.003906
73 abaisser inf  abɛse    0.125000   0.062500

                               tir1       tir2
    lexeme   case phono
40  avoir    pi3S a      181.982352  90.991176
50  abaisser ii3S abɛsɛ    0.008911   0.004456
67  abaisser pi3S abɛs     0.031250   0.015625
73  abaisser inf  abɛse    0.062500   0.031250
101 abaisser ppMS abɛse    0.062500   0.031250

                               tir1       tir2
    lexeme   case phono
40  avoir    pi3S a      176.991176  88.495588
45  abaisser ai3S abɛsa    1.000000   0.500000
67  abaisser pi3S abɛs     0.015625   0.007812
73  abaisser inf  abɛse    0.031250   0.015625
101 abaisser ppMS abɛse    0.031250   0.015625

                               tir1       tir2
    lexeme   case phono
40  avoir    pi3S a      170.495588  85.247794
45  abaisser ai3S abɛsa    1.500000   0.750000
67  abaisser pi3S abɛs     1.007812   0.503906
73  abaisser inf  abɛse    0.015625   0.007812
101 abaisser ppMS abɛse    0.015625   0.007812

                               tir1       tir2
    lexeme   case phono
40  avoir    pi3S a      183.247794  91.623897
45  abaisser ai3S abɛsa    0.750000   0.375000
67  abaisser pi3S abɛs     0.503906   0.251953
73  abaisser inf  abɛse    0.007812   0.003906
101 abaisser ppMS abɛse    0.007812   0.003906

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         170.623897  85.311948
45  abaisser   ai3S abɛsa       0.375000   0.187500
67  abaisser   pi3S abɛs        0.251953   0.125977
108 abandonner ai3S abɑ̃dɔna    0.250987   0.125494
109 abandonner ai1S abɑ̃dɔnɛ    0.125000   0.062500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         158.311948  79.155974
45  abaisser   ai3S abɛsa       0.187500   0.093750
67  abaisser   pi3S abɛs        0.125977   0.062988
108 abandonner ai3S abɑ̃dɔna    0.125494   0.062747
109 abandonner ai1S abɑ̃dɔnɛ    1.062500   0.531250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         177.155974  88.577987
45  abaisser   ai3S abɛsa       0.093750   0.046875
67  abaisser   pi3S abɛs        0.062988   0.031494
108 abandonner ai3S abɑ̃dɔna    0.062747   0.031373
109 abandonner ai1S abɑ̃dɔnɛ    0.531250   0.265625

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         165.577987  82.788994
45  abaisser   ai3S abɛsa       0.046875   0.023438
67  abaisser   pi3S abɛs        0.031494   0.015747
108 abandonner ai3S abɑ̃dɔna    0.031373   0.015687
109 abandonner ai1S abɑ̃dɔnɛ    0.265625   0.132812

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         180.788994  90.394497
45  abaisser   ai3S abɛsa       0.023438   0.011719
67  abaisser   pi3S abɛs        0.015747   0.007874
108 abandonner ai3S abɑ̃dɔna    0.015687   0.007843
109 abandonner ai1S abɑ̃dɔnɛ    0.132812   0.066406

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         174.394497  87.197248
45  abaisser   ai3S abɛsa       0.011719   0.005859
67  abaisser   pi3S abɛs        0.007874   0.003937
108 abandonner ai3S abɑ̃dɔna    0.007843   0.003922
109 abandonner ai1S abɑ̃dɔnɛ    0.066406   0.033203

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          167.197248  83.598624
109 abandonner ai1S abɑ̃dɔnɛ     0.033203   0.016602
114 abandonner pP   abɑ̃dɔnɑ̃    0.062500   0.031250
125 abandonner pi1S abɑ̃dɔn      0.035156   0.017578
132 abandonner inf  abɑ̃dɔne     3.352711   1.676356

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          171.598624  85.799312
109 abandonner ai1S abɑ̃dɔnɛ     0.016602   0.008301
113 abandonner ii3S abɑ̃dɔnɛ     1.000000   0.500000
114 abandonner pP   abɑ̃dɔnɑ̃    1.031250   0.515625
125 abandonner pi1S abɑ̃dɔn      0.017578   0.008789

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          177.799312  88.899656
108 abandonner ai3S abɑ̃dɔna     1.000000   0.500000
109 abandonner ai1S abɑ̃dɔnɛ     0.008301   0.004150
113 abandonner ii3S abɑ̃dɔnɛ     0.500000   0.250000
114 abandonner pP   abɑ̃dɔnɑ̃    0.515625   0.257812

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          183.899656  91.949828
108 abandonner ai3S abɑ̃dɔna     0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ     0.250000   0.125000
114 abandonner pP   abɑ̃dɔnɑ̃    0.257812   0.128906
130 abandonner pi3P abɑ̃dɔn      0.500000   0.250000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          181.949828  90.974914
108 abandonner ai3S abɑ̃dɔna     1.250000   0.625000
113 abandonner ii3S abɑ̃dɔnɛ     1.125000   0.562500
114 abandonner pP   abɑ̃dɔnɑ̃    0.128906   0.064453
130 abandonner pi3P abɑ̃dɔn      0.250000   0.125000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          178.974914  89.487457
108 abandonner ai3S abɑ̃dɔna     0.625000   0.312500
113 abandonner ii3S abɑ̃dɔnɛ     0.562500   0.281250
114 abandonner pP   abɑ̃dɔnɑ̃    0.064453   0.032227
130 abandonner pi3P abɑ̃dɔn      0.125000   0.062500

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          168.487457  84.243729
108 abandonner ai3S abɑ̃dɔna     0.312500   0.156250
109 abandonner ai1S abɑ̃dɔnɛ     1.000000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ     0.281250   0.140625
114 abandonner pP   abɑ̃dɔnɑ̃    0.032227   0.016113

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         172.243729  86.121864
50  abaisser   ii3S abɛsɛ       1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna    0.156250   0.078125
109 abandonner ai1S abɑ̃dɔnɛ    0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ    0.140625   0.070312

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         182.121864  91.060932
50  abaisser   ii3S abɛsɛ       0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna    0.078125   0.039062
109 abandonner ai1S abɑ̃dɔnɛ    0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ    1.070312   0.535156

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         175.060932  87.530466
50  abaisser   ii3S abɛsɛ       0.250000   0.125000
108 abandonner ai3S abɑ̃dɔna    0.039062   0.019531
109 abandonner ai1S abɑ̃dɔnɛ    1.125000   0.562500
113 abandonner ii3S abɑ̃dɔnɛ    1.535156   0.767578

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         171.530466  85.765233
50  abaisser   ii3S abɛsɛ       0.125000   0.062500
102 abaisser   ppFS abɛse       1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna    0.019531   0.009766
109 abandonner ai1S abɑ̃dɔnɛ    0.562500   0.281250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         169.765233  84.882617
50  abaisser   ii3S abɛsɛ       0.062500   0.031250
102 abaisser   ppFS abɛse       0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna    0.009766   0.004883
109 abandonner ai1S abɑ̃dɔnɛ    1.281250   0.640625

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         172.882617  86.441308
50  abaisser   ii3S abɛsɛ       0.031250   0.015625
102 abaisser   ppFS abɛse       0.250000   0.125000
109 abandonner ai1S abɑ̃dɔnɛ    0.640625   0.320312
113 abandonner ii3S abɑ̃dɔnɛ    0.191895   0.095947

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         159.441308  79.720654
50  abaisser   ii3S abɛsɛ       0.015625   0.007812
102 abaisser   ppFS abɛse       0.125000   0.062500
109 abandonner ai1S abɑ̃dɔnɛ    0.320312   0.160156
113 abandonner ii3S abɑ̃dɔnɛ    0.095947   0.047974

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         166.720654  83.360327
50  abaisser   ii3S abɛsɛ       0.007812   0.003906
102 abaisser   ppFS abɛse       0.062500   0.031250
109 abandonner ai1S abɑ̃dɔnɛ    0.160156   0.080078
113 abandonner ii3S abɑ̃dɔnɛ    0.047974   0.023987

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         163.360327  81.680164
102 abaisser   ppFS abɛse       0.031250   0.015625
109 abandonner ai1S abɑ̃dɔnɛ    0.080078   0.040039
113 abandonner ii3S abɑ̃dɔnɛ    1.023987   0.511993
128 abandonner pi3S abɑ̃dɔn     1.378906   0.689453

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         172.680164  86.340082
102 abaisser   ppFS abɛse       0.015625   0.007812
109 abandonner ai1S abɑ̃dɔnɛ    0.040039   0.020020
113 abandonner ii3S abɑ̃dɔnɛ    0.511993   0.255997
125 abandonner pi1S abɑ̃dɔn     1.000000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         162.340082  81.170041
102 abaisser   ppFS abɛse       0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna    1.000000   0.500000
109 abandonner ai1S abɑ̃dɔnɛ    0.020020   0.010010
110 abandonner ii3P abɑ̃dɔnɛ    1.000000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         162.170041  81.085020
108 abandonner ai3S abɑ̃dɔna    0.500000   0.250000
109 abandonner ai1S abɑ̃dɔnɛ    0.010010   0.005005
110 abandonner ii3P abɑ̃dɔnɛ    0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ    0.127998   0.063999

                                    tir1      tir2
    lexeme     case phono
40  avoir      pi3S a         167.085020  83.54251
104 abaisser   ppMP abɛse       1.000000   0.50000
108 abandonner ai3S abɑ̃dɔna    0.250000   0.12500
110 abandonner ii3P abɑ̃dɔnɛ    0.250000   0.12500
113 abandonner ii3S abɑ̃dɔnɛ    0.063999   0.03200

                                   tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         168.54251  84.271255
45  abaisser   ai3S abɛsa       1.00000   0.500000
104 abaisser   ppMP abɛse       0.50000   0.250000
108 abandonner ai3S abɑ̃dɔna    2.12500   1.062500
110 abandonner ii3P abɑ̃dɔnɛ    0.12500   0.062500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         170.271255  85.135628
45  abaisser   ai3S abɛsa       0.500000   0.250000
104 abaisser   ppMP abɛse       0.250000   0.125000
108 abandonner ai3S abɑ̃dɔna    1.062500   0.531250
110 abandonner ii3P abɑ̃dɔnɛ    0.062500   0.031250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         167.135628  83.567814
45  abaisser   ai3S abɛsa       0.250000   0.125000
100 abaisser   ai3P abɛsɛʁ      1.000000   0.500000
104 abaisser   ppMP abɛse       0.125000   0.062500
108 abandonner ai3S abɑ̃dɔna    0.531250   0.265625

                                tir1       tir2
    lexeme   case phono
40  avoir    pi3S a       169.567814  84.783907
45  abaisser ai3S abɛsa     0.125000   0.062500
52  abaisser pP   abɛsɑ̃    1.000000   0.500000
100 abaisser ai3P abɛsɛʁ    0.500000   0.250000
104 abaisser ppMP abɛse     0.062500   0.031250

                                tir1       tir2
    lexeme   case phono
40  avoir    pi3S a       165.783907  82.891953
45  abaisser ai3S abɛsa     0.062500   0.031250
52  abaisser pP   abɛsɑ̃    0.500000   0.250000
100 abaisser ai3P abɛsɛʁ    0.250000   0.125000
104 abaisser ppMP abɛse     0.031250   0.015625

                                tir1       tir2
    lexeme   case phono
40  avoir    pi3S a       163.891953  81.945977
45  abaisser ai3S abɛsa     0.031250   0.015625
52  abaisser pP   abɛsɑ̃    0.250000   0.125000
100 abaisser ai3P abɛsɛʁ    0.125000   0.062500
104 abaisser ppMP abɛse     0.015625   0.007812

                                tir1       tir2
    lexeme   case phono
40  avoir    pi3S a       166.945977  83.472988
45  abaisser ai3S abɛsa     0.015625   0.007812
52  abaisser pP   abɛsɑ̃    0.125000   0.062500
100 abaisser ai3P abɛsɛʁ    0.062500   0.031250
104 abaisser ppMP abɛse     0.007812   0.003906

                                tir1       tir2
    lexeme   case phono
40  avoir    pi3S a       169.472988  84.736494
45  abaisser ai3S abɛsa     0.007812   0.003906
52  abaisser pP   abɛsɑ̃    0.062500   0.031250
67  abaisser pi3S abɛs      1.000000   0.500000
100 abaisser ai3P abɛsɛʁ    0.031250   0.015625

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         175.736494  87.868247
52  abaisser   pP   abɛsɑ̃      0.031250   0.015625
67  abaisser   pi3S abɛs        0.500000   0.250000
100 abaisser   ai3P abɛsɛʁ      0.015625   0.007812
108 abandonner ai3S abɑ̃dɔna    0.008301   0.004150

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         177.868247  88.934124
52  abaisser   pP   abɛsɑ̃      0.015625   0.007812
67  abaisser   pi3S abɛs        0.250000   0.125000
100 abaisser   ai3P abɛsɛʁ      0.007812   0.003906
109 abandonner ai1S abɑ̃dɔnɛ    0.250000   0.125000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         160.934124  80.467062
45  abaisser   ai3S abɛsa       1.000000   0.500000
52  abaisser   pP   abɛsɑ̃      0.007812   0.003906
67  abaisser   pi3S abɛs        0.125000   0.062500
109 abandonner ai1S abɑ̃dɔnɛ    0.125000   0.062500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         189.467062  94.733531
45  abaisser   ai3S abɛsa       0.500000   0.250000
67  abaisser   pi3S abɛs        0.062500   0.031250
109 abandonner ai1S abɑ̃dɔnɛ    0.062500   0.031250
111 abandonner ii1S abɑ̃dɔnɛ    0.128906   0.064453

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         182.733531  91.366765
45  abaisser   ai3S abɛsa       0.250000   0.125000
67  abaisser   pi3S abɛs        0.031250   0.015625
109 abandonner ai1S abɑ̃dɔnɛ    0.031250   0.015625
111 abandonner ii1S abɑ̃dɔnɛ    0.064453   0.032227

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         169.366765  84.683383
45  abaisser   ai3S abɛsa       0.125000   0.062500
67  abaisser   pi3S abɛs        0.015625   0.007812
109 abandonner ai1S abɑ̃dɔnɛ    0.015625   0.007812
111 abandonner ii1S abɑ̃dɔnɛ    0.032227   0.016113

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         183.683383  91.841691
45  abaisser   ai3S abɛsa       0.062500   0.031250
67  abaisser   pi3S abɛs        0.007812   0.003906
109 abandonner ai1S abɑ̃dɔnɛ    0.007812   0.003906
111 abandonner ii1S abɑ̃dɔnɛ    0.016113   0.008057

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         171.841691  85.920846
45  abaisser   ai3S abɛsa       0.031250   0.015625
111 abandonner ii1S abɑ̃dɔnɛ    0.008057   0.004028
125 abandonner pi1S abɑ̃dɔn     1.031250   0.515625
128 abandonner pi3S abɑ̃dɔn     0.549964   0.274982

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         169.920846  84.960423
45  abaisser   ai3S abɛsa       0.015625   0.007812
108 abandonner ai3S abɑ̃dɔna    1.000000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ    1.000000   0.500000
125 abandonner pi1S abɑ̃dɔn     0.515625   0.257812

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         170.960423  85.480211
45  abaisser   ai3S abɛsa       0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna    0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ    0.500000   0.250000
125 abandonner pi1S abɑ̃dɔn     0.257812   0.128906

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         186.480211  93.240106
108 abandonner ai3S abɑ̃dɔna    0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ    0.250000   0.125000
125 abandonner pi1S abɑ̃dɔn     0.128906   0.064453
128 abandonner pi3S abɑ̃dɔn     0.818746   0.409373

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          164.240106  82.120053
108 abandonner ai3S abɑ̃dɔna     0.125000   0.062500
111 abandonner ii1S abɑ̃dɔnɛ     1.000000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ     0.125000   0.062500
114 abandonner pP   abɑ̃dɔnɑ̃    1.000000   0.500000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          162.120053  81.060026
108 abandonner ai3S abɑ̃dɔna     2.062500   1.031250
111 abandonner ii1S abɑ̃dɔnɛ     0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ     0.062500   0.031250
114 abandonner pP   abɑ̃dɔnɑ̃    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         166.060026  83.030013
73  abaisser   inf  abɛse       1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna    1.031250   0.515625
111 abandonner ii1S abɑ̃dɔnɛ    0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ    0.031250   0.015625

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         164.030013  82.015007
73  abaisser   inf  abɛse       0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna    0.515625   0.257812
111 abandonner ii1S abɑ̃dɔnɛ    0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ    0.015625   0.007812

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         173.015007  86.507503
73  abaisser   inf  abɛse       0.250000   0.125000
108 abandonner ai3S abɑ̃dɔna    0.257812   0.128906
111 abandonner ii1S abɑ̃dɔnɛ    0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ    1.007812   0.503906

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         176.507503  88.253752
73  abaisser   inf  abɛse       0.125000   0.062500
108 abandonner ai3S abɑ̃dɔna    1.128906   0.564453
111 abandonner ii1S abɑ̃dɔnɛ    0.031250   0.015625
113 abandonner ii3S abɑ̃dɔnɛ    0.503906   0.251953

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         172.253752  86.126876
73  abaisser   inf  abɛse       0.062500   0.031250
108 abandonner ai3S abɑ̃dɔna    1.564453   0.782227
111 abandonner ii1S abɑ̃dɔnɛ    0.015625   0.007812
113 abandonner ii3S abɑ̃dɔnɛ    0.251953   0.125977

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         169.126876  84.563438
73  abaisser   inf  abɛse       0.031250   0.015625
108 abandonner ai3S abɑ̃dɔna    0.782227   0.391113
111 abandonner ii1S abɑ̃dɔnɛ    0.007812   0.003906
113 abandonner ii3S abɑ̃dɔnɛ    0.125977   0.062988

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          180.563438  90.281719
73  abaisser   inf  abɛse        0.015625   0.007812
108 abandonner ai3S abɑ̃dɔna     0.391113   0.195557
113 abandonner ii3S abɑ̃dɔnɛ     0.062988   0.031494
114 abandonner pP   abɑ̃dɔnɑ̃    0.847656   0.423828

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          165.281719  82.640859
73  abaisser   inf  abɛse        0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna     0.195557   0.097778
113 abandonner ii3S abɑ̃dɔnɛ     0.031494   0.015747
114 abandonner pP   abɑ̃dɔnɑ̃    0.423828   0.211914

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          174.640859  87.320430
108 abandonner ai3S abɑ̃dɔna     0.097778   0.048889
113 abandonner ii3S abɑ̃dɔnɛ     1.015747   0.507874
114 abandonner pP   abɑ̃dɔnɑ̃    0.211914   0.105957
128 abandonner pi3S abɑ̃dɔn      1.000000   0.500000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          157.320430  78.660215
45  abaisser   ai3S abɛsa        1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna     0.048889   0.024445
113 abandonner ii3S abɑ̃dɔnɛ     0.507874   0.253937
114 abandonner pP   abɑ̃dɔnɑ̃    0.105957   0.052979

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          152.660215  76.330107
45  abaisser   ai3S abɛsa        0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna     0.024445   0.012222
113 abandonner ii3S abɑ̃dɔnɛ     0.253937   0.126968
114 abandonner pP   abɑ̃dɔnɑ̃    0.052979   0.026489

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         149.330107  74.665054
45  abaisser   ai3S abɛsa       0.250000   0.125000
50  abaisser   ii3S abɛsɛ       1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna    0.012222   0.006111
113 abandonner ii3S abɑ̃dɔnɛ    0.126968   0.063484

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          153.665054  76.832527
45  abaisser   ai3S abɛsa        0.125000   0.062500
50  abaisser   ii3S abɛsɛ        0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ     0.063484   0.031742
114 abandonner pP   abɑ̃dɔnɑ̃    0.013245   0.006622

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          161.832527  80.916263
45  abaisser   ai3S abɛsa        0.062500   0.031250
50  abaisser   ii3S abɛsɛ        0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ     0.031742   0.015871
114 abandonner pP   abɑ̃dɔnɑ̃    1.006622   0.503311

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          174.916263  87.458132
45  abaisser   ai3S abɛsa        0.031250   0.015625
50  abaisser   ii3S abɛsɛ        0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ     0.015871   0.007936
114 abandonner pP   abɑ̃dɔnɑ̃    0.503311   0.251656

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         172.458132  86.229066
45  abaisser   ai3S abɛsa       0.015625   0.007812
50  abaisser   ii3S abɛsɛ       0.062500   0.031250
109 abandonner ai1S abɑ̃dɔnɛ    2.000000   1.000000
113 abandonner ii3S abɑ̃dɔnɛ    0.007936   0.003968

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          169.229066  84.614533
45  abaisser   ai3S abɛsa        0.007812   0.003906
50  abaisser   ii3S abɛsɛ        0.031250   0.015625
109 abandonner ai1S abɑ̃dɔnɛ     1.000000   0.500000
114 abandonner pP   abɑ̃dɔnɑ̃    0.125828   0.062914

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          161.614533  80.807266
50  abaisser   ii3S abɛsɛ        0.015625   0.007812
109 abandonner ai1S abɑ̃dɔnɛ     0.500000   0.250000
114 abandonner pP   abɑ̃dɔnɑ̃    0.062914   0.031457
125 abandonner pi1S abɑ̃dɔn      2.000000   1.000000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          154.807266  77.403633
50  abaisser   ii3S abɛsɛ        0.007812   0.003906
109 abandonner ai1S abɑ̃dɔnɛ     0.250000   0.125000
114 abandonner pP   abɑ̃dɔnɑ̃    2.031457   1.015728
125 abandonner pi1S abɑ̃dɔn      1.000000   0.500000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          157.403633  78.701817
109 abandonner ai1S abɑ̃dɔnɛ     0.125000   0.062500
114 abandonner pP   abɑ̃dɔnɑ̃    1.015728   0.507864
125 abandonner pi1S abɑ̃dɔn      0.500000   0.250000
132 abandonner inf  abɑ̃dɔne     2.906637   1.453319

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          154.701817  77.350908
109 abandonner ai1S abɑ̃dɔnɛ     0.062500   0.031250
114 abandonner pP   abɑ̃dɔnɑ̃    0.507864   0.253932
125 abandonner pi1S abɑ̃dɔn      0.250000   0.125000
132 abandonner inf  abɑ̃dɔne     2.453319   1.226659

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          169.350908  84.675454
109 abandonner ai1S abɑ̃dɔnɛ     0.031250   0.015625
114 abandonner pP   abɑ̃dɔnɑ̃    0.253932   0.126966
125 abandonner pi1S abɑ̃dɔn      0.125000   0.062500
132 abandonner inf  abɑ̃dɔne     2.226659   1.113330

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          160.675454  80.337727
109 abandonner ai1S abɑ̃dɔnɛ     0.015625   0.007812
114 abandonner pP   abɑ̃dɔnɑ̃    0.126966   0.063483
125 abandonner pi1S abɑ̃dɔn      0.062500   0.031250
132 abandonner inf  abɑ̃dɔne     2.113330   1.056665

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          158.337727  79.168864
101 abaisser   ppMS abɛse        1.000000   0.500000
109 abandonner ai1S abɑ̃dɔnɛ     0.007812   0.003906
114 abandonner pP   abɑ̃dɔnɑ̃    0.063483   0.031742
125 abandonner pi1S abɑ̃dɔn      0.031250   0.015625

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          150.168864  75.084432
101 abaisser   ppMS abɛse        0.500000   0.250000
114 abandonner pP   abɑ̃dɔnɑ̃    0.031742   0.015871
125 abandonner pi1S abɑ̃dɔn      0.015625   0.007812
132 abandonner inf  abɑ̃dɔne     1.028332   0.514166

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          171.084432  85.542216
101 abaisser   ppMS abɛse        0.250000   0.125000
114 abandonner pP   abɑ̃dɔnɑ̃    0.015871   0.007935
125 abandonner pi1S abɑ̃dɔn      0.007812   0.003906
132 abandonner inf  abɑ̃dɔne     0.514166   0.257083

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          188.542216  94.271108
101 abaisser   ppMS abɛse        0.125000   0.062500
114 abandonner pP   abɑ̃dɔnɑ̃    0.007935   0.003968
132 abandonner inf  abɑ̃dɔne     1.257083   0.628542
148 abandonner pi2P abɑ̃dɔne     0.250000   0.125000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          183.271108  91.635554
101 abaisser   ppMS abɛse        0.062500   0.031250
132 abandonner inf  abɑ̃dɔne     0.628542   0.314271
148 abandonner pi2P abɑ̃dɔne     0.125000   0.062500
159 abandonner ai1P abɑ̃dɔnam    0.125000   0.062500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         168.635554  84.317777
67  abaisser   pi3S abɛs        1.000000   0.500000
101 abaisser   ppMS abɛse       0.031250   0.015625
128 abandonner pi3S abɑ̃dɔn     1.000000   0.500000
132 abandonner inf  abɑ̃dɔne    0.314271   0.157135

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         177.317777  88.658888
67  abaisser   pi3S abɛs        0.500000   0.250000
101 abaisser   ppMS abɛse       0.015625   0.007812
128 abandonner pi3S abɑ̃dɔn     0.500000   0.250000
132 abandonner inf  abɑ̃dɔne    0.157135   0.078568

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         160.658888  80.329444
67  abaisser   pi3S abɛs        0.250000   0.125000
101 abaisser   ppMS abɛse       0.007812   0.003906
128 abandonner pi3S abɑ̃dɔn     0.250000   0.125000
132 abandonner inf  abɑ̃dɔne    1.078568   0.539284

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         167.329444  83.664722
67  abaisser   pi3S abɛs        0.125000   0.062500
109 abandonner ai1S abɑ̃dɔnɛ    1.000000   0.500000
128 abandonner pi3S abɑ̃dɔn     0.125000   0.062500
132 abandonner inf  abɑ̃dɔne    1.539284   0.769642

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         160.664722  80.332361
67  abaisser   pi3S abɛs        0.062500   0.031250
109 abandonner ai1S abɑ̃dɔnɛ    0.500000   0.250000
128 abandonner pi3S abɑ̃dɔn     0.062500   0.031250
132 abandonner inf  abɑ̃dɔne    0.769642   0.384821

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         165.332361  82.666181
67  abaisser   pi3S abɛs        0.031250   0.015625
109 abandonner ai1S abɑ̃dɔnɛ    0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ    1.000000   0.500000
125 abandonner pi1S abɑ̃dɔn     1.000000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         170.666181  85.333090
67  abaisser   pi3S abɛs        0.015625   0.007812
109 abandonner ai1S abɑ̃dɔnɛ    0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ    0.500000   0.250000
125 abandonner pi1S abɑ̃dɔn     0.500000   0.250000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          171.333090  85.666545
67  abaisser   pi3S abɛs         0.007812   0.003906
109 abandonner ai1S abɑ̃dɔnɛ     0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ     0.250000   0.125000
114 abandonner pP   abɑ̃dɔnɑ̃    2.000000   1.000000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          191.666545  95.833273
50  abaisser   ii3S abɛsɛ        1.000000   0.500000
109 abandonner ai1S abɑ̃dɔnɛ     0.031250   0.015625
113 abandonner ii3S abɑ̃dɔnɛ     0.125000   0.062500
114 abandonner pP   abɑ̃dɔnɑ̃    1.000000   0.500000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          184.833273  92.416636
50  abaisser   ii3S abɛsɛ        0.500000   0.250000
109 abandonner ai1S abɑ̃dɔnɛ     0.015625   0.007812
113 abandonner ii3S abɑ̃dɔnɛ     0.062500   0.031250
114 abandonner pP   abɑ̃dɔnɑ̃    0.500000   0.250000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          184.416636  92.208318
50  abaisser   ii3S abɛsɛ        0.250000   0.125000
109 abandonner ai1S abɑ̃dɔnɛ     0.007812   0.003906
113 abandonner ii3S abɑ̃dɔnɛ     0.031250   0.015625
114 abandonner pP   abɑ̃dɔnɑ̃    0.250000   0.125000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          169.208318  84.604159
50  abaisser   ii3S abɛsɛ        0.125000   0.062500
73  abaisser   inf  abɛse        1.000000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ     0.015625   0.007812
114 abandonner pP   abɑ̃dɔnɑ̃    0.125000   0.062500

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          155.604159  77.802080
50  abaisser   ii3S abɛsɛ        0.062500   0.031250
73  abaisser   inf  abɛse        0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ     0.007812   0.003906
114 abandonner pP   abɑ̃dɔnɑ̃    0.062500   0.031250

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          182.802080  91.401040
50  abaisser   ii3S abɛsɛ        0.031250   0.015625
73  abaisser   inf  abɛse        0.250000   0.125000
114 abandonner pP   abɑ̃dɔnɑ̃    0.031250   0.015625
125 abandonner pi1S abɑ̃dɔn      1.253906   0.626953

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          194.401040  97.200520
45  abaisser   ai3S abɛsa        1.000000   0.500000
50  abaisser   ii3S abɛsɛ        0.015625   0.007812
73  abaisser   inf  abɛse        0.125000   0.062500
114 abandonner pP   abɑ̃dɔnɑ̃    0.015625   0.007812

                                     tir1        tir2
    lexeme     case phono
40  avoir      pi3S a          200.200520  100.100260
45  abaisser   ai3S abɛsa        0.500000    0.250000
50  abaisser   ii3S abɛsɛ        0.007812    0.003906
73  abaisser   inf  abɛse        0.062500    0.031250
114 abandonner pP   abɑ̃dɔnɑ̃    0.007812    0.003906

                                   tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         183.10026  91.550130
45  abaisser   ai3S abɛsa       0.25000   0.125000
73  abaisser   inf  abɛse       0.03125   0.015625
108 abandonner ai3S abɑ̃dɔna    1.00000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ    1.00000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         166.550130  83.275065
45  abaisser   ai3S abɛsa       0.125000   0.062500
73  abaisser   inf  abɛse       0.015625   0.007812
108 abandonner ai3S abɑ̃dɔna    0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         157.275065  78.637532
45  abaisser   ai3S abɛsa       0.062500   0.031250
73  abaisser   inf  abɛse       0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna    0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ    0.250000   0.125000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         176.637532  88.318766
45  abaisser   ai3S abɛsa       0.031250   0.015625
108 abandonner ai3S abɑ̃dɔna    0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ    0.125000   0.062500
125 abandonner pi1S abɑ̃dɔn     0.082092   0.041046

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         171.318766  85.659383
45  abaisser   ai3S abɛsa       0.015625   0.007812
108 abandonner ai3S abɑ̃dɔna    0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ    0.062500   0.031250
125 abandonner pi1S abɑ̃dɔn     0.041046   0.020523

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         189.659383  94.829692
45  abaisser   ai3S abɛsa       0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna    0.031250   0.015625
113 abandonner ii3S abɑ̃dɔnɛ    0.031250   0.015625
125 abandonner pi1S abɑ̃dɔn     0.020523   0.010262

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         179.829692  89.914846
108 abandonner ai3S abɑ̃dɔna    0.015625   0.007812
113 abandonner ii3S abɑ̃dɔnɛ    0.015625   0.007812
125 abandonner pi1S abɑ̃dɔn     0.010262   0.005131
128 abandonner pi3S abɑ̃dɔn     0.750000   0.375000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         178.914846  89.457423
108 abandonner ai3S abɑ̃dɔna    1.007812   0.503906
113 abandonner ii3S abɑ̃dɔnɛ    0.007812   0.003906
125 abandonner pi1S abɑ̃dɔn     1.005131   0.502565
128 abandonner pi3S abɑ̃dɔn     0.375000   0.187500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         173.457423  86.728711
108 abandonner ai3S abɑ̃dɔna    0.503906   0.251953
125 abandonner pi1S abɑ̃dɔn     0.502565   0.251283
128 abandonner pi3S abɑ̃dɔn     2.187500   1.093750
129 abandonner ps3S abɑ̃dɔn     0.062500   0.031250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         188.728711  94.364356
108 abandonner ai3S abɑ̃dɔna    0.251953   0.125977
125 abandonner pi1S abɑ̃dɔn     0.251283   0.125641
128 abandonner pi3S abɑ̃dɔn     2.093750   1.046875
129 abandonner ps3S abɑ̃dɔn     0.031250   0.015625

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         182.364356  91.182178
108 abandonner ai3S abɑ̃dɔna    0.125977   0.062988
125 abandonner pi1S abɑ̃dɔn     0.125641   0.062821
128 abandonner pi3S abɑ̃dɔn     1.046875   0.523438
129 abandonner ps3S abɑ̃dɔn     0.015625   0.007812

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          175.182178  87.591089
108 abandonner ai3S abɑ̃dɔna     0.062988   0.031494
113 abandonner ii3S abɑ̃dɔnɛ     1.000000   0.500000
114 abandonner pP   abɑ̃dɔnɑ̃    1.000000   0.500000
125 abandonner pi1S abɑ̃dɔn      0.062821   0.031410

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          168.591089  84.295544
45  abaisser   ai3S abɛsa        1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna     0.031494   0.015747
113 abandonner ii3S abɑ̃dɔnɛ     0.500000   0.250000
114 abandonner pP   abɑ̃dɔnɑ̃    0.500000   0.250000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          169.295544  84.647772
45  abaisser   ai3S abɛsa        0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna     0.015747   0.007874
113 abandonner ii3S abɑ̃dɔnɛ     0.250000   0.125000
114 abandonner pP   abɑ̃dɔnɑ̃    0.250000   0.125000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          167.647772  83.823886
45  abaisser   ai3S abɛsa        0.250000   0.125000
108 abandonner ai3S abɑ̃dɔna     0.007874   0.003937
113 abandonner ii3S abɑ̃dɔnɛ     0.125000   0.062500
114 abandonner pP   abɑ̃dɔnɑ̃    0.125000   0.062500

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          170.823886  85.411943
45  abaisser   ai3S abɛsa        0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ     0.062500   0.031250
114 abandonner pP   abɑ̃dɔnɑ̃    0.062500   0.031250
128 abandonner pi3S abɑ̃dɔn      1.407715   0.703857

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          167.411943  83.705972
45  abaisser   ai3S abɛsa        0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ     0.031250   0.015625
114 abandonner pP   abɑ̃dɔnɑ̃    1.031250   0.515625
128 abandonner pi3S abɑ̃dɔn      0.703857   0.351929

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          180.705972  90.352986
45  abaisser   ai3S abɛsa        0.031250   0.015625
113 abandonner ii3S abɑ̃dɔnɛ     0.015625   0.007812
114 abandonner pP   abɑ̃dɔnɑ̃    0.515625   0.257812
128 abandonner pi3S abɑ̃dɔn      0.351929   0.175964

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          193.352986  96.676493
45  abaisser   ai3S abɛsa        0.015625   0.007812
113 abandonner ii3S abɑ̃dɔnɛ     0.007812   0.003906
114 abandonner pP   abɑ̃dɔnɑ̃    0.257812   0.128906
128 abandonner pi3S abɑ̃dɔn      0.175964   0.087982

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          199.676493  99.838246
45  abaisser   ai3S abɛsa        0.007812   0.003906
114 abandonner pP   abɑ̃dɔnɑ̃    0.128906   0.064453
128 abandonner pi3S abɑ̃dɔn      0.087982   0.043991
130 abandonner pi3P abɑ̃dɔn      0.500000   0.250000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          179.838246  89.919123
90  abaisser   pi2P abɛse        1.000000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ     1.000000   0.500000
114 abandonner pP   abɑ̃dɔnɑ̃    0.064453   0.032227
128 abandonner pi3S abɑ̃dɔn      0.043991   0.021996

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          172.919123  86.459562
90  abaisser   pi2P abɛse        0.500000   0.250000
110 abandonner ii3P abɑ̃dɔnɛ     1.000000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ     0.500000   0.250000
114 abandonner pP   abɑ̃dɔnɑ̃    0.032227   0.016113

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          170.459562  85.229781
90  abaisser   pi2P abɛse        0.250000   0.125000
110 abandonner ii3P abɑ̃dɔnɛ     0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ     0.250000   0.125000
114 abandonner pP   abɑ̃dɔnɑ̃    0.016113   0.008057

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          170.229781  85.114890
90  abaisser   pi2P abɛse        0.125000   0.062500
110 abandonner ii3P abɑ̃dɔnɛ     0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ     0.125000   0.062500
114 abandonner pP   abɑ̃dɔnɑ̃    0.008057   0.004028

                                   tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         158.11489  79.057445
90  abaisser   pi2P abɛse       0.06250   0.031250
109 abandonner ai1S abɑ̃dɔnɛ    1.00000   0.500000
110 abandonner ii3P abɑ̃dɔnɛ    0.12500   0.062500
113 abandonner ii3S abɑ̃dɔnɛ    0.06250   0.031250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         162.057445  81.028723
90  abaisser   pi2P abɛse       0.031250   0.015625
109 abandonner ai1S abɑ̃dɔnɛ    0.500000   0.250000
110 abandonner ii3P abɑ̃dɔnɛ    0.062500   0.031250
111 abandonner ii1S abɑ̃dɔnɛ    1.000000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         167.028723  83.514361
90  abaisser   pi2P abɛse       0.015625   0.007812
109 abandonner ai1S abɑ̃dɔnɛ    0.250000   0.125000
110 abandonner ii3P abɑ̃dɔnɛ    0.031250   0.015625
111 abandonner ii1S abɑ̃dɔnɛ    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         176.514361  88.257181
90  abaisser   pi2P abɛse       0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna    1.000000   0.500000
109 abandonner ai1S abɑ̃dɔnɛ    0.125000   0.062500
110 abandonner ii3P abɑ̃dɔnɛ    0.015625   0.007812

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         158.257181  79.128590
108 abandonner ai3S abɑ̃dɔna    0.500000   0.250000
109 abandonner ai1S abɑ̃dɔnɛ    0.062500   0.031250
110 abandonner ii3P abɑ̃dɔnɛ    0.007812   0.003906
111 abandonner ii1S abɑ̃dɔnɛ    0.125000   0.062500

                                   tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         174.12859  87.064295
64  abaisser   pi1S abɛs        1.00000   0.500000
108 abandonner ai3S abɑ̃dɔna    0.25000   0.125000
109 abandonner ai1S abɑ̃dɔnɛ    0.03125   0.015625
111 abandonner ii1S abɑ̃dɔnɛ    0.06250   0.031250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         166.064295  83.032148
64  abaisser   pi1S abɛs        0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna    1.125000   0.562500
109 abandonner ai1S abɑ̃dɔnɛ    0.015625   0.007812
111 abandonner ii1S abɑ̃dɔnɛ    0.031250   0.015625

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         161.032148  80.516074
64  abaisser   pi1S abɛs        0.250000   0.125000
108 abandonner ai3S abɑ̃dɔna    0.562500   0.281250
109 abandonner ai1S abɑ̃dɔnɛ    0.007812   0.003906
111 abandonner ii1S abɑ̃dɔnɛ    0.015625   0.007812

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          166.516074  83.258037
64  abaisser   pi1S abɛs         0.125000   0.062500
108 abandonner ai3S abɑ̃dɔna     0.281250   0.140625
111 abandonner ii1S abɑ̃dɔnɛ     0.007812   0.003906
114 abandonner pP   abɑ̃dɔnɑ̃    1.546875   0.773438

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          176.258037  88.129018
64  abaisser   pi1S abɛs         0.062500   0.031250
108 abandonner ai3S abɑ̃dɔna     0.140625   0.070312
114 abandonner pP   abɑ̃dɔnɑ̃    0.773438   0.386719
128 abandonner pi3S abɑ̃dɔn      0.345703   0.172852

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          170.129018  85.064509
45  abaisser   ai3S abɛsa        1.000000   0.500000
64  abaisser   pi1S abɛs         0.031250   0.015625
108 abandonner ai3S abɑ̃dɔna     0.070312   0.035156
114 abandonner pP   abɑ̃dɔnɑ̃    0.386719   0.193359

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          184.064509  92.032255
45  abaisser   ai3S abɛsa        0.500000   0.250000
64  abaisser   pi1S abɛs         0.015625   0.007812
108 abandonner ai3S abɑ̃dɔna     0.035156   0.017578
114 abandonner pP   abɑ̃dɔnɑ̃    0.193359   0.096680

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         177.032255  88.516127
45  abaisser   ai3S abɛsa       0.250000   0.125000
64  abaisser   pi1S abɛs        0.007812   0.003906
73  abaisser   inf  abɛse       1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna    0.017578   0.008789

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          177.516127  88.758064
45  abaisser   ai3S abɛsa        0.125000   0.062500
73  abaisser   inf  abɛse        0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna     0.008789   0.004395
114 abandonner pP   abɑ̃dɔnɑ̃    0.048340   0.024170

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          180.758064  90.379032
45  abaisser   ai3S abɛsa        0.062500   0.031250
73  abaisser   inf  abɛse        0.250000   0.125000
114 abandonner pP   abɑ̃dɔnɑ̃    0.024170   0.012085
125 abandonner pi1S abɑ̃dɔn      0.125000   0.062500

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          174.379032  87.189516
45  abaisser   ai3S abɛsa        0.031250   0.015625
73  abaisser   inf  abɛse        0.125000   0.062500
114 abandonner pP   abɑ̃dɔnɑ̃    0.012085   0.006042
125 abandonner pi1S abɑ̃dɔn      0.062500   0.031250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         157.189516  78.594758
45  abaisser   ai3S abɛsa       0.015625   0.007812
73  abaisser   inf  abɛse       0.062500   0.031250
108 abandonner ai3S abɑ̃dɔna    1.000000   0.500000
125 abandonner pi1S abɑ̃dɔn     0.031250   0.015625

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         169.594758  84.797379
45  abaisser   ai3S abɛsa       0.007812   0.003906
50  abaisser   ii3S abɛsɛ       1.000000   0.500000
73  abaisser   inf  abɛse       0.031250   0.015625
108 abandonner ai3S abɑ̃dɔna    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         199.797379  99.898689
50  abaisser   ii3S abɛsɛ       0.500000   0.250000
73  abaisser   inf  abɛse       0.015625   0.007812
74  abaisser   fi3S abɛsəʁa     1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna    0.250000   0.125000

                                 tir1       tir2
    lexeme   case phono
40  avoir    pi3S a        189.898689  94.949345
50  abaisser ii3S abɛsɛ      0.250000   0.125000
73  abaisser inf  abɛse      0.007812   0.003906
74  abaisser fi3S abɛsəʁa    0.500000   0.250000
104 abaisser ppMP abɛse      1.000000   0.500000

                                 tir1       tir2
    lexeme   case phono
40  avoir    pi3S a        166.949345  83.474672
50  abaisser ii3S abɛsɛ      1.125000   0.562500
67  abaisser pi3S abɛs       1.000000   0.500000
74  abaisser fi3S abɛsəʁa    0.250000   0.125000
104 abaisser ppMP abɛse      0.500000   0.250000

                                 tir1       tir2
    lexeme   case phono
40  avoir    pi3S a        171.474672  85.737336
50  abaisser ii3S abɛsɛ      0.562500   0.281250
67  abaisser pi3S abɛs       0.500000   0.250000
74  abaisser fi3S abɛsəʁa    0.125000   0.062500
104 abaisser ppMP abɛse      0.250000   0.125000

                                 tir1       tir2
    lexeme   case phono
40  avoir    pi3S a        165.737336  82.868668
50  abaisser ii3S abɛsɛ      0.281250   0.140625
67  abaisser pi3S abɛs       0.250000   0.125000
74  abaisser fi3S abɛsəʁa    0.062500   0.031250
104 abaisser ppMP abɛse      0.125000   0.062500

                                 tir1       tir2
    lexeme   case phono
40  avoir    pi3S a        177.868668  88.934334
50  abaisser ii3S abɛsɛ      0.140625   0.070312
67  abaisser pi3S abɛs       0.125000   0.062500
74  abaisser fi3S abɛsəʁa    0.031250   0.015625
104 abaisser ppMP abɛse      0.062500   0.031250

                                tir1       tir2
   lexeme   case phono
40 avoir    pi3S a        163.934334  81.967167
50 abaisser ii3S abɛsɛ      0.070312   0.035156
67 abaisser pi3S abɛs       0.062500   0.031250
71 abaisser pi3P abɛs       1.000000   0.500000
74 abaisser fi3S abɛsəʁa    0.015625   0.007812

                                tir1       tir2
   lexeme   case phono
40 avoir    pi3S a        173.967167  86.983584
50 abaisser ii3S abɛsɛ      0.035156   0.017578
67 abaisser pi3S abɛs       0.031250   0.015625
71 abaisser pi3P abɛs       0.500000   0.250000
74 abaisser fi3S abɛsəʁa    0.007812   0.003906

                               tir1       tir2
    lexeme   case phono
40  avoir    pi3S a      177.983584  88.991792
50  abaisser ii3S abɛsɛ    0.017578   0.008789
67  abaisser pi3S abɛs     0.015625   0.007812
71  abaisser pi3P abɛs     0.250000   0.125000
104 abaisser ppMP abɛse    0.007812   0.003906

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         178.991792  89.495896
50  abaisser   ii3S abɛsɛ       0.008789   0.004395
67  abaisser   pi3S abɛs        0.007812   0.003906
71  abaisser   pi3P abɛs        0.125000   0.062500
108 abandonner ai3S abɑ̃dɔna    0.500000   0.250000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          185.495896  92.747948
71  abaisser   pi3P abɛs         0.062500   0.031250
108 abandonner ai3S abɑ̃dɔna     0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ     0.062988   0.031494
114 abandonner pP   abɑ̃dɔnɑ̃    0.015625   0.007812

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          180.747948  90.373974
71  abaisser   pi3P abɛs         0.031250   0.015625
108 abandonner ai3S abɑ̃dɔna     0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ     0.031494   0.015747
114 abandonner pP   abɑ̃dɔnɑ̃    0.007812   0.003906

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         175.373974  87.686987
71  abaisser   pi3P abɛs        0.015625   0.007812
108 abandonner ai3S abɑ̃dɔna    0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ    0.015747   0.007874
115 abandonner ai2S abɑ̃dɔna    0.031250   0.015625

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         176.686987  88.343493
71  abaisser   pi3P abɛs        0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna    0.031250   0.015625
113 abandonner ii3S abɑ̃dɔnɛ    1.007874   0.503937
115 abandonner ai2S abɑ̃dɔna    0.015625   0.007812

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         188.343493  94.171747
108 abandonner ai3S abɑ̃dɔna    0.015625   0.007812
113 abandonner ii3S abɑ̃dɔnɛ    0.503937   0.251968
115 abandonner ai2S abɑ̃dɔna    0.007812   0.003906
125 abandonner pi1S abɑ̃dɔn     1.000000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         183.171747  91.585873
108 abandonner ai3S abɑ̃dɔna    0.007812   0.003906
113 abandonner ii3S abɑ̃dɔnɛ    0.251968   0.125984
125 abandonner pi1S abɑ̃dɔn     0.500000   0.250000
128 abandonner pi3S abɑ̃dɔn     0.143555   0.071777

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         180.585873  90.292937
50  abaisser   ii3S abɛsɛ       1.000000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ    0.125984   0.062992
125 abandonner pi1S abɑ̃dɔn     0.250000   0.125000
128 abandonner pi3S abɑ̃dɔn     2.071777   1.035889

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         177.292937  88.646468
50  abaisser   ii3S abɛsɛ       0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ    1.062992   0.531496
125 abandonner pi1S abɑ̃dɔn     0.125000   0.062500
128 abandonner pi3S abɑ̃dɔn     2.035889   1.017944

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         168.646468  84.323234
50  abaisser   ii3S abɛsɛ       0.250000   0.125000
110 abandonner ii3P abɑ̃dɔnɛ    1.000000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ    0.531496   0.265748
125 abandonner pi1S abɑ̃dɔn     0.062500   0.031250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         169.323234  84.661617
50  abaisser   ii3S abɛsɛ       0.125000   0.062500
110 abandonner ii3P abɑ̃dɔnɛ    0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ    0.265748   0.132874
125 abandonner pi1S abɑ̃dɔn     0.031250   0.015625

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         178.661617  89.330809
50  abaisser   ii3S abɛsɛ       0.062500   0.031250
110 abandonner ii3P abɑ̃dɔnɛ    0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ    0.132874   0.066437
125 abandonner pi1S abɑ̃dɔn     1.015625   0.507812

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         156.330809  78.165404
50  abaisser   ii3S abɛsɛ       0.031250   0.015625
71  abaisser   pi3P abɛs        1.000000   0.500000
110 abandonner ii3P abɑ̃dɔnɛ    0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ    0.066437   0.033219

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         172.165404  86.082702
50  abaisser   ii3S abɛsɛ       0.015625   0.007812
71  abaisser   pi3P abɛs        0.500000   0.250000
110 abandonner ii3P abɑ̃dɔnɛ    0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ    0.033219   0.016609

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         169.082702  84.541351
50  abaisser   ii3S abɛsɛ       0.007812   0.003906
71  abaisser   pi3P abɛs        0.250000   0.125000
110 abandonner ii3P abɑ̃dɔnɛ    0.031250   0.015625
113 abandonner ii3S abɑ̃dɔnɛ    0.016609   0.008305

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          164.541351  82.270676
71  abaisser   pi3P abɛs         0.125000   0.062500
110 abandonner ii3P abɑ̃dɔnɛ     0.015625   0.007812
113 abandonner ii3S abɑ̃dɔnɛ     0.008305   0.004152
114 abandonner pP   abɑ̃dɔnɑ̃    0.250000   0.125000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          184.270676  92.135338
71  abaisser   pi3P abɛs         0.062500   0.031250
108 abandonner ai3S abɑ̃dɔna     1.000000   0.500000
110 abandonner ii3P abɑ̃dɔnɛ     0.007812   0.003906
114 abandonner pP   abɑ̃dɔnɑ̃    1.125000   0.562500

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          179.135338  89.567669
71  abaisser   pi3P abɛs         0.031250   0.015625
108 abandonner ai3S abɑ̃dɔna     0.500000   0.250000
114 abandonner pP   abɑ̃dɔnɑ̃    0.562500   0.281250
125 abandonner pi1S abɑ̃dɔn      0.140869   0.070435

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          182.567669  91.283834
67  abaisser   pi3S abɛs         1.000000   0.500000
71  abaisser   pi3P abɛs         0.015625   0.007812
108 abandonner ai3S abɑ̃dɔna     0.250000   0.125000
114 abandonner pP   abɑ̃dɔnɑ̃    0.281250   0.140625

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          186.283834  93.141917
67  abaisser   pi3S abɛs         0.500000   0.250000
71  abaisser   pi3P abɛs         1.007812   0.503906
108 abandonner ai3S abɑ̃dɔna     0.125000   0.062500
114 abandonner pP   abɑ̃dɔnɑ̃    0.140625   0.070312

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          178.141917  89.070959
67  abaisser   pi3S abɛs         0.250000   0.125000
71  abaisser   pi3P abɛs         0.503906   0.251953
108 abandonner ai3S abɑ̃dɔna     0.062500   0.031250
114 abandonner pP   abɑ̃dɔnɑ̃    0.070312   0.035156

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          166.070959  83.035479
67  abaisser   pi3S abɛs         0.125000   0.062500
71  abaisser   pi3P abɛs         0.251953   0.125977
108 abandonner ai3S abɑ̃dɔna     0.031250   0.015625
114 abandonner pP   abɑ̃dɔnɑ̃    0.035156   0.017578

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         179.035479  89.517740
67  abaisser   pi3S abɛs        1.062500   0.531250
71  abaisser   pi3P abɛs        0.125977   0.062988
108 abandonner ai3S abɑ̃dɔna    0.015625   0.007812
109 abandonner ai1S abɑ̃dɔnɛ    1.000000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         162.517740  81.258870
67  abaisser   pi3S abɛs        0.531250   0.265625
71  abaisser   pi3P abɛs        0.062988   0.031494
108 abandonner ai3S abɑ̃dɔna    0.007812   0.003906
109 abandonner ai1S abɑ̃dɔnɛ    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         171.258870  85.629435
67  abaisser   pi3S abɛs        0.265625   0.132812
71  abaisser   pi3P abɛs        0.031494   0.015747
109 abandonner ai1S abɑ̃dɔnɛ    0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ    1.000000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         173.629435  86.814717
67  abaisser   pi3S abɛs        0.132812   0.066406
71  abaisser   pi3P abɛs        0.015747   0.007874
109 abandonner ai1S abɑ̃dɔnɛ    0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         170.814717  85.407359
67  abaisser   pi3S abɛs        0.066406   0.033203
71  abaisser   pi3P abɛs        0.007874   0.003937
109 abandonner ai1S abɑ̃dɔnɛ    0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ    1.250000   0.625000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          165.407359  82.703679
67  abaisser   pi3S abɛs         0.033203   0.016602
109 abandonner ai1S abɑ̃dɔnɛ     0.031250   0.015625
113 abandonner ii3S abɑ̃dɔnɛ     0.625000   0.312500
114 abandonner pP   abɑ̃dɔnɑ̃    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         176.703679  88.351840
67  abaisser   pi3S abɛs        0.016602   0.008301
101 abaisser   ppMS abɛse       1.000000   0.500000
109 abandonner ai1S abɑ̃dɔnɛ    0.015625   0.007812
113 abandonner ii3S abɑ̃dɔnɛ    0.312500   0.156250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         177.351840  88.675920
67  abaisser   pi3S abɛs        1.008301   0.504150
101 abaisser   ppMS abɛse       0.500000   0.250000
109 abandonner ai1S abɑ̃dɔnɛ    0.007812   0.003906
113 abandonner ii3S abɑ̃dɔnɛ    0.156250   0.078125

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         180.675920  90.337960
67  abaisser   pi3S abɛs        0.504150   0.252075
86  abaisser   pi2S abɛs        1.000000   0.500000
101 abaisser   ppMS abɛse       0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ    0.078125   0.039062

                               tir1       tir2
    lexeme   case phono
40  avoir    pi3S a      189.337960  94.668980
67  abaisser pi3S abɛs     0.252075   0.126038
71  abaisser pi3P abɛs     1.000000   0.500000
86  abaisser pi2S abɛs     0.500000   0.250000
101 abaisser ppMS abɛse    0.125000   0.062500

                               tir1       tir2
   lexeme   case phono
40 avoir    pi3S a       191.668980  95.834490
52 abaisser pP   abɛsɑ̃    1.000000   0.500000
67 abaisser pi3S abɛs      0.126038   0.063019
71 abaisser pi3P abɛs      0.500000   0.250000
86 abaisser pi2S abɛs      0.250000   0.125000

                               tir1       tir2
   lexeme   case phono
40 avoir    pi3S a       183.834490  91.917245
52 abaisser pP   abɛsɑ̃    0.500000   0.250000
67 abaisser pi3S abɛs      0.063019   0.031509
71 abaisser pi3P abɛs      0.250000   0.125000
86 abaisser pi2S abɛs      0.125000   0.062500

                               tir1       tir2
   lexeme   case phono
40 avoir    pi3S a       177.917245  88.958622
52 abaisser pP   abɛsɑ̃    0.250000   0.125000
67 abaisser pi3S abɛs      0.031509   0.015755
71 abaisser pi3P abɛs      0.125000   0.062500
86 abaisser pi2S abɛs      0.062500   0.031250

                               tir1       tir2
   lexeme   case phono
40 avoir    pi3S a       186.958622  93.479311
52 abaisser pP   abɛsɑ̃    1.125000   0.562500
67 abaisser pi3S abɛs      0.015755   0.007877
71 abaisser pi3P abɛs      0.062500   0.031250
86 abaisser pi2S abɛs      0.031250   0.015625

                               tir1       tir2
   lexeme   case phono
40 avoir    pi3S a       191.479311  95.739656
52 abaisser pP   abɛsɑ̃    0.562500   0.281250
67 abaisser pi3S abɛs      0.007877   0.003939
71 abaisser pi3P abɛs      0.031250   0.015625
86 abaisser pi2S abɛs      0.015625   0.007812

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         189.739656  94.869828
52  abaisser   pP   abɛsɑ̃      0.281250   0.140625
71  abaisser   pi3P abɛs        0.015625   0.007812
86  abaisser   pi2S abɛs        0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna    1.000000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         185.869828  92.934914
52  abaisser   pP   abɛsɑ̃      0.140625   0.070312
71  abaisser   pi3P abɛs        0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna    1.500000   0.750000
111 abandonner ii1S abɑ̃dɔnɛ    0.125000   0.062500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         174.934914  87.467457
52  abaisser   pP   abɛsɑ̃      0.070312   0.035156
108 abandonner ai3S abɑ̃dɔna    0.750000   0.375000
111 abandonner ii1S abɑ̃dɔnɛ    0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ    0.375000   0.187500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         159.467457  79.733728
52  abaisser   pP   abɛsɑ̃      0.035156   0.017578
108 abandonner ai3S abɑ̃dɔna    0.375000   0.187500
111 abandonner ii1S abɑ̃dɔnɛ    0.031250   0.015625
113 abandonner ii3S abɑ̃dɔnɛ    0.187500   0.093750

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         174.733728  87.366864
52  abaisser   pP   abɛsɑ̃      0.017578   0.008789
108 abandonner ai3S abɑ̃dɔna    0.187500   0.093750
111 abandonner ii1S abɑ̃dɔnɛ    0.015625   0.007812
113 abandonner ii3S abɑ̃dɔnɛ    0.093750   0.046875

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         172.366864  86.183432
52  abaisser   pP   abɛsɑ̃      0.008789   0.004395
108 abandonner ai3S abɑ̃dɔna    0.093750   0.046875
111 abandonner ii1S abɑ̃dɔnɛ    0.007812   0.003906
113 abandonner ii3S abɑ̃dɔnɛ    0.046875   0.023438

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          156.183432  78.091716
108 abandonner ai3S abɑ̃dɔna     0.046875   0.023438
113 abandonner ii3S abɑ̃dɔnɛ     1.023438   0.511719
114 abandonner pP   abɑ̃dɔnɑ̃    0.500000   0.250000
125 abandonner pi1S abɑ̃dɔn      0.008301   0.004150

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          157.091716  78.545858
108 abandonner ai3S abɑ̃dɔna     0.023438   0.011719
113 abandonner ii3S abɑ̃dɔnɛ     1.511719   0.755859
114 abandonner pP   abɑ̃dɔnɑ̃    0.250000   0.125000
128 abandonner pi3S abɑ̃dɔn      2.066487   1.033244

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          154.545858  77.272929
45  abaisser   ai3S abɛsa        1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna     0.011719   0.005859
113 abandonner ii3S abɑ̃dɔnɛ     0.755859   0.377930
114 abandonner pP   abɑ̃dɔnɑ̃    0.125000   0.062500

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          170.272929  85.136465
45  abaisser   ai3S abɛsa        0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ     0.377930   0.188965
114 abandonner pP   abɑ̃dɔnɑ̃    0.062500   0.031250
128 abandonner pi3S abɑ̃dɔn      0.516622   0.258311

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         183.136465  91.568232
45  abaisser   ai3S abɛsa       0.250000   0.125000
73  abaisser   inf  abɛse       1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna    1.000000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ    0.188965   0.094482

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         181.568232  90.784116
45  abaisser   ai3S abɛsa       0.125000   0.062500
73  abaisser   inf  abɛse       0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna    1.500000   0.750000
111 abandonner ii1S abɑ̃dɔnɛ    1.000000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         163.784116  81.892058
45  abaisser   ai3S abɛsa       0.062500   0.031250
73  abaisser   inf  abɛse       0.250000   0.125000
108 abandonner ai3S abɑ̃dɔna    0.750000   0.375000
111 abandonner ii1S abɑ̃dɔnɛ    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         156.892058  78.446029
45  abaisser   ai3S abɛsa       0.031250   0.015625
73  abaisser   inf  abɛse       0.125000   0.062500
108 abandonner ai3S abɑ̃dɔna    0.375000   0.187500
111 abandonner ii1S abɑ̃dɔnɛ    0.250000   0.125000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         166.446029  83.223015
45  abaisser   ai3S abɛsa       0.015625   0.007812
73  abaisser   inf  abɛse       0.062500   0.031250
108 abandonner ai3S abɑ̃dɔna    1.187500   0.593750
111 abandonner ii1S abɑ̃dɔnɛ    0.125000   0.062500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         176.223015  88.111507
45  abaisser   ai3S abɛsa       1.007812   0.503906
73  abaisser   inf  abɛse       0.031250   0.015625
108 abandonner ai3S abɑ̃dɔna    0.593750   0.296875
111 abandonner ii1S abɑ̃dɔnɛ    0.062500   0.031250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         172.111507  86.055754
45  abaisser   ai3S abɛsa       0.503906   0.251953
73  abaisser   inf  abɛse       0.015625   0.007812
108 abandonner ai3S abɑ̃dɔna    0.296875   0.148438
111 abandonner ii1S abɑ̃dɔnɛ    0.031250   0.015625

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         180.055754  90.027877
45  abaisser   ai3S abɛsa       0.251953   0.125977
73  abaisser   inf  abɛse       0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna    0.148438   0.074219
111 abandonner ii1S abɑ̃dɔnɛ    0.015625   0.007812

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         184.027877  92.013938
45  abaisser   ai3S abɛsa       0.125977   0.062988
108 abandonner ai3S abɑ̃dɔna    0.074219   0.037109
111 abandonner ii1S abɑ̃dɔnɛ    0.007812   0.003906
113 abandonner ii3S abɑ̃dɔnɛ    0.016363   0.008182

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         187.013938  93.506969
45  abaisser   ai3S abɛsa       0.062988   0.031494
108 abandonner ai3S abɑ̃dɔna    0.037109   0.018555
113 abandonner ii3S abɑ̃dɔnɛ    0.008182   0.004091
125 abandonner pi1S abɑ̃dɔn     0.375000   0.187500

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          182.506969  91.253485
45  abaisser   ai3S abɛsa        0.031494   0.015747
108 abandonner ai3S abɑ̃dɔna     0.018555   0.009277
114 abandonner pP   abɑ̃dɔnɑ̃    1.000000   0.500000
125 abandonner pi1S abɑ̃dɔn      0.187500   0.093750

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          170.253485  85.126742
45  abaisser   ai3S abɛsa        0.015747   0.007874
108 abandonner ai3S abɑ̃dɔna     0.009277   0.004639
114 abandonner pP   abɑ̃dɔnɑ̃    0.500000   0.250000
125 abandonner pi1S abɑ̃dɔn      0.093750   0.046875

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          158.126742  79.063371
45  abaisser   ai3S abɛsa        0.007874   0.003937
108 abandonner ai3S abɑ̃dɔna     1.004639   0.502319
113 abandonner ii3S abɑ̃dɔnɛ     1.000000   0.500000
114 abandonner pP   abɑ̃dɔnɑ̃    0.250000   0.125000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          161.063371  80.531686
52  abaisser   pP   abɛsɑ̃       1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna     0.502319   0.251160
113 abandonner ii3S abɑ̃dɔnɛ     0.500000   0.250000
114 abandonner pP   abɑ̃dɔnɑ̃    0.125000   0.062500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         160.531686  80.265843
52  abaisser   pP   abɛsɑ̃      0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna    0.251160   0.125580
111 abandonner ii1S abɑ̃dɔnɛ    1.000000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ    0.250000   0.125000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         161.265843  80.632921
52  abaisser   pP   abɛsɑ̃      1.250000   0.625000
108 abandonner ai3S abɑ̃dɔna    0.125580   0.062790
111 abandonner ii1S abɑ̃dɔnɛ    0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ    0.125000   0.062500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         165.632921  82.816461
52  abaisser   pP   abɛsɑ̃      0.625000   0.312500
108 abandonner ai3S abɑ̃dɔna    0.062790   0.031395
111 abandonner ii1S abɑ̃dɔnɛ    0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ    0.062500   0.031250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         171.816461  85.908230
52  abaisser   pP   abɛsɑ̃      0.312500   0.156250
67  abaisser   pi3S abɛs        1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna    0.031395   0.015697
111 abandonner ii1S abɑ̃dɔnɛ    0.125000   0.062500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         160.908230  80.454115
52  abaisser   pP   abɛsɑ̃      0.156250   0.078125
67  abaisser   pi3S abɛs        0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna    0.015697   0.007849
111 abandonner ii1S abɑ̃dɔnɛ    0.062500   0.031250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         167.454115  83.727058
52  abaisser   pP   abɛsɑ̃      0.078125   0.039062
67  abaisser   pi3S abɛs        0.250000   0.125000
108 abandonner ai3S abɑ̃dɔna    0.007849   0.003924
111 abandonner ii1S abɑ̃dɔnɛ    0.031250   0.015625

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          169.727058  84.863529
52  abaisser   pP   abɛsɑ̃       0.039062   0.019531
67  abaisser   pi3S abɛs         1.125000   0.562500
111 abandonner ii1S abɑ̃dɔnɛ     0.015625   0.007812
114 abandonner pP   abɑ̃dɔnɑ̃    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         163.863529  81.931764
52  abaisser   pP   abɛsɑ̃      0.019531   0.009766
67  abaisser   pi3S abɛs        0.562500   0.281250
109 abandonner ai1S abɑ̃dɔnɛ    1.000000   0.500000
111 abandonner ii1S abɑ̃dɔnɛ    0.007812   0.003906

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          169.931764  84.965882
52  abaisser   pP   abɛsɑ̃       0.009766   0.004883
67  abaisser   pi3S abɛs         0.281250   0.140625
109 abandonner ai1S abɑ̃dɔnɛ     0.500000   0.250000
114 abandonner pP   abɑ̃dɔnɑ̃    0.125000   0.062500

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          182.965882  91.482941
67  abaisser   pi3S abɛs         0.140625   0.070312
109 abandonner ai1S abɑ̃dɔnɛ     1.250000   0.625000
114 abandonner pP   abɑ̃dɔnɑ̃    0.062500   0.031250
125 abandonner pi1S abɑ̃dɔn      0.016136   0.008068

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          173.482941  86.741471
67  abaisser   pi3S abɛs         0.070312   0.035156
109 abandonner ai1S abɑ̃dɔnɛ     0.625000   0.312500
114 abandonner pP   abɑ̃dɔnɑ̃    0.031250   0.015625
125 abandonner pi1S abɑ̃dɔn      0.008068   0.004034

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          171.741471  85.870735
67  abaisser   pi3S abɛs         0.035156   0.017578
109 abandonner ai1S abɑ̃dɔnɛ     0.312500   0.156250
114 abandonner pP   abɑ̃dɔnɑ̃    0.015625   0.007812
128 abandonner pi3S abɑ̃dɔn      0.034821   0.017410

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          175.870735  87.935368
67  abaisser   pi3S abɛs         0.017578   0.008789
109 abandonner ai1S abɑ̃dɔnɛ     0.156250   0.078125
114 abandonner pP   abɑ̃dɔnɑ̃    0.007812   0.003906
128 abandonner pi3S abɑ̃dɔn      0.017410   0.008705

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         182.935368  91.467684
67  abaisser   pi3S abɛs        0.008789   0.004395
109 abandonner ai1S abɑ̃dɔnɛ    0.078125   0.039062
128 abandonner pi3S abɑ̃dɔn     1.008705   0.504353
132 abandonner inf  abɑ̃dɔne    1.517104   0.758552

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         171.467684  85.733842
109 abandonner ai1S abɑ̃dɔnɛ    0.039062   0.019531
113 abandonner ii3S abɑ̃dɔnɛ    1.000000   0.500000
128 abandonner pi3S abɑ̃dɔn     1.504353   0.752176
132 abandonner inf  abɑ̃dɔne    0.758552   0.379276

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         166.733842  83.366921
109 abandonner ai1S abɑ̃dɔnɛ    0.019531   0.009766
113 abandonner ii3S abɑ̃dɔnɛ    0.500000   0.250000
128 abandonner pi3S abɑ̃dɔn     0.752176   0.376088
132 abandonner inf  abɑ̃dɔne    0.379276   0.189638

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         198.366921  99.183460
45  abaisser   ai3S abɛsa       1.000000   0.500000
52  abaisser   pP   abɛsɑ̃      1.000000   0.500000
109 abandonner ai1S abɑ̃dɔnɛ    0.009766   0.004883
113 abandonner ii3S abɑ̃dɔnɛ    0.250000   0.125000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         187.183460  93.591730
45  abaisser   ai3S abɛsa       0.500000   0.250000
52  abaisser   pP   abɛsɑ̃      0.500000   0.250000
109 abandonner ai1S abɑ̃dɔnɛ    1.004883   0.502441
113 abandonner ii3S abɑ̃dɔnɛ    0.125000   0.062500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         179.591730  89.795865
45  abaisser   ai3S abɛsa       0.250000   0.125000
52  abaisser   pP   abɛsɑ̃      0.250000   0.125000
109 abandonner ai1S abɑ̃dɔnɛ    0.502441   0.251221
113 abandonner ii3S abɑ̃dɔnɛ    0.062500   0.031250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         164.795865  82.397933
45  abaisser   ai3S abɛsa       0.125000   0.062500
52  abaisser   pP   abɛsɑ̃      0.125000   0.062500
109 abandonner ai1S abɑ̃dɔnɛ    0.251221   0.125610
113 abandonner ii3S abɑ̃dɔnɛ    0.031250   0.015625

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         175.397933  87.698966
45  abaisser   ai3S abɛsa       0.062500   0.031250
52  abaisser   pP   abɛsɑ̃      0.062500   0.031250
109 abandonner ai1S abɑ̃dɔnɛ    0.125610   0.062805
110 abandonner ii3P abɑ̃dɔnɛ    1.000000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         161.698966  80.849483
45  abaisser   ai3S abɛsa       0.031250   0.015625
52  abaisser   pP   abɛsɑ̃      0.031250   0.015625
101 abaisser   ppMS abɛse       1.000000   0.500000
109 abandonner ai1S abɑ̃dɔnɛ    0.062805   0.031403

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         154.849483  77.424742
45  abaisser   ai3S abɛsa       0.015625   0.007812
52  abaisser   pP   abɛsɑ̃      0.015625   0.007812
101 abaisser   ppMS abɛse       0.500000   0.250000
109 abandonner ai1S abɑ̃dɔnɛ    0.031403   0.015701

                                tir1       tir2
    lexeme   case phono
40  avoir    pi3S a       168.424742  84.212371
45  abaisser ai3S abɛsa     0.007812   0.003906
50  abaisser ii3S abɛsɛ     1.000000   0.500000
52  abaisser pP   abɛsɑ̃    0.007812   0.003906
101 abaisser ppMS abɛse     0.250000   0.125000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         159.212371  79.606185
50  abaisser   ii3S abɛsɛ       0.500000   0.250000
101 abaisser   ppMS abɛse       0.125000   0.062500
108 abandonner ai3S abɑ̃dɔna    0.500000   0.250000
109 abandonner ai1S abɑ̃dɔnɛ    0.007851   0.003925

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         155.606185  77.803093
50  abaisser   ii3S abɛsɛ       0.250000   0.125000
101 abaisser   ppMS abɛse       0.062500   0.031250
108 abandonner ai3S abɑ̃dɔna    0.250000   0.125000
110 abandonner ii3P abɑ̃dɔnɛ    0.031250   0.015625

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         155.803093  77.901546
50  abaisser   ii3S abɛsɛ       0.125000   0.062500
101 abaisser   ppMS abɛse       0.031250   0.015625
108 abandonner ai3S abɑ̃dɔna    1.125000   0.562500
110 abandonner ii3P abɑ̃dɔnɛ    0.015625   0.007812

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         168.901546  84.450773
50  abaisser   ii3S abɛsɛ       0.062500   0.031250
101 abaisser   ppMS abɛse       0.015625   0.007812
108 abandonner ai3S abɑ̃dɔna    0.562500   0.281250
110 abandonner ii3P abɑ̃dɔnɛ    0.007812   0.003906

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         170.450773  85.225387
45  abaisser   ai3S abɛsa       1.000000   0.500000
50  abaisser   ii3S abɛsɛ       0.031250   0.015625
101 abaisser   ppMS abɛse       0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna    0.281250   0.140625

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         167.225387  83.612693
45  abaisser   ai3S abɛsa       0.500000   0.250000
50  abaisser   ii3S abɛsɛ       0.015625   0.007812
74  abaisser   fi3S abɛsəʁa     1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna    0.140625   0.070312

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         171.612693  85.806347
45  abaisser   ai3S abɛsa       0.250000   0.125000
50  abaisser   ii3S abɛsɛ       0.007812   0.003906
74  abaisser   fi3S abɛsəʁa     0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna    1.070312   0.535156

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          171.806347  85.903173
45  abaisser   ai3S abɛsa        0.125000   0.062500
74  abaisser   fi3S abɛsəʁa      0.250000   0.125000
108 abandonner ai3S abɑ̃dɔna     0.535156   0.267578
114 abandonner pP   abɑ̃dɔnɑ̃    0.062500   0.031250

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          181.903173  90.951587
45  abaisser   ai3S abɛsa        0.062500   0.031250
74  abaisser   fi3S abɛsəʁa      0.125000   0.062500
108 abandonner ai3S abɑ̃dɔna     0.267578   0.133789
114 abandonner pP   abɑ̃dɔnɑ̃    0.031250   0.015625

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         178.951587  89.475793
45  abaisser   ai3S abɛsa       0.031250   0.015625
52  abaisser   pP   abɛsɑ̃      1.000000   0.500000
74  abaisser   fi3S abɛsəʁa     0.062500   0.031250
108 abandonner ai3S abɑ̃dɔna    0.133789   0.066895

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         174.475793  87.237897
45  abaisser   ai3S abɛsa       0.015625   0.007812
52  abaisser   pP   abɛsɑ̃      0.500000   0.250000
74  abaisser   fi3S abɛsəʁa     0.031250   0.015625
108 abandonner ai3S abɑ̃dɔna    0.066895   0.033447

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         173.237897  86.618948
45  abaisser   ai3S abɛsa       0.007812   0.003906
52  abaisser   pP   abɛsɑ̃      0.250000   0.125000
74  abaisser   fi3S abɛsəʁa     0.015625   0.007812
108 abandonner ai3S abɑ̃dɔna    0.033447   0.016724

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          183.618948  91.809474
52  abaisser   pP   abɛsɑ̃       0.125000   0.062500
74  abaisser   fi3S abɛsəʁa      0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna     0.016724   0.008362
114 abandonner pP   abɑ̃dɔnɑ̃    1.126953   0.563477

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         198.809474  99.404737
52  abaisser   pP   abɛsɑ̃      0.062500   0.031250
67  abaisser   pi3S abɛs        1.000000   0.500000
102 abaisser   ppFS abɛse       1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna    0.008362   0.004181

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         171.404737  85.702369
52  abaisser   pP   abɛsɑ̃      0.031250   0.015625
67  abaisser   pi3S abɛs        0.500000   0.250000
102 abaisser   ppFS abɛse       0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         166.702369  83.351184
52  abaisser   pP   abɛsɑ̃      0.015625   0.007812
67  abaisser   pi3S abɛs        0.250000   0.125000
102 abaisser   ppFS abɛse       0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ    0.250000   0.125000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         173.351184  86.675592
52  abaisser   pP   abɛsɑ̃      0.007812   0.003906
67  abaisser   pi3S abɛs        0.125000   0.062500
102 abaisser   ppFS abɛse       0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ    0.125000   0.062500

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          165.675592  82.837796
67  abaisser   pi3S abɛs         0.062500   0.031250
102 abaisser   ppFS abɛse        0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ     0.062500   0.031250
114 abandonner pP   abɑ̃dɔnɑ̃    0.035217   0.017609

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          179.837796  89.918898
67  abaisser   pi3S abɛs         0.031250   0.015625
102 abaisser   ppFS abɛse        0.031250   0.015625
113 abandonner ii3S abɑ̃dɔnɛ     0.031250   0.015625
114 abandonner pP   abɑ̃dɔnɑ̃    0.017609   0.008804

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          164.918898  82.459449
67  abaisser   pi3S abɛs         0.015625   0.007812
102 abaisser   ppFS abɛse        0.015625   0.007812
113 abandonner ii3S abɑ̃dɔnɛ     0.015625   0.007812
114 abandonner pP   abɑ̃dɔnɑ̃    0.008804   0.004402

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         159.459449  79.729725
67  abaisser   pi3S abɛs        0.007812   0.003906
102 abaisser   ppFS abɛse       0.007812   0.003906
113 abandonner ii3S abɑ̃dɔnɛ    0.007812   0.003906
125 abandonner pi1S abɑ̃dɔn     0.754883   0.377441

                                      tir1       tir2
    lexeme     case phono
40  avoir      pi3S a           153.729725  76.864862
125 abandonner pi1S abɑ̃dɔn       0.377441   0.188721
128 abandonner pi3S abɑ̃dɔn       1.008374   0.504187
132 abandonner inf  abɑ̃dɔne      0.581101   0.290550
134 abandonner fi1S abɑ̃dɔnəʁɛ    1.250000   0.625000

                                      tir1       tir2
    lexeme     case phono
40  avoir      pi3S a           149.864862  74.932431
125 abandonner pi1S abɑ̃dɔn       0.188721   0.094360
128 abandonner pi3S abɑ̃dɔn       1.504187   0.752094
132 abandonner inf  abɑ̃dɔne      1.290550   0.645275
134 abandonner fi1S abɑ̃dɔnəʁɛ    0.625000   0.312500

                                      tir1       tir2
    lexeme     case phono
40  avoir      pi3S a           158.932431  79.466216
125 abandonner pi1S abɑ̃dɔn       0.094360   0.047180
128 abandonner pi3S abɑ̃dɔn       0.752094   0.376047
132 abandonner inf  abɑ̃dɔne      0.645275   0.322638
134 abandonner fi1S abɑ̃dɔnəʁɛ    0.312500   0.156250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         159.466216  79.733108
71  abaisser   pi3P abɛs        1.000000   0.500000
125 abandonner pi1S abɑ̃dɔn     1.047180   0.523590
128 abandonner pi3S abɑ̃dɔn     1.376047   0.688023
132 abandonner inf  abɑ̃dɔne    1.322638   0.661319

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         163.733108  81.866554
71  abaisser   pi3P abɛs        0.500000   0.250000
125 abandonner pi1S abɑ̃dɔn     0.523590   0.261795
128 abandonner pi3S abɑ̃dɔn     0.688023   0.344012
132 abandonner inf  abɑ̃dɔne    0.661319   0.330659

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         173.866554  86.933277
71  abaisser   pi3P abɛs        0.250000   0.125000
111 abandonner ii1S abɑ̃dɔnɛ    1.000000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ    1.000000   0.500000
125 abandonner pi1S abɑ̃dɔn     0.261795   0.130898

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         176.933277  88.466638
71  abaisser   pi3P abɛs        0.125000   0.062500
101 abaisser   ppMS abɛse       1.000000   0.500000
111 abandonner ii1S abɑ̃dɔnɛ    0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         182.466638  91.233319
71  abaisser   pi3P abɛs        0.062500   0.031250
101 abaisser   ppMS abɛse       0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna    1.000000   0.500000
109 abandonner ai1S abɑ̃dɔnɛ    1.000000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         180.233319  90.116660
71  abaisser   pi3P abɛs        0.031250   0.015625
101 abaisser   ppMS abɛse       0.250000   0.125000
108 abandonner ai3S abɑ̃dɔna    0.500000   0.250000
109 abandonner ai1S abɑ̃dɔnɛ    0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         174.116660  87.058330
71  abaisser   pi3P abɛs        0.015625   0.007812
101 abaisser   ppMS abɛse       0.125000   0.062500
108 abandonner ai3S abɑ̃dɔna    0.250000   0.125000
109 abandonner ai1S abɑ̃dɔnɛ    0.250000   0.125000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         159.058330  79.529165
71  abaisser   pi3P abɛs        0.007812   0.003906
101 abaisser   ppMS abɛse       0.062500   0.031250
108 abandonner ai3S abɑ̃dɔna    0.125000   0.062500
109 abandonner ai1S abɑ̃dɔnɛ    0.125000   0.062500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         145.529165  72.764582
45  abaisser   ai3S abɛsa       1.000000   0.500000
101 abaisser   ppMS abɛse       0.031250   0.015625
108 abandonner ai3S abɑ̃dɔna    0.062500   0.031250
109 abandonner ai1S abɑ̃dɔnɛ    0.062500   0.031250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         162.764582  81.382291
45  abaisser   ai3S abɛsa       0.500000   0.250000
101 abaisser   ppMS abɛse       0.015625   0.007812
108 abandonner ai3S abɑ̃dɔna    0.031250   0.015625
109 abandonner ai1S abɑ̃dɔnɛ    0.031250   0.015625

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         182.382291  91.191146
45  abaisser   ai3S abɛsa       0.250000   0.125000
73  abaisser   inf  abɛse       1.000000   0.500000
101 abaisser   ppMS abɛse       0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna    0.015625   0.007812

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         172.191146  86.095573
45  abaisser   ai3S abɛsa       0.125000   0.062500
73  abaisser   inf  abɛse       1.500000   0.750000
108 abandonner ai3S abɑ̃dɔna    0.007812   0.003906
109 abandonner ai1S abɑ̃dɔnɛ    0.507812   0.253906

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         166.095573  83.047786
45  abaisser   ai3S abɛsa       0.062500   0.031250
73  abaisser   inf  abɛse       0.750000   0.375000
109 abandonner ai1S abɑ̃dɔnɛ    0.253906   0.126953
113 abandonner ii3S abɑ̃dɔnɛ    0.063477   0.031738

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         170.047786  85.023893
45  abaisser   ai3S abɛsa       0.031250   0.015625
73  abaisser   inf  abɛse       0.375000   0.187500
109 abandonner ai1S abɑ̃dɔnɛ    0.126953   0.063477
113 abandonner ii3S abɑ̃dɔnɛ    0.031738   0.015869

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         181.023893  90.511947
45  abaisser   ai3S abɛsa       0.015625   0.007812
64  abaisser   pi1S abɛs        1.000000   0.500000
73  abaisser   inf  abɛse       0.187500   0.093750
109 abandonner ai1S abɑ̃dɔnɛ    0.063477   0.031738

                               tir1       tir2
   lexeme   case phono
40 avoir    pi3S a       189.511947  94.755973
45 abaisser ai3S abɛsa     0.007812   0.003906
52 abaisser pP   abɛsɑ̃    1.000000   0.500000
64 abaisser pi1S abɛs      0.500000   0.250000
73 abaisser inf  abɛse     0.093750   0.046875

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         180.755973  90.377987
52  abaisser   pP   abɛsɑ̃      0.500000   0.250000
64  abaisser   pi1S abɛs        0.250000   0.125000
73  abaisser   inf  abɛse       0.046875   0.023438
109 abandonner ai1S abɑ̃dɔnɛ    0.015869   0.007935

                                tir1       tir2
    lexeme   case phono
40  avoir    pi3S a       173.377987  86.688993
52  abaisser pP   abɛsɑ̃    0.250000   0.125000
64  abaisser pi1S abɛs      0.125000   0.062500
73  abaisser inf  abɛse     0.023438   0.011719
101 abaisser ppMS abɛse     1.000000   0.500000

                                tir1       tir2
    lexeme   case phono
40  avoir    pi3S a       177.688993  88.844497
52  abaisser pP   abɛsɑ̃    0.125000   0.062500
64  abaisser pi1S abɛs      0.062500   0.031250
73  abaisser inf  abɛse     0.011719   0.005859
101 abaisser ppMS abɛse     0.500000   0.250000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         171.844497  85.922248
52  abaisser   pP   abɛsɑ̃      0.062500   0.031250
64  abaisser   pi1S abɛs        0.031250   0.015625
101 abaisser   ppMS abɛse       0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ    1.000000   0.500000

                                tir1       tir2
    lexeme   case phono
40  avoir    pi3S a       163.922248  81.961124
50  abaisser ii3S abɛsɛ     1.000000   0.500000
52  abaisser pP   abɛsɑ̃    0.031250   0.015625
64  abaisser pi1S abɛs      0.015625   0.007812
101 abaisser ppMS abɛse     0.125000   0.062500

                               tir1       tir2
   lexeme   case phono
40 avoir    pi3S a       170.961124  85.480562
50 abaisser ii3S abɛsɛ     0.500000   0.250000
52 abaisser pP   abɛsɑ̃    0.015625   0.007812
64 abaisser pi1S abɛs      0.007812   0.003906
67 abaisser pi3S abɛs      1.000000   0.500000

                               tir1       tir2
   lexeme   case phono
40 avoir    pi3S a       173.480562  86.740281
45 abaisser ai3S abɛsa     1.000000   0.500000
50 abaisser ii3S abɛsɛ     0.250000   0.125000
52 abaisser pP   abɛsɑ̃    0.007812   0.003906
67 abaisser pi3S abɛs      0.500000   0.250000

                              tir1       tir2
   lexeme   case phono
40 avoir    pi3S a      163.740281  81.870141
45 abaisser ai3S abɛsa    0.500000   0.250000
50 abaisser ii3S abɛsɛ    0.125000   0.062500
67 abaisser pi3S abɛs     0.250000   0.125000
90 abaisser pi2P abɛse    0.500000   0.250000

                              tir1      tir2
   lexeme   case phono
40 avoir    pi3S a      169.870141  84.93507
45 abaisser ai3S abɛsa    0.250000   0.12500
50 abaisser ii3S abɛsɛ    0.062500   0.03125
67 abaisser pi3S abɛs     0.125000   0.06250
90 abaisser pi2P abɛse    0.250000   0.12500

                             tir1       tir2
   lexeme   case phono
40 avoir    pi3S a      152.93507  76.467535
45 abaisser ai3S abɛsa    0.12500   0.062500
46 abaisser ai1S abɛsɛ    1.00000   0.500000
50 abaisser ii3S abɛsɛ    1.03125   0.515625
67 abaisser pi3S abɛs     0.06250   0.031250

                              tir1       tir2
   lexeme   case phono
40 avoir    pi3S a      164.467535  82.233768
45 abaisser ai3S abɛsa    0.062500   0.031250
46 abaisser ai1S abɛsɛ    0.500000   0.250000
50 abaisser ii3S abɛsɛ    0.515625   0.257812
67 abaisser pi3S abɛs     0.031250   0.015625

                              tir1       tir2
   lexeme   case phono
40 avoir    pi3S a      168.233768  84.116884
45 abaisser ai3S abɛsa    0.031250   0.015625
46 abaisser ai1S abɛsɛ    0.250000   0.125000
50 abaisser ii3S abɛsɛ    0.257812   0.128906
67 abaisser pi3S abɛs     0.015625   0.007812

                              tir1       tir2
   lexeme   case phono
40 avoir    pi3S a      176.116884  88.058442
45 abaisser ai3S abɛsa    0.015625   0.007812
46 abaisser ai1S abɛsɛ    0.125000   0.062500
50 abaisser ii3S abɛsɛ    0.128906   0.064453
67 abaisser pi3S abɛs     0.007812   0.003906

                              tir1       tir2
   lexeme   case phono
40 avoir    pi3S a      176.058442  88.029221
45 abaisser ai3S abɛsa    0.007812   0.003906
46 abaisser ai1S abɛsɛ    0.062500   0.031250
50 abaisser ii3S abɛsɛ    0.064453   0.032227
90 abaisser pi2P abɛse    0.007812   0.003906

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         172.029221  86.014610
46  abaisser   ai1S abɛsɛ       0.031250   0.015625
50  abaisser   ii3S abɛsɛ       0.032227   0.016113
108 abandonner ai3S abɑ̃dɔna    0.126953   0.063477
113 abandonner ii3S abɑ̃dɔnɛ    0.314941   0.157471

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         175.014610  87.507305
46  abaisser   ai1S abɛsɛ       0.015625   0.007812
50  abaisser   ii3S abɛsɛ       0.016113   0.008057
108 abandonner ai3S abɑ̃dɔna    0.063477   0.031738
113 abandonner ii3S abɑ̃dɔnɛ    0.157471   0.078735

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         166.507305  83.253653
46  abaisser   ai1S abɛsɛ       0.007812   0.003906
50  abaisser   ii3S abɛsɛ       0.008057   0.004028
108 abandonner ai3S abɑ̃dɔna    0.031738   0.015869
113 abandonner ii3S abɑ̃dɔnɛ    1.078735   0.539368

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          177.253653  88.626826
108 abandonner ai3S abɑ̃dɔna     0.015869   0.007935
113 abandonner ii3S abɑ̃dɔnɛ     0.539368   0.269684
114 abandonner pP   abɑ̃dɔnɑ̃    1.501953   0.750977
128 abandonner pi3S abɑ̃dɔn      1.094116   0.547058

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          192.626826  96.313413
50  abaisser   ii3S abɛsɛ        1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna     0.007935   0.003967
113 abandonner ii3S abɑ̃dɔnɛ     0.269684   0.134842
114 abandonner pP   abɑ̃dɔnɑ̃    0.750977   0.375488

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          195.313413  97.656707
50  abaisser   ii3S abɛsɛ        0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ     0.134842   0.067421
114 abandonner pP   abɑ̃dɔnɑ̃    0.375488   0.187744
128 abandonner pi3S abɑ̃dɔn      1.773529   0.886765

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          195.656707  97.828353
50  abaisser   ii3S abɛsɛ        0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ     0.067421   0.033710
114 abandonner pP   abɑ̃dɔnɑ̃    1.187744   0.593872
128 abandonner pi3S abɑ̃dɔn      0.886765   0.443382

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          182.828353  91.414177
50  abaisser   ii3S abɛsɛ        0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ     0.033710   0.016855
114 abandonner pP   abɑ̃dɔnɑ̃    0.593872   0.296936
128 abandonner pi3S abɑ̃dɔn      0.443382   0.221691

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          164.414177  82.207088
50  abaisser   ii3S abɛsɛ        0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ     0.016855   0.008428
114 abandonner pP   abɑ̃dɔnɑ̃    0.296936   0.148468
128 abandonner pi3S abɑ̃dɔn      0.221691   0.110846

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          171.207088  85.603544
50  abaisser   ii3S abɛsɛ        0.031250   0.015625
113 abandonner ii3S abɑ̃dɔnɛ     0.008428   0.004214
114 abandonner pP   abɑ̃dɔnɑ̃    0.148468   0.074234
125 abandonner pi1S abɑ̃dɔn      1.000000   0.500000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          178.603544  89.301772
50  abaisser   ii3S abɛsɛ        0.015625   0.007812
101 abaisser   ppMS abɛse        1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna     1.000000   0.500000
114 abandonner pP   abɑ̃dɔnɑ̃    0.074234   0.037117

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          173.301772  86.650886
50  abaisser   ii3S abɛsɛ        0.007812   0.003906
101 abaisser   ppMS abɛse        0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna     0.500000   0.250000
114 abandonner pP   abɑ̃dɔnɑ̃    0.037117   0.018559

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          169.650886  84.825443
101 abaisser   ppMS abɛse        0.250000   0.125000
108 abandonner ai3S abɑ̃dɔna     0.250000   0.125000
114 abandonner pP   abɑ̃dɔnɑ̃    0.018559   0.009279
125 abandonner pi1S abɑ̃dɔn      2.625000   1.312500

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          155.825443  77.912722
101 abaisser   ppMS abɛse        0.125000   0.062500
108 abandonner ai3S abɑ̃dɔna     0.125000   0.062500
114 abandonner pP   abɑ̃dɔnɑ̃    0.009279   0.004640
125 abandonner pi1S abɑ̃dɔn      1.312500   0.656250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         166.912722  83.456361
101 abaisser   ppMS abɛse       0.062500   0.031250
108 abandonner ai3S abɑ̃dɔna    1.062500   0.531250
111 abandonner ii1S abɑ̃dɔnɛ    1.000000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ    1.000000   0.500000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         164.456361  82.228180
101 abaisser   ppMS abɛse       0.031250   0.015625
108 abandonner ai3S abɑ̃dɔna    0.531250   0.265625
111 abandonner ii1S abɑ̃dɔnɛ    0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ    1.500000   0.750000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         196.228180  98.114090
101 abaisser   ppMS abɛse       0.015625   0.007812
108 abandonner ai3S abɑ̃dɔna    1.265625   0.632812
111 abandonner ii1S abɑ̃dɔnɛ    0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ    0.750000   0.375000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         171.114090  85.557045
101 abaisser   ppMS abɛse       0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna    0.632812   0.316406
111 abandonner ii1S abɑ̃dɔnɛ    0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ    0.375000   0.187500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         174.557045  87.278523
101 abaisser   ppMS abɛse       1.003906   0.501953
108 abandonner ai3S abɑ̃dɔna    0.316406   0.158203
111 abandonner ii1S abɑ̃dɔnɛ    0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ    0.187500   0.093750

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         173.278523  86.639261
101 abaisser   ppMS abɛse       0.501953   0.250977
108 abandonner ai3S abɑ̃dɔna    0.158203   0.079102
111 abandonner ii1S abɑ̃dɔnɛ    0.031250   0.015625
113 abandonner ii3S abɑ̃dɔnɛ    0.093750   0.046875

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         173.639261  86.819631
101 abaisser   ppMS abɛse       0.250977   0.125488
108 abandonner ai3S abɑ̃dɔna    0.079102   0.039551
111 abandonner ii1S abɑ̃dɔnɛ    0.015625   0.007812
113 abandonner ii3S abɑ̃dɔnɛ    0.046875   0.023438

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         167.819631  83.909815
101 abaisser   ppMS abɛse       0.125488   0.062744
108 abandonner ai3S abɑ̃dɔna    1.039551   0.519775
111 abandonner ii1S abɑ̃dɔnɛ    0.007812   0.003906
113 abandonner ii3S abɑ̃dɔnɛ    0.023438   0.011719

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          177.909815  88.954908
101 abaisser   ppMS abɛse        0.062744   0.031372
108 abandonner ai3S abɑ̃dɔna     0.519775   0.259888
113 abandonner ii3S abɑ̃dɔnɛ     0.011719   0.005859
114 abandonner pP   abɑ̃dɔnɑ̃    0.531250   0.265625

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          174.954908  87.477454
101 abaisser   ppMS abɛse        0.031372   0.015686
108 abandonner ai3S abɑ̃dɔna     0.259888   0.129944
114 abandonner pP   abɑ̃dɔnɑ̃    0.265625   0.132812
128 abandonner pi3S abɑ̃dɔn      0.586005   0.293003

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          166.477454  83.238727
101 abaisser   ppMS abɛse        0.015686   0.007843
108 abandonner ai3S abɑ̃dɔna     1.129944   0.564972
114 abandonner pP   abɑ̃dɔnɑ̃    0.132812   0.066406
128 abandonner pi3S abɑ̃dɔn      1.293003   0.646501

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          154.238727  77.119363
101 abaisser   ppMS abɛse        0.007843   0.003922
108 abandonner ai3S abɑ̃dɔna     0.564972   0.282486
114 abandonner pP   abɑ̃dɔnɑ̃    0.066406   0.033203
128 abandonner pi3S abɑ̃dɔn      0.646501   0.323251

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          149.119363  74.559682
108 abandonner ai3S abɑ̃dɔna     0.282486   0.141243
109 abandonner ai1S abɑ̃dɔnɛ     1.000000   0.500000
113 abandonner ii3S abɑ̃dɔnɛ     2.000000   1.000000
114 abandonner pP   abɑ̃dɔnɑ̃    0.033203   0.016602

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          164.559682  82.279841
108 abandonner ai3S abɑ̃dɔna     0.141243   0.070621
109 abandonner ai1S abɑ̃dɔnɛ     0.500000   0.250000
113 abandonner ii3S abɑ̃dɔnɛ     1.000000   0.500000
114 abandonner pP   abɑ̃dɔnɑ̃    0.016602   0.008301

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          172.279841  86.139920
108 abandonner ai3S abɑ̃dɔna     0.070621   0.035311
109 abandonner ai1S abɑ̃dɔnɛ     0.250000   0.125000
113 abandonner ii3S abɑ̃dɔnɛ     0.500000   0.250000
114 abandonner pP   abɑ̃dɔnɑ̃    0.008301   0.004150

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         169.139920  84.569960
67  abaisser   pi3S abɛs        1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna    0.035311   0.017655
109 abandonner ai1S abɑ̃dɔnɛ    0.125000   0.062500
113 abandonner ii3S abɑ̃dɔnɛ    0.250000   0.125000

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         174.569960  87.284980
67  abaisser   pi3S abɛs        0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna    1.017655   0.508828
109 abandonner ai1S abɑ̃dɔnɛ    0.062500   0.031250
113 abandonner ii3S abɑ̃dɔnɛ    0.125000   0.062500

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         183.284980  91.642490
67  abaisser   pi3S abɛs        0.250000   0.125000
108 abandonner ai3S abɑ̃dɔna    0.508828   0.254414
109 abandonner ai1S abɑ̃dɔnɛ    0.031250   0.015625
113 abandonner ii3S abɑ̃dɔnɛ    1.062500   0.531250

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         176.642490  88.321245
67  abaisser   pi3S abɛs        0.125000   0.062500
108 abandonner ai3S abɑ̃dɔna    0.254414   0.127207
109 abandonner ai1S abɑ̃dɔnɛ    0.015625   0.007812
113 abandonner ii3S abɑ̃dɔnɛ    0.531250   0.265625

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         176.321245  88.160623
64  abaisser   pi1S abɛs        1.000000   0.500000
67  abaisser   pi3S abɛs        0.062500   0.031250
108 abandonner ai3S abɑ̃dɔna    0.127207   0.063603
109 abandonner ai1S abɑ̃dɔnɛ    0.007812   0.003906

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         167.160623  83.580311
64  abaisser   pi1S abɛs        0.500000   0.250000
67  abaisser   pi3S abɛs        0.031250   0.015625
73  abaisser   inf  abɛse       1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna    0.063603   0.031802

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         170.580311  85.290156
64  abaisser   pi1S abɛs        0.250000   0.125000
67  abaisser   pi3S abɛs        0.015625   0.007812
73  abaisser   inf  abɛse       0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna    0.031802   0.015901

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         159.290156  79.645078
64  abaisser   pi1S abɛs        0.125000   0.062500
67  abaisser   pi3S abɛs        0.007812   0.003906
73  abaisser   inf  abɛse       0.250000   0.125000
108 abandonner ai3S abɑ̃dɔna    0.015901   0.007950

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         174.645078  87.322539
64  abaisser   pi1S abɛs        0.062500   0.031250
73  abaisser   inf  abɛse       0.125000   0.062500
108 abandonner ai3S abɑ̃dɔna    1.007950   0.503975
109 abandonner ai1S abɑ̃dɔnɛ    0.125488   0.062744

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         164.322539  82.161269
64  abaisser   pi1S abɛs        0.031250   0.015625
73  abaisser   inf  abɛse       0.062500   0.031250
108 abandonner ai3S abɑ̃dɔna    0.503975   0.251988
109 abandonner ai1S abɑ̃dɔnɛ    0.062744   0.031372

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         171.161269  85.580635
64  abaisser   pi1S abɛs        0.015625   0.007812
73  abaisser   inf  abɛse       0.031250   0.015625
108 abandonner ai3S abɑ̃dɔna    1.251988   0.625994
109 abandonner ai1S abɑ̃dɔnɛ    0.031372   0.015686

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         181.580635  90.790317
64  abaisser   pi1S abɛs        0.007812   0.003906
73  abaisser   inf  abɛse       0.015625   0.007812
108 abandonner ai3S abɑ̃dɔna    1.625994   0.812997
109 abandonner ai1S abɑ̃dɔnɛ    0.015686   0.007843

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          169.790317  84.895159
73  abaisser   inf  abɛse        0.007812   0.003906
108 abandonner ai3S abɑ̃dɔna     0.812997   0.406498
109 abandonner ai1S abɑ̃dɔnɛ     0.007843   0.003922
114 abandonner pP   abɑ̃dɔnɑ̃    1.531250   0.765625

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          170.895159  85.447579
73  abaisser   inf  abɛse        1.003906   0.501953
108 abandonner ai3S abɑ̃dɔna     0.406498   0.203249
114 abandonner pP   abɑ̃dɔnɑ̃    0.765625   0.382812
125 abandonner pi1S abɑ̃dɔn      0.250000   0.125000

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          169.447579  84.723790
45  abaisser   ai3S abɛsa        1.000000   0.500000
73  abaisser   inf  abɛse        0.501953   0.250977
108 abandonner ai3S abɑ̃dɔna     1.203249   0.601625
114 abandonner pP   abɑ̃dɔnɑ̃    0.382812   0.191406

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          187.723790  93.861895
45  abaisser   ai3S abɛsa        0.500000   0.250000
73  abaisser   inf  abɛse        0.250977   0.125488
108 abandonner ai3S abɑ̃dɔna     0.601625   0.300812
114 abandonner pP   abɑ̃dɔnɑ̃    0.191406   0.095703

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          177.861895  88.930947
45  abaisser   ai3S abɛsa        0.250000   0.125000
73  abaisser   inf  abɛse        0.125488   0.062744
108 abandonner ai3S abɑ̃dɔna     0.300812   0.150406
114 abandonner pP   abɑ̃dɔnɑ̃    0.095703   0.047852

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          177.930947  88.965474
45  abaisser   ai3S abɛsa        0.125000   0.062500
73  abaisser   inf  abɛse        0.062744   0.031372
108 abandonner ai3S abɑ̃dɔna     1.150406   0.575203
114 abandonner pP   abɑ̃dɔnɑ̃    0.047852   0.023926

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          175.965474  87.982737
45  abaisser   ai3S abɛsa        0.062500   0.031250
73  abaisser   inf  abɛse        0.031372   0.015686
108 abandonner ai3S abɑ̃dɔna     0.575203   0.287602
114 abandonner pP   abɑ̃dɔnɑ̃    0.023926   0.011963

                                     tir1       tir2
    lexeme     case phono
40  avoir      pi3S a          185.982737  92.991368
45  abaisser   ai3S abɛsa        0.031250   0.015625
73  abaisser   inf  abɛse        0.015686   0.007843
108 abandonner ai3S abɑ̃dɔna     0.287602   0.143801
114 abandonner pP   abɑ̃dɔnɑ̃    0.011963   0.005981

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         170.991368  85.495684
45  abaisser   ai3S abɛsa       0.015625   0.007812
73  abaisser   inf  abɛse       0.007843   0.003922
102 abaisser   ppFS abɛse       1.000000   0.500000
108 abandonner ai3S abɑ̃dɔna    0.143801   0.071900

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         172.495684  86.247842
45  abaisser   ai3S abɛsa       0.007812   0.003906
102 abaisser   ppFS abɛse       0.500000   0.250000
108 abandonner ai3S abɑ̃dɔna    0.071900   0.035950
128 abandonner pi3S abɑ̃dɔn     0.723756   0.361878

                                    tir1       tir2
    lexeme     case phono
40  avoir      pi3S a         175.247842  87.623921
102 abaisser   ppFS abɛse       0.250000   0.125000
108 abandonner ai3S abɑ̃dɔna    0.035950   0.017975
113 abandonner ii3S abɑ̃dɔnɛ    1.000000   0.500000
128 abandonner pi3S abɑ̃dɔn     0.361878   0.180939